### ISSUE TITLE
5 Pokemon of ~50

### ISSUE THREAD

**Issue by Nerdcoat** [mchristopher/PokemonGo-DesktopMap#10]
Its an amazing project, but it just showed 5 different pokemons of ~50 after 5 minutes.
Any idea?

**Comment by ilikesomething** [comment]
what do you mean ?

**Comment by Nerdcoat** [comment]
It shows not every pokemon which is around. 
Actually the next is 2 streets away, the game showed me 9 different in my street.

**Comment by BohdanPozharskyi** [comment]
@Nerdcoat they might spawn before you refreshed the map
