### ISSUE TITLE
0.3.2 no map is loading

### ISSUE THREAD

**Issue by Thyrant** [mchristopher/PokemonGo-DesktopMap#1002]
Hi there,
when i start the 0.3.2 there is no map loading the status shows "operational"
When i start the app 0.2.1 the map is loading but staus is "waiting"

Account isnt ban

Both apps (0.2.1 and 0.3.2 are in same folder C:\Users\current user\AppData\Local\pokemon)

**Comment by Mikey1981** [comment]
OK, so this is the same issue I had. I have found the fix and it is with your Google API Key. You need to generate a new Google API Key, not sure if PokemonGo/Niantic has started banning these keys. Just go create a new API Key and everything should be up and running normally again. This worked for me.

**Comment by Rockymin** [comment]
I have the issue as well.  The map just shows a white screen on the desktop.  However, it still works fine after I turn mobile on and load it on both my phone and tablet.  Are you sure it's the key?

**Comment by Thyrant** [comment]
I tried the mobile share, and yes, it works on mobil, but still a white screen on desktop

**Comment by Thyrant** [comment]
This works fpr me
[https://github.com/mchristopher/PokemonGo-DesktopMap/issues/1017](#1017)
