### ISSUE TITLE
0.3.2 not working?

### ISSUE THREAD

**Issue by Inrego** [mchristopher/PokemonGo-DesktopMap#1003]
It isn't scanning any areas, and after a while it says "possible ban". I am sure that the account isn't banned.

**Comment by baer1** [comment]
same here. i just created a new account and it isnt working too.

**Comment by Mikey1981** [comment]
OK, so this is the same issue I had. I have found the fix and it is with your Google API Key. You need to generate a new Google API Key, not sure if PokemonGo/Niantic has started banning these keys. Just go create a new API Key and everything should be up and running normally again. This worked for me.

**Comment by baer1** [comment]
new api key doesnt work for me.

**Comment by baer1** [comment]
okay it works now. my 1. account i ever used doenst work anymore. seems to be banned. the second account i have created today is working after i was catching one of the initial pokemon and gave a nickname to the account.
