### ISSUE TITLE
0.3.2

### ISSUE THREAD

**Issue by Stormkitster** [mchristopher/PokemonGo-DesktopMap#1004]
Not liking the ptc login at all. just made a new account got my starter and all the right stuff done got it to come up without saying "waiting" then i just get a blank white map nothing showing up at all even though it says operational.

Running windows 10 fully update to the newest updates im not understanding why its not working minus ti get a javascript error upon opening the app up. please help.

**Comment by Mikey1981** [comment]
OK, so this is the same issue I had but with windows 7. I have found the fix and it is with your Google API Key. You need to generate a new Google API Key, not sure if PokemonGo/Niantic has started banning these keys. Just go create a new API Key and everything should be up and running normally again. This worked for me.

**Comment by TYKANT** [comment]
@Mikey1981 tried with a regenerated key. did not worked for me
