### ISSUE TITLE
UPGRADED JAVA - NOW MAP DOESN'T WORK

### ISSUE THREAD

**Issue by juliehedges** [mchristopher/PokemonGo-DesktopMap#1005]
I upgraded my Java for another program I use for work.  Now my map is not working at all.  I get this error when opening.
<img width="419" alt="pokemon map error" src="https://cloud.githubusercontent.com/assets/21193102/17886054/15b27772-68ee-11e6-972e-1bdd3dd68c1f.png">

**Comment by Mikey1981** [comment]
I have found the fix and it is with your Google API Key. You need to generate a new Google API Key, not sure if PokemonGo/Niantic has started banning these keys. Just go create a new API Key and everything should be up and running normally again. This worked for me.
![image](https://cloud.githubusercontent.com/assets/21193097/17886224/a275f184-68d5-11e6-8567-2707a7219f07.png)

**Comment by juliehedges** [comment]
Mikey, thank you for your quick response.  Well that solved the error message.  Unfortunately, my map is not scanning or updating at all.

**Comment by SPID3R31** [comment]
I've got the same issue! I've changed my google API KEY but the error message apear over and over!
