### ISSUE TITLE
Gym and Pokestop location

### ISSUE THREAD

**Issue by gauravyadav26** [mchristopher/PokemonGo-DesktopMap#1006]
Is there any way I can upload my gym and pokestop location to cloud, because as of now, my PC needs to be on and running the app then only I can get location on my mobile. I don't need pokemon information just gyms and pokestops.

**Comment by GeorgeGarman** [comment]
The SQLite db file is located:
C:\Users\[your username]\AppData\Roaming\pokemon-go-map\pogom.db
There are tables for "gym" and "pokestop". The tables contain latitude and longitude for each item.
