### ISSUE TITLE
Possible ban notification

### ISSUE THREAD

**Issue by dani-holland85** [mchristopher/PokemonGo-DesktopMap#1007]
Hey guys,

I updated Pokemon GO Live Map to 0.3.2 and now im getting the notification in the top of the screen "Possible Ban". When i log into my Pokemon Trainer Club I can still login without any ban notification. Has anyone any idea how to solve this?

Regards,

Daniel

**Comment by Isterius** [comment]
yup, me 2

**Comment by djstearns** [comment]
See issue 1023
