### ISSUE TITLE
0.3.2

### ISSUE THREAD

**Issue by SPID3R31** [mchristopher/PokemonGo-DesktopMap#1008]
HEY!

I've changed my google API KEY and now nothing hapened! I can see the map, "waiting" is dispaly during 2 min and then i've got Possible ban. If I change my API again, i can't see the map and i see waiting and later "possible ban"! HELP MMEEE :( (I'm french, sorry if I made any mistakes)

**Comment by lakeguy** [comment]
same here...made a new account (PTC) and created new API key. must be something higher up that is being blocked, IP or? tried VPN but that didn't work either.
