### ISSUE TITLE
how i .. -.-

### ISSUE THREAD

**Issue by ceyaira** [mchristopher/PokemonGo-DesktopMap#1009]
i like to log in with google ...unfortunately i missklick onetime on the ptc button . So google login is going away.
i installed new ..nothing happend i searched for File  like named  "Cache" ..found nothing ..
need help pls thx.

**Comment by hngouveia01** [comment]
Hi! Try to find the file 'config.json', there you will find a line with 'auth_service'.

Change it to google.
