### ISSUE TITLE
coordinate issue

### ISSUE THREAD

**Issue by dittowill** [mchristopher/PokemonGo-DesktopMap#101]
I'm still having the issue where its farther than the actual coordinates by a block or 2 off.

**Comment by ShawnHardwick** [comment]
Although it is personal information, if you can find an example coordinate and matching address that displays the issue, that would be great in replicating the issue.

**Comment by dittowill** [comment]
![pokemong](https://cloud.githubusercontent.com/assets/20570933/17041251/a724a2a6-4f59-11e6-93a9-5c7b7dbb8d33.png)
the black circle is the location of the coordinate but it shows the location to be different

**Comment by BohdanPozharskyi** [comment]
Encountered this problem twice today, in other cases everything worked well. So for now I got a workaround with storing my current location, since my pc won't move anyway.
