### ISSUE TITLE
0.3.2 on Raspberry Pi B+

### ISSUE THREAD

**Issue by nopejusttesting** [mchristopher/PokemonGo-DesktopMap#1011]
Can anyone write me a guide on how to run this new version on a Raspberry Pi B+ running raspbian?
Pretend i'm an idiot and have very little experience building from source.
I see Linux support has been dropped but hopefully someone can help me anyway.

**Comment by palkooo** [comment]
to run on a server, I would try this instead: https://github.com/PokemonGoMap/PokemonGo-Map
