### ISSUE TITLE
letting people know map works again here are 2 tips. good luck!

### ISSUE THREAD

**Issue by PokemongoGether** [mchristopher/PokemonGo-DesktopMap#1012]
update app through the app youll get a pop up saying update

change your ptc account make a new email(yahoo or anything not google obviously etc.

also attain new api with new email(google obviously) but dont associate it with anything good to go.

**Comment by PokemongoGether** [comment]
3 tips sorry lol tryibng to do my part :dancers:

**Comment by sjoerdsteen** [comment]
Unfortunately this method doesn't work for me, it keeps saying "Possible Ban". Any other suggestions?

**Comment by Xrecon420** [comment]
I logged in to my new PTC account and caught my first pokemon then it worked fine.

**Comment by sjoerdsteen** [comment]
Thanks guys! After the additional step Xrecon420 suggested the map works fine again.

**Comment by pocketq10** [comment]
i have the map up and running and it scanning...but there hasnt been any pokemon popping up, not even a pidgey. anyone else having this issue?

**Comment by SPID3R31** [comment]
Nope, search for hide pokémon...

**Comment by Lavicius** [comment]
i followed that 2 steps, and now my account is 'Operational', but map isn't loading.

In developer console this is appearing:

MAP: Uncaught TypeError: Cannot read property 'getBounds' of undefined
main.html:169 2016-08-23 14:45:22,799 [ search-worker-0][        search][    INFO] Searching at 39.506992,-0.363971

**Comment by furax187** [comment]
@Lavicius i have the same problem, did you update to the lastest version ? cause i havent yet.
Mine says also operational

**Comment by tutti13** [comment]
Just go to "C:\Users\USERNAME\AppData\Roaming" and delete the folder "pokemon-go-map". Should work.

**Comment by furax187** [comment]
ye i did that now, and i installed the latest version and now everything works

**Comment by drippybutt** [comment]
@tutti13 On windows 10, that folder doesnt exist for me

**Comment by colonelingus** [comment]
@drippybutt  for me in Windows 10 it was under "C:\Users\USERNAME\Roaming" after I deleted the Roaming folder it started working for me.

**Comment by pill0ws** [comment]
the AppData folder is a system folder, it maybe hidden.
