### ISSUE TITLE
Use 0.3.2 But can't run Multiple Windows?

### ISSUE THREAD

**Issue by DarkSilv3r** [mchristopher/PokemonGo-DesktopMap#1014]
Anyone with this problem as well? In 0.2.1 i could run the app a couple of times. Now it closes itself when i open the next appliance?

**Comment by madkeeper89** [comment]
with 0.3.2. multiple windows still work here. Using Windows7.

**Comment by jijetelu** [comment]
i can't also
sux

**Comment by DarkSilv3r** [comment]
Works now with me, but i don't know what it was that fixed it. I deleted all the files and tried again , then it worked :')

**Comment by jijetelu** [comment]
sux, no I just cannot get rid of 0.3.2 verzion
!!!!

**Comment by DarkSilv3r** [comment]
When i launchedthe 0.2.1 again, it asked me to update. Worked since then.

**Comment by GrodanFreeman** [comment]
I get all kinds of errors but it still seems to work when I run multiple instances.

**Comment by Butom** [comment]
at my PC win10 it doesnt work, all acc are on the same marker, if i drag them only one window scans, rest arent, any solutions?
