### ISSUE TITLE
solution ban

### ISSUE THREAD

**Issue by jwebdyp** [mchristopher/PokemonGo-DesktopMap#1015]
To avoid Ban just follow two steps:

1 - Create an account PTC
2 - Begin with the account created PokemonGo

Once the initial pokemon appear can start the map.

Greetings.

**Comment by SPID3R31** [comment]
Thanks guy <3

**Comment by dani-holland85** [comment]
Thats what i did last week, and that account seems to be banned right now

**Comment by ITP2AME** [comment]
same here fresh account is banned, my suggestion would be to change how the scanning works, using multiple accounts for each "step" because right now scanning works in a specific pattern which would be easy to find in their logs.

**Comment by lairmongomap1** [comment]
ok found it need to login with ptc not with google on pkemon go :)

**Comment by mdueck** [comment]
Thank you!! Jwebdyp, your solution worked for me.

I caught my starter pokemon with my dummy PTC account then also caught a pidgey for good measure. After this my desktop map said "operational" in the top middle, but nothing was happening. I logged back in about an hour later and everything works great again.
