### ISSUE TITLE
Map not showing

### ISSUE THREAD

**Issue by walshy415** [mchristopher/PokemonGo-DesktopMap#1017]
Program says it is operational but the map won't load and just shows the white screen below

**Comment by PJRay** [comment]
Same problem here. I had to revert all the way back to 0.2.1 before the map would show up. Using 0.3.2 just shows a white screen instead of the map.

**Comment by drippybutt** [comment]
When I am reverting back to 2.1 it isn't working for me anymore. Does your 2.1 work? Mine worked before I clicked on update, now nothing works at all.

**Comment by walshy415** [comment]
No my 2.1 is always stuck on waiting

**Comment by tutti13** [comment]
Just go to "C:\Users\USERNAME\AppData\Roaming" and delete the folder "pokemon-go-map". Should work.

**Comment by furax187** [comment]
i was using the version before the new one and i had also white screen and status operational.
I uninstalled pokemap go map, deleted the folder pokemon-go-map, downloaded the last version and installed that one and now everything works again

**Comment by drippybutt** [comment]
Furax, did you revert to 2.1 or are you using 3.2

**Comment by PJRay** [comment]
tutti13's suggestion of deleting the folder in AppData\Roaming fixed the problem for me. Now 0.3.3 works again.

**Comment by drippybutt** [comment]
@PJRay Where is this folder located on windows 10, that folder doesnt exist for me

**Comment by PJRay** [comment]
@drippybutt - it is in C:\Users\[username]\AppData\Roaming

But note that the AppData is hidden, so you'll have to turn on showing hidden folder. This is done like this: http://www.howtogeek.com/howto/windows-vista/show-hidden-files-and-folders-in-windows-vista/

**Comment by TYKANT** [comment]
@tutti13 deleting the folder did not worked for me. Still stuck in waiting.
