### ISSUE TITLE
MAP NOT WORKING!!!!!

### ISSUE THREAD

**Issue by shvoid** [mchristopher/PokemonGo-DesktopMap#1019]
I have created a new PTC account, a new email, and a new api and it is still not working.

**Comment by shvoid** [comment]
It just keeps saying possible ban....

**Comment by tinlar** [comment]
same issue;
New PTC on a new email address with a new Google code.

**Comment by shvoid** [comment]
I got it working, I had to actually log into the pokemon go with the new PTC account and catch a pokemon in order for it to work.

**Comment by sjoerdsteen** [comment]
Try to login to pokemon go with your new PTC account and catch a pokemon. After that login again to the pokemon go live map.
