### ISSUE TITLE
Can't drag pin in map

### ISSUE THREAD

**Issue by Arsar01** [mchristopher/PokemonGo-DesktopMap#1020]
I was able to drag the red pin to the location I wanted to scan but I'm now unable to do that. Is anyone else experiencing this? Is there anything I can do to fix it?

**Comment by sjoerdsteen** [comment]
Have you locked your marker? Go to options/location settings and disable "Lock Marker".

**Comment by germanocaumo** [comment]
Same thing here. Unable to drag pin on Mobile.

**Comment by Arsar01** [comment]
Sjoerdsteen, yup that was the problem, thank you. I hadn't noticed the new settings in the new update and it was locked by default.

Germanocaumo, it's what sjoerdsteen said, you have to disable the "lock marker"
