### ISSUE TITLE
Mapped Worked and now it doesnt load. after i created a new PTC Account and got a new API, but now the map doesnt load the screen stays white

### ISSUE THREAD

**Issue by MGRza** [mchristopher/PokemonGo-DesktopMap#1022]
Mapped Worked after i created a new PTC Account and got a new API, but now the map doesnt load the screen stays white.

**Comment by mastahpeo** [comment]
Delete the Pokemon folder form you AppData folder and try again. Should work. Did for me.

**Comment by drippybutt** [comment]
@mastahpeo Do you happen to know how to locate this folder on windows 10? I cant seem to locate that folder

**Comment by mastahpeo** [comment]
C:\Users\USERNAME\AppData\Roaming

If you can't see AppData you need to go to Folder Options and turn on Show Hidden Files/Folders.

**Comment by drippybutt** [comment]
@mastahpeo thanks, that took care of it

**Comment by MGRza** [comment]
Yeah that fixed worked, thanks a lot

**Comment by pill0ws** [comment]
bah, did that fix and apparently I wrote down the wrong password for my burner account. I backed up my previous AppData folder, does anyone know which file in there has the account info stored? is it just the cookie file?
