### ISSUE TITLE
Feature request: Omit empty scans beforehand

### ISSUE THREAD

**Issue by Spoetnic** [mchristopher/PokemonGo-DesktopMap#1025]
Awesome that you can now see the spawn locations, but this raises a question for me:

If you know that the next scan will not include any spawnpoints, why even scan there?
Wouldnt it be quicker to just omit these and move to the next (with a slightly longer delay to 'getThere'.

Looking forward to your thoughts :)

**Comment by Spoetnic** [comment]
Or are these spawnpoints only obtained after a initial scan?

**Comment by brianguy1** [comment]
I love this idea. Perhaps you could set it to ignore cells that don't have any spawns after x scans.  Given that we can't change the shape of the scan area, this would allow you to set a higher scan radius and still have the spawn locations scanned more frequently.

**Comment by mchristopher** [comment]
This is a feature that would be part of PokemonGo-Map, not this project. Please post an issue request on their GitHub: https://github.com/PokemonGoMap/PokemonGo-Map
