### ISSUE TITLE
Not able to show lured pokemon in version 0.3.2

### ISSUE THREAD

**Issue by patpatmon** [mchristopher/PokemonGo-DesktopMap#1026]
While it was possible in version 0.2.1. Any idea?

**Comment by Sedare** [comment]
Honestly, I didnt want to see them anyways, I use my scanner to map out spawn locations for later use, not to hunt currently spawned pokemons. I prefer to have these not showing up. :)

**Comment by blahblah3141** [comment]
Yes, I agree, this is slightly annoying. Overall this update has been a great improvement though

**Comment by PJRay** [comment]
I wonder if it is possible to have it as a setting?
