### ISSUE TITLE
Scan Setup

### ISSUE THREAD

**Issue by G0rzilla** [mchristopher/PokemonGo-DesktopMap#1028]
![scan](https://cloud.githubusercontent.com/assets/20774722/17900343/3bfe5862-695f-11e6-91f4-908f8e747184.jpg)

How can I make my scan do the same as this? And Who ever is using this scan maybe reply been trying to contact you.

**Comment by hibbovsky** [comment]
Hijacking the issue cause I also have a question about setup. Which .js file should I edit to make the marker hidden on default?

**Comment by Mirx** [comment]
Just enable spawn points under marker settings

**Comment by G0rzilla** [comment]
@Mirx those aren't spawn points that's how this guys one scans it doesn't do the bee hive scan

**Comment by Mirx** [comment]
I don't think you can from PokemonGo-DesktopMap, as you can't change the search command as far as I know.

If you would run PokemonGo-Map, you would first generate spawn point data by using a normal search, dump the spawn point database, and the give a different search command using the spawn points in the database to search.

It's only usefull if you have really big blindspots without spawnpoints, so I never bothered.

https://pgm.readthedocs.io/en/develop/extras/Spawnpoint-Scanning.html

**Comment by G0rzilla** [comment]
Thank you @Mirx wish I knew how he got all that spawn data then, wouldn't mind doing something like that in my area, this is how my poor scan looks :'( 
![scan me](https://cloud.githubusercontent.com/assets/20774722/17903729/cf6b410c-696c-11e6-8e37-9dabf44ad7af.jpg)

**Comment by Mirx** [comment]
It's all in the link. And 0.3.2 uses the latest pokomongo-map and datbase structure which will collect spawn data.

**Comment by G0rzilla** [comment]
@Mirx is it tough to install?

**Comment by Mirx** [comment]
That all depends on your level of IT knowledge :p I never did it because I'm lazy and like the desktopmap all in one package with all the dependencies included.

There are youtube videos available on how to install on windows, docker containers etc. Most in the link, otherwise in the pinned topics in the discord channel of pokemongo-map
