### ISSUE TITLE
Gather Data Fast Update Coming!!

### ISSUE THREAD

**Issue by GrodanFreeman** [mchristopher/PokemonGo-DesktopMap#1029]
Been seeing chatter about the new update having an in game captia that comes up when suspicious activity is detected.

http://www.i4u.com/2016/08/114581/pokemon-go-bots-and-pokemon-trackers-stop-working-new-pokemon-go-app-update

Gather as much as you can because I predict they may have this stopped up soon!

**Comment by furax187** [comment]
wow, if that's true, it's a sad day for all. If they keep doing this kind of stuff and ban all these trackers, no1 will play it anymore and they will end up with no players at all.

**Comment by MrAwesomers** [comment]
They should stop bots, but not scanners and IV calculators. Botting is cheating, scanners and IV stuff are just features that improve the game. Features they forgot to add in the game.

If this change is real, I'll create a thousand accounts and let them stand still next to eachother instead of having 1 walk around. I just hope my computer can handle running that many instances lol

**Comment by GrodanFreeman** [comment]
I am sure that is what they are trying to do.  The problem is the bots work using the exact same mechanics as the maps, so on their end it difficult to tell which is which.  I am sure almost all of the banning is being done by an automated program that detects suspicious activity.  There are way too many fake accounts for a human or even group of humans to go through.  Although they do have the money to afford the interns. lol

**Comment by MrAwesomers** [comment]
The mechanics are the same, but scanners run in circles and don't catch any pokemon. There are a million ways to see if it's a bot or something else tbh. Also, all botters are already getting banned. No bot is undetected at the moment, so this action is clearly to stop the need to ban everybody and to stop scanners and other useful features that they didn't add.

Meanwhile, my ticket to change team is still unanswered after more than a month. I'm so tired of being on a different team than all my friends. If they stop my scanners and stop me from hunting pokemon, I'd probably quit.

**Comment by rhawley88** [comment]
spawns have changed also again so really gather quick what data you can

**Comment by Shogunz1** [comment]
no problems as of yet. runs great.

**Comment by pill0ws** [comment]
jesus, they better not touch my IV checker.... the new Apraisal feature is just half assed as I expected.... at least I've logged enough IV's that I maybe able to decypher wtf the stupid Team Leader is saying about the pokemon being appraised but stats stupid, I want my hardset values, not some guesstimation. There is ust no reason at ALL to prevent people from knowing the IV's of their captured pokemon, especially with the appraisal feature being in place for the plebs (i use that term in the nicest possible way, its not a bad term)

**Comment by MrAwesomers** [comment]
![2016-08-24 23 31 21](https://cloud.githubusercontent.com/assets/20760672/17948852/f2e6a112-6a52-11e6-9428-91a02c731b44.jpg)
