### ISSUE TITLE
[Suggestion] Remove expired pokemons and lures from map

### ISSUE THREAD

**Issue by JarJak** [mchristopher/PokemonGo-DesktopMap#103]
Or is there any reason why you leave expired things on it?

**Comment by ShawnHardwick** [comment]
I believe it is supposed to remove expired entries, but the code he forked from had a bug.

@mchristopher May I suggest merging this committ (or maybe the whole entire develop branch) from the forked Python code to fix the issue?

https://github.com/AHAAAAAAA/PokemonGo-Map/commit/99a97f473e34ab7adc34ea4d6a5b5749c1206084

**Comment by LitoOsaka** [comment]
I found pressing Ctr + R to refresh the map effectively remove all expired pokemons. I don't have pokestop and gym on so I cant tell you about those.

**Comment by JarJak** [comment]
And now there is no way to see lures... why?
