### ISSUE TITLE
PTC Account Creating Help needed

### ISSUE THREAD

**Issue by G0rzilla** [mchristopher/PokemonGo-DesktopMap#1032]
Please can some tell me whats the fastest way to create accounts.
Do you use the same mail for all the accounts or do you need to create more emails also?
Want to run multiple scans.

**Comment by Mirx** [comment]
Haven't used it as I only run 1 account, but this seems to be to goto app

ptc-acc-gen over at https://github.com/FrostTheFox/ptc-acc-gen is once again functional, still only semi-automated, but it works.

**Comment by LeeTaylorVS** [comment]
I used [Pikapy](https://github.com/skvvv/pikapy) to create my accounts.

**Comment by G0rzilla** [comment]
@Mirx If you use just one account whats your scan size?
@LeeTaylorVS How many could you create? you probably still need to verify the account and still log in and catch first Pokemon?

**Comment by LeeTaylorVS** [comment]
I created 30 accounts, all using one email address and then just verified the email address for each one. Never logged in and caught a Pokemon.

The following command will create 30 accounts with random usernames but all using the same password.

```
pikapy -m myemail+@gmail.com -p pasword123 -c 30
```

**Comment by Mirx** [comment]
Just 3. I only use the map when something really interesting is in my nearby screen. Constantly switching between the map and the game is to tedious for me.
