### ISSUE TITLE
The most annoying problem from JavaScript error!

### ISSUE THREAD

**Issue by galaxy9999** [mchristopher/PokemonGo-DesktopMap#1035]
Multi windows/acct screen

Open 1st window, no javascript error. set the marker to  from the default IP and minimize. 
Open 2nd window, javascript error, the marker starts at the last set marker location (instead of default IP location, well, move the marker to ideal location. it seems working, minimize
Open 3rd window, no javascript error. set the marker to  from the default IP and minimize. 
Open 4th window, javascript error, the marker starts at the 3rd set marker location (instead of default IP location, well, move the marker to ideal location. it seems working, minimize.
.
.
.
.
.
Then all the sudden I see the default IP location where I always pull the marker away being scanned over and over again. some of the location I intended to scan stopped while all the marked were still locked at my locations in separated windows. 

If I manually to unlock and re-lock on those windows, it will start again. however one of the correct scanning windows will stop and the ghost scanning at the default IP location will just keep going. 

It seems that the number of all Javascript error windows/account will always scan at the default IP location in the background . If you manually pull one marker away, it will maintain the # of the scanning at that location by pulling another marker from elsewhere.  The default IP location will maintain green forever (no red) because the numbers of scanning from javascript error windows in the background that I can't interfere. 

i.e. I have 9 workers/windows/accts, 4 had javascript error, 5 did not, there will always be 4 accts scanning the default IP address location no matter where I place the markers. If I make one of the 4 error windows to start scan at correct location, it will stealthily pull one of the 5 correct windows to continue scanning at default IP location.  

I hope I describe it in the way you guys can understand it. and look for any solution you guys may have.

**Comment by galaxy9999** [comment]
Did more research and that's what I found:

1. The JavaScript error is brought by 0.3.2. It must be some kind of corrupt files in it because my manually updated 0.2.1 is perfect javascript error free still.

2. It is always the 2nd windows/acct have JavaScript error. Such as 1 is fine 2 has error, 3 is fine. 4 has error, 5 is fine. 6 has error...

3. All Javascript error windows/accts will make the scan at the default location where your IP address give to you. No matter where you draft the markers to.

**Comment by nopejusttesting** [comment]
Here is how I got around the problem but it's not perfect. For instance when I closed all the windows and came back 8 hours later. I found somehow the default area was still being actively scanned. Anyway.
Open window 1, Login account 1, place wherever you like
Open window 2, Login account 2, Will give error and default to the spot you placed 1.
Open window 3, Login account 2, Place wherever you like
Open window 4, Login account 3, Will give error and default to the spot you placed 2.
Open window 5, Login account 3, place wherever you like

Using this method you are able to have all your accounts scanning their correct areas but you will have double the windows open. If you sort the windows that gave errors and the ones that didn't you are able to close the ones that did give errors without effecting the non error windows.

It's a pain in the ass and I wish someone would fix it.

**Comment by galaxy9999** [comment]
I used to do that. lol It is rather annoying indeed. I really hope the devs can look at the code to figure out why the 2nd one uses the 1st one's scan location. Then the same type of error repeats. It must be a defect on code. :) No, I use 0.2.1 with manual map update to avoid the javascript errors. It really drives me nuts. Dev, please help us to fix this error. Thank you!

**Comment by Nonkel** [comment]
Looks like the same error I described yes. Really annoying, must be something wrong in code. ot fixed in 0.3.3 unfortunately, still behaves the same.
