### ISSUE TITLE
Possible Ban

### ISSUE THREAD

**Issue by batsche** [mchristopher/PokemonGo-DesktopMap#1039]
Hi,

installed the new version of PokemonGo Map. Cause there is no option to login with my google account I made a PTC account.

Loged in, nothing will be scanned. Then look up and there is the button:

Possible Ban

Created another PTC account, fresh login, same problem.

Bug or what have I done wrong?

Btw: PokemonGo Game is still working perfectly, my main account is not banned

**Comment by Mikkikki** [comment]
Did you use the account to choose a starter?

**Comment by batsche** [comment]
I made the account, confirmed my email adress, used username & password for the live map and nothing works.

Didnt make more.

Made a new try now. New PTC account. Accepted some things in my PTC profile. Added some Pokemons in my Pokedek. Made a new google api. Tried to log in - same problem: Possible ban

**Comment by anon2019** [comment]
been using this for a while now and using a burner PTC account exclusively for this and it got banned 4 days ago

**Comment by batsche** [comment]
ok have it. Needed to log in the game with my PTC account and catch one of the starter pokemons. Now he scanns the location.

Can someone explain me follow functions:

Lock marker - you can't put the marker to another place?
Scan follow locations - ???? Is this when I have the live map at my mobile active?
Start at user's location - ??? Is this when I have the live map at my mobile active?
Search - ???

Why don't I see any spawn points? I activated the option but nothing happens :(

**Comment by Arsar01** [comment]
Lock marker- you can't manually drag it to other places
Scan follow locations - yes for mobile (although i read a comment on here about how he had a laptop in his car and was scanning, idk what he was talking about)
Start at user's location - yes for mobile (^^)
Search- if you toggle it off it'll pause the search

**Comment by himeshpatel88** [comment]
I have created a new PTC account, logged in on my phone, caught my first starter and then logged into the app, it will scan for about 1015mins before showing status as "Possible Ban", I then have to close all windows and re-open for it to continue to the have the same problem, is there a way around this?
