### ISSUE TITLE
My notifications tab has completely wiped, there are no pokemon there. Can anyone please help?

### ISSUE THREAD

**Issue by Arsar01** [mchristopher/PokemonGo-DesktopMap#1042]
Yesterday I added in about 50 pokemon I didn't have to my notification settings, but when I close the app and open it again, they disappear and I instead get an older version of my notifications tab. How do I save the pokemon I add into notifications?

**Comment by MrAwesomers** [comment]
I'm wondering the same thing. When I open the application, sometimes the list loads but sometimes it doesn't. (I'm using mac os x)

**Comment by Arsar01** [comment]
I'm on windows

**Comment by Arsar01** [comment]
I logged in this morning and I saw that there are no pokemon listed in my notifications anymore. I added in some pokemon last night and logged out, logged back in, as well as closed and reopened the program to see if the new pokemon were there and they were. But for some reason, it's all gone now. Anyone experiencing this as well?

**Comment by drippybutt** [comment]
With me, for some reason, the first instance of the app is what saves. So the first one I open, with all notifications I add in, they stay. The other three instances do not have them though. Also, if you delete your pokemon-go-map folder in appdata/roaming, it wipes all the notifications and everything.
