### ISSUE TITLE
Can't Login

### ISSUE THREAD

**Issue by pill0ws** [mchristopher/PokemonGo-DesktopMap#1044]
I made a new account, logged in to capture my starter pokemon but the game would not let me login under the PTC account so I used the Google account to do so. Then I tried loggin in with the App and it says the password is incorrect, which is a dirty lie because I literally just made the account. I nnoticed that the PTC servers were down for maintenance, could this be causing this login error. I am certain I am using the correct login info as it works on the PTC website but does not work on the game client or the App

**Comment by Mirx** [comment]
It might be to long, the max for the app is something like 15 characters, while the website allows more.
Try to change it on the website, if it fails, then your password is too long.

**Comment by pill0ws** [comment]
ahhhh, ok. well the password worked in 2.1, it's only 12 characters. However the strange thing is that the password doesnt work on the game client either. It only works on the website. The game client, when logging in with PTC will not accept the password, only when logging in with Google
