### ISSUE TITLE
Outage? Java error?

### ISSUE THREAD

**Issue by Eodore** [mchristopher/PokemonGo-DesktopMap#1045]
![untitled2](https://cloud.githubusercontent.com/assets/21231395/17953503/8b1e3924-6aa6-11e6-8a57-2d013406b3ed.png)

Please advise!

**Comment by Eodore** [comment]
![untitled3](https://cloud.githubusercontent.com/assets/21231395/17953526/c02cd6c0-6aa6-11e6-82b3-2257dbd10d05.png)

**Comment by HunterSnatch** [comment]
Same -- Then my "Outage" switched to "Possible Ban" then I shut down and re-opened to see if I got banned again and it's been running normal for an hour. Weird. Anyone else?

**Comment by Eodore** [comment]
HunterSnatch,

Yeah that's weird. Actually the first time I managed to go online, "Operational", that was last night. And now it's been giving me the exact symptoms - "Outage" then swithced to "Possible Ban".

**Comment by MrAwesomers** [comment]
Noticing the same. Restarting the app fixes it for me. If restarting the app gives possible ban again, the account is probably banned. My guess is when the app can't connect to the server for any reason, it will show outage and retry it's connection. If it fails after a certain time to fix it's connection it will stop trying and tell you that your account might be banned.
