### ISSUE TITLE
[JavaScript Error] Problem after second login

### ISSUE THREAD

**Issue by gibalb** [mchristopher/PokemonGo-DesktopMap#1047]
In the first login all was going fine, but then in my second try I got a javascript error.

Operating System: Windows 10
Type of computer: laptop
PTC login
![error](https://cloud.githubusercontent.com/assets/17603509/17959296/77d90b3e-6a6d-11e6-9c70-3fd2728953d1.jpg)

**Comment by madkeeper89** [comment]
Same issue her,
i still press OK and it works withouts problems here. 3 instances same time.

**Comment by BMWtx** [comment]
Giovani (might want to black that stuff out, but that's just me), you should be fine with this error recurring. It's generally those javascript errors relating to squirrel resources that will inhibit you from actually utilizing the scanner.
