### ISSUE TITLE
Possible to get Pokestops and Gym location out from the program?

### ISSUE THREAD

**Issue by thetof91** [mchristopher/PokemonGo-DesktopMap#1048]
Hello.

I just wonder if it is possible to get all PokeStops and Gyms out from the program. As I can see it saves it, but I have not found where.
It is as im right now scanning pretty big area. Where I want to get the PokeStops and Gyms locations, so I can export it out so just use it on my google maps and save locations there. :)

**Comment by hibbovsky** [comment]
pogom.db

**Comment by qmech7k** [comment]
I can recommend using the sql.js project to access the pogom.db database directly from javascript, no need to export anything.

**Comment by thetof91** [comment]
qmech7k

Can you explain how to do that?
