### ISSUE TITLE
Pulling incorrect location, ability to change location?

### ISSUE THREAD

**Issue by Fryz04** [mchristopher/PokemonGo-DesktopMap#105]
Is there any way that you can incorporate a feature to allow entering a custom location. Mine is pulling to the local DNS 30 miles from actual location.

**Comment by JWise93** [comment]
Scroll down within the applications login screen, you can override the location with GPS coordinates.

**Comment by fenixasin** [comment]
please comment fryz04 if this helped, and close or comment that this can be closed to help the developer

**Comment by daveydz3** [comment]
So my issue is similar to this in that even when I leave the coordinates blank to use my current location, it puts my location somewhere really far away. is there a cache I can clear?

**Comment by MinimalSkill** [comment]
you could just manually put in your coordinates

**Comment by daveydz3** [comment]
right, but it's not working with the current geolocation, how can that be fixed?

**Comment by JWise93** [comment]
I believe there is an issue tracker for that, already. This should be closed, as it is requesting a feature that is currently available.

**Comment by ShawnHardwick** [comment]
The app first attempts to resolve your location through the browser locator API. This is the same API used by Google Maps and other websites for determining your location. If it cannot find you location that way, it takes your IP and matches it again the ipinfo.io  service to determine a rough location.
