### ISSUE TITLE
Suggestion: Let us set notifications for rarity, but with exceptions

### ISSUE THREAD

**Issue by PJRay** [mchristopher/PokemonGo-DesktopMap#1051]
Say, I want anything uncommon and rarer, but I don't want to get notifications for every single goldeen that shows up. So far, we can only set notifications for specific pokemon (which takes for ever to do) and then the rarity. I would like a box with exceptions to the rarer pokemon that the map would otherwise notify me about.

_Sorry if this is not the place to put a suggestion - I wasn't sure where else to put it._

**Comment by pegleggregx** [comment]
To add to this is there a way to view a list of what each poke is considered?
