### ISSUE TITLE
no pokemon on map

### ISSUE THREAD

**Issue by pocketq10** [mchristopher/PokemonGo-DesktopMap#1053]
is it me or is the scanner not displaying pokemon any longer?

**Comment by poekrel** [comment]
#1017

**Comment by pocketq10** [comment]
thanks for the reply

**Comment by pocketq10** [comment]
@poekrel that topic doesnt answer my question, i see the map, and it scanning, and the top says operational, but no pokemon has appeared. i dont know if this had something to do with the new pokemon go update or not.

**Comment by pocketq10** [comment]
pokemon started showing up after 15 mins of waiting....pokestop then appeared as well....very very slow
