### ISSUE TITLE
"Possible Ban"

### ISSUE THREAD

**Issue by ChongoPower** [mchristopher/PokemonGo-DesktopMap#1055]
Doensnt matter if I use an old PTC account or a brand new, it always say "Possible Ban" after the "Waiting" sign. 

Any idea what it could be?

**Comment by RebelPrinceTrys** [comment]
I have this issue as well. I'm able to log onto that PTC account just fine, on the game and on the Pokemon site. But the map is 100% non-functional for me at present.

**Comment by xxxGRISBYxxx** [comment]
I'm having the same issue myself. I tried different PTC accounts and same message. Map does load with waiting message, then message changes to possible ban.
