### ISSUE TITLE
Push notification to Phone

### ISSUE THREAD

**Issue by AnthonyButler012** [mchristopher/PokemonGo-DesktopMap#1060]
Seriously, this app is wonderful, but someone has to work on pushing desktop notifications to our phone !!! I've searched in all posted issues and no one found a solution for that. People kept talking about Push bullet, IFTTT, Growl, but nothing concrete yet ...

**Comment by rajeshj82** [comment]
Hi Antony, Plz try below link,, will send you desktop notification as well as notification for your android mobile.

Click below link
https://livehelp.outbell.com/mybluemoon

Note: Remember to accept push notification pop-up while the site loading in your mobile.

**Comment by AnthonyButler012** [comment]
Could you be more specific on how I can use this link to push notification to my phone ? I looked the whole website and couldn't find a way to do so ...

**Comment by AnthonyButler012** [comment]
This link could be useful for developers : https://documentation.onesignal.com/v2.0/docs/website-sdk-installation

Unfortunately, I don't know how to upload the files to the top-level root of your site directory (Step 2). Anyone can help me with this ?
