### ISSUE TITLE
"Possible ban" but just created the Account..

### ISSUE THREAD

**Issue by ultimate2106** [mchristopher/PokemonGo-DesktopMap#1062]
1. I created a new google mail account
2. I created new API Key
3. I created new PTC Account with this GMail
4. Reinstalled PoGoMap and logged in
5. "Waiting.." .... "Possible ban" -.-

server up: null
main.html:147 Error getting location, trying second provider PositionError
main.html:169 2016-08-26 10:22:34,138 [      MainThread][     runserver][    INFO] Parsed location is: 34.0432/-118.2675/72.4387 (lat/lng/alt)

main.html:169 2016-08-26 10:22:34,138 [      MainThread][        models][    INFO] Connecting to local SQLite database

main.html:169 2016-08-26 10:22:34,138 [      db-cleaner][        models][    INFO] Regular database cleaning complete

main.html:169 2016-08-26 10:22:34,138 [ search-overseer][        search][    INFO] Search overseer starting

main.html:169 2016-08-26 10:22:34,138 [ search-overseer][        search][    INFO] Starting search worker threads

main.html:169 2016-08-26 10:22:34,138 [ search-overseer][        search][    INFO] New location caught, moving search grid

main.html:169 2016-08-26 10:22:34,186 [ search-worker-0][        search][    INFO] Searching at 34.043211,-118.267506

main.html:169 2016-08-26 10:22:34,186 [ search-worker-0][      auth_ptc][    INFO] PTC User Login for: Freekill93

main.html:174 Python server started!
main.html:174 Got open express port: 8001
main.html:169 2016-08-26 10:22:34,789 [ search-worker-0][      auth_ptc][    INFO] PTC User Login successful.
2016-08-26 10:22:34,789 [ search-worker-0][      auth_ptc][    INFO] Request PTC Access Token...

main.html:174 Express server started!
main.html:159 server up: http://localhost:8001
main.html:169 2016-08-26 10:22:34,957 [ search-worker-0][      auth_ptc][    INFO] PTC Access Token successfully retrieved.

main.html:149 Found location [53.5685,8.5968] by ipinfo.io
main.html:169 2016-08-26 10:22:45,444 [ search-worker-0][        search][   ERROR] Map parse failed at 34.043211,-118.267506, abandoning location. Freekill93 may be banned.
Traceback (most recent call last):
  File "C:\Users\Moonlight\AppData\Local\pokemon\app-0.3.2\resources\app\map\pogom\search.py", line 510, in search_worker_thread
    findCount = parse_map(args, response_dict, step_location, dbq, whq)
  File "C:\Users\Moonlight\AppData\Local\pokemon\app-0.3.2\resources\app\map\pogom\models.py", line 387, in parse_map
    cells = map_dict['responses']['GET_MAP_OBJECTS']['map_cells']
KeyError: 'map_cells'

main.html:169 2016-08-26 10:22:55,457 [ search-worker-0][        search][    INFO] Searching at 34.044157,-118.266849

main.html:169 2016-08-26 10:22:55,676 [ search-worker-0][        search][   ERROR] Map parse failed at 34.044157,-118.266849, abandoning location. Freekill93 may be banned.

**Comment by batsche** [comment]
You need to log in Pokemon with your new created PTC account and catch one of the first tutorial pokemon - then log in poke map again and it should work

**Comment by askeland** [comment]
Remember to activate your PTC account through the activation email
