### ISSUE TITLE
SpawnPoint Add recent times

### ISSUE THREAD

**Issue by Smileynator** [mchristopher/PokemonGo-DesktopMap#1063]
Hey, this might sound silly, but look at this example:
http://puu.sh/qOSzc.png
These spawn points often spawn some pokemon (not always the same obviously) on the same hour of the day.
I would like to see the common spawning times if possible for the last X time when i mouse over the clue spawn dots when enabled.

This would be very useful because of things like this:
http://puu.sh/qOSCm.png

Please consider this valuable feature.

**Comment by qmech7k** [comment]
Spawnpoints have a fixed minutes-after-the-hour where they spawn something. You don't need to see "common spawning times", it's redundant.

On the other hand, it can be useful to see a list of what has spawned in that spawnpoint. Adding this feature yourself is not too difficult. The easiest thing is probably to create a google maps project yourself and add the spawns as map markers. I used a project called spawnScan (hosted here on github) as my base (actually just using the spawns.html file). Then simply copied the spawn database (pogom.db) and used a client side javascript implementation of sqlite to access the database (project called sql.js hosted here on github). Some appropriate sql queries on the database and simple store the results as google maps infowindows connected to the appropriate map markers.

The spawns.html has a pretty clever piece of js (not mine!) that presents color-coded dots for all spawnpoints reflecting the time remaining until the spawned pokemon disappears, updated realtime (well, every 1 second by default).

**Comment by Butom** [comment]
any link qmech7k?
and a question, any posibility a person that is weak at programing to run it?

**Comment by qmech7k** [comment]
It's a bit of a hybrid mess, so I'm reluctant to push my changes. The spawnScan project stores everything in json files, whereas this project uses an sqlite database. I layered my changes on top of spawnScan's way of doing things, so checking the database for any spawnpoints that existed in the json. Not very elegant.

I'll see if I can quickly change everything to just use the sqlite database, then submit a pull request to this project (it would just be a stand-alone file / set of files, based heavily on that part of spawnScan). Effectively just an alternative, always off-line, visualization (off-line from Pokemon, but requiring google maps access).

**Comment by Smileynator** [comment]
Well the idea would be to list the "minutes past the hour" time something spawns. And the last X pokemon that spawned there. Sorry if my intentions are not clear!

The piont is to help identify common spawns. I have 2 spots in my town that are some sort of onix nest ( was a shelder nest last week) Which only spawns said onix's on those 2 spots at like 5/6 times per 24h. So it is interesting to see happen.

**Comment by qmech7k** [comment]
Check the passiveViewer folder in my fork:
https://github.com/qmech7k/PokemonGo-DesktopMap

You need to add a google maps api key and a copy of your pogom.db file. Detection of non-standard spawns is disabled due to extremely slowness (on initial load). To enable, just uncomment the two lines in the map.html file below "check spawnpoint type" and the last line in the redraw function (to make non-standard spawnpoints show up red).
