### ISSUE TITLE
How to use multiple accounts?

### ISSUE THREAD

**Issue by aldder** [mchristopher/PokemonGo-DesktopMap#1065]
I'm sorry but i can't understand how to use multiple accounts.
I edited config.ini with all required elements, but the program seems to ignore everything except inputs in login screen.
Can someone pls help me??
Thanks

**Comment by magicdev2** [comment]
i dont think you can.....

**Comment by magicdev2** [comment]
i may be wrong.

**Comment by gabrielqduarte** [comment]
Just open 2 instances of the program. It will merge the findings and you can use multiple accounts

**Comment by aldder** [comment]
I don't think it's a solution for 20+ accounts

**Comment by madkeeper89** [comment]
#1078 - there is your answer.
