### ISSUE TITLE
Can't load map

### ISSUE THREAD

**Issue by pretzelfanatic** [mchristopher/PokemonGo-DesktopMap#1066]
Version 3.2 says operational but does not load a map.

**Comment by magicdev2** [comment]
mines to the lastest version doesnt work 
Oops! Something went wrong.
This page didn't load Google Maps correctly. See the JavaScript console for technical details.

**Comment by datoneguy90** [comment]
also having this problem. The map appears for a second or two then the "Oops something went wrong" message pops up.

**Comment by magicdev2** [comment]
![dsc_0386](https://cloud.githubusercontent.com/assets/21266952/18019491/5959df88-6baa-11e6-9ddf-a5d1b1f824e7.JPG)

**Comment by magicdev2** [comment]
![dsc_0389](https://cloud.githubusercontent.com/assets/21266952/18019534/8e221596-6baa-11e6-944a-878e31642847.JPG)

**Comment by magicdev2** [comment]
there.

**Comment by alexandrox** [comment]
Almoust you can see the map for a few second. I can't load the map, this always stay in loading
