### ISSUE TITLE
WARNING -INSTA BAN

### ISSUE THREAD

**Issue by elexiel** [mchristopher/PokemonGo-DesktopMap#1068]
Using this map on Pokemon Go 0.35 update will get your account banned!
This release is not safe to use for me on google login.

**Comment by magicdev2** [comment]
but not for ptc i dont think

**Comment by elexiel** [comment]
probably just a matter of time, since reports of "possible bans" are piling up. I would not risk using it on any main acc.

**Comment by Xionyus** [comment]
I've had 2 fake PTC accounts banned within maybe 3 days each from using this. PTC isn't exactly safe either.

I'm just wondering if they will be able to find out what my main account is, since you have to log in, accept terms, and catch a starter.

**Comment by magicdev2** [comment]
really? i have 2 accounts thats am have been using to test botting and its been a week and didnt get ban

**Comment by elexiel** [comment]
@magicdev2    better be careful. you have Been warned.

**Comment by gabrielqduarte** [comment]
i had 2 fake accounts that got the "possible ban" alert when i logged in today...

Looks like this is not working anymore :/

**Comment by magicdev2** [comment]
rip xD but really i dont get it how did you get ban everytime i bot i get soft ban or ip ban but never perm ban... dont want to jinx my self ;p

**Comment by PokemongoGether** [comment]
use bluestacks, google bluestacks use that to catch the pokemon and log out.

**Comment by magicdev2** [comment]
i dont like bluestacks it just annoy for me...

**Comment by Xionyus** [comment]
@PokemongoGether Good idea. I'll give it a try!

**Comment by rayra1234** [comment]
How do you guys know if the fake ptc has been banned? I didn't receive any email and I can still login into ptc website. However, the scanner doesnt work and says possible ban

**Comment by tinlar** [comment]
you must not be using a "new account" 

Log into the account in the game, play enough to capture your first Poke'Mon ... the account will then work for Desktop Map.

**Comment by Condedukee** [comment]
@tinlar it really works, thx.

**Comment by starstremr** [comment]
where did you get .35?
