### ISSUE TITLE
Server Mode

### ISSUE THREAD

**Issue by blahblah3141** [mchristopher/PokemonGo-DesktopMap#1071]
I often roam around my university campus and I want to view this map on my phone while doing this, However, I just want to "view" the scan that my computer is making on a VPN instead of the phone doing an extra scan itself. I know that ngrok.io actually scans from your phone using its IP (Correct me if I'm wrong) and so is not 100% safe.

Is server mode what I want, or do I have to use a remote desktop app?

**Comment by beng8686** [comment]
You are wrong it doesn't scan using your phone resources. Easy way to tell is that the stats are exactly the same on both the computer and phone and so are the scanned locations. Your mobile browser doesn't have the necessary resources to run a scan anyway.

**Comment by blahblah3141** [comment]
So I am 100% safe running from ngrok on the same phone that has my main account?

**Comment by blew888** [comment]
Any way to run without using ngrok.io?
