### ISSUE TITLE
Requesting Spawn Location History

### ISSUE THREAD

**Issue by Sedare** [mchristopher/PokemonGo-DesktopMap#1074]
I am literally stupid when it comes to coding, but I want to know how possible it is to do one change.

I would like to be able to view stats on ANY SPECIFIC SPAWN LOCATION.

I can see that you already have this option separated by pokemon, but is it an option for this to be on the pokemon when I click on it... say as a new link next to GET DIRECTIONS? I cant imagine this is impossible since you already manage spawn locations, I just want to view the history of a location.

I have found that certain spawn points show a propensity to spawn rare pokemon, and others do NOT. I want to test this out. :D

**Comment by qmech7k** [comment]
Look at my response here:

https://github.com/mchristopher/PokemonGo-DesktopMap/issues/1063
