### ISSUE TITLE
Feature Request: Change color of spawn locations that are nests and/or post to a shared map.

### ISSUE THREAD

**Issue by brianguy1** [mchristopher/PokemonGo-DesktopMap#1075]
Given that it tracks spawn locations and what spawns, it should be relatively easy for it to identify which spawn locations are nests if a single pokemon spawns frequently from the same spot. We could indicate the nest spawn points as a different color or picture for easy identification. 

Ideally, if people were open to sharing the nest location, it could report to a master shared database. Or I suppose all spawn points, pokestops, and gyms could be collected into a master shared map.

Great app and cheers to the developers. Awesome program.

**Comment by qmech7k** [comment]
I wish there were a consensus definition for "nest". There seem to be two main camps. One camp defines a nest as a spawnpoint that always spawns the same pokemon. I've never seen one of those myself, although I haven't trawled all my scan data for it. The other camp defines a nest as a tight cluster of spawns.

You seem to have a very lose definition of nest that is unworkable in practice. What is "frequently"? I've been looking somewhat at identifying the "encounter tables" that lie behind the various spawn points in my area. After 5K spawns, I don't have nearly enough data, but there appears to be a time trigger, maybe "seasonal". As an example, those 5K spawns covering a relatively small area over a period of several weeks. During that time I saw not a single Mr Mime. On the other hand, during the past 3-4 days, I've seen 4 just IN GAME, not even scanning, all at spawn points I've scanned heavily plus see in game pretty much every day. The statistical likelihood of this being random is fairly low.

Even ignoring these seasonal changes, looking at my data, it's hard for me to see what you would characterize a "nest". For example, I have a lot of spawn points that are basically:

33% Rattata
33% Weedle
33% Other

Is that a Rattata nest? Not a very interesting nest, of course, but that's part of the problem. Replace Rattata with Hitmonchan or Dragonair and that would be a VERY interesting spawnpoint indeed and calling it a "Dragonair Nest" would seem to fit your definition of a nest very well.
