### ISSUE TITLE
Scans stop working after 2-3 hours

### ISSUE THREAD

**Issue by homerfan123** [mchristopher/PokemonGo-DesktopMap#1077]
Hey everyone,

after upgrading the scanner app from 0.2.1 to 0.3.2 I had no problem setting them up with PTC accounts I had before. Only problem is now, that after about 2-3 hours they stop working and display "possible ban" and I need to log out an log in again. After the relog they work fine again. No standby mode triggered by the pc or anything, since I didnt change anything, only updated the app.

Anyone who had/has the same issue?

**Comment by himeshpatel88** [comment]
+1

**Comment by galaxy9999** [comment]
JavaScript error?

**Comment by homerfan123** [comment]
No error while this happens. If I have 5 instances of the app not all 5 stop at the same time. Maybe one stops, the second after 10 minutes, third after 3 minutes etc (no system behind that). Just seems like there is a timeout after a specific time or point of time.

**Comment by homerfan123** [comment]
is there actually a way to get back to 0.2.1? The installer just installs the newest version 0.3.2
