### ISSUE TITLE
Compiling scans from multiple accounts?

### ISSUE THREAD

**Issue by MemoriesofNemo** [mchristopher/PokemonGo-DesktopMap#1078]
Is there a way to compile the scans from multiple accounts to have the collected data from all of them in one window? That way you'd be able to cover a much larger area and not have to scroll through all your open windows to find what you need. 

It would be amazing to be able to have coverage of your entire city updated at all times, in a single URL.

**Comment by madkeeper89** [comment]
if the multiple accounts run on the same computer, you can see all scans in all windows at the same time.

if the multiple accounts run on multiple computers, you need to share one mysql database.

my friends and me use about 12 accounts on 5 computers with one mysql database. we scan our whole (little) city.

greets

**Comment by MemoriesofNemo** [comment]
Hmm, when i try to run multiple instances of the program on my pc, it will only perform scans in one window at a time, despite using different accounts and google api's.
I'm not very skilled with programming, so if you could explain how to maybe make it work, i would be incredibly grateful :)

Before i opened this thread, i wasn't even aware of the possibility of running multiple instances of the program on a single pc.



Sendt fra min Samsung Galaxy-smartphone.


-------- Oprindelig besked --------
Fra: madkeeper89 <notifications@github.com>
Dato: 28/08/2016 18.09 (GMT+01:00)
Til: mchristopher/PokemonGo-DesktopMap <PokemonGo-DesktopMap@noreply.github.com>
Cc: MemoriesofNemo <memories_of_nemo@hotmail.com>, Author <author@noreply.github.com>
Emne: Re: [mchristopher/PokemonGo-DesktopMap] Compiling scans from multiple accounts? (#1078)


if the multiple accounts run on the same computer, you can see all scans in all windows at the same time.

if the multiple accounts run on multiple computers, you need to share one mysql database.

my friends and me use about 12 accounts on 5 computers with one mysql database. we scan our whole (little) city.

greets

-

**Comment by dripsin** [comment]
Is the config file "config.ini.example" useable if we modify it? Would this streamline using multiple accounts?
