### ISSUE TITLE
Mobile Support?

### ISSUE THREAD

**Issue by ItsDatBoiSwane** [mchristopher/PokemonGo-DesktopMap#108]
I'm still currently new to this idea and love the project i would love if someone could explain to me how the mobile support is supposed to work, because currently driving out catching pokemon then coming back into the house gets difficult.

**Comment by killerjerick** [comment]
Basically, you portforward port 8000 (http://www.portforward.com has a nice guide on how to portforward on most routers)

You will then scan the QR code that comes up when you hit "Activate" alternatively you can type in the address it gives you which allows you to see the map on safari.

Happy hunting!

**Comment by ItsDatBoiSwane** [comment]
@killerjerick Thank you thank you thank you! Luckily i have some general experience with port forwarding and figured it out quite easily. Thanks heaps!
