### ISSUE TITLE
Having an issue: "Oops! Something went wrong. This page didn't load Google Maps correctly. See the JavaScript console for technical details. "

### ISSUE THREAD

**Issue by WynterWynter** [mchristopher/PokemonGo-DesktopMap#1081]
Can someone help?
Like above it mentions it is operational just map is showing Oops! Something went wrong.
This page didn't load Google Maps correctly. See the JavaScript console for technical details.

i got a new PTC and new Google map key.

**Comment by dragoncai** [comment]
Do you have activate  "Google Maps JavaScript API" ?

**Comment by WynterWynter** [comment]
Where do I find out about that?

**Comment by WynterWynter** [comment]
Yes I just checked it and it is enabled.

**Comment by aldder** [comment]
make a new project and get a new key. if it doesn't work, change google account and redo everything

**Comment by WynterWynter** [comment]
Thanks. Problem fixed.
