### ISSUE TITLE
I can get the program to open, but its not scanning. It just says possible ban at the top.

### ISSUE THREAD

**Issue by hybridguitarist** [mchristopher/PokemonGo-DesktopMap#1082]
so I just met a guy who was using this program today at a kabuto nest, and it was working beautifully. So I downloaded the program and installed the software. The "PokemonGoMap-Win.exe " to be exact. latest version. Got the google maps key, and created the pokemon trainer club throw away account. caught the starter pokemon and hit one pokestop just to be sure. sighned in with the account and at the top it says waiting for 10 sec and then says possible ban. is there a step I missed or is there something I need to do to fix this issue. or am I just screwed off the bat? please help!!!

**Comment by Edcwae1a** [comment]
I have this same problem on MAC. Just says outage and then possible ban. But the account is good and I'm wondering what I'm doing wrong now. It used to work before this desktop map update, and before the pokemon go update. Account was banned but then I made a new account...which isn't banned. But I have the same result. Does not scan at all.

**Comment by hybridguitarist** [comment]
I've seen alot of post on this but very few answers. I was with a guy who was using this program around 600pm pst and was using it affectively. I was very exited to get home and try it, but its just not working.

**Comment by juggalokyle** [comment]
Bump! Having the same issue! I'm new to this and just downloaded it!

**Comment by BMWtx** [comment]
Was having the same issue and they just seemingly started to work again of their own accord. Probably about to revert to 0.2.1 as I was using that without issue.

**Comment by ButtCheez** [comment]
I had been using it fine for a while with the google login, then on day the google login wasn't an option only the PTC so a created a dumby PTC acct. and tried to use it and same as all above, it will say waiting for a little while and then "possible ban". So yeah it doesn't work anymore for me but I have a friend who still has the google login option on his and it still works fine sooo what ever update I must have got that took away the google login seemed to ruin to app for me...

**Comment by waclock** [comment]
Same problem here

**Comment by kylerichard** [comment]
Same problem as well. Ever since the newest release it has been telling me possible ban on my Mac but it was working perfectly fine before when I used the Google log in

**Comment by Pkmnletarn** [comment]
I have the same problem. I have tried two different accounts, thought I took the steps in the wrong order and that it would make a difference. It didn't! 
I am wondering a little about the function of the PTC account. My idea was that I wasn't fully a member. All I can use it for is to set up my profile. I was under the impression that you could access parts of Pokemon Go status and pokedex from PTC. What is PTC good for? Just to play Pokemon TCG online?
What was the reason that the Google login stopped working?

**Comment by ndsvw** [comment]
I think, PTC is for all the people who are younger than 18.
If you start Pokémon Go the first time, you have to confirm your age and if you're younger than 18, you can only login into PTC.

Google login got removed beacause: "It has been reported that Google login scans stop after 30 minutes." (https://github.com/mchristopher/PokemonGo-DesktopMap/wiki)

And by the way! **I have the same problem and can see the text "Possible ban",** too.

**Comment by Pkmnletarn** [comment]
Hi!
Thanks for the personal reply! You must really be busy!
Even if I cannot get it to work, I applaud your effort and hope to I get it
to work in some way. I will keep trying and check in your site at regular
intervals.
When it works, I will sponsor you for sure!
:-)
Staffan, 54 years young

2016-08-30 10:59 GMT+02:00 ndsvw <notifications@github.com>:

**Comment by aibo1** [comment]
same issue here. I even reverted back to 0.2.1 which was previously working fine, but now that one's stuck on waiting too.
