### ISSUE TITLE
Reducing Search Radius (What does it do?)

### ISSUE THREAD

**Issue by ad1tyas** [mchristopher/PokemonGo-DesktopMap#1083]
As the title says..

I'm a bit confused on what reducing the search radius (or increasing) does.

Does it..
1. Reduce the diameter of the search circle?
2. Reduce the amount of circles it expands to around the original?

Thanks!

**Comment by madkeeper89** [comment]
#2

**Comment by ad1tyas** [comment]
Thanks.
