### ISSUE TITLE
Multi-scanners? 

### ISSUE THREAD

**Issue by userino** [mchristopher/PokemonGo-DesktopMap#1084]
Hello guys. 
I want to ask, if it is possible to scan a bigger area, by using multiple accounts, like a city or town ? 
I tried to make a 2nd account and load it up, but at soon the 2nd started to scan, the 1st stopped. 
I used same API on both accounts. 
If it is possible, could you please tell me how to do it ? 

Thanks!

**Comment by juggalokyle** [comment]
I would like to know how to do this as well.
