### ISSUE TITLE
Multiple scanners now limited to 3 since this update

### ISSUE THREAD

**Issue by Nonkel** [mchristopher/PokemonGo-DesktopMap#1086]
Hi there,

I was always able to scan the small village I live in with 4 scanners from 4 PTC accounts, radius set to 5 on 2 scanners and 4 on the other 2. These all combined on the map of the first scanner. All using same map API.

But now, since the last update, I keep getting errors, although I use the exact same procedure. Start up the first scanner. Start up the second, I get an error but it still functions. Start up the 3rd scanner with radius 4, also works. But when I start the 4th scanner, the 3rd stops working. If I refresh the 3rd, the 4th stops. I use 4 different PTC accounts, but this makes no difference. I think its an error somewhere in the program, but Im no way of an expert on that. Drives me mad, though. Had the perfect setup, and now Im missing a part of town.

Cant help to think that that's the exact place where all the rare Pokemon spawn... ;-)

Somebody who can help me out or has any suggestions? Thanks in advance!
Oh, and the earlier requests of push messages to mobile phone when a rare spawns, yes please!

**Comment by galaxy9999** [comment]
Is your error the same JavaScript error described here, https://github.com/mchristopher/PokemonGo-DesktopMap/issues/1035?

**Comment by Nonkel** [comment]
Looks the same to what Im experiencing, yes!

________________________________
Van: galaxy9999 <notifications@github.com>
Verzonden: woensdag 31 augustus 2016 10:01:29
Aan: mchristopher/PokemonGo-DesktopMap
CC: Nonkel; Author
Onderwerp: Re: [mchristopher/PokemonGo-DesktopMap] Multiple scanners now limited to 3 since this update (#1086)


Is your error the same JavaScript error described here, #1035<https://github.com/mchristopher/PokemonGo-DesktopMap/issues/1035>?

-
