### ISSUE TITLE
Add Spawnpoint Scanning to DesktopMap

### ISSUE THREAD

**Issue by xslayserx** [mchristopher/PokemonGo-DesktopMap#1087]
Hey I'm a total noop at programming but i saw that you could scan your area based on Spawnpoints.. I read alot about tbterra, .json and other stuff i didnt really understood.
So is there any easy way to scan based on spawnpoints or can i expect an update in the future ?

**Comment by bbjfsu** [comment]
This would be really great. I use the desktop version because I cant run pyhton on this computer.

**Comment by ManiacDC** [comment]
https://github.com/mchristopher/PokemonGo-DesktopMap/issues/1046
