### ISSUE TITLE
tried everything, ip banned?

### ISSUE THREAD

**Issue by heyitzdinny** [mchristopher/PokemonGo-DesktopMap#1088]
my scanner wont detects any pokemons and the status is operational, so I tried to download 0.2.1 and its the same problem. deleting roaming/pokemon-go-map, didn't work. Created a new api from different google account.  tried 5 new dumbies account , which are non-banned and still having the same problem.

any idea? 
![errpr](https://cloud.githubusercontent.com/assets/21326464/18074870/e4387f20-6e24-11e6-885e-dd99110b702d.jpg)

**Comment by heyitzdinny** [comment]
Btw I activated all my accounts and catch the starter

**Comment by a314s** [comment]
My alt accounts last about 1 week before they stop working. Make a new alt account and try with that. (you can't just make an account on the website you need to make sure to play through the tutorial in the game)

**Comment by dhyde79** [comment]
can you log in via mobile with your normal account on wifi from that IP?  if yes, your IP isn't banned.
