### ISSUE TITLE
Pokemon not shown

### ISSUE THREAD

**Issue by lycenthedead** [mchristopher/PokemonGo-DesktopMap#1090]
Everything shows except pokemon, despite having pokemon scanning enabled. I've cleared cache, deleted the entire pokemon-go-map file in roaming, but no luck. Account is activated/not banned (have tried with 8 different accounts as well). Anyone know a cause/fix?

**Comment by robertybob** [comment]
Working ok for me

**Comment by heyitzdinny** [comment]
I too having the same problem. Going to try out a few ideas fellow member suggested

**Comment by lycenthedead** [comment]
It works fine on several desktops for me, but my VPS systems are having trouble showing Pokemon =/

**Comment by lycenthedead** [comment]
On the off chance it was because of some data corruption, I copied the pokemon-go-map file from my roaming on a machine that successfully scanned pokemon and copied it in the same location on the machine on which pokemon do not show. This did not solve the problem, so I'm not sure of another potential cause. Anyone have any input on this yet?

**Comment by heyitzdinny** [comment]
ill bet you got this error too."[Window Title] Error  [Main Instruction] A JavaScript error occurred in the main process  [Content] Uncaught Exception: Error: listen EADDRINUSE :::8001 ......." is this a network issue by your computer. it sound like something else is interfering with port 8001.

**Comment by lycenthedead** [comment]
Nope, I have the port forwarded and the map successfully displays on port 8001 (or whichever I specify). The map displayed still lacks pokemon though :x

**Comment by lycenthedead** [comment]
Just tried changing to a new Google API Key: No luck. Pokemon still do not show. I've no problem accessing the map on the ip xxx.xx.xxx.xx:8001 and seeing the map + gyms + pokestops (lured and all), so I'm not sure what the problem is =/
