### ISSUE TITLE
Full Stats Mode

### ISSUE THREAD

**Issue by blahblah3141** [mchristopher/PokemonGo-DesktopMap#1091]
When I click "all locations" in full stats mode while viewing Pokemon for, say, the last day, I should only see Pokemon locations for the last day instead of all time. Otherwise it gets very confusing

**Comment by HighOnTacos** [comment]
I disagree. I would miss that feature if it were removed, because it's great to know what spawns could potentially spawn various pokemon.

**Comment by blahblah3141** [comment]
I do not think you understand my question? You would still be able to see a map of where that Pokemon would spawn for all time if you wanted to... this just aligns the Pokemon shown with your current full stats mode.

For example, if my full stats is currently set to "last day", when I click all locations for, say, Pidgey, it will show all the Pidgeys that have spawned in the last day on the map. If your full stats mode is set to "map lifetime" it will still show all the Pidgeys that have ever spawned on your map...

In any case, they have implemented my suggestion in the latest update (0.3.3) so this question is now moot.
