### ISSUE TITLE
PTC accounts

### ISSUE THREAD

**Issue by SturgBoy** [mchristopher/PokemonGo-DesktopMap#1093]
With PTC accounts seeming to be instantly banned is it at all possible to use this without logging into an account?

**Comment by dripsin** [comment]
I dont think it would. You kinda need the account to get Niantics API information if i am correct.

**Comment by SturgBoy** [comment]
Does using bluestacks get you banned too?

**Comment by ndsvw** [comment]
it's possible.
if they recognize that your device is a virtual one -> they know that the GPS signal is probably faked -> they maybe ban your account.

**Comment by SturgBoy** [comment]
I'll try using a fake PTC account on it and check, I'm guessing it will ban though

**Comment by heyitzdinny** [comment]
Jw does using a ptc account generator will be all instant banned?

**Comment by SturgBoy** [comment]
Very likely, im not even scanning at all and they're showing up as banned

**Comment by minn3h** [comment]
Seems you have to login to the app and play a bit before a new PTC account works. I went to the point where you are asked to visit a pokestop but did not do so. Scanning started working.
