### ISSUE TITLE
Too many connections?

### ISSUE THREAD

**Issue by hybridguitarist** [mchristopher/PokemonGo-DesktopMap#1095]
What does this mean when I get this message? Please help!!!!

Too many connections! The tunnel session '6a6f919c67797c9637fb55dd8e1f2d5b' has violated the rate-limit policy of 20 connections per minute by initiating 35 connections in the last 60 seconds. Please decrease your inbound connection volume or upgrade to a paid plan for additional capacity.

The error encountered was: ERR_NGROK_702

**Comment by LuckyYou** [comment]
it means exactly what it says, I cant tell if this is a joke or not?

**Comment by hybridguitarist** [comment]
not a joke. I just don't understand what it means? I get it a lot, and I was wondering if someone could explain why it says it.. Thanks!! I have it open on my computer when I'm out and about and sometimes I can only scan one time on my phone and when I refresh it gives me that message.

**Comment by HighOnTacos** [comment]
Why would you need to refresh on your phone? The map continuously updates.

Anyways, I think it's talking about the amount of people connecting to any ngrok.io page at that time. Just refresh and try again, it'll work.

**Comment by hybridguitarist** [comment]
Thanks high tacos. The reason why I refresh is because when I open it, it will scan one time and for like 5 min the marker won't move away from the scan spot, so I refresh and that's when I get the message. so is there a limit on how many scans I can do? I also made sure the scan is off on my desktop. Because recently it's been only letting me scan like once or twice than the marker won't move. I'm still a neewbie on this and would like to use it to its full potential.

**Comment by hybridguitarist** [comment]
Sorry word correcting. Highontacos!

**Comment by HighOnTacos** [comment]
Click on the options in the top left, and find the option "Show scan
locations." This will show you where the app is scanning. The marker does
not move, but green circles will show up, radiating out from the marker in
a circle/hexagonal shape. These circles go from green, to yellow/orange, to
red, showing how long ago it was scanned. You can use the "Scan Radius"
option on launch to set how many circles it will scan outwards before
starting again at the marker.

**Comment by HighOnTacos** [comment]
I've found that a radius of 5 circles takes ten minutes to complete. Any higher, and there's a chance that it will miss pokemon that have spawned and despawned in 15 minutes while it's working on scanning the outmost ring. You can move the marker at any time to restart the scan in the middle.
