### ISSUE TITLE
no pokeman show after update

### ISSUE THREAD

**Issue by negev11** [mchristopher/PokemonGo-DesktopMap#1097]
am I the only one to have this problem?

I update to the new ver, made a new API key, made a new PTC account 
and then try to run the software but no pokemon show on map

**Comment by dylanf1996** [comment]
yeah same it says operational and everything...

**Comment by brianguy1** [comment]
I have the same issue. It auto updated and now nothing shows up. Bummer!!!

**Comment by negev11** [comment]
yes it works again...many thanks brianguy1
