### ISSUE TITLE
Paste from elsewhere - OS X

### ISSUE THREAD

**Issue by simonwicks** [mchristopher/PokemonGo-DesktopMap#11]
First off, amazing work on this! I've tried a couple of the other self hosted options, but this one works the best by a long shot for me. 

I however have strong passwords both on google and PTC, and there's currently no way paste into the fields, same for the coordinates. 

If this is considered a bug, consider it submitted. If not, feel free to ignore! :)

**Comment by ferazambuja** [comment]
Or maybe save the credentials?

Great work!!
