### ISSUE TITLE
Strange searcharea

### ISSUE THREAD

**Issue by Nintech** [mchristopher/PokemonGo-DesktopMap#1101]
Hi,

just updatet the great program but now I have strange searchareas. The search is no longer performed in a circle and doesn´t start on the marked spot but guessed to or three circles south-east of the selected marker. 
Any ideas how to change that? Thanks

**Comment by CoastalSlam** [comment]
I also noticed this new search pattern and would prefer the circular pattern can we be given a chose to select the pattern we want?

**Comment by jasonasey** [comment]
I have the same issue. Its annoying and makes it really hard to use now

**Comment by Gentleman-Taco** [comment]
No way, this is better, much harder for Niantic to easily see predictable routes to ban the account with.

**Comment by jasonasey** [comment]
That might be true, but at least let it start on the marker

**Comment by CoastalSlam** [comment]
There is still a pattern either way, But like i said if we had a choice we could change up the pattern and that would make it harder for Niantic to detect.

**Comment by juggalokyle** [comment]
This new scan pattern is annoying. Bring back the scanning to start where I put my marker. How do I get this back?

**Comment by tangrl** [comment]
It's particularly hard to use when on Server mode and connect from a cell phone. When I spot a good Pokemon in Pokemon Go I'd like scan from my current location and circle out. It takes a while for the new search pattern to search the area close to me. Lot of times the Pokemon is already gone.
