### ISSUE TITLE
New scanned locations colors

### ISSUE THREAD

**Issue by nopejusttesting** [mchristopher/PokemonGo-DesktopMap#1104]
I prefer the old darker colors. It was easier to see. Maybe an option to switch between the old color and the new one?

Also what do the different colors mean for the spawn points?

**Comment by ark71** [comment]
The different colors represent how soon the spot will spawn.  Green means the spot currently has a spawn, blue means it will spawn soon and purple means it won't spawn for awhile.  I don't have exact times when they change colors.  This is all from my observation.  Also, the spawns will change colors when, for instance, a spot that currently has a spawned a pokemon will gradually turn yellow then orange the closer it is to the end of the spawn time.
