### ISSUE TITLE
SCAN MY WHOLE CITY?

### ISSUE THREAD

**Issue by zapii2002** [mchristopher/PokemonGo-DesktopMap#1105]
Can someone help me how to scan my whole city? Right now its just scanning a little bit of the city

**Comment by nopejusttesting** [comment]
Two ways.
First is the easiest. Before you login, change the scan radius to something like 40. It will take awhile and
be wildly ineffective but it will scan the whole city after a day or two

Second way is harder. It requires multiple PTC accounts. placed strategically and set to 4 or 5 radius. Once you get the first account scanning. Open a new window and login a 2nd account. You will get the hang of it but....
really there is no need to actively scan an entire city. To each his own I guess.

**Comment by zapii2002** [comment]
@nopejusttesting If im trying  to open the 2nd window my 1st will stop to work. Do you know how to fix it?

**Comment by zapii2002** [comment]
@nopejusttesting it says if i have "Larger numbers increase search area but updates are slower." Does that means that the pokemons will get slow to spawn out on the map or what? i have it on 3 right now and all the pokemons spawn with like 14 minutes and if i have it on 40 will they spawn at 1 minute left? or what?

**Comment by magicdev2** [comment]
yes the longer the radius the longer it will take to load all of that pokemon for example if a pokemon came out 2 mins ago you will find out in 4 mins

**Comment by iPaulis** [comment]
Pokemon have a fixed spawn time, is not related to the map at all. Another thing is when the map registers the pokemon and how much time they have left until despawn. If the radius number is higher it will take more time to complete the whole scan, thus the refresh time will be higher. If a pokemon comes out now in my house and my map is scanning another area, I will have to wait until the maps scanner arrives to my house so it can load the pokemon that came out, the longer it takes the scanner to arrive the fewer minutes the pokemon will have left to despawn.

**Comment by magicdev2** [comment]
yes i know but it also the map and how fast it can load

**Comment by magicdev2** [comment]
the pokemon may have a fixed spawn time you wont even know if theres a pokemon there if the map doesnt load
