### ISSUE TITLE
Ranges?

### ISSUE THREAD

**Issue by ultimate2106** [mchristopher/PokemonGo-DesktopMap#1106]
So what is this new Option "Ranges" and what's the meaning of the different colors for the range circles and spawn points?
And the fuck is wrong with the search pattern lol :D

**Comment by ark71** [comment]
Ranges show how far away the pokemon, gym or pokestop can be accessed from.

**Comment by ultimate2106** [comment]
> Ranges show how far away the pokemon, gym or pokestop can be accessed from.
Thank you! And what is the meaning of the colors?

**Comment by baf2099** [comment]
I just downloaded the 0.3.3 for OS X and I don't have the ranges option or the colored spawn points with timers =[

**Comment by ark71** [comment]
Don't quote me on this, but from my observations the different colors represent how soon the spot will spawn. Green means the spot currently has a spawn, blue means it will spawn soon and purple means it won't spawn for awhile. I don't have exact times when they change colors. This is all from my observation. Also, the spawns will change colors when, for instance, a spot that currently has a spawned a pokemon will gradually turn yellow then orange the closer it is to the end of the spawn time.  Also, if you hover your mouse over a spawn spot it will tell you when that spawn will occur.

**Comment by adrianroditis** [comment]
Sounds like a valid answer but I would love a confirmation from admins :)
