### ISSUE TITLE
where are the pokemon??

### ISSUE THREAD

**Issue by dylanf1996** [mchristopher/PokemonGo-DesktopMap#1107]
Am operational but  haven't seen a pokemon in hours, ive restarted 5x... any ideas?

**Comment by juggalokyle** [comment]
I'm getting the same problem right now. Tho I have another map running on version 3.2 that is able to scan some Pokemon.

**Comment by dylanf1996** [comment]
oh, how did you avoid the update?

**Comment by juggalokyle** [comment]
Cuz it's been running nonstop since a couple days ago
