### ISSUE TITLE
Don't update to Version 0.3.3, it's a mess

### ISSUE THREAD

**Issue by CelloDE** [mchristopher/PokemonGo-DesktopMap#1113]
Scanning not working properly, stops random after a time, can't use more than 1 scanner.

**Comment by dylanf1996** [comment]
has anyone had a single pokemon pop up on version 3.3? I havent ... says am operational too

**Comment by CoastalSlam** [comment]
i have  pokemon showing up  on version 3.3

**Comment by baf2099** [comment]
I have pokemon showing up on version 0.3.3 on OS X, however the show ranges option and the colored spawn points aren't working

**Comment by dylanf1996** [comment]
Those actually work for me i just got no Pokemon showing up, even the gyms are consistently up to date

**Comment by lycenthedead** [comment]
Same, no pokemon

**Comment by baf2099** [comment]
Are you on Windows or OS X? If OS X I'm now sure how it possible for the show ranges to be working for you, I dove into the package contents and it looks like maybe the wrong files got packaged for this release because I can't find any reference to the show ranges item that should be in the options

**Comment by youtubesteak** [comment]
Everything is working fine for me, on Windows 7 x64. Scan pattern has changed, but scans and ranges are working correctly.

**Comment by baf2099** [comment]
Can anyone else confirm this issue in the OS X release?

**Comment by mwoelky** [comment]
Just updated right now from 3.3.2 to 3.3.3 on OSX 10.9.2 (with python 2.7.12).  Everything seems to work as expected.  I'll keep you posted if issues would arise.

**Comment by lycenthedead** [comment]
Map works fine on my normal machines, issues with pokemon only seem to arise on my VPS machines. Could Python version out of date cause this maybe? Only thing I haven't checked

**Comment by galaxy9999** [comment]
Aside the problem you reported, none of you have JavaScript error on multiple window set up on Windows?

**Comment by dylanf1996** [comment]
am on windows 7, I never had problems before but i just cant get any pokemon to show up anymore

**Comment by dylanf1996** [comment]
I have a warning in the console saying cannot read property style of nule. anyone know what that means?

**Comment by warsaws** [comment]
Working for me except the scan radius is a half hexagon shape.

**Comment by tangrl** [comment]
It works on OSX and Windows 10 (Parallels). On my Windows 8 machine, it's giving the endless errors when turning developer tools:

[    db-updater-0][        models][ WARNING] NOT NULL constraint failed: scannedlocation.scanned_id... Retrying

Any idea how to fix it?
