### ISSUE TITLE
Ranges option and Spawn Point colors not available on OSX

### ISSUE THREAD

**Issue by baf2099** [mchristopher/PokemonGo-DesktopMap#1114]
I just downloaded the 0.3.3 for OS X and I don't have the ranges option or the colored spawn points with timers =[. Has the OS X version not been updated the same as the Windows version?

**Comment by dripsin** [comment]
I has its working for mine. (using OSX)

**Comment by baf2099** [comment]
So my question then is how is this possible? The OS X app is a packaged application correct? If we download the same exact zip package and run from there how can you have code that I don't. Or is there something that running earlier versions has installed on my system that I need to wipe out in order to allow the newer version to function correctly?

**Comment by dripsin** [comment]
You probably still have the left over data in application support. Delete the folder and let it recreate itself. Note it will delete your data base. I would save that just incase you want the Pokemon spawn data. Let me know if you need help finding it.

**Comment by adrianroditis** [comment]
What do the colors mean?

**Comment by carlvandal** [comment]
found this when poking around tonight.

```
// purple when spawn is neither about to spawn nor active
// green to red over 15 minutes of active spawn
// light blue to dark blue over 5 minutes til spawn
```
