### ISSUE TITLE
Database

### ISSUE THREAD

**Issue by gauravyadav26** [mchristopher/PokemonGo-DesktopMap#1115]
Please send me the database file of your scan everyone, I'm trying to build a collective database.

**Comment by PhilipposVassil** [comment]
how can i do that?

**Comment by warsaws** [comment]
Would like to contribute as well and see more data, how do we do this? Where is the file stored?

**Comment by gauravyadav26** [comment]
File is stored at C:\Users\username\AppData\Roaming\pokemon-go-map and file name is pogom.db
and send that file to me on my email gauravyadav2601@gmail.com, I have created a website where I upload gym, pokestop and nests location http://www.pokegym.ga/
