### ISSUE TITLE
[Electronic/Desktop App] Scanner Location Pin resets itself even with Lock function

### ISSUE THREAD

**Issue by DrewGH** [mchristopher/PokemonGo-DesktopMap#1116]
Noticed on the newest 0.3.3 version that even if you have the scanner pinned to a location, even with the "Lock" function enabled, after a while the scanner resets back to either:

1) where your location is or 2) original address of whatever is on the input -- whichever happens, you lose your scan area and it starts scanning by itself of wherever it defaulted back to.

This is with "Scan Follows Location" box enabled, but "Start @ User's location" disabled; "Lock  marker" also enabled. Running multiple instances but noticed that each window of PoGo-Map (all separate accounts/all functioning correctly/non banned etc) eventually all collapsed or resets onto your original/default location, which obviously isn't good.

Scanning also seems faster but stops functioning after a while or is faulty; even setting a new pin/location does not work and requires a restart of the app

**Comment by djmn** [comment]
I've had this same issue with this version and the last couple versions as well. Every evening the scan position moves to the same spot over by Como. I don't think I've ever scanned this area. Is there a way to fix this? Also, is there a way to change the scan location from the mobile, once this issue occurs?
