### ISSUE TITLE
Scan disapears in the middle..

### ISSUE THREAD

**Issue by zapii2002** [mchristopher/PokemonGo-DesktopMap#1117]
Okey so when i scan for the pokemons i can see on the "scanned locations" that its disapears in the middle and the "scanned locations" keep getting bigger and bigger and the whole in the middle are getting bigger and bigger. The scanning option is on 5. Anyone here knows how to fix this? Here is how it looks: https://imgur.com/a/EHiJX

**Comment by Takekin** [comment]
You need to restart the search

**Comment by zapii2002** [comment]
How do i do that?
>
>
