### ISSUE TITLE
Hi, where do I find the stats with the pokemon spawn hour locally? Thanks

### ISSUE THREAD

**Issue by adrianroditis** [mchristopher/PokemonGo-DesktopMap#1118]
Hi, where do I find the stats with the pokemon spawn hour locally?
Thanks

**Comment by dripsin** [comment]
Im not the guy who made this but correct me if i am wrong. There might be a database file that is associated with the package. If i recall they are sql files. Before this map program became a desktop app there was a guide with the original pokemon go map. If you can find it i think ti will help you with your answer.

**Comment by adrianroditis** [comment]
@dripsin Thanks a lot! Any idea where to find it on Windows? I was able to find a pogom folder but not the .db file.

**Comment by ding-kan** [comment]
And @dripsin, what program would you suggest on mac for looking at that .db file? Thanks.

**Comment by dripsin** [comment]
I think there's a program he mentions in the read file. I don't recall what it is. If I was to guess I think it's called MySQL but I'm lazy to check.

**Comment by dripsin** [comment]
I think for Windows it's at C:\Users\username\AppData\Roaming\pokemon-go-map.

The file should be called pogom.db

**Comment by adrianroditis** [comment]
Works like a charm. You are a magician
