### ISSUE TITLE
Detecting Pokémon but not on map

### ISSUE THREAD

**Issue by heyitzdinny** [mchristopher/PokemonGo-DesktopMap#1119]
In log it detected Pokémon but in the actually map none are shown.  Example : parsing found 5 Pokémons, 5 gym, etc. also stats show Pokémons but map is none.

**Comment by dylanf1996** [comment]
same..

**Comment by dripsin** [comment]
How long do you let the map run before you check it? If too soon and the radius is too small then you wont see it till it gets to that pokemons position. If you wait to long with the search function enabled then you might overshoot the pokemon thus resulting in newly spawned pokemon around you to not be seen. Play with the slider that says "Scanned Locations" to see if it might be user error.

**Comment by dylanf1996** [comment]
![untitled](https://cloud.githubusercontent.com/assets/21204225/18176299/a3d1d1d0-703a-11e6-84f2-eba6d04757bd.png)

**Comment by heyitzdinny** [comment]
Same log as me.  Still no solution ?
