### ISSUE TITLE
How do you stop an individual scan when running multiple scanners on one map API?

### ISSUE THREAD

**Issue by CoastalSlam** [mchristopher/PokemonGo-DesktopMap#1120]
How do you stop an individual scan when running multiple scanners on one map? I'm running 4 scanners on one map API and need to know how to stop and start one of the scanners.

**Comment by dripsin** [comment]
Depends. From my experience(if you didn't modify the app itself) all you would have to do is unselect the search slider. That will terminate the search function of that scanner.
