### ISSUE TITLE
How to downgrade to v 0.3.2

### ISSUE THREAD

**Issue by manojrajput** [mchristopher/PokemonGo-DesktopMap#1121]
After uninstalling v.0.3.3, when i install v0.3.2 i get "please wait" and in "tooglr developer tools" i get upgrade your code or clear you database." 

can anyone please tell me how to clear database to get v.0.3.2 worked again.

**Comment by ultimate2106** [comment]
You can find your DB here C:\Users\username\AppData\Roaming\pokemon-go-map

**Comment by manojrajput** [comment]
Thanks.. now i am able to install 0.3.2
