### ISSUE TITLE
Any way to keep all the data (not just past 24 hr)

### ISSUE THREAD

**Issue by adind** [mchristopher/PokemonGo-DesktopMap#1123]
Is there a way to have it keep all the data instead of just the past 24 hours?

Thanks!

**Comment by Sedare** [comment]
yeah, same, im about to go back to the previous release.

**Comment by youtubesteak** [comment]
![image](https://cloud.githubusercontent.com/assets/20827977/18175677/1dde0f0c-7040-11e6-8aeb-d492f38e318b.png)

Mine is working fine... Are you using the options to change criteria?

**Comment by adind** [comment]
How exactly do I do that?

**Comment by youtubesteak** [comment]
In the map, click Stats in the top right, then when in stats, click the options cog in the top left and it should give you these options to choose from.

**Comment by Sedare** [comment]
Works perfect. I did not know you had to be in full stats mode to show this menu. This was the option I had been requesting a while back. :D

**Comment by youtubesteak** [comment]
@Sedare Haha, well good. It's actually been in there for a while. My only issue is with my older db files, the 500 hour pokemon show, so I only have ~2 weeks of data without including those. I just haven't taken the time to go through and clean those up, but with a decent SQLite manager, you can do anything you want with the db file that you can do with SQL, like create e-mail alerts using triggers, view in-depth data, custom views, etc.
