### ISSUE TITLE
System notification issues (Win10)

### ISSUE THREAD

**Issue by PastyIsTasty** [mchristopher/PokemonGo-DesktopMap#1124]
System notifications generally don't work at all. The Pokemon is correctly identified and has the bounce animation in the app window, but no notification comes from the system.

Sometimes the notification will work correctly, not sure what the difference is.

Sometimes when a notification works correctly, an old notification that wasn't sent is triggered at the same time.

Any known workarounds for this?

**Comment by adrianroditis** [comment]
Get notified for less pokemons? The important ones. If you get more notifications at once, the system can get confused

**Comment by PastyIsTasty** [comment]
The settings I have would typically give me about 1 notification every few hours. Only in testing the issue did I set it up for more, so I don't think that's the problem.

Notifications used to work fine for me in v0.2.1
