### ISSUE TITLE
[Suggestion] Multiple account in grid

### ISSUE THREAD

**Issue by JohanJu** [mchristopher/PokemonGo-DesktopMap#113]
Is it possible to use a account list and position them in a grid pattern from the same instance of the app?
![Image](http://i67.tinypic.com/1zewh13.jpg)

**Comment by andrewda** [comment]
This is possible in the newer versions of PokemonGo-Map. This repo should be updated to use that instead, as it has a lot of improved/fixed features.

**Comment by emliv** [comment]
I would love a "saved locations" feature - right now I have a wordpad document of the coordinates I use most that I copy and paste from.
