### ISSUE TITLE
Not work

### ISSUE THREAD

**Issue by mattiasusta** [mchristopher/PokemonGo-DesktopMap#1131]
i have installed the app for windows but after the access i see only the map without pokèmon

**Comment by ndsvw** [comment]
do you get the messagt "possible ban" at the top?

**Comment by carlvandal** [comment]
My app works great, installed late yesterday night and have been running it since, works great. (I use PTC account)

**Comment by mattiasusta** [comment]
No i don't 

Mattia

**Comment by carlvandal** [comment]
@mattiasusta 
Yeah that's the same as I installed, make sure the software is allowed through windows firewall aswell, i got a prompt and i almost just clicked OK thus only allowing it on public networks, maybe you did that when starting the app?

**Comment by mattiasusta** [comment]
@carlvandal 

I have tried installing it again and noticed that out this warning:
[http://it.tinypic.com/r/11ipp9t/9](url)

what i can do?

**Comment by dripsin** [comment]
You might try updating your java, restart the program, uninstall then reinstall the program, and restart your computer. This should help but if it doesn't you might be missing some of the requirements. Also make sure you are grabbing the releases since they will be the whole package that you need.
