### ISSUE TITLE
Can't add second PTC account right away: how to use the new multi account feature??

### ISSUE THREAD

**Issue by Nonkel** [mchristopher/PokemonGo-DesktopMap#1133]
First PTC account can be added. When trying to add a second PTC account, I get the message:
Oops, something went wrong and we couldn't log you in. Please try again. Unable to get login session from Pokemon SSO.

What does that mean? All my PTC accounts worked normally on previous version. I was really enthousiastic about this multiple account thingy...please help me get this to work!

**Comment by Nonkel** [comment]
Update: when I log in with my first account, and then start a new instance of the program, I CAN add a second account. Not sure how this works atm...

**Comment by homerfan123** [comment]
same here

**Comment by iPaulis** [comment]
I added a PTC account, then a google account in the same instance, no problem.

**Comment by torantal** [comment]
I was able to add three accounts, but can only see scanned locations for two accounts and don't understand how the three accounts would actually share the one location you can provide.

**Comment by AnarkhiA** [comment]
I just did what Nonkel did, closed all the instances of the app. restarted it and it did started running, (search pattern is all messed up?) my search doesn't seem to go any faster.

**Comment by damnitimlost** [comment]
I added 3 accounts to a single instance. Not sure if it's speeding up anything? Any way that we can map 3 locations with 3 accounts?

**Comment by Nonkel** [comment]
Since I want to add 4 accounts, I would also expect there to be 4 fields to enter 4 different locations...not?

**Comment by homerfan123** [comment]
Would be great if maybe mchristopher give some description of his added features.. was thinking the same as Nonkel but how are multiple accounts managed in one location? Is there some calculation of how big the scaning radius is and amount of accounts => the accounts start xx minutes after each other???

**Comment by jasonasey** [comment]
Has anyone figured out what the second account is doing?
Is it possible to get them to scan two different locations at once?

**Comment by AnarkhiA** [comment]
as far as I tried it does nothing. I tried widening the scan area that didnt speed up. I tried opening the map twice, but that doesnt work either.

**Comment by AnarkhiA** [comment]
__update__ 

I got bored and decided to add some more ptc accounts in the desktopmap, what happened is marvelous! if I use two accounts only one is activly scanning, but when I added a third, a second account started scanning the map, I am now at five accounts and four of them are actually scanning. I am happy with this.

**Comment by zapii2002** [comment]
How do i know if its multi scanning?

**Comment by AnarkhiA** [comment]
it adds more search bubbles at the same time, CQ it goes alot faster.

**Comment by Nonkel** [comment]
Yup thats how it works I discovered after restarting the program. I have 4 PTC accounts added. It scans multiple areas at once now. So I had to abandon my previous strategy of 4 scans each with its own marker. Instead I widened the radius to 8 (!) and it works like a charm!

Only negative, the form of 1 scan is different ofcourse, so I cant cover all the area I did with 4 separate scans...

**Comment by CoastalSlam** [comment]
How about when you add the logon account you also add a set of longitude and latitude so we can scan different areas instead of 1 big area. And give us a choice of the scan pattern.

**Comment by galaxy9999** [comment]
I have not updated because of the fear of JavaScript error. Does this version do not require you to open multiple  instances of the program (like all previous versions) while still able to run multiple location scan.

**Comment by AnarkhiA** [comment]
No! Just add one more than you want.

**Comment by nwydev** [comment]
galaxy9999, how did you stop the update from happening?  When I started 0.33 today, there was a banner message saying an update is available.  I ignored it and did some scanning.  Later, I exited the program and restart, it has already been updated to 0.34.

**Comment by dripsin** [comment]
@AnthonyButler012 He is right. Another method that i use is i start the server with my first account then i stop it and add the others one at a time doing this process over till i have my desired accounts on.

**Comment by Nonkel** [comment]
What I would like to know is how I can tell an account has a possible ban. Before, this would display at the top. But now, since Im using 5 accounts in 1 window, how can I tell if one of those accounts stops scanning because its banned?

**Comment by AnarkhiA** [comment]
Maybe make a new request for that. This topic is getting littert

**Comment by Cooleronie** [comment]
I have the same issue. However, a quick fix is to 1) Add PTC account 2) Tools -> Refresh 3) Add PTC account etc.

A whole lot faster than restarting the app every time.
