### ISSUE TITLE
Updated the map and full stats information is wiped

### ISSUE THREAD

**Issue by blahblah3141** [mchristopher/PokemonGo-DesktopMap#1135]
This information was very useful to me - and not sure if this is a bug or intentional. In any case, can I get that information back through some left over files?

**Comment by damnitimlost** [comment]
Same here the old Database was wiped? Can it be restore?

**Comment by zexpe** [comment]
I think it might be because the database schema has changed: spawn points now contain extra information about when pokemon spawn at them.

**Comment by blahblah3141** [comment]
Spawnpoint data was present in last update as well (0.3.3). The multi-account update, which has seemingly not changed spawnpoint data, is the one causing the issues. In any case, I just need to know if there is an old database file saved on my computer which I can retrieve to find my lost stats data.

**Comment by nakratz** [comment]
You can find the old DB file in your /Users/*NAME*/AppData/Roaming/pokemon-go-map folder. There are now 2 db files. pogom.db which is the old one and pogomon-0.3.4.db

**Comment by gauravyadav26** [comment]
all you need to do is go to C:\Users\username\AppData\Roaming\pokemon-go-map and you will find old database by name pogom.db and new as pogom-0.3.4.bd. merge them and problem is solved.

**Comment by romanticheart** [comment]
Any idea where to find this on Mac?

**Comment by zexpe** [comment]
~/Library/Application Support/pokemon-go-map

**Comment by romanticheart** [comment]
Thanks! Not seeing it there unfortunately. Nothing about the app anywhere in Application Support.

**Comment by zexpe** [comment]
The one in your home directory Library (not the root directory one)?

**Comment by romanticheart** [comment]
That was the problem! Found it, thank you! Is there an easy way to merge them or shall I go on a google search to learn new things?

**Comment by jwever** [comment]
sqlite3 pogom.db .dump | sqlite3 pogom-new.db
sqlite3 pogom-0.3.4.db .dump | sqlite3 pogom-new.db
cp pogom-new.db pogom-0.3.4.db

Worked for me. You may want to make a backup of pogom.db & pogom-0.3.4.db first just in case.

**Comment by romanticheart** [comment]
I'm mostly a newb with this stuff, just good at following directions, so please excuse my ignorance. Are those Terminal inputs?  

Also, looking at the commit for this, it sounds like this is something that will need to be done each time the program is updated. I don't really understand the logic behind changing the .db source for each version.

**Comment by zexpe** [comment]
Worked for me too, but some of the errors explain the reason for the new database, the schema has changed for gyms at least:

`Error: near line 23: table gym has 8 columns but 9 values were supplied
Error: near line 28: table "pokemon" already exists
Error: near line 128: table "pokestop" already exists
Error: near line 129: UNIQUE constraint failed: pokestop.pokestop_id
`

Not sure how important this is and what if anything is lost by keeping the old schema. It's possibly safer to construct the new database from the 0.3.4 file first.

**Comment by romanticheart** [comment]
Starting to think I should just wait for the next update. There seems to be a lot of issues with this one. I'm also finding that the scan does not restart after it finishes one search of the area. I have to manually restart it. Assuming a green spawn point means there is a spawned Pokemon there, but I have multiple on my map showing no Pokemon.

**Comment by zexpe** [comment]
Green means a Pokemon has spawned there but it hasn't been scanned yet: there's about a 10s delay between each scan location, so if you are scanning a large radius then it will take a long time before it has scanned a particular spawn point to see what Pokemon has spawned there.

**Comment by romanticheart** [comment]
Only a radius of 3. I moved the marker right on top of one of the green spawn points, have scanned locations on so I see that it scanned that spot, but no Pokemon.

**Comment by romanticheart** [comment]
![screen shot 2016-09-02 at 12 02 53 pm](https://cloud.githubusercontent.com/assets/20682231/18210159/333b287e-7105-11e6-9f5f-92ead7baa1e8.png)
![screen shot 2016-09-02 at 12 02 42 pm](https://cloud.githubusercontent.com/assets/20682231/18210163/34cff7be-7105-11e6-8141-56e85df73a1d.png)

**Comment by zexpe** [comment]
A radius of 3 means 15 scan locations and so it'll take about 2-3 minutes to cover them all. Once they are covered they remain green for about 15 minutes. So they will always be green with a scan radius of 3, but you still may have to wait up to 3 minutes for the spawned Pokemon to be scanned.

**Comment by zexpe** [comment]
It did stop scanning on me once, but logging out and logging back into again worked.

**Comment by romanticheart** [comment]
Nah I understand that. What I'm saying is that when I saw the point go green, I manually moved the location pin directly on top of it, which began a new scan at that point. I watched the green scanned location circle pop up right there, no Pokemon.

**Comment by zexpe** [comment]
I've not seen that before, but I guess it may be possible, because I have seen a Pokemon spawn at a different time than the spawn point expected it to spawn (20 minutes earlier), so perhaps it's possible that spawn times can change, in which case an expected spawn won't occur.

**Comment by romanticheart** [comment]
Here's an interesting thing. I can hit one spawn point from my desk. From my experience, it spawns every hour on the hour while I'm at work. Been like this since the game came out. But according to the map info, It should be spawning at :27. Is it possible timing is off in the map somehow?

**Comment by zexpe** [comment]
Is that 0:27 as in 0 mins 27s?

**Comment by romanticheart** [comment]
It says "Every hour from 00:27 to 15:27", so I assumed that means it would spawn at, say, 12:27, 1:27, 2:27, etc. Unless I'm misunderstanding.

**Comment by zexpe** [comment]
No, that's minutes and seconds past the hour (every hour).

**Comment by romanticheart** [comment]
OH, wow, I feel a little dumb right now. Suddenly it all makes sense. Thank you! Main issue now is that it still only scans once around the set radius and then just sits there until I move the pin again.

**Comment by warsaws** [comment]
Could anyone explain how to use my old database data with the new updated version? Can I just rename the old file with the new file name to replace it?

**Comment by pokemapcomments** [comment]
If I roll back to a previous version, will it automatically pull up the old spawn database? Is there a way to get it to merge the old and new formats?

**Comment by pokemapcomments** [comment]
Why was this issue closed? I'm still not able to see the old statistical data.
