### ISSUE TITLE
Scan where I drop pin

### ISSUE THREAD

**Issue by Rayenous** [mchristopher/PokemonGo-DesktopMap#1136]
The newest version scans the region starting from a point other than where I dropped the pin/marker.  -  When I want to do a quick scan of a small area, I need to be able to drop the pin, wait 10-20 seconds and move on.  Now if I want to scan an area, I have to wait a few minutes for it to finally scan the location I want.

How do I tell the app to scan starting from the place the pin is dropped?

**Comment by LuckyYou** [comment]
Same thing happened with min- i just adjusted the pin so the scan is present in the area i want it.. 
<img width="487" alt="screen shot 2016-09-02 at 10 48 35 am" src="https://cloud.githubusercontent.com/assets/20827882/18207843/dab952de-70fa-11e6-927e-771a83c9fa86.png">

**Comment by PokeTrainerHeinrich** [comment]
This is not a bug. Just wait for the complete scan. It depends on your range. The scan now goes the other way round. It starts at the outside and goes to where the pin is. So it still works fine, but different than before.

**Comment by kingkush666** [comment]
Why have you done it this way? To me that makes no sense. Naturally i want to search the areas that are closest to where i drop the pin. It is easier to controll where the search is being done..

**Comment by PokeTrainerHeinrich** [comment]
There is no difference to the way it was before. If you want to have closer range just set the range to a smaller number.

**Comment by kingkush666** [comment]
okey. Sorry for noob question but how do i do that?

**Comment by PokeTrainerHeinrich** [comment]
When you start the application, just before you login, scroll down, you have a point with "scanning options". The lower the number, the nearer the range. I usually have set it on 2. That is what I also can see with my phone and also reach within a minute or two. Just try out some settings to find you best fitting.

**Comment by kingkush666** [comment]
Ok, thanks for the fast respons :)

**Comment by mchristopher** [comment]
Map usage issues or questions should be reported at https://github.com/PokemonGoMap/PokemonGo-Map.

**Comment by Rayenous** [comment]
This wasn't a Map usage issue.  It's a design flaw.
