### ISSUE TITLE
Forever Waiting

### ISSUE THREAD

**Issue by NickHab** [mchristopher/PokemonGo-DesktopMap#1138]
I can log in but then the button at the middle of the top just says waiting forever. Any ideas on what the issue is?

**Comment by AnarkhiA** [comment]
try different account & api key/

**Comment by aibo1** [comment]
Same issue here. Account and API key are fine. Eventually the "Waiting" turns to "Possible Ban" but the account isn't banned -- I'm using it on my phone right now. Everything worked fine until I upgraded from DesktopMap 0.2.1
