### ISSUE TITLE
long scanning time

### ISSUE THREAD

**Issue by ajoin007** [mchristopher/PokemonGo-DesktopMap#1139]
Hey,

Thx for your awesome scanner. Perhaps this is not an issue but is it normal it takes like 30 seconds to scan 1 little location (1 green circle)?
What are the different colours of the spawnlocations?

**Comment by DrHeinz** [comment]
Takes 10 seconds, that's normal.

Would like to know the spawnloction colours as well.

**Comment by torantal** [comment]
from my observations:

Blue is "will spawn soon"
Green is "spawned just now"
Yellow is "about 7 minutes left"
Red is "is about to despawn"
grey is "no spawn right now"

**Comment by dripsin** [comment]
Add more accounts with the new feature. Theres a few comments at the end of #1133 that should help you.
