### ISSUE TITLE
[MAC OSX] no map is shown

### ISSUE THREAD

**Issue by s4ty** [mchristopher/PokemonGo-DesktopMap#114]
After the last update from yesterday I am not able to see the map anymore. 

App freezes at this state (default settings):
![bildschirmfoto 2016-07-22 um 07 24 38](https://cloud.githubusercontent.com/assets/1499134/17047355/6892bd64-4fdd-11e6-9fbc-c24d6ebae500.png)

**Comment by andrewda** [comment]
Open the dev console. Are there any errors?

**Comment by s4ty** [comment]
yes:
`Error: Cannot call loadURL because the webContents is unavailable. The WebView must be attached to the DOM and the dom-ready event emitted before this method can be called.(…)`
main.html:196

**Comment by andrewda** [comment]
Hmm, interesting. I'll look into fixing this issue. In the meantime, you might be able to spam refresh it in hopes that it will load.

**Comment by s4ty** [comment]
I'll roll back to Version 0.0.6. This version still works for me.

**Comment by themrkevin** [comment]
same for me but my error is
Python: /usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python: can't open file './example.py': [Errno 2] No such file or directory
