### ISSUE TITLE
I do believe I was just instantaneously IP banned on this new version

### ISSUE THREAD

**Issue by getmeabeer** [mchristopher/PokemonGo-DesktopMap#1140]
I set up 20 accounts, started up the map, and it started scanning...but no pokemon showed up. Checked my phone on my main account...no pokemon nearby. Disconnected from my wifi...Lots of pokemon nearby. The new version seems to have gotten me IP banned the instant I started it up.

Used the most recent version for 3 days with 20 accounts, with no problem at all.

**Comment by PokeTrainerHeinrich** [comment]
How can you use the most recent version for 3 days now? There has been an update today and yesterday. Maybe you just should update you application.

**Comment by getmeabeer** [comment]
Version 0.3.3
@mchristopher mchristopher released this 3 days ago

**Comment by PokeTrainerHeinrich** [comment]
Yeah, the most recent version is 0.3.4.

**Comment by getmeabeer** [comment]
Are you retarded? I used 0.3.3 for three days with no problem. 0.3.4 is what got me the IP ban instantly, using 20 accounts. Please try to learn English before being such a prick for no reason.

**Comment by PokeTrainerHeinrich** [comment]
If you don't know any manners I don't think I will help you anymore. I know English, but you wrote that you use it, not that you used it. Also there are no problems with the recent version. I have several accounts, not a single ban. So maybe the mistakes is not in the program but in front of your pc.

**Comment by getmeabeer** [comment]
"Used the most recent version for 3 days with 20 accounts, with no problem at all."

"you wrote that you use it, not that you used it"

...Anyway, I wasn't looking for help from you. I was IP banned when using 0.3.4, with the same number of accounts (20) that I was using on 0.3.3. I was just letting everybody know. You literally have mental problems and you should consider seeking help for your anger issues.

**Comment by PokeTrainerHeinrich** [comment]
Yeah, well, if you edit your comment after that, nice try.
The only one with mental problems is you. You are the only one with the problem here, think about it. Pretty obvious where to find the problem.

**Comment by getmeabeer** [comment]
You really think I edited my comment after the fact? Like I've been carrying on this whole exchange just to try to pull the wool over your eyes? This is all a big conspiracy? Are you actually that insane?

**Comment by PokeTrainerHeinrich** [comment]
No, I actually can see that you edited it. But that is not my cup of tea. You think this is a big conspiracy when you think that all your accounts get banned. Even if you think it is only your IP it is really bad if you cannot fix it. I mean, everybody knows how to reconnect and get a new IP. But yeah, this requires a certain level of intelligence.

**Comment by getmeabeer** [comment]
You believe that, on a home modem, you literally just reconnect your modem and you get a new IP? You have got to be trolling me. Nobody is that stupid.

Anyway, it was a temporary ban and not a huge issue, but it only popped up in the most recent version, and I've now been using fewer accounts with no problem. I was merely letting the creator of this program, and others interested, know the issue that I had. I don't need some nobody that knows nothing coming on here spouting nonsensical bullshit about wrong versions.

**Comment by PokeTrainerHeinrich** [comment]
If you think that is not possible you are the one that is stupid. Every router can do that. I do that several times a day.
The only bullshit is your issue, since there is no issue. No one has the problem, so there is no problem. Maybe you should fix your internet and read the manual of your devices to see how you reconnect.

**Comment by getmeabeer** [comment]
"I reset my router several times per day to change my IP!!"

...right...Not crazy.

**Comment by PokeTrainerHeinrich** [comment]
I see, you don't have a clue what I do for a living. Otherwise you would understand that it is necessary to do it. But yeah, as said, that would require a certain level of intelligence. Couldn't find that on you so far.

**Comment by mchristopher** [comment]
Can we try to keep things civil?

Due to the way scanning works, it's possible Niantic can detect when many accounts work in tandem. Regardless, this is something to bring up with https://github.com/PokemonGoMap/PokemonGo-Map, not this project.
