### ISSUE TITLE
Include Google Maps API key to "Add Account" to improve performance?

### ISSUE THREAD

**Issue by nwydev** [mchristopher/PokemonGo-DesktopMap#1142]
Just wondering if it makes sense to include Google Maps API key as part of "Add New Account screen" so each account can use its own key?  Will that help performance?  Thanks @mchristopher for working so hard on this program!!!

**Comment by AVellucci** [comment]
The API key is unrelated to the scanner. The only purpose it serves is loading the Google map so you can see the area it's scanning. As it doesn't affect scan speed at all it wouldn't offer any improvement.
