### ISSUE TITLE
Include Longitude and Latitude to "Add Account"

### ISSUE THREAD

**Issue by CoastalSlam** [mchristopher/PokemonGo-DesktopMap#1144]
It would be nice to be able to scan multiple areas and if you have let say 8 accounts and you could identify 8 locations or even 4 locations to soeed up the scanning.

**Comment by torantal** [comment]
at the moment you can just set a larger radius and multiple accounts will speed up the scanning process by sharing the overall honeycomb shape between the different account

Personally I'd also prefer separate areas, as my target area is more L-shaped and I'm very much looking forward to scanning spawn points only.

**Comment by dripsin** [comment]
You might still be able to use more than one program to overlay the scans. Then you can position your accounts in each program. If you need help let me know.

**Comment by torantal** [comment]
I guess I can scan one honeycomb per running program, each using the number of accounts provided when started for the respective honeycomb?
