### ISSUE TITLE
scanning start location is not saved

### ISSUE THREAD

**Issue by jimbofisher** [mchristopher/PokemonGo-DesktopMap#1145]
i set google map coordinates prior to logging in, and the marker also does not start at that point.

ever since the update, the starting marker seems to move without any rhyme or reason after a while. it also does not save the spot i had left it at.

this gets problematic as if i have to constantly move it manually it will look like i'm teleporting around the map

**Comment by AVellucci** [comment]
@jimbofisher How eratic is this? the PokemonGoMap project recently updated the scanning settings.
It no longer scans in a spiral, it scans in a pattern that starts and ends in the same location.

**Comment by jimbofisher** [comment]
the bug appears to be tied to screen resolution. if it changes the marker appears to move with it. if i'm playing a game which has a different resolution from native it looks like it messes with the scanner. this is a very puzzling bug since it has never happened until the recent update.
