### ISSUE TITLE
multiple scanning issue

### ISSUE THREAD

**Issue by pocketq10** [mchristopher/PokemonGo-DesktopMap#1146]
seems like i can only have a max of two scans going? i tried to open a third one and the 2nd scan stop showing pokemon but the third one does.

**Comment by ThigSchuch** [comment]
I'm with 6 accounts, the scan is so fast now, radius 15 scans in less 5 minutes

**Comment by pocketq10** [comment]
ah okay, guess i need an account for every scan, thanks thig

**Comment by nwydev** [comment]
@pocketq10 , radius 15 scans in less 5 min? wow that was fast.  I need 10 min for radius 12 scan.

**Comment by dripsin** [comment]
More accounts = Better coverage + speed(with diminishing returns)

**Comment by manojrajput** [comment]
how multiple account thing works? i have 2 accounts. How can i use 2 scan at same time at different points? Please suggest.

**Comment by ThigSchuch** [comment]
Manojrajput I found a small bug and I'll report, but that's how: From the home screen you put latitude and longitude, right? When you start, you change the marker once place, the accounts will separate and scan two places at same time, as the budy said, more accounts, faster and more areas are covered. Sry my english, 50% google translator

**Comment by manojrajput** [comment]
i tried as you said but it is still not working. May be i am doing something wrong. Anyway thanks for your help...
