### ISSUE TITLE
please try again.code 4

### ISSUE THREAD

**Issue by mj2266** [mchristopher/PokemonGo-DesktopMap#115]
[win]when i try to login in my google account nd click on accept..next thing it shows is that "oops..something went wrong and we couldnt sign u in.please try again .code 4"
wat should i do?i have windows 10 64 bit

**Comment by fenixasin** [comment]
thats a new one

**Comment by mj2266** [comment]
is there any solution??i have been trying from yesterday

**Comment by Mirx** [comment]
If for example you are behind a proxy you will get this error message, as the app can't connect to the internet.

It might also be your firewall settings.
