### ISSUE TITLE
better host? 

### ISSUE THREAD

**Issue by dedkob** [mchristopher/PokemonGo-DesktopMap#1151]
wonder how i can put another host the get more users to connect. it failed at 30 connections. anyone can help me?

**Comment by madkeeper89** [comment]
all users need to share one mysql database. 
you tried to connect 30 accounts with one database and it doesn't work ?

my friends & me using about 10 accounts with one mysql database and it works.

please more details for your issue.

**Comment by dedkob** [comment]
can i use my own mysql database server?

**Comment by madkeeper89** [comment]
sure you can use your own mysql server. but if your friends want to connect from outside (from his home) you need to open a port to the internet and give him your static IP Adresss. if you dont have a static IP, you need a DNS service.

i use a webhost mysql database server where my websites are hosted too.
easy to set up and allways online.

**Comment by dedkob** [comment]
could make tutorial how to do?
