### ISSUE TITLE
Please add option to block out some circles in pattern

### ISSUE THREAD

**Issue by NickIxo** [mchristopher/PokemonGo-DesktopMap#1154]
I would find it of immense value if you could label some scanned circles on the scanner as a skip zone.
Due to no/poor spawn points or inaccessible areas. in my area there are 2 factories which are entirely off limits to me and obviously consume huge portions of my scan zones when its all 1 giant conglomerate scan as it is with the new multi account feature. 
i would really like to extend my scan range/or change pattern to avoid these areas and hit more high value areas.
As an alternative, implementing multiple scan points with multi account would also be helpful, but in general blocking useless tiles might be simpler/more effective.

**Comment by 3Trace** [comment]
What would be even better is if it automatically skipped loading a circle that it already recognized has zero spawn points in it

**Comment by NickIxo** [comment]
As long as I have some manual control that would be nice.

**Comment by Nonkel** [comment]
That would be nice so you can customize the scan area to your likings. My town isnt an exact hexagon, I guess nobodies town is. So if you can skip a lot of areas, that would also speed up the proces and reduce the need for a lot of accounts.

**Comment by NickIxo** [comment]
Yeah as mentioned there are two giant factories in my immediate area (a carrier factory and a bottled drink factory) and they consume a lot of my resources as they are also near highly desirable scanning areas so they're unavoidable.

**Comment by AVellucci** [comment]
this should be requested on the PokemonGoMap repo, this project is just the wrapper for that map.
