### ISSUE TITLE
Auto login / "remember me" feature?

### ISSUE THREAD

**Issue by hillai** [mchristopher/PokemonGo-DesktopMap#1155]
Hi,
This is by far the best Pokemon map app I've seen, I've been using it for a while and it's really great. There's one feature that I'd really like to see in it - auto login. While the app does remember my account details, I still have to press the login button every time, which seems kind of redundant. Could you please add a feature to make the app auto login each time I open it? That would be great.
Thanks!

**Comment by blahblah3141** [comment]
Its only one button...
