### ISSUE TITLE
Google maps fails to load from home server but ok in cloud

### ISSUE THREAD

**Issue by 3shirts** [mchristopher/PokemonGo-DesktopMap#1157]
I have deployed to a Jelastic server and that works fine but the version I have installed to my home server just shows the Google Maps error "This page didn't load Google Maps correctly. See the JavaScript console for technical details"
If I look in the console I have: "Google Maps API error: InvalidKeyMapError" however I have put the same key into the Jelastic version and it works fine. Looking on the Google API dashboard I can see requests registering from the Jelastic version but none arrive from the home server so it seems like they are never even reaching Google.

Update: Ok, if I don't run it without the --host 0.0.0.0 switch, it works ok. That means I can only see it from the server itself though and not my main PC across the network. Any ideas?

**Comment by neilwick** [comment]
Have you got a restriction on which URLs can run that API key? Check on your Google API dashboard.

**Comment by 3shirts** [comment]
No, I have to referrers set.

**Comment by 3shirts** [comment]
I seem to have fixed it. I changed the switch to the host machine's local IP rather than using 0.0.0.0 and it is loading ok now.
