### ISSUE TITLE
When I move my marker, it continues with regular scan pattern instead of resetting to center

### ISSUE THREAD

**Issue by blahblah3141** [mchristopher/PokemonGo-DesktopMap#1159]
I normally leave my marker in one place and let it scan all around. However, sometimes I want to just quickly check one spot that is farther away, and I did so (in previous versions) by moving my marker there, letting it scan one circle, and then moving it back to my regular place.

However, in this version, if my normal marker scan is currently scanning, for example, the circle that is two circle units to the left of the marker, then when I move the marker, it continues scanning that circle and the circle next to it, etc, instead of resetting to the center like it should when a new position is made.

**Comment by blahblah3141** [comment]
![markerglitch](https://cloud.githubusercontent.com/assets/20790845/18229011/9a1a0a7a-7299-11e6-8e4c-18d7fd3d1b07.PNG)

**Comment by momoka575** [comment]
Me, too. We are looking for improvement

**Comment by scanner1129** [comment]
I think  this is the new scan behavior. The first scans are from the bottom of a 3 radius (I think). if you let it run you then see the 3 radius circle fill up, and then the top half of the whole area (from settings), and then the bottom half. 

That screenshot looks like it is working like it should in the latest version. The old version started from the marker center and spiraled clockwise.

**Comment by blahblah3141** [comment]
Got it.

**Comment by valdircasotti** [comment]
I would love to go back there before scanning method , it was more efficient , I hope an update
