### ISSUE TITLE
How to compile for os x

### ISSUE THREAD

**Issue by daproject85** [mchristopher/PokemonGo-DesktopMap#116]
can you please give instructions on how to compile source code for os x?

**Comment by ranrinc** [comment]
I want to get this information too..TIA

**Comment by MGrafe** [comment]
Just download the App for OSX

https://github.com/mchristopher/PokemonGo-DesktopMap/releases

**Comment by daproject85** [comment]
I want to make modifications

**Comment by hawkrives** [comment]
Install [NodeJS](https://nodejs.org), then go into the folder and run `npm install`.

After that's done, a simple `npm start` should open the app. Edit files and hit cmd/ctrl-R to refresh the app when you change things.

**Comment by Traxmaxx** [comment]
I assume you have NodeJS and Python (installed by default)

```bash
easy_install --user pip
```

the output looks something like this:
```logtalk
Searching for pip
Reading https://pypi.python.org/simple/pip/
Best match: pip 8.1.2
Downloading https://pypi.python.org/packages/e7/a8/7556133689add8d1a54c0b14aeff0acb03c64707ce100ecd53934da1aa13/pip-8.1.2.tar.gz#md5=87083c0b9867963b29f7aba3613e8f4a
Processing pip-8.1.2.tar.gz
Writing /var/folders/w3/nks_q4zs25jffj2rgnkzw1fm0000gn/T/easy_install-ql0yTM/pip-8.1.2/setup.cfg
Running pip-8.1.2/setup.py -q bdist_egg --dist-dir /var/folders/w3/nks_q4zs25jffj2rgnkzw1fm0000gn/T/easy_install-ql0yTM/pip-8.1.2/egg-dist-tmp-URSM6S
warning: no previously-included files found matching '.coveragerc'
warning: no previously-included files found matching '.mailmap'
warning: no previously-included files found matching '.travis.yml'
warning: no previously-included files found matching '.landscape.yml'
warning: no previously-included files found matching 'pip/_vendor/Makefile'
warning: no previously-included files found matching 'tox.ini'
warning: no previously-included files found matching 'dev-requirements.txt'
warning: no previously-included files found matching 'appveyor.yml'
no previously-included directories found matching '.github'
no previously-included directories found matching '.travis'
no previously-included directories found matching 'docs/_build'
no previously-included directories found matching 'contrib'
no previously-included directories found matching 'tasks'
no previously-included directories found matching 'tests'
creating /Users/traxmaxx/Library/Python/2.7/lib/python/site-packages/pip-8.1.2-py2.7.egg
Extracting pip-8.1.2-py2.7.egg to /Users/traxmaxx/Library/Python/2.7/lib/python/site-packages
Adding pip 8.1.2 to easy-install.pth file
Installing pip script to /Users/traxmaxx/Library/Python/2.7/bin
Installing pip2.7 script to /Users/traxmaxx/Library/Python/2.7/bin
Installing pip2 script to /Users/traxmaxx/Library/Python/2.7/bin

Installed /Users/traxmaxx/Library/Python/2.7/lib/python/site-packages/pip-8.1.2-py2.7.egg
Processing dependencies for pip
Finished processing dependencies for pip
```

Add ```/Users/YourUsername/Library/Python/2.7/bin``` to ```$PATH```
Then

```bash
cd ./PokemonGo-DesktopMap/map
pip install --user -r requirements.txt
cd ..
npm install
```

and you're ready to start the app with ```npm start```

**Comment by BinaryBeard** [comment]
@Traxmaxx `npm install` will run the pip install command. 

This: 
```
cd ./PokemonGo-DesktopMap/map
pip install --user -r requirements.txt
cd ..
npm install
```
Has been condensed to this ([#55](https://github.com/mchristopher/PokemonGo-DesktopMap/pull/55)): 
```
npm install
```

**Comment by Traxmaxx** [comment]
@BinaryBeard yes but it's installing them globally and that failed for me.

**Comment by misterpink14** [comment]
@Traxmaxx have you figured this out? What is your output? I had some issues and may be able to help

**Comment by daproject85** [comment]
does anyone know how to compile? nnpm start just runs it, doesn't actually make an executable ...

**Comment by misterpink14** [comment]
This should give you enough to build the app for osx/windows
http://electron.rocks/electron-angular-packing-and-distribution/

**Comment by Traxmaxx** [comment]
@misterpink14 everything is working fine. Except that I needed to install the Python packages with the ```--user``` flag.

The output before was ```/something/something not writeable```

**Comment by ranrinc** [comment]
I got npm start working properly and no problem. However upon distrib.sh it compile correctly with login screen. Upon login and pass Google its just hang on white screen. Any idea? Running on Mac

**Comment by hawkrives** [comment]
My first step would be to open the devtools from the View menu and see if there are any errors shown in the Console tab.

**Comment by misterpink14** [comment]
@ranrinc have you checked the node logs? What are you seeing in the terminal when this happens? Any errors from dev tools would also be useful

**Comment by ranrinc** [comment]
@misterpink14 so far when I npm start it work perfectly. Only if I compile it using distrib.sh then it only work for login and the blank white screen

**Comment by misterpink14** [comment]
Do you see any error output when running distrib.sh? I just ran the script and it worked fine for me. After logging in do you see the following popup?
<img width="419" alt="screen shot 2016-07-24 at 10 23 56 pm" src="https://cloud.githubusercontent.com/assets/9299960/17090402/6de26c3a-51ed-11e6-89fe-d7ffe8874df5.png">

**Comment by ranrinc** [comment]
@misterpink14 have not seen those warning.. Will tested again

**Comment by misterpink14** [comment]
@ranrinc this might be a stretch, but it could be app restrictions in osx

**Comment by mattrat88** [comment]
Is there any way to get the Mac desktop app to search a larger area ? I have no idea how to set up workers , that's above me lol -_-

**Comment by hawkrives** [comment]
@mattrat88: You might want to open a new issue for that – I don't know if that's part of this one 😉.

**Comment by mattrat88** [comment]
Lol I got it going it's just on my windows machine now running like 20 accounts Urgh life
