### ISSUE TITLE
New Spawn Point features explanation? [not an issue]

### ISSUE THREAD

**Issue by MacTrace** [mchristopher/PokemonGo-DesktopMap#1160]
I'm working with the assumption that the colors are telling me that something has either spawned or will spawn soon depending on the color, but I don't know exactly. I thought initially it correlated with rarity, but the colors change so that can't be right. And the timers, a friend said, mean that two things spawn at each point every hour, and the times are indicating how long after each hour you can expect something to spawn at a given point. Is that correct, if so, does it change?

Any further explanation would be helpful. I'm guessing it's posted somewhere but I just didn't see it.

[v0.3.4]

**Comment by krijnsent** [comment]
See this post (not in any wiki yet as far as I could see) https://github.com/PokemonGoMap/PokemonGo-Map/pull/969:

Varies the colors of the spawn circle based on its spawn time relative to the current time:
Default color is purple
At 5 minutes, spawn circles turn light blue and becomes darker until the spawn time
At spawn time, spawn circles turn green and change to red over the course of the active spawn
