### ISSUE TITLE
Regarding "Scanning Option"

### ISSUE THREAD

**Issue by MrBirdDk** [mchristopher/PokemonGo-DesktopMap#1162]
I'm in a town so i would like to scan the whole town, i would say a 5 mile radius should do it.

how much to write into that box marker Scanning options ?

when i tried as a start, i only get 10-15 pokemons on the map, but alot of pokestops ?

any thoughts on this ?
or am i just way off in my settings.

i tried to uninstall the program, but for some reason it saves the reg-info somewhere..
so i cant do a full uninstall.

**Comment by dedkob** [comment]
i used 15 accounts with 20 radius options works well.
