### ISSUE TITLE
Is it possible to have two instances of the app running on one PC

### ISSUE THREAD

**Issue by ad1tyas** [mchristopher/PokemonGo-DesktopMap#1163]
Is it possible to have two instances of the app running on one PC and also to change the port it lists to?

Thanks

**Comment by jareem** [comment]
@mchristopher ?

**Comment by ad1tyas** [comment]
:/

**Comment by Cereusly** [comment]
I'm pretty sure each extra instances just uses the next open port.  The default port is 8000 so a second instance would use 8001, then 8002, etc.  There's also a pull request that adds the option to change the express port though I have no experience with it.

**Comment by ad1tyas** [comment]
The problem isn't the port, but the saved login info.

I'm pretty sure we can't run two instances with the same PTC Accounts right?
