### ISSUE TITLE
Loading, please wait

### ISSUE THREAD

**Issue by soundog** [mchristopher/PokemonGo-DesktopMap#1164]
Hi!
My app wont work, and im currently only using it on the desktop.
i've put in 2 different PTC accounts, and created a API from google, just as described.
What can i do to make this work? Anything people here have had some issues with?

**Comment by MrBirdDk** [comment]
did you login to the accounts from the game ?

**Comment by soundog** [comment]
Well, i just tried that, nothing yet, still loading.
I even started the app before i went out, 2 hours later, nothing.

**Comment by scanner1129** [comment]
did you respond to the email requesting to verify your accounts yet?
