### ISSUE TITLE
Scan stops after complete scan

### ISSUE THREAD

**Issue by elfkinn** [mchristopher/PokemonGo-DesktopMap#1168]
Just updated to 3.4 and added a few more accounts, to compensate for not being able to individually place each account where I want. And since I updated every time it finishes a full scan of the area it stops scanning till I relaunch the program. Anyone else having this issue, or know how to fix it

**Comment by elfkinn** [comment]
think it might be working properly now, I restarted my computer, I will close this in a few hours when im sure

**Comment by elfkinn** [comment]
issue is still happening

**Comment by luckytom333** [comment]
On 1 PC, it works great, 10 accounts, 12 radius.  On my other PC, 10 accounts, 12 radius, it scans around once fine and then slowly dies out over about 3-4 rotations until it completely stops.  I then have to close the program and reopen.  I have uninstalled, deleted app data, rebooted, etc, no luck.  Both PC's have the same hardware and are running Windows 10 Pro 64 bit.

**Comment by elfkinn** [comment]
are you using the same accounts on each pc? I tried running my 30+ accounts on another computer running osx but python keeps crashing, the computer I was using before was using win 10 and the same 30+ accounts.

**Comment by luckytom333** [comment]
Using different accounts on each computer.  Now today, both computers are doing the same thing... runs great the first time around... then dies out after about 2-3 more scans.  Also it seems to not want to change the default scan location anymore, it's permanently set to one location.

**Comment by scanner1129** [comment]
Are your Pokemon Go accounts used in this map Google accounts? Google accounts time out after 30 mins on this tool. PTC accounts do not.

**Comment by luckytom333** [comment]
I'm using PTC accounts.  I reverted back to version 3.3 and all works fine.  Version 3.4 has issues as stated above.

**Comment by elfkinn** [comment]
PTC account here

**Comment by romanticheart** [comment]
Has anyone figured out a fix for this yet? It's basically app-breaking for me, as I am generally leaving this on in the background to collect data.
