### ISSUE TITLE
Please update Wiki/FAQ

### ISSUE THREAD

**Issue by Nonkel** [mchristopher/PokemonGo-DesktopMap#1176]
Hi,

Program works great with last update!

One request though, the FAQ is not updated. I just turned on spawn points to optimally cover them with my scans (never thought of that before...) but now I see different colour codes. No clue to what they mean, FAQ and Setup don't even mention the spawnpoint option. Anyone that can enlighten me?

Besides the example above, I see a lot of questions pop up that can be tackled with a bit more explanation. Would be a waste if one spends hours on making this program work, and then not let people use it to its fullest because there is information lacking. Thanks!

**Comment by Pkmnletarn** [comment]
Great job! 
I got it working and had the exact same question regarding spawn point color. But wanted to give you a salute. Donation on it's way! 
:-)

**Comment by krijnsent** [comment]
As I posted with another issue: https://github.com/mchristopher/PokemonGo-DesktopMap/issues/1160  See this post (not in any wiki yet as far as I could see, I agree that could be updated) https://github.com/PokemonGoMap/PokemonGo-Map/pull/969:

Varies the colors of the spawn circle based on its spawn time relative to the current time:
Default color is purple
At 5 minutes, spawn circles turn light blue and becomes darker until the spawn time
At spawn time, spawn circles turn green and change to red over the course of the active spawn

**Comment by torantal** [comment]
Updated the faq, not that anyone reads it ... ;)

**Comment by PhilipposVassil** [comment]
@torantal i read it! nice thanks 
I have solve my questions
