### ISSUE TITLE
error after installing

### ISSUE THREAD

**Issue by toneeebear** [mchristopher/PokemonGo-DesktopMap#1178]
![ss 2016-09-06 at 09 24 51](https://cloud.githubusercontent.com/assets/21000483/18259196/f4bcc064-7413-11e6-88e9-9980c72a9f7e.png)

having problems after installing help!ive'd already download some folders also but still same error

![wqra](https://cloud.githubusercontent.com/assets/21000483/18259209/1a821a06-7414-11e6-9f49-b277ef5e05b9.PNG)

**Comment by Froggy5662** [comment]
Stop
