### ISSUE TITLE
Search Marker Disappeared 

### ISSUE THREAD

**Issue by warsaws** [mchristopher/PokemonGo-DesktopMap#1179]
What it says. The center searching marker that you move to set where scans begin has disappeared. Scanning commences like normally from where the marker should be, but it is not there/not selectable even if I click where it seems like it would be. Toggling the side location options doesn't change it. Any ideas? 

The scanner had been working for me for several days. The scan location was starting offset a bit from where the marker was actually placed, but it was there visible. Now it just up and disappeared, no idea why. I'm on Win7 x64 Thanks.

**Comment by elfkinn** [comment]
try style settings and look at the search marker settings

**Comment by blahblah3141** [comment]
Also try removing "lock marker"

**Comment by scanner1129** [comment]
This happens to me when I use my smartphone's web browser and change the location to where I am / was. I can usually see the scans still working in the mobile location by turning on the scanned areas from the options > marker settings.

Other than stopping the server and restarting, I can set another location, click on stats and go back to the map, or refresh the browser (if still using) to sync it up again. Sometimes the "too many tunnel connections" message pops up and you have to wait 60 secs to refresh it again.

**Comment by warsaws** [comment]
Changing any of the search marker settings like "local marker" doesn't change it. Like scanner1129 said, I had been using it on my smartphone for several hours yesterday. But logging out, refreshing, restarting the PC, or changing the marker settings don't make it reappear. Never had this issue before. I can still manually move the scan center from the lat/long on login but it's not ideal.
