### ISSUE TITLE
Windows version not working on Windows Vista

### ISSUE THREAD

**Issue by campodim** [mchristopher/PokemonGo-DesktopMap#118]
I got the following error when i launch the latest version for windows on my windows vista : 

> The procedure entry point "GetCurrentProcessExplicitAppUserodelID" could not be located in the dynamic link library shell32.dll

Could you provide a working version for windows vista please ?

**Comment by vlalo001** [comment]
Did you run as admin?

**Comment by campodim** [comment]
i did, same result, same error :(

**Comment by hfmls** [comment]
if it runs vista it can run 7 lite mate :|

**Comment by mchristopher** [comment]
I don't have a copy of Vista handy, the earliest version of Windows I've tested with is 7. It sounds like an issue with Electron, which is outside the area of dependencies I have time to work on right now.
