### ISSUE TITLE
Stuck on loading screen

### ISSUE THREAD

**Issue by vicstarrr** [mchristopher/PokemonGo-DesktopMap#1180]
So i logged out and logged back in. I click on the start server button and it goes in but its stuck on the loading, please wait... Ive been stuck on that for a long time now it won't go in.

**Comment by scanner1129** [comment]
can you log in to pokemon go with the account you are trying to use for the map?if so, have you verified the account via the email, accepted the terms of service in the game, and caught a starter pokemon? Finally, make sure your Google Maps key is set up correctly.

Those are the common resolutions to this very frequently posted issue.

**Comment by vicstarrr** [comment]
hello yes i did all those things i thought since maybe because i had like 7-8 accounts so i deleted all and left one. I also got a new google map key and tried it again. its still stuck on that same loading please wait. I tried deleting the app and re-installing and same problem
