### ISSUE TITLE
Request for scanning

### ISSUE THREAD

**Issue by Jesselscott** [mchristopher/PokemonGo-DesktopMap#1182]
Trying to figure out how to scan such that all of the spawn points are picked up.  On the weekends I sent the scanner to 150 and let it run all weekend.  Still not picking up some spawns. Assuming the start time is not sufficiently offset to pick them all up.  Is there any way to offset the start of each progressive scan at a set time from the previous in order to mark all of the spawn points?  It would be great if you could just type in the nearest scheduled scan ie. :00, :12, :24, :36, :48.  That would in theory, capture every spawn point.  Another useful thing would be able to see how many scans have been completed from a location since it was started and the time each one started.  Currently there is no way to know how long a single scan will take.  Another useful thing would be to have a ghost image showing the area that will be scanned with the current settings when you move the pin so you can make sure it's covering the areas you want it to cover.  New to all of this so apologies if this isn't the right place to put suggestions.

**Comment by scanner1129** [comment]
go into options  > marker and turn on scanned locations. I think you'll answer some of your own questions by visualizing the way the tool works. BTW, 150 radius is way too much for this tool in my experience - especially if you are only using 1 account. 

Start out with a radius of 5 to 7 and see what's happening, and then you can experiment with multiple accounts. I've settled on a radius of 8 with 12 accounts, for example, just to make sure I see all spawns I can get to in less than 10 mins.

**Comment by Jesselscott** [comment]
I guess I am using this tool a little different than most.  I am not using it to located spawns.  I am using it to map spawn points and times.  I am using multiple accounts.  radius 150 works well when I am using it to map spawn points for a region and I am leaving it up on my work computer to scan for an entire weekend.  The problem is that I have no way of knowing where the outer limits of the scan will fall so it's basically it's trial and error.  It would be great if the pin graphic included an outline of the outer limits of a complete scan. As I tried to describe in my first post, the other issue when doing region scans is that the scan cycle is well over an hour.  If the start of subsequent scans is close to the first you will not end up getting all of the spawns.

**Comment by scanner1129** [comment]
https://github.com/TBTerra/spawnScan

**Comment by 3Trace** [comment]
I've noticed that it doesn't display every gym anymore, along with spawn points, past a certain distance from places you've placed the pin. So I'd suggest moving the pin around to map out the spawn points. The information does stay for a while but I know it deletes after a while.
