### ISSUE TITLE
Error: listen EADDRINUSE :::8001

### ISSUE THREAD

**Issue by Wilmarzuluaga18** [mchristopher/PokemonGo-DesktopMap#1185]
The app doesnt work because of this java error, HELP!

**Comment by scanner1129** [comment]
You have another process already using port 8001? This explains it and explains how to identify and kill that process - http://stackoverflow.com/a/38069981

**Comment by Madman8** [comment]
I do not understand at all how to kill the port. can anyone help a "moron" figure this out in children's terms.

**Comment by jareem** [comment]
@Madman8 You won't "kill the port", but instead kill the process already using this port.

Open a command prompt and type : netstat -ab
Look for a line with "TCP            x.x.x.x:8001"
You will see the process involved, then you just have to kill it.

**Comment by meisterluv** [comment]
How do you run multiple clients without running in to this error??
