### ISSUE TITLE
is it possible to use a config.ini ?

### ISSUE THREAD

**Issue by MrBirdDk** [mchristopher/PokemonGo-DesktopMap#1186]
i found an config.ini example in the folders, so i was wondering if it is possible to use that, for account info and such.

**Comment by meisterluv** [comment]
there is an example config file in /app/map/config folder. copy it and delete the '.example' . edit with notepad++ or whatever text editor you like.

**Comment by davidmorr** [comment]
Any tips on getting this to work? I have the essential fields but still get asked to login.
