### ISSUE TITLE
Running multiple accounts - unmovable group of scanners. 

### ISSUE THREAD

**Issue by benjimonz** [mchristopher/PokemonGo-DesktopMap#1188]
Macbook Pro OSX Yosemite
I have multiple accounts running and when I log in there is one outlier of scanning happening. It's constantly running, even when I log out and log back in (there will be new scans).
The thing is, I cannot move this group of scanners. There is no marker to move.

I have tried reinstalling but the group of scanners is now consistently running, as if they are now running on their own!

What's going on? Is there a way to reset all the accounts?

![screen shot 2016-09-06 at 10 52 52 pm](https://cloud.githubusercontent.com/assets/22045050/18301237/aeda7890-7484-11e6-8b2d-314ab424106a.png)

**Comment by torantal** [comment]
Use a task manager to kill all python instances or simply reboot. That should reset this.
