### ISSUE TITLE
Waiting and nothing going on...

### ISSUE THREAD

**Issue by smkaevur** [mchristopher/PokemonGo-DesktopMap#119]
I just see map and my location.... In the centre WAITING...
If do the Tools - Refresh... this say Operational but nothing going on... Just my location and map
noone pokemon, no one pokestop but  yesterday on other computer was working

**Comment by vlalo001** [comment]
Pokemon go servers are down, close this issue

**Comment by JarJak** [comment]
Hmm program could check server status, it would be nice :)

**Comment by smkaevur** [comment]
https://go.jooas.com/
You can check here... now the servers are online but pokemons not appeared
