### ISSUE TITLE
Max Accounts and Push Notifications

### ISSUE THREAD

**Issue by random189268** [mchristopher/PokemonGo-DesktopMap#1191]
1) What is the max # of accounts we can use on one IP?

2) Are there plans to allow push notifications, or does anyone know a way to do this?

I would ask these on a discord but don't see anything listed, and the FAQ on the Wiki here was pretty light.

**Comment by RossHerlihy** [comment]
2) I'd love to see some push notifications as well. Would anyone be able to advise on if its possible to implement PokeAlarm into PGDM? https://www.reddit.com/r/pokemongodev/comments/51l7jt/pokealarm_external_notifications_now_with_lure/

**Comment by random189268** [comment]
Can this be used for the push notifications? https://github.com/kvangent/PokeAlarm

Not sure if that is compatible with this Pokemon Go Map.

**Comment by MarkoHess** [comment]
Works, i have done it this morning. But you'll need to change the config.ini of pokemaps to enable webhooks on your wished port and follow the instructions of PokeAlarm installation.

**Comment by meisterluv** [comment]
PokeAlarm works for this.  One thing to note though is that you must NOT have any pokemons assigned in the notification section in the desktop app. It seems the desktop app will not send any info to the web hook when you ask the app to notify you.

**Comment by ThriceCandy** [comment]
What needs to be done to get pogomap to pull from config.ini?  When I try and use it, the user interface will hang in 'loading' indefinitely when I start the server.
