### ISSUE TITLE
[Enhancement] spawn point scanning

### ISSUE THREAD

**Issue by ArcosBinary** [mchristopher/PokemonGo-DesktopMap#1192]
Could you add a checkbox for spawnpoint scanning using the -ss option?

**Comment by simonbuehler** [comment]
:+1:

**Comment by 3Trace** [comment]
There's been many threads asking for this, I think they are implementing it in the next release.

**Comment by themysticalone** [comment]
Yes, this would definitely be desirable. I'd be able to switch back to radius 7 instead of 5 if I could exclude all the areas without spawns.

**Comment by ThunderVamp9** [comment]
Yeah, this will be nice to see. Right now I have 16PTC's in a R15 scan. Does OK, completes a scan in about 8 mins but as you can see there is a LOT of wasted space in the scan that I could avoid with older versions by running multiple instances of the scanner up until this version. I do like this one's speed, but really looking forward to a way to have it not waste time scanning sections that will never have anything in them.
![pogomap](https://cloud.githubusercontent.com/assets/20704423/18787489/1498e042-8171-11e6-9801-a7ef85ef2184.jpg)
