### ISSUE TITLE
Just recieved scanner notification of possible ban

### ISSUE THREAD

**Issue by Sedare** [mchristopher/PokemonGo-DesktopMap#1195]
never seen it before, but it happened literally on the minute of 12:00 midnight, and I closed the scanner within 3 seconds. Am I alone on this, or was there some sort of widespread ban hammer that just went down?

**Comment by lmcmalo** [comment]
Set up a new PTC account around the same time, got the 'Possible Ban' immediately.   I can login with the PTC account on an old iphone through the same public IP address.   Time to read this code.

**Comment by NickIxo** [comment]
Back on the old scanner i used to get "possible ban" warnings all the time. They weren't always accurate, so i would just try to log in on your accounts most suspect of a ban. (generally the oldest, in my experience)

**Comment by 3Trace** [comment]
Happens to me all the time when I leave the scanner running all night while I sleep. Just log out and log back in.
