### ISSUE TITLE
No Pokemon Showing

### ISSUE THREAD

**Issue by RyusuiJL** [mchristopher/PokemonGo-DesktopMap#1196]
With the current release (0.3.4), the map SEEMS to be working, but no Pokemon show.  I have the option to show scanned areas on, and I see it move around the map, but no Pokemon icons will show up.  I've gotten the map to work a few times, but even then, it stops working after maybe 30-60 min.

**Comment by nhlongnguyen** [comment]
Probably your IP has been banned due to high number of requests being sent from it.
