### ISSUE TITLE
20 Accounts what should be on the search?

### ISSUE THREAD

**Issue by zapii2002** [mchristopher/PokemonGo-DesktopMap#1197]
Okey i have 20 accounts and iam wondering what my search should be on?

**Comment by he3amo** [comment]
5:15min at radius 15, 6min at radius 16. The remaining 10 minutes to catch.

**Comment by zapii2002** [comment]
what do you mean @he3amo ? Do you mean if i have it on 15 it will take 5 minutes to show up on map or what?

**Comment by he3amo** [comment]
@zapii2002 Scanning takes 5 minutes on 15 radius with 20 accounts

**Comment by zapii2002** [comment]
Okey but what are im going to have it on then? @he3amo ? i

**Comment by CTMapper** [comment]
@he3amo - How did you calculate these times?    It'd be great to know how to calculate the ideal scan radius.    I have 13 mappers, but would also like to start separating them to do multiple area scanning.  Typically I want it on a ~5min scan so there's time to catch the pokemon, but if I'm leaving it on overnight to collect data, then I want a 15min scan.   What's the formula?

**Comment by he3amo** [comment]
@CTMapper 
A good idea to add the scan time  to the home screen. Final time should be divided by the number of accounts
![pg](https://cloud.githubusercontent.com/assets/20947142/18395637/ebe7c658-76c7-11e6-8217-fb118c4ecfbf.PNG)

**Comment by zapii2002** [comment]
What do you mean with all this: RADIUS,POINTS,SUMM,MINUTES? I dont understand @he3amo

**Comment by he3amo** [comment]
@zapii2002 Scan points go +6 at each step. Just look at the radius and minutes. Minutes is the time of scanning with one account. ;)

**Comment by torantal** [comment]
![pubchart](https://cloud.githubusercontent.com/assets/6267029/18400792/b6252f82-76d7-11e6-8422-be8e1de7b92d.png)

**Comment by torantal** [comment]
To have a chance to catch a spawn anywhere in your radius look for combinations where [time to drive to the furthest scan circle from your starting point]+[scan duration] is about 10 minutes max.

**Comment by zapii2002** [comment]
What does the minutes mean?
like on the Search Radius 20 and the Scan duration for # of accounts used 20. Thats 00:09:31 what does that means? Does it means that all pokemons spawn when it have 9 minutes or what?
Can someone please explain ?? 
I need to know what im going to have my Scanning Option on, I have 20 accounts and i want a big area and pokemons that i can see fast!!

**Comment by torantal** [comment]
Radius 20: using 20 account it takes 9:31 min to scan every single circle of the full search pattern. This search will find any spawn within your radius and at the point of finding it it spawned at most 9:31 minutes ago. So in the worst case you see a dragonite spawn with 5:30 min left to get there.  

Radius 15: using 20 account it takes 5:16 min to scan every single circle of the full search pattern. This search will find any spawn within your radius and it spawned at most 5 minutes ago. So in the worst case you see a dragonite spawn with 10 min left to get there.  

Understood?

**Comment by zapii2002** [comment]
Yes Thank you :) but Can i Have more accounts THEN 20? :)

**Comment by torantal** [comment]
No idea of the limitations in the implementation. Give it a try.
