### ISSUE TITLE
Help?

### ISSUE THREAD

**Issue by SitopApen** [mchristopher/PokemonGo-DesktopMap#1198]
Hey
So I'm new to this whole thing.
I downloaded the PokemonGoMap-Win.exe file, because I'm on Windows 10
I don't know if I have to download anything else in there too.

After I did that, I got an API key online following their directions and then I got the address of where I am. However, every time I search for Pokemon the map stays blank for about a minute and then at the top it says "Possible Ban" in red.
Did I screw this up somehow? I'm using a google account.
Thanks!

**Comment by NLferdiNL** [comment]
The account doesn't work until you got past the tutorial stuff in the game.
I believe the program doesn't skip through it.
