### ISSUE TITLE
How do i know if one account is banned?

### ISSUE THREAD

**Issue by zapii2002** [mchristopher/PokemonGo-DesktopMap#1199]
I Have 20 accounts and how do i know if one of them are banned?

**Comment by torantal** [comment]
Fire up PoGo and try to log on with each one. The desktop map does not have an indicator right now.

**Comment by nhlongnguyen** [comment]
Go to Tools->Toggle developer tools and you have everything logged there

**Comment by NickIxo** [comment]
where would this information be logged in the dev tools?

**Comment by nhlongnguyen** [comment]
Either search for "banned" keyword or check manually if any of your workers return with 0 pokemons, 0 pokestops and 0 gyms

**Comment by ajoin007** [comment]
? i can't find my accounts in the dev body part nor can i find anything about being banned.

**Comment by torantal** [comment]
I think  nhlongnguyen means you should look in the console message under dev tools

**Comment by srenobdrawkwa** [comment]
What's it mean if it says 0 pokemons, I'm getting it a lot

**Comment by srenobdrawkwa** [comment]
Scrap the above question, what does DB queue is >50 try increasing DB threads mean?

**Comment by Acaceres1996** [comment]
Thats what we were discussing in #1205
