### ISSUE TITLE
Does it matter which account I log in to?

### ISSUE THREAD

**Issue by hdubb** [mchristopher/PokemonGo-DesktopMap#120]
I have a level 22 main but I do not want to risk getting it banned.

If I make a new level 1 account, will it show me the same pokemon as if I logged into my level 22?

**Comment by LitoOsaka** [comment]
Yes, it does.

**Comment by hdubb** [comment]
If I log in to my main account and switch to different locations, will it look like I am GPS spoofing, which will result in a ban?

**Comment by JarJak** [comment]
Never log in in this app with your main account.

**Comment by Mrxshamsi** [comment]
I made a new account just for these kind of programs, you get the same pokemon but different CP.
