### ISSUE TITLE
scanning fine but not tracking any pokemon

### ISSUE THREAD

**Issue by lochnesskid** [mchristopher/PokemonGo-DesktopMap#1200]
I had the scanner going with 5 accounts working fine for about 2 hours then I decided to make a few more account then it suddenly stopped working. It still said operational at the top it was still scanning (green circles popping up and pokestops) but no pokemon ever appeared. I decided to go back to 1 account to see if that worked and still nothing, I live in an area where there is always pokemon around

**Comment by lochnesskid** [comment]
I am using ptc accounts and got past the part where i caught the first Pokemon on all of them

**Comment by torantal** [comment]
restart - reboot - re-install - return here

give each a try and move on to the next if you're not successful

**Comment by lochnesskid** [comment]
@torantal I used a personal hotspot on my phone and connected to it and started working second I switched back to my router it stopped working again maybe an ip ban?

**Comment by torantal** [comment]
du you have a static ip? otherwise reboot your ip provider's modem and you'll get a new one assigned

**Comment by lochnesskid** [comment]
@torantal thanks alot working again
