### ISSUE TITLE
Strange times for spawn points

### ISSUE THREAD

**Issue by davidmorr** [mchristopher/PokemonGo-DesktopMap#1201]
When I hover over a spawn point I often get times of day that are far too big. e.g.,

Spawn Point
Every hour from 38:36 to 53:36
May appear as early as 8:36

Or does the 38 and 53 mean something else?

**Comment by torantal** [comment]
Every hour from 38:36 to 53:36 translates into:

00:38:36 - 00:53:36
01:38:36 - 01:53:36
02:38:36 - 02:53:36
03:38:36 - 03:53:36
...

**Comment by davidmorr** [comment]
So they are mm:ss, not hh:mm. Thanks
