### ISSUE TITLE
possible ban

### ISSUE THREAD

**Issue by SetMeFree1** [mchristopher/PokemonGo-DesktopMap#1203]
this app has already gotten two of my accounts banned, so I don't trust it anymore. There's also a very weird script error with it.

Java script error:
https://gyazo.com/b6c983f3656d796384f234141b87b569

connect error
https://gyazo.com/69fb68673192a86a771253ea5b3b360c

**Comment by torantal** [comment]
Any app with scanning behaviour will get you banned at some point, unless the search pattern is at some point so refined that it is indistinguishable from someone walking about. So don't use it with anything but throwaway accounts.

I've had similar errors when starting multiple sessions, but they normally don't matter or go away after a restart (app/os).

**Comment by SetMeFree1** [comment]
The problem is, it's not after a while, it's immediate. New account, logged into the map, wait 30 seconds, 'possible ban'. And your ban letter comes. Oh well, sticking to maps on my phone for now.
