### ISSUE TITLE
DB Queue > 50 in radius greater than 7

### ISSUE THREAD

**Issue by Acaceres1996** [mchristopher/PokemonGo-DesktopMap#1205]
The app is working great! However, i am having a problem:

When setting up the app to scan a radius of 8 or more, the following warning appears:

016-09-09 00:27:14,298 [    db-updater-0][        models][ WARNING] DB queue is > 50 (@51); try increasing --db-threads

In first half an hour or so, the scanning works like it should. After that, it stops scanning. 

When setting the scanner on 7 or less, the warning disappears, and the scan works fine even on extended periods of time.

**Comment by iCiccio25** [comment]
me too with radius 11. After some minutes i have [ db-updater-0] [ WARNING] DB queue is > 50 (@numbers); try increasing --db-threads

**Comment by Acaceres1996** [comment]
For what i was reading in the issues of the Pokemon Go Map (Which is the base map of this project, i think), it's an issue of the database configuration. From what i understood, the database ends up locked after some time because of an uncontrollable queue of information pending to be updated on it.

**Comment by iCiccio25** [comment]
So we must use radius at 7 or less to avoid this?

**Comment by Acaceres1996** [comment]
After 24 hours of the server up on radius 7, i also found some of this warnings in the console. However, they were less than 10 warnings in 24 hours, and apparently they didnt affect the scan.

On the pogom issues, they suggested something about using the parameters -nk and -ng to stop the scan from retrieving information about pokestops and gyms in order to minimize the data injected in the database. However, thats in the pogom project, and i certainly dont know how could it be applicable here.

(This app apparently gets all this information, and the toggles on the menu are only for showing/not showing whats already in the database. I could be wrong, though.)

**Comment by iCiccio25** [comment]
Mmm... I have pokestop's toggle turn off, I'll try also turning off gyms. Thank you

**Comment by iCiccio25** [comment]
With 10 accounts, radious at 11 and pokestop and gyms off seems work fine

**Comment by Acaceres1996** [comment]
Good! With radius 8 and both things off, server has been scanning smoothly on my side. I will try in the next days to add more accounts and to increase the scanner for further tests.
