### ISSUE TITLE
how to avoid getting IP banned

### ISSUE THREAD

**Issue by lochnesskid** [mchristopher/PokemonGo-DesktopMap#1209]
I am using Mac OSX and the tracker will work great for 10 mins then I am assuming I get IP Banned because pokemon stop appearing and unable to track pokemon on the app while connected to my wifi. I tried only using 1 account but the same thing kept happening. The ban last for a few hours. Is there a way I can avoid this from happening any ideas?

**Comment by lochnesskid** [comment]
ptc accounts

**Comment by b3y0ndd34th** [comment]
Are you using a Pokemon Trainer Club Account?

There is a limitation with the Google accounts (probably something to prevent the bots from working well), you can only use the Google account for ~15 minutes before you need to log out and back in again.

To avoid this, you can set up a PTC account and the scan *should* run for days.

**Comment by lochnesskid** [comment]
@b3y0ndd34th I am using all PTC accounts works long enough to do 1 full scan then im banned

**Comment by b3y0ndd34th** [comment]
Have you logged into the game and captured your first pokemon, as well as named your character?

**Comment by lochnesskid** [comment]
@b3y0ndd34th yes

**Comment by srenobdrawkwa** [comment]
Same issue can't figure out how to fix it... 😞

**Comment by cpbeckner** [comment]
I was having the same issue and I reverted to version 0.3.3 and it works great now with no stopping scanning.

**Comment by srenobdrawkwa** [comment]
Does 0.33 allow mutiple accounts?
