### ISSUE TITLE
how to use mobile without getting banned

### ISSUE THREAD

**Issue by jus10g** [mchristopher/PokemonGo-DesktopMap#1211]
Thanks for the great application - it has made the game a heck of a lot more fun.  I'm trying to figure out the optimal way to use the mobile function.  If I use the weblink to the mobile site, and then reset my scan to my new location (perhaps dozens of miles away), won't I get flagged for a ban because my location just "teleported?"

**Comment by torantal** [comment]
Just DON'T use your regular account for scanning, but a throwaway account, then there's no association between you using the website and your regular play-account.

**Comment by jus10g** [comment]
but won't my throwaway account(s) get immediately banned?  I'm making them by hand so I'd prefer not to lose them repeatedly...

**Comment by torantal** [comment]
Just imagine people using the same account on different devices, mom in NYC, dad on his trip to Miami. Just logging on in turns wil make the position jump without having done anything wrong TOS-wise, so not a basis for banning.

The filters that Niantec uses for finding bot-/scan-behaviour are not known so just assume that you will have to replace your scan-accounts and your mileage may vary. I'm currently running a 7-account scan and typically need three new accounts per week.

**Comment by blahblah3141** [comment]
Sharing accounts is against the TOS @torantal and you will get banned in that scenario (mom in NYC, dad on his trip...)

**Comment by torantal** [comment]
It might be the case on paper and some people might have actually had negative consequences, but personally I'd yet have to see it and I know quite a few where the family will share. And if one really cared just run the account on an old phone then one person can run as many accounts as they can carry phones..

**Comment by torantal** [comment]
And anyway - discussing this as an issue here where people will run 20-50 accounts on their scanner makes this a pretty insignificant issue in comparison ... ;)
