### ISSUE TITLE
Show IV/Stats

### ISSUE THREAD

**Issue by RyusuiJL** [mchristopher/PokemonGo-DesktopMap#1212]
Would it be possible to have the map show the IVs of each Pokemon?

**Comment by PJRay** [comment]
I'm guessing that you'd have to level up the map accounts a little before that is feasible - otherwise the IV interval values you get will be very broad. It's a really interesting suggestion, though.

**Comment by RyusuiJL** [comment]
Go Radar is supposed to be able to do that.  I just haven't been able to get the app to work well for me.

**Comment by AnarkhiA** [comment]
goradar does do that yea. but! it doesnt always show the IV stats. no need to level a account or anything. that wouldnt make anysense either since cp is different for every level anyway.

**Comment by AVellucci** [comment]
As this is specific to the PokemonGoMap this issue would be better opened on the PokemonGoMap repo, as this is just a wrapper for that project.
