### ISSUE TITLE
Warning Database Locked

### ISSUE THREAD

**Issue by Thefinder109** [mchristopher/PokemonGo-DesktopMap#1215]
I'm running 0.3.4 and I keep seeing Warnings around the database being locked.   Is this normal or is something wrong?

**Comment by jus10g** [comment]
I'm also getting a lot of database locked errors.  See below for error messages.

Recently the app got stuck "cleaning database" and wouldn't do any scanning.  Restarting the application helps for a little bit, but it seems to be recurring.

> 2016-09-13 20:10:43,784 [    db-updater-0][        models][ WARNING] database is locked... Retrying
> 
> main.html:169 2016-09-13 20:10:43,786 [ search-worker-2][        search][   ERROR] Exception in search_worker: database is locked
> Traceback (most recent call last):
>   File "/Applications/Pokemon GO Live Map.app/Contents/Resources/app/map/pogom/search.py", line 597, in search_worker_thread
>     record = GymDetails.get(gym_id=gym['gym_id'])
>   File "/Applications/Pokemon GO Live Map.app/Contents/Resources/app/packages.zip/peewee.py", line 4562, in get
>     return sq.get()
>   File "/Applications/Pokemon GO Live Map.app/Contents/Resources/app/packages.zip/peewee.py", line 2913, in get
>     return next(clone.execute())
>   File "/Applications/Pokemon GO Live Map.app/Contents/Resources/app/packages.zip/peewee.py", line 2960, in execute
>     self._qr = ResultWrapper(model_class, self._execute(), query_meta)
>   File "/Applications/Pokemon GO Live Map.app/Contents/Resources/app/packages.zip/peewee.py", line 2656, in _execute
>     return self.database.execute_sql(sql, params, self.require_commit)
>   File "/Applications/Pokemon GO Live Map.app/Contents/Resources/app/packages.zip/peewee.py", line 3492, in execute_sql
>     self.commit()
>   File "/Applications/Pokemon GO Live Map.app/Contents/Resources/app/packages.zip/peewee.py", line 3316, in __exit__
>     reraise(new_type, new_type(*exc_args), traceback)
>   File "/Applications/Pokemon GO Live Map.app/Contents/Resources/app/packages.zip/peewee.py", line 3485, in execute_sql
>     cursor.execute(sql, params or ())
> OperationalError: database is locked
