### ISSUE TITLE
How to put multiple locations in version 0.3.4

### ISSUE THREAD

**Issue by DaniloBR** [mchristopher/PokemonGo-DesktopMap#1217]
I'm sorry if this is too simple, but this version is possible to place multiple accounts, but can't find a way to put multiple locations. If someone help, thank you very much.

**Comment by Acaceres1996** [comment]
I think the only way is to have multiple instances of the app open, scanning different places at the same time. As every instance will be working with the same database, you should see all the scan information.

**Comment by DaniloBR** [comment]
I just do not understand the cause of having the option of multiple accounts. I thought I would have a way to put multiple locations at the same time. But thanks!

**Comment by dragonatorfear** [comment]
you can add multiple accounts to increase the scanning radius and scanning speed in one location. Running a 10 radius in less than 3 mins here ;)

**Comment by DaniloBR** [comment]
Wow! Really! I had not realized it. Thank you very much!
