### ISSUE TITLE
Possible ban / Outage 

### ISSUE THREAD

**Issue by srenobdrawkwa** [mchristopher/PokemonGo-DesktopMap#1219]
Following my issue of my scanner only scanning once and then stopping I have noticed the green "operational" bar up top has changed to constant red "possible ban/outage" wondering if this issue is related and someone might have a resolution?

**Comment by torantal** [comment]
Have your scan accounts all caught the intro pokemon? Can you still log on with them?

**Comment by srenobdrawkwa** [comment]
I have 55 accounts yes i caught starters and I don't want to try log in to all of them. :( lol

**Comment by tonremmacs** [comment]
Are you using the latest release version? 
I tired to run it with 55 accounds, but got softban in less then 15 minits because so many accounts teleported way to much on my 24 radius I was using. 

I changed it down to 10 in radius with 11 acounts and that runs without a problem.

**Comment by srenobdrawkwa** [comment]
Yeah  I did maybe I went a little over the top to fast 😅

**Comment by srenobdrawkwa** [comment]
Have you managed to increase it to more then 11 accounts and 10 radius?

**Comment by Mharper554** [comment]
why would you want more than 3 or 4 accounts

**Comment by torantal** [comment]
A radius of 10-11 with 7 accounts is what I can reach with my bicycle if the remaining time in around 7-8 minutes. If I used 3 accounts I would miss a few altogether and others would be identified too late to still catch them. 

If we get spawn point scanning in this project at some point *hoping and waiting* then the scans will be much more effective.
