### ISSUE TITLE
Show lured pokestops

### ISSUE THREAD

**Issue by legendz97** [mchristopher/PokemonGo-DesktopMap#1222]
How do I show lured pokestops?

**Comment by jasonasey** [comment]
It used to do it, but not anymore since the last two updates:(

**Comment by PokeTrainerNextDoor** [comment]
Where is the problem? The lured pokestops work just fine. I can see two right now, and they are marked as lured in the app and on the map.

**Comment by tinarazzburton** [comment]
The app used to show pokemon that were at lured pokestops.  It no longer does that.  You can see see which pokestops are lured, but it no longer shows which pokemon are there.
