### ISSUE TITLE
Scanning location different than drop location

### ISSUE THREAD

**Issue by Capnriz** [mchristopher/PokemonGo-DesktopMap#1226]
I have put the scanner onto a specific location and it is scanning down and to the left, 2 city blocks from my original scan spot. I created a new Google API key and inserted it, did not fix it. 

Anyone else having the same issue?

**Comment by torantal** [comment]
I've had similar effects when either running multiple instances or when a client was connected and had the location setting "scan follows location" active, overriding the desktop setting

**Comment by themysticalone** [comment]
It follows a specific pattern so that the ending point of a 'walk' is next to the starting point of the walk. That way it looks like a continuous loop, with no sudden jump from the outside of a hexagon to the center, which may theoretically trigger a bot/spoofing ban.
