### ISSUE TITLE
Notifications Update

### ISSUE THREAD

**Issue by zachkont** [mchristopher/PokemonGo-DesktopMap#1228]
Is it possible that you add a notification system like pushbullet so that one can run the scanner on a server and get notifications on a mobile device? Could be useful for pokemon appearing around your home etc.

**Comment by mwaraya** [comment]
+1

**Comment by 3Trace** [comment]
To piggyback off of the idea of expanding notifications, would be great to have several (at least 2) levels of notifications that have different sounds. Yes, I would like to know when magikarp spawn, but should it really make the same sound as when a Snorlax, Lapras, or Dragonite spawn?

A second group that you could assign an "all hands on deck" alarm sound to at the bare minimum would be fantastic way to not have to jump up every time the notification goes off when I'm falling asleep just to make sure it's not one of those 3 I mentioned. Thoughts?

**Comment by Scubbersteve** [comment]
The best would be a compatibility with Snarl or Growl. You get push notifications to your mobile device.
