### ISSUE TITLE
program blocked on "loading, please waiting..." screen (MAC)

### ISSUE THREAD

**Issue by kyogre2A** [mchristopher/PokemonGo-DesktopMap#1229]
yesterday i had to force quit the PC while the program was scanning, since then i can't get it to work anymore. how can i solve this? where can i found the program directory to uninstall it?

**Comment by gagnonjeanfrancois** [comment]
I have the same issue : the program blocked on "loading, please waiting..." screen 

I'm using PCT account, I tried 2 fresh Google API (I looked to not leave blank space), the scanning option is set to 1, I tried with and without " Server Mode / Allow access from anywhere ".

If I open the tool box ( In the menu : Tools > Toggle Developer tools ) and I go in Console Mode I get this error message :

```
 Error getting location, trying second provider
PositionError {code: 2, message: "Network location provider at 'https://www.googleapis.com/' : Returned error code 403."}
code : 2 message :
"Network location provider at 'https://www.googleapis.com/' : Returned error code 403."
__proto__ : PositionError
PERMISSION_DENIED : 1
POSITION_UNAVAILABLE : 2
TIMEOUT : 3
code : (...)
get code : () constructor :
PositionError() message : (...)
get message : ()
Symbol(Symbol.toStringTag) :
"PositionError"
__proto__ : Object

- Found location [75.5000,-70.5833] by ipinfo.io
```

I'm using the 0.3.4 version on Windows 10.

**Comment by vicstarrr** [comment]
I've had the same problem for about a week now. I've done the same steps as well made new accounts, caught the starter, confirmed email, they all still work after logging in again, and i still have the same problem. I also have a mac.

**Comment by scanner1129** [comment]
"Network location provider at 'https://www.googleapis.com/' : Returned error code 403."
__proto__ : PositionError
PERMISSION_DENIED : 1

No sure, but to me that looks like something is off with using your google API key. Permission denied seems to indicate your account is having trouble logging into the url when this tool tries to establish the connection.

I went to https://console.developers.google.com/ and looked at my key. It is unrestricted and has a warning about anyone can access it. The console then has options to restrict access. Maybe you have restrictions configured and therefore get DENIED? 

Justa guess, but try an unrestricted API key if you are not already.

**Comment by vicstarrr** [comment]
I checked on the restrictions and it isn't restricted. I tried to download and older version and the version before this one works. Weird because at first it worked great then just for no reason it stopped working. At least i know now that I'm not the only one with the same problem.
