### ISSUE TITLE
getting current spawns only during log-in

### ISSUE THREAD

**Issue by spetn** [mchristopher/PokemonGo-DesktopMap#123]
Hi, first of all this is amazing, however is it just me or do I need to log-off and re-login every time from the software in order to reload/refresh new spawns? I ran it on my pc and went out with my mobile but after 15min I would only get expired pokemons and not new ones. I tried to refresh the page on my mobile but it does not work. Thank you

**Comment by koliha** [comment]
This is related to this issue #72 and has already been addressed (changes have been committed).  Fix should be present in release 0.0.8 (not released yet, hopefully soon?).

**Comment by poekrel** [comment]
Yes it should be soon I think.  0.0.8 was actually released for a few minutes yesterday but there was a java error in the code so it was taken down again quickly. That being said, the aforementioned fixes should already be ready to go as soon as the bug is found fixed.

**Comment by mchristopher** [comment]
This should be fixed in the latest release.
