### ISSUE TITLE
Account status - Working

### ISSUE THREAD

**Issue by lucky644** [mchristopher/PokemonGo-DesktopMap#1230]
Hello,

Awesome app!

Quick question, if I have multiple accounts going, is there a way for me to see if they are all working?

I mean, the app is working and updating etc, but I have like 7 accounts added, and I'm not sure if it tells you if a specific account isn't working (banned...wrong password)

Any insight into this?

Thanks!

**Comment by Acaceres1996** [comment]
I think the only way to know if something is wrong with an specific worker is in the console. If there is an account witch the app cannot log to, or if it is finding 0 pokemons, 0pokestops and 0 gyms... It's likely something is not working well with that worker. After that, you should check it yourself logging in with said account.

**Comment by lucky644** [comment]
How can I view the console?

I'm pretty sure if I could see what was going on in the background with the raw data I could figure it out myself.

**Comment by Acaceres1996** [comment]
Tools>Toogle Developer Tools.

There, you have to search for the console tab. Be aware that the console "calls" the accounts as search-worker-number, so first of all you should see which account is assigned to which search-worker-number (In the console, filtering by the name of the account should do to see the line where the search-worker tries to log with a given name)

**Comment by lucky644** [comment]
That is exactly what I was looking for.

Turns out, in fact, I did typo one password for one account haha.

Thanks!
