### ISSUE TITLE
Getting Spawnpoints from older database?

### ISSUE THREAD

**Issue by ultimate2106** [mchristopher/PokemonGo-DesktopMap#1231]
Hey guys. When I updated the map my database got cleared.. Is it possible to get my spawnpoints from my old database into the new one (merged)?

**Comment by ultimate2106** [comment]
Noone can help? =(

**Comment by AVellucci** [comment]
@ultimate2106 check %appdata%\pokemon-go-map
you'll find both DBs in there.
I wouldn't suggest using the old db as it's obsolete and may cause issues for you later on.

**Comment by ultimate2106** [comment]
It's not that I want to use the old db but want my old spawnpoints.
And another question would be.. How can I merge 2 new databases?
I know btw where to find both DBs but not how to merge the data.....

**Comment by AVellucci** [comment]
@ultimate2106 the spawn points are generated by the pokemon table, it fetches the pokemon coordinates and then creates a spawn point when you run the map, their not a separate table.

You can find guide on how to merge SQLite Databases online.
