### ISSUE TITLE
Is anyone working on a hotfix for the db thread > 50 issue?

### ISSUE THREAD

**Issue by loiacj** [mchristopher/PokemonGo-DesktopMap#1235]
Honestly, that's the only thing that stops the program from running. It only started happening in the last five days. I miss being able to leave it up and just view it while I'm out and about on campus.

I've tried: Uninstalling and Reinstalling
Running as Administrator
Using all PTC Accounts only
Using all Google Accounts only
Increasing the scanning radius
Decreasing the scanning radius
Crying profusely
Resetting my ipaddress

Any update on the current project would be appreciated. I love the program and would like to see it running smoothly again. You guys are the best ^-^

**Comment by srenobdrawkwa** [comment]
This is my issue, what does Db>50 code mean? I have tried all new PTC accounts even chosen the buddy for each and also tried increasing/ decreasing accounts and radius. Resetting my IP address. And just signed into the accounts they still work, could the soft ban possibly not lift until you try to catch another Pokemon?

**Comment by srenobdrawkwa** [comment]
Don't worry about the SoftBan theory lol, very sleep deprived and after rereading it I realised even with a soft ban they should still see the Pokemon spawn  😅

**Comment by HollyKohai** [comment]
It's not even a ban. It's something to do with the database I think. Not sure. But I'd like it to be fixed so I can just leave my scan up

**Comment by HollyKohai** [comment]
What's really upsetting is that the scan just entirely slowly dies out. It doesn't show the areas being scanned slowly like it usually would going around in the circle making the rounds. Just really frustrating

**Comment by srenobdrawkwa** [comment]
Yeah just looked up what the code means on Google and it's way to deep for me to understand 😓 I just want to use the scanner lol I set it all up and have Made 88 accounts to date trying to sort it and have never got in to work once lol 😰

**Comment by HollyKohai** [comment]
I had it working for a week straight. 5 Dragonites spawned at my uni on the south side, so yeah, we have good stuff here. I'd like to know when it spawns so I can go get it xc

**Comment by jasonasey** [comment]
I get this too, not sure what it is.. Any more ideas?

**Comment by HollyKohai** [comment]
bump

**Comment by EvilLost** [comment]
If you guys are using too many accounts to be hitting this problem, its probably time to upgrade to the command line version.

**Comment by HollyKohai** [comment]
what does that mean?

**Comment by mitchganjjah** [comment]
Anyone ever figure this out???

**Comment by HollyKohai** [comment]
Lower number of accounts until the message stops appearing in console

**Comment by mitchganjjah** [comment]
Thanks. Thats what Im trying now.  Is it caused by too many accounts or too big of a step radius?

**Comment by HollyKohai** [comment]
I'm not sure which one exactly. I use a 10 radius and can get about 13-14 accounts for it to become stable

**Comment by Burbankian** [comment]
if you don't care about pokestops ( or gyms)  
you can disable them in config (if you haven't yet)

**Comment by secondhandnudes** [comment]
@HollyKohai Any tips on how you set this up to not break after running through a single scan? I've got fewer accounts running at a smaller radius and cannot get it to run continuously. Completely uninstalled and deleted all files and did a fresh install and still running into the issue right away

**Comment by HollyKohai** [comment]
@secondhandnudes basically i left the scan radius at 10, put the accounts down to 8, and just increased the number of accounts after leaving up for 20 minutes without issue (checking developer tools in case the >50 happened again. If it does, you've gone too far)

**Comment by secondhandnudes** [comment]
@HollyKohai Thanks, going to start working through process of elimination here to see why I'm not getting same results. I keep gyms, lured pokestops, pokemon, and spawn points up on scanner. Do you think any of this has an effect / what are you tracking? Right now I have radius 8 and 12 accounts; going to cut accounts in half and work up from there if that works.

**Comment by EternisRequiem** [comment]
@Burbankian I don't know how to do this in the desktop app version? I saw you can add this to config in the main pogo map thread, but I don't know how to implement it...

 webhook-updates-only:   true
# only sendeupdates to webhooks, (excludes gyms & non-lured pokéstops)

**Comment by Burbankian** [comment]
I didn't touch the webhookupdatesonly
I just removed the "#" from 'no-gyms' and 'no-pokestops' and set them to **true**

**Comment by EternisRequiem** [comment]
Where is this located in the desktop map config?  I can't even *find* the config in all the damn folders lol

**Comment by Burbankian** [comment]
go to the PoGodesktopmap file location > app "version" > resources > app > map > config 
if you havent touched anything there yet, there will be an EXAMPLE file there, just turn it into config.ini  
NotePad++

**Comment by IonJam** [comment]
When I use the config file with even a single line uncommented, the program refuses to work again, it's just stuck on "Loading, wait..." forever, unless I delete the config file.

**Comment by almaloul** [comment]
Honestly I had the same issue with the non html based version and it turned out to be the actual Sqlite db built into the build not being able to be used my multiple writers properly, I setup mariadb and input the mysql info in to config and now am running 70+ workers (accounts) with no error db thread >50, not sure if that helps with the desktop version

**Comment by almaloul** [comment]
Burbankian's suggestion is correct, try downloading mariadb and set up a new db, then alter config.ini to run on mysql not the default Sqlite and input all of the information, see if that works

**Comment by almaloul** [comment]
Use notepad++ to modify config.ini

**Comment by Burbankian** [comment]
@IonJam did you also fill in username, password, location, and gmaps key?  
those fields are required, and dont forget to remove the '#'

**Comment by AerosHawk** [comment]
Could anyone drop an attachment of their working config file? I'm not able to get mine working. Please edit personal info too as I don't want to be held liable for that kind of thing.

Really I just need an example of a working config file to see if I can do this. I have 20 accounts, and a radius of 7 set up. I get one search, usually on the top half first, some delay for it to hit the bottom half, and then nothing it quits out till I restart it.

**Comment by HollyKohai** [comment]
@AerosHawk I use around 12 Accounts for 10 Radius. (Sometimes it'll stop working after a few days so I go down to 11 accounts).

So decrease your account numbers to only 5 accounts, see if the increase db thread comes back, if not then increase till it does, then you know the limit for your 7 radius.

**Comment by AerosHawk** [comment]
@HollyKohai 
Still wish I could replace the sqlite db...

**Comment by Burbankian** [comment]
this is my config.ini (with edited user/pass/loc/ApiK)  
it comes with disabled gym and pokestop detection  
if you want those to be detected, just put "#" before those lines
https://www.dropbox.com/s/lmprdmvf9sa77nv/config.ini?dl=0

remember to use NotePad++

**Comment by secondhandnudes** [comment]
Thank you to everyone giving advice in this thread. I used the config.ini from @Burbankian and filled in my own values, and now appear to be successfully running my full 12 accounts without any database errors. I didn't download mariadb and set up a new db or anything, but if anyone else is having an issue getting the config.ini working, post in here and I'll try to help

**Comment by EternisRequiem** [comment]
Do you leave config.ini in the config folder or put it in app folder, or...?
I just see in the dev tools console that it's reporting pokestops and gyms still (or does this still happen?)

**Comment by secondhandnudes** [comment]
I left it where it was, and I also disabled pokestops but not gyms; the dev tools console reports "0 pokestops and x gyms"

**Comment by Burbankian** [comment]
it should be in the config folder  
resources > App > map > config (this one)

**Comment by PokeFinders** [comment]
Finally!  This build now actually works the way it was intended after disabling the pokestop detection.  Much thanks to @Burbankian for the jumpstart on the config.ini!  I've got 40 accounts running on a 30 radius that sweeps the entire area once every 14 minutes.

**Comment by mitchganjjah** [comment]
I feel like an idiot but I can't find config.ini or any installed file for this map.  The only file it puts on my system is the PokemonMap-Win.exe that i downloaded.  Where is the install???
