### ISSUE TITLE
See which worker accounts are possibly banned?

### ISSUE THREAD

**Issue by ShiroyashaGin** [mchristopher/PokemonGo-DesktopMap#1237]
If you have mutliple accounts set up it sometimes says "possible ban" in the status box. Is there a way of being able to see which account it is trying to use at that moment so that i can remove that account from the list.

**Comment by ehsians** [comment]
Go to Tools/ Toogle Developer Tools.
Then when you START your server, 
look at the codes at the top. Successful should look like this...

main.html:169 2016-09-19 07:21:59,016 [ search-worker-0][      auth_ptc][    INFO] PTC User Login for: pokemon12345678

main.html:169 2016-09-19 07:21:59,682 [ search-worker-0][      auth_ptc][    INFO] PTC User Login successful.


Look for something that might say unsuccessful or fail.

**Comment by ehsians** [comment]
Also, FILTER and look for consistent 0 search results over long period of time
Parsing found 0 pokemons, 0 pokestops, and 0 gyms

**Comment by random189268** [comment]
I don't understand the point of the /status page. When I type in the password I set it just shows a blank screen. Is this a defect or is there just something wrong with my setup?
