### ISSUE TITLE
Scanning two locations

### ISSUE THREAD

**Issue by bugglesnug** [mchristopher/PokemonGo-DesktopMap#1238]
Hi. The other day I was scanning a location and the app crashed, and when I restarted (with a new location) it was still scanning the old location. Now whenever I launch the app, regardless of location, it will still be stuck scanning the old location as well as whatever location I enter. It will show pokemon at both. It's been stuck like this for a few days now. Basically there are two separate light green honeycomb patterns on the map a few miles away. See attachment.
![captdfgdfgure](https://cloud.githubusercontent.com/assets/6424259/18599405/f6320d3e-7c1d-11e6-9499-69747363f99a.JPG)

**Comment by MichaelSchra** [comment]
I had this happen when I got back to Chicago from Florida.  It would simoultainiously scan my old FL location and Chicago location.  I fixed it by deleting everything in c:/users/me/appdata/pokemongo/

**Comment by raivic** [comment]
I'm having this same issue. I'm running the OSX version and I can't seem to find the app data folder.

**Comment by equanimitivity** [comment]
I am having the same issue as well, but with multiple locations, not just 2. Also running OSX but I seemed to clear it up by deleting any files that had pokemon in the name in this directory:
~/Library/Preferences/

**Comment by macinmn** [comment]
if you're running on Windows, it's likely running still in the background.  kill the python processes with this from cmd/start :
taskkill /f /im python.exe
