### ISSUE TITLE
No Pokemon

### ISSUE THREAD

**Issue by mewtwo4333** [mchristopher/PokemonGo-DesktopMap#1239]
Pokemon aren't appearing for me at all. There are Pokemon on the nearby list, but nothing appears on the map except pokestops and gyms. I made sure that it was set to show Pokemon and pokestops.

![screenshot 1](https://cloud.githubusercontent.com/assets/22247070/18602005/20c5e0fa-7c1b-11e6-8b04-1395a0aa8b32.png)

**Comment by HighOnTacos** [comment]
Same thing started happening to me today aswell. Hope there's a fix soon.

**Comment by jijetelu** [comment]
anyone figured out what is happening ?
