### ISSUE TITLE
Feature Request - Use in IIS for Website

### ISSUE THREAD

**Issue by mathis1337** [mchristopher/PokemonGo-DesktopMap#124]
So I downloaded the source code and uploaded to a server. The login page pops up, however, after I click login it just clears everything and never proceeds forward? Is that because this can't be run as a web application or does something else need to be done? Reason I ask is this would be super useful if I could use it on the go on my phone through a browser. THanks!

**Comment by Pineyka** [comment]
I had this problem.
Try to my description of the post # 122 and write it works.

**Comment by mathis1337** [comment]
I don't think you understood. I can get the exe version working fine. I downloaded source code and wanted to run it in IIS through a website. I saw there was .html files and .js which should run fine through IIS, however, nothing happens after I login. It just looks like it refreshed the page.

**Comment by Pineyka** [comment]
You pulled two files with the program and threw to the IIS? :)))
Well, maybe I did not understand.
But one thing I know for sure. As I took out the engine and steering with my Toyota and put it into a wheelbarrow could not ride it.
I had to make a lot of modifications in my wheelbarrow to make it work.

**Comment by mathis1337** [comment]
I didn't pull two file. I referenced file types. You don't understand my question. Thanks anyways though.

**Comment by mchristopher** [comment]
This project isn't designed to work on a server - it relies on desktop-specific functions and a python backend process. If you're looking for a server-based solution, I recommend looking into https://github.com/AHAAAAAAA/PokemonGo-Map.
