### ISSUE TITLE
Not an Issue database file

### ISSUE THREAD

**Issue by gauravyadav26** [mchristopher/PokemonGo-DesktopMap#1240]
can people send me there database files old and new files I'am tring to make a combined map
send them at gauravyadav2601@gmail.com

**Comment by CTMapper** [comment]
Are you assembling a combined map?  I think this would be fantastic!  With the many people running this program, it would be an amazing community resource to mine for trends, or seek out hotspots for a particular pokemon.  It would be better than many of the self-reporting ones that are out there, or could be a better backend source to one of those sites (perhaps that's what you're doing?).

Are you getting files?  Do you have an example of what you're doing?  I'm happy to email you my pogom-0.3.4.db but it'd be great to hear more of your plans, and get more people promoting this effort.

**Comment by CTMapper** [comment]
Also, given most email services limit file size, you'll probably need to find a better site where people can just upload them.  For example, my db is 35mb and my email account will only let me send 25mb max files.

For others reference, your db file is at:   /Users/NAME/AppData/Roaming/pokemon-go-map/pogom-0.3.4.db

**Comment by gauravyadav26** [comment]
I have received just 1 files yet, my thinking behind this was to find hotspots for people to catch what they are looking for, plus people like us living in cities its not that of an issue but people in rural areas limited resources to play with (gyms and stops) so for them if there is a map which tells them about all the gyms and stops, that will be really helpful for them. I have no technological knowledge so I have tried my best and have made this site www.pokegym.ga , data on it is limited as its just the data I mined myself.
