### ISSUE TITLE
any way to see IV stats?

### ISSUE THREAD

**Issue by tinarazzburton** [mchristopher/PokemonGo-DesktopMap#1241]
I've seen some scanners that show IV stats on pokemon.  It would be cool if we could see that and also set alerts for high IV pokemon.

**Comment by imadummy1** [comment]
@tinarazzburton That feature was recently merged. Execute `git gud` at the command prompt to install it

**Comment by Coolc6401** [comment]
@imadummy1 Where can I find the command prompt?
