### ISSUE TITLE
Map stuck on 'Waiting'

### ISSUE THREAD

**Issue by Mharper554** [mchristopher/PokemonGo-DesktopMap#1243]
Where it says "operational" or "outage" or "possible ban" it is stuck saying "waiting". What causes this? Btw it wont scan. I have functional ptc and google accounts on it.

**Comment by gaaroth** [comment]
same problem, opening the console i get this error

`resources\app\map\pogom\models.py", line 557, in parse_map cells = map_dict['responses']['GET_MAP_OBJECTS']['map_cells']`

Right on a fresh install
