### ISSUE TITLE
No longer showing Pokemon at lures ?

### ISSUE THREAD

**Issue by tinarazzburton** [mchristopher/PokemonGo-DesktopMap#1246]
I just realized that the app doesn't seem to be showing Pokemon that spawn at lures.  Did that change recently or have I just not noticed ?

**Comment by RMPPARTS** [comment]
I have had this installed for over 2 weeks and the Lured Pokémon spawns have never showed up.  I did not know this was a previous function.  
Does any one know if this can be fixed?

**Comment by mwaraya** [comment]
this stop working in the previous update (like 1 month ago...). My guest its that niantic change something (the new tracking system that still its not released..)

**Comment by tinarazzburton** [comment]
It had been a previous function.  You would see all the pokemons that spawned that lures (usually disappeared in like 2-3 mintues), and you could also click on any pokestop to see what was currently spawned there.
