### ISSUE TITLE
On Windows 10, stops working after roughly 40 min

### ISSUE THREAD

**Issue by mygo89** [mchristopher/PokemonGo-DesktopMap#125]
I set it up running and shared it with my phone, only to realise it stopped updating after about 40 mins. Have to re-login to get it going again, refresh doesn't solve the issue.

**Comment by koliha** [comment]
This is related to this issue #72 and has already been addressed (changes have been committed). Fix should be present in release 0.0.8 (not released yet, hopefully soon?).

**Comment by mchristopher** [comment]
This should be fixed in the latest release.
