### ISSUE TITLE
Unexpected/unsupported platform 'linux2'

### ISSUE THREAD

**Issue by ivomarsan** [mchristopher/PokemonGo-DesktopMap#1250]
When I execute `npm start`, I receive

`Python: Traceback (most recent call last):
  File "./run_map.py", line 7, in <module>
    import check_prereqs
  File "/home/ivomarsan/tests/PokemonGo-DesktopMap/app/check_prereqs.py", line 30, in <module>
    raise Exception(err)
Exception: Unexpected/unsupported platform 'linux2'.
`
Help

**Comment by imadummy1** [comment]
@ivomarsan `npm start` is trying to execute your npm modules but this release has python and git issues on linux as you've seen. Could you execute `git gud` at the command line and post the output?

**Comment by ivomarsan** [comment]
`$ git gud
git: 'gud' não é um comando git. Veja 'git --help'.

Você quis dizer isso?
	add
`

`git gud` is not a git command

**Comment by imadummy1** [comment]
@ivomarsan It looks like your installation of Git is either out of data or corrupted. Its not safe to work with a corrupted version. I'd suggest that you remove Git entirely from your system and then re-execute `git gud` as it should fix your issues.

**Comment by ivomarsan** [comment]
I'm not getting
