### ISSUE TITLE
Statistics logging does not save data from previous launches

### ISSUE THREAD

**Issue by mhujsak** [mchristopher/PokemonGo-DesktopMap#1251]
If you quit the app and log back in, the statistics are reset.  If that data was logged we could analyze statistics over all of our collected data. 

I'm surveying a particular area near my office that has a bunch of rare spawns.  It would be helpful to aggregate all of my info to figure out best spawning times and plan breaks around those windows.

It would also be great if this accomodated future updates of Pokemon Go.  If this feature allowed you to select date ranges or expunge old data you'd be covered in the event of a reset.

**Comment by Rayenous** [comment]
I've got this installed on 3 different machines (none run at the same time).  One system logs the statistics properly, one has the same issue you have, and the third (the one I want to use most often) only keeps statistics of the pokemon that are currently on the map... the moment a pokemon despawns, it is no longer in the statistics.

All systems are OSX... 10.9.5 logs properly... 10.10.1 only shows stats of current pokemon on the map... the third (I think OSX 10.9.??) only keeps stats of current session.
