### ISSUE TITLE
Multi account

### ISSUE THREAD

**Issue by Zikaba** [mchristopher/PokemonGo-DesktopMap#1254]
Is there a way to add bulk account for quickest scan ?
For each account i want to add, i need to "add", then start, logout and add again.

Thanks !

**Comment by imadummy1** [comment]
@Zikaba Did you try executing `git gud` in a command prompt?

**Comment by Burbankian** [comment]
I know one way  
Toggle Developer Tools  
go to Resources 
click Local Storage
select file:// 
the lowest key there is user_acct, thats what I change when I'm changing accounts  
I saved my account information in notepad and just copy-paste
