### ISSUE TITLE
Feature Request: Only scan areas with spawn points?

### ISSUE THREAD

**Issue by datrinh** [mchristopher/PokemonGo-DesktopMap#1255]
I noticed that you can see the spawn points with spawn times now. That's an awesome cool feature!
Wouldn't that make it possible to only scan those areas or even only at those times? Wouldn't it make things way more efficient and faster?

**Comment by pehmolelu** [comment]
+1. First it should scan the whole area and after that only spawn points

**Comment by toddstar** [comment]
you just need to update(/add a line in) main.js with `--spawnpoint-scanning` under `var cmdLine = [`
