### ISSUE TITLE
Update & DB deletion

### ISSUE THREAD

**Issue by mazeeville** [mchristopher/PokemonGo-DesktopMap#1256]
hey been using this for the past week and really happy with it. I have 2 questions though:
Will this be updated again anytime soon with IVs and possibly lured spawns?
Second: I have been told to delete the DB so it doesnt get too big... How would i do that on OSX macbook pro?

**Comment by Rayenous** [comment]
All the 'scan sites' I've seen that list IV's appear to rely on user input to get the IV's. - Is the IV information available in the data sent back on this type of scan?

**Comment by minim8** [comment]
@Rayenous You need to encounter the Pokemon for this extra data.. Still, its possible and someone already wrote the code. See the link in my thread for more info 
https://github.com/mchristopher/PokemonGo-DesktopMap/issues/1257

**Comment by Burbankian** [comment]
IV determination may be different now, there are threads on TSR saying that their getting different IV values (and moveset) despite catching the pokemon on the same spawn point at the same time with their friend/s

**Comment by minim8** [comment]
@Burbankian can you link a source pls? checked it 14 hours ago (only a sample size of 4) but they all had identical IV and movesets

**Comment by Burbankian** [comment]
actually, I tested it with my friend earlier, and we still get the same moveset/IV  
I'm trying to find the reddit post and can't seem to find it, looks like what the player experienced are anecdotal bugs :/

**Comment by AerosHawk** [comment]
IVs and movesets seem to only differ if that other person is on a different team.

Me and my girl, both team Valor, get the same IVs and same moveset every time without fail.
