### ISSUE TITLE
Add/Implement this pls to show IV + Moveset!

### ISSUE THREAD

**Issue by minim8** [mchristopher/PokemonGo-DesktopMap#1257]
https://github.com/PokemonGoMap/PokemonGo-Map/pull/1272

Not my work, but still an awesome feature which would safe alot of time. I would recommend to filter all Pokemon by default and add a List where you can add Pokemon for which the IV+Move check should be performed.

**Comment by jasonasey** [comment]
Did you put the coding intho the json file? any help on how to get this working on mine?

**Comment by heyitzdinny** [comment]
would like to know how to set this up?

**Comment by harrison0550** [comment]
If anyone can provide a setup guide or walkthrough on how to get this working that would be much appreciated. Sorry most of this is foreign to me.

**Comment by himeshpatel88** [comment]
+1 is there a way to add this to the app without having any coding experience? Or is this being worked on already? If so, what is the ETA on release?

**Comment by tedtim** [comment]
That map is the backend for this app. It looks like it might be added to that map in the future as an option, so it might get added to this app.
i have it running in my setup, it works well.

**Comment by simonbuehler** [comment]
@tedim sorry offtopic, but mind explaining the steps? (on windows if possible)

**Comment by Burbankian** [comment]
I tried putting it on mchristopher's map, but I guess I'm not skillful enough :/   
I don't really want to change maps, I like mchristopher's release :)

**Comment by tleple** [comment]
@tedtim Do oyu mind make a video tutorial how to do it ?

**Comment by tedtim** [comment]
when i set this up, i deleted my existing map and changed to a mysql server I already had setup. this will change the DB to version 8 and add an extra column in the tables.

**Comment by simonbuehler** [comment]
ok current developer branch has this implemented, build from git and replace the map with the new version works

**Comment by harrison0550** [comment]
I genuinely wish I knew what that meant. Regretting going into marketing at this point and not learning more about coding. Sighhhh Curse you computers for coming out after I graduated high school.

**Comment by simonbuehler** [comment]
There is a good [Installation](https://pgm.readthedocs.io/en/develop/basic-install/index.html) howto for git developer version and you'll be there in 20minutes, i personally switched to the map without the (excellent) wrapper mchristopher built, gives you some advanced configuration options but remote sharing is easier with this wrapper

**Comment by toddstar** [comment]
it doesn't work on this wrapper, you either need to wait for mchristopher to update or do a clean install of PokemonGoMap
