### ISSUE TITLE
Please make settings on mobile phone permanent

### ISSUE THREAD

**Issue by Nonkel** [mchristopher/PokemonGo-DesktopMap#1258]
Hi,

I suspect this is rather difficult, but with every new linking of my phone to the scanner (I shut down at night, or when Im away not catching anything etc) and opening my browser on my phone, I see ALL pokemon so I need to repeat the process of excluding a lot of them. Otherwise I just cant see the good stuff, you know...crowded by pidgies and the likes.

So, is there a way to let my mobile browser 'remember' these settings? For example, I dont wanna see pokestops but do want to see gyms. On startup, I have to manually switch those. Not a big deal, but still would be a great QOL improvement...

**Comment by toddstar** [comment]
the only way to remember settings is to setup port forwarding on your router to your machine & not use the 'mobile' sharing; the mobile/share will always start a new 'connection' which drops the remembered settings

**Comment by Nonkel** [comment]
Thanks for the suggestion, but I have no idea which steps to take to do what you describe...

**Comment by toddstar** [comment]
have a look for your router on here https://portforward.com/router.htm and follow the instructions
