### ISSUE TITLE
[Question] What units is the "radius" setting measured in?

### ISSUE THREAD

**Issue by emliv** [mchristopher/PokemonGo-DesktopMap#126]
What units is the "radius" setting measured in?

**Comment by fangwei007** [comment]
Really like this App, when will the new version be released ? Gonna need it for this afternoon

**Comment by fenixasin** [comment]
@fangwei007, then learn to code and contribute. That is really rude hijacking someone elses question

**Comment by mchristopher** [comment]
I think it's roughly 1 unit to every 100 meters, though I'm not completely sure. That code is based on another project.

**Comment by fangwei007** [comment]
@fenixasin Are you out of your mind ? ppl just asked a simple question and who are you exactly join git since July 20,2016? Com'n you are the one who need to learn coding first sprout!
