### ISSUE TITLE
No Pokemon Showing Up on Map

### ISSUE THREAD

**Issue by QueenEtherea** [mchristopher/PokemonGo-DesktopMap#1260]
So, I downloaded this wonderful app a few weeks ago. I've loved it and have been using it every day since I downloaded it. Unfortunately, today, I opened the app and see the red "OUTAGE" at the top, but it very quickly turns to "OPERATIONAL". It seems to work fine where the red marker initially starts, but when I move the marker, no Pokemon show up. You can see where the marker started because there's some Pokemon there, but I moved the marker and waited 5 minutes before snapping that screenshot. Is there just an issue with the server right now? Any input would be lovely!
![screenshot 9](https://cloud.githubusercontent.com/assets/22436790/18819914/7e8b59e8-834d-11e6-9c48-c1a641d500a5.png)

**Comment by Burbankian** [comment]
turn on scanned location, the marker may be there, but the scanners "might be" in a different place

**Comment by fusenuk** [comment]
Following on from what burbankian said, if you turn on the 'scanned locations' toggle within Marker Settings and you notice the green scanned area hasn't moved when you moved the cursor, you may need to check what 'scan follow's location' is toggled to under 'Location Settings'

**Comment by QueenEtherea** [comment]
I've turned on the "SCANNED LOCATIONS" and it's showing that it's scanning the area. However, the Pokemon don't show up until like 10 minutes later. It usually shows them pretty quickly.

**Comment by QueenEtherea** [comment]
It seems the problem has resolved itself. A few people in my area were experiencing some issues with the Pokemon Go app itself yesterday, so maybe that was the issue. Thank you for everyone who responded.

**Comment by himeshpatel88** [comment]
+1, i am having the same issue, scanned locations on, can see the scanning area all green, span points even changing colours, the pokemon just arent showing up, for information purposes, i have 7 acc scanning at radius of 7. I previously had then on radius of 6 and they were showing up yesterday, did a restart on my laptop and changed nothing else, no pokemon showing up, any insights would be great!

**Comment by QueenEtherea** [comment]
This is probably a dumb question, but what is the purpose of having multiple accounts? Also, how do you change the radius?
