### ISSUE TITLE
[USER SPECIFIC] Pokemongo map gui can launch, but cmd line fails

### ISSUE THREAD

**Issue by saics72** [mchristopher/PokemonGo-DesktopMap#1261]
I do not know what the problem is, I can launch the gui fine, but when I try cmd line, I get the following error:
2016-09-25 18:54:42,878 [ MainThread][ runserver][CRITICAL] It seems p goapi is not up-to-date. You must run pip install -r requirements.txt again
I did run that command, here is my output:
C:\Users\saics\AppData\Local\pokemon\app-0.3.4\resources\app\map>pip install -r requirements.txt --upgrade Requirement already up-to-date: six==1.10.0 in c:\python27\lib\site-packages (fr om -r requirements.txt (line 1)) Requirement already up-to-date: Flask==0.11.1 in c:\python27\lib\site-packages ( from -r requirements.txt (line 2)) Requirement already up-to-date: gevent==1.1.2 in c:\python27\lib\site-packages ( from -r requirements.txt (line 3)) Requirement already up-to-date: Jinja2==2.8 in c:\python27\lib\site-packages (fr om -r requirements.txt (line 4)) Requirement already up-to-date: MarkupSafe==0.23 in c:\python27\lib\site-package s (from -r requirements.txt (line 5)) Requirement already up-to-date: Werkzeug==0.11.10 in c:\python27\lib\site-packag es (from -r requirements.txt (line 6)) Requirement already up-to-date: configargparse==0.10.0 in c:\python27\lib\site-p ackages (from -r requirements.txt (line 7)) Requirement already up-to-date: click==6.6 in c:\python27\lib\site-packages (fro m -r requirements.txt (line 8)) Requirement already up-to-date: itsdangerous==0.24 in c:\python27\lib\site-packa ges (from -r requirements.txt (line 9)) Requirement already up-to-date: peewee==2.8.1 in c:\python27\lib\site-packages ( from -r requirements.txt (line 10)) Requirement already up-to-date: wsgiref==0.1.2 in c:\python27\lib\site-packages (from -r requirements.txt (line 11)) Requirement already up-to-date: geopy==1.11.0 in c:\python27\lib\site-packages ( from -r requirements.txt (line 12)) Requirement already up-to-date: s2sphere==0.2.4 in c:\python27\lib\site-packages (from -r requirements.txt (line 13)) Requirement already up-to-date: PyMySQL==0.7.5 in c:\python27\lib\site-packages (from -r requirements.txt (line 14)) Requirement already up-to-date: flask-cors==2.1.2 in c:\python27\lib\site-packag es (from -r requirements.txt (line 15)) Requirement already up-to-date: flask-compress==1.3.0 in c:\python27\lib\site-pa ckages (from -r requirements.txt (line 16)) Requirement already up-to-date: LatLon==1.0.1 in c:\python27\lib\site-packages ( from -r requirements.txt (line 17)) Collecting pgoapi from git+https://github.com/PokemonGoMap/pgoapi.git#egg=pgoapi (from -r requirements.txt (line 18)) Cloning https://github.com/PokemonGoMap/pgoapi.git to c:\users\saics\appdata\l ocal\temp\pip-build-n7cosw\pgoapi Requirement already up-to-date: xxhash in c:\python27\lib\site-packages (from -r requirements.txt (line 19)) Requirement already up-to-date: sphinx==1.4.5 in c:\python27\lib\site-packages ( from -r requirements.txt (line 20)) Requirement already up-to-date: sphinx-autobuild==0.6.0 in c:\python27\lib\site- packages (from -r requirements.txt (line 21)) Requirement already up-to-date: recommonmark==0.4.0 in c:\python27\lib\site-pack ages (from -r requirements.txt (line 22)) Requirement already up-to-date: sphinx_rtd_theme==0.1.9 in c:\python27\lib\site- packages (from -r requirements.txt (line 23)) Requirement already up-to-date: requests==2.10.0 in c:\python27\lib\site-package s (from -r requirements.txt (line 24)) Requirement already up-to-date: PySocks==1.5.6 in c:\python27\lib\site-packages (from -r requirements.txt (line 25)) Collecting flask_cachebust from git+https://github.com/maddhatter/Flask-CacheBus t.git@38d940cc4f18b5fcb5687746294e0360640a107e#egg=flask_cachebust (from -r requ irements.txt (line 26)) Cloning https://github.com/maddhatter/Flask-CacheBust.git (to 38d940cc4f18b5fc b5687746294e0360640a107e) to c:\users\saics\appdata\local\temp\pip-build-n7cosw\ flask-cachebust Could not find a tag or branch '38d940cc4f18b5fcb5687746294e0360640a107e', ass uming commit. Requirement already up-to-date: protobuf_to_dict==0.1.0 in c:\python27\lib\site- packages (from -r requirements.txt (line 27)) Requirement already up-to-date: greenlet>=0.4.9 in c:\python27\lib\site-packages (from gevent==1.1.2->-r requirements.txt (line 3)) Requirement already up-to-date: future in c:\python27\lib\site-packages (from s2 sphere==0.2.4->-r requirements.txt (line 13)) Requirement already up-to-date: pyproj in c:\python27\lib\site-packages (from La tLon==1.0.1->-r requirements.txt (line 17)) Requirement already up-to-date: protobuf>=3.0.0a3 in c:\python27\lib\site-packag es (from pgoapi->-r requirements.txt (line 18)) Requirement already up-to-date: gpsoauth==0.4.0 in c:\python27\lib\site-packages (from pgoapi->-r requirements.txt (line 18)) Requirement already up-to-date: imagesize in c:\python27\lib\site-packages (from sphinx==1.4.5->-r requirements.txt (line 20)) Requirement already up-to-date: docutils>=0.11 in c:\python27\lib\site-packages (from sphinx==1.4.5->-r requirements.txt (line 20)) Requirement already up-to-date: babel!=2.0,>=1.3 in c:\python27\lib\site-package s (from sphinx==1.4.5->-r requirements.txt (line 20)) Requirement already up-to-date: colorama>=0.3.5; sys_platform == "win32" in c:\p ython27\lib\site-packages (from sphinx==1.4.5->-r requirements.txt (line 20)) Requirement already up-to-date: Pygments>=2.0 in c:\python27\lib\site-packages ( from sphinx==1.4.5->-r requirements.txt (line 20)) Requirement already up-to-date: snowballstemmer>=1.1 in c:\python27\lib\site-pac kages (from sphinx==1.4.5->-r requirements.txt (line 20)) Requirement already up-to-date: alabaster<0.8,>=0.7 in c:\python27\lib\site-pack ages (from sphinx==1.4.5->-r requirements.txt (line 20)) Requirement already up-to-date: watchdog>=0.7.1 in c:\python27\lib\site-packages (from sphinx-autobuild==0.6.0->-r requirements.txt (line 21)) Requirement already up-to-date: pathtools>=0.1.2 in c:\python27\lib\site-package s (from sphinx-autobuild==0.6.0->-r requirements.txt (line 21)) Requirement already up-to-date: argh>=0.24.1 in c:\python27\lib\site-packages (f rom sphinx-autobuild==0.6.0->-r requirements.txt (line 21)) Requirement already up-to-date: tornado>=3.2 in c:\python27\lib\site-packages (f rom sphinx-autobuild==0.6.0->-r requirements.txt (line 21)) Requirement already up-to-date: port-for==0.3.1 in c:\python27\lib\site-packages (from sphinx-autobuild==0.6.0->-r requirements.txt (line 21)) Requirement already up-to-date: PyYAML>=3.10 in c:\python27\lib\site-packages (f rom sphinx-autobuild==0.6.0->-r requirements.txt (line 21)) Requirement already up-to-date: livereload>=2.3.0 in c:\python27\lib\site-packag es (from sphinx-autobuild==0.6.0->-r requirements.txt (line 21)) Requirement already up-to-date: commonmark<=0.5.4 in c:\python27\lib\site-packag es (from recommonmark==0.4.0->-r requirements.txt (line 22)) Requirement already up-to-date: setuptools in c:\python27\lib\site-packages (fro m protobuf>=3.0.0a3->pgoapi->-r requirements.txt (line 18)) Requirement already up-to-date: pycryptodomex>=3.0 in c:\python27\lib\site-packa ges (from gpsoauth==0.4.0->pgoapi->-r requirements.txt (line 18)) Requirement already up-to-date: pytz>=0a in c:\python27\lib\site-packages (from babel!=2.0,>=1.3->sphinx==1.4.5->-r requirements.txt (line 20)) Requirement already up-to-date: singledispatch in c:\python27\lib\site-packages (from tornado>=3.2->sphinx-autobuild==0.6.0->-r requirements.txt (line 21)) Requirement already up-to-date: certifi in c:\python27\lib\site-packages (from t ornado>=3.2->sphinx-autobuild==0.6.0->-r requirements.txt (line 21)) Requirement already up-to-date: backports_abc>=0.4 in c:\python27\lib\site-packa ges (from tornado>=3.2->sphinx-autobuild==0.6.0->-r requirements.txt (line 21)) Installing collected packages: pgoapi, flask-cachebust Found existing installation: pgoapi 1.1.6 Uninstalling pgoapi-1.1.6: Successfully uninstalled pgoapi-1.1.6 Running setup.py install for pgoapi ... done Found existing installation: Flask-CacheBust 1.0.0 Uninstalling Flask-CacheBust-1.0.0: Successfully uninstalled Flask-CacheBust-1.0.0 Running setup.py install for flask-cachebust ... done Successfully installed flask-cachebust-1.0.0 pgoapi-1.1.6

Do you have any suggestions?

Thanks

**Comment by imadummy1** [comment]
@saics72 It looks like you have an issue with Git and python. Can you go to a command prompt and run `git gud` and post the output here?
