### ISSUE TITLE
Can't move the location in mobile

### ISSUE THREAD

**Issue by wiggin36** [mchristopher/PokemonGo-DesktopMap#1262]
When I'm in mobile I can't change the location, I already turn off the option of lock location but that didn't help, the mark goes back to the location in the desktop automatically, and if I change it in the desktop the scanner stops working in my cellphone.

**Comment by QueenEtherea** [comment]
This has happened to me a few times as well. When it does happen, I go to the computer, and it usually shows "POSSIBLE BAN" at the top. I just log out and log back in , toggle mobile again, and it ends up working again.

**Comment by caiobrreis** [comment]
go to options > location settings > disable 'Lock Marker'

**Comment by Burbankian** [comment]
what browser are you using on your mobile?   
I tried it with dolphin browser and it didn't work  
but when I use chrome, location change works fine

**Comment by hbalagtas** [comment]
For some reason it doesn't work on Safari on iOS 10 either but works fine on Chrome.

**Comment by steeltown84** [comment]
It actually works for me in Safari iOS10...

**Comment by wiggin36** [comment]
Just tried it with Chrome as burbakian says, it works better than Safari. Other thing I noticed is that in Safari when I reload the page it takes me out, in Chrome it works fine.
