### ISSUE TITLE
How to remove old spawn points?

### ISSUE THREAD

**Issue by Jesselscott** [mchristopher/PokemonGo-DesktopMap#1264]
I tried uploading a new API.  I thought that would allow me to start with a new slate and map all of the new spawn points but the spawn points persisted from the old map.  Can someone tell me how to start fresh?  Is there a file on my hard drive I can delete?

**Comment by Burbankian** [comment]
go to USER\AppData\Roaming\pokemon-go-map  
you'll find a database file there  
if you are using 0.3.4, the db file is "pogom-0.3.4"  
either rename that file, or remove that file from the folder  
PoGoMap will automatically make a new one

**Comment by davidmorr** [comment]
Every so often, Niantic changes the spawn points so many of the ones on the map are no longer valid. It would be useful if spawn points that had not been used for a while, e.g., two weeks, just disappeared.

**Comment by datrinh** [comment]
Where do I find the DB on mac?

**Comment by davidmorr** [comment]
~/Library/pokemon-go-map/pogom0.3.4db

**Comment by steeltown84** [comment]
or ~>Users>_username_>Library>Application Support>pokemon-go-map
