### ISSUE TITLE
JavaScript error on login

### ISSUE THREAD

**Issue by ntorsday** [mchristopher/PokemonGo-DesktopMap#1265]
Why do I always get a JavaScript Error on start. Whenever I click "Start Server" it gives me a JavaScript Error, then when I click "OK" it says possible ban on the top and doesn't scan. I have tried this with multiple new accounts(All PTC). I just re-downloaded the application and I get the same result. I'm running Windows 10 on an HP laptop. I get the same error on my PC as well.

JavaScript Error:(https://cloud.githubusercontent.com/assets/20603772/18895397/ee584956-84de-11e6-98a7-4d5c0373e710.PNG)

Possible Ban:(https://cloud.githubusercontent.com/assets/20603772/18895526/e312ea28-84df-11e6-8e77-c8b8db318a73.png)

Thanks,
-NT

UPDATE: It only gives me the JavaScript Error when I input my location on the starting screen. It still does the "waiting..." then the "Possible ban" message.

**Comment by Burbankian** [comment]
I get javascripts error, but they're not really important  
as for the possible ban, is this the 1st time you used this map?   
or have you used it before and "possible ban" suddenly appeared?

**Comment by ntorsday** [comment]
@Burbankian I have used this application multiple times but it started happening about 3 weeks ago.
