### ISSUE TITLE
Map not scanning

### ISSUE THREAD

**Issue by coolykid** [mchristopher/PokemonGo-DesktopMap#1266]
Whenever i leave the map open for a while it stops scanning randomly.
I have scanned locations on, along with 10 accounts running.
Pretty frequently all the map will turn red, where its usually green.
The status at the top remains saying its still operational, but it stops scanning completely.
This happens once every hour or so, and i can fix it by logging out and restarting it.
Does anyone have a fix for this?
Thanks!
Coolykid

**Comment by HollyKohai** [comment]
Lower number of accounts or increase range. DB running over itself. I run a 10 range with around 10 accounts and it works. If I go above those 10 accounts same problem. Issue with db thread

**Comment by coolykid** [comment]
I was running 10 with 7 range, ill try now and check if 10 works, thanks

**Comment by coolykid** [comment]
Nope, same thing happened. About an hour in it just stops and quits. it still says operational but the squares are all turning yellow and red

**Comment by Burbankian** [comment]
once the scan circles are going red
open developer tools and go to console  
we might see the problem there
I think this might also be linked to 50 db threads

**Comment by coolykid** [comment]
Will do when it happens again

**Comment by DESP90** [comment]
What helped for me, is that I stopped scanning for pokestops and gyms.

I did this by editing the config.ini file, which for me is located at C:\Users\MyName\AppData\Local\pokemon\app-0.3.4\resources\app\map\config.

I removed the # before 'no-gyms' and 'no-pokestops and typed 'true' after the :.

The config.ini file has to be edited in Notepad++.

**Comment by coolykid** [comment]
https://gyazo.com/b55e47f3d53e29385a3e0ec1c601ecfb @Burbankian a picture of the console
It keeps saying "database is locked"

**Comment by Burbankian** [comment]
I'm not sure about the "db is locked" issue  
but you can solve the "db queue > 50" by disabling pokestop and/or gym detection in config.ini  
you can also increase your db threads instead via command line (I think), but I don't know how to, thats why I settled with disabling pokestop/gym detection
