### ISSUE TITLE
Notes for spawnpoints?

### ISSUE THREAD

**Issue by ultimate2106** [mchristopher/PokemonGo-DesktopMap#1267]
So I often want to make some notes about Spawnpoint X. I.e. "Lapras spawned on Tuesday at hour 3pm" so I can check the Spawnpoint when I forgot the day or time and it's not needed to create an extra Textfile just for that^^ Would be cool!

**Comment by simonbuehler** [comment]
click on stats, full stats, clickon the wanted pokemon and get a heatmap and the appearance times

**Comment by ultimate2106** [comment]
Well thanks but I know that^^
1st: I don't want to search in the Stats for the pokemon that appeared there (maybe I already forgot which one it was). Would be faster to remember the spawnpoint and read the note.
2nd: That was just an example for notes :)

**Comment by simonbuehler** [comment]
if you scan on different pc's, i guess thats not doable if not without a shared database?

**Comment by ultimate2106** [comment]
Well that's the point. I see Pokemon X on my sisters PC and want to make a note with spawntime on my PC.

**Comment by ultimate2106** [comment]
Also "Full Stats" doesn't show all found pokemon. Yesterday I scanned and found a vaporeon but it's not listed anymore..

**Comment by Burbankian** [comment]
@ultimate2106 have you fiddled with options?  
try changing duration to "map lifetime"  
duration is default at "last day"
