### ISSUE TITLE
Help? Colors.

### ISSUE THREAD

**Issue by lmnottingham** [mchristopher/PokemonGo-DesktopMap#1269]
Maybe I'm late to the party, but can you possibly give me a key for the colors of the spawn points? 
Thanks
Lindsay

**Comment by tedtim** [comment]
Grey/Gray: No pokemon
Blue: Pokemon spawning soon
Green: pokemon has spawned
Yellow: 1/2 through the 15min spawn
Red: pokemon will de-spawn soon
