### ISSUE TITLE
Unable to close app

### ISSUE THREAD

**Issue by kairedfern** [mchristopher/PokemonGo-DesktopMap#1271]
I'm using this on a mac, and even trying to force quit the app simply won't quit. I've even tried deleting files and it says it is still running. Quite concerning...

**Comment by chucklesak** [comment]
What OS are you running? Have you restarted the computer?

**Comment by kairedfern** [comment]
Running Yosemite, and I have restarted it for other issues and it snuck back in without me opening it. I'm going to restart again, but it's a pain given it's an old laptop.

**Comment by davidmorr** [comment]
When you shut it down, did you have it set to reopen all the windows after restart? Untick the box in the shutdown dialogue and it should not start up again.
