### ISSUE TITLE
How do I breakup with my boyfriend?

### ISSUE THREAD

**Issue by HollyKohai** [mchristopher/PokemonGo-DesktopMap#1272]
I tried deleting his Pokemon Go account but he just doesn't get the message.

**Comment by ultimate2106** [comment]
The fuck?

**Comment by chucklesak** [comment]
sounds like your BF needs a new GF.

**Comment by HollyKohai** [comment]
agreed.

**Comment by chucklesak** [comment]
Now I'm in suspense. Did you break up?

**Comment by HollyKohai** [comment]
@chucklesak Apparently removing every pokemon with 1000+ cp isn't enough for him to just give up

**Comment by Sedare** [comment]
And posting on this message board is only going to make it worse for your goal. Try cosmo.
