### ISSUE TITLE
Pokemon Times in "Full Stats" are the disappearing time

### ISSUE THREAD

**Issue by ultimate2106** [mchristopher/PokemonGo-DesktopMap#1273]
So the times I see when I open full stats, click on a pokemon and hover over a spawnpoint are the times when it is disappearing. Kinda confusing me sometimes when I forget^^

**Comment by tedtim** [comment]
technically, the disappearing time is the last time you saw the Pokemon.  Would be wrong if the stats said "Spawn Time"
