### ISSUE TITLE
MAC - need fresh start

### ISSUE THREAD

**Issue by chucklesak** [mchristopher/PokemonGo-DesktopMap#1275]
I have been having some issues with the MAC app and I have been trying to do a fresh start, but for whatever reason when I try to do a delete and a re-install, it retains all of the old information and changes. I have not been able to do a complete fresh start as if it was never installed. Anyone have any suggestions on how to clear this up?

**Comment by steeltown84** [comment]
Delete this folder
_harddrive_>Users>_username_>Library>Application Support>pokemon-go-map
That should clear out any old data.

**Comment by chucklesak** [comment]
it did and I was able to reload it, but I keep receiving the following error when I enable mobile and open it up on my phone:
![screen shot 2016-09-29 at 7 40 48 pm](https://cloud.githubusercontent.com/assets/22513625/19004710/b631529e-871c-11e6-9cf5-fbcde2de1bf8.png)
![screen shot 2016-09-30 at 2 46 25 pm](https://cloud.githubusercontent.com/assets/22513625/19004711/b6388a6e-871c-11e6-81c0-6972830cc8ae.png)
