### ISSUE TITLE
outage/operational with 130acc r33

### ISSUE THREAD

**Issue by tntckoo** [mchristopher/PokemonGo-DesktopMap#1276]
Hello, i am impressed by this holly app, thanks you mike! Into my problem, i using 130account with radius 33 in one instance. Yes, is huge area, but it work good. But sometimes i find pokemon too late to catch, is like 10% chance. I think is because fast moving scanning. So, if exist some "smart" option like one scaning account can scan only in small area like r4 and make togather big area in my case r33 i think it will help to eliminate outage error/no scans problems. Thanks!

**Comment by garyoakalarm** [comment]
Are you noticing that a lot of your workers are reporting back 0 pokemon, 0 stops, 0 gyms? Some of them could have been soft banned as you're using an incredible amount of accounts :O

**Comment by tntckoo** [comment]
actualy i getting soft ban message after 3-4 hours, restart application help for another 3-4 hours...
