### ISSUE TITLE
reinstall windows - no pokemon showing ?

### ISSUE THREAD

**Issue by jijetelu** [mchristopher/PokemonGo-DesktopMap#1277]
I just reinstalled windows 10 and now no pokemons are showing ? Scaner is working, even notifications are working, just no pokemons are visable on map. Any idea why ?

**Comment by jijetelu** [comment]
anyone ? is't quite annoying ?

**Comment by jasonasey** [comment]
Check that your computer time is correct, This can cause no pokemon to show up
