### ISSUE TITLE
Softban when mobile joins back onto the wifi network

### ISSUE THREAD

**Issue by garyoakalarm** [mchristopher/PokemonGo-DesktopMap#1279]
hey ya'll, so I had 60 accounts working smoothly when i went out hunting (more than 5 hours), then everything went to crap as I got home and connected back onto the wifi network with my game. Scanner died and nothing was scanning. All I had to do was reset my router but is anyone else experiencing this issue?

**Comment by toddstar** [comment]
likely an ip ban from Niantic

**Comment by garyoakalarm** [comment]
yea it's weird i was able to smoothly scan with 60 accounts then come home log into my real game and get everything soft banned lol.

**Comment by tntckoo** [comment]
i got this problem like you gary, start one week earlier. I think niantic change something on theyr "bot disabling" politics.
