### ISSUE TITLE
grunt: not found on raspberry pi 2

### ISSUE THREAD

**Issue by HoshiYamazaki** [mchristopher/PokemonGo-DesktopMap#1280]
npm WARN deprecated lodash.assign@4.2.0: This package is deprecated. Use Object.assign.

> pogomap@0.1.0 postinstall /home/pi/Compilations/PokemonGo-Map-3.2.0
> grunt build

sh: 1: grunt: not found

npm ERR! Linux 4.4.13-v7+
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v6.7.0
npm ERR! npm  v3.10.3
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! pogomap@0.1.0 postinstall: `grunt build`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the pogomap@0.1.0 postinstall script 'grunt build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the pogomap package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     grunt build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs pogomap
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls pogomap
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/pi/Compilations/PokemonGo-Map-3.2.0/npm-debug.log

**Comment by imadummy1** [comment]
so whats the problem? go find it? or do you need a scanner for that too?
