### ISSUE TITLE
Can not click run server button

### ISSUE THREAD

**Issue by daodinhlong** [mchristopher/PokemonGo-DesktopMap#1281]
When ran the last release package, It is successful, but I can not click run server button and login button

Help me!

**Comment by krohne** [comment]
wget https://bootstrap.pypa.io/ez_setup.py -O - | python
-or-
curl https://bootstrap.pypa.io/ez_setup.py | python

http://stackoverflow.com/questions/7446187/no-module-named-pkg-resources
