### ISSUE TITLE
Pokemon aren't showing up

### ISSUE THREAD

**Issue by seamusbrennan** [mchristopher/PokemonGo-DesktopMap#1282]
Pokemon aren't popping up, the map looks to be scanning however because the scanned location circles are appearing.  I'm using a mac.

**Comment by Slowacki** [comment]
That is because Pokemon GO now randomly serves captcha, which kills the scanning.

**Comment by seamusbrennan** [comment]
So will the map be down permanently now?

**Comment by Slowacki** [comment]
Seeing that it's a bit of a dead project (no commits in last month) I'm afraid so. We'll see how Fast pokemap goes around this issue (if it manages to) and maybe someone will be able to implement it here as well.

**Comment by seamusbrennan** [comment]
I got it to work just now by logging into the account i made for searching and completed the captcha.

**Comment by Slowacki** [comment]
That's what I do as well, but the checks are returning every 15 minutes ish.

**Comment by davidmorr** [comment]
Hmm, I logged in on my iPad and all I get is "Pokemon Go" at the top and the rest of the screen is a big empty white box with music playing.

**Comment by blehblahblu** [comment]
Using a gmail account instead of PTC fixed this for me.

**Comment by cooler67** [comment]
I tried a google account and that doesn't do anything. The gyms are not even updating.

**Comment by tashinasydney** [comment]
Cooler, did you log into the game normally and catch a starter pokemon? You have to do that before the account will work with the map.

**Comment by cooler67** [comment]
Isn't that risky doing it on the same device you play the game on, with your main account ?

**Comment by cooler67** [comment]
I tried your suggestion and it works. Thanks! Pretty easy work around.

**Comment by tashinasydney** [comment]
I usually use a different device to do the "catch the starter" thing. I don't think it's a huge risk, but it's all degrees of risk and I have an iPad that I never use with my real account, so it's easy enough for me to avoid using my phone.

**Comment by cooler67** [comment]
Curios.. Why is this still working and other websites, like pokevision are not ? They scan to large of an area, or too many requests are coming from them ?

**Comment by EternisRequiem** [comment]
Suddenly just happened to all my accounts I had scanning...

**Comment by cooler67** [comment]
It was working, then it stopped working again. Losing incentive to play the game now.

**Comment by ManiacDC** [comment]
Can confirm using a google account does not fix the issue, it'll still ask for the captcha after a certain amount of time. It just happened to work for a while because it was a new account.
