### ISSUE TITLE
New map software to try

### ISSUE THREAD

**Issue by joe0093** [mchristopher/PokemonGo-DesktopMap#1283]
https://pokemon-radar.net/

Since this project seems dead(not blaming anyone though this game is dead too)... This new map seems to have a lot more features and i think it uploads your personal scans to a public server which is nice. also notifications can run through twitter i think. 

For those who didnt figure out yet niantic just updated their servers today (oct 5) to **sometimes** put a reCAPTCHA on server requests so thats why maps are unstable right now.

**Comment by hbalagtas** [comment]
I think players wouldn't be resorting to running apps and sites that does the tracking if the games actual tracker actually works. Discovering this project actually revive my enthusiasm for the game even though my SO lost complete interest, however they are waging a war against their actual players while botters and gps spoofers run rampant.

**Comment by chansters** [comment]
Too bad the self-hosted version is Windows only.
