### ISSUE TITLE
Python keeps crashing every 10 - 15 minutes

### ISSUE THREAD

**Issue by chansters** [mchristopher/PokemonGo-DesktopMap#1284]
I have updated Python on my Mac to 2.7.12 and ensured the latest version has precedence in my path but this app still uses 2.7.5 for some reason.  

This is the crash report.

> Process:         Python [4476]
> Path:            /System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python
> Identifier:      Python
> Version:         2.7.5 (2.7.5)
> Code Type:       X86-64 (Native)
> Parent Process:  pokemon-go-map [4417]
> Responsible:     pokemon-go-map [4417]
> User ID:         501
> Date/Time:       2016-10-05 21:20:23.006 -0700
> OS Version:      Mac OS X 10.9.5 (13F1911)
> Report Version:  11

In Terminal 

> Mac-mini:~ chris$ python --version
> Python 2.7.12

 **Any idea how to get the app to use 2.7.12 instead ?**

**Comment by davidmorr** [comment]
Which version of OS X are you using? Python crashed regularly one until I realised I needed Yosemite or later. I was using Mavericks. Upgrading fixed it.

**Comment by chansters** [comment]
Thanks David. Yes, I'm using Mavericks on my mac mini which is the machine that I want to run this on. It's an older mac mini, so I don't want to upgrade it past Mavericks (performance).  I decided to install the main version of the Pokemon Go Map app (the command line version) and it's been working great.  It's definitely not as easy to install as this version but it has not crashed Python yet.
