### ISSUE TITLE
add anti-captcha service?

### ISSUE THREAD

**Issue by pokeboo1** [mchristopher/PokemonGo-DesktopMap#1285]
Hello if ladt problem lock after capcha maybe add service anticapcha? 
i'm used for other projects https://anti-captcha.com/ they have api

**Comment by katfude** [comment]
anti-captcha requires money, which means lots of costs to the dev, which means he's a rich philanthropist or needs to collect a subscription cost, which means he is now a business, which means he can now be sued.

Bad idea. Some way to forward the captcha to the user in app would be best.

**Comment by pokeboo1** [comment]
Yes anti-captcha requires money, but lol, why should the developer pay for the captcha? Each user himself will drive its data API s and pay their captcha. only need to add the ability to program. The idea of a more than good. I like easier to pay $ 1 per 1000 captchas than entering them manually

**Comment by tedtim** [comment]
How long do you think 1000 captchas will last? Not cost effective if you run more than 10 accounts.

**Comment by pokeboo1** [comment]
and why do you need so many accounts? I have enough 3 account
p.s. developer can make both variants of manual or automatic captcha entry. I do not see this as a problem, if there is a desire from the developer.
p.p.s. but if you use more than 10 accounts you will not catch pokemons, and just sit and enter a CAPTCHA)))

**Comment by tedtim** [comment]
well, let us know when you figure it out. It should be no problem for someone who has used the service and API before in other projects.
p.s. -  no one is using their scanning account to catch Pokemon, that would be stupid.
