### ISSUE TITLE
Can we change how it scans?

### ISSUE THREAD

**Issue by Goof-Troop** [mchristopher/PokemonGo-DesktopMap#1290]
Like to scan the spawn points, or change it to prioritise currently active spawn points?

**Comment by Nonkel** [comment]
We have bigger fish to fry...first priority is how to circumvent the captcha

**Comment by Goof-Troop** [comment]
I dont get why this recaptcha thing is such a big deal, then again u guys probably do alot more than just use the map :D lol. idk, i've just stumbled across this map a couple days ago

**Comment by pehmolelu** [comment]
How do you manually pass CAPTCHA ? Goof-Troop, it already suppor that active spawn point scanning. Add --spawnpoints-only parameter in main.js file on row around 210 inside var cmdLine = [ array.

**Comment by Goof-Troop** [comment]
look man even that sounds complex for me hahaha but ill look about the map thing and see if i can work that out lol. Manually pass it? by tapping on the pictures with a sign post, sorry if you mean something different lol
