### ISSUE TITLE
Maps doesn't load due to javascript

### ISSUE THREAD

**Issue by victorids** [mchristopher/PokemonGo-DesktopMap#1292]
Oops! Something went wrong.
This page didn't load Google Maps correctly. See the JavaScript console for technical details.

First time trying to use this application. Map doesn't load.

**Comment by xxxGRISBYxxx** [comment]
I am having the same problem. It has been reported as an issue here several times, but no one has helped. Hopefully someone does know how to fix the issue and will share that information.

**Comment by luckytom333** [comment]
Getting the same error:

This page didn't load Google Maps correctly. See the JavaScript console for technical details.

**Comment by luckytom333** [comment]
Fixed it... regenerate a new API key.
