### ISSUE TITLE
PokemonGo and all other scanners are offline due to Niantic server changes for now!

### ISSUE THREAD

**Issue by torantal** [mchristopher/PokemonGo-DesktopMap#1295]
No need for further discussion here at the moment.

**Comment by 0logic0** [comment]
wellll, I disagree. Let's talk about how crappy this is and how worthless Pokemon Go is without it. A healthy complaint never hurt. My life is over #killme-ow, #NianticSquirt-ledAllOverThisGame, #TheyShouldBeExe-ggutored, #MyFootAndTheirButt-erfree, #ERaticateNiantic, #Fear-owMe, #GloomLife, #SorryIWastedYouTimeImaGoSmokeSomeWeed-le #Koffing #Weezing, #JKGTFOverIt

**Comment by torantal** [comment]
Better take that to https://www.reddit.com/r/pokemongodev/ ...

**Comment by 0logic0** [comment]
Haha, I read my post again and my bad. that looked a little too much like some of the posts I've seen here. I was going to put an edit in that I was joking, but you're too quick .  unless you know I was joking and that's where people go to complain.

**Comment by torantal** [comment]
Just thought a catchy topic title might keep people without any knowledge of the underlying problem from spamming this further.

**Comment by taylormeyer** [comment]
Any idea if/when a workaround might be put in place for an update @torantal

**Comment by torantal** [comment]
Check the reddit link above for current developments. It might be days, weeks or never because so many people have turned their back to the game that devs are not motivated enough. Also nothing that can be done couldn't be rendered unusable again with the next update.

**Comment by Nonkel** [comment]
Isn't it also awfully quit on behalf of mchristopher? Not a single tweet about this program or work on a possible solution. Looks like he has turned his back on this. The developer of Fastpokemap.se is still working on a solution. But I like this program way better. Would be a shame if nobody would try to fix this....

**Comment by torantal** [comment]
This program is "only" a gui wrapper für the pokemongo map tool, so there's no solution with regards to the current challenges that could be solved within the PokemonGo-DesktopMap context. 

So if they come up with a solution he and the other devs here can then update the wrapper to hand it to us on a silver plate again. It was always possible to run the PokemonGo tool yourself inkl. remote access and maps, but it was made so much easier with this project.  At the moment  the foundation is lacking so it does not make sense to work on anything DesktopMap related.

**Comment by mchristopher** [comment]
Version 0.4.1 contains the newest release and should be fully working.
