### ISSUE TITLE
spawn points still working from prev scans

### ISSUE THREAD

**Issue by eloknu** [mchristopher/PokemonGo-DesktopMap#1296]
so i finally logged on the map and stopped the scanning just so i could view the points which i noitced still change colors.. ive always been alittle confused on what the colors ment if someone could explain that to me as well as the spawn timers. example one says every hour from 3:25 to 18:25 or 50:01 to 05:01 what exactly does that mean

**Comment by wasisdn** [comment]
timers give you the timetable already like your samples, spawn point become active every houer from 3 minute and 25 second to 18 minute 25 second or 50 minute and 1 second to  next hour 5 minute 1 second. every spawn point will be active for 15 minutes.
green means active, when time running it change colour to yellow. orange-red means nearly time out. grey is inactive and blue close to become active.

**Comment by eloknu** [comment]
Thank you that makes reading it so much easier. I found the cache folder on my pc. Any recommend programs to get to actually be able to read those files? I run Windows 10

**Comment by willydk** [comment]
I believe there was another migration, most of the spawns are all different timers
