### ISSUE TITLE
Secret Key leaked? Maybe update soon? :)

### ISSUE THREAD

**Issue by ultimate2106** [mchristopher/PokemonGo-DesktopMap#1298]
So I have heard that the secret key to get pokemon data has been leaked. So maybe there will be an update soon? o:

**Comment by Condedukee** [comment]
I hope they will do

**Comment by johnnylingo** [comment]
pokesear.ch seems to have a working version.  I'd love to go back to the days where I ran the scan around my house and ran out to chase down rare pokemon in my area.  Sure, GPS spoofing is fun in it's own right, but not nearly as much fun as physically running to catch something rare.

**Comment by mchristopher** [comment]
Version 0.4.1 contains the newest release and should be fully working.
