### ISSUE TITLE
Any Efforts to Get This Back Up?

### ISSUE THREAD

**Issue by seamusbrennan** [mchristopher/PokemonGo-DesktopMap#1299]
Just wondering if anyone is doing anything to get this back up and running, I prefer this map to fastpokemap so I'm hoping it'll be back up eventually.

**Comment by Nonkel** [comment]
This map version is way better. Fastpokemap is ok if you are out there and want to hunt down a Pokemon in your nnearby list. But with winter coming, I only want to go out when i hear the notification 'ding' of the PokemonGo DesktopMap. But its awfully quiet here lately...

Please, anyone that has some knowledge on how to get this map back up, help out!

**Comment by Brisingrox** [comment]
I have the leaked files but not the know how to make it fonctional. Need someone who can explain zo me how to make the Hashserver emulation eith unicorn, how to rip of that binary from a IPA...

**Comment by Mharper554** [comment]
There hasn't been an update in 2 months. We all know the API is leaked. Come on man get it up!

**Comment by musicgreg** [comment]
The leaked files will probably not help you.  Soon after they were leaked Niantic patched to block the workaround in those files.  Waryas has come up with another workaround, but it is unlikely he will share it, but don't be mad at him.  If he shares it Niantic will block it, or people will use it to get bots running.  I really love this app, and I think it serves a little bit different purpose that fastpokemap, but someone will have to figure out the same loophole, or a different one, and then not share that either.

**Comment by Brisingrox** [comment]
I think you could be right with your guess. Bit i am also sir that it is possible to make it run with the leaked files. Many of discord i'm in #re have it slowly bit surely running. Pokemesh,pokealert... juste to name a few. An you are fals on one exeption they are already fonctional bots online. For ex, pokefarmer are up since 2 days. So i would really put some efforts into it for making that work. And i still also don't gave up. Even when it gone cost me some time. I will make my map running.

**Comment by Brisingrox** [comment]
The methode how waryas and elfinlazz have found the whole is still open. I read every channel i can to puzzel the solution together

**Comment by Brisingrox** [comment]
But two things a certain. 1) with the next update on horizon everthing could be gone and back to square one. 2) there will always be people who will overcome the tightest security. And find holes in the wall to explore even if it takes e while. At the  end it took the pogodev team a few weeks to find a workaround after the last great api change. So it is still hope that one day our map could go back online

**Comment by musicgreg** [comment]
FPM is dead, they say for good, but they released all the code.  Niantic patched and it stopped working and their 3 months of work is all gone :(

**Comment by nikola987** [comment]
All is not gone, since local scanners (like this one) are working just fine on android.

**Comment by centilian9** [comment]
Witch one is still working? Can you point me to a right direction?

**Comment by nikola987** [comment]
Pokemesh for example still works.

**Comment by Mharper554** [comment]
Any for IOS?

**Comment by mchristopher** [comment]
Version 0.4.1 contains the newest release and should be fully working.
