### ISSUE TITLE
Zombie Processes & Memory Leaks

### ISSUE THREAD

**Issue by bryanhelmig** [mchristopher/PokemonGo-DesktopMap#13]
If you close the app - the Python thread continues to run in the background. Definitely an issue with the packaging. Process manager will show this. (OS X specifically).

Also, a leak means it will eventually eat up gigabytes of data. That could be the underlying PoGo API library's fault.

**Comment by ilikesomething** [comment]
Possible duplicate of #6

**Comment by xan0v** [comment]
Can confirm this on Windows as well - Python process isn't killed and continues to run.

**Comment by Ruined1** [comment]
Same windows 10 x64 bit. This needs fixed ASAP and should be marked important.

**Comment by mchristopher** [comment]
Yeah, this has been fixed in 0.0.3. I'm going to close it for now. Please open a new issue if the problem still exists.

**Comment by bryanhelmig** [comment]
Confirmed no more Zombies. :-)
