### ISSUE TITLE
[Suggestion] Make a version for VPS to have it always with you

### ISSUE THREAD

**Issue by Micrim** [mchristopher/PokemonGo-DesktopMap#130]
Hello guys, first thanks for your program it's awesome. 
i came up with this idea, if it would be possible to add this kind of program to a VPS with a link to access by mobile to have it aviable everytime even when pc is far away (to change locations and all) and with tracking from device GPS

Hope this is possible, as i'm not a programmer i don't know if it will be possible

Cya

**Comment by kolyasik86** [comment]
great idea, I support Micrim!

I believe that we are not alone is used!

Thanks guys!

**Comment by andrewda** [comment]
Take a look at the base for this repo: https://github.com/AHAAAAAAA/PokemonGo-Map

**Comment by r3dlin3r** [comment]
@Micrim use Chrome Remote desktop in the meantime ;-)

https://chrome.google.com/webstore/detail/chrome-remote-desktop/gbchcmhmhahfdphkhkmpfmihenigjmpp?

**Comment by mchristopher** [comment]
The purpose of this app is to run on a desktop, not on a server. If you're looking for a server-based solution, follow the link from @andrewda above.
