### ISSUE TITLE
The 0.4.1 stay in 0.4.0 on mac version

### ISSUE THREAD

**Issue by paco57** [mchristopher/PokemonGo-DesktopMap#1300]
Hi, I installed the last version on Mac OSx Sierra 0.4.1 but after installation it still mention 0.4.0 ...
and the download button for the update doesn't work, see screenshot.

![image](https://cloud.githubusercontent.com/assets/6207237/20042305/c5a66728-a477-11e6-8304-75809b46cce0.png)

**Comment by seamusbrennan** [comment]
Same thing happens to me, but the tracker works so I don't really mind

**Comment by eamethan** [comment]
I'm getting the same message, it shows that it's scanning, but not showing any Pokemon found.

**Comment by ilya668111** [comment]
yes, same on mac os

**Comment by RebelPrinceTrys** [comment]
Me too. Keeps saying it wants to download a "helper tool," but then the program closes and nothing happens. :(

**Comment by Mharper554** [comment]
Me as well

**Comment by germitgirl** [comment]
same here

**Comment by memosoto** [comment]
same here

**Comment by Calvinthesneak** [comment]
I think 4.1 was just an update to the windows installer.  4.0 and 4.1 should be more or less the same thing for purposes of MAC.

For your ptc accounts have you logged into them, accepted Terms of Service and caught your starter pokemon on each account?

**Comment by ibruno** [comment]
Yes... same account only works in Windows version, on Mac no :(

**Comment by RebelPrinceTrys** [comment]
Yes, the account has worked for me just fine before. But not this update...
