### ISSUE TITLE
Captcha Still an issue

### ISSUE THREAD

**Issue by jasonasey** [mchristopher/PokemonGo-DesktopMap#1303]
Will you be able to push the Captcha to the program r so we can make this more usable?
 Most of the time the scanner is blank.

**Comment by garyoakalarm** [comment]
would love to have this pushed to the user somehow for those that use the pokelarm extension :). or just bypass it altogether lol

**Comment by minim8** [comment]
using pokealert to do the captchas atm. not elegant but better than doing it completely manually on the phone. Hope they will get pushed to the user soon though
