### ISSUE TITLE
won't install on Win10

### ISSUE THREAD

**Issue by johnnylingo** [mchristopher/PokemonGo-DesktopMap#1304]
I can't get 0.4.0 or 0.4.1 to install on win10, admin account, run as admin.

**Comment by Calvinthesneak** [comment]
What sort of error are you getting?  You provided no useful information other than your OS to help you.  Does it run and just stop? Do you get an error message?

**Comment by johnnylingo** [comment]
I just get the little whirly for a second or two and then nothing.  I wish there was an error, at least that would be something.

**Comment by Calvinthesneak** [comment]
Do you mean the pikachu rubbing his cheeks?

**Comment by johnnylingo** [comment]
Nope.  That would be the splash screen.  At least that would be something.  I mean my cursor changes to the "waiting" cursor for a second, and then.... Nothing.

**Comment by johnnylingo** [comment]
So the issue is due to some asinine security 'features' of Win10 that prevent certain programs from running under the default administrator account.  It runs fine under a user account.
