### ISSUE TITLE
Can't add multiple PTC accounts directly

### ISSUE THREAD

**Issue by Squamoto** [mchristopher/PokemonGo-DesktopMap#1306]
If I want to add more than one PTC account, I get this error:

Oops, something went wrong and we couldn't log you in. Please try again. Unable to get login session from Pokemon SSO.

If I start the server and go back to the starting settings page or close the window and reopen it, it works fine again for a single account.

**Comment by Zikaba** [comment]
Add, then CTRL + R, and add again, etc etc.
