### ISSUE TITLE
No pokemon showing up?

### ISSUE THREAD

**Issue by krisdunn5** [mchristopher/PokemonGo-DesktopMap#1307]
I created a new api key, it says operational at the top, yet no pokemon are showing up...

what can I do?

someone on reddit said to run "pip install -r requirements.txt --upgrade" but I have no idea what that means..

**Comment by himeshpatel88** [comment]
+1

**Comment by loiacj** [comment]
+1

**Comment by krisdunn5** [comment]
@himeshpatel88 @HollyKohai I was able to fix the problem by simply using an IOS device and logging into the accounts. 
This message popped up: http://static1.i4u.com/sites/default/files/imagecache/main_image_large/images/2016/10/niantic-recaptcha.jpg
and all I had to do was solve the captcha and since then my scanner is working again! 

not sure how often these captchas will pop up, but I've been scanning for 2 hours now and it still works
