### ISSUE TITLE
Cant login 

### ISSUE THREAD

**Issue by ericcireeric** [mchristopher/PokemonGo-DesktopMap#131]
Hello ! I have a question, when I click on login with google or PTC, a message appears "invalid pokemon ids. only numbers and commas allowed",
I used the app yesterday, and it was working fine :(  

 what can I do ??

**Comment by IMNoob1** [comment]
first of all there is an update.
if you didnt install it go a head and do it.
test it and replay.

**Comment by mchristopher** [comment]
Try the latest version.
