### ISSUE TITLE
not all pokemon are scanning

### ISSUE THREAD

**Issue by eloknu** [mchristopher/PokemonGo-DesktopMap#1310]
so i added 2 accts but im not sure how that actually works. do they both scan under the same marker at the same time? anyway regardless of that ive been comparing the scans to pokesear.ch and even the fact that i know in my area when pokemon should be up and its not catching them all.. also how are captchas handled

**Comment by nikola987** [comment]
This happens to me also. I thought that I have been captchad but, I tested all my accounts (I use 8) and they are all OK :s

**Comment by Borys74** [comment]
I have the same problem. The program does not detect all Pokémons that shows in the SIGHTINGS, in the game.

**Comment by nikola987** [comment]
Ok I have a theory.
Niantic said that they doubled the number of pokemon (and items from pokestops) for this new promotion which lasts the next 7 days.
What if the new pokemons are spawn the same way that pokemon appear from lure module.
That would I think explain why the scanner refuses to see all pokemons.

**Comment by harrison0550** [comment]
It doesn't appear to be pulling in all the updated spawn points. I now have 4 spawn points at my house and its not showing any of them on the scanner. I am grateful it is back up and running though. May just need a few tweaks.

**Comment by Calvinthesneak** [comment]
I'm finding on second pass of scanner I tend to pick up a lot more spawns.  Not sure if it's all of them though.

**Comment by luckytom333** [comment]
It's most likely due to the new speed mechanism Niantic put into the game.  The accounts are scanning too quickly which results in them not seeing any pokemon.  How do you modify the scan delay to slow it down?
