### ISSUE TITLE
Enabling IV and Gym information

### ISSUE THREAD

**Issue by Calvinthesneak** [mchristopher/PokemonGo-DesktopMap#1314]
Because people don't read the wiki.....  You can turn on IV's and gym information on this map by editing a config.ini file.

https://github.com/mchristopher/PokemonGo-DesktopMap/wiki/Config.INI

**Comment by minim8** [comment]
where is the config file located on mac? could neither find it in application support nor in the package contents. (only the config.ini.example file and editing this one doesnt change anything)

sorry i have no clue about macs :/

**Comment by elvquant** [comment]
On OS X inside the Apps Resources folder. Right click on app and choose "open containing folder", then "Resources/app/map/config"

**Comment by Calvinthesneak** [comment]
> (only the config.ini.example file and editing this one doesnt change anything)

There is no config.ini by default.  You have to make a copy of the config.ini.example, and save it as config.ini.  Then uncomment(by removing the # at the start of the line) the following lines and set them to true:

`gym-info: true             # enables detailed gym info collection (default false)`

`encounter: true             # Set to true to start encounters to pull more info, like IVs or movesets. (default false)`

PS, if someone can edit the wiki page to add OSX and Linux paths, it would be appreciated.

**Comment by AdroitAesthete** [comment]
Mornin' Calvin-

I did exactly as you instructed (on Windows 10), and now the app no longer fully opens, for some reason. I'm stuck at the "Loading, please wait..." screen, and am completely stumped as to why. 

The only two lines that I have uncommented are the two above, and I saved the updated config file as you instructed as well.

It was working this morning just prior to the edits. Any idea why my app is stalling? 
Any help would be much appreciated!

Attached, for the sake of clarity:
![pogo1](https://cloud.githubusercontent.com/assets/23361444/20144614/d14f98e6-a662-11e6-87ee-680b2147dd0f.PNG)
![pogo2](https://cloud.githubusercontent.com/assets/23361444/20144615/d150aaba-a662-11e6-96f7-1235538222ce.PNG)
![pogo3](https://cloud.githubusercontent.com/assets/23361444/20144616/d1510bae-a662-11e6-814b-27a29b24abd5.PNG)

**Comment by hennipenn** [comment]
> There is no config.ini by default. You have to make a copy of the config.ini.example, and save it as config.ini. Then uncomment(by removing the # at the start of the line) the following lines and set them to true:

gym-info: true # enables detailed gym info collection (default false)

encounter: true # Set to true to start encounters to pull more info, like IVs or movesets. (default false)

I did everything as you described but nothing changes. The app works the same way as before editing. I also tried on Windows 10. Can anybody help? 

With windows 7 everything works fine :)

**Comment by CTsouth86** [comment]
I'm fairly new to programming and would like to give this a try as well if it will work on Windows 10.

If I understand correctly, I can also reduce the scan-delay time of the tracker from the default 10?

**Comment by Calvinthesneak** [comment]
I'm using it on both windows 7 and windows 10.  

Are you using Notepad++ or just the default windows notepad?  

I recommended notepad++ because it will keep line breaks and characters consistent.  I'll attach a copy of what I'm currently using.
[config.zip](https://github.com/mchristopher/PokemonGo-DesktopMap/files/581735/config.zip)

**Comment by Calvinthesneak** [comment]
Also make sure to restart the app after you modify config file, it has to load it at startup.

**Comment by koki871** [comment]
Using Mac OS 10.11.6. Duplicated the .example file and renamed to "config.ini," but after launching the application, the contents of the folder is reverted to the original setting - i.e. I only see .example file in the config folder.

**Comment by Calvinthesneak** [comment]
Just a sample of gym and IV/moveset info.

![iv gym](https://cloud.githubusercontent.com/assets/23301696/20161016/98e88c72-a6a0-11e6-82ac-2ed5b8959073.jpg)

**Comment by Calvinthesneak** [comment]
One thing to check, that I saw on the PoGo Dev thread where I posted this, was make sure you're not running the installer/updater exe, it will reinstall and erase your config.ini file.  

> I tried to use the config file, but for some reason it gets deleted every time I launch the app? Any ideas what's happening?
> EDIT: Nevermind. If I run the packaged exe, it replaces all the files on every run. Instead, if I just run the exe in the appdata folder, the config file is fine.

**Comment by minim8** [comment]
@Calvinthesneak Thanks, I'm an idiot I didnt think about renaming it to config.ini instead of config.ini.example ... Works fine now, but wouldnt it be better to only use the whitelist for some specific pokemon instead of encoutering all of them? Or doesnt Niantic care about the number of requests sent?

**Comment by rqwedx1** [comment]
can smn tell me how to fix this, it wont recognize the accs

 # Authentication settings
auth-service: ptc          # ptc (default) or google
username: [acc1, acc2]
password: [p1, p2]

**Comment by Calvinthesneak** [comment]
You don't need to fill accs in if they're on the login screen

---- rqwedx1 wrote ----

can smn tell me how to fix this, it wont recognize the accs

Authentication settings

auth-service: ptc # ptc (default) or google
username: [acc1, acc2]
password: [p1, p2]

##

**Comment by rqwedx1** [comment]
but i do want to add them this way cuz its way faster then clicking through the login screen for 50+accs

**Comment by Calvinthesneak** [comment]
Not sure if this allows accounts only in the config file, but one way to find out.  You're using Notepad++ and note just regular notepad or some other text editing tool that's going to stick innapropriate line control characters in?  Make sure you have space at start and end of your square brackets.  Other than that I'm not sure, you might need to go to the PoGo-Map wiki.

username: [ account1, account 2, account 3 ]
password: [ password, password, password ]

**Comment by kanucks25** [comment]
Can't seem to figure out how to enable IV (windows 7).

Followed the steps in OP. As far as I can tell, just had to add "true" on the right line. Not sure if it's just for Mac, but I also tried copying the file and taking out the ".example" and that didn't work either.

Help please :)

**Comment by Calvinthesneak** [comment]
What did you use to uncomment lines in your .ini file?

Did you try downloading the config file I attached as a zip in the post above?

https://github.com/mchristopher/PokemonGo-DesktopMap/files/581735/config.zip

**Comment by kanucks25** [comment]
^ Used it and it works. Thanks! :D

**Comment by rqwedx1** [comment]
nope, doesnt work. missed a space within the bracket but still doesnt work. using n++. but thanks for the effort.

> Not sure if this allows accounts only in the config file, but one way to find out. You're using Notepad++ and note just regular notepad or some other text editing tool that's going to stick innapropriate line control characters in? Make sure you have space at start and end of your square brackets. Other than that I'm not sure, you might need to go to the PoGo-Map wiki.

username: [ account1, account 2, account 3 ]
password: [ password, password, password ]

**Comment by Calvinthesneak** [comment]
might just be the load screen config overwrites the config.ini file.  So options like IV and Gym stats which just were off by default with no gui switch can work, but stuff like accounts, location, Google Maps API key are going to be overwritten....

**Comment by himeshpatel88** [comment]
I followed all these steps, including using your config file and nothing seems to have changed. Help please!!

**Comment by jasonclark-skillstream** [comment]
Did you wait till new mons populated?

It will only show once they have been scanned, anything scanned previously doesn't show the updated fields.

**Comment by himeshpatel88** [comment]
I hovered over the gyms but they look the same, have not waited for new mons to show up yet, I will try that and comment on my findings thanks!

**Comment by himeshpatel88** [comment]
Been about 20mins, nothing has populated, don't know what the problem is...

**Comment by jasonclark-skillstream** [comment]
Is the config file saved as config.ini file and file type showing as configuration settings and not EXAMPLE File

**Comment by himeshpatel88** [comment]
This is what I have:
![config](https://cloud.githubusercontent.com/assets/21130118/20222458/6472109e-a803-11e6-8282-7e1ec3bced2a.PNG)
![configdetails](https://cloud.githubusercontent.com/assets/21130118/20222457/64479792-a803-11e6-874c-04a0a5ff7367.PNG)

**Comment by jasonclark-skillstream** [comment]
Looks okay but try removing it/ or rename then replace with mine.
[config.zip](https://github.com/mchristopher/PokemonGo-DesktopMap/files/586272/config.zip)

**Comment by himeshpatel88** [comment]
I have tried both and had the same results...not sure what the problem is...I replaced your file and will wait on results.

**Comment by himeshpatel88** [comment]
I am not getting any mons scanning at all now, and the gyms have not updated since I replaced the file with your version. HELP!

**Comment by himeshpatel88** [comment]
![capture](https://cloud.githubusercontent.com/assets/21130118/20224655/888e0e6a-a80d-11e6-9f06-71eacacb6187.PNG)

**Comment by jasonclark-skillstream** [comment]
Could you post a screenshot of your config folder again?

**Comment by jasonclark-skillstream** [comment]
I just looked at your notepad ++entry and it looks like you added an extra .ini at the end of the file name. i.e. config.ini.ini

**Comment by himeshpatel88** [comment]
I actually ended up uninstalling the whole program, deleting the rest of the info in the pokemon folder, restarted my laptop, re-installed, replaced config.example with your version and it is all working fine now! Thank you for your help @jaydoginvasion

**Comment by jasonclark-skillstream** [comment]
Awesome, that's great news

**Comment by jayro11** [comment]
im sorry for such a noob question...but im on a mac and i can not find the app resources folder for the life of me.  or can someone post the path on OS X

**Comment by jayro11** [comment]
ok...so i figured it out...i have it working great....except...after a while the pokemon show up without the  IV and moveset info.  Does anybody know why it does that?

**Comment by elvquant** [comment]
> For OSX the example config.ini.example can be found by right-clicking the app file (the same file you use to launch the app) and selecting "Show Contents", then navigating within the contents to resources\app\map\

Works well, but on Quit "Pokémon Desktop Map.app" the config.ini are deleted and all other files are restored. ;( ;(
