### ISSUE TITLE
Regression(?) TOS not accepted.

### ISSUE THREAD

**Issue by Axeia** [mchristopher/PokemonGo-DesktopMap#1319]
Hello,

I'm not sure if this version of the map accepted the TOS automatically for you as PokemonGo-Map used to do for you but atm the Terms of Service are not accepted automatically when adding clients to the application. This leads to 'fresh accounts' not working at all, you just get a bunch of errors in the developer tools -> console.

Logging into the game on the same accounts, accepting the Terms of Service and then starting up the server does work.

**Comment by richnj** [comment]
Does anyone use the same device they play on to accept the TOS to activate the worker accounts?  I used to be able to do this through an emulator but this does not work any longer and I am hesitant to use my phone to register workers.  Any advice or suggestions would be greatly appreciated.

**Comment by harrison0550** [comment]
I got an old android phone I use to catch the first mon with etc. Sucks to have to physically log in etc to each account but fortunately I catch 3-4 mons on each account and they have not had any problems since.

**Comment by Axeia** [comment]
I also use a secondary device to activate the account after they've successfully banned both the Bluestacks and Nox options. If I recall correctly in the early days it was mentioned that the IMEI gets sent along and thus  they could ban your entire device permanently if they wanted to - I would indeed advice you not to use the device you normally play on. 

Either borrow a phone from someone who doesn't play or use an old device you no longer actively use.

**Comment by richnj** [comment]
Thanks for the advice, I will definitely not use my phone to activate the accounts,  I just tried to using an old phone but I could not download the app due to the phone being too outdated I guess.  I may try looking into purchasing a really cheap phone to try to have someone else activate an account for me as I can't wait to get the radar back up and working.

**Comment by hubbalicious** [comment]
You can try sideloading the pokemon app. I have an old phone (galaxy s3) that I use for this purpose and this is what I had to do. I think as long as you're on 4.4 the app will work (although it crashes a lot on this phone).

Alternatively you can try using pokealert on the old phone, which will accept the TOS and catch the starter pokemon for you.

**Comment by richnj** [comment]
Thanks, I will try sideloading before I buy a new phone,  I did borrow a friends phone to activate one worker just to verify the new installation and I am up and running but do need to add some workers now.
thanks all
