### ISSUE TITLE
Database Locked

### ISSUE THREAD

**Issue by himeshpatel88** [mchristopher/PokemonGo-DesktopMap#1320]
I keep getting logs with "Database Locked" messages, how do I fix this? Is this a problem that has occurred because of the latest API update? If so, will it be updated soon? Is there a workaround in the meantime?

**Comment by kezc7** [comment]
Switch to a mysql database, it solves this issue.

**Comment by notesofposit** [comment]
how do you switch to mysql.... i have this issue as well where my database keeps locking up
