### ISSUE TITLE
A javascript error occured in the main process

### ISSUE THREAD

**Issue by renzomaster28** [mchristopher/PokemonGo-DesktopMap#1322]
Alguien sabe cual es el problema o como solucionarlo?
![1](https://cloud.githubusercontent.com/assets/18461255/20219703/5e9bb610-a809-11e6-978b-ff0072338299.jpg)
![2](https://cloud.githubusercontent.com/assets/18461255/20219705/5ebf1844-a809-11e6-9f23-43405cc4b1b1.jpg)
![3](https://cloud.githubusercontent.com/assets/18461255/20219706/5ec7a7c0-a809-11e6-82f7-8804900fac04.jpg)

**Comment by nickgp33** [comment]
same here
<img width="419" alt="screen shot 2016-11-11 at 9 57 56 am" src="https://cloud.githubusercontent.com/assets/23404328/20221620/a2dc251a-a7f7-11e6-8aed-525325b360fc.png">

**Comment by Su9m7** [comment]
same here
