### ISSUE TITLE
NEW FEATURE: Added Pokesniper2 snipe link to map

### ISSUE THREAD

**Issue by luckofthelefty** [mchristopher/PokemonGo-DesktopMap#1323]
Added this line to net45/resources/app/map/static/dist/js/map.min.js
` <a href='pokesniper2://"+a+"/"+f.toFixed(6)+","+g.toFixed(7)+"'>Snipe</a>`
where the code says 
`Location: "+f.toFixed(6)+", "+g.toFixed(7)+`
AND
Added this line to net45/resources/app/map/static/dist/js/map.built.js
`<a href='pokesniper2://"+name+"/"+latitude.toFixed(6)+","+longitude.toFixed(7)+"'>Snipe</a>`
Where the code says
`Location: ' + latitude.toFixed(6) + ', ' + longitude.toFixed(7)  +`

This results in:
![image](https://cloud.githubusercontent.com/assets/15348451/20225769/12934472-a813-11e6-9ec9-54635def2334.png)

here are the edited files. 

[map.min.zip](https://github.com/mchristopher/PokemonGo-DesktopMap/files/586511/map.min.zip)

Just unzip and place the two files in `net45/resources/app/map/static/dist/js/`

EDIT:

Download and following setup instructions for pokesniper2 here:
[http://www.ownedcore.com/forums/pokemon-go/pokemon-go-hacks-cheats/566079-pokesniper2-pokemon-sniper-catch-any-pokemon-no-matter-where-you.html](http://www.ownedcore.com/forums/pokemon-go/pokemon-go-hacks-cheats/566079-pokesniper2-pokemon-sniper-catch-any-pokemon-no-matter-where-you.html)

You need to run the registerurl.bat for this work.

**Comment by Nonkel** [comment]
I would strongly object to incorporating this cheating program.

**Comment by luckofthelefty** [comment]
To each his own, but using the map violates the PokemonGO ToS also.

**Comment by Nonkel** [comment]
This map is a replacement for the poor excuse of a map/tracking in game. If that gets fixed, there will be less need for a map like this.

**Comment by luckofthelefty** [comment]
This map also gives you the options to see IV's, move sets, and what pokemon are currently in GYM's. All of which were never intended to be part of the game. Not trying to argue over it. If someone thinks it should be removed, then they can. I can fork it and put it up elsewhere. I had some friends ask me if this would be possible so I figured I would share it.

**Comment by Brisingrox** [comment]
That is some insane stuff. I get that implemented instantly when i'm home. If you think about removing it send me pm with the fork if you create one. But personaly i think of it as an worthy extension for those who like it. And i think also that there are not much people who gone have use of it because normaly you don't play with the account you scann.

**Comment by nikola987** [comment]
what does sniping do?

**Comment by Brisingrox** [comment]
Google Pokemon go snipping and then you see by yourself.

**Comment by RyusuiJL** [comment]
Curious...can this be done with PokeStops, too?

**Comment by Brisingrox** [comment]
Good question but no relevanze because of the speedcap limit. If you could snip a pokestop and jump to some other in less then a second i think you get captcha or not even spin the pokestop.

Like driving to fast and for sure get flagged by niantic

**Comment by Brisingrox** [comment]
And again there is normaly no use of that because you're normaly not play with the account ypu scan

**Comment by RyusuiJL** [comment]
Very good point.  I hadn't thought about that.

On another note, is the Pokesniper app windows only?  I downloaded the app from the link you posted but it only has an .exe file.

**Comment by luckofthelefty** [comment]
Note this though. Pokesniper2 allows you to configure your play account to use for snipe. All that link does is navigate to a URL "pokesniper2://pokemonname/lat,long"
During the setup of pokesniper2 there is a "registerurl.bat" which register the above url with the pokesniper2 program. You do not have to snipe with the account you scan with. I'd highly recommend not doing that. 
So to recap: 
Config pokesnipe with your play account.
Run "registerurl"
Launch map with search account.
Click snipe

**Comment by Brisingrox** [comment]
Oh i didn't knew that. Sry my fault. That sounds even better then before. But still you have the the distance problem depending on where you're scanning/seeing the pokemon and the place you're actualy are...

**Comment by Brisingrox** [comment]
That what i tought about is to link between scan/notification/snipping integration thing.

@lukeofthelefty can you PM me. Want to ask something about that with you

**Comment by luckofthelefty** [comment]
I haven't had any issues sniping Pokemon from all over the world with this method. As long as you don't open the Pokemon go app anytime while doing it

**Comment by luckofthelefty** [comment]
I've created a fork of the repo, we can continue our discussion over there. Just start up an issue thread over there
