### ISSUE TITLE
Pokemon Show up with 10 seconds left

### ISSUE THREAD

**Issue by BoveMachine** [mchristopher/PokemonGo-DesktopMap#1328]
The pokemon always show up when scanned, however the Disappears at is always at 10 seconds and when it hits zero they disappear off the map. Any ideas?

When the area is rescanned they pop back up again, but will have 10 seconds like before.

**Comment by magicdev2** [comment]
Because of thia new API that pokemon go has and its anti bot and hacking. It makes all the bots hard to see if theres a pokemon and in the last 10 seconds it shows i really dont know how to explain it but Its Cuz of thr new API

**Comment by BoveMachine** [comment]
So if i quickly grab the coordinates, go there, there is a chance it may still be there?

**Comment by BoveMachine** [comment]
They pop up, and say 10 seconds remaining, then they disappear off the map until the same area is scanned again, then same thing.
