### ISSUE TITLE
Stuck at 'Waiting'

### ISSUE THREAD

**Issue by Nonkel** [mchristopher/PokemonGo-DesktopMap#1329]
Program worked flawless for a week or so. But since yesterday evening, scan started to drop off (red circles appearing), and now it's not scanning at all. Says 'Waiting' at top of the screen.

Something changed by Niantic again? More people with this issue? Any ideas?

**Comment by jasonclark-skillstream** [comment]
Probably had your accounts banned, lost mine yesterday too

**Comment by hcjsy** [comment]
me too. updated api needed :(

**Comment by supershannii** [comment]
Having the same issue. Accounts I use are not banned.

**Comment by CavalornIV** [comment]
got the same problem
creating a new PTC didn't fix the problem
