### ISSUE TITLE
Links don't work

### ISSUE THREAD

**Issue by syousef1975** [mchristopher/PokemonGo-DesktopMap#133]
I've gone back to using scripts in 0.0.7 instead of the windows app because I links from the map to pokedex and directions don't work inside the app.

**Comment by mchristopher** [comment]
Try the latest version, it's got an updated interface that may fix this issue.

**Comment by slyfree** [comment]
same in 011 version

**Comment by hotice** [comment]
This continues to occur with the latest version (0.2.1), at least on Linux.
