### ISSUE TITLE
Account Recycler / "Account needs to cool off due to exception"

### ISSUE THREAD

**Issue by secondhandnudes** [mchristopher/PokemonGo-DesktopMap#1330]
From developer log:

2016-11-15 13:24:19,101 [account-recycler][        search][    INFO] Account ********** needs to cool off for 4795 seconds due to exception

I'm starting to get these quite frequently and haven't really seen this discussed on here. Anyone else experiencing / found a way to avoid it? I have set step count to 10 and scan delay to 15 already and it's still happening, so not sure if there are some other settings I need to tweak

**Comment by J6667** [comment]
The account is probably banned.

**Comment by secondhandnudes** [comment]
@J6667 It's not banned, though it's similar to the response you get when it is banned (it says "due to failure" instead of "exception"). In these cases, the accounts run through their cool off period and begin to function again.

Whether it's a soft ban is a different case, which is a definite possibility and why I'm asking whether anyone's found a solution.
