### ISSUE TITLE
Recaptcha

### ISSUE THREAD

**Issue by ze3ity** [mchristopher/PokemonGo-DesktopMap#1332]
Hello all,

Has anyone had to reCaptcha all their accounts? If so, is there a faster way of doing it (say, get them sent to the computer) or are you just logging onto each separate account to do the reCaptcha on a mobile device?

**Comment by Rayenous** [comment]
38 of 40 accounts had to be 'fixed'... within an hour of doing it, a couple of them got hit with recaptcha again.  -  Niantic seems to be developing it's detection methods.  May need to find a way to make scanning pattern seem more 'realistic'.  Perhaps never scanning the 'exact' same GPS location, but rather a location 'right beside' the previous spot.  (Ie: If a previous scan was 11.1111111, -11.111111, then make the next pas scan from 11.111112, -11.111112).  -  Just a thought.

**Comment by ze3ity** [comment]
Here's a link to bypass the Captcha.

https://github.com/PokemonGoMap/PokemonGo-Map/pull/1526

Not sure how to implement or go about it. Any help would be greatly appreciated.

**Comment by kanucks25** [comment]
Would be nice if someone had a fix/work-around.

I have to re-captcha seemingly once an hour. It wouldn't be that big of a deal if I knew exactly when the captcha was required so I wouldn't miss out on scans.

**Comment by Brisingrox** [comment]
You have a few options. 
1) make your self a pogo map and implement some 2captcha service inside so that you don't need to bother anymore about captchas.
2) you simply create some new accounts to scann. Because i suppose all of your accounts are flagged. And you will get more and more captchas because the map here is not up to date with the right 0.45 api

**Comment by kanucks25** [comment]
@Brisingrox Is #1 even possible for someone with zero programming experience? :P
