### ISSUE TITLE
Scan starts 2 cells out from desired location

### ISSUE THREAD

**Issue by MeTheBosss** [mchristopher/PokemonGo-DesktopMap#1334]
Is this a desired feature?  Select a location for the desired scan.  It starts out a radius of 2 steps and scans inward.  Sometimes, you just want to see what is at that location rather than waiting.  Any way to change it?  On Mac OX 10.

**Comment by kanucks25** [comment]
When the scanner first came out it wasn't like this, not sure why it's changed. I'm sure there is a way to change it but I don't know how to tweak the files.

Now I kind of just estimate where the circle is going to pop up by placing the marker east-northeast of the desired location.
