### ISSUE TITLE
Stopped showing Pokémon

### ISSUE THREAD

**Issue by OliverAlmonte** [mchristopher/PokemonGo-DesktopMap#1335]
It worked perfectly until yesterday. Since yersterday it doesn't show Pokémon, even though it's on "operational" and It's scanning areas. (I'm sure there are Pokémon because I'm playing)

**Comment by J6667** [comment]
I'm pretty sure, that is an IP Ban. Got several times IP banned since yesterday with my ~80 workers. Will try with just 60 workers today.

**Comment by vgcf** [comment]
log into your scanner acct and solve the captcha then it should work fine again

**Comment by OliverAlmonte** [comment]
@vgcf Could you explain me with more detail how to do that?

**Comment by vgcf** [comment]
on your phone
