### ISSUE TITLE
Scanner isn't scanning

### ISSUE THREAD

**Issue by ZaloSan** [mchristopher/PokemonGo-DesktopMap#1336]
I got two aacounts, one from Google and a PTC one running together.

The map is not showing Pokemon nor Gyms nor Pokestops, not even when I leave it scanning for hours and hours.

**Comment by vgcf** [comment]
your accounts been flagged. solve the captchas on your phone

**Comment by pitmasteruniversity** [comment]
I have the same problem and have solved the CAPTCHAS???

**Comment by Acker-Andy** [comment]
Same question

**Comment by Acker777** [comment]
Same problem+1
