### ISSUE TITLE
Map don't show all Pokemons and Spawn Points

### ISSUE THREAD

**Issue by batsche** [mchristopher/PokemonGo-DesktopMap#1342]
As I wrote in the headline, the map don't show all the pokemons and spawn points in the scanned area. I don't know why, but it helps less if the map show a pigdey and the snorlax 1ft away not f.e.

Is this a bug or what is the problem?

**Comment by cendak** [comment]
Maybe it's scan delay to fast, I also have this problem. 

Colleague has a similar map and there changed the scan delay to 12s (movement speed of 10m/s) and it's much better.

**Comment by l3lackitty** [comment]
Where can you edit scan delay?
