### ISSUE TITLE
can someone help me please

### ISSUE THREAD

**Issue by furax187** [mchristopher/PokemonGo-DesktopMap#1344]
First of all i am no IT-engineer or  it-specialist. I am just a person who loves to play pokemon go.
So a few months ago, i installed the pokemongo-desktopmap and i created like 10 accounts that i use to scan the area where i live with. Everything worked great, until niantic made an update involving capthas.
Cause when i ran the map it didnt showed me any pokemon. So i read on the forum, u have to fix the capthas in pokemon go.  Now today i logged into my 10 accounts and did the captha shit to see if you are a person. But after an hour, i see that the map doesnt show me pokemons again. So i assume that captha shit is on again. So i came to the issues page here and i read that there is a way to fix the captha shit automaticly. Someone posted a solution. But for me that thread is chinese ( no offense to chinese people lol ). So if christopher could update the .exe with a automaticly fix for the captha i would appreciate it. Or if someone could explain/make a tutorial how to install the update into the files that would be awesome aswell and then people like me could try to fix it ourselves.
Also if i would make new accounts and start using those, will i still have the captha shit from in the beginning or will it take days before it would get it?

The fix that i am talking about is here: https://github.com/PokemonGoMap/PokemonGo-Map/pull/1526

**Comment by Rayenous** [comment]
I'm in essentially the same boat.  40 accounts, all getting reCaptcha'd repeatedly.  I have followed the "Enable automated recaptcha solving with 2captcha" the best that I could, by inserting the changes mentioned into the specified files, but have been unable to get the reCpatcha fix to work.

Note: I am running this on OSX 10.9.5, in case that info helps.

**Comment by Nonkel** [comment]
Lastly, the captcha is coming up very fast. If I solve the captcha, a while ago the account would last for almost a day. Now Im happy if it lasts more than an hour. How can this be tackled?
No fun in having to log in to my accounts every hour just to keep the scanner running. If thats the state its in at the moment, the scanner might as well be down. Sad face here.....

**Comment by CTsouth86** [comment]
A tutorial would be nice just to understand what to do.

**Comment by furax187** [comment]
Yes it would be. So if someone got it working, can that person pls explain what we have to do.
I hope Christopher will release an update of his program with a fix for this problem. Christopher if u read this, i am counting on u ( says a desperate pokemon go player lol )

**Comment by Nonkel** [comment]
This one could also be useful: https://github.com/PokemonGoMap/PokemonGo-Map/pull/1582

Don't know how to implement this...in the same boat as you guys. Seems there must be some way to replace or add files?? Can someon help us out, please!

**Comment by Nonkel** [comment]
Maybe change the title of this topic to better reflect what we need help with? Something like: Please help needed with how to implement different solutions suggested here at github, Noobs need help! (im one of the noobs...)

**Comment by Lucitiana** [comment]
Guys, easiest is that you just reinstall the scanner but use a git pull, this way you will already download the files that have the recaptcha included and you just need to set it up by getting an API key from 2captcha and put it in the config file. Be aware that 2captcha requires you to put real money in there in order for it to solve your captchas though.

Follow this: https://pgm.readthedocs.io/en/develop/basic-install/index.html#git-version
