### ISSUE TITLE
issue with loading  names from the gym holder

### ISSUE THREAD

**Issue by Elfandor** [mchristopher/PokemonGo-DesktopMap#1347]
I dont see the name of the gym holder. I have no idea why i dont see it :/ .

Thats how it looks like everythign seem to works normal: 

https://gyazo.com/b68fa9ca2fd7bb4f6bb879dc6e57022d

thanks a lot for any help i get :)

**Comment by krisdunn5** [comment]
how were you able to get iv's and movesets for pokemon?

**Comment by Rayenous** [comment]
@krisdunn5 - That can be found here:
https://github.com/mchristopher/PokemonGo-DesktopMap/wiki/Config.INI

**Comment by Elfandor** [comment]
soemone any idea? :(
