### ISSUE TITLE
not working anymore?

### ISSUE THREAD

**Issue by Toodo** [mchristopher/PokemonGo-DesktopMap#1348]
yesterday i found pokemons but today i cant find anything

**Comment by Toodo** [comment]
its working now but i have 3 accounts and one says maybe banend and one works only the scan cant find any pokemons/gyms pokestops.
so i created a new account but its says that the now account is banned why?

**Comment by ppianta** [comment]
i've had a banned account too - not much you can do about it. for the account that is not finding any pokemon, log into the pokemon go mobile app with the account in question and you will probably have to solve a captcha (or two or three) and then the account should be back to normal.
