### ISSUE TITLE
More errors

### ISSUE THREAD

**Issue by SetMeFree1** [mchristopher/PokemonGo-DesktopMap#1349]
https://gyazo.com/93fa9034d9625acc5bc37a7dc7227090
https://gyazo.com/5949451e1c2bc8a4d749dadb35f022e2

These are the same errors I've been getting. I've tried to get a new API key, it didnt work. I've had this issue for months, kept coming back to this because when it worked, it was good...

**Comment by ppianta** [comment]
I've seen those errors before and i simply fully closed out the app and restarted it and most of the time it was fine after that. it seems fully resetting the app helps for lots of issues and now it's the first thing i do when i hit any error.
