### ISSUE TITLE
[Suggestion] restart radar without logging out and back in

### ISSUE THREAD

**Issue by xan326** [mchristopher/PokemonGo-DesktopMap#135]
So this suggestion came with an issue, which so far has been fixed from a previous version. Before I would start the radar, let it run, and it worked in almost like a ripple pattern; but it would never load pokemon back in the center. The newer version, from what I can tell, has stopped that, but I can't exactly tell; I feel like their should be more pokemon spawning in my area, but I can only tell by restarting the program.
So, a nice little button for restarting the radar would be nice.

**Comment by xan326** [comment]
Also, to go along with this; setting options from when you're already logged in.

**Comment by mchristopher** [comment]
You can now change location without login/logout in the latest version.
