### ISSUE TITLE
"This page didn't load Google Maps correctly" when launching

### ISSUE THREAD

**Issue by joshbgosh10592** [mchristopher/PokemonGo-DesktopMap#1361]
Hello! Is this project still working? When I launch it on Windows, I see a flash of Google Maps, but then loads to, "Oops! Something went wrong. This page didn't load Google Maps correctly. See the JavaScript console for technical details"
Any idea?

**Comment by SoloKMV** [comment]
You must create your own Google Maps API Key!
Follow this guide: https://github.com/mchristopher/PokemonGo-DesktopMap/wiki/Google-Maps-API:-a-brief-guide-to-your-own-key

**Comment by joshbgosh10592** [comment]
I did though.
