### ISSUE TITLE
error please help me

### ISSUE THREAD

**Issue by dtcpatjuh** [mchristopher/PokemonGo-DesktopMap#1366]
![error](https://user-images.githubusercontent.com/21728575/34123011-7eaa69d0-e42e-11e7-9ec4-81204133f982.jpg)
what does this mean ?
and what can i do to fix this ?

**Comment by ghost** [comment]
[Read this.](https://github.com/mchristopher/PokemonGo-DesktopMap/wiki/FAQ#why-is-there-an-outage) (BTW this project is now unmaintained, so you shouldn't even use this)
