### ISSUE TITLE
Easier Pokemon filter.

### ISSUE THREAD

**Issue by they007** [mchristopher/PokemonGo-DesktopMap#137]
So, I'm sure this isn't the best way to implement it, but i threw this table in my login.html and now I can just click the Pokemon I want to filter/hide. It does work for me and I'm able to easily click the pokemon I do/don't want to show in my filter.

![pokefilter](https://cloud.githubusercontent.com/assets/19333809/17074104/4df5d148-503d-11e6-9e9c-417627231751.png)

I put my table code right after: 
`<span>
Fill in a list of Pokemon to filter (ex: <code>1,2,3,4</code>)
</span>
`

My table below:

`<table>
<tbody>
<tr><td><a href=# onclick="javascript:pokeids.value+=this.id;" id="1,"><img src="map/static/icons/1.png" alt="pokemon1"></a></td><td><a href=# onclick="javascript:pokeids.value+=this.id;" id="2,"><img src="map/static/icons/2.png" alt="pokemon2"></a></td><td><a href=# onclick="javascript:pokeids.value+=this.id;" id="3,"><img src="map/static/icons/3.png" alt="pokemon3"></a></td><td><a href=# onclick="javascript:pokeids.value+=this.id;" id="4,"><img src="map/static/icons/4.png" alt="pokemon4"></a></td><td><a href=# onclick="javascript:pokeids.value+=this.id;" id="5,"><img src="map/static/icons/5.png" alt="pokemon5"></a></td><td><a href=# onclick="javascript:pokeids.value+=this.id;" id="6,"><img src="map/static/icons/6.png" alt="pokemon6"></a></td><td><a href=# onclick="javascript:pokeids.value+=this.id;" id="7,"><img src="map/static/icons/7.png" alt="pokemon7"></a></td><td><a href=# onclick="javascript:pokeids.value+=this.id;" id="8,"><img src="map/static/icons/8.png" alt="pokemon8"></a></td><td><a href=# onclick="javascript:pokeids.value+=this.id;" id="9,"><img src="map/static/icons/9.png" alt="pokemon9"></a></td><td><a href=# onclick="javascript:pokeids.value+=this.id;" id="10,"><img src="map/static/icons/10.png" alt="pokemon10"></a></td><td><a href=# onclick="javascript:pokeids.value+=this.id;" id="11,"><img src="map/static/icons/11.png" alt="pokemon11"></a></td><td><a href=# onclick="javascript:pokeids.value+=this.id;" id="12,"><img src="map/static/icons/12.png" alt="pokemon12"></a></td><td><a href=# onclick="javascript:pokeids.value+=this.id;" id="13,"><img src="map/static/icons/13.png" alt="pokemon13"></a></td><td><a href=# onclick="javascript:pokeids.value+=this.id;" id="14,"><img src="map/static/icons/14.png" alt="pokemon14"></a></td><td><a href=# onclick="javascript:pokeids.value+=this.id;" id="15,"><img src="map/static/icons/15.png" alt="pokemon15"></a></td><td><a href=# onclick="javascript:pokeids.value+=this.id;" id="16,"><img src="map/static/icons/16.png" alt="pokemon16"></a></td><td><a href=# onclick="javascript:pokeids.value+=this.id;" id="17,"><img src="map/static/icons/17.png" alt="pokemon17"></a></td><td><a href=# onclick="javascript:pokeids.value+=this.id;" id="18,"><img src="map/static/icons/18.png" alt="pokemon18"></a></td><td><a href=# onclick="javascript:pokeids.value+=this.id;" id="19,"><img src="map/static/icons/19.png" alt="pokemon19"></a></td><td><a href=# onclick="javascript:pokeids.value+=this.id;" id="20,"><img src="map/static/icons/20.png" alt="pokemon20"></a></td><td><a href=# onclick="javascript:pokeids.value+=this.id;" id="21,"><img src="map/static/icons/21.png" alt="pokemon21"></a></td><td><a href=# onclick="javascript:pokeids.value+=this.id;" id="22,"><img src="map/static/icons/22.png" alt="pokemon22"></a></td><td><a href=# onclick="javascript:pokeids.value+=this.id;" id="23,"><img src="map/static/icons/23.png" alt="pokemon23"></a></td><td><a href=# onclick="javascript:pokeids.value+=this.id;" id="24,"><img src="map/static/icons/24.png" alt="pokemon24"></a></td><td><a href=# onclick="javascript:pokeids.value+=this.id;" id="25,"><img src="map/static/icons/25.png" alt="pokemon25"></a></td><td><a href=# onclick="javascript:pokeids.value+=this.id;" id="26,"><img src="map/static/icons/26.png" alt="pokemon26"></a></td><td><a href=# onclick="javascript:pokeids.value+=this.id;" id="27,"><img src="map/static/icons/27.png" alt="pokemon27"></a></td><td><a href=# onclick="javascript:pokeids.value+=this.id;" id="28,"><img src="map/static/icons/28.png" alt="pokemon28"></a></td><td><a href=# onclick="javascript:pokeids.value+=this.id;" id="29,"><img src="map/static/icons/29.png" alt="pokemon29"></a></td><td><a href=# onclick="javascript:pokeids.value+=this.id;" id="30,"><img src="map/static/icons/30.png" alt="pokemon30"></a></td><td><a href=# onclick="javascript:pokeids.value+=this.id;" id="31,"><img src="map/static/icons/31.png" alt="pokemon31"></a></td><td><a href=# onclick="javascript:pokeids.value+=this.id;" id="32,"><img src="map/static/icons/32.png" alt="pokemon32"></a></td><td><a href=# onclick="javascript:pokeids.value+=this.id;" id="33,"><img src="map/static/icons/33.png" alt="pokemon33"></a></td><td><a href=# onclick="javascript:pokeids.value+=this.id;" id="34,"><img src="map/static/icons/34.png" alt="pokemon34"></a></td><td><a href=# onclick="javascript:pokeids.value+=this.id;" id="35,"><img src="map/static/icons/35.png" alt="pokemon35"></a></td><td><a href=# onclick="javascript:pokeids.value+=this.id;" id="36,"><img src="map/static/icons/36.png" alt="pokemon36"></a></td><td><a href=# onclick="javascript:pokeids.value+=this.id;" id="37,"><img src="map/static/icons/37.png" alt="pokemon37"></td></tr>
<tr><td><a href=# onclick="javascript:pokeids.value+=this.id;" id="38,"><img src="map/static/icons/38.png" alt="pokemon38"></a></td><td><a href=# onclick="javascript:pokeids.value+=this.id;" id="39,"><img src="map/static/icons/39.png" alt="pokemon39"></a></td><td><a href=# onclick="javascript:pokeids.value+=this.id;" id="40,"><img src="map/static/icons/40.png" alt="pokemon40"></a></td><td><a href=# onclick="javascript:pokeids.value+=this.id;" id="41,"><img src="map/static/icons/41.png" alt="pokemon41"></a></td><td><a href=# onclick="javascript:pokeids.value+=this.id;" id="42,"><img src="map/static/icons/42.png" alt="pokemon42"></a></td><td><a href=# onclick="javascript:pokeids.value+=this.id;" id="43,"><img src="map/static/icons/43.png" alt="pokemon43"></a></td><td><a href=# onclick="javascript:pokeids.value+=this.id;" id="44,"><img src="map/static/icons/44.png" alt="pokemon44"></a></td><td><a href=# onclick="javascript:pokeids.value+=this.id;" id="45,"><img src="map/static/icons/45.png" alt="pokemon45"></a></td><td><a href=# onclick="javascript:pokeids.value+=this.id;" id="46,"><img src="map/static/icons/46.png" alt="pokemon46"></a></td><td><a href=# onclick="javascript:pokeids.value+=this.id;" id="47,"><img src="map/static/icons/47.png" alt="pokemon47"></a></td><td><a href=# onclick="javascript:pokeids.value+=this.id;" id="48,"><img src="map/static/icons/48.png" alt="pokemon48"></a></td><td><a href=# onclick="javascript:pokeids.value+=this.id;" id="49,"><img src="map/static/icons/49.png" alt="pokemon49"></a></td><td><a href=# onclick="javascript:pokeids.value+=this.id;" id="50,"><img src="map/static/icons/50.png" alt="pokemon50"></a></td><td><a href=# onclick="javascript:pokeids.value+=this.id;" id="51,"><img src="map/static/icons/51.png" alt="pokemon51"></a></td><td><a href=# onclick="javascript:pokeids.value+=this.id;" id="52,"><img src="map/static/icons/52.png" alt="pokemon52"></a></td><td><a href=# onclick="javascript:pokeids.value+=this.id;" id="53,"><img src="map/static/icons/53.png" alt="pokemon53"></a></td><td><a href=# onclick="javascript:pokeids.value+=this.id;" id="54,"><img src="map/static/icons/54.png" alt="pokemon54"></a></td><td><a href=# onclick="javascript:pokeids.value+=this.id;" id="55,"><img src="map/static/icons/55.png" alt="pokemon55"></a></td><td><a href=# onclick="javascript:pokeids.value+=this.id;" id="56,"><img src="map/static/icons/56.png" alt="pokemon56"></a></td><td><a href=# onclick="javascript:pokeids.value+=this.id;" id="57,"><img src="map/static/icons/57.png" alt="pokemon57"></a></td><td><a href=# onclick="javascript:pokeids.value+=this.id;" id="58,"><img src="map/static/icons/58.png" alt="pokemon58"></a></td><td><a href=# onclick="javascript:pokeids.value+=this.id;" id="59,"><img src="map/static/icons/59.png" alt="pokemon59"></a></td><td><a href=# onclick="javascript:pokeids.value+=this.id;" id="60,"><img src="map/static/icons/60.png" alt="pokemon60"></a></td><td><a href=# onclick="javascript:pokeids.value+=this.id;" id="61,"><img src="map/static/icons/61.png" alt="pokemon61"></a></td><td><a href=# onclick="javascript:pokeids.value+=this.id;" id="62,"><img src="map/static/icons/62.png" alt="pokemon62"></a></td><td><a href=# onclick="javascript:pokeids.value+=this.id;" id="63,"><img src="map/static/icons/63.png" alt="pokemon63"></a></td><td><a href=# onclick="javascript:pokeids.value+=this.id;" id="64,"><img src="map/static/icons/64.png" alt="pokemon64"></a></td><td><a href=# onclick="javascript:pokeids.value+=this.id;" id="65,"><img src="map/static/icons/65.png" alt="pokemon65"></a></td><td><a href=# onclick="javascript:pokeids.value+=this.id;" id="66,"><img src="map/static/icons/66.png" alt="pokemon66"></a></td><td><a href=# onclick="javascript:pokeids.value+=this.id;" id="67,"><img src="map/static/icons/67.png" alt="pokemon67"></a></td><td><a href=# onclick="javascript:pokeids.value+=this.id;" id="68,"><img src="map/static/icons/68.png" alt="pokemon68"></a></td><td><a href=# onclick="javascript:pokeids.value+=this.id;" id="69,"><img src="map/static/icons/69.png" alt="pokemon69"></a></td><td><a href=# onclick="javascript:pokeids.value+=this.id;" id="70,"><img src="map/static/icons/70.png" alt="pokemon70"></a></td><td><a href=# onclick="javascript:pokeids.value+=this.id;" id="71,"><img src="map/static/icons/71.png" alt="pokemon71"></a></td><td><a href=# onclick="javascript:pokeids.value+=this.id;" id="72,"><img src="map/static/icons/72.png" alt="pokemon72"></a></td><td><a href=# onclick="javascript:pokeids.value+=this.id;" id="73,"><img src="map/static/icons/73.png" alt="pokemon73"></a></td><td><a href=# onclick="javascript:pokeids.value+=this.id;" id="74,"><img src="map/static/icons/74.png" alt="pokemon74"></td></tr>
<tr><td><a href=# onclick="javascript:pokeids.value+=this.id;" id="75,"><img src="map/static/icons/75.png" alt="pokemon75"></a></td><td><a href=# onclick="javascript:pokeids.value+=this.id;" id="76,"><img src="map/static/icons/76.png" alt="pokemon76"></a></td><td><a href=# onclick="javascript:pokeids.value+=this.id;" id="77,"><img src="map/static/icons/77.png" alt="pokemon77"></a></td><td><a href=# onclick="javascript:pokeids.value+=this.id;" id="78,"><img src="map/static/icons/78.png" alt="pokemon78"></a></td><td><a href=# onclick="javascript:pokeids.value+=this.id;" id="79,"><img src="map/static/icons/79.png" alt="pokemon79"></a></td><td><a href=# onclick="javascript:pokeids.value+=this.id;" id="80,"><img src="map/static/icons/80.png" alt="pokemon80"></a></td><td><a href=# onclick="javascript:pokeids.value+=this.id;" id="81,"><img src="map/static/icons/81.png" alt="pokemon81"></a></td><td><a href=# onclick="javascript:pokeids.value+=this.id;" id="82,"><img src="map/static/icons/82.png" alt="pokemon82"></a></td><td><a href=# onclick="javascript:pokeids.value+=this.id;" id="83,"><img src="map/static/icons/83.png" alt="pokemon83"></a></td><td><a href=# onclick="javascript:pokeids.value+=this.id;" id="84,"><img src="map/static/icons/84.png" alt="pokemon84"></a></td><td><a href=# onclick="javascript:pokeids.value+=this.id;" id="85,"><img src="map/static/icons/85.png" alt="pokemon85"></a></td><td><a href=# onclick="javascript:pokeids.value+=this.id;" id="86,"><img src="map/static/icons/86.png" alt="pokemon86"></a></td><td><a href=# onclick="javascript:pokeids.value+=this.id;" id="87,"><img src="map/static/icons/87.png" alt="pokemon87"></a></td><td><a href=# onclick="javascript:pokeids.value+=this.id;" id="88,"><img src="map/static/icons/88.png" alt="pokemon88"></a></td><td><a href=# onclick="javascript:pokeids.value+=this.id;" id="89,"><img src="map/static/icons/89.png" alt="pokemon89"></a></td><td><a href=# onclick="javascript:pokeids.value+=this.id;" id="90,"><img src="map/static/icons/90.png" alt="pokemon90"></a></td><td><a href=# onclick="javascript:pokeids.value+=this.id;" id="91,"><img src="map/static/icons/91.png" alt="pokemon91"></a></td><td><a href=# onclick="javascript:pokeids.value+=this.id;" id="92,"><img src="map/static/icons/92.png" alt="pokemon92"></a></td><td><a href=# onclick="javascript:pokeids.value+=this.id;" id="93,"><img src="map/static/icons/93.png" alt="pokemon93"></a></td><td><a href=# onclick="javascript:pokeids.value+=this.id;" id="94,"><img src="map/static/icons/94.png" alt="pokemon94"></a></td><td><a href=# onclick="javascript:pokeids.value+=this.id;" id="95,"><img src="map/static/icons/95.png" alt="pokemon95"></a></td><td><a href=# onclick="javascript:pokeids.value+=this.id;" id="96,"><img src="map/static/icons/96.png" alt="pokemon96"></a></td><td><a href=# onclick="javascript:pokeids.value+=this.id;" id="97,"><img src="map/static/icons/97.png" alt="pokemon97"></a></td><td><a href=# onclick="javascript:pokeids.value+=this.id;" id="98,"><img src="map/static/icons/98.png" alt="pokemon98"></a></td><td><a href=# onclick="javascript:pokeids.value+=this.id;" id="99,"><img src="map/static/icons/99.png" alt="pokemon99"></a></td><td><a href=# onclick="javascript:pokeids.value+=this.id;" id="100,"><img src="map/static/icons/100.png" alt="pokemon100"></a></td><td><a href=# onclick="javascript:pokeids.value+=this.id;" id="101,"><img src="map/static/icons/101.png" alt="pokemon101"></a></td><td><a href=# onclick="javascript:pokeids.value+=this.id;" id="102,"><img src="map/static/icons/102.png" alt="pokemon102"></a></td><td><a href=# onclick="javascript:pokeids.value+=this.id;" id="103,"><img src="map/static/icons/103.png" alt="pokemon103"></a></td><td><a href=# onclick="javascript:pokeids.value+=this.id;" id="104,"><img src="map/static/icons/104.png" alt="pokemon104"></a></td><td><a href=# onclick="javascript:pokeids.value+=this.id;" id="105,"><img src="map/static/icons/105.png" alt="pokemon105"></a></td><td><a href=# onclick="javascript:pokeids.value+=this.id;" id="106,"><img src="map/static/icons/106.png" alt="pokemon106"></a></td><td><a href=# onclick="javascript:pokeids.value+=this.id;" id="107,"><img src="map/static/icons/107.png" alt="pokemon107"></a></td><td><a href=# onclick="javascript:pokeids.value+=this.id;" id="108,"><img src="map/static/icons/108.png" alt="pokemon108"></a></td><td><a href=# onclick="javascript:pokeids.value+=this.id;" id="109,"><img src="map/static/icons/109.png" alt="pokemon109"></a></td><td><a href=# onclick="javascript:pokeids.value+=this.id;" id="110,"><img src="map/static/icons/110.png" alt="pokemon110"></a></td><td><a href=# onclick="javascript:pokeids.value+=this.id;" id="111,"><img src="map/static/icons/111.png" alt="pokemon111"></td></tr>
<tr><td><a href=# onclick="javascript:pokeids.value+=this.id;" id="112,"><img src="map/static/icons/112.png" alt="pokemon112"></a></td><td><a href=# onclick="javascript:pokeids.value+=this.id;" id="113,"><img src="map/static/icons/113.png" alt="pokemon113"></a></td><td><a href=# onclick="javascript:pokeids.value+=this.id;" id="114,"><img src="map/static/icons/114.png" alt="pokemon114"></a></td><td><a href=# onclick="javascript:pokeids.value+=this.id;" id="115,"><img src="map/static/icons/115.png" alt="pokemon115"></a></td><td><a href=# onclick="javascript:pokeids.value+=this.id;" id="116,"><img src="map/static/icons/116.png" alt="pokemon116"></a></td><td><a href=# onclick="javascript:pokeids.value+=this.id;" id="117,"><img src="map/static/icons/117.png" alt="pokemon117"></a></td><td><a href=# onclick="javascript:pokeids.value+=this.id;" id="118,"><img src="map/static/icons/118.png" alt="pokemon118"></a></td><td><a href=# onclick="javascript:pokeids.value+=this.id;" id="119,"><img src="map/static/icons/119.png" alt="pokemon119"></a></td><td><a href=# onclick="javascript:pokeids.value+=this.id;" id="120,"><img src="map/static/icons/120.png" alt="pokemon120"></a></td><td><a href=# onclick="javascript:pokeids.value+=this.id;" id="121,"><img src="map/static/icons/121.png" alt="pokemon121"></a></td><td><a href=# onclick="javascript:pokeids.value+=this.id;" id="122,"><img src="map/static/icons/122.png" alt="pokemon122"></a></td><td><a href=# onclick="javascript:pokeids.value+=this.id;" id="123,"><img src="map/static/icons/123.png" alt="pokemon123"></a></td><td><a href=# onclick="javascript:pokeids.value+=this.id;" id="124,"><img src="map/static/icons/124.png" alt="pokemon124"></a></td><td><a href=# onclick="javascript:pokeids.value+=this.id;" id="125,"><img src="map/static/icons/125.png" alt="pokemon125"></a></td><td><a href=# onclick="javascript:pokeids.value+=this.id;" id="126,"><img src="map/static/icons/126.png" alt="pokemon126"></a></td><td><a href=# onclick="javascript:pokeids.value+=this.id;" id="127,"><img src="map/static/icons/127.png" alt="pokemon127"></a></td><td><a href=# onclick="javascript:pokeids.value+=this.id;" id="128,"><img src="map/static/icons/128.png" alt="pokemon128"></a></td><td><a href=# onclick="javascript:pokeids.value+=this.id;" id="129,"><img src="map/static/icons/129.png" alt="pokemon129"></a></td><td><a href=# onclick="javascript:pokeids.value+=this.id;" id="130,"><img src="map/static/icons/130.png" alt="pokemon130"></a></td><td><a href=# onclick="javascript:pokeids.value+=this.id;" id="131,"><img src="map/static/icons/131.png" alt="pokemon131"></a></td><td><a href=# onclick="javascript:pokeids.value+=this.id;" id="132,"><img src="map/static/icons/132.png" alt="pokemon132"></a></td><td><a href=# onclick="javascript:pokeids.value+=this.id;" id="133,"><img src="map/static/icons/133.png" alt="pokemon133"></a></td><td><a href=# onclick="javascript:pokeids.value+=this.id;" id="134,"><img src="map/static/icons/134.png" alt="pokemon134"></a></td><td><a href=# onclick="javascript:pokeids.value+=this.id;" id="135,"><img src="map/static/icons/135.png" alt="pokemon135"></a></td><td><a href=# onclick="javascript:pokeids.value+=this.id;" id="136,"><img src="map/static/icons/136.png" alt="pokemon136"></a></td><td><a href=# onclick="javascript:pokeids.value+=this.id;" id="137,"><img src="map/static/icons/137.png" alt="pokemon137"></a></td><td><a href=# onclick="javascript:pokeids.value+=this.id;" id="138,"><img src="map/static/icons/138.png" alt="pokemon138"></a></td><td><a href=# onclick="javascript:pokeids.value+=this.id;" id="139,"><img src="map/static/icons/139.png" alt="pokemon139"></a></td><td><a href=# onclick="javascript:pokeids.value+=this.id;" id="140,"><img src="map/static/icons/140.png" alt="pokemon140"></a></td><td><a href=# onclick="javascript:pokeids.value+=this.id;" id="141,"><img src="map/static/icons/141.png" alt="pokemon141"></a></td><td><a href=# onclick="javascript:pokeids.value+=this.id;" id="142,"><img src="map/static/icons/142.png" alt="pokemon142"></a></td><td><a href=# onclick="javascript:pokeids.value+=this.id;" id="143,"><img src="map/static/icons/143.png" alt="pokemon143"></a></td><td><a href=# onclick="javascript:pokeids.value+=this.id;" id="144,"><img src="map/static/icons/144.png" alt="pokemon144"></a></td><td><a href=# onclick="javascript:pokeids.value+=this.id;" id="145,"><img src="map/static/icons/145.png" alt="pokemon145"></a></td><td><a href=# onclick="javascript:pokeids.value+=this.id;" id="146,"><img src="map/static/icons/146.png" alt="pokemon146"></a></td><td><a href=# onclick="javascript:pokeids.value+=this.id;" id="147,"><img src="map/static/icons/147.png" alt="pokemon147"></a></td><td><a href=# onclick="javascript:pokeids.value+=this.id;" id="148,"><img src="map/static/icons/148.png" alt="pokemon148"></td></tr>
<tr><td><a href=# onclick="javascript:pokeids.value+=this.id;" id="149,"><img src="map/static/icons/149.png" alt="pokemon149"></a></td><td><a href=# onclick="javascript:pokeids.value+=this.id;" id="150,"><img src="map/static/icons/150.png" alt="pokemon150"></a></td><td><a href=# onclick="javascript:pokeids.value+=this.id;" id="151,"><img src="map/static/icons/151.png" alt="pokemon151"></td></tr>
</tbody>
</table>`

**Comment by mchristopher** [comment]
Check out the latest version, it should be a bit easier to deal with now.
