### ISSUE TITLE
[BIG Bug] Full Bag

### ISSUE THREAD

**Issue by fenixasin** [mchristopher/PokemonGo-DesktopMap#138]
bag gets full, not able to delete anything form the bot as far as delete all potions or only save 30 pokeballs

could be a way to find bots, over stuffed bag with like 600 items of the 350 limit

**Comment by killerjerick** [comment]
You're on the wrong github..

**Comment by fangwei007** [comment]
@fenixasin You are suck an idiot, look at your questions, LMAO!
