### ISSUE TITLE
Notify of Pokemon Not Making a Sound?

### ISSUE THREAD

**Issue by jameson167** [mchristopher/PokemonGo-DesktopMap#139]
Hey MChristopher, bravo on this new Version 0.1.0 I have been stress testing it out and it's working absolutely beautifully! The location changes, hide pokemon filters, and Google API location lookup are all working flawlessly. I will test out the 30-minute timeout update from PTC and see if it continues to live update without issues. 

I did have 1 simple question regarding the "notify of pokemon". I added a few common pokemon to that notify list to test out how the notification would respond but I didn't hear any sound or see any visual queues. What is supposed to happen when notifications are on? Thanks!

**Comment by michaelcao** [comment]
Same question here. Wasn't sure what notification I was supposed to be getting? A sound or popup? Not seeing anything at the moment. Otherwise, awesome update!

**Comment by ChristopherJOlson** [comment]
Same question, just commenting for visibility, great Update though!
