### ISSUE TITLE
Reports as Virus with Avast

### ISSUE THREAD

**Issue by Darkfae** [mchristopher/PokemonGo-DesktopMap#14]
Heads up, this reports as a virus/malware component with Avast! and the programme will delete the .exe file upon detecting it. Requested a boot time scan, yadda, yadda. 

It was quite unhappy with it, so fun times.

**Comment by ilikesomething** [comment]
maybe you should consider using a real antivirus and not this avastcrap. I suggest you Kaspersky or Nod32, it will be atleast a little more usefull than avast

**Comment by mchristopher** [comment]
This is outside my control, I'm using the Electron files from the official project. I assume Avast will update itself in time, but for now just mark this project as exempt.

**Comment by Darkfae** [comment]
Sorry I didn't get back - it uh, did a _fully bloody boot time scan_, which with my system and storage, took all day (had D&D anyway, so).

Yeah, I'll mark things as exempt for now. I just figured I'd report it so you guys could have it recorded and other people could know it was a thing prior to running it. Might not just be Avast that ends up freaking out about it at the moment, either. but we'll see.
