### ISSUE TITLE
Feature Request: Multiple Accounts

### ISSUE THREAD

**Issue by thappy** [mchristopher/PokemonGo-DesktopMap#140]
Log in with multiple PTC Accounts to track larger areas

**Comment by z06jaz** [comment]
There has to be a way increase the rate. skiplagged just came out with a map that refreshes GIANT areas instantly, its crazy. but its so crowded.. he doesn't have any filter settings

**Comment by killerjerick** [comment]
@z06jaz Skiplagged's map is based off Pokemonradargo which is just user submitted pokemon... It's not exactly a good map as it's not up to date and accurate...

**Comment by z06jaz** [comment]
Are you sure about that? From what I read and witnessed it pretty much does exactly what this map does, but broadcasts it to the skiplagged server and then the server puts it on their main map. So imagine all of us using this map, our results get sent to a server and then to a main map where everybody can see LIVE

**Comment by killerjerick** [comment]
Just tested in my area, 0 pokestops 0 pokemon, mchristopher's map shows ~20 pokestops and a lot of pokemon

**Comment by z06jaz** [comment]
killer thats because nobody is broadcasting in your area. Zip out a little bit. I know for a fact central park and in AZ where I am at downtown there are people using it and broadcasting the spawns live.
