### ISSUE TITLE
More Suggestion

### ISSUE THREAD

**Issue by ranrinc** [mchristopher/PokemonGo-DesktopMap#143]
Hi there,

ver 0.10 look very nice, however several feature that exist in ver 0.0.7 is gone.
I wish you can bring it back, especially the one with adding number to the list of what I want/need to see. Its really helpful rather than having to write it one by one to the hide and notification list. 

Still haven't figure out how to change location via the filter new function.

Anyway keep up the great work.. PokemonGo-DesktopMap rock!

**Comment by bravenizer** [comment]
Hi there,

Great new map.....but one thing I really missed from ver 0.0.7.....the coordinate of each pokemon.
Can you bring that back?

you're the man!! thx
