### ISSUE TITLE
Why it's not showing my current location. 

### ISSUE THREAD

**Issue by tangrl** [mchristopher/PokemonGo-DesktopMap#145]
Why it's not showing my current location. Instead, it's about 10 miles away.
Also, I can't figure out how to change location.

**Comment by Synthlord** [comment]
Having the exact same problem. Would also like to know how to change your location without logging out and changing the latitude/longitude.

**Comment by pill0ws** [comment]
I've seen this happen a lot as well. It's strange that it somehow fixes itself at times and other times it is just hell. My workaround is using google maps to find my actual current location and manually setting it.

**Comment by tangrl** [comment]
Can you tell the detailed steps how to manually set the location?

Thanks!
