### ISSUE TITLE
Can`t see the map?

### ISSUE THREAD

**Issue by smkaevur** [mchristopher/PokemonGo-DesktopMap#146]
version 0.1.0 loggin in ... and can see only parametres and settings... and blank instead a map

**Comment by Azzinoth** [comment]
same problem :(

**Comment by fitzfuchs** [comment]
![unbenannt](https://cloud.githubusercontent.com/assets/7803977/17077518/2e2a4a4c-50d3-11e6-8432-1b411da9811c.PNG)

Version 0.1.0 no map error after login under Windows 10 x64
