### ISSUE TITLE
Awesome improvements in 0.1.0.  Some issues with mobile.

### ISSUE THREAD

**Issue by tinarazzburton** [mchristopher/PokemonGo-DesktopMap#148]
I love the new filter system and the ability to add notifications.  It's working wonderfully on desktop.  

There's still some issues with mobile, because it seems after 30 minutes it stops populating new pokemon.  Also, the filters don't seem to carry over to mobile.  I'd have to manually type all filters on my phone each time I started mobile.  Also, expired pokemon stay on the map in mobile (though they disappear from the desktop version)

**Comment by 2-m** [comment]
I noticed he pushed https://github.com/mchristopher/PokemonGo-DesktopMap/commit/42452ce035422249d4cc61894d3f07cd8e93475f earlier, not sure if that fixes it or not
