### ISSUE TITLE
Location Setting Suggestion

### ISSUE THREAD

**Issue by audreyel-osta** [mchristopher/PokemonGo-DesktopMap#149]
Hi, the new update is absolutely fantastic, I almost feel greedy asking this, but would it be possible to be able to set location by dragging and dropping the red pin from which the radius starts? This would help with having a look at how things are elsewhere without having to pull up Maps, copypaste the coordinates and then hope for the best.

thanks again for your amazing work

**Comment by pill0ws** [comment]
So, if you are running windows 10, you can setup virtual desktops and run multiple instances of the app at the same time. They can all be in different areas scanning different nodes. Thats the trick I got going right now.

As far as feedback for the red pin, i think drag and drop is a noble cause. I could give up one or two virtual desktops with drag and drop. Ideally you could eventually aim for dynamic updates of current locations also but as an awesome tool, it works so much better by being able to manually ping different hot spots (Or cold spots, Snorlax literally hangs out in residential neighborhoods late at night). Hell, maybe you remove the location pin all together and just let users ping on the map to scan a space around it
