### ISSUE TITLE
Changing location on mobile doesn't work

### ISSUE THREAD

**Issue by alexnewmannn** [mchristopher/PokemonGo-DesktopMap#154]
Desktop uses an autofill in search provided by google, however, on mobile, the autofill suggestions never appear. I may be able to take a look into this later today

**Comment by shootaaa** [comment]
I started to use it last night. It was good at first, after a while, both desktop and mobile cant change locations. Any help would be appreciated! Thanks.

**Comment by SoonDead** [comment]
Same here it just does nothing. Logging in-out is a bother.
