### ISSUE TITLE
Auto Re-login?

### ISSUE THREAD

**Issue by CrystaX01** [mchristopher/PokemonGo-DesktopMap#155]
Anyway to do an automatic relogin once google times you out after 30mins? Cuz otherwise the map is hard to use if you can only go outside for 30mins with it, have to go back home and login/out and toogle mobile hosting again.

**Comment by changeisnormal** [comment]
It probably would be way faster to make a trainer club account for this than to wait for update.

**Comment by roflinger** [comment]
even with the PTC Account it logs out

**Comment by changeisnormal** [comment]
I am running 0.1.0 and it has been running for about 6 hours now on PTC account. Are you using the new version  ?

**Comment by roflinger** [comment]
yes i do - do you an account that you only use for the map? mine is also botting in this area i am scanning ^^

**Comment by changeisnormal** [comment]
It is a throwaway account for live map client.

**Comment by roflinger** [comment]
ok - i use a "maponly" account now too .. hope it helps, thx

**Comment by ranrinc** [comment]
Well.. if only I can signin for PTC account..

**Comment by roflinger** [comment]
works now for me with my extra account, thx

**Comment by CrystaX01** [comment]
The problem is registering PTC accounts is blocked since days due to "maintenance".

**Comment by changeisnormal** [comment]
The site comes back up once a while. I was able to make a few for the past two days during different time. Check often
