### ISSUE TITLE
[Suggestions/Request] and questions

### ISSUE THREAD

**Issue by changeisnormal** [mchristopher/PokemonGo-DesktopMap#156]
Suggestion/Request
1. Export/import filter list. It was actually quite easy to put in filter list in 0.0.7 by typing in numbers. Is it possible to make that an option again for Hide and Notify ?
2. Saving locations with names for easier login while on Desktop and display the same list once the map is running for fast switching on the go
3.  An option to put in port number for running multiple instances of live maps
4. Is it possible to manually remove pokemon we already captured from the map?

Questions 
How does Notification works ? I put some pokemons in there but nothing happens when they appear on the map

**Comment by SPGxSimplicity** [comment]
I preferred to have the filtering by numbers. That way, we could save our own lists.
