### ISSUE TITLE
Not perfect screen after using filter...

### ISSUE THREAD

**Issue by ranrinc** [mchristopher/PokemonGo-DesktopMap#158]
I believe this is also another bugs that happen on my Map
<img width="853" alt="screen shot 2016-07-23 at 9 20 39 pm" src="https://cloud.githubusercontent.com/assets/15801696/17078361/72017aea-511b-11e6-9059-6f5563e3f187.png">

**Comment by changeisnormal** [comment]
That looks fine. Do you mean the map is green ?

**Comment by ranrinc** [comment]
Did u see that there are missing Logout, Operational and Mobile.. furthermore the bottom part shown white area

**Comment by changeisnormal** [comment]
Oh...On Windows, there is a scroll bar on the right of the window. I didn't know how it works on Mac

**Comment by tealtail** [comment]
CSS problem. Main content area is height: 100%, not accounting for the padding-bottom: 50px. One fix would be to set `overflow:hidden` on `body > .container-fluid`

or remove `padding-bottom` and calculate correct height with respect to the 50px header with `calc()`:

```
.content {
    height: calc(100% - 50px);
    overflow: auto;
}
```
