### ISSUE TITLE
[REQUEST] Scan faster

### ISSUE THREAD

**Issue by roflinger** [mchristopher/PokemonGo-DesktopMap#159]
is there a way to make the scan faster? if yes where do i have to edit? :) thx

**Comment by roflinger** [comment]
found it in map.cs 

window.setInterval(updateMap, 5000);
updateMap();


you can also delete pokestop and gym search above

**Comment by SmilinItalin** [comment]
Ill have to try this :)...... how much fast can you get it to go.....does it cause any other lag?

**Comment by Hidden999** [comment]
Where did you find it? Cant find anything like map.cs??

**Comment by andrewda** [comment]
@Hidden999 Pretty sure he meant `map.js`.

**Comment by Hidden999** [comment]
@andrewda still dont know where that is??

**Comment by andrewda** [comment]
In the map directory. Should just be /map/static/map.js

**Comment by Hidden999** [comment]
@andrewda i see and what do i change the numbers to then?

**Comment by andrewda** [comment]
@Hidden999 I have no idea. You should probably ask @roflinger as he was the one who figured this out.

**Comment by Hidden999** [comment]
@andrewda thank you @roflinger what did you change the numbers to?

**Comment by z06jaz** [comment]
I would also like to know how to get it to scan faster. Our clients scan at .5 seconds.

**Comment by z06jaz** [comment]
Rofl what did you set the interval to? Did it work well ?

**Comment by z06jaz** [comment]
I've changed it a few times, I don't see any changes to how fast it scans :/

**Comment by Hidden999** [comment]
@z06jaz i didn't see any changes as well.
