### ISSUE TITLE
Change Your Location Not Working

### ISSUE THREAD

**Issue by mrachimv** [mchristopher/PokemonGo-DesktopMap#163]
Change Your Location Not Working

**Comment by theunreal** [comment]
Same here..

**Comment by SmilinItalin** [comment]
Same here.

**Comment by AppliedEllipsis** [comment]
Also not working, I have to logout, change it in the advanced section and log back in.

**Comment by iAbi** [comment]
Same here, I guess it's just putting in the coordinates and enter or tab away? No?

But nothing happens

**Comment by vbarashkov** [comment]
+1

**Comment by jameson167** [comment]
+1 Same issue, no longer able to type in locations via Google api, have to manually edit coordinates.
