### ISSUE TITLE
[BUG] Notify isn't working

### ISSUE THREAD

**Issue by PassyFox** [mchristopher/PokemonGo-DesktopMap#164]
When setting the pokémon to which i want to get notified in the filter part. i see them popping up on the map but the notify doesn't work. using the program on a Win10 PC

**Comment by cngodles** [comment]
This is working for me on a Windows 10 PC. It comes through the Windows Notification System. Do you maybe have that disabled/muted?

**Comment by PassyFox** [comment]
euhm how do i check to see if this is on?

**Comment by PassyFox** [comment]
found out how to put the alarms on thenx
