### ISSUE TITLE
excluding pokemon by number

### ISSUE THREAD

**Issue by daproject85** [mchristopher/PokemonGo-DesktopMap#166]
excluding pokemon by name can get painful if you want to exclude alot. furthermore it does not persist between desktop and mobile. Can we do it by number? it was great before when you could enter it at log in screen

**Comment by ranrinc** [comment]
I 2nd this too.... Changing into the name make it painful to add them

<img width="798" alt="screen shot 2016-07-24 at 12 24 14 am" src="https://cloud.githubusercontent.com/assets/15801696/17079271/ffb47c5c-5134-11e6-8bab-b9ed5a6df989.png">

**Comment by rhawley88** [comment]
what about doing it by name and number. since it currently searches with partial

**Comment by daproject85** [comment]
What do u mean partial

**Comment by rhawley88** [comment]
if you type in Dri in the box beedrill will come up and dodrio.  what you type does not have to be first letters of the word. so if you were to have it listed as Ivysaur 002. it would populate at 002 also

**Comment by daproject85** [comment]
Good idea
