### ISSUE TITLE
Only show pokestops with lure module

### ISSUE THREAD

**Issue by juic3pow3rs** [mchristopher/PokemonGo-DesktopMap#168]
In version 0.1.0 I miss the option "Only show pokestops with active pokestops module" like in the previous versions.

Would be awesome if you could implement this feature again.

**Comment by tristo7** [comment]
Gyms cannot have lure modules.

**Comment by juic3pow3rs** [comment]
You're right, I mean pokestops.

I don't know why I wrote gyms...
