### ISSUE TITLE
Windows 8 compatible

### ISSUE THREAD

**Issue by Chachos713** [mchristopher/PokemonGo-DesktopMap#172]
Could you make it windows 8 compatible, or is there something that prevents it from being windows 8 compatible.

**Comment by misterpink14** [comment]
I've run it on Windows 7 with no issues. From my understanding, it's just not actively being tested on any other Windows platform than 10. Have you had any issues with running it on Win8?

**Comment by Chachos713** [comment]
I found the problem. I was running python 3.4 when I needed to run python 2.7.
