### ISSUE TITLE
Reqest/Issue Refreshing UI changes Tunnel URL

### ISSUE THREAD

**Issue by CAAC** [mchristopher/PokemonGo-DesktopMap#174]
When refreshing UI, the tunnel URL changes.

Would it be possible to keep the same tunnel URL after refreshing? Or have an option to push the URL to a mobile device via text message?

Thanks!

**Comment by robertftw** [comment]
In version 1.1: after line in main.html 222 add so it looks like this:
`mobileTunnel = localtunnel(parsedServerUrl.port, {
local_host: '127.0.0.1',
subdomain:'YOUR_DOMAIN_NAME_HERE',`

**Comment by CAAC** [comment]
Do you happen to know the default forwarding port?
