### ISSUE TITLE
Pushover notifications

### ISSUE THREAD

**Issue by iAbi** [mchristopher/PokemonGo-DesktopMap#176]
Hi all,

Is something like pushover notifications something we could benefit from?

Scenario I have in mind:

You set the location, share de map with your mobile and go hunting. When a pokemon spawns that you have in your notification list, it give a notification on you computer/mac, but on to go it would be able to push a notification to your mobile or even smart watch. 1 click and you get directions!

**Comment by iAbi** [comment]
Pushover.net

**Comment by roflinger** [comment]
good idea :+1:

**Comment by iAbi** [comment]
or any change to add Growl? Once notifications are linked to Growl, it's easy to push it to Prowl for iOS device.

**Comment by iAbi** [comment]
How do I send Pushover notifications in Python?

The standard httplib and urllib libraries can be used, replacing "APP_TOKEN" with the token of your app, and "USER_KEY" with your user's key (or your own if sending messages to your own devices).

import httplib, urllib
conn = httplib.HTTPSConnection("api.pushover.net:443")
conn.request("POST", "/1/messages.json",
  urllib.urlencode({
    "token": "APP_TOKEN",
    "user": "USER_KEY",
    "message": "hello world",
  }), { "Content-type": "application/x-www-form-urlencoded" })
conn.getresponse()
For Python 3, httplib has been replaced with http.client and urlencode has moved to urllib.parse.

import http.client, urllib
conn = http.client.HTTPSConnection("api.pushover.net:443")
conn.request("POST", "/1/messages.json",
  urllib.parse.urlencode({
    "token": "APP_TOKEN",
    "user": "USER_KEY",
    "message": "hello world",
  }), { "Content-type": "application/x-www-form-urlencoded" })
conn.getresponse()
Alternatively, the 3rd party pushnotify Python package written by Jeffrey Goettsch, the pushover Python 3 package written by Wyatt Johnson, and the Chump Python package written by Karan Lyons are available.

[Top]

**Comment by Padawin86** [comment]
I agree. I would love for this to be able to forward the notifications to my phone through Growl. I'm not sure exactly how to set it up, but this document implies it shouldn't be that difficult

[http://www.growlforwindows.com/gfw/d.ashx?f=Growl%20for%20Windows%20-%20Application%20Integration%20Guide.doc](url)

**Comment by luckofthelefty** [comment]
I got push bullet working in a previous build. I'm sure I could get it again if that would be useful.

**Comment by PedroMD** [comment]
@luckofthelefty Tremendously useful :)
