### ISSUE TITLE
[BUG] location changing while in map not working

### ISSUE THREAD

**Issue by Hearttless** [mchristopher/PokemonGo-DesktopMap#178]
I don't know if i'm using this wrong or if it's not functional yet, but when I try to input a location into the filter menu while in the map screen, it does nothing. I tried inputting coordinates and also the specific location name as it is called on Google maps and neither works. If i'm using it wrong could someone please notify me. Thanks!

**Comment by MSAdministrator** [comment]
Yes, this just happened to me as well.  I actually have installed it on two systems and it was working as expected then it did not. Not sure if an API limit was hit or not.

**Comment by Hearttless** [comment]
When it's working, how do you change the location though? do you use coordinates?

**Comment by azarsawar** [comment]
not working for me also

**Comment by Chaoscontrol** [comment]
Same here. There's no "Set" button. I still try pressing Enter, but it doesn't do anything. Tried coordinates, tried street queries. Nothing.

**Comment by Quickbowjob** [comment]
Loaded the whole World! yet I've been stuck at the same grid area for hours all because the flag moving stop working since yesterday.
