### ISSUE TITLE
Cannot change location. Not able to go to other location. Please fix the issue. 

### ISSUE THREAD

**Issue by azarsawar** [mchristopher/PokemonGo-DesktopMap#179]
Cannot change location. Not able to go to other location. Please fix the issue.

**Comment by Ubuuntu** [comment]
Yep, me too. I cant change my location :\ With this fix the map should work pretty fine! Great job!

**Comment by itzgankstah** [comment]
I had this issue on my mac and also trying to load from my parrllels 10 windows install.  I still had the same issues.

It did work on my desktop though.  It seems the autopopulate list when you are typing in the address is not appearing.
