### ISSUE TITLE
Permit Own GoogleMaps API

### ISSUE THREAD

**Issue by jnovack** [mchristopher/PokemonGo-DesktopMap#18]
To prevent a blank screen or using an API key limit, permit users to enter their own Google Maps API key.

**Comment by fr-ser** [comment]
You can do that in the credentials file under resources\app\map

**Comment by Ashex1** [comment]
This will also be required once the rewrite of pokemongo-map is complete as currently the app is using the hardcoded key from that project.

**Comment by hfmls** [comment]
any hints on how to do this please?

**Comment by hfmls** [comment]
so...i just got a new API but the problem now is that i am already blacklisted on my ip.
How to counter this? thank you
