### ISSUE TITLE
Map not loading in mobile browser.

### ISSUE THREAD

**Issue by sturgisc** [mchristopher/PokemonGo-DesktopMap#180]
map loads fine on desktop app/ desktop browser. only the top bar with filter/Pokemongomap will load on both my iphone and android. i have tried all of the mobile browsers on both devices.

**Comment by KrayZeee** [comment]
got the same issue here

**Comment by mchristopher** [comment]
@sturgisc @KrayZeee do you guys have any filtering tools on your devices? Can you get me a console log from the browser?

**Comment by KrayZeee** [comment]
@mchristopher just tried another browser since the one i used to use didnt have any possibility for devtools. chrome is working fine, so the error is browserdependent

**Comment by Drkstoner** [comment]
I have gotten the map to load in samsung built in and Firefox for android browsers a few times but shortly there after I get a client message and have to restart mobile sharing

**Comment by sturgisc** [comment]
its working fine now. on all browsers. must of been an error on my end.
