### ISSUE TITLE
[REQUEST] add a screenshot button

### ISSUE THREAD

**Issue by PassyFox** [mchristopher/PokemonGo-DesktopMap#182]
this would come so much in handy when only displaying gyms for tactical purposes or creating maps for events

**Comment by KrayZeee** [comment]
windows and android aswell are able to take screenshots.. on windows press print then open paint and there press strg+v or open snippingtool to cut a part from your desktop..
on android i think it was volume up+powerbutton or on cyanogenmod go to settings buttons und aktivate screenshot... now press the powerbutton for a second and choose screenshot..

**Comment by joshuacane** [comment]
On a mac, you can press [Command] [Shift] [3] to take a screenshot and airdrop it to your phone. The whole process should only take about 30ish seconds.

**Comment by PassyFox** [comment]
all good sugestions but a quick screenshot button for the pc version makes it a bit more nicer :)
