### ISSUE TITLE
GPS Coordinates missing in v1.2.7?

### ISSUE THREAD

**Issue by Wakamo** [mchristopher/PokemonGo-DesktopMap#188]
Pokemon's exact coordinates no longer appear when selecting them. Was this feature intentionally taken away, and if so why? Personally, I found them immensely helpful.

**Comment by fenixasin** [comment]
we are not even on 127 yet....

**Comment by Wakamo** [comment]
<img width="396" alt="screen shot 2016-07-24 at 11 43 06 am" src="https://cloud.githubusercontent.com/assets/20618572/17084747/d4cebae8-5193-11e6-9ed9-94c25b837b05.png">
On second glance, I see what you mean. I was going off of the application info, which appears to be wrong or referencing something else.
