### ISSUE TITLE
0.1.1 not working for me

### ISSUE THREAD

**Issue by Ninjistix** [mchristopher/PokemonGo-DesktopMap#190]
had to downgrade back to 0.1.0

**Comment by Hearttless** [comment]
download it??? why is that hard. just delete all the 0.1.1 files, then go to the main page (https://github.com/mchristopher/PokemonGo-DesktopMap/releases) then scroll down to the download you want.

**Comment by Ninjistix** [comment]
i meant, when i downloaded the 0.1.1 and logged in, nothing came up, map was blank didnt even show any scanning being done, and also i did downgrade back to 0.1.0

**Comment by smkaevur** [comment]
anybody please resolve the problem with blank map? why it is blank?
