### ISSUE TITLE
linux error: no such file package.json

### ISSUE THREAD

**Issue by theresthatguy** [mchristopher/PokemonGo-DesktopMap#192]
"npm start" errors and outputs log files with following contents:

0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'start' ]
2 info using npm@3.10.3
3 info using node@v6.3.0
4 verbose stack Error: ENOENT: no such file or directory, open '/home/theresthatguy/Pokemon/pogodesk/package.json'
4 verbose stack     at Error (native)
5 verbose cwd /home/theresthatguy/Pokemon/pogodesk
6 error Linux 4.4.0-31-generic
7 error argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
8 error node v6.3.0
9 error npm  v3.10.3
10 error path /home/theresthatguy/Pokemon/pogodesk/package.json
11 error code ENOENT
12 error errno -2
13 error syscall open
14 error enoent ENOENT: no such file or directory, open '/home/theresthatguy/Pokemon/pogodesk/package.json'
15 error enoent ENOENT: no such file or directory, open '/home/theresthatguy/Pokemon/pogodesk/package.json'
15 error enoent This is most likely not a problem with npm itself
15 error enoent and is related to npm not being able to find a file.
16 verbose exit [ -2, true ]

**Comment by misterpink14** [comment]
Did npm install work first? Also, are you sure you are in the correct directory?

**Comment by theresthatguy** [comment]
Yes, npm is installed. No, I wasn't in the correct directory, but now I am running into new issue. Will post new issue. Thank you for the reply. Too much late night pokemon fried my brain.
