### ISSUE TITLE
Lures not working, Picture.

### ISSUE THREAD

**Issue by 23ttfe3fa** [mchristopher/PokemonGo-DesktopMap#193]
![wut](https://cloud.githubusercontent.com/assets/20591128/17081225/59bf54a2-5193-11e6-950b-7020c39f1222.jpg)

When refreshing the timers increase in duration and just seems buggy I can't tell if there is actually lures where they say there is and the timer is definitely not working properly.

Main reason I need this program is for the lure locations not many lures in my small town and if there is one I want to be able to know if its worth driving across town for it and it wont end before i get there.

**Comment by misterpink14** [comment]
Two images one after another would be helpful to see what's going on

**Comment by 23ttfe3fa** [comment]
Signed in found a lure:
![b4](https://cloud.githubusercontent.com/assets/20591128/17082179/d6358b22-51b7-11e6-808a-75994dc811bf.jpg)
Pressed "Tools/Refresh"
![after](https://cloud.githubusercontent.com/assets/20591128/17082178/d5e4160c-51b7-11e6-8bfc-4f93a7179e6a.jpg)
Took a few seconds to refresh and find lure and screenshot again but you can see the lure timer increased it's duration by minutes instead of going down 30ish seconds.

Anything else I can do to help figure this out? (I think it might have to do with some "Last updated variable"?)

**Comment by Ninjabull** [comment]
https://i.gyazo.com/9609deb974cd95fb0f47de47eb32a17f.png
Could be some localization issue with the lure timers?
