### ISSUE TITLE
Please add "dont show pokestops and gyms"

### ISSUE THREAD

**Issue by faataliis** [mchristopher/PokemonGo-DesktopMap#195]
Please add the options again, its annoying to see all pokemon and gyms, pokestop ):

**Comment by DarkriseOo** [comment]
dude, its in...

**Comment by DarkriseOo** [comment]
if you are on map, on the upper left side -> filter

**Comment by faataliis** [comment]
Yeah, i realized just after i logged in, im so sorry, you are doing such a nice job

**Comment by DarkriseOo** [comment]
np , just close the issue :)
