### ISSUE TITLE
View space maximization

### ISSUE THREAD

**Issue by AVellucci** [mchristopher/PokemonGo-DesktopMap#197]
The new update from today added a new darker bar and filters, which is super useful.
But the new bar also takes up more height revenue from the map. Would it be possible to either move the filter to the top white bar with the rest of the items or have the setting hide themselves on the left instead of taking up the space from the height of the map? I have a 1366x768 Monitor and I'd rather lose more space from the width than lose height.

EDIT: I've noticed now that the mobile uses this bar, didn't know this before. I still use my laptop when scanning for pokemon on the go and would still like to see the height space increased as much as possible for PC if possible.

**Comment by pill0ws** [comment]
Ithink part of the space consumption goes to the variance in size of names. Some names are much larger and take up more space. Icons would be more efficient for UI real estate. Names are useful for selecting what you want to filter, icons are more useful for "at a glance" information, like what is currently being filtered already.

**Comment by AVellucci** [comment]
The new bar that has been added is my main concern.
With the addition of this darker bar that now has the Filter rules on it we've lost another 51px of height to the Map view. on a larger monitor this is probably negligible, and this is probably still unnoticeable on a 4:3 screen but on a screen at 16:9 with smaller resolutions this loss of Map view space is very noticeable.
Windows 7 For example:
 - SuperBar takes up 39px
 - Titlebar if maximized takes up 22px
 - Menubar takes up 20px
 - The White bar takes up 50px
 - The new Filter bar takes up 51px  

if you add this all up you have 182px of space, on a screen that has a height of 768px that lost space is a huge deal.
