### ISSUE TITLE
[REQUEST] Is there anything useful I can help with?

### ISSUE THREAD

**Issue by pill0ws** [mchristopher/PokemonGo-DesktopMap#199]
I am not a strong coder, I have taken several courses and understand most of the basics and a lot of cause/effect type scenarios but writing is a skill I hadn't worked on. My interests lie mostly in the "Human" aspect of HCI. I studied cognitive science and specialized in human cognition. HCI was too intimidating to specialize in but it has become somewhat of a hobby in general for me as a gamer. Most my time spent paying games goes into setting up how I do so and this map has completely fascinated me with it's applications (hell, the game did that first to be fair, I hate pokemon but I love using the GPS to trigger my reward system). I spend probably more time coming up with unique ways to play games than actually playing them. I play Overwatch with a mouse and PS4 controller (for secondary mouse movement control using the gyroscope/accelerometer, feels like aiming a gun in conjunction with normal mouse control). I was actually dipping into remapping the circuits of the controller into a glove (Doomfist) before this new hotness swept away my fascinations. When I played WoW I spent pretty much more time editing LUA scripts of various UI's to make them as informative as possible with as little clutter so the experience wasnt degraded. Now I find myself just playing with this map app more so than chasing after the things it reveals

 I would love to get more involved but I know my skillset and writing code isn't within my stronger abilities. Mine lean more toward user centered design oriented around functional efficiency. The focus of my academics was on how brains do the things that we want them to do (and often things we dont want them to). Everything from sensation/perception to motor skills and breakdowns that occur from parallel and/or competitive processes (such as green and red, the reasoning behind why "redish-green" is nearly impossible to imagine).

All that said, the only thing I can think of that I may be able to contribute to this project would possibly be mockups. If that's the kind of thing that would be helpful I would love to throw some together. There's a lot of great ideas being posted by users and I could throw together some layouts of various feature sets so that the people who are actually good at writing code may have a picture of how it would look and/or come up with some better ideas in how they want to go about doing it. If the devs feel that is unnecessary, I am also cool with just testing and feeding back ideas/observations. I am having fun with this project either way, its almost more fun to study the pokemons behavior patterns than it is to go catch them. No joke, Snorlax is either eating or sleeping. He's only ever at a house or at a food spot. So if theres room for me to apply the source of my student loan debt to this project, I would love to help out where I can

**Comment by realbunny** [comment]
If you want to help out, fork the project and see what you can add to it.
