### ISSUE TITLE
Manual location

### ISSUE THREAD

**Issue by lpre30** [mchristopher/PokemonGo-DesktopMap#2]
When logging in, I first set the map location and then log in, but following that an error screen occurs and I wanted to see if I was doing something wrong. Thank you!

**Comment by 3nvy** [comment]
Me too, its says dat latitute and longitude are needed, even tho they are there :(

**Comment by reflexx666** [comment]
I had the same when I used the long/lat that was already in the field. If you overwrite it with your own long/lat it will work normally.

**Comment by poekrel** [comment]
It would be nice to be able to set a default Long & Lat or better yet, have the ability to save a list or coordinates with descriptions in something like a drop down menu

**Comment by billi165** [comment]
You may be trying to login too quick. On the initial login screen, wait for your coordinates to fill in before you hit the button.

**Comment by InfinityBMX** [comment]
Having the same problem. When I try to set manual co-ordinates I get a latitude and longitude are needed error. Happened 6 times in a row so I came here to check issues and when I went back to try again it worked.

**Comment by AVellucci** [comment]
This has been resolved in Latest versions and setting LAT/LON on the login page will carry over to the Map.
