### ISSUE TITLE
[0.1.1] Google Maps not loading 

### ISSUE THREAD

**Issue by xardover** [mchristopher/PokemonGo-DesktopMap#203]
I've seen some reports like this #157 about Google Maps not loading. It seems like issue was fixed in 0.1.1 but i having the same problem on this version.

Screenshot: http://imgur.com/a/qRXbj

I am running 64-bit Windows 10

Can you fix it please?

**Comment by Pineyka** [comment]
CCleaner! and clean computer

**Comment by xardover** [comment]
What exactly i need to clean?

**Comment by fitzfuchs** [comment]
Same problem as in 0.1.0
Map not loading:
![unbenannt](https://cloud.githubusercontent.com/assets/7803977/17083739/5411b638-51a9-11e6-8d66-67bd1fc4b867.PNG)

**Comment by BuloZB** [comment]
I clean registry with cc ccleaner And now works fine

**Comment by xardover** [comment]
Registry cleaning is not working

**Comment by xardover** [comment]
It seems like 0.7.0 is working — map is fine but this version has other problems

**Comment by misterpink14** [comment]
Running a full cycle of CCleaner should fix that. Have you tried that? (not the registry cleaner)

**Comment by xardover** [comment]
Full cleaning cycle not working too
