### ISSUE TITLE
Public map

### ISSUE THREAD

**Issue by ntamas94** [mchristopher/PokemonGo-DesktopMap#204]
Make a public map so everybody see the resoult , the program conect to a public server and sent the pokemon coordinates. this solution makes to use multiple accounts.   Catch them all together!!! :D

**Comment by sportyguy** [comment]
Too much traffic, it would bog down and make the map unusable.

**Comment by mixJ2O** [comment]
@ntamas94 the current method is the best way to ensure that the required Pokemon account used to "see" the Pokemon isn't banned. If one account is being used to scan Pokemon at multiple locations all around the world it would get banned very quickly. Besides, there is also the issue with the Google Maps API call limit which is something like 25,000 a day which would be used very quickly if everyone used it.

Oh, and there is.. https://pokevision.com
