### ISSUE TITLE
[Request] Add subdomain support for localtunnel.me

### ISSUE THREAD

**Issue by they007** [mchristopher/PokemonGo-DesktopMap#207]
LocalTunnel.me allows you to specify a specific subdomain. Add an option (textbox in the mobile sharing dialog) that allows you to request a specific subdomain. This feature will allow me to bookmark/favorite my pokemon go map URL on my mobile and not have to QR code scan it each time. 

(I've modified the code directly and just hardcoded my subdomain, which works fine, but it would be nicer to have this in the UI).

**Comment by sniperz911** [comment]
Can you send me the code ? would be great instead of making a macro xD
