### ISSUE TITLE
Help!How to set the latitude and longitude?

### ISSUE THREAD

**Issue by pengzijian1992** [mchristopher/PokemonGo-DesktopMap#208]
How to set the latitude and longitude?It seems that there are something different to the interface you post
![qq 20160724214842](https://cloud.githubusercontent.com/assets/20619059/17084183/33141bf6-51ea-11e6-9f73-d29306f9df56.png)

**Comment by Hearttless** [comment]
You can set it when you log in. I don't think the in-map location changer works right now as there are many posts about it and no clear answer yet. for right now you just have to use the one on the log in screen until there is a patch.

**Comment by andrewda** [comment]
#213
