### ISSUE TITLE
Feature request.

### ISSUE THREAD

**Issue by JohanJu** [mchristopher/PokemonGo-DesktopMap#21]
I have some ideas that may make this even better

1. Drag position
2. Auto walk (https://play.google.com/store/apps/details?id=com.marlon.floating.fake.location) for inspiration of good implementation.
3. Rare pokémon notification 

4 Combine to find them all!!!﻿

Also set location doesn't work for me

**Comment by Ruined1** [comment]
@JohanJu CLEARLY you don't understand what this application does. It doesn't affect your game at all, it ONLY shows you what pokemon are around at the location you set. It's a map to find the pokemon, that's it.

**Comment by JohanJu** [comment]
@Ruined1 Please explain which of this points affect the game:
1. Location is set by input coordinates it should be able to set by drag en drop.
2. Pseudo code (for (coordinates = start; coordinates!=end; coordinates+=stepSize))
3. When drawing icons: (if(pokemon in rareList){play sound})

**Comment by marandus** [comment]
All of these are extensions to the underlying MAP server application, you should post your request there: https://github.com/AHAAAAAAA/PokemonGo-Map
