### ISSUE TITLE
[0.1.1] Mobile: No active client for '.............'

### ISSUE THREAD

**Issue by ZetPill** [mchristopher/PokemonGo-DesktopMap#210]
The map loads perfectly fine on my phone with PTC. However, after a small amount of time (seems to differ from 10 minutes to around 30 minutes) no new Pokemon are loading on the map. Everytime I then try to refresh it it tells me the error mentioned in the title.

**Comment by jorgejd** [comment]
Getting same issue constantly, some times even before 10 minutes or right away some times after an hour (Most it has lasted without) Tested it all day yesterday.

**Comment by DyonR** [comment]
Can confirm, Using Windows 10, PTC account, same error after 10-30 minutes.
Since the webserver is hosted on port 8000, wouldn't it be possible to port-forward my router and allow me to connect using my IP?
I did try connecting to the ip:8000 locally, but that didn't work.

**Comment by Hearttless** [comment]
i think that it stops refreshing new pokemon after you leave the wifi with the ip address that the map is being hosted on. I've just realized this as it still counts the time until expiration even after you leave wifi which confused me in the begining as to why it would still count down and not find new pokemon. The mobile version is just really buggy after you leave wifi.

**Comment by ZetPill** [comment]
@Hearttless I always use mobile network, even at home, so I never leave wifi as I'm never connected to it.
