### ISSUE TITLE
Wrong Location

### ISSUE THREAD

**Issue by Akshadraj** [mchristopher/PokemonGo-DesktopMap#212]
When I start the map and log in using any of my account it places me in a spot where I am not. I am around 5kms away from the location it shows. Also the location is not changeable even though there is an option to change it in Filter menu. Please help me

**Comment by Lagoph** [comment]
same problem someone said copying pasting was working but cant figure it out - sorry

**Comment by pill0ws** [comment]
So I have noticed this too. Then I will log in to google maps directly via a browser and click "update location" and it will put me in that same strange place. This could be an error caused by just getting bad info directly from google. I have see the error repeated outside of the app itself

**Comment by IMNoob1** [comment]
There is currently some bugs with geolocation (either googles GPS detector or something else) it's a known issue, in order to view your location manually input it
