### ISSUE TITLE
the filter does not work

### ISSUE THREAD

**Issue by takenpro** [mchristopher/PokemonGo-DesktopMap#214]
Not works in windows 8.1 :(

**Comment by itzgankstah** [comment]
works on windows 10 =) . sad face...

**Comment by heyjonmanning** [comment]
Which version? 

If you're filtering when you log in (I know that was the case for 0.0.7) you have to change the "No Filter" dropdown box to either "Do Not Show" or "Only Show" for the filtering to work regardless if you entered values into the input box next to it.

**Comment by Lagoph** [comment]
@itzgankstah I'm on windows 10 & cant change my location in the filter. any tips?

**Comment by heyjonmanning** [comment]
@Lagoph just log out and reset the GPS coordinates. The location setting in the filter bar doesn't seem to be working for me either on v0.1.1

**Comment by Lagoph** [comment]
BOOM. I didn't even see it had override function at login screen. You da Man. 
-thanks

**Comment by heyjonmanning** [comment]
@Lagoph No problemo :)
