### ISSUE TITLE
localhost:8000 and how to share that?

### ISSUE THREAD

**Issue by ntamas94** [mchristopher/PokemonGo-DesktopMap#215]
local ip:8000       not work
i tryed myip:8000 and nothing
portforward 8000      not work

please help me.

**Comment by daproject85** [comment]
this runs on 5000 man

**Comment by ntamas94** [comment]
localhost:8000 that work 
localhost:5000 not work
mayebe run on 8000 port :d

**Comment by DyonR** [comment]
@daproject85 Are you sure it runs on port 5000? According to my netstat Python is hosting something on port 8000...

**Comment by daproject85** [comment]
I'm running mine bro , I didn't mod anything , straight OOTB
