### ISSUE TITLE
address search location change issue

### ISSUE THREAD

**Issue by DarkVapur** [mchristopher/PokemonGo-DesktopMap#216]
the change your location box isnt working, it doesnt display the drop down menu of locations for me to select a new one to go to

**Comment by powerseller1001** [comment]
same problem here, would be great if the box would be working to quick select predefined locations.

**Comment by pill0ws** [comment]
Yea, I would love preset locations rather than manually copy pasting every time

**Comment by Lagoph** [comment]
@pill0ws - you said manually copying every time? Are you using GPS coordinates? I can seem to get anything to change the location from the one it starts up with. Wind 10 btw.
