### ISSUE TITLE
Great Work, Little Suggestion

### ISSUE THREAD

**Issue by maxbrauer123** [mchristopher/PokemonGo-DesktopMap#218]
Hello Mr. Christopher,

Great work. Everyone, even we in Germany are using your Programm for Pokemon Go. A great Point are the notifications, when a new Pokemon spawns in the scanned Area. It would be Great if we could filter all Pokemon at once, so that we dont need to type in them all. 

Can you add the feature, that we can add all Pokémon to the Hide Pokemon and Notify of Pokemon) List? 

Thank you for your Work,

Greeting from Bonn, Germany

**Comment by Hearttless** [comment]
You can hide all pokemon in the 0.1.1 and i think 0.1.0 as well. Uncheck the Pokemon slider in the filter menu and all mapped pokemon are hidden and just the gyms and pokestops show.
