### ISSUE TITLE
Localtunnel issues

### ISSUE THREAD

**Issue by MidKnightReaper** [mchristopher/PokemonGo-DesktopMap#219]
Since the change to localtunnel it refreshes very slow, and if I refresh the mobile page it fails completely and I have to go back to my desktop and reset the mobile sharing. I never had this problem with ngrok. Only had to refresh the sharing when I reached the Google timeout limit.

**Comment by dusktildawn48** [comment]
i second this.

**Comment by eatcodeplay** [comment]
Let me third that. localtunnel is really not helping :)

**Comment by pill0ws** [comment]
I have gotten 'no active client' errors quite often. It's much less reliable than ngrok in its current state

**Comment by jellyjuice** [comment]
Agree, I have ran into this problem multiple times as well, sucks when you start it up, go out, only to find it stops working roughly around the 15 min mark for me.

**Comment by halorrr** [comment]
Yeah this has become unusable on the go for me since the switch to localtunnel

**Comment by Auzzy** [comment]
I've also been experiencing this issue. I've switched back to 0.1.0 for the time being.

**Comment by Stupefy** [comment]
just wanted to bump this.  none of my friends or i can keep localtunnel working for more than a few minutes.  It times out and says "no active client for "'asdfasdfas'"
