### ISSUE TITLE
Build instruction

### ISSUE THREAD

**Issue by JohanJu** [mchristopher/PokemonGo-DesktopMap#22]
Can you add instructions for how the program can be built and run from the sources?
Also would it be possible to run this on a webserver like wamp and open the page in chrome?

**Comment by blogui91** [comment]
+1

**Comment by mchristopher** [comment]
I added a README that includes some of these details. It's technically possible to run as a web server, but you'll probably want to look into the original https://github.com/AHAAAAAAA/PokemonGo-Map repo for that.
