### ISSUE TITLE
linux: stays on login screen

### ISSUE THREAD

**Issue by theresthatguy** [mchristopher/PokemonGo-DesktopMap#220]
With no linux specific instructions I managed to get this app running using:

curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
sudo apt install nodejs
sudo pip install virtualenv
cd ~/pogodesk/resources/app
sudo npm install electron-prebuilt
npm start

However, after I click login, the button is slightly lighter shade and while you can't see it in the screenshot below my mouse turns into and stays as a little fist with no smoking like symbol while over the button. Password is copy/paste from my password manager software, so I am certain password is correct.
Before click:
![before](https://cloud.githubusercontent.com/assets/20618895/17085601/17d4b08c-51a2-11e6-93cd-65cb5bfe95ab.png)
After click:
![screenshot from 2016-07-24 13-07-51](https://cloud.githubusercontent.com/assets/20618895/17085545/bdc2cd96-51a0-11e6-8f7d-0bc6ed8ca6ee.png)

**Comment by AVellucci** [comment]
@theresthatguy Is this still an issue with the latest release(0.2.1)?
