### ISSUE TITLE
Mobile access via LAN

### ISSUE THREAD

**Issue by hoadn** [mchristopher/PokemonGo-DesktopMap#221]
I don't want to use the localtunnel.me
I found my computer ip is 192.168.1.127
Why can't i access the web using 192.168.1.127:9000
in my computer and my LAN computer?
Anyone help me please.
Thank you

**Comment by MinnesotaMiracleMan** [comment]
Agreed. I was also hoping we could host to a port by port forwarding like the original program allowed for. Having a constant address is better than hosting through ngrok or localtunnel because those links have expired on me.

**Comment by sportyguy** [comment]
@hoadn The IP address you listed is a private ip address which means it can't be used outside of your home network.  You would have to set up your router to either put your computer into a DMZ (not recommended) or set up a specific port forward from your public ip address.

**Comment by KrayZeee** [comment]
@hoadn in addition to @sportyguy there are even more problems which can ocour, like dslite which doesnt let you connect to your home pc on normalways, so you would have to switch to ipv6 which is really hard to remember or you setup a domain. but after this there are some android versions which doesnt even support ipv6. so the current implementation is the easiest way in my opinion

**Comment by mixJ2O** [comment]
Have you tried using port 8000? Just setup port 8000 forwarding on your firewall/router into your local LAN computer IP.
