### ISSUE TITLE
Not working on Windows XP?

### ISSUE THREAD

**Issue by Steevflores** [mchristopher/PokemonGo-DesktopMap#224]
Hi, 
the application doesn't work on my EEE PC running on windows XP. It says when I launch the executable : "not a valid Win32 application"

Is it normal? Am I missing something? 

Thanks in advance!

**Comment by PolarisBeaver** [comment]
Windows XP is an extremely old operating system, and even major software like Google Chrome is no longer being updated for it. Consider upgrading.

**Comment by misterpink14** [comment]
@Steevflores Electron is only supported by Win7 and later: https://github.com/electron/electron/blob/master/docs/tutorial/supported-platforms.md

**Comment by Steevflores** [comment]
Ok thanks. Well, I wanted to take that EEE PC on a road trip, and scan in real time. But I can't manage to install something newer than XP on this. Too bad :p
