### ISSUE TITLE
Accessing Map from external IP

### ISSUE THREAD

**Issue by corang** [mchristopher/PokemonGo-DesktopMap#226]
I would like to access this map from another seperate network (i.e. phone) but I do not want to use localtunnel. I have taken the time to port forward and unblock everything from windows firewall but when I try to connect I just get a connection_refused error. Anyone have any ideas?

**Comment by IMNoob1** [comment]
You can use only localhost tunnels (ngrok was used before and now local tunnel) you can use sidepoint , mom, forwardhq etc etc etc. 
many offere great secure tunneling for your localhost, Google for it.
