### ISSUE TITLE
Blank Map

### ISSUE THREAD

**Issue by Ripsurf1** [mchristopher/PokemonGo-DesktopMap#227]
The application was working a few hours ago, but now there is nothing displaying, no google map, pokemons, nothing, it says it's operational, but there is nothing. What kind of bug is it?

**Comment by samuelgnoble** [comment]
Have you made sure to check the server status on a site like ispokemongodownornot.com?

Currently Pokemon Trainer Club login is experiencing major latency.

COuld you give more information so others can try to replicate the issue of the map disappearing? 
![screen shot 2016-07-25 at 1 46 51 pm](https://cloud.githubusercontent.com/assets/13971571/17111194/6830422c-526e-11e6-8110-c656a50505e7.png)
