### ISSUE TITLE
No Pokemon

### ISSUE THREAD

**Issue by DarkriseOo** [mchristopher/PokemonGo-DesktopMap#23]
there are no pokemon on map, still after 10 minutes not

**Comment by ellisio** [comment]
The pokemon servers are down right now.

**Comment by Ruined1** [comment]
Yes the servers are going up and down for the last hour. It is not this applications fault.

**Comment by DarkriseOo** [comment]
ok thanks

**Comment by VideyS** [comment]
Can someone confirm that when the servers aren't on fire, all I need to do is open the app, login, and the pokemon will load automatically on the map.

**Comment by ferazambuja** [comment]
yes, it was working fine.

**Comment by Quikchitown** [comment]
There's no pokemon on mine either. I downloaded the file unzipped it and opened the file entered my info and the map opened with no pokemon appearing anywhere.

**Comment by Ruined1** [comment]
ONE SIMPLE GOOGLE SEARCH WOULD TELL YOU THE SERVERS ARE DOWN

https://go.jooas.com/

@mchristopher CANT DO ANYTHING ABOUT THAT.
