### ISSUE TITLE
Win-logging into updated map wont work

### ISSUE THREAD

**Issue by RiverGray** [mchristopher/PokemonGo-DesktopMap#230]
For the last days I haven't been able to see any pokemon on the map, now after deleting everything and downloading the whole newest release it now only shows nothing but a login screen that is in an almost stripped down version of the GUI, practically just the code. Now I cant figure out what to download and the what to do with it to get it to work. Is there anybody who can tell me easily how and what I need to download and then do in simple terms (since I've obviously been out of the coding biz wayyy to long apparently) to get this map back working like it was just a few days ago.

**Comment by DP9Hb** [comment]
Same here [http://s018.radikal.ru/i527/1607/61/e2331810da9e.jpg](url)
no map

**Comment by RiverGray** [comment]
exactly what I was seeing pretty much
