### ISSUE TITLE
[QUESTION] Scan Radius

### ISSUE THREAD

**Issue by PassiveModding** [mchristopher/PokemonGo-DesktopMap#233]
what does each number increment account for the detection zone
eg. 1=1km, 2=2km, 3=3km etc.

**Comment by AVellucci** [comment]
According to the scanned area image.
It looks like the radius is roughly 95m.
![capture](https://cloud.githubusercontent.com/assets/11682773/17099999/d2b76060-5239-11e6-9012-52cc0a282521.PNG)

**Comment by B00kW0rm87** [comment]
AVellucci, are you saying 1 is 95m, meaning if I put in 15, it would be 95x15=1425m or 2850m Diameter?

**Comment by AquatikJustice** [comment]
Yes, that's what he is saying

**Comment by AVellucci** [comment]
Not exactly.
95m is the radius of each scanned location. But you can see there is about a 25m overlap, so you won't get exactly 1425m radius at a RADIUS of 15, you'll lose about 20m - 25m for each added increment so the formula would be more accurate like so
`(95xn)-(25-(n-1))`
Read as 95m multiplied by your selected radius subtracted by 25m per radius after 1

**Comment by PassiveModding** [comment]
Great explanation, this is much appreciated thankyou!
