### ISSUE TITLE
No pokemon !

### ISSUE THREAD

**Issue by Onarki** [mchristopher/PokemonGo-DesktopMap#234]
Hello,

The pokemons are no more displayed in the newest version 0.10 and 0.11, but the version 0.0.7 though !

Regards,
Onarki

**Comment by samuelgnoble** [comment]
Have you made sure to check the server status on a site like ispokemongodownornot.com?

Currently Pokemon Trainer Club login is experiencing major latency.

![screen shot 2016-07-25 at 1 46 51 pm](https://cloud.githubusercontent.com/assets/13971571/17111146/45257874-526e-11e6-9025-4f53998cfa49.png)
