### ISSUE TITLE
Pokestops In mobile mode

### ISSUE THREAD

**Issue by thefaith01** [mchristopher/PokemonGo-DesktopMap#236]
I can't seem to turn off Pokestops in mobile access.
It goes off for a seconds but when i start using the map. they all pop up again.

On Chrone PC and my phone. Samsung S6

**Comment by CelloDE** [comment]
Turn off Pokestops and refresh the page, worked for me.

**Comment by thefaith01** [comment]
That works for me too!
Thanks mate
