### ISSUE TITLE
POKEMON NOT LOADING

### ISSUE THREAD

**Issue by unknownss** [mchristopher/PokemonGo-DesktopMap#237]
Hi there are no pokemon loading for version 0.1.1

**Comment by CalyPhornia** [comment]
I have the same problem. "Waiting" appeared. Maybe the servers busy?

**Comment by AVellucci** [comment]
this looks like it's due to PTC being down/unstable, try with a Google account and it should load and become "operational"
![ptc](https://cloud.githubusercontent.com/assets/11682773/17108051/e0241d76-525f-11e6-950b-c6e6a1bcd06f.PNG)

**Comment by taylorreece** [comment]
@AVellucci ^ What website is this screenshot from?

**Comment by AVellucci** [comment]
@taylorreece it's from here: [is PokemonGo down or not](http://ispokemongodownornot.com/)

**Comment by unknownss** [comment]
yes it works with the google account thanks

**Comment by AVellucci** [comment]
@unknownss If this solved your problem can you please close the issue.
