### ISSUE TITLE
 Help with problems

### ISSUE THREAD

**Issue by hellforyou** [mchristopher/PokemonGo-DesktopMap#238]
<a target="_blank" href="http://radikal.ru/big/bf3ff3cb63dd497086af7aa1ad6ea1cd"><img src="http://i062.radikal.ru/1607/a9/c7c39ee686f4.jpg" ></a>

**Comment by kdichev** [comment]
looks like you are missing some files. Try to download again

**Comment by hellforyou** [comment]
Download file "PokemonGoMap-Win.zip" . Or you need something else?

**Comment by taylorreece** [comment]
Did you unzip the directory before running the .exe, or did you just run the .exe?

**Comment by hellforyou** [comment]
Of course, I Extract

**Comment by hellforyou** [comment]
I myself found the problem. Just I am from Russia and I have been named folder in Russian ... I changed to English and helped
