### ISSUE TITLE
Mobile map disappears after a while

### ISSUE THREAD

**Issue by XxMaster1919** [mchristopher/PokemonGo-DesktopMap#239]
Hi, 
i am running the desktop App on a Macbook. because i dont want to carry it with me while catching pokemon i tried using the "mobile version". It works fine but after a few minutes the map disappears on the phone and it says: "no active client for '...' " 
but on the macbook its still running. what can i do?

I am using Google Chrome on the Phone to open the link i get from the desktop app.

**Comment by Mirx** [comment]
Localtunnel is not up to par. I switched back to version 1.0 because the mobile tunnel is much more reliable.

**Comment by kaitlynhansen** [comment]
Can someone please explain to me how I can download it on my moblie?

**Comment by Mirx** [comment]
You can't run it natively on your phone, but you can transfer the map view running on your PC to your mobile. Your PC will need to remain on.

In the right top, click "Mobile", then click "toggle Sharing", and the open the URL on your mobile.

**Comment by XxMaster1919** [comment]
I tried the 1.0 version and it works fine, probably gonna use this till the bug with "localtunnel" is solved.
