### ISSUE TITLE
Errors in console: no pokemon

### ISSUE THREAD

**Issue by pyrex** [mchristopher/PokemonGo-DesktopMap#24]
![win 0 0 3 errors](https://cloud.githubusercontent.com/assets/1911618/17001860/00e94816-4e86-11e6-8cc6-00c0208533d9.png)

NameError: Global name 'errno' is not defined

Could it be related to the PTC portal being overloaded?

**Comment by DarkriseOo** [comment]
i'm using gmail, still doesnt working....

**Comment by DarkriseOo** [comment]
ok, its because the server are down right now

**Comment by sainar** [comment]
same error. servers are already working. I have windows
