### ISSUE TITLE
[ Request ] Remove pokemon from map after catching it

### ISSUE THREAD

**Issue by TehJokeR** [mchristopher/PokemonGo-DesktopMap#240]
It would be nice to be able to click and delete a pokemon from the map once you've caught it so we can keep track over time of what to get and what not to get. - Specific instances, not hide the pokemon completely.

**Comment by heyjonmanning** [comment]
I'd prefer for the Pokemon to stay on the map, even after caught. If someone else comes to the spot you can tell them how much more time until it despawns and exactly where it is.

**Comment by TehJokeR** [comment]
It would be optional, to click and remove it from the map
