### ISSUE TITLE
HELP

### ISSUE THREAD

**Issue by biokovo** [mchristopher/PokemonGo-DesktopMap#243]
Can someone please explain how do i connect with my phone?

**Comment by CelloDE** [comment]
After you click the "toggle sharing" button there should be a QR code and a link after a few seconds.

**Comment by heyjonmanning** [comment]
Download the app "Barcode Scanner" on Android if you need something to scan the code. Or it shows you the URL under the code that you can just manually type into your browser on your phone.

**Comment by mixJ2O** [comment]
There may a problem with localtunnel.me, it does stop working after a while for me. I've just mapped port 8000 in my router/firewall and used my public ip for now..
