### ISSUE TITLE
Change your location doesn´t work anymore

### ISSUE THREAD

**Issue by micomete** [mchristopher/PokemonGo-DesktopMap#245]
Hi, first times the function Change your location worked fine for me.But now if i type in a adress nothing happend.I use an google account.Somone with the same issues or maybe a workarounf to fix it?

**Comment by aschnebe** [comment]
This is my first time using this, but I can't get location to change either. I type in a location, hit enter, and nothing changes. There's not submit/search button, so I don't even know if I'm doing it right.

**Comment by heyjonmanning** [comment]
For now, it seems like it's not working. Just log out, change location and log back in. Doesn't take very long and accomplishes the same thing. Your settings for hide/notify should be saved.

**Comment by onlyforhabitica** [comment]
Even easier, just flip the filter switches off and on again and they reappear.

**Comment by StephanBijzitter** [comment]
Also suffering from this
