### ISSUE TITLE
It stops scanning after a while

### ISSUE THREAD

**Issue by giola97** [mchristopher/PokemonGo-DesktopMap#247]
Well, I don't know if it's normal or not, but after a while, usually 20-30 minutes, the program stops scanning the pokemons nearer to the marker and only scans those that are at the edge of the radius. Then it completely stop scanning. Can I solve it somehow?

**Comment by AquatikJustice** [comment]
Are you signing in with a Google account?

**Comment by giola97** [comment]
Yes I am

**Comment by AquatikJustice** [comment]
Google logins time out after 30 minutes. If you want it to stay logged in and refresh indefinitely, create a PTC account and log in using that. There will be no difference between the two as far as seeing Pokemon on the map goes.
