### ISSUE TITLE
Mac osx no pokemon appear

### ISSUE THREAD

**Issue by Cameronday14** [mchristopher/PokemonGo-DesktopMap#25]
I open the map on my mac and it gets my location and I can see everything but, no pokemon are appearing on the map. I do not know why this is doing it could I please get some help.

**Comment by ding-kan** [comment]
Pretty sure Niantic servers are down. I checked the actual app and it was stuck at the ol' 25%. Correct me if I'm mistaken.

**Comment by Cameronday14** [comment]
even when the servers where up there where no pokémon

**Comment by ferazambuja** [comment]
It was working before. The API seems to be down...

**Comment by ashworthca** [comment]
It was working fine on my mac book pro today.  It would have been a server issue after they updated the app mobile app to 1.0.3

**Comment by Cameronday14** [comment]
what osx are you guys running @ferazambuja @ashworthca @ding-kan

**Comment by yaleman** [comment]
I'm having similar issues, got this in the logs:

```
python ./example.py --auth_service google --token *removed* --location -27.414719899999998,153.03849309999998 --auto_refresh 10 --step-limit 7 --display-gym --port 8000 --parent_pid 39709
Python: usage: example.py [-h] [-a AUTH_SERVICE] [-u USERNAME] [-p PASSWORD]
                  [-t TOKEN] -l LOCATION -st STEP_LIMIT [-i IGNORE | -o ONLY]
                  [-ar AUTO_REFRESH] [-dp] [-dg] [-H HOST] [-P PORT]
                  [-L LOCALE] [-ol] [-c] [-pm] [-d] [-pid PARENT_PID]

Python: example.py: error: argument -l/--location: expected one argument
```

I'm having trouble logging in to the app at the moment, running El Capitan. 

Maybe the location needs to be quoted?

**Comment by yaleman** [comment]
Just tested running this from the commandline, it seems to be an issue with example.py's parsing of arguments

**Comment by Cameronday14** [comment]
its not tracking locations for me right now and no pokemon are appearing. I am running el capitan version 10.11.5

**Comment by ferazambuja** [comment]
El Capitan 10.11.6
It's working for me now as long as I type my location at the start.
Nothing happens on the app if I input a new location and set.

Keep constantly getting this errors:
[-] retrying_api_req: request error (Unexpected end-group tag.), retrying

**Comment by yaleman** [comment]
It's the comma-split location that's doing it. If you run 

```python example.py -l "123"```

It works, but 

```python example.py -l "123,123"```

 doesn't - as it's trying to associate it as an array or something

**Comment by Cameronday14** [comment]
in terminal, I am sort of new to this I just started coding java. @yaleman

**Comment by yaleman** [comment]
@Cameronday14 my comments were more for @mchristopher :)

**Comment by ashworthca** [comment]
@Cameronday14  I am running 10.11.5 (15F34).

**Comment by mchristopher** [comment]
@yaleman Can you change line 173 in main.js from:

    lat + ',' + long,
to this:

    parseFloat(lat).toFixed(7) + ',' + parseFloat(long).toFixed(7),

and let me know if that fixes it?

**Comment by yaleman** [comment]
Still getting the exact same error

**Comment by mchristopher** [comment]
@yaleman What version of python do you have? What's the output of `python --version`?

**Comment by yaleman** [comment]
$ python --version
Python 2.7.10

**Comment by mchristopher** [comment]
Ah, I think I figured out the problem. Replace lines 172-173 with:

      '--location=' +
        parseFloat(lat).toFixed(7) + ',' + parseFloat(long).toFixed(7),

**Comment by yaleman** [comment]
Yep, that makes it work fine now1

**Comment by mchristopher** [comment]
Cool. Version 0.0.6 includes that update, so you should be good to go!

**Comment by yaleman** [comment]
Confirmed v0.0.6 works perfect
