### ISSUE TITLE
Export Pokestop and Pokegyms to PDF

### ISSUE THREAD

**Issue by EstebanVargas10** [mchristopher/PokemonGo-DesktopMap#256]
It would be nice.

**Comment by mixJ2O** [comment]
Hi @EstebanVargas10 I agree but the Pokemon do expire, would you be using this just for the Pokestops and Gyms?

**Comment by EstebanVargas10** [comment]
Thanks for answering!
 Yes, I scanned almost all my country. I update the app and everything disappeared. It would be nice to save the Pokegyms and Pokestops and later be able to download the map in PDF of something. So there's no necessary to scan everything again.

Thanks for your time :)
