### ISSUE TITLE
Where does the desktop app keep its settings?

### ISSUE THREAD

**Issue by 93732** [mchristopher/PokemonGo-DesktopMap#257]
How do I clear the "cache" of the login page?  For example, the user name/password/GPS coordinates and the search distance are saved on my Mac OS X and load every time I launch the app.  I tried to clear my safari cache (in OS X) but these settings still show up when I open the app.

**Comment by climardo** [comment]
Here are a list of the files. See beneath files names for directory. 
<img width="787" alt="screen shot 2016-07-26 at 4 08 27 am" src="https://cloud.githubusercontent.com/assets/19438277/17130473/ae452d86-52e6-11e6-9eda-fdf82c323621.png">

**Comment by 93732** [comment]
Great, thank you!
