### ISSUE TITLE
no pokemon no scans

### ISSUE THREAD

**Issue by slaugbr1** [mchristopher/PokemonGo-DesktopMap#258]
so it was working fine and adter i downloaded 1.2 i made a key and logged in normally. However just the pin drops to the location i put it i even clicked show cans nothing happens it just sits there no scaning no pokemon and the refresh doesnt do anything

**Comment by Onarki** [comment]
Same

**Comment by sonte** [comment]
I am having the same issue on multiple computers and using different ptc accounts.
