### ISSUE TITLE
On which port does the server run?

### ISSUE THREAD

**Issue by vincentcox** [mchristopher/PokemonGo-DesktopMap#260]
I see this in the GUI:
<img width="538" alt="screen shot 2016-07-26 at 07 52 09" src="https://cloud.githubusercontent.com/assets/9286611/17127434/dda5b19e-5305-11e6-9a38-00c750e66da5.png">
Does this mean that it's open on a certain port?

**Comment by vincentcox** [comment]
It appears that it's port 8000

**Comment by thegm90** [comment]
Vince - what's the full URL for accessing the server option then? Any tips :)

**Comment by vincentcox** [comment]
On your computer it's: http://localhost:8000
For outside your network it's: the IP you find on here: http://ip4.me/
For example: http://28.23.222.12:8000
However, if you want to allow people from outside to acces the map, you have to use portforwarding on your router to allow people to reach your computer. Unfortunately I can't help with that configuration because every router has a different GUI.

**Comment by thegm90** [comment]
Thanks man. Trying to configure to run within https://github.com/istornz/iPokeGo But, this isn' working for me... Any tips?

**Comment by vincentcox** [comment]
Wow, thats an interesting project. Thanks for linking up.
I think (and don't take my word for it) that this repo uses a slightly different implementation than this repo: (https://github.com/AHAAAAAAA/PokemonGo-Map).
If you look at https://www.reddit.com/r/pokemongodev/top/, you can see this:
<img width="730" alt="screen shot 2016-07-26 at 08 53 55" src="https://cloud.githubusercontent.com/assets/9286611/17128643/8bbfe47c-530e-11e6-828f-b257331621ff.png">
So I suspect that there is a certain difference between the backend code. Maybe you can start a new issue (this one is closed and will not be seen by the developer), so you get a response by the dev himself.

**Comment by vincentcox** [comment]
Wait, there is one thing we can test.
So if you run the app on your computer, which ip address do you use for the ios app?
If you are testing it inside your network, you have to search your internal ip (https://www.youtube.com/watch?v=HsCD7hUlSjk) and use that

**Comment by thegm90** [comment]
That APP is great! A little hard to get going, for my newbie self.. But really great! Just need to get the server right. My brother is making a server, but he's asleep and hasn't migrated the system to run on his NUC which we use for our PLEX, so it'll run 24/7. UGH! hah. Fairly certain his port will work, just wanted something to test the app with tonight.

Tip for loading that app, if use do... Make sure you input your iTunes id as your dev id. Not sure how experienced you are, but hopefully this is helpful. These projects are awesome!

**Comment by thegm90** [comment]
Technically, this is working(my ip:8000) I can't tap to change position though, which I thought was to be a feature?
