### ISSUE TITLE
Start scanning from the outer ring, instead of the center

### ISSUE THREAD

**Issue by StephanBijzitter** [mchristopher/PokemonGo-DesktopMap#261]
Pokémon have timers, which can sometimes be a bit short.

Now, if I have 6 minutes to get to the other side of the city for a Dragonite, but it would take a scan 4 minutes to even scan that section, I'll only have two minutes left. As such, the scan should propagate inwards, instead of outwards. This will allow the user more time to get those far-away Pokémon quickly.

I could open a PR, if wanted.

**Comment by JamesA27** [comment]
I disagree with this, but maybe it can be an optional feature.  Let's say a Lapras spawns two blocks away from you with a 2 minute timer (literally just happened to me today).  You want to know about this.  Most people don't want to go across the city and would want to be notified about the close ones as soon as possible.
