### ISSUE TITLE
Map is just shown for a split of a second

### ISSUE THREAD

**Issue by pWnH** [mchristopher/PokemonGo-DesktopMap#263]
```
Error: Cannot call loadURL because the webContents is unavailable. The WebView must be attached to the DOM and the dom-ready event emitted before this method can be called.
    at webview.loadURL (C:\Users\xxx\Downloads\PokemonGoMap-Win (1)\resources\electron.asar\renderer\web-view\web-view.js:409:15)
    at serverUp (file:///C:/Users/xxx/Downloads/PokemonGoMap-Win%20(1)/resources/app/main.html:195:21)
    at EventEmitter.<anonymous> (file:///C:/Users/xxx/Downloads/PokemonGoMap-Win%20(1)/resources/app/main.html:158:9)
    at emitTwo (events.js:106:13)
    at EventEmitter.emit (events.js:191:7)
```

**Comment by aldder** [comment]
same issue

**Comment by Taitaka** [comment]
Same here, i receive this message:

Oops! Something went wrong.
This page didn't load Google Maps correctly. See the JavaScript console for technical details.

**Comment by pWnH** [comment]
Ya, somehow it is working now for me

**Comment by cgpoondy** [comment]
Did you change anything or did it just work out fine after some wait?

**Comment by pWnH** [comment]
It worked after like 10 minutes of waiting and trying different API keys. In the end it worked with the first Browser API-Key i got.

**Comment by cgpoondy** [comment]
Need to test it out a bit i guess. doesnt work the time being tho.

**Comment by cgpoondy** [comment]
Got the solution apparently. 

You need to go to your dashboard where you create your API and enable the Google Maps API for JavaScript option. It was not enabled at the time i was created the API. 

After you enable it, it should work just fine.

p.s.: might be a bit of a beginner mistake but bear with me. :)

**Comment by rdthp** [comment]
I enabled it. Still same thing

**Comment by rdthp** [comment]
Works after restarting the .exe twice

**Comment by topboybat** [comment]
Doesn't work for me :/ I've enabled Google Maps API for Java and restarted but nothing has changed. Any suggestions?

**Comment by aldder** [comment]
Finally i solved using another google account!!
1) create new project
2) enable Google Maps Javascript from Dashboard
3) create new credential (Browser key)

**Comment by RiverGray** [comment]
ok I got it to the point where it disappeared after a second and then playing thru diff things this thread touched on I FINALLY have my map back! Hope it lasts this time! lol

**Comment by pokema** [comment]
how do you enable the javascript api?
