### ISSUE TITLE
Neccessary to have a API Key?

### ISSUE THREAD

**Issue by tarroyo8** [mchristopher/PokemonGo-DesktopMap#265]
I was using the app on OSX earlier and me being impatient seeing the 'waiting' message rather then being logged in right away, I quit then launched again. Now whenever I try logging in I get the 'Invalid Google Maps API key. Please follow instructions to set API key before login.'

I don't remember seeing this message when I installed PokemonGo, Was there a default key? I don't wanna have to go thru the steps to assign myself a key if its not needed.

**Comment by climardo** [comment]
I haven't found a way around the key with the current version 0.1.2, there was no default key in the field.

**Comment by ranrinc** [comment]
The new version require you to have your own Google API. the reason because the used of API have limits, this way eventually it will expired. So follow the instruction and get your own Google API.

**Comment by AVellucci** [comment]
@tarroyo8 There is a new field requiring you to generate your own API key with a link on how to do so.
The reason for this is that the API key that was defaulted in previous versions was getting over loaded.
It's a simple procedure to generate your own key and should take you no more than 10 minutes.
If you have already got this working would you mind please closing this issue?
