### ISSUE TITLE
Nothing showing up

### ISSUE THREAD

**Issue by onlyforhabitica** [mchristopher/PokemonGo-DesktopMap#268]
Apologies if this has been addressed earlier, but this new update is just not working for me.

I've made a Google API key, put it in where it needs to be, logged into google, and...nothing. It works fine on the older versions, but for some reason this version doesn't work.
http://i.imgur.com/2qWF5mN.png
http://i.imgur.com/HLoI31p.png (I promise I put in the google maps API key correctly)

Any help?

**Comment by CanadianToast** [comment]
Click "Filter" Toggle the settings.

**Comment by onlyforhabitica** [comment]
Lol, didn't notice that Pokemon switch the first time. Ughhhh.

Thanks @CanadianToast
