### ISSUE TITLE
[Mobile Error] "No active client for ' ' "

### ISSUE THREAD

**Issue by CanadianToast** [mchristopher/PokemonGo-DesktopMap#269]
Mobile links give error "no active client for 'xvsptlumnt' after a certain amount of visits to the page.
This seems to happen after a certain amount of time OR when you have more than 2 devices accessing the mobile link.
 
('xvsptlumnt' is the unique url from localtunnel.me, and I know it changes with every new share.)

**Comment by marcspc** [comment]
having same problem

**Comment by Anden1980** [comment]
Same here

**Comment by domuk** [comment]
Same problem here, map url seems to expire and stop working after 3-6 minutes.

**Comment by mixJ2O** [comment]
Yeah, I get the same problem. Why don't you just use your local IP and connect to port 8000 for now? You'll have to map the ports in your router/firewall but that's easy then just connect in using your public IP or something like dyndns.

**Comment by CanadianToast** [comment]
Should go back to ngrok.io

**Comment by XxMaster1919** [comment]
same here

**Comment by 3ClawedLobster** [comment]
Having the same problem
