### ISSUE TITLE
Settings Coordinates Doesn't Move Map?

### ISSUE THREAD

**Issue by jameson167** [mchristopher/PokemonGo-DesktopMap#27]
Hey I really appreciate you putting in the time to work on such a great project for the community. I was testing out the WIN version and was trying to manually type in coordinates and click "Set" and nothing would happen on the map. It would prompt a "GET" /next_loc with the coordinates I typed but I don't see any response. Is this simply for loading the pokemon and we just have to manually move the actual visual map? Is it just not working because of the server issues with niantic currently? Thanks!

**Comment by ahack90** [comment]
It is not locating me properly saying i am in California and will not let me set location. Also Pokemon do not seem to be appearing on this map? Am i doing something wrong?

**Comment by ahack90** [comment]
The servers seem to be up as well checked the google servers, login on mobile is working

**Comment by drgfir** [comment]
I know it is probably a pain to do this but for now you can relocate map pin by restarting program and manually type in coordinates at bottom of login window,....( use google maps to get location coordinates, put coordinates in program then login.
