### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by Onarki** [mchristopher/PokemonGo-DesktopMap#270]
Hey, i'm using the latest version 0.1.2, i'did generate a google maps key, when i tried to login using PTC or google account no pokemon is scanned (pokemon scan is active on the filer) but only gyms and pokestops are scanned, is there any solution for this ?

ps : I don't have this problem using the version 0.0.7

**Comment by AVellucci** [comment]
Lets cover some obvious ones first.
When you start the scan does it say it's "Operational"?
Have you tried disabling and re-enabling the Pokemon filter?
If you enable the Scanned location filter does it show the area being scanned?

These are some of the more common reasons as to why you may not see pokemon appearing.

**Comment by Onarki** [comment]
Take a look to the captures below :

Version 0.1.2 :
![capture](https://cloud.githubusercontent.com/assets/9077920/17142308/3297e882-533f-11e6-872a-350f9fa8a588.PNG)

Version 0.0.7 :
![capture2](https://cloud.githubusercontent.com/assets/9077920/17142418/96352e7c-533f-11e6-955b-08d5e4776414.PNG)

And yes i tried to enable disable the pokemon filter and nothing happens.

**Comment by AVellucci** [comment]
Could be maybe it wasn't unzipped correctly or had an error when it was unzipped.
Maybe the pokemon sprites are missing, are the sprites found in this folder? `\resources\app\map\static\icons`
Try redownloading the zip and extracting it again to see if that corrects the issue.

Or if you have a log file that might shed a little more light on this.

**Comment by Onarki** [comment]
The sprites exists in this location "\resources\app\map\static\icons", i tried redownloading and extracting and still the same probleme, and with version 0.1.1 as well.

Where can i find the log file ?

**Comment by Onarki** [comment]
It is working on mac os but not windows (windows 7), any suggestions ?
