### ISSUE TITLE
Oops! Something went wrong.

### ISSUE THREAD

**Issue by jetjmu** [mchristopher/PokemonGo-DesktopMap#274]
Since installing 0.1.2 I'm not able to access the map. I followed the instructions to display the API key, pasted into the application, then get an error message once the map displays. It appears to load at first for half a second, then a grey error screen appears with the message:

"Oops! Something went wrong.
This page didn't load Google Maps correctly. See the JavaScript console for technical details."

(Happy to paste the JavaScript console but I'm not sure how to access it...)

**Comment by BitBoxGaming** [comment]
I am getting the same error.

Here is the error from the console:

`Error: Cannot call loadURL because the webContents is unavailable. The WebView must be attached to the DOM and the dom-ready event emitted before this method can be called.(…)`

**Comment by rdthp** [comment]
same here. 0.1.1 still works

**Comment by cgpoondy** [comment]
Got the solution apparently.

You need to go to your dashboard where you create your API and enable the Google Maps API for JavaScript option. It was not enabled at the time i created the API.

After you enable it, it should work just fine.

**Comment by rdthp** [comment]
Enabled Google Maps Javascript API. Still doesnt work

**Comment by rdthp** [comment]
working now. had to restart and refresh.

**Comment by rickyb823** [comment]
Same error here. Enabled the JavaScript API and tried to restart and refresh with no luck. Anyone have any other ideas?

**Comment by aldder** [comment]
Finally i solved using another google account!!
1) create new project
2) enable Google Maps Javascript from Dashboard
3) create new credential (Browser key)
