### ISSUE TITLE
Download

### ISSUE THREAD

**Issue by PokemonCindy** [mchristopher/PokemonGo-DesktopMap#275]
Do I have to download Zip and Source code?

**Comment by DarkriseOo** [comment]
no

**Comment by PokemonCindy** [comment]
Thanks man :)

**Comment by XxMaster1919** [comment]
no, just the operating system you use. 
Linux, Windows or OSX

**Comment by AVellucci** [comment]
@PokemonCindy If this issue has been resolved for you please close this ticket.
