### ISSUE TITLE
bug notification

### ISSUE THREAD

**Issue by DarkriseOo** [mchristopher/PokemonGo-DesktopMap#276]
every 5 seconds the tiny window pops up : A wild ....... appeared! 
but there is nothing , its bugging. If I close the application it still goes on!

**Comment by mclucario** [comment]
Same here. Using in Windows 10 64-Bit

**Comment by rah913** [comment]
I'm experiencing the same issue on OS X with the new client.

**Comment by mclucario** [comment]
Removing and adding the "spamming" Pokémon to the notification list fixed it.

**Comment by rah913** [comment]
I've tried that and it doesn't fix it. Notification continues to spam.

**Comment by mclucario** [comment]
Yep. it keeps going.

**Comment by ranrinc** [comment]
I post the bug earlier...

**Comment by neutron666** [comment]
for me the notifications don't work at all..

**Comment by jhliberty** [comment]
+1
