### ISSUE TITLE
[Suggestion] Set Custom Location Grid 

### ISSUE THREAD

**Issue by ryukomell** [mchristopher/PokemonGo-DesktopMap#277]
I only want a small area scanned, the area it scans is far too large for what I need, is it possible to make it where I can reduce the size and just make my own circles to scan?

**Comment by AVellucci** [comment]
Currently the scanner can only scan in a hexagonal field. if the area is too large reduce the RADIUS from the default to a lower number before logging in. It is on the log in screen.

**Comment by ryukomell** [comment]
I put it at 0 and 1.  The grid is still the same size, but the outter colors are now more yellowish(though all the pokemon are still on there, though maybe it's left over from the previous scan).  Did I mess up?

**Comment by ryukomell** [comment]
Yeah, looks like they are all disappearing now, so that works.  The lower I set it, the less google map pings it uses of my limit, correct?

**Comment by AVellucci** [comment]
From what I can see, it keeps the request open after the initial ping so it shouldn't use more than one request per login. I could be wrong about this though.

**Comment by ryukomell** [comment]
Cool, thanks for the help :)
