### ISSUE TITLE
[Suggestion] Text Pokemon Notifications to us.

### ISSUE THREAD

**Issue by ryukomell** [mchristopher/PokemonGo-DesktopMap#278]
I was using another map app that a guy made(am I able to post the github link, or will that be frowned upon?) that would post the locations to twitter and then the tweets would be texted to me.  It was set up for just my small little area, and it works well, but having a visual map like this is really nice, but I do miss the text notifications.

**Comment by AVellucci** [comment]
I'd be okay with an update that uses PushBullet or a script that hooks to the ADB shell or a Twitter feed.
Any of those options would be nice.

**Comment by ryukomell** [comment]
Nice, very happy to hear that.
