### ISSUE TITLE
Servers working the app isnt? 

### ISSUE THREAD

**Issue by SmilinItalin** [mchristopher/PokemonGo-DesktopMap#28]
I want to say thank you for you all taking the time to do this. I had a blast learning last night, it was working flawless. The servers been down most the day. 
1. I saw vs 3 was out downloaded it..... and it was giving a bunch of script errors......and wasnt working. (think you got that figured out because of vs 4
2. no more script errors....... but the app is not working (as in showing pokemon
3. more a curiosity question...... i noticed in the maps you do have icons for the rarer pokemon, and when i was using it last night never saw really anything past a 2nd evolve ....does it not show them or is it just not around my location.

Thank you again

**Comment by Ruined1** [comment]
https://go.jooas.com/

**Comment by SmilinItalin** [comment]
LOL ya they was up when i posted it. But crashed soon after. :( This is a new one i found http://ispokemongodownornot.com/
