### ISSUE TITLE
[Suggestion] Removing scan locations from the active scan

### ISSUE THREAD

**Issue by mygo89** [mchristopher/PokemonGo-DesktopMap#281]
By scanning an area and then disabling some scan locations for the next and future scans.
I know some dead zones where nothing ever is, and removing them from the scan would be great if it made the next scan faster by skipping them.

**Comment by AVellucci** [comment]
This would be really nice to have, especially if it sped it up even by a second or two.

**Comment by AquatikJustice** [comment]
This would be nice. I live in an area with a lot of snobs in their gated communities and it always sucks when I'm tracking something I have been on the lookout for and I get denied by a gate and a guard.

**Comment by pill0ws** [comment]
Yea, it would be very cool to remove deadzones from the scanner. This would probably have to be tagged to the starting location as the search zones are always calculated from that point specifically. I had previously thought that id some kind of grid were established it would allow for creating lists of areas that could then be blacklisted. Currently the app takes a starting location exclusive for each app instance, there would probably need to be a common grid of search nodes shared by all of the clients before a blacklist could be used by all of them. 6 clients seems to be the limit though I've logged in with multiple accounts with the same limit so I dont think its PTC timing you out, its something in the client that causes errors after 6 clients.

**Comment by AVellucci** [comment]
If anything, it'd be nice to be able to incorporate a black list using polygon coordinates and then have the community manage it instead of having the dev do it.

**Comment by mygo89** [comment]
Doesn't current scan count as a grid. if you View scanned locations you actually see circles going in clockwise direction.  would just need the option to disable some circles manually
