### ISSUE TITLE
port 8000 login

### ISSUE THREAD

**Issue by Dravenfilth** [mchristopher/PokemonGo-DesktopMap#282]
When I set up my port forward and thank you it works amazing on the newest version 4 hours straight no bumps. Is there a way I can password protect http://"myip":8000 ? So instead of ij just showing the map it prompts me for some type of authentication.

**Comment by AVellucci** [comment]
A login would need to be coded into the page for this feature.
You could either make one yourself or wait for one if it ever happens.

**Comment by Dravenfilth** [comment]
so create script for authentication, download source, insert said authentication script compile......looks like i have some research to do tonight.

**Comment by AVellucci** [comment]
If you get one working maybe fork the project and request the commit be added to this project.
It'd be nice to have as a feature we can enable disable at will when we first log in.
