### ISSUE TITLE
No pokemon after program is open for a while

### ISSUE THREAD

**Issue by BitBoxGaming** [mchristopher/PokemonGo-DesktopMap#283]
When the map has been open for a while, the pokemon will stop refreshing and in the end, no pokemon will be displayed on the map, even though there are pokemon around (I check on other apps)

**Comment by AVellucci** [comment]
Are you using PTC or Google Login?

**Comment by BitBoxGaming** [comment]
I am using Google Login.

This issue also occurred in previous versions.

**Comment by Dravenfilth** [comment]
google accounts have an auto time out from what I have read, switch to a PTC account and re-try

**Comment by AVellucci** [comment]
Please see this issue #247 
If this answers your query please close this ticket afterward.

**Comment by BitBoxGaming** [comment]
Thanks
