### ISSUE TITLE
Mobile share doesn't scan 

### ISSUE THREAD

**Issue by giola97** [mchristopher/PokemonGo-DesktopMap#284]
Well, my roblem is simple. Whenever I share my map with a mobile it just makes me see the pokemons that were on the map in the moment I wired it and never scans new pokemons .

**Comment by StephanBijzitter** [comment]
At least you still see something, I just see the scanned locations highlighted without the pokemon ;-)

**Comment by AVellucci** [comment]
What version are you running?
Can you provide steps to reproduce?

**Comment by Hearttless** [comment]
if you're using version 0.1.2, did you check the box at the bottom that said something like "enable server"? because that should work.

**Comment by rhawley88** [comment]
so with mobile you have to enable in the filter to see pokemon mine was off after scan or to show searched field.  once you do that you should be able to see pokemon or your scanned ara
