### ISSUE TITLE
[Bug]Non existing Pokémon appear

### ISSUE THREAD

**Issue by gonjiak** [mchristopher/PokemonGo-DesktopMap#285]
Sometimes pokémon appear at random spots which doesn't exist (checked it with other tools). They always have a low time counter, mostly around 2:20.

**Comment by AVellucci** [comment]
By checking it with other tools do you mean that it appears on all tools, or just on this app?

**Comment by gonjiak** [comment]
just this app, if an area get scanned, they appear close to the scanned area. In the screenshot attached you can see it. magnemite and poliwag popped up as the area under them got scanned.
![screen](https://cloud.githubusercontent.com/assets/20668938/17155386/28e5a748-5385-11e6-82bd-b0145a933c60.jpg)

**Comment by AVellucci** [comment]
if they popped up while the area underneath was being scanned then they might actually be in the scanned area, it could be placing the images in the wrong place.
Also I could be wrong but the coordinates also don't translate to the correct location either. not sure if changed them on the image before posting it or not.

This may be a valid issue with incorrect pokemon showing up in the wrong places.

**Comment by StephanBijzitter** [comment]
On a sidenote, three squirtles and a wartortle, you're a lucky man

**Comment by gonjiak** [comment]
At least according to google maps the coordinates are correct, haven't edited them. But I noticed that every false message have either a shorter coordination length or a 

lot of same digits in a row. I checked all pokemon around the location with other apps, I didn't found them. 

![screen](https://cloud.githubusercontent.com/assets/20668938/17188022/cfdb08d4-543b-11e6-8a19-89648be92377.jpg)

@StephanBijzitter I just have squirtles here, not a single charmander or bulbasaur..

**Comment by minim8** [comment]
I can confirm this problem. I thought it was just because of the bad update rates that I see all of them with only 2min 45secs left after they appear on the app, but I checked other scanning Apps as well and none of these specific "3 min pokemons" where to be found there.
