### ISSUE TITLE
[REQUEST]Proxysupport

### ISSUE THREAD

**Issue by KrayZeee** [mchristopher/PokemonGo-DesktopMap#287]
Since i am a little bit paranoid im currently using a VPN at home when i am starting this application, so the chances are even smaler getting caught. i am using a fake account for this but when pogo and this tool connects daily through the same network im getting a little bit scared.

but in the end i want to let other people use my pc when i am out and so having to turn VPN off then since i have limited traffic and diffenrent other reasons. so it woukd be realy nice to let the scanningApp to run through a proxy.

is it implementable or are there any other ways to achieve this?

are my concerns reasonable or am i just getting to nervous about this?

**Comment by AVellucci** [comment]
Currently IP banning is not a thing for PokemonGo, nor Ingress, Niantic's previous app that has the same system. There is always a chance it may be a thing at some point but right now it does not look like it's going to happen.
Implementing an option to use a proxy could be possible I believe.
