### ISSUE TITLE
Repeating Notifications

### ISSUE THREAD

**Issue by ltramsey09** [mchristopher/PokemonGo-DesktopMap#289]
I'm having an issue with notifications for pokemon repeating multiple times for the same instance. I had notify on for Pikachu and several others and it was the only one effected. Turned off notifications for Pikachu and then the repeating notifications for Poliwrath began. Not sure if it is specific for those selections or what.

macOS 10.11.6

**Comment by StephanBijzitter** [comment]
I got the same issue with the latest OS X version, since the latest update today.

**Comment by EstebanVargas10** [comment]
Me too

**Comment by aiham** [comment]
It also looks like the Pokemon that you're being notified about appear on the map the first time then disappear after subsequent notifications. I think you get a repeat notification for every scan step.

**Comment by wordymcword** [comment]
I got this problem and got it to stop when I took off the pokemon that aren't in the game off my notify list. (Mew, mewtwo, ditto, birds, region locked ones) Hope that helps you.
