### ISSUE TITLE
map NO Loads

### ISSUE THREAD

**Issue by Lowerman** [mchristopher/PokemonGo-DesktopMap#29]
Sorry my bad english, map NO Loads, 
map is white  , Windows 7 Ultimate x64

**Comment by DarkVamprism** [comment]
I have the same problem, is there any prerequisite programs we need installed?

**Comment by kogot** [comment]
I have a same issue. Even tried on different pc

**Comment by breandr** [comment]
I think this is for negative lat/long values

**Comment by Lowerman** [comment]
This is sad : /

**Comment by Lowerman** [comment]
Breandr, What I think not even with the Default Location map not run !

**Comment by Lowerman** [comment]
Version 0.0.6 correct me, but the set button still does not work, thank you!
