### ISSUE TITLE
Mobile connect problem

### ISSUE THREAD

**Issue by MatthiasDING** [mchristopher/PokemonGo-DesktopMap#292]
When I try to connect this map program using my iphone6 by scanning the code, It always give a response "No active client for XXXXX".  What happened to me? Have I made some mistakes?

I have tried both window and linux version.

**Comment by rhawley88** [comment]
make sure you have server selection enabled

**Comment by MatthiasDING** [comment]
I'm sure that I have selected the option Server Enabled.

**Comment by MatthiasDING** [comment]
Now ip：8000 works on linux.
