### ISSUE TITLE
Can not log into PTC [Linux]

### ISSUE THREAD

**Issue by darkforcesjedi** [mchristopher/PokemonGo-DesktopMap#296]
If I log in using a google account the application works fine (other than timing out after 30 minutes as mentioned in other discussions). However, when I try to log in using a PTC account with the "Remember Login" checked, the login buttons become disabled and nothing else happens.

It seems to work if I uncheck that option.

Edit: I logged out and I have not been able to get it to log back in again.

**Comment by darkforcesjedi** [comment]
Another update, I tried it on Windows and logging into PTC seems to work reliably. Seems to be specific to the Linux build.

**Comment by dinandmentink** [comment]
Confirmed. Have exactly the same problem.

**Comment by AVellucci** [comment]
@darkforcesjedi Is this still an issue with the latest release(0.2.1)?
