### ISSUE TITLE
Oops! Something went wrong

### ISSUE THREAD

**Issue by yakoblahblah** [mchristopher/PokemonGo-DesktopMap#299]
<img width="792" alt="screen shot 2016-07-26 at 9 28 26 pm" src="https://cloud.githubusercontent.com/assets/20675177/17163897/4058cca0-5378-11e6-805a-32a54f7f4a8d.png">

**Comment by thiesgruening** [comment]
I experienced the same issue.

**Comment by Cova4** [comment]
Me too
