### ISSUE TITLE
Refresh

### ISSUE THREAD

**Issue by Migelius** [mchristopher/PokemonGo-DesktopMap#3]
Please, add key for Manual refresh, or make this automaticaly.

**Comment by IMNoob1** [comment]
At least im not the only one the app is not refreshing too.

**Comment by jnovack** [comment]
A spinning refresher would be nice.

Spinning = Refreshing data from server.
Not Spinning = Press to spin and refresh.

**Comment by mchristopher** [comment]
The latest release adds a Refresh option to the menu bar, is that what you're looking for?

**Comment by jnovack** [comment]
Yes, that partially would solve issues.

The secondary issue would be when PoGo is down (like now), where some visual element would inform the user the servers are offline so they don't think the application is bad.

**Comment by AVellucci** [comment]
Closing this issue as the initial problem was rectified in newer versions.
