### ISSUE TITLE
No more "info-box" when hovering

### ISSUE THREAD

**Issue by Apicedda** [mchristopher/PokemonGo-DesktopMap#304]
I liked that feature, it's just me or it has been removed?

**Comment by ranrinc** [comment]
Its working fine on my end..the only thing that not working is when notification appear, click and nothing happen

**Comment by Apicedda** [comment]
yeah, thats not working too. Just to make sure i mean that to show the info-box i have to click on the pokemon icon instead of just hovering it with the cursor

**Comment by AVellucci** [comment]
I personally like that it doesn't appear on hover.
I'm not sure if it was tied to it but when you hover on a pokemon on the top of the map it moves the map to center on the pokemon, which was much more tedious than clicking on the pokemon.
I don't need to know every pokemon's info if I hover it accidentally and I definitely don't want to have to navigate a maze of pokemon with my mouse just to avoid it panning and centering my map on that pokemon.
