### ISSUE TITLE
[Request] Option to disable change of map location

### ISSUE THREAD

**Issue by vincentcox** [mchristopher/PokemonGo-DesktopMap#305]
**Where to implement:** at the start screen below the tab server settings
**What to implement:** Toggle to disable the feature to change map location where it is scanning
**Reason:** When sharing the app with multiple people it's interesting to disable the change of map location for the clients. Otherwise it would jump constantly when people change it.

**Comment by thappy** [comment]
Agreed, I have to resort to using old versions due to this
