### ISSUE TITLE
[Feature Request] Loading Indicator

### ISSUE THREAD

**Issue by datrinh** [mchristopher/PokemonGo-DesktopMap#311]
I sometimes have the problem that the map doesn't update properly anymore. I then have to relog form time to time. If the app had a visual indicator for updating, I could know when to need to relog.

**Comment by jgwallace3** [comment]
2nd'd. Maybe a more general 'activity' indicator? Would give nice warm fuzzys that the app is doing something.

**Comment by AVellucci** [comment]
The app does have a visual indicator, if you enable Scanned Locations you'll be able to watch the App as it scans the area. if all the circles begin turning red with no new green ones showing up then you know it's stopped scanning.

**Comment by jgwallace3** [comment]
I've enabled 'scanned locations', but see no difference (no circles anywhere). FWIW, I only have 'pokemon' enabled, not gyms or stops. I also have a number of pokemon excluded.

**Comment by datrinh** [comment]
The green circles are working for me in 0.1.3 too. It's a little to obstructive for my taste.

**Comment by jgwallace3** [comment]
And... after starting in 0.1.3 -- not seeing the circles, reverting to 0.1.2 -- and seeing them, then progressing back to 0.13 -- and still seeing them now ... I don't really know what to think. Perhaps there was some sort of init code for the circle drawing that was in 0.1.2 and not in 0.1.3? Strange...

In any case, I found my 'visual indicator'.
