### ISSUE TITLE
Invalid Google Maps API Key. Please follow instructions to set API key before login. 

### ISSUE THREAD

**Issue by jnewt345** [mchristopher/PokemonGo-DesktopMap#315]
Can't find these instructions. What am I missing?

**Comment by PhantonQuad** [comment]
https://github.com/mchristopher/PokemonGo-DesktopMap/wiki/Google-Maps-API:-a-brief-guide-to-your-own-key

**Comment by jnewt345** [comment]
You are awesome. Map is awesome.

**Comment by AVellucci** [comment]
@jnewt345 if your problme is solved please close this issue
