### ISSUE TITLE
[suggestion] Growl 

### ISSUE THREAD

**Issue by dotheknifefight** [mchristopher/PokemonGo-DesktopMap#316]
If this could work with Growl or Boxcar that would be a dream.

**Comment by Padawin86** [comment]
I agree. I would love for this to be able to forward the notifications to my phone through Growl. I'm not sure exactly how to set it up, but this document implies it shouldn't be that difficult

[http://www.growlforwindows.com/gfw/d.ashx?f=Growl%20for%20Windows%20-%20Application%20Integration%20Guide.doc](url)

**Comment by AnthonyButler012** [comment]
This issue hasn't been solved yet ...
