### ISSUE TITLE
Last release vs current.

### ISSUE THREAD

**Issue by dotheknifefight** [mchristopher/PokemonGo-DesktopMap#319]
The last release was great. I could leave it on for hours and it would work beautifully. With this last release, some rarer Pokemon don't stay on the map but I get continuous notifications about them (Snorlax) and after a while it just stops scanning and I have to refresh or sometimes even relog to start scanning again.

**Comment by milano140** [comment]
yeah... scans stop after some time, i have to also quit the app and restart the desktop client for it to start scanning (and working) properly again

**Comment by shersey42** [comment]
It would be really nice if we could see the last scanned location in yellow or some other color (when Scanned Locations is toggled on) so that we could know where we are in the scan and also if the scan is stuck and has stopped scanning.

**Comment by dotheknifefight** [comment]
the circles do change color as they get older.

**Comment by shersey42** [comment]
Ah now I see it. I guess I just didn't quite notice it. Thanks!

**Comment by pill0ws** [comment]
I miss the functionality of click to Exclude when clicking pokemon on the map. This made it super easy to clean up the map when you logged in. Click to notify was ok but it wasnt very effective at populating a notify list of rare things. Typically the click to exclude was used the most. I would like that reinstated if at all possible. I realize the shift back to ngrok may of broke some things

So after populating a notify list repeatedly I feel like the best way to handle this is a large popout with images of all the pokemon that toggled notify on the icons you tap/clicked and either a swipe of clcik somewhere else would close it. I tend to know what things I see on the map that I have never seen before by looking at them more so than by their names. At least until I have seen them a few times. A table showing all icons would make it real easy to pickout stuff I have never seen before

**Comment by sniperz911** [comment]
I got no prob today with the last update i got it to work 16 hours straight (With macro reboot hourly and then send the link on PM on facebook) and it worked fine with 7 scan at the same time.
