### ISSUE TITLE
Feature request: blacklist system for showing pokemon

### ISSUE THREAD

**Issue by Helios747** [mchristopher/PokemonGo-DesktopMap#32]
Simple enough. I may even tackle this myself. Just documenting it here in case somebody gets to it first.

Basically, I don't want to see a zillion zubats fill up the window. You can already sorta modify the source to have it ignore certain pokemon (Maybe you can just delete the images you don't want to load? Haven't tested), but that's cumbersome and I don't want to change things in source every time I want to see different pokemon.

If nobody wants to do UI work, a simple text file could work and just parse that. Ideally to help end users, Something in UI could be implemented.

**Comment by SmilinItalin** [comment]
I read in a older post. you can go in and delete the icon, and it will not show up on the map anymore. Maybe a temporary fix.

**Comment by djofwarr** [comment]
Inside the PokemonGoMap-Win\resources\app\map\static\icons you can delete the icon of the Pokemon you don't want to see.

**Comment by fenixasin** [comment]
This is implemented in Version 0.0.5    This should be considered resolved

**Comment by Helios747** [comment]
If there is a UI element for it, I either missed it or it doesn't show up on my machine.

**Comment by andrewda** [comment]
It should be located at the bottom of the login window.

**Comment by Helios747** [comment]
Ah. My mistake.

Didn't notice the window scrolled.
