### ISSUE TITLE
Oops! Something went wrong.

### ISSUE THREAD

**Issue by rast2169** [mchristopher/PokemonGo-DesktopMap#320]
Starts to load the map, Flashes green circles then blanks out.

This page didn't load Google Maps correctly. See the JavaScript console for technical details.

Happens with both log in options\

Console says: Error: Cannot call loadURL because the webContent is unavailable. The WebView must be atached to the DOM and the dom-ready event emitted befor the method can be called. (...)

**Comment by JoeG05** [comment]
I'm getting the same issue.  I'll be checking back in for and/or with solutions.

**Comment by zombou** [comment]
To fix this go to the API Library (left side on the page where you created your key), in the middle row open: Google Maps JavaScript API and top middle will say "ENABLE JAVASCRIPT API" (or something similar). After you enabled it, it starts showing you statistics on the same page. Now try to log in back into the Map App and the "oops" should be gone. This part wasn't so clear from the guide as it was missing pictures, but this helped for me :)

**Comment by rast2169** [comment]
Got it. Works great now. Thanks for your help.

**Comment by Archer1022** [comment]
Let me start off saying that I had one of the earlier versions working fine. Im really new with all this programing and whatnot, Ive followed all the listed instructions and still can't get version 0.1.3 to run on my mac... I have no idea what Im doing wrong. I just keep getting the same message at the top of this post. The map will flicker for a split second and then nothing. any help would be greatly appreciated thanks

**Comment by thrillwad** [comment]
I can confirm that @zombou 's solution above works!

**Comment by livingtatted** [comment]
It didn't work for me someone help please!

<img width="1440" alt="screen shot 2016-07-29 at 4 27 43 pm" src="https://cloud.githubusercontent.com/assets/20582970/17262600/53fabf32-55aa-11e6-994d-fcfd8a3ef970.png">
