### ISSUE TITLE
Multiple maps

### ISSUE THREAD

**Issue by rotflmao1** [mchristopher/PokemonGo-DesktopMap#322]
Hi

I have always opened 5 maps of different regions and i love your app, great work. So what i did to open multiple maps is copied folder with map 4 times to be able to run always different settings but it doesn't work so i guess logging informations and coordinates are not stored in the folder but global so whenever i open 5 maps again i can see in all 5 apps the same logging and coordinates data. Please store settings in the folder so it can be more handy.

Thank you

**Comment by pill0ws** [comment]
So I do the same thing, I run 5 processes then host with a primary process that I login to mobiley through ngrok so I can move one around. I have the same problem myself so I have been using Google maps to save and label places so i can quickly set things back up. I imagine the saved places feature could even be an easy way to handle this. Ideally you wouldn't even need to set coordinates when you logged in, it could just use your current position if swapping locations wasn't such a convoluted motor process. Saved locations could encompass this. 

As far as search radius, it could be cool if location changes were as simple as click and drag. Perhaps if saved locations were added, a function could be added to begin a search at that location at an input value or a point click distance away from the saved location could be used to caluculate a radius.
