### ISSUE TITLE
Linking To Mobile, Map stops working

### ISSUE THREAD

**Issue by baileyhelix** [mchristopher/PokemonGo-DesktopMap#323]
When I link to mobile and go out with my phone my map only stays updating for about an hour or so then I get a message saying no active tunnel, is anyone having this issue or have an idea on how to fix.

**Comment by YonderGod** [comment]
Are you using the latest release? 
"reverting to ngrok for tunnel"

I haven't used this version, but on the previous version, which was using localtunnel.me, an hour is way better than what I was getting; about 5 minutes.

**Comment by baileyhelix** [comment]
i am using version 0.1.3
