### ISSUE TITLE
Web Interface at http://"MYIP":8000 question

### ISSUE THREAD

**Issue by SiliconFalcon** [mchristopher/PokemonGo-DesktopMap#324]
With the map running on my server I get "This site can't be reached" from an outside machine when trying to access http://MYIP:8000

I have port 8000 opened in my machine firewall and Port Forwarding setup in my router.
I also have a few other services setup for outside access to this server and they all work fine.

**Comment by iAbi** [comment]
Did you check the checkbox for "server" on the login screen of the app? At the bottom?

**Comment by SiliconFalcon** [comment]
Yes "Server Mode / Allow access from anywhere"
Is there another port that should be opened?

**Comment by PhantonQuad** [comment]
Only needed to do 8000 here, check internal IP address your forwarded to is correct and can you connect to it via lan using that internal address?

**Comment by SiliconFalcon** [comment]
Sorry, it was a local software firewall rule.
Working now!

**Comment by PhantonQuad** [comment]
Awesome! Good job mate!

**Comment by JaymerJaymer** [comment]
I'm in my house on my lan.
OS X desktop, with iPhone hitting it at ip:8000

I get the header on the screen, but only a gray screen for the map.
Tapping options does nothing at the top.
any ideas?

**Comment by JaymerJaymer** [comment]
Above was iPhone Chrome.
Tried it with Safari and the Options slide-out menu works.
But still no map image and no mobs displayed.

**Comment by AVellucci** [comment]
using another Computer connect to your map with FireFox/Chrome hit F12 and collect the Console Output and provide it here.
