### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by pakZndra** [mchristopher/PokemonGo-DesktopMap#325]
Sorry! Something went wrong.
This page didn't load Google Maps correctly. See the JavaScript console for technical details.

**Comment by Sylex-FiKnight** [comment]
Did you try to log in with PTC or Google? PTC has been having login issues all morning. They are slowly stabilizing now though.

**Comment by Drasow** [comment]
Same error and it was with google log.

**Comment by AVellucci** [comment]
Can you provide the JavaScript Console Output?
Found in "Tools>Developer Tools"

**Comment by pakZndra** [comment]
I have figured it out, first go to your Google API then open Library then click on Google Maps Javascript API then reload your Pokemon Live Map. Voila! It works with PTC or Google Account. :)

**Comment by AVellucci** [comment]
Amazing! @pakZndra now that your problem has been solved I'd kindly ask that you close this issue

**Comment by YufeiG** [comment]
Thanks this fixed it for me!
