### ISSUE TITLE
Sorry! Something went wrong

### ISSUE THREAD

**Issue by Zaka2630** [mchristopher/PokemonGo-DesktopMap#326]
"This page didn't load Google Maps correctly. See the JavaScript console for technical details."

I made sure Javascript API is enabled and I followed all the steps to generate my own API browser key. It doesn't load the map upon logging in. BTW I'm using a Pokemon account.

**Comment by AVellucci** [comment]
Can you provide the Javascript Console output?
Found under "Tools>Developer Tools"
