### ISSUE TITLE
Mobile connected, not displaying actual map [Fixed]

### ISSUE THREAD

**Issue by SamuriBakePie** [mchristopher/PokemonGo-DesktopMap#327]
Update: To get this to work I had to update my iPhone to the newest operating system.

**Original Post:**
I've had this issue since the change to localtunnel, I saw the latest version 1.1.3 and was excited to see the change back to ngrok hoping this would fix my issues as the last ngrok update worked fine for my phone. However, upon connecting my mobile device to the tunnel, all my phone displays is the black header with options and pokemon go map. I have used the options to try and set coordinates, turn on and off pokemon, etc, nothing seems to display the map. The rest of the screen is a gray rectangle and I've kept it there for a 20 minutes to see if it was loading, however the results are the same. I have uninstalled all of the previous versions from my computer, restarted my iphone, installed google maps on my phone wondering if the recent map fix changes caused it, all to no avail. I saw the other posts about the :8000 port, however my phone is connected to my laptop so I do not see how that would help. If anyone could shed some light on my issue it would be greatly appreciated. 

(Edit: I am aware the servers are currently down, but that is not a factor here, it won't even display a blank map. There is just no display whatsoever besides the header. Also, my map was working fine this morning and still is, its just the mobile.)

Side Note: I really appreciate what you have done here, this makes my mornings runs way better being able to map out a route that fills up my stardust and candy reserves to the best efficiency possible.

**Comment by PhantonQuad** [comment]
You using iPhone? I am and had a similar issue, a couple of refreshes of the safari browser resolved it for me

**Comment by SamuriBakePie** [comment]
I am using an iphone. I've tried that in the past, however I will try it again. 

Refreshed the page, waited a minute, tried again. Did this 4 more times, no change. Excited and opened Safari as well, no change in the map. Thank you for the idea though, I'm glad it fixed in your case.

**Comment by PhantonQuad** [comment]
Ok damn..no worries!

Maybe you could try another device to narrow it down to either server side or the mobile device.

**Comment by SamuriBakePie** [comment]
Very good point, let me go try that on my brother's phone. Also I do have the server box checked, and I've tried it unchecked as well.

Tried it on my brothers phone, my old phone, and my computer. All same results, shows the header with options and the map title but no actual map.

**Comment by AVellucci** [comment]
could you provide the console log?

**Comment by SamuriBakePie** [comment]
You would have to explain to me how to do that. I'm running this off my lenovo laptop with windows 10.

**Comment by AVellucci** [comment]
from the app click "Tools>Developer Options" then select the Console tab and copy that output.
From another PC hit F12 and do the same thing and provide that log as well.
Preferable to be done with FireFox or Chrome as IE is horrible.

**Comment by gonjiak** [comment]
I had the same problem using an 5s. it was working with version 0.1.0 just fine, then localtunnel.me didn't worked at all, and now with 0.1.3 it didn't worked aswell. Checked it with a iphone 6 and it was running just fine. I just had to use a firmware update on my 5s and tadaa, working. You may check if your phone is up to date.

**Comment by SamuriBakePie** [comment]
So what im copying is the big giant thing that is basically just scanning and its 100's of lines long?

**Comment by SamuriBakePie** [comment]
My phone is probably not up to date now that you mention it, but It should work on my computer right?

**Comment by AVellucci** [comment]
You don't need to copy the full scan from the app, usually just the first few start up lines or any Error lines.

**Comment by SamuriBakePie** [comment]
server started!
main.html:157 server up
main.html:199 Error: Cannot call loadURL because the webContents is unavailable. The WebView must be attached to the DOM and the dom-ready event emitted before this method can be called.(…)
main.html:199 Error: Cannot call loadURL because the webContents is unavailable. The WebView must be attached to the DOM and the dom-ready event emitted before this method can be called.(…)
main.html:157 server up
main.html:199 Error: Cannot call loadURL because the webContents is unavailable. The WebView must be attached to the DOM and the dom-ready event emitted before this method can be called.(…)
main.html:143 Got location: 47.1643833, -122.5619529
main.html:166 2016-07-27 13:29:42,953 [     search] [   INFO] Login to Pokemon Go successful.

main.html:166 2016-07-27 13:29:42,953 [     search] [   INFO] Scanning step 1 of 271 started.

main.html:166 2016-07-27 13:29:44,305 [     search] [   INFO] Completed  0.37% of scan.

main.html:166 2016-07-27 13:29:44,311 [     search] [   INFO] Scanning step 2 of 271 started.

main.html:166 2016-07-27 13:29:44,539 [     models] [   INFO] Upserting 3 pokemon

main.html:166 2016-07-27 13:29:45,589 [     search] [   INFO] Completed  0.74% of scan.

main.html:166 2016-07-27 13:29:45,592 [     search] [   INFO] Scanning step 3 of 271 started.

main.html:166 2016-07-27 13:29:45,997 [     models] [   INFO] Upserting 1 


That's from the computer running the map

**Comment by SamuriBakePie** [comment]
Strange, now my computer is showing the map, but my phone still does not

**Comment by AVellucci** [comment]
What about the log from another computer connecting to it?

**Comment by SamuriBakePie** [comment]
Failed to load resource: (ngrok tunnel here)/static/dist/img/cross.png the server responded with a status of 404 (NOT FOUND)

But for whatever reason that computer is displaying it now

**Comment by AVellucci** [comment]
I guess my dominance over the Electronic race frightened them into working XD

**Comment by SamuriBakePie** [comment]
I guess so I just don't understand why it works on my computer and not my Iphone. I would understand if it didn;t work before that I needed to update my phone but it worked fine on previous versions of the ngrok

**Comment by JaymerJaymer** [comment]
I have the exact same problem on my phone.
My desktop screen works fine (always has), and even NOW, with the PTC logins not working, google login works and I have live data on OS X.

This is the first time I've tried using as a server.  Now I see I can send my kids out and they can tap into my server at home.  Brilliant.

But just a gray screen on the phone.  Headers display.  Slide-out menu works on Safari only.

**Comment by SamuriBakePie** [comment]
I have a 5s, but its the second most recent versions, I'm gonna go through, delete some old photos and such, update and let you know if that helps.

**Comment by JaymerJaymer** [comment]
Ahhh, I have an older jailbroken 5s on 8.1.3
My kids just brought in a 5c on latest iOS and it worked fine 1st time.

**Comment by SamuriBakePie** [comment]
Update is *almost* done

**Comment by SamuriBakePie** [comment]
Works like a charm now. Updating issue

**Comment by AVellucci** [comment]
@SamuriBakePie If Your issue has been solved please close it
