### ISSUE TITLE
Need help modifying source code. json. maps.  I want the hover back!!!

### ISSUE THREAD

**Issue by JaymerJaymer** [mchristopher/PokemonGo-DesktopMap#328]
ok, i give. 
spent 2 hours and i wasn't going to give in... but i just can't bang my head more.

i personally HATE having to click the icon on the map - the hover box was perfect. 
Its OBVIOUSLY a simple toggle or a call to a different package.
But I can't find where.

I've looked through all the .PY code in "pogom" and I don't think what I'm looking for is actually in the Python code.
I'm pretty sure it has to be buried in Packages, and I'm stumped.

Can someone help?
thx

PS _ this worked in 0.1.2 but not in 0.1.3

**Comment by AVellucci** [comment]
did you try checking the changes in the GIT to see what was changed instead of blindly modify files?

**Comment by JaymerJaymer** [comment]
Thats a great idea. But I have no idea how all that stuff works.  Can you give me some direction?

**Comment by AVellucci** [comment]
The Map is actually bundled from here [PokemonGo-Map](https://github.com/AHAAAAAAA/PokemonGo-Map) once there you can view the individual commits and work your way from the most recent to the oldest, maybe from there you can find the change, as I'm not a python, json person I can't tell what half the changes actually do, so you'll be on your own for that.

**Comment by JaymerJaymer** [comment]
Does anyone else have any idea how to proceed?
A mouseover listener must have been used on the markers in 0.1.2, but not in 0.1.3
I'd like to add that code back in.
Thanks !!!
