### ISSUE TITLE
Map displays fine, but can't see Pokemon

### ISSUE THREAD

**Issue by chesyoungblood** [mchristopher/PokemonGo-DesktopMap#329]
The last version that works for me for displaying pokemon is 0.0.7

I am running OSX Yosimite 10.10.2 on a 2009 iMac. 

This map has been extremely helpful for me but if possible I would like to be able to run the latest version. 

Any ideas?

**Comment by chesyoungblood** [comment]
After it sits for a while, I do eventually see Gyms and Pokestops, but no Pokemon.

I am using a google account, not ptc

**Comment by SamuriBakePie** [comment]
Stupid question, did you check the boxes in the options section?

**Comment by chesyoungblood** [comment]
Not a stupid question at all, but yes, I have pokestops and gyms turned off

**Comment by SamuriBakePie** [comment]
So, under options pokemon is turned on correct? Just clarifying. I like to remove all the old versions of the program before I download the new one, I would recommend you doing the same.

**Comment by chesyoungblood** [comment]
Correct, the Pokemon option is turned on.

I will give that a try real quick

**Comment by chesyoungblood** [comment]
![screen shot 2016-07-27 at 7 12 14 pm](https://cloud.githubusercontent.com/assets/20644623/17194982/2c5d18ee-5429-11e6-9b63-e01ef3460922.png)

Screenshot of 0.1.3

**Comment by SamuriBakePie** [comment]
Now, I'm not able to help with this however there is a user on here who checks pretty regularly that can if you do this. If you go to tools, developers tools, and click on the console tab, look in the code lines that follow if you can see anything that has error in or it or something that looks wrong and copy/paste it here

**Comment by chesyoungblood** [comment]
Great. Thanks for your help Samuri!

**Comment by chesyoungblood** [comment]
![screen shot 2016-07-27 at 7 29 15 pm](https://cloud.githubusercontent.com/assets/20644623/17195423/9440c49a-542b-11e6-9b92-10d3ac7b720a.png)

This is the Error message I'm receiving.

**Comment by havenofear** [comment]
![1](https://cloud.githubusercontent.com/assets/20538325/17199052/d60a2112-549b-11e6-8b71-bbdee2be0fa8.png)
Got the same. Even if i start pokemap on my other laptop, sharing it for ngrok.io, try to enter this link - same result - No pokemons.

**Comment by SamuriBakePie** [comment]
Havenofear you are saying your mobile has this issue correct? Check out the closed issues about mobiles doing that if so

**Comment by havenofear** [comment]
It's happening not on mobile. it's on laptop (2nd)

**Comment by babasz** [comment]
Got the same... I see Gyms and Pokestops, but no Pokemon for version new version 0.1.3.
version 0.0.7 that works for me for displaying pokemon
