### ISSUE TITLE
Can't change my location

### ISSUE THREAD

**Issue by Shogunz1** [mchristopher/PokemonGo-DesktopMap#331]
Can't change my location in the program. Was able to but now cant. Doesn't auto fill or anything. What am I doing wrong? Why isn't it giving me addresses now? Seems to sometimes auto fill but still doesnt travel anywhere.

**Comment by Layzmaster** [comment]
Also this. Seemed fine for most of the day. No longer works

**Comment by SamuriBakePie** [comment]
On the newest version its under options you can do 111, -111 for coordinates.

**Comment by Shogunz1** [comment]
I'm talking about in the Pokémon go map. I go to options, then change my location and it doesn't change my location. The marker only stays at my current location. I was able to move the marker around freely about two hours ago. I would type in an address and the marker would move then show the Pokémon in that new area.

**Comment by Sum4196** [comment]
I'm experiencing the same issue, been trying to figure out the cause and how to fix it with no luck so far.  Any luck on your end @Shogunz1?

**Comment by Sum4196** [comment]
Nevermind! I literally tried it seconds after my comment and it seems to be working again

**Comment by Shogunz1** [comment]
None. It's not a deal breaker just I'm having to input the location on my main pc and that's the only area I can look at via mobil.

**Comment by Shogunz1** [comment]
I'm on mobil right now and it's not working. I'll have to get on my main in a few to see if it's working thee.

**Comment by Sum4196** [comment]
It's working on my main currently.  I would double check that you're sharing it to your mobile and if you are, maybe try disabling that feature and re-enabling it, that might do the trick.

**Comment by Shogunz1** [comment]
Yeah its weird cause I'll type an address in and sometimes it looks like its going to search for it but doesn't finish.

**Comment by Shogunz1** [comment]
Idk, kinda frustrating. Everything works great I just cant change locations without getting to my main. Basically have to set a location, drive to it, get the mon, and drive back to change the search to another locale.

**Comment by Shogunz1** [comment]
Wait you have to create a new api every time you log back in? That fixed it.

**Comment by Sum4196** [comment]
Glad you fixed it! You can also look into a remote desktop to access your main from your mobile.

**Comment by Shogunz1** [comment]
Ty @Sum4196.

**Comment by jgwallace3** [comment]
Is there any way to change your location by clicking on the map? I know you can enter a manual location in the options.

**Comment by mike2246** [comment]
Location not working for me either, tried coordinates and typing in address. Also when I login it doesn't bring up my location it brings up a location about a mile away

**Comment by Shogunz1** [comment]
I just created another api and it's been golden ever since. I love this program. Being disabled it's helped me out so much.

**Comment by Sum4196** [comment]
That's great, I'm glad to hear it :) Glad I could help out
