### ISSUE TITLE
I bought a new domain.

### ISSUE THREAD

**Issue by eigurt** [mchristopher/PokemonGo-DesktopMap#332]
So I bought a domain and now im wondering if it's possible to get it attached and ready. You can call me a noob but the only thing I'm good at is network engineering. How can I get it to work in my ftp server? I would really appreciate either a detailed answer or a "no it doesn't work" answer.
Cheers!

**Comment by iAbi** [comment]
Run it on any pc you want. Forward port 8000 in your Firewall to your pc local IP. Go to the domain admin site and forward your domain to your public IP adress. If no fixed adress, use a dynamic dns.

**Comment by eigurt** [comment]
Thank you for your response. Now that I have done what you said I only get to my router at home. How does one change this to my map?

**Comment by eigurt** [comment]
I thought I could use PAT but I don't think my router supports it.
