### ISSUE TITLE
Network location provider at 'https://www.googleapis.com/' : Returned error code 403

### ISSUE THREAD

**Issue by coremaya** [mchristopher/PokemonGo-DesktopMap#333]
how to do

**Comment by Spasib0** [comment]
hi how do you cope with this problem ?

**Comment by Spasib0** [comment]
hi how do you cope with this problem ?

**Comment by DanielTPCarvalho** [comment]
Hi, at your Google Projects you have to go to API LIBRARY, Google Maps APIs and enable whichever you need. For Browser you should enable JavaScrip API

**Comment by Spasib0** [comment]
from one account , works on a computer at work, and does not work at home , the difference in providers (what comes to mind )
