### ISSUE TITLE
[Suggestion] Visual indicator of Pokemon on notify list

### ISSUE THREAD

**Issue by vsammiel** [mchristopher/PokemonGo-DesktopMap#334]
Maybe this already exists and I'm missing it, but I'd love to see a visual indicator for Pokemon on my notify list to go with the sound. I've filtered out a lot of the clutter on my map, but sometimes every second counts.

**Comment by pill0ws** [comment]
So the last version would allow you to click the notification and zoom to what triggered it. However that doesnt seem to be working in v0.1.3. That made things very easy for locating it and the "get Directions" link actually worked too. Which was pretty cool for shaving those seconds off without having to plan out a route. As far as a visual notification though the popup was the only real visual queue, but it was pretty effective when it let you be on your way to that point within two clicks
