### ISSUE TITLE
Remove "Expired" Pokemon? 

### ISSUE THREAD

**Issue by nsusnjara** [mchristopher/PokemonGo-DesktopMap#335]
Pokemon remain on map even after Expiring. Cluttering the map. Any way to fix?

**Comment by pill0ws** [comment]
Noticed this problem too, the recent version lost a lot of funcitonality of the previous version but gained a working broadcaster. I imagine some things need to be reworked in support of nrgrok but I totally appreciate ngrok more than tunnel now
