### ISSUE TITLE
[Suggestion] Include lured pokemon

### ISSUE THREAD

**Issue by Kyouga** [mchristopher/PokemonGo-DesktopMap#336]
Maybe add an option to show lured pokemon on the map as well? Combining it with the lured pokestops is overwhelming..

**Comment by Layzmaster** [comment]
Lured pokemon don't show up on the "nearby" and won't show up on the map. You can tell what where it came from by the color of the circles around the pokemon. Pink-Lure, white-wild, pink mist-incense

**Comment by AVellucci** [comment]
@Kyouga As layz mentioned only naturally occuring pokemon can be seen on any kind of map application, since this is currently not a possible feature please close this issue.

**Comment by Kyouga** [comment]
No wait, CMIIW, but the current map application *can* show the lured pokemon:
1. Show the pokestops by selecting Options - Pokestops
2. Click on one of the lured pokestops.
3. Voila, a "Lured Pokemon:" is listed on the pokestop, which is not visible on the normal map.

As you can see, if I have to turn on the pokestops and then have to click on each lured ones, it's getting pretty hectic on the map.
What I suggest is those pokemon shown on the pokestops just appear on the map without the need to click on each of the lured pokestops.

@Layzmaster I'm sorry but I don't see any color circles around the pokemon.. is it possible that feature is only available on Linux/OSX? I'm using Windows..
![screenshot](https://cloud.githubusercontent.com/assets/11424410/17214082/76559452-5501-11e6-93ee-a75e05634f7d.png)

**Comment by AVellucci** [comment]
Lured Pokestops will report their last lured pokemon when pinged if they are active, but the pokemon will not show up if you ask the API for pokemon only as it may not be a "nearby" pokemon, the "lured pokemon" at those pokestops could have been lured 30 minutes ago at the start of the lure and may not even still be there.
All Applications that can scan for pokemon all mention that they cannot scan for lured, incensed or any kind of pokemon that appears only for select people.

**Comment by Kyouga** [comment]
@AVellucci So from what I understand from your comment, the lured pokemons *should* be visible on the map albeit on a *random* location?
Is it just  or I do *not* see any lured pokemon *at all* shown on the map, even though there is a lot of lured pokestops nearby? Or am I misunderstood your explanation somehow?


1. Add an option to "Hide pokestops but show lured pokemons"
2. The option will retrieve the lure information and therefore got the lured pokemon info, which should spawn at least in the vicinity of the lured pokestop.
3. Show just the pokemon, instead of showing the pokestops.
Or is it not plausible?

**Comment by AVellucci** [comment]
You're somewhat right on how it works. Though to change it the Scanner would have to scan pokestops regardless as any pokemon spawned by a lure is not it's own instance.
For example lets say there are 3 pokemon in an area, 2 are natural and 1 is lured.
The way the information is recieved is like so:
`PKMN-1, LAT,LON,TIME
PKMN-2,LAT,LON,TIME
STOP,LAT,LON,isLURED,LURE-TIME,POKEMON-SPAWNED,PKMN-TIME`
so the third pokemon is not an actual pokemon, it's actually a pokestop that is lured with pokemon information in it.

**Comment by Kyouga** [comment]
Well, I think it's better to have the option rather than cluttering the screen with all the pokestops and have to check lured pokemons one by one.
Of course, this is just a suggestion. Feel free to ignore. I really appreciate the hard work put into this maps.
I'll just close this suggestion.
