### ISSUE TITLE
Code: PHP Mail to send mobile URL as Text Message

### ISSUE THREAD

**Issue by luckofthelefty** [mchristopher/PokemonGo-DesktopMap#337]
Hey guys,

I've written a few changes to the newest release that make it pretty convenient as far as the moblie map goes. I've run in to issues with using the barcode scanner opening up in its own built in browser which is littered with ads. The caveat to this is that it requires you be hosting a XAMPP or other type of local web server capable of hosting PHP. Using the "Mail" function that is built in to php you can send mail to/from anyone. This means you get a text with the link so it opens in you default mobile browser instead of the scanner app. I hope some find this useful anyway, here's the code:

textMessage.php (file to be hosted locally):
```
<?php

if(isset($_POST)){
    $carrier = $_POST['carrier'];
    $number = $_POST['number'];
    $message = $_POST['message'];


switch($carrier){
    case 'AT&T':
        $address = 'txt.att.net';
        break;
    case 'T-Mobile':
        $address = 'tmomail.net';
        break;
    case 'Sprint':
        $address = 'messaging.sprintpcs.com';
        break;
    case 'Verizon':
        $address = 'vtext.com';
        break;
    default:
        $address = '-1';
}
    if($address != "-1"){
       $emailToTxt = $number."@".$address;  
       mail($emailToTxt, "", $message, "From: PokemonGoMap");
       if(mail){
         echo "Success sent to: ".$emailToTxt;
       }
    }else{
        echo "Unable to send: ".$carrier." : ".$number;
    }
  
}
?>
```
After this, make these modifications in the main.html file located in resources/app folder:

After the line of html that reads (Line 107 in Brackets text editor):
` <span>To toggle sharing, click the button below.</span>
`
Insert:
```
  <div>
     <div class="checkbox">
        <label><input type="checkbox" id="sendText" checked>Send Text Message</label>
      </div>
      <div id="mobileConfig">
         <div class="form-group">
             <label for="carrier">Select Carrier:</label>
             <select id="carrier" class="form-control">
                <option id="att" value="AT&T">AT&T</option>
                <option id="tmobile" value="T-Mobile">T-Mobile</option>
                <option id="sprint" value="Sprint">Sprint</option>
                <option id="verizon" value="Verizon">Verizon</option>
             </select>
          </div>
          <input id="phone" class="form-control" type="text" placeholder="Number no spaces or dashes ex. 9999999999">
       </div>
    </div>
```
Step 3, add in this next piece to the `function setupMobile()` section of the javascript below.
Once you find the function, look for the `ngrok.once('connect', function(url){ ` and below where it says `ngrokConnect(null, url);` add this:
```
if($("#sendText").prop("checked")){
   $.post("http://10.0.101.187/weather/textMessage.php",{
      carrier: $("#carrier").val(),
      number: $("#phone").val(),
      message: url   
     },function(data){
     alert(data)
  })  
}
```

Finally, add this to the `$(document).ready(function(){ ` section near the bottom of the javascript:
```
$("#sendText").click(function(){
   if($("#sendText").prop("checked")){
      $("#mobileConfig").fadeIn()
   }else{
      $("#mobileConfig").hide()
   }    
})
```

This is configured for the 4 main providers, however, by adding to the php file you can add more if yours isn't one of the main 4. Maybe @mchristopher could consider wrapping this function in? I'm not familiar with the ngrok server or how it works but I find that getting a text is easier.

Hope this is useful to someone other than me haha.

Thanks

**Comment by KrayZeee** [comment]
why not just using another QR-Code scanner which lets you choose in which browser it should open? im using the https://play.google.com/store/apps/details?id=com.a13softdev.qrcodereader if i have not set one browser as default, im getting a prompt in which brwoser i want to open the link

**Comment by luckofthelefty** [comment]
I'm currently on iOS. I can take a look in to other scanners, but I also have some other code that will restart the map every 7 days, or automatically startup with default preset coordinates on reboot/loss of power. This machine it is being ran on will power on once power is applied(say after a power outage) and auto log in to a preset account and start the map back up. So when it does, it auto ptcLogin() and toggleMobile() which creates a new map. I then get a text with the new map in case I was out and about and the PC restarts.
