### ISSUE TITLE
[Suggestion]

### ISSUE THREAD

**Issue by kodyy19** [mchristopher/PokemonGo-DesktopMap#338]
Okay so when you click a pokemon it comes up with "Exclude/Notify/Get directions" any chance we could get another option like "got it" or something like that so when you catch the pokemon you can remove that one this would help out a ton when camping nests because you kinda get lost on what ones you have already got

**Comment by andrewda** [comment]
This is implemented into the latest version of PokemonGo-Map. When this gets updated to PokemonGo-Map v2.1.0, it should be good to go.

**Comment by kodyy19** [comment]
Oh cool can't wait ;D
