### ISSUE TITLE
"Failed to login to Pokemon Go..."

### ISSUE THREAD

**Issue by DrumYum** [mchristopher/PokemonGo-DesktopMap#340]
(Sorry for my bad English)
For some time it works perfectly, but then suddenly scanner stops working and you need to relogin to make it work again.
It's very annoying, because I use "mobile sharing", and I need to relogin my computer with TeamViewer from my Android device every time when it breaks and I'm not at home. :(
So, please, do something with it, thank you in advance!

If it can help, in console I see an infinite number of this:
````
main.html:166 2016-07-28 13:10:53,904 [auth_google] [   INFO] Google Login successful.

main.html:166 2016-07-28 13:10:54,296 [     pgoapi] [  ERROR] Login failed - unexpected server response!
2016-07-28 13:10:54,296 [     search] [   INFO] Failed to login to Pokemon Go. Trying again.

main.html:166 2016-07-28 13:10:55,296 [auth_google] [   INFO] Google Login successful.

main.html:166 2016-07-28 13:10:55,663 [     pgoapi] [  ERROR] Login failed - unexpected server response!
2016-07-28 13:10:55,663 [     search] [   INFO] Failed to login to Pokemon Go. Trying again.

main.html:166 2016-07-28 13:10:56,663 [auth_google] [   INFO] Google Login successful.

main.html:166 2016-07-28 13:10:57,069 [     pgoapi] [  ERROR] Login failed - unexpected server response!

main.html:166 2016-07-28 13:10:57,071 [     search] [   INFO] Failed to login to Pokemon Go. Trying again.
```

**Comment by AVellucci** [comment]
Please check the PGO Server status before posting "can't login" issues.
![pgo](https://cloud.githubusercontent.com/assets/11682773/17206950/33a904ee-5480-11e6-977e-4bc4a70e22da.PNG)

**Comment by sniperz911** [comment]
If you're using only 1 account you can setup up ur radar with a PTC account and it will not timeout.

Google account seem to timeout 1 hour after you started them so the thing i do because i have multi radar and it does'nt seem to work with PTC account i setuped a macro that reset hourly and push me the link through facebook.

**Comment by sniperz911** [comment]
I think he mean after some time the map does'nt scan anymore

**Comment by DrumYum** [comment]
**_AVellucci_**, I know about IsPokemonGoDownOrNot.com, I talk about periodic timeout like **_sniperz911_** mentioned, not about global server crash.
I'll try PTC account instead of Google today, thanks. At now I restart it and manually write ngrok link, so it took like 5~ minutes every time just to make it work again. 
Maybe I lost Pikachu only because of this. :(

**Comment by sniperz911** [comment]
It will work for both but i don't encourage the use of that because there is rumor you can get ban or flagged for that because i think how it work is it use ur account and teleport to scan the zones so use a dummy account to be sure.
