### ISSUE TITLE
Not scanning anymore

### ISSUE THREAD

**Issue by Vulcaiiin** [mchristopher/PokemonGo-DesktopMap#341]
Hello,

My Pokemon Go Map app doesn't scan anymore, i don't know why. 
Could it be because of my Google map API Key? 
I can log in but the scan stopped, it all became red and no new green scan appears.

First error appearing:
"Error: Cannot call loadURL because the webContents is unavailable. The WebView must be attached to the DOM and the dom-ready event emitted before this method can be called.(…)"

and then for each scan step:

"  [     search] [  ERROR] Scan step 1 failed. Response dictionary key error."

**Comment by AVellucci** [comment]
PGO is currently Critical
http://ispokemongodownornot.com/
Check status of PGO before opening an issue for connection reasons.
Please close this issue.

**Comment by Vulcaiiin** [comment]
Oh ok sorry, i was able to correctly login on my phone so I didn't think about this.
