### ISSUE TITLE
Notifications not working + Timeout issues

### ISSUE THREAD

**Issue by celeritax** [mchristopher/PokemonGo-DesktopMap#344]
In both 0.13 and 0.11, the map occassionally times out and you need to close + re-open or log out + log in again.

The notify-list isn't saved if you share to mobile/web and close it.
Notifications do not work in the windows program, only in a browser window.

**Comment by LesBean** [comment]
2nd the timeout issue, my map would stop working after about an hour of running. which isn't a big deal if you have a laptop but if you want a dedicated server and share with mobile theirs nothing you could do, if you programmed a macro to refresh the app it would break the link between the server and mobile devices
