### ISSUE TITLE
not show everything

### ISSUE THREAD

**Issue by gepcio** [mchristopher/PokemonGo-DesktopMap#347]
i have a problem i scan one place on my town my friends living near and he go catch pikachu when he walk near pikachu , he catch golbat i dont saw this pokemon on map 1 min ago :O so  i refresh map and still nothing why?

**Comment by iAbi** [comment]
Dowa he have an Incent activated?

**Comment by iAbi** [comment]
*incense

**Comment by gepcio** [comment]
no :/

**Comment by RenHakubi** [comment]
I also get the same issue, bulbasaur shows up in my near me pokemon but the map shows nothing =/ missed out on that one lol I'll find another in due time hopefully it will show up on the map.
