### ISSUE TITLE
DOES NOT WORK - NO MAPS - HELP ME PLX.

### ISSUE THREAD

**Issue by Piterek96** [mchristopher/PokemonGo-DesktopMap#349]
HELLO,  SOMEONE HELP ME WHY IT DOES NOT WORK ??  :+1:  :+1: 

![przechwytywanie](https://cloud.githubusercontent.com/assets/20706016/17218498/4c03f446-54e8-11e6-9dc3-f107d2978ea0.PNG)

**Comment by maisdesign** [comment]
Actually neither version 0.1.3 nor v0.1.2 are showing UI.
On a fresh win 10 64bit installation i tryied to run 0.1.3 First and it didn't showed up then tryied 0.1.2 and also this isn't working properly.

**Comment by Tails32** [comment]
This happened to me too. The problem were spaces in the folder name of the program. Try to remove any spaces in the folder name if there are any and please tell us if this helped.
