### ISSUE TITLE
Program won't track GPS Location

### ISSUE THREAD

**Issue by nikky-k** [mchristopher/PokemonGo-DesktopMap#35]
I'm on Mac OSX (El Capitan) and it seems like for the past several hours, when I open the program, it doesn't track my GPS location. It will drop me off the coast of California and I'm in Virginia. When I logged in about five minutes ago, it dropped me at my house but just to see, I closed the program and logged in again and it had me off the coast of California again.

**Comment by sageknives** [comment]
I have yosemite mac osx, I'm in washington state and it also puts me off the coast of california

**Comment by chrismapes** [comment]
I can confirm this issue is happening in Windows as well. I'm too busy to debug myself ATM, but if it's not fixed by later tonight I'll try to see if I can put together a patch and a PR.
