### ISSUE TITLE
MAP Not Working - Why ????

### ISSUE THREAD

**Issue by Piterek96** [mchristopher/PokemonGo-DesktopMap#350]
hello, why does not work ??

![przechwytywanie](https://cloud.githubusercontent.com/assets/20706016/17218616/b20efdd0-54e8-11e6-96f0-6dba6751bd25.PNG)

**Comment by AVellucci** [comment]
Hello @Piterek96 please do not open multiple issues for the same problem.
I'd ask that you close this issue and follow your previous one #349

**Comment by Piterek96** [comment]
I'm sorry , you know how to help me?

**Comment by AVellucci** [comment]
There are a few tickets with this exact issue, Some have already been closed. You can check the closed issues to see if one has a solution for you. Though you should close one of your tickets as you opened 2 for the same issue.
