### ISSUE TITLE
[Suggestion] Alerts

### ISSUE THREAD

**Issue by jane0815** [mchristopher/PokemonGo-DesktopMap#351]
I love the alert function. Have the map open all the time when at home to scan the area around me.

But i am always to slow to see the alert and then have to search the map what alert that was.

Would it be possible to leave alert pop-up open until they are clicked away or add some alert history?

Or maybe even send the alerts from Mac to the Android phone?

**Comment by iAbi** [comment]
In mac the Notification stays in Notification center

**Comment by kdprince** [comment]
Even better: Add option to send text message to configurable number/numbers with hyperlink of to map
