### ISSUE TITLE
Notify of Pokémon suddenly empty

### ISSUE THREAD

**Issue by jane0815** [mchristopher/PokemonGo-DesktopMap#353]
Two times i had the problem that after a restart the List of Pokemons to Notify was empty.

**Comment by jane0815** [comment]
Happened again after Update to newest Version.

This is very annoying as it takes ages to add all filters again.

**Comment by jane0815** [comment]
In the new Version is is even harder to add and check notification pokemons. With the numbers every pokemon takes up one line and it is only possible to see 4 lines of names. 

The field should be much bigger and also have an option to copy the content so it is possible to paste a whole set of pokemons.

**Comment by jane0815** [comment]
And empty again!!!! 

The last version is broken!

**Comment by mg6101** [comment]
It appears to be broken in 0.1.5 as well. Filter/notification preferences as well as toggles for pokestops/ scannedlocations/etc. do not save between sessions.

**Comment by tinarazzburton** [comment]
yeah my software auto-updated and cleared the list for me again.  It's definitely a pain to set up that list again.
