### ISSUE TITLE
Change method of notification/filter list

### ISSUE THREAD

**Issue by tinarazzburton** [mchristopher/PokemonGo-DesktopMap#354]
The current method of adding names to the "hide common" and "notify" list is pretty cumbersome.  I would suggest pulling up a list of all names and being able to check/uncheck names.  

If we could export and import lists, that would be helpful too as my list occasionally disappears.

**Comment by JaymerJaymer** [comment]
i agree, i had a long list of Pokemon ID#s that was EASY to copy/paste into view or hide.
While some "do gooder" thought it was "cool" to modernize the UI, it doesn't work easily.
You can't copy/paste a list either.

**Comment by jane0815** [comment]
I agree it is not very userfriendly. For me this is the most important feature of the map.

**Comment by mchristopher** [comment]
@tinarazzburton @JaymerJaymer @jane0815 I'd recommend putting an issue in at https://github.com/AHAAAAAAA/PokemonGo-Map. This project simply makes that one easy to use, and I'm sure they'd welcome the feedback.
