### ISSUE TITLE
web link cant update it self

### ISSUE THREAD

**Issue by PhilipposVassil** [mchristopher/PokemonGo-DesktopMap#355]
Web link cant update it self cant update the map on your phone by enable the URL

When you refresh your browser it says no active client for "the name of the name of the link"

This happens when i leave pc alone and go out to find the pokemon i looking for
after the pokemon that i look for catch reopen browser and reload the page because i almost all the pokemon show expired and after refresh web page wont load....

problem solved! :D
I just find out the option that you can portforward your web link via 3G/4G from the tick from the login screen(server option-> tick it and then login -> take the link and go outsite :) )

**Comment by AVellucci** [comment]
This seems to be a common issue for people using Ngrok or LocalTunnel There are already a few issue for this, try checking the closed issues first to see if someone has solved this already.
If I find a ticket for reference I'll link it.

**Comment by JaymerJaymer** [comment]
AVellucci     to me, your reply doesn't make sense.
all most of us are probably doing is downloading the release and install/running it.
I've been on OS X version since 0.1.6 and i have no idea of Ngrok or LocalTunnel.
You make it sound like we have a choice or should know which one.

**Comment by AVellucci** [comment]
@JaymerJaymer how do you make your map available for mobile? if you use the Mobile button you will get a localtunnel or ngrok link.
If you use the checkbox at the bottom of the login that requires portforwarding to work outside your network.
