### ISSUE TITLE
Version 0.1.3 not loading UI

### ISSUE THREAD

**Issue by maisdesign** [mchristopher/PokemonGo-DesktopMap#356]
Hi, as just said this version doesn't loads UI
![version 0 1 3](https://cloud.githubusercontent.com/assets/1204645/17226193/748bdd6e-5508-11e6-8cdf-4b26df42dfb7.PNG)

**Comment by AVellucci** [comment]
@maisdesign There is already an issue for this, see #349 
Please follow that issue and close this one, thank you.
