### ISSUE TITLE
stuck on "waiting" for last 3 versions

### ISSUE THREAD

**Issue by shadowedlab** [mchristopher/PokemonGo-DesktopMap#358]
ive tried each version, from 1.1 up, each will not load any pokemon or maps, simply says "waiting"

**Comment by AVellucci** [comment]
@shadowedlab Please be sure to check
http://ispokemongodownornot.com/   or   https://go.jooas.com/
For Server Status before posting connection issues.
You'll see that PGO logins are currently down 
![pgo-1](https://cloud.githubusercontent.com/assets/11682773/17228443/fd866454-54e0-11e6-9984-b4dfc9f0f74a.PNG)
