### ISSUE TITLE
[Request] Release ZIP versions of Windows installation along with the EXE

### ISSUE THREAD

**Issue by AVellucci** [mchristopher/PokemonGo-DesktopMap#360]
It's great that you have an auto-installer but I'd rather have the folder and files in a location I choose rather than use an auto installer that is bascally a zip folder in EXE format.
Releasing 2 copies of this would be nice as in my case I can use the ZIP which I prefer over an installer placing files in my AppData location.

**Comment by mchristopher** [comment]
@AVellucci Thanks for the feedback. The `.nuget` file is actually a zip file, if you download and extract that it'll work in the same way as the old zip files did. Does that work for you?

**Comment by AVellucci** [comment]
@mchristopher I don't see a `.nuget` file, I do however see a `.nupkg` and if I open that with, say, 7-zip it doesn't have the files in there.
