### ISSUE TITLE
Error when running multiple instances

### ISSUE THREAD

**Issue by AVellucci** [mchristopher/PokemonGo-DesktopMap#361]
I get this error when running a 0.1.3 version and the new 0.1.4 version.
![java](https://cloud.githubusercontent.com/assets/11682773/17230080/78e75246-54e8-11e6-8b77-8d305525bde8.PNG)

**Comment by sk310** [comment]
I am also the same , you get this error in the 0.1.5 version .
 Want to know how to resolve.
