### ISSUE TITLE
Oops! Something went wrong.

### ISSUE THREAD

**Issue by St3nist** [mchristopher/PokemonGo-DesktopMap#362]
I have tried to go through the steps seen in previous issues but my java script is already enabled. The map will load briefly and then I get the error. I have tried everything I have seen to help and nothing has worked. Ever since the last update I have not been able to view the map. PLEASE HELP

**Comment by c0mput3rxz** [comment]
pokemon servers are currently down

**Comment by ITguy5286** [comment]
I ran into this issue as well, fixed it just by making sure that the API was copied over/typed in correctly. make sure no extra spaces and everything that is caps should be

**Comment by St3nist** [comment]
How do I get back to see my API again?

**Comment by St3nist** [comment]
Never mind I figured it out. Thank you!

**Comment by Pineyka** [comment]
Just that important. If you solved the problem yourself, you should tell about it. This will help if someone has the same problem.
