### ISSUE TITLE
Slow Map

### ISSUE THREAD

**Issue by JDClough** [mchristopher/PokemonGo-DesktopMap#363]
Loading the map used to be super fast, now it is very slow!

**Comment by LesBean** [comment]
agreed, previous version was extremely quick at scanning this map seems to take way to long, stuff disappears by the time it would start scanning again,  hopefully the kinks can get worked out.

**Comment by fnayr** [comment]
http://cmmcd.com/PokemonTrainerClub/

(The PTC server is unstable/down right now). By the way you should donate if you haven't already to continue the development of this app (I did!).

**Comment by Narazna** [comment]
I am also having the same problem.

In the old version the map would scan 3 circles at a time, but now it only scans one.

It may be because of the shaky PTC servers but iunno.

**Comment by mchristopher** [comment]
The latest release (0.1.5) has a fast scan mode that will speed up the scan, though it may be less accurate.

**Comment by LesBean** [comment]
Awesome app Christopher, thanks for the donate button now it'll be easy to donate :) also any idea why this times out for me after an hour? everything stops scanning, i have to restart the program for it to start scanning again, (my computer doesn't have any of those features that shut internet and hibernate on just a FYI) not a big issue ill just bring a laptop with me but i would love my desktop to be the server.
