### ISSUE TITLE
Sharing is not possible

### ISSUE THREAD

**Issue by majuss** [mchristopher/PokemonGo-DesktopMap#364]
0.14 broke the sharing button :( "Toggle sharing" is grey and not clickable.

Tested Linux and OS X

**Comment by BirkHappens** [comment]
Confirmed above.  Not working on OS X El Capitan 10.11.6.  I'm also seeing that the status button that normally says "Operational" is stuck in "Waiting" even though the map is working and showing Pokemon.

Great app. Thank you for your hard work!

**Comment by majuss** [comment]
Seems like it's a problem with the button. Just logout and in again. Then click the toggle button once and wait patiently :D after a few secs the link will appear.

**Comment by BirkHappens** [comment]
Upgraded to 0.15 and the issue is no longer present.  thanks!
