### ISSUE TITLE
Javascript Error - Uncaught Exception

### ISSUE THREAD

**Issue by AquatikJustice** [mchristopher/PokemonGo-DesktopMap#366]
Keep getting this error every time I try to log in and open the map.
![js error](https://cloud.githubusercontent.com/assets/4640482/17232277/80f50dee-54ec-11e6-9745-44e596d5840d.png)

**Comment by Fonzzz** [comment]
i always get "Oops! Something went wrong.
This page didn't load Google Maps correctly. See the JavaScript console for technical details." or your error message :(

**Comment by aagulto** [comment]
Same here!
![image](https://cloud.githubusercontent.com/assets/20647076/17232916/975e1d70-54f9-11e6-8ea1-d87588a91392.png)

**Comment by AquatikJustice** [comment]
Not sure if it's related or not, but my map will load and start searching but it won't show any pokestops or gyms.

**Comment by jacobzlogar** [comment]
Port 8001 is in use. On OSX you can run something like this
`lsof -i:8001`
look at the PID
`kill PID`
