### ISSUE TITLE
Sever mode?

### ISSUE THREAD

**Issue by tinarazzburton** [mchristopher/PokemonGo-DesktopMap#368]
This is a dumb question, but is there documentation that explains some of the features?  I was trying to figure out what "Sever Mode" and "fast scanning mode" does.

**Comment by LesBean** [comment]
Fast scanning make scans quicker (little green circles if you click on options upper left of the app and check the scanned locations button) this is how it finds / shows you the Pokemon, also the Server mode allows you to use mobile tethering (correct me if I'm wrong), which makes it so you can use this on your phone / tablet but wherever the app is installed on it has to remain running and connected to the internet or it will not work.

**Comment by calgar** [comment]
I'm wondering about those 2 options as well.  I just upgraded to the latest version and enabled fast scans.(I've always used the showed scanned options to see it that instance died or not).  I don't see any major differences "yet" (servers have been cranky all day)

**Comment by Hearttless** [comment]
The 0.1.4 servers took a really long time to scan due to some changes with the program (big update). So I assume the fast scan update (0.1.5) was an attempt to patch that problem.
