### ISSUE TITLE
[Mobile] Expired Pokemon on Notification list wont go away until Page Refresh

### ISSUE THREAD

**Issue by calgar** [mchristopher/PokemonGo-DesktopMap#369]
Expired Pokemon on Notification list wont go away until Page Refresh

**Comment by Hearttless** [comment]
that seems like a feature... if you chose to be notified about it, you probably want to see how much time it has, even if it expired in order to maybe determine if that is a nest for a certain spawn.

**Comment by calgar** [comment]
thought so (and I like the idea but maybe control it with a checkbox??), but it doesn't say expired in any case... I've crosschecked the desktop and mobile version and sometimes the pokemon is still there and sometimes is not..also that's not the way it works on the desktop version (expired). maybe keep the same behavior on both ???
