### ISSUE TITLE
Location and pokemon spawns not working on Mac osx

### ISSUE THREAD

**Issue by Cameronday14** [mchristopher/PokemonGo-DesktopMap#37]
When I open it it puts me in the middle of the ocean. No pokemon are spawning when I was on land. I am running Mac osx el Capitan version 10.11.5. Anyone know whats wrong?

**Comment by Cameronday14** [comment]
I am in vail colorado, could it just be a dead location?

**Comment by Cameronday14** [comment]
I also just tried it on my windows computer and the map tracks the location but no pokemon appear on the map.

**Comment by HuXu77** [comment]
Works for me, version 0.0.7, macOS 10.11.5 and I put the location in manually.  Sometime the geolocation might not work, make sure the long, lat gets automatically filled out before you start otherwise it will put you in the ocean.
