### ISSUE TITLE
[Suggestion] default location

### ISSUE THREAD

**Issue by Tails32** [mchristopher/PokemonGo-DesktopMap#371]
I am using the map on a desktop PC and my location is therefore resolved by my IP. I'd rather like to set a default location that is used whenever I start the program.

Closed: what I was looking for is already available and I simply oversaw it.

**Comment by jacobzlogar** [comment]
Pretty sure you can do that already just specify an address in the config options on the launch page, maybe update the program if this is a new feature?

**Comment by calgar** [comment]
more than a default location I would say an address book (of frequently used addresses)
