### ISSUE TITLE
pokemon not appearing in scan area at all. PLEASE HELP ASAP

### ISSUE THREAD

**Issue by mrevoco** [mchristopher/PokemonGo-DesktopMap#373]
i have downloaded the 0.1.3 version of this scanner along with the newer versions and in all the versions when I go to scan for the pokemo,n none show up in the scanner at all, but when I scan and have the gyms or pokestops set for scan those will show up? I do have the bar set "ON" to scan for pokemon just none are showing up. I have tried to uninstall the app and reinstall and no luck. also had a friend who Is using the same one try to figure out why It wasn't showing any pokemon and have had no luck. any help would be much appreciated really wanna get that dragonite!!!
thanks

**Comment by al3x-edge** [comment]
@mrevoco Can you post in your console log from the developer tools?

**Comment by mrevoco** [comment]
@al3x-edge what exactly do you mean by that? I'm not super computer savvy so idk exactly everything I should know. Lol. It's been a few years since I've used computers but got one to use this app and it's not showing Pokémon at all when I scan.

**Comment by al3x-edge** [comment]
@mrevoco Try `ctrl`+`shift`+`i` or `command` + `alt` + `i` depending on Linux/Windows or macOS.  

Should come up with something like this:
![screen shot 2016-07-28 at 11 13 42 pm](https://cloud.githubusercontent.com/assets/62131/17236734/0d0bf442-5519-11e6-904b-eb8de438efa0.png)

Click the funnel and then click Errors. Paste what is there to here.
![screen shot 2016-07-28 at 11 14 55 pm](https://cloud.githubusercontent.com/assets/62131/17236753/4148a2fa-5519-11e6-9e9f-4f6631aa70c1.png)

**Comment by mrevoco** [comment]
Shows 350Estates are hidden by filers

**Comment by mrevoco** [comment]
Not Estates. It's at 400 and going up on the hidden filters

**Comment by mrevoco** [comment]
@al3x-edge

**Comment by mrevoco** [comment]
Idk how to paste what it shows from my computer to her @al3x-edge sorry :(

**Comment by mrevoco** [comment]
![20160728_211903](https://cloud.githubusercontent.com/assets/20714575/17236917/268a3672-550a-11e6-962e-34b5d2a9636a.jpg)
  This is what I got when I took pic with my phone. The number was still going up though @al3x-edge

**Comment by mrevoco** [comment]
![20160728_213141](https://cloud.githubusercontent.com/assets/20714575/17237020/f2375cbe-550a-11e6-9bf7-d8ee7a68cfe9.jpg)
![20160728_213121](https://cloud.githubusercontent.com/assets/20714575/17237022/fa58c36a-550a-11e6-9e45-c1a6f83379b8.jpg)


![20160728_213044](https://cloud.githubusercontent.com/assets/20714575/17237029/0351414a-550b-11e6-93ff-faec8dcdb260.jpg)

**Comment by mrevoco** [comment]
Here is 3 pics of what I can get. It shows I have the scanner on to look for Pokémon but none showing up. One pic shows an error at the very top of the console logs but idk what it is. Then one shows what it mainly shows while I have it scanning. Doesn't hardly show errors while scanning. Has me and a friend stumped. Spent $120 to hopefully have this scanner work and no luck so far.

**Comment by mrevoco** [comment]
also if it helps any the computer is a Toshiba satellite A215 I believe is the model. installed windows 8 on it and tried the app, didn't work. so went ahead and installed windows 10 to see if itd help and no luck. I tried last night to install and reinstall the document but still have yet to see a pokemon pop up on the scanner. gyms and pokestops still show though.

**Comment by avielc** [comment]
From what i can tell its a Windows 10 issue, or some old legacy code. (someone mentioned it) but i still can't seem to find the cause or how to locate what's bugging the app @al3x-edge @mchristopher 
Hopefully someone can help with it, Thank you all and Christopher, thanks for the app its awesome!

**Comment by mrevoco** [comment]
@avielc I had the same problem on Windows 8.1 though as well. That's why I upgraded to 10 to see if it fixed the issue but it didnt. Still haven't been able to figure out why Pokémon aren't showing up.

**Comment by avielc** [comment]
@mrevoco yea, lately from what i could tell it didn't happen on my other Windows10 computer, so i assume its something to do with the code. @mchristopher @al3x-edge

**Comment by mrevoco** [comment]
@avielc Yeah it's weird I installed ithe on my gfs computer and it works fine. Mine not so much. Lol
