### ISSUE TITLE
just sent you 0.5 btc

### ISSUE THREAD

**Issue by zordin** [mchristopher/PokemonGo-DesktopMap#374]
subj!
thanks for you work!

**Comment by mchristopher** [comment]
Woah, thanks!! I'm glad you're enjoying the app, I'll keep the updates coming :)

**Comment by zordin** [comment]
actually it would be great that you implement statistics part. Where you will fix each pokemon founded by your map, to make big data info, where there is statiscs where often pokemon borns.
you know like titan panel for WorldofWarcraft %)
