### ISSUE TITLE
0.1.5 Not Allowing Multiple Instances

### ISSUE THREAD

**Issue by EternisRequiem** [mchristopher/PokemonGo-DesktopMap#375]
While I like a looot of the changes in .1.5, I found it extraordinarily useful to have several instances up so I could scan three different locations at the same time, and have my phone connect to it nicely.  It also seems to be pretty speedy when that's done this way too, instead of doing an entire section of the city.

(When I load up a second instance, it just defaults both to scanning whatever location I inputted into the new instance, unlike before where you could scan two locations)

Would it be possible to have multiple locations scanned within one app, or allow multiple again?  I ended up going back to the 1.2 release since that one works the best for it that I know of, and has been goin on for days on my desktop without any issues.

**Comment by al3x-edge** [comment]
@EternisRequiem what os are you running? Running `open -n -a` on macOS seems to work for me.

**Comment by skeeker20** [comment]
I'm running Windows 10 and I have this same issue.

**Comment by EternisRequiem** [comment]
Windows 10.  There was a weird interaction and right now I only have one instance open but something is apparently still scanning in one area, so I'm not sure what that's all about...
