### ISSUE TITLE
Game continues to say waiting...

### ISSUE THREAD

**Issue by olyx11** [mchristopher/PokemonGo-DesktopMap#377]
And before you say it is a server being down issue, I downloaded the app two days ago. It has never worked even with different versions of the App and WITH THE SERVERS BEING UP.

Downloaded the latest version 1.5. I now get the attached error when I launch the application. I have restarted my system, tried running as administrator, verified that I only launched the app one time, and still get the error. Also, still get this even though the servers show up

main.html:157 server up: null
main.html:145 Error getting location, trying second provider PositionError
main.html:147 Found location [30.4000,-97.7528] by ipinfo.io
main.html:167 2016-07-28 20:18:45,736 [ runserver] [ INFO] Parsed location is: 30.4573/-97.7897/0.0000 (lat/lng/alt)
main.html:167 2016-07-28 20:18:45,742 [ search] [ INFO] Search loop 0 starting
main.html:167 2016-07-28 20:18:45,744 [ search] [ INFO] Attempting login to Pokemon Go.
main.html:167 2016-07-28 20:18:45,749 [ auth_google] [ INFO] Google Login successful.
main.html:172 Python server started!
main.html:172 Got open express port: 8001
main.html:172 Express server started!
main.html:157 server up: http://localhost:8001
main.html:167 2016-07-28 20:18:47,029 [ search] [ INFO] Failed to login to Pokemon Go. Trying again in 5 seconds.
main.html:167 2016-07-28 20:18:52,029 [ auth_google] [ INFO] Google Login successful.
main.html:167 2016-07-28 20:18:53,075 [ search] [ INFO] Failed to login to Pokemon Go. Trying again in 5 seconds.

livemapserror

**Comment by innrwrld** [comment]
I get a similar error of "Loading, please wait...", on MacOS.  Console log below:

`server up: null
main.html:167 Traceback (most recent call last):
  File "./runserver.py", line 57, in <module>
    create_tables(db)
  File "/private/var/folders/d7/313wrk9d5kq0xxk842lzx39m0000gn/T/AppTranslocation/9258ABEF-489C-4EFB-984C-3E1525E20495/d/Pokemon GO Live Map.app/Contents/Resources/app/map/pogom/models.py", line 341, in create_tables

main.html:167     db.connect()
  File "packages.zip/peewee.py", line 3404, in connect
  File "packages.zip/peewee.py", line 3316, in __exit__
  File "packages.zip/peewee.py", line 3402, in connect
  File "packages.zip/peewee.py", line 3658, in _connect
peewee.OperationalError: unable to open database file

main.html:145 Error getting location, trying second provider PositionError
main.html:147 Found location [x,y] by ipinfo.io`

**Comment by olyx11** [comment]
Gee... Thanks for nothing. I have been having the same trouble with the app for over a month. I keep opening issues and you keep closing them with no response or even trying to troubleshoot. Are you just not able to figure out the issue and there for ignore it? I am really interested if assisting to resolve the issue and work with you, but that is difficult to do if there is no communication from your side. 

Sincerely,
Ox
