### ISSUE TITLE
No pokemon

### ISSUE THREAD

**Issue by MakeVio** [mchristopher/PokemonGo-DesktopMap#379]
I see pokestops, gyms, scanned areas(no idea what that is) but not a single pokemon. I've moved the location around multiple places. Is there a button I need to use to scan? And is there not a read me file to explain what stuff does?

**Comment by eritropp** [comment]
same here, all versions which are using google api key shows no pokemons.  although it shows all gym and pokestop data (prestige, lures, etc.)

**Comment by eritropp** [comment]
i guess it was google's issue, now works again, withouth changes

**Comment by mrevoco** [comment]
how did you guys fix this? I have the same exact problem and I have been trying everything. I can see pokestops and gyms but no pokemon show up at all. ive tried to reinstall the download and redownload but no luck

**Comment by MakeVio** [comment]
I didn't fix it, it's still happening for me.
