### ISSUE TITLE
Map only loads spawn for a few minutes, doesn't update?

### ISSUE THREAD

**Issue by jameson167** [mchristopher/PokemonGo-DesktopMap#38]
Thanks so much for this amazing app. I got the map loading and working but it seemed like after about 15-20 minutes it stopped loading any fresh pokemon spawns. Perhaps it is just user error and I am supposed to be doing something to cause a "refresh" ? Or is it supposed to constantly update the new pokemon by itself every X seconds? Thanks!

**Comment by jameson167** [comment]
Also, while using the app can I change the location of the current spawns by typing in new latitute longitudes up top and clicking SET? Or Do i have to restart the entire app with new LAT/LONG on the login screen?

**Comment by fenixasin** [comment]
this is kinda tied into my #43mobile lat long refresh issue.


but after like 15-20 min it stops updating in the core area of the marker and all you have if a ring around it
