### ISSUE TITLE
JavaScript Error

### ISSUE THREAD

**Issue by TranquilityX89** [mchristopher/PokemonGo-DesktopMap#381]
![untitled](https://cloud.githubusercontent.com/assets/20720683/17242343/54bd8286-557f-11e6-9953-00d80e92e4ea.png)

this.

**Comment by TranquilityX89** [comment]
Made the port work, but 0 pokemon on map.

**Comment by eritropp** [comment]
you have a program running which is already listening that port (8001), pogomap can't bind to it.
