### ISSUE TITLE
Timeout issues, notitication issues

### ISSUE THREAD

**Issue by celeritax** [mchristopher/PokemonGo-DesktopMap#384]
The map stops working after a short while and pokemon stop appearing. The problem was in 0.1.1 and 0.1.3 but still persist.

Also, if you share to mobile again all your settings dissapear like which pokemon to filter and notification.

**Comment by majuss** [comment]
0.1.5 ist the actual version... please update!

**Comment by celeritax** [comment]
Please read again. It was in 0.1.1 and 0.1.3 but IT STILL PERSIST. Meaning, the bug is in 0.1.5 also.

**Comment by SiliconFalcon** [comment]
I', seeing the same. I installed the latest  0.1.5 on another box and it runs all day so far. Perhaps there was a cache or reg entry created from an old install?
