### ISSUE TITLE
Saved settings for Hide and Notify Pokémon

### ISSUE THREAD

**Issue by PunchyKiss** [mchristopher/PokemonGo-DesktopMap#385]
On the Mac, version 0.1.5 will not save settings for 'Hide Pokémon' and 'Notify of Pokémon' when the app is quite and re-opend.

**Comment by Drewbacca81** [comment]
It would also be nice if there was some way to save this in between versions. With the original way, I just saved the comma separated numbers to a text file. It just takes awhile to reinput everything if you're notifying for a lot of pokemon. For that matter, if you could just have checkboxes next to the pokemon, you could go down the list and select multiple at the same time, so you wouldn't have to scroll through them all each time you select one.

**Comment by munkhof** [comment]
Experiencing the same issue on OSX; but I don't even restart it, just a log in and out and all notifications and hide/exclude options are lost. Using google authentication.

Also to the dev: any chance you could reimplement the feature for notification and hiding pokemons by numbers like in the older verions? You still got the geo location field anyway ;) was much easier switching between different filters depending if i wanted a evening hunting pidgeys for leveling or only wanted to be disturbed during a movie if a rare one appeared closeby :-D

**Comment by frosty22** [comment]
Try copy app to the Application, it solved problem by me. If you run it from another folder it probably doesnt have correct permission for saving.
