### ISSUE TITLE
On restarting the application all scanning settings disappear

### ISSUE THREAD

**Issue by intraum** [mchristopher/PokemonGo-DesktopMap#386]
this used to happen with every update, but now happens every time i restart or logout of the map. options such as show scanned locations and notify pokemon are empty upon restart

**Comment by munkhof** [comment]
Experiencing the same issue in 1.5, however logging out and back in (using google authentication) is enough to reset my notification list.
Should note that im using the OSX version.

**Comment by frosty22** [comment]
Try copy app to the Application, it solved problem by me. If you run it from another folder it probably doesnt have correct permission for saving.
