### ISSUE TITLE
[REQUEST]BEST IDEA EVER!

### ISSUE THREAD

**Issue by roflinger** [mchristopher/PokemonGo-DesktopMap#387]
Hi Chris, 

could you add https://www.reddit.com/r/pokemongodev/comments/4uzeb9/pokewatch_a_bot_that_watches_an_area_for_rare/ 

to you Bot? 
It informs on twitter if it finds some pokemons. That would be a way to get it pushed to your phone.

please please please <3 

here is the github link

https://github.com/bunzosteele/PokeWatch

**Comment by Arceus** [comment]
I second this. It would greatly improve the GO experience in my community :)
