### ISSUE TITLE
new version 0.1.5 virus found

### ISSUE THREAD

**Issue by PhilipposVassil** [mchristopher/PokemonGo-DesktopMap#388]
This virus that AVG found is Generic virus on windows

I am scared....:/
Please fix it ASAP!
Check your computer and your files
Thank you

**Comment by Hearttless** [comment]
I saw that too, but it said Windows protected the PC. My antivirus (Webroot) didn't catch anything, so i'm guessing it's picking up on the new google key that the update needs to run and somehow your antivirus dosent like how much access your giving it. I can't think of anything else in the new updates that would change to much in that aspect. (again, i'm just guessing. There could still be a virus that makes your computer implode)

**Comment by PhilipposVassil** [comment]
Hello and thank you for your report
The other 3 first releases in zip this are clean when running the exe file

Now my antivirus says has virus in this exe
I don't know what happens there
If someone has the knowledge i would like to hear it
