### ISSUE TITLE
[Request] Save data to database

### ISSUE THREAD

**Issue by Iworb** [mchristopher/PokemonGo-DesktopMap#389]
Original PokemonGo-Map can save information about spotted pokemons into database (SQLite/MySQL or PostgreSQL). Is it possible to implement some kind of data saving?
I've seen "[pokelyzer](http://www.whackdata.com/2016/07/26/instructions-analyzing-pokemon-go-data/)" project, it could be start point of develop.

**Comment by chancrescolex** [comment]
YES PLEASE. Or perhaps if that's too much work, for now possibly just add an option to make all expired spawns visible? Then we could still look for patterns/nests
