### ISSUE TITLE
Map not loading in southern hemisphere

### ISSUE THREAD

**Issue by R467** [mchristopher/PokemonGo-DesktopMap#39]
Using default coords or manual ones. Only shows a white screen doesn't load the map at all

**Comment by IMNoob1** [comment]
have you tried different location first?

**Comment by R467** [comment]
Default co ords:
![image](https://cloud.githubusercontent.com/assets/20569382/17009491/86bab1f6-4f3e-11e6-816b-e093ff64fbae.png)

Result:
![image](https://cloud.githubusercontent.com/assets/20569382/17009496/9e3e800a-4f3e-11e6-8979-818f82725feb.png)

Set to yank coords:
![image](https://cloud.githubusercontent.com/assets/20569382/17009511/c3252b6c-4f3e-11e6-8038-0521edbce6e7.png)

Map loads:
![image](https://cloud.githubusercontent.com/assets/20569382/17009518/df05d11a-4f3e-11e6-99c2-50474d22014f.png)

"Set" button doesn't appear to do anything at that point

If I manually enter the southern hemisphere co ords I also get a blank map

**Comment by IMNoob1** [comment]
Set button will "work" (hopefully) in near feature allow you to move your self in the map without the need of closing the application.

I see that you got something in map, whats wrong than?

**Comment by R467** [comment]
Thanks for your help

The issue is that the map only loads when using a positive value for latitude
E.g. -42, 147 won't load. 42, 147 will load

**Comment by IMNoob1** [comment]
indeed there is no "-" in lang / lat

good luck :+1:

**Comment by R467** [comment]
I don't follow...

Half the world is in - latitude
![image](https://cloud.githubusercontent.com/assets/20569382/17009715/dde1bcb6-4f40-11e6-8acf-eb7cf062fae4.png)

**Comment by IMNoob1** [comment]
Yes only if you live in South America , Africa etc etc you said you line in south hemp.


Hu lol read my post ment to say in your location

**Comment by R467** [comment]
Can you get it working for negative latitudes?

**Comment by IMNoob1** [comment]
Sure why not (probably?) haven't tried it yet and I'm on my phone so it's a good question to ask

**Comment by R467** [comment]
Much appreciated

**Comment by breandr** [comment]
Yeah I'm also not able to get this working for Australian location.

**Comment by mchristopher** [comment]
@R467 @IMNoob1 Can you guys try version 0.0.6? There was a bug with negative latitudes that I'm guessing was causing this.

**Comment by R467** [comment]
It's working now. You're a legend

**Comment by mchristopher** [comment]
Cool, glad it's working.
