### ISSUE TITLE
How to get multisearches to work.

### ISSUE THREAD

**Issue by abuch47** [mchristopher/PokemonGo-DesktopMap#392]
download the pokemon-go-map-0.1.5-full.nupkg from release page, extract with program (RAR).

run executable, then run as many more as you like just like you used to.

I have them searching my area at a radius of 20, every few minutes. which means around ten threads going at once all overlapping eachother. This way every pokemon that comes up has at least ten minutes on the spawn timer left. 

Only works from homebase and allows me around ten minute drive radius to collect.

Tried mobile and using it to move around but its tedious to setup and scan times are just not fast enough to check an area while on the move. Its possible though and the fast scanner may aid.

Best setup would be to scan my whole city constantly so every location of every pokemon is known.

Or the whole world? FTW.

**Comment by abuch47** [comment]
Still having the problem where the scans will just stop for no reason, I think due to PTC being down.

But pokevision is working,

**Comment by SmilinItalin** [comment]
Curious which platform your running this on. I was doing something simalar in vs.7 and now that they have updated a lot in vs 1.5 would like to set this up to run mutiple scans. Im running on windows 10. Will the steps you stated work? when i tryed running a second vs it closed the first?

**Comment by abuch47** [comment]
As others have said multiple threads get throttled. 

Mine works with two threads per PTC as some others have stated but some people said only one thread/scan per PTC account.

I am using 0.1.5 with fast scan, using two different PTC to run 2 threads each for a total of 4 threads/applications opened.

I can scan a search radius of 20(seems to be around 3km in my area and a drive time of around ten  minutes max) Each scan is 5 minutes and 16 seconds behind each other to equally cover the same scanning amount. Every timer on Mr.Christophers app seems to be 15min so for every pokemon it finds I can have minimum 9 minutes 44 seconds to find which is perfect for my max 10 minute radius.

fast scan seems to work and it does pick up the rare stuff which is what I want but its not as good as it was for me running multiple instances in 0.1.2 and 0.1.3

The scans run out eventually due to different speeds and needs to be reset but can last for 6 hours pretty reliably,

I havn't tried 0.1.6. but due to slower scanning speeds needing more PTCs Im not happy with the update, will definitely try it though and make a new post if it works.

I have caught 2 dragonite, aerodactyl, dragonair, omastar, snorlax, clefable, blastoise, venusaur, jynx, kadabra, victreebell, slowbro with this method, Ive also missed haunter, gengar, raichu, dragonair (lucky another came), weezing, wigglytuff, nidoqueen, vileplume, charmeleon due to not enough time or just coudln't be bothered ( I need all these evos).

It has also showed porygon, onix, blastoise, venusaur, haunter, jynx and kangaskhan fairly reguraly.

Never seen farfetch'd, mr.mime, charizard, tauros, electabuzz, muk, dewgong, magneton, alakazam, machamp, ninetales (in my area), chancey or gyarados but hoping soon :)
