### ISSUE TITLE
[Error] listen EADDRINUSE :::8001

### ISSUE THREAD

**Issue by AVellucci** [mchristopher/PokemonGo-DesktopMap#397]
I get the following error when starting up the map
![v 0 1 5](https://cloud.githubusercontent.com/assets/11682773/17251067/36701ba4-5575-11e6-8b92-ffdae8d5b168.PNG)
Win7-x64
Java 1.8.0_101
PGO-Map v0.1.5

**Comment by MakeVio** [comment]
I get this as well.

**Comment by cykou** [comment]
Hello, I am getting this error as well, does anyone have info?
