### ISSUE TITLE
Add multiple PTC accounts and cycle through them for faster cell refresh

### ISSUE THREAD

**Issue by because-bot-fed** [mchristopher/PokemonGo-DesktopMap#398]
Due to the API throttling now, it would probably be good to increase the performance by being able to add multiple PTC  accounts and have the program cycle through them to request cell refreshes at a faster rate since single accounts are now throttled severely and cannot request more than one thing at a time. 

Just a thought! :)

**Comment by esparks** [comment]
Agreed

**Comment by calgar** [comment]
are you sure the throttling is account based?   I've been testing that theory myself.   I used to be able to run 14 instances at the same time without degradation (using 0.1.3).    Today I can run 6 without degradation... The moment I start the 7th instance is when things start to break... I tested using another PTC account on my 7th instance and it has the same results as if I was using the same account.   That leads me to believe the throttling happens on either an IP address based or a session based criteria (or maybe both)..

**Comment by andrewda** [comment]
@calgar Tested and definitely account-based throttling.

**Comment by calgar** [comment]
if the above is true then the solution can be a distributed model (client/servers) with several VPN endpoints which is I guess where they're trying to migrate the software to (since 0.1.5 opens listeners on your host)

**Comment by calgar** [comment]
@andrewda how many instances do you run per account?

**Comment by abuch47** [comment]
I can run 2 fine. any more and the app even tells me it has outages that affect all scans
