### ISSUE TITLE
Enable Javascrips API?

### ISSUE THREAD

**Issue by mannefalth** [mchristopher/PokemonGo-DesktopMap#399]
Help! I follow this [guide ](https://github.com/mchristopher/PokemonGo-DesktopMap/wiki/Google-Maps-API:-a-brief-guide-to-your-own-key)but i dont understand how to enable the Javascript API. Plz halp ;)

**Comment by zombou** [comment]
You can check my post here #320 . Helped me and seems it helped others too.
