### ISSUE TITLE
Map does not load due to python version error

### ISSUE THREAD

**Issue by Bigben37** [mchristopher/PokemonGo-DesktopMap#4]
When I try to login the map does not load and I get the following error message:

```
Starting Python process...
Got open port: 8000
Maps path: /home/benjamin/Downloads/PokemonGoMap/resources/app/map
python ./example.py --auth_service ptc --token ## --location #.#,#.# --auto_refresh 10 --step-limit 7 --display-gym --port 8000 --parent_pid 17445
Python:   File "./example.py", line 111
    print '[-] {}'.format(message)
                 ^
SyntaxError: invalid syntax
```

The problem is that you call the script with `python` which is linked to `python3.x` on my system (and probably on many others aswell), but the error message suggests that you need to call `python2.x`. So you should explicitly specify which python version you need.

**Comment by tsipizic** [comment]
Open file resources/app/main.js and change  line 105 to var pythonCmd = 'python2';

**Comment by mchristopher** [comment]
The maps project that this uses requires Python 2. I'll add info the the README file.
