### ISSUE TITLE
Stop with these Updates

### ISSUE THREAD

**Issue by lucasxvieira** [mchristopher/PokemonGo-DesktopMap#400]
Every time you guys releases a new update, it's taking even longer to show pokemons on the map, just keep it simple. This version 0.1.5 is taking hella long to view pokemons, so i switched back to version 0.1.2, it shows pokemon super quick on the map and that's what people want. Version 0.1.2 is a lot better than all these new versions

**Comment by Arceus** [comment]
No one forces you to use newer versions. If they appear slower there's gotta be a reason, intended or not. They'll fix it eventually, don't take everything for granted.

**Comment by wowoo123** [comment]
these new .exe versions are not very good, the  .zip were much better, im using version 0.1.3 now

**Comment by naveen-rasiah** [comment]
Why dont you try reading the release notes before complaining about someone's project. Turn on Fast Scan in the login screen in v1.5 for faster scans.

**Comment by AVellucci** [comment]
@lucasxvieira I understand your frustration with the rate of the scans, since this is also referenced in #401 please close this issue and follow that one.

**Comment by MakeVio** [comment]
Why would I want to turn fast scan on when it warns that it may be inaccurate?

**Comment by Arceus** [comment]
@mAKEvIO Fast scan is the previous scanning method. No problems with accuracy so far.

**Comment by Ezoteric** [comment]
@Arceus I had many pokemon not show up on fast scan, not always but when pokevision used to work i checked both to see the difference. If i didnt use pokevision next to it i lost myself a snorlax and a lapras. course it also happened with other pokemon.

But when i saw a pokemon was mission on this app i check the 1.5 and also there some pokemon didnt show up while the pokemon was there on my phone and pokevision, so even the slow scan is not 100% sadly but i prey this app wont go and IF niantic ask to remove it i hope the devs will say, sure we can when you fix your damn trackin system we will :P
