### ISSUE TITLE
Fix scan radius to be 70 metres (adapt to API change) 

### ISSUE THREAD

**Issue by vowswithin** [mchristopher/PokemonGo-DesktopMap#402]
From the /r/pokemongodev 

Sounds like there was a change made by Niantic and needs the code to be updated before all the pokemon show up properly again.

Fix scan radius to be 70 metres (adapt to API change)
-    pulse_radius = 0.1                  # km - radius of players heartbeat is 100m
+    pulse_radius = 0.07                  # km - radius of players heartbeat is 70m

**Comment by StormReiki** [comment]
this link might help provide information
https://www.reddit.com/r/pokemongodev/comments/4v73aj/psa_scan_radius_was_changed_from_100m_to_70m/
