### ISSUE TITLE
I can't use the Application

### ISSUE THREAD

**Issue by SirSerlin** [mchristopher/PokemonGo-DesktopMap#404]
I have no clue why this is happening...
![ddd](https://cloud.githubusercontent.com/assets/20728189/17255612/dce77bda-55b1-11e6-9c00-9e21e159ed7c.png)

**Comment by wowoo123** [comment]
try version version 0.1.3, works much better and faster for me as the new .exe versions.

**Comment by SirSerlin** [comment]
That's the one I'm using, no matter which one It never works, I only get this page.

**Comment by Arceus** [comment]
The same happens on my brother's PC. We tried everything.

**Comment by SirSerlin** [comment]
Damn, someone HEEEEELP!!!

**Comment by andrewda** [comment]
`Tools > Developer Console`. Could you screenshot the errors? If no errors show up, try refreshing.

**Comment by SirSerlin** [comment]
Not sure what you need, if this is not what you need, let me know.

![fdfdf](https://cloud.githubusercontent.com/assets/20728189/17257985/b07f086e-55bc-11e6-9257-92074bd0181d.png)

**Comment by robo32amg** [comment]
same problem here. i have two os win 7 on computer. One is working, but other one is not working.

**Comment by Doberok** [comment]
This problem occurs on a cluttered computer , reinstall windose and will work checked

**Comment by bananaphon3** [comment]
Fresh installed Windows same behavior

**Comment by SirSerlin** [comment]
^ Same

**Comment by bananaphon3** [comment]
well what solvet it for me after a fresh install was new admin accou
