### ISSUE TITLE
Mobile Mode doesn't keep filter/alert preferences.

### ISSUE THREAD

**Issue by Drewbacca81** [mchristopher/PokemonGo-DesktopMap#407]
I would be nice if they carry over. Adding in alerts on a phone is quite time consuming and painful.

**Comment by pocketq10** [comment]
yep i agree.

**Comment by Holli357** [comment]
I wouldn't even mind adding them on the phone ... if only they'd stay!  But you re-load the program and any filters you added on your phone are erased.
