### ISSUE TITLE
Server Mode / Allow access 

### ISSUE THREAD

**Issue by Pineyka** [mchristopher/PokemonGo-DesktopMap#408]
-Server Options
-Server Mode / Allow access from anywhere

Someone explain to me what it is and how to use it?

**Comment by Hidden999** [comment]
@Pineyka I've got no idea either :(

**Comment by they007** [comment]
This is an "advanced" option that requires other knowledge to use. 
A quick explanation: 
This program uses web server software to run. By default, that web server is programmed to only accept requests from the same machine. No other computer/device would be able to load the map from the web server. If you check that box, the web server will accept requests from other machines.

If you have the knowledge and experience with setting up networks for web site traffic, this button is a way to configure the software to allow you to use your networking knowledge to get to the map webpage from another machine. If you do not have the knowledge of how to use this feature, I would recommend just clicking the "mobile" button once you log in and using private tunnel method to access the map from other machines. That is the easy method for users who don't want to or know how to configure web servers and networks.

**Comment by Pineyka** [comment]
Thanks a lot.
Yes I coped. It was a stupid question. I graduated CCNA and work. However,
at first did not you write this function. After a moment's reflection, I
came to what is used.
Well done - respect

2016-07-30 20:24 GMT+02:00 they007 <notifications@github.com>:
