### ISSUE TITLE
user's settings

### ISSUE THREAD

**Issue by Doberok** [mchristopher/PokemonGo-DesktopMap#411]
Hello, is it possible to transfer the settings from the old version to the new one, and then a long time to adjust the Pokémon who do not want it to appear , or which files are copied to a new version where the user's settings are located

**Comment by gonjiak** [comment]
For windows the settings are saved here: 

%HOMEPATH%\AppData\Roaming\pokemon-go-map

The alert / exclude database is located at Local Storage directory -> http_localhost_800X.localstorage

Don't modify the files on your own, it will most likely corrupt them.

There may be multiple files with following numbers, e.g. 8000, 8001 etc., check which one includes your settings you want to import and make a backup, it's usually 8000. Now simply paste the file into the folder, just rename them to 8001, 8002 ... 
I made this to import the data from 0.1.3 to 0.1.5, but should work from version 0.1.1 or higher

**Comment by Doberok** [comment]
great, works , thanks)
