### ISSUE TITLE
[NON-ISSUE POST] To those that didn't get their maps loaded on the application

### ISSUE THREAD

**Issue by TYKANT** [mchristopher/PokemonGo-DesktopMap#412]
After you've enabled the main API key, go to **Library**, click on the circled links and enable each one of them. The ones that you really need to turn on are the **JavaScript**, **Geocoding** and **Geolocation** APIs before anything else. Let me know if it works for y'all.
![api](https://cloud.githubusercontent.com/assets/20737970/17269539/b11dc7fc-5610-11e6-897c-36d1c192fbbc.jpg)

**Comment by erylflynn** [comment]
Went and enabled all that were not and still get stuck at loading.  Running the 1.5 Linux x64 code.

**Comment by bigjdjr** [comment]
getting stuck also.

**Comment by markus-zhang** [comment]
I'm sorry, but that doesn't work. I can't see the map. BTW also got a javascrpit error before logging in.
