### ISSUE TITLE
A Javascript Error occured in the main process

### ISSUE THREAD

**Issue by breinkober** [mchristopher/PokemonGo-DesktopMap#413]
![](https://i.gyazo.com/ef63cd218d6c7f444888e33be2fb7ff8.png)

**Comment by skyli91** [comment]
Same here

**Comment by hrdsk** [comment]
Same here

**Comment by SebasJoustra** [comment]
Same

**Comment by dotas86** [comment]
same

**Comment by keaganbester** [comment]
Please refer to £412. You have created an API key without enabling javascript.

Please close this issue if this fixes your problem

**Comment by psychoblue** [comment]
I get this same error, but mine occurs during/after installation or even before logging in.

**Comment by heyjonmanning** [comment]
@keaganbester Thanks, that fixed it for me. 

@psychoblue Same thing happened to me, it tried to log in with my previous credentials as soon as installation finished. Clicked ok on the dialog, followed the instructions in post #412 and everything is working again.

**Comment by Drewbacca81** [comment]
I'm getting a similar error. The map starts to load and then it gives me a Javascript error. I followed #412 instructions, and it still is happening. Interesting, everything works fine on my Mac laptop, but my PC desktop gets these errors.

**Comment by psychoblue** [comment]
I just found it weird I got that error during the installation process before even logging in. I went back to 0.1.3 and without making any changes, it still worked. No errors. :(
