### ISSUE TITLE
Linux 64 Stuck at Loading, please wait.

### ISSUE THREAD

**Issue by erylflynn** [mchristopher/PokemonGo-DesktopMap#417]
Enabled Javascript, geocaching, and all as another post here suggested and still just stuck at loading.  What I am doing to start is just double click on "Pokemon GO Live Map" to execute in dolphin.  Am I starting this correct?  I get the start screen asking for account, location and key.  If I miss information it does throw an error.  But with all entered it sticks at loading please wait.

Also does it want a browser or server API key?  I tried both.

**Comment by AVellucci** [comment]
@erylflynn please follow #545
