### ISSUE TITLE
Cool, but what's next?

### ISSUE THREAD

**Issue by ViBE-HU** [mchristopher/PokemonGo-DesktopMap#419]
Maybe I'm a noob but there is no even tutorial for basics and I have no clue what the hell should I do next after logged in with PTC account:

![poglivemap](https://cloud.githubusercontent.com/assets/640109/17271701/0b381c3e-5683-11e6-8d00-87d27e855853.jpg)

**Comment by MariusWolflord** [comment]
I would probably recommend re-logging in and or close the application and open it up again. If that doesn't work, revert to an older version. Once you log in, it should look like google maps with pokemon popping up as per your search filters

**Comment by ViBE-HU** [comment]
@MariusWolflord I tested a few recent versions. Same issue.

**Comment by MariusWolflord** [comment]
1.0.3 works fine for me, I think I've seen that kind of screen shot appear
before in the issues, look around. Out of all the map tools and apps out
there, this is still the best.
