### ISSUE TITLE
Pokemon not appearing on windows?

### ISSUE THREAD

**Issue by pokemonTracker10** [mchristopher/PokemonGo-DesktopMap#42]
my map is working but there are no pokemon appearing at the moment could I please get some help I would love to have this map working.

**Comment by fenixasin** [comment]
Could be the servers are not refreshing, give it some time. reload.

if they show up please post update here so we can mark this issue resolved.

**Comment by pokemonTracker10** [comment]
Just refreshed and got no progress @fenixasin

**Comment by IMNoob1** [comment]
Have you tried a different location to confirm something is bugged?

**Comment by pokemonTracker10** [comment]
I just tried changing the map and it would not load and I tried it on my mac and it does not show any pokeomon either. @fenixasin @ IMNoob1

**Comment by fenixasin** [comment]
are you on version 0.0.5?

**Comment by pokemonTracker10** [comment]
yes on my windows but my mac is not let me check   @fenixasin

**Comment by pokemonTracker10** [comment]
it is not working on my mac or windows, I get location but no pokemon @fenixasin

**Comment by pokemonTracker10** [comment]
want me to put a picture of what I am seeing? @fenixasin @mchristopher

**Comment by xlirik** [comment]
Same, win7/10
PokemonGo-DesktopMap v 0.0.6
Console:
ERROR in app: Exception on /static/jquery.js [GET]
Traceback (most recent call last):
  File "packages.zip\flask\app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "packages.zip\flask\app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "packages.zip\flask\app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "packages.zip\flask\app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "packages.zip\flask\app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "packages.zip\flask\helpers.py", line 892, in send_static_file
    cache_timeout=cache_timeout)
  File "packages.zip\flask\helpers.py", line 633, in send_from_directory
    filename = safe_join(directory, filename)
  File "packages.zip\flask\helpers.py", line 603, in safe_join
    return os.path.join(directory, filename)
  File "C:\Users\admin\Desktop\Новая папка (6)\resources\app\pywin\lib\ntpath.py", line 85, in join
    result_path = result_path + p_path
UnicodeDecodeError: 'ascii' codec can't decode byte 0xcd in position 21: ordinal not in range(128)

**Comment by Fritak** [comment]
I have same error on linux x64, but 0.0.7 doesn't fixed it:

> Python: [2016-07-21 13:59:13,525] ERROR in app: Exception on /static/jquery.js [GET]
> Traceback (most recent call last):
>   File "packages.zip/flask/app.py", line 1988, in wsgi_app
>     response = self.full_dispatch_request()
>   File "packages.zip/flask/app.py", line 1641, in full_dispatch_request
>     rv = self.handle_user_exception(e)
>   File "packages.zip/flask/app.py", line 1544, in handle_user_exception
>     reraise(exc_type, exc_value, tb)
>   File "packages.zip/flask/app.py", line 1639, in full_dispatch_request
>     rv = self.dispatch_request()
>   File "packages.zip/flask/app.py", line 1625, in dispatch_request
>     return self.view_functions[rule.endpoint](**req.view_args)
>   File "packages.zip/flask/helpers.py", line 892, in send_static_file
>     cache_timeout=cache_timeout)
>   File "packages.zip/flask/helpers.py", line 633, in send_from_directory
>     filename = safe_join(directory, filename)
>   File "packages.zip/flask/helpers.py", line 603, in safe_join
>     return os.path.join(directory, filename)
>   File "/usr/lib/python2.7/posixpath.py", line 73, in join
>     path += '/' + b
> UnicodeDecodeError: 'ascii' codec can't decode byte 0xc5 in position 16: ordinal not in range(128)
