### ISSUE TITLE
Installation Error: "Command failed: 4294967295"

### ISSUE THREAD

**Issue by psychoblue** [mchristopher/PokemonGo-DesktopMap#423]
![uncaughtexception](https://cloud.githubusercontent.com/assets/20744140/17272899/508b2374-5671-11e6-8805-28597983d120.png)

I get this error when installing the program ver 0.1.5.  My API is configured correctly, but that shouldn't matter at this point as I'm not even attempting to log in.  Just install.  Something I missed?  Thanks everyone.

**Comment by harshmasters07** [comment]
whats your answer.....plz tell me tooo  same problem

**Comment by psychoblue** [comment]
Closing issue.  With Niantic being douchy and just removing features instead of fixing problems, I've uninstalled the game and no longer care.
