### ISSUE TITLE
Notification spam

### ISSUE THREAD

**Issue by capgames** [mchristopher/PokemonGo-DesktopMap#424]
Any time a pokemon in my notification list despawns off the map i get 12 notifications spamming me even if i recieved the notification when it spawned

**Comment by daveydz3** [comment]
this seems to happen to me too

**Comment by pgtc** [comment]
Same with me, not sure if it's related but seems like notification spam has only been happening with the lure spawns.

**Comment by tinarazzburton** [comment]
Happened to me with a lure spawn as well.

**Comment by depraz** [comment]
Yes, I've got this error too running windows 10 64-bit
