### ISSUE TITLE
Issue with pokemon sprite visibility

### ISSUE THREAD

**Issue by Vellioh** [mchristopher/PokemonGo-DesktopMap#425]
Like other users have reported before I've been having issues seeing any Pokemon showing up in scans.  This was additionally odd because it works completely fine on my other computer.  Upon further tinkering I noticed that If I put an alert on a common Pokemon the system recognizes locations of them nearby so the issue isn't that the scanning isn't working properly just that the sprites arn't being displayed for some reason.  I've tried reinstalling and ensured multiple times that the "View Pokemon" switch was turned on and its still having this issue.  I'm completely stumped.

**Comment by pill0ws** [comment]
I had that issue and immediately resolved it by running the app in administrator mode. Try that out, it seemed to work for me
