### ISSUE TITLE
Map not working

### ISSUE THREAD

**Issue by conklin75** [mchristopher/PokemonGo-DesktopMap#426]
I've been using version 0.0.5 since last week with great effectiveness. Any reason it stopped working today? It stopped around 3pm. I tried to use other versions but none of them seem to generate as many pokemon or a decent radius

**Comment by conklin75** [comment]
before
![image](https://cloud.githubusercontent.com/assets/20747836/17274159/9d1ce75c-56a0-11e6-98bf-9bb55f59af15.png)
after
![image](https://cloud.githubusercontent.com/assets/20747836/17274158/89669bea-56a0-11e6-926b-53fa312f4b3c.png)

**Comment by markus-zhang** [comment]
I believe this is a Niantic issue as it seems that they cut the spawn rate in the new patch.

**Comment by conklin75** [comment]
it's definately not showing everything anymore
