### ISSUE TITLE
NUPKG files?

### ISSUE THREAD

**Issue by Drewbacca81** [mchristopher/PokemonGo-DesktopMap#427]
Ok, this is another noob question. What are the NUPKG files that say "full" and "delta" at the top? I just usually use the zip or exe file for what OS I'm using. What are the other files?

**Comment by 141** [comment]
They open up with 7zip on windows, and it contains everything needed to use the app. Just extract the \lib\net45\ folder to a PokemonGoMap_1.6 folder (to make things less confusing) and use it. I like the option better than the exe file. All I know is I don't need the delta file, it's probably for programing changes or info.
