### ISSUE TITLE
mobile: lat/long / refresh

### ISSUE THREAD

**Issue by fenixasin** [mchristopher/PokemonGo-DesktopMap#43]
any chance to be able to see the lat long on mobile to update, that was I can have a tighter search range via steps. And the refresh button on mobile would be good as well.

**Comment by fenixasin** [comment]
along with this to elaborate on the tighter steps


from the login page, if we can change the Step# from the screen with a fill in box

**Comment by IMNoob1** [comment]
Sounds good and I think it's an easy implement (?) like fetching the lan/lat?

**Comment by fenixasin** [comment]
not exactly, to be able to change the lat/long from the mobile.

so I can have say a 3km step and move to different areas around town and have a tight radar

could be done with multiple saved places/ corodinates

**Comment by IMNoob1** [comment]
Meaning decrease the st (7/10 to around 2/3 for fast interval) and multiple locations?

**Comment by fenixasin** [comment]
yea, selection of save locations with names from login instead of looking up and retyping the lat/long of each location you wish to preview or view live when hunting.
