### ISSUE TITLE
First Login ok from second time Error

### ISSUE THREAD

**Issue by Niniania** [mchristopher/PokemonGo-DesktopMap#434]
![pokemonerror](https://cloud.githubusercontent.com/assets/20751053/17275393/d1eeaf12-56fd-11e6-8f95-f0954740d53b.jpg)

**Comment by ffpenski** [comment]
Same problem occured from first login. Instead of map see javascript error msg ^/\^

**Comment by ffpenski** [comment]
Please refer to #412 . Problem already solved :)

**Comment by ekse89** [comment]
I have the same error as Niniania, I have done what ffpenski suggested but it did not remove the error. Any other ideas?

**Comment by Niniania** [comment]
I followed the steps with enabling APIs but it hasn't resolved it for me either.
