### ISSUE TITLE
Scanning Error after update

### ISSUE THREAD

**Issue by emregency** [mchristopher/PokemonGo-DesktopMap#435]
I have just pulled the latest release. Since then, I am getting a Scanning Error after the login.

`[        search] [  ERROR] Scanning error @ ConnectionError: HTTPSConnectionPool(host='android.clients.google.com', port=443): Max retries exceeded with url: /auth (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x00000000040D3D68>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))`

**Comment by emregency** [comment]
After removing the -st option, I was able to log in.

**Comment by steppeulv** [comment]
How's that done?
