### ISSUE TITLE
Work together with BrianEstrada/PokeScanner

### ISSUE THREAD

**Issue by Jenneuuuuh** [mchristopher/PokemonGo-DesktopMap#439]
Hello,

I think it would be a good idea to talk with the developers of the Pokescanner ( Android app - Available on Github ). I have both their app and the this one. Both find different pokémon and both are accurate. ( most pokemon are find in both apps but not all )
If you two would work together you would have the ultimate app.
I don't know anything about programming but seemed like a good idea. 

Cheers. ( Sorry for language mistakes, i'm dutch )

**Comment by AVellucci** [comment]
@mchristopher Might be something to look into, I know that PokeScanner doesn't use Python or Node but maybe you guys can find a way to work in a new algorithm for location scanning as the Speed fix is now a huge issue.
