### ISSUE TITLE
Niantic is shutting down scanners

### ISSUE THREAD

**Issue by pill0ws** [mchristopher/PokemonGo-DesktopMap#440]
So pokevision just shut down at the request of Niantic. Over the course of today an new patch was released for the game as well as older versions of the app not functioning properly. The Ceo warned of this in a recent interview and I think that Niantic has taken server side measures to prevent "rare farming". I think this includes limiting update rates, limiting event triggers by speed in general as well as detection software that will deny any further updates at all if triggered and huge changes in distance covered between nodes maybe a trigger. I've been experimenting with older versions and none seem to be capable of running multiple scans anymore and once even attempting to do so, it seem like no scan at all will work without completely rebooting. I'd be concerned about "watchers" now as these changes could mean other changes as well that arent as apparent. 

0.1.2 is still working properly although limited to one instance of the app now. The speed is acceptable and seems to find everything. The unfortunate side is the reason that version was scrapped, the tunnel service was too problematic. Those that can set it up as a server will find it still function well but needs a signout between position changes so as not to trigger the huge distance gap detector (I just made that up but it certainly feels like its a thing now)

 So the development of this App may soon be compromised as the next step is to shutdown any/all GIT Hub projects. I hope not but I am willing to bet with the removal of the footsteps and the shutdown of pokevision as well that Niantic will add functionality to the pokemon+ watch that simulates scanning to a very controlled and limited degree.  It probably wont be nearly as cool either but it would be the only way to actually track something. "Shenanigans!"

**Comment by intraum** [comment]
can't confirm this for sure, but i live in a rural area and since the update, scanning has seemingly stopped pokemon from spawning, my area is almost empty now.. if niantic have an algorithm to detect scanning, which seems possible, its also possible theyre punishing ppl for scanning, and i would be surprised if anyone else in my village plays, never mind scans.

**Comment by tinarazzburton** [comment]
intraum, that wouldn't make much sense since I would expect the more populated the area (such as New York City), the more likely people are playing pokemon go and the more likely people are using scanners.  If they punished entire areas for scanning, you'd have to assume that places like Central Park would abruptly stop spawning pokemon.

**Comment by cyan** [comment]
no but they changed pokemon nest spawn, that might be the reason for your troubles :/

**Comment by pill0ws** [comment]
Basically asking for too many updates too quickly gets you none. What still works is 0.1.6 of this App with a 2 radius and follow location on. The problem is a large radius now alerts the game. When the end of a huge spiral restarts its a large distance. For an app like this to function on the limitations theyve set, it need to abandon blanket scans. Currently I can manually changing coords by small amounts and spacing them out so as not to spam, with a radius of 2 is seems to pickup everything again. You may still be able to scan within a house distance of your current position.  As long as the update rate on the app is within the update rate set by Niantic seemingly yesterday afternoon then it will recieve an accurate scan. As long as the radius isnt over the distance threshold then it wont deny a query result. Basically you need to toggle the app on and off and use it within a small few block area. 

An alternative is exclusively called pathed scans that dont reset automatically and force a delay between ending it and beginning it. Say for instance you scan nothing at all until feedback is recieved and the feedback is in the form of a drawn path. This would at least appear to the system that there is movement that falls under their acceptable rate. I have even noticed encounters dont pop up unless I am driving much slower than before. Seems liek the event trigger system got some nerfs

**Comment by Doyoueventraps** [comment]
this game is more fun for me driving around and finding pokemon with friends. then walking around all over the city hoping for a squirtle to pop up.

when in reality actually scanning and seeing how far apart the pokemon you actually want, and now realizing they are making it way more difficult is going to draw people from the game

**Comment by cirespieler** [comment]
Pill0ws, instead of a delay the workers could reverse direction after completing the spiral.

**Comment by Ezoteric** [comment]
@pill0ws if you can keep it up keep it up and F*ck niantic 
if they cant fix their trackin system they have no right to cancel stuff like this.

If they email you give me the email and ill mail them back a nice screenshot of a botnet thats ready to ddos their servers :P

**Comment by Hearttless** [comment]
Doesn't Niantic have better things to worry about right now? like... I don't know... The f*cking servers dont even work half the time, they delayed their pokemon+ device that they've been hyping up, they pushed back their trading and breeding update and they still have f*cking pokestops in cemeteries and most of all the sole feature needed to actually play the one thing you can do in the game doesn't properly work, the nearby list. But yea, it seems appropriate for them to be focused scanners right now...
