### ISSUE TITLE
Stuck at a blank page with "Loading Please wait" (OSX)

### ISSUE THREAD

**Issue by Hamozus** [mchristopher/PokemonGo-DesktopMap#443]
Hello,
The app was working fine until a few days ago (1.5) and now won't charge the map and will remain stuck forever on Loading Please wait. Still makes my mac sweat (use of processor/memory + heating) but without the results.
I updated to 1.6 and created a new API key to no avail. Don't know what changed to cause the problem. The problem predates Niantic updates btw.
Any suggestion or help would be much welcomed :)

**Comment by AVellucci** [comment]
@Hamozus please follow #545
