### ISSUE TITLE
Customizable search patterns

### ISSUE THREAD

**Issue by vsammiel** [mchristopher/PokemonGo-DesktopMap#447]
Is there any way to implement customizable search patterns? I live on the north end of a small town that is narrow but long. With the new slower scan speeds I have several issues. Placing the origin point in the center of town makes it take quite a while to scan my immediate area barely gets to where I live and leaves a couple blocks north of me unscanned. If I move the origin point north, it misses too much of the southern end of town which is where the majority of the rare spawns are. If I increase the search radius any farther than 7, there are tons of wasted scan circles and the scan cycle takes forever.

Instead of something that spirals outward from the center, the ideal scan pattern for my situation would be a relatively narrow sweep from north to south. Or if spiraling outwards is the only option, allowing me to exclude wasted scan circles from the pattern so I could increase the radius would work as well.

**Comment by pill0ws** [comment]
this is practically a necessity now with Niantics recent changes. The spiral is now a problem for dpeed. Theres actually some huge number of static spawn points. I've noticed things in the same areas many times. They may not be the same thing (sometimes they are) but specific places always have a pokemon of some kind at some point through out the day. It would be great to log spawn points,  there are a lot but they are finite and preset
