### ISSUE TITLE
Possible to set up server WITHOUT a uname & password?

### ISSUE THREAD

**Issue by brntphish** [mchristopher/PokemonGo-DesktopMap#448]
I wrote an iOS/Mac app that used a Backdoor into pokevisions site to grab info and perform spiral searches but since that site is down it is a no go. 

I would be willing to work with someone to enable users to set up there own servers and just point my app at the server in the settings.

Can this be done without a trainer account?

Proof app was built and working 
https://m.facebook.com/story.php?story_fbid=1061613040574683&id=100001779903579&notif_t=like&notif_id=1469972903013982

**Comment by AVellucci** [comment]
@brntphish Let me get this straight, what you're asking for is for users to set up their own scanners and make them available online so you can backdoor into them and use them for yourself however you please?
