### ISSUE TITLE
How does the refresh function work?

### ISSUE THREAD

**Issue by fathey** [mchristopher/PokemonGo-DesktopMap#45]
What exactly does the refresh function? I'm not really sure if newly spawned pokemon are displayed on already scanned areas. Or do I have to restart the app everytime i want to scan the same area?

**Comment by fenixasin** [comment]
it looks like it refreshes the timers, and rescans area before the 10 minute interval is up. if new are found it adds them. 

I am under the impression this is how it works.

If this explanation works for you, please pose here so we can mark this issue as resolved.

**Comment by fathey** [comment]
Just had a closer look and it is how you explained it. Thanks!
