### ISSUE TITLE
App still working? Mine says 'waiting' at the top

### ISSUE THREAD

**Issue by ejd59005** [mchristopher/PokemonGo-DesktopMap#451]
Since last night my app has stopped working. I tried updating to a newer version, but once I login, it just says waiting, and nothing ever loads. 

Am I doing something wrong?

**Comment by NickIxo** [comment]
Historically, when this has happened to me, I re-login until it starts working. sometimes it takes just one try, but sometimes i have needed to do this 2 or 3 times.
If that doesn't resolve it, then I am unsure, but everything is working for me.
Try an older version as well, I'm still using 1.1 and its going great.

**Comment by ejd59005** [comment]
Weird. I've been using it for over a week without any issues. I've tried to logout and login multiple times. Even created a new PTC account, to no avail. 

I AM running it on a VPS. Wonder if that has anything to do with it. I just don't want to run it on my machine, since it's connected to the same network as my phone. Don't want any links to the Desktop Map and my phone.
