### ISSUE TITLE
Only scanning 1 circle at a time?

### ISSUE THREAD

**Issue by NickIxo** [mchristopher/PokemonGo-DesktopMap#452]
In the newer versions, it's only scanning 1 circle at a time for me, resulting in painfully slow scans.
How do I resolve this?

**Comment by Mirx** [comment]
You don't. Niantic changed the API to limit external apps.

https://github.com/AHAAAAAAA/PokemonGo-Map/issues/2777#issuecomment-236405364

**Comment by NickIxo** [comment]
But version 1.1 still works just fine scanning 4 circles at a time?

**Comment by Arceus** [comment]
@NickIxo It works but some pokemon may not appear.

**Comment by NickIxo** [comment]
Alright so the solution is to just run 4-5 instances of the newer versions ? or does this have a weakness

**Comment by Arceus** [comment]
That would work, but the best course of action is doing that with 5 different accounts.

**Comment by NickIxo** [comment]
I thought as much. Thankfully i have in fact exactly 5 google accounts. 
Do you think it is possible to somewhat easily program this type of feature in, wherein someone can log in with multiple names to have one awesome multi-scanner without using multiple instances?

**Comment by NickIxo** [comment]
Also where are hidden and notify pokemon stored? I ask because on one instance i have them all but in another I dont. They can't be account based because it never erased when i switched my first account.
