### ISSUE TITLE
[Bug] Upserting pokemon to the wrong location

### ISSUE THREAD

**Issue by AVellucci** [mchristopher/PokemonGo-DesktopMap#453]
I'm scanning a Radius of 4 - 5 and I noticed that outside my radius there are pokemon being upserted there.
I know the scan can't reach that spot as the pokemon are way to far for the normal scan to see. when I check the coordinates they're pointing to a location within the radius but the pokemon icon is upserted outside of it's actual location.
![pgo](https://cloud.githubusercontent.com/assets/11682773/17277945/5bfa205a-571d-11e6-9fc9-580045e05352.PNG)
you can see a Gastly, Golbat & Clefairy upserted outside the scanned radius.

**Comment by raamar10** [comment]
I am having a similar issue. On top of it, I am having more instances where a pokemon is not where it is showing on the map. I will go to the location and more around a bit and the pokemon never appears :(

**Comment by AVellucci** [comment]
@raamar10 if you check the pokemons LAT/LON and search those coordinates on google maps and go to that actual location the pokemon should be there, instead of where it's showing on the map
