### ISSUE TITLE
No Pokemon

### ISSUE THREAD

**Issue by guanxing10** [mchristopher/PokemonGo-DesktopMap#454]
When I scan for pokemon it shows no pokemon even when i know there is one next to me. This only happened to me. The pokemon switch is on. Please Help. Thank!

**Comment by avielc** [comment]
Same here

**Comment by celeritax** [comment]
Same here, new version finds nothing.

**Comment by avielc** [comment]
I would assume you all have the issue with Windows 10 and you used an old version of pokemongo map ? @mchristopher : FYI
