### ISSUE TITLE
[BUG] Map Will Not load - OSX

### ISSUE THREAD

**Issue by swimboy46163** [mchristopher/PokemonGo-DesktopMap#461]
Ever since version 0.1.4 the map will not load on OSX. Map does load on version 0.1.3. Thanks for a great Application!

**Comment by JaymerJaymer** [comment]
i've been using OS X since v 0.0.6, and still do on latest version.  its up right now.
using safari.
sometimes i have to alternate between a PTC & google login.

**Comment by AVellucci** [comment]
@swimboy46163 Can you provide the console logs or screenshots for this?

**Comment by hectorlr** [comment]
This happens to me. Console log-

>Python: Traceback (most recent call last):
  File "./runserver.py", line 22, in <module>
    from flask_cors import CORS
ImportError: No module named flask_cors

**Comment by hectorlr** [comment]
Also this:

>main.html:158 server up: null
main.html:146 Error getting location, trying second provider PositionError {code: 2, message: "Network location provider at 'https://www.googleapis.com/' : Returned error code 403."}
main.html:148 Found location [<lat>,<long>] by ipinfo.io


Note: Removed my coordinates from the console log.
