### ISSUE TITLE
Multiplayer Team idea!

### ISSUE THREAD

**Issue by Pineyka** [mchristopher/PokemonGo-DesktopMap#463]
idea of a multi-account is interesting. But I suggest another solution.
Playing alone in gaining gym is difficult and time-consuming, the team is doing it quickly. Just scan the map. Perhaps the solution would be to exchange information about the scanned areas. Each player team discovers another piece of map (smaller) and exchanged between players. Perhaps through the API or external server to exchange real-time or p2p

**Comment by AVellucci** [comment]
I understand the part where you mention having a server to consolidate the results would be nice but it's also a factor as to why this project hasn't been completely shutdown yet.

I don't understand the "team" part though, if you have a "team" would you not be together hunting? Giving strangers your whereabouts could be quite dangerous.
