### ISSUE TITLE
Stops scanning

### ISSUE THREAD

**Issue by Usernummer** [mchristopher/PokemonGo-DesktopMap#465]
After a while it stops scanning at all, and then i have to restart the program. Can this be fixed in any way?
Also i want to ask if you're working a way to make it scan faster, or if it's gonna be like this for now?

**Comment by JelleVDB** [comment]
Are you using the google login to the application? Because those timeout automatically after 30m. I had the same issue before but i'd recommend switching to a PTC account

**Comment by Usernummer** [comment]
Yea i do... Isn't a bit of trouble switching between 5 PTC accounts, or is it no problem?
