### ISSUE TITLE
[QUESTION] Reduce total search radius?

### ISSUE THREAD

**Issue by honoraryorange** [mchristopher/PokemonGo-DesktopMap#466]
Is there a way to reduce the total search radius in the app until we get a faster way to scan? Basically I'd like to cut the search area in half for now, for when I'm hanging out at a park or similar and just want to see what is close by.

**Comment by hunion99** [comment]
login screen, scroll down

**Comment by honoraryorange** [comment]
Crap, thanks! I went through every single setting like 5 times post-launch, but didn't think to look at login.
