### ISSUE TITLE
[FEATURE SUGGESTION] Upload pokemon notifications via list?

### ISSUE THREAD

**Issue by sfelman** [mchristopher/PokemonGo-DesktopMap#467]
It takes too long to upload all my pokemon I want notifications for 1 by 1. Can you add a save list feature or a quicker way to upload the pokemon?

**Comment by Usernummer** [comment]
This would be awesome.

**Comment by Drewbacca81** [comment]
Agreed. This was possible in the original releases when we put them in by comma-separated numbers.
