### ISSUE TITLE
Pokemon Go: No Icons appearing on map [Possible Windows 10 error]

### ISSUE THREAD

**Issue by neocabbitz4** [mchristopher/PokemonGo-DesktopMap#468]
Awesome work on the app to date before hand!

I noticed with the new Version 0.1.6 that although I am getting back console logs saying there are indeed pokemon and pokestops : 

2016-08-01 00:12:53,177 [search_thread-0][        models] [   INFO] Upserted 1 pokemon, 1 pokestops, and 0 gyms
main.html:168 2016-08-01 00:12:58,493 [search_thread-0][        models] [   INFO] Upserted 1 pokemon, 1 pokestops, and 0 gyms

I am not seeing the icons appearing. 

I thought it could not find the icons so I went into AppData just to double check..they indeed are there (renamed from icons to pixel_icons I see). As I am not getting any error output from the console logs, I was wondering if anyone had a clue on this bug? Should I attempt to remove the AppData and try again (though I noticed that in several other threads this was discouraged).

I should mention that I am running Windows 10. I am going to attempt a run on Fedora 21 and Windows 7 later on, but if anyone has any info that would be swell!

**Comment by neocabbitz4** [comment]
After some testing, I've noticed that there is a difference between Windows 7 and Windows 10. The linux version works without issue in Fedora 21.

**Comment by neocabbitz4** [comment]
One final test leads me to believe that there is some missing component that is targeted by the application for Windows 10. 

Could there be a missing library in the windows wrapper that is necessary for work in Windows 10? As it returns a console log about finding the pokemon (it populates Pokestops and Gyms Flawlessly) as data.msg, I am curious if a import is missing.

At any rate, the only possible solution I can give currently is this:

Use windows 7 or Linux.

**Comment by mikehaydon** [comment]
Version 0.1.6 is working fine on Win 10 for me. Perhaps you have some legacy code sticking around.

**Comment by avielc** [comment]
@mikehaydon Any chance you can think of what could be sticking around?
I have the same issue too (been using the old old version that doesn't have a versioning number anywhere)

**Comment by neocabbitz4** [comment]
@mikehaydon Is there another place that code sits besides in Appdata\Local? I attempted to look through some of the exposed code in the source but to no luck on a path.
