### ISSUE TITLE
map won't update the long/lat to new position

### ISSUE THREAD

**Issue by wseery** [mchristopher/PokemonGo-DesktopMap#47]
The map is currently not where I am located, it is across town.  I got my current long/lat and put them in at the top.  Then I clicked the set button.  In the console, it says it saved that as the next location.  Then, it goes through the steps and just does where it was before, not even going to the one I just tried to add.  I can't figure out how to change the position, since it won't update

**Comment by dittowill** [comment]
im having the same issue.

**Comment by jameskrawczyk** [comment]
Just some debug on this. 

When you enter a new location it does save it according to the console output 

```
Saved next location as LAT,LONG
127.0.0.1 - - [21/Jul/2016 05:38:38] "GET /next_loc?lat=LAT&lon=LONG HTTP/1.1" 200
```

It will then loop through the current coordinates updates up to 100% (49 of 49) and will show output 

```
Update to next location LAT, LONG
[-] register_background_thread called
[-] register_background_thread: queueing
```

It then continues on to start a new update cycle with the old coordinates.

**Comment by kogot** [comment]
@jameskrawczyk thank you for advice. Set button doesn't work. But preset location options works perfectly.
