### ISSUE TITLE
JavaScript error

### ISSUE THREAD

**Issue by nat173** [mchristopher/PokemonGo-DesktopMap#472]
![image](https://cloud.githubusercontent.com/assets/20761840/17281011/d6a60b3a-575d-11e6-8d9f-cfdaea000a94.png)

![image](https://cloud.githubusercontent.com/assets/20761840/17281021/fe5719da-575d-11e6-905c-a4476e6f1441.png)

**Comment by daGOPHERshow** [comment]
Same Issue

**Comment by iKurama** [comment]
bump

**Comment by Llewyne** [comment]
Same issue

**Comment by aradzu10** [comment]
Same :(

**Comment by heipnotik** [comment]
Same :/ 
Was working before I went to bed about 6 hours ago....
Won't show scans.

**Comment by zaqrwe** [comment]
same..

**Comment by iKurama** [comment]
https://github.com/mchristopher/PokemonGo-DesktopMap/issues/412 This will fix it ^^ I promise
