### ISSUE TITLE
Issue with nmp when installing on ubuntu 14.04 LTS

### ISSUE THREAD

**Issue by codingcoug** [mchristopher/PokemonGo-DesktopMap#473]
here is the readout I get from the terminal.
Is there another step that needs to happen in the install process? 
does it need to be extracted to a specific location? 

I coppied the files to my server via an winscp and put them in the downloads folder and the installed node and I get this in the readout. 

npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.19.0-65-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! cwd /home/user/Downloads/PokemonGoMap-Lin-x64
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! path /home/user/Downloads/PokemonGoMap-Lin-x64/package.json
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /home/user/Downloads/PokemonGoMap-Lin-x64/npm-debug.log
npm ERR! not ok code 0

**Comment by AVellucci** [comment]
@codingcoug Can you provide the Additional Log?
 `/home/user/Downloads/PokemonGoMap-Lin-x64/npm-debug.log`

**Comment by dobey-xx** [comment]
Yeah same issue here:

0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'start', 'main.js' ]
2 info using npm@3.5.2
3 info using node@v4.2.6
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle pokemon-go-map@0.1.7~prestart: pokemon-go-map@0.1.7
6 silly lifecycle pokemon-go-map@0.1.7~prestart: no script for prestart, continuing
7 info lifecycle pokemon-go-map@0.1.7~start: pokemon-go-map@0.1.7
8 verbose lifecycle pokemon-go-map@0.1.7~start: unsafe-perm in lifecycle true
9 verbose lifecycle pokemon-go-map@0.1.7~start: PATH: /usr/share/npm/bin/node-gyp-bin:/opt/PokemonGo-DesktopMap/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin
10 verbose lifecycle pokemon-go-map@0.1.7~start: CWD: /opt/PokemonGo-DesktopMap
11 silly lifecycle pokemon-go-map@0.1.7~start: Args: [ '-c', 'electron main.js "main.js"' ]
12 info lifecycle pokemon-go-map@0.1.7~start: Failed to exec start script
13 verbose stack Error: pokemon-go-map@0.1.7 start: `electron main.js "main.js"`
13 verbose stack spawn ENOENT
13 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/lib/utils/spawn.js:17:16)
13 verbose stack     at emitTwo (events.js:87:13)
13 verbose stack     at ChildProcess.emit (events.js:172:7)
13 verbose stack     at maybeClose (internal/child_process.js:821:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
14 verbose pkgid pokemon-go-map@0.1.7
15 verbose cwd /opt/PokemonGo-DesktopMap
16 error Linux 4.4.0-21-generic
17 error argv "/usr/bin/nodejs" "/usr/bin/npm" "start" "main.js"
18 error node v4.2.6
19 error npm  v3.5.2
20 error file sh
21 error code ELIFECYCLE
22 error errno ENOENT
23 error syscall spawn
24 error pokemon-go-map@0.1.7 start: `electron main.js "main.js"`
24 error spawn ENOENT
25 error Failed at the pokemon-go-map@0.1.7 start script 'electron main.js "main.js"'.
25 error Make sure you have the latest version of node.js and npm installed.
25 error If you do, this is most likely a problem with the pokemon-go-map package,
25 error not with npm itself.
25 error Tell the author that this fails on your system:
25 error     electron main.js "main.js"
25 error You can get information on how to open an issue for this project with:
25 error     npm bugs pokemon-go-map
25 error Or if that isn't available, you can get their info via:
25 error     npm owner ls pokemon-go-map
25 error There is likely additional logging output above.
26 verbose exit [ 1, true ]

**Comment by MauroMombelli** [comment]
#733  #749

**Comment by MauroMombelli** [comment]
solution: run again

    npm install

check the installation of elecrton goes fine; if not run 

    pip install virtualenv
