### ISSUE TITLE
Suggestion to scan for nearby tracker updates rather than discovery events

### ISSUE THREAD

**Issue by pill0ws** [mchristopher/PokemonGo-DesktopMap#475]
The nearby tracker literally triggers events when you cross over tracks. Tracks are somewhere in between a previous spawn point and the current. Pokemon spawn for 15m and then despawn for 15m  before respawning in a direction they are facing when you encounter them about a 15m distance at what the game considers walking. "They are all facing different directions when you encounter them, this direction is facing the next spawn point that will occur 15m after despawn.

Up until now scanners were only interested in what exactly was at every specific node in a redonkulous scan radius. However the acceptable speed, caluclated by distance of changes in coords between updates, has been reduced to trigger discovery. The acceptable speeds to trigger a change in the nearby tracker is however still very high and was always even higher than the discover speed. The nearby tracker literally allows players to triangulate on coordinates. it doesnt show a new pokemon on it until you cross a point they have been (suggestably the previous spawn node). The position on the tracker is a very simple Left, Right, Straight, or Behind you system realtive to the actual tracks themself and not to the pokemons whereabouts. For anything of high speed to work at all now it must specifically aim for tracks and responding to the event notifications for the nearby tracker. When the tracker gets to a point where the pokemon is dead center, that is when a very small/slow scan will reveal precise coordinates. This would allow a tracking pattern to simply run down a line of longitude or latitude at a high speed and respond to the nearby tracker update events. Ultimately it would allow you to just do a search for the specific thing you are looking for, track it and then stop at a location and scan slowly to trigger the discovery event.

**Comment by ej8** [comment]
Man most of that went over my head.  Are you saying this tool isn't very useful?

**Comment by pill0ws** [comment]
No, I am saying that speedy scanning of nodes is impossible but speedy scanning of the 'tracks' that update the nearby tracker are still possible. Yo ucan scan tiny areas still but the new provisions set by Niantic will trigger under certin conditions and anything over a radius of 2 will trigger them now when the scanner reaches the end of its radius then teleports back to the center. The game sees this as super fast speed that is over the threshold to discover pokemon within range. If you drive down the road over 25mph you will not trigger pokemon discoveries either. Previously it was around 35mph to see them pop up, they really want you to walk now but in reality you can cover more tracks moving at high speed.
