### ISSUE TITLE
Step 4 - ".........enable the Javascript API" ?

### ISSUE THREAD

**Issue by ej8** [mchristopher/PokemonGo-DesktopMap#476]
I got the key for Step 4. Where do you enable the Javascript API?  When I log in and enter my API key I get a millisecond view of the map and then it changes to the grey screen with "Oops! Something went wrong.  This page didn't load Google Maps correctly. See the JavaScript console for technical details."

<img width="797" alt="screenshot 2016-07-31 22 32 34" src="https://cloud.githubusercontent.com/assets/16333236/17281990/c34d7274-576e-11e6-8b5d-33c06e4492cd.png">

**Comment by magicnld** [comment]
You can fix this problem simple. follow this steps.

Authentication for the standard API — API keys

Get an API key

To get started using the Google Maps JavaScript API, click the button below, which takes you to the Google API Console, guides you through the process, and activates the Google Maps JavaScript API and any related services automatically.

GET A KEY

Alternatively, follow these steps to get an API key:

1Go to the Google API Console.
2Create or select a project.
3Click Continue to enable the API and any related services.
4On the Credentials page, get a Browser key (and set the API Credentials). 
5Note: If you have an existing Browser key, you may use that key.
6To prevent quota theft, secure your API key following these best practices.
7(Optional) Enable billing. See Usage Limits for more information.

**Comment by joshuacane** [comment]
I had the same issue for about a day until I looked further into it. Turns out, the problem isn't in the code at all. It's the fact that the API key has letters that look alike. I ended up typing uppercase I's instead of lowercase L's which look alike. I copied and pasted each individual letter that I wasn't confident with on google search to see what letter it would be. Once I corrected the issue, I typed it in and it worked perfectly.

**Comment by lordofire** [comment]
Same issue here, tried as joshuacane mentioned, but still did not work

**Comment by richardgetz** [comment]
Also not working for me.

**Comment by ej8** [comment]
@joshuacane   why aren't you just copying and pasting?  That is what I've done.  Could that be inaccurate?

**Comment by richardgetz** [comment]
Coy and pasting normally works for me with Maps API. That is not the issue.

**Comment by Genek1968** [comment]
Copying and pasting is not working for me
