### ISSUE TITLE
Multiple Scans, one screen?

### ISSUE THREAD

**Issue by shuyin82** [mchristopher/PokemonGo-DesktopMap#478]
I am running a facebook group for my town and I currently have the mobile link shared on the page so people in the group can scan in town, is there any way I can scan 5 times but show it all on one single screen? The link provided to my group would show the results of all 5 scans on 1 single map?

**Comment by SmilinItalin** [comment]
im trying to figure this out........but it seems when i do mutiple scans it stacks the scans already?
