### ISSUE TITLE
map spawn radius

### ISSUE THREAD

**Issue by krazor8** [mchristopher/PokemonGo-DesktopMap#48]
any way to increase the shown spawn radius of pokemon to show pokemon further way?

**Comment by Codys4x4** [comment]
This would be very helpful, I'd also like to know the answer to this.

**Comment by jameson167** [comment]
In the PokemonGoMap-Win\resources\app folder,
open the main.js file.
There is a step-limit line that is default set to '7' or '10'
If you increase or decrease that range it makes the range larger or smaller.

I am not sure on how to change the coordinates that the app loads without having to completely shut down the app and re-open it with new coordinates on the login screen. Is there any better way to update "location" without having to restart the app?

**Comment by fenixasin** [comment]
reference #42,43,47

**Comment by mchristopher** [comment]
This should be on the login page in version 0.0.6.

**Comment by krazor8** [comment]
ive chnagedthe 7 to a 10 increase is good, would be a great option to add when able

**Comment by itsjustmeman** [comment]
how do you do this on OS X, also is there a fix to the set location? i don't love in California next to the staples center.

**Comment by krazor8** [comment]
i went to playstore(app store for iphone) and download a app to show my lat and long based on gps and typed in the coordinates before i hit log in
