### ISSUE TITLE
Scanner

### ISSUE THREAD

**Issue by Doberok** [mchristopher/PokemonGo-DesktopMap#480]
it seems that the scanner began to work poorly or does not work, can not find the Pokemon nearly on the map , before the park was a lot , had to hide , and now there is almost no

**Comment by aquastrike** [comment]
Same problem here. Used to work very well. Starting July 31 after update of the pokemon go, the scanner can only find much less pokemons for some reason.

**Comment by Frikoriko** [comment]
Seems to work the same for me. I wish there was an auto refresh interval.
