### ISSUE TITLE
Can't see any pokemon 

### ISSUE THREAD

**Issue by jstarmu1999** [mchristopher/PokemonGo-DesktopMap#481]
![capture](https://cloud.githubusercontent.com/assets/20766605/17285862/57694e8c-577a-11e6-87fa-f3bf8415f96c.PNG)

Pokestops and gyms are displaying correctly. However I can see any pokemon on the map. Please help me.
I am using Windows 7.

Many thanks,

**Comment by avielc** [comment]
Also issues on #468 #454 and probably a few other older posts, all related to Windows 10 and probably upgrades from older version. (might not be related in this case, but its not a single user issue anymore)
@mchristopher 
@jstarmu1999 - care to add a console log to see if it actually "Upserts" the pokemons to the map or not.
Thanks
