### ISSUE TITLE
[Suggestion] Check-mark to toggle hidden pokemon

### ISSUE THREAD

**Issue by KERL0N** [mchristopher/PokemonGo-DesktopMap#482]
It's nice that we can hide the most common pokemon and the ones that we are not interested in, but sometimes (like when I need to catch a bunch of different pokemon to have 50-60 evolutions possible for a lucky egg) I want to see all of them. I can remove the pokemon from the list, but I would have to add all of them back right after. A useful feature would be to have a check-mark that enables/disables hiding the pokemon . I check that when I need it and I don't have to edit the list twice, saving time.

**Comment by Mirx** [comment]
I would like that feature. Both for switching too "stardust collection" mode, and to get a better feel if a sector is properly monitored due to the recent changes in the API.

**Comment by Ixlyth** [comment]
I came here specifically to suggest this feature for both toggling hidden pokemon AND for toggling alerts.
