### ISSUE TITLE
IDP.ARES.GENERIC VIRUS found in update

### ISSUE THREAD

**Issue by PureMassacre** [mchristopher/PokemonGo-DesktopMap#483]
The update on 31/7/16 came up with this in the squrril file WTAF?

**Comment by zaqrwe** [comment]
it's something with windows 10. On windows 7 there is no AVG detection for me. But still I got error in installation and can't load map

**Comment by AVellucci** [comment]
The file is not a virus, please see the VirusTotal page provided.
[VirusTotal](https://www.virustotal.com/en/file/455fdb254ce8e4bf83991ae22b37e11c9e4c33df0941ab9c7f31863abebc21cf/analysis/)
