### ISSUE TITLE
[Suggestion] Crowdsourced scanning

### ISSUE THREAD

**Issue by kaspervdl** [mchristopher/PokemonGo-DesktopMap#484]
I see a lot of issues/suggestions about using multiple accounts to increase scanning speed and range, but when people do this, this will result in areas getting scanned multiple times.
If we would all share our scanning results, this would increase scanning efficiency, and scanning range as well.

Ofcourse there would have to be a way to prevent fake result sharing, and there will have to be a dedicated server to host the results, but maybe its a good idea?

**Comment by TheFalseKing** [comment]
I'd love something like this. Only issue is that the information is obsolete within 15 minutes.

**Comment by mygo89** [comment]
i'd like this option if i could enable it for nearby scans, i wouldn't want to see scans that are out of my reach of time getting there.

**Comment by kaspervdl** [comment]
Well, it could be very usefull for scans just out of your reach, for example in my town, there is a pikachu and nidoran nest, and by looking at scans that are just out of reach, you can determine if its worth a visit if it looks like a nest.

**Comment by kaspervdl** [comment]
Ive thought a bit more about this, and a simple way to keep out fake results would be to allow users to hide results from certain users. For example when you find results from someone else and they appear fake, just hide them.

Also, about the obsolete after 15 minutes part: if multiple people have scanners at fixed locations, they retrieve new information every time, so its not just usefull for 15 minutes, but for as long as the scanner is on :)
