### ISSUE TITLE
Problem with map

### ISSUE THREAD

**Issue by RazorShaman** [mchristopher/PokemonGo-DesktopMap#485]
I have a problem with a display of the map: in old version there is no map, only settings that don't work; and in new 0.1.6 there is only "loading please wait" message and nothing more. How can I solve this?

![111111](https://cloud.githubusercontent.com/assets/20768365/17288062/b71ab86e-57db-11e6-8fbc-ac238f219863.png)
![11111](https://cloud.githubusercontent.com/assets/20768365/17288064/bbdf2146-57db-11e6-8971-ee6f98310ddf.png)

**Comment by sossienl** [comment]
I get this error in the console: 

MAP: Uncaught TypeError: Cannot read property 'getSouthWest' of undefined

**Comment by AVellucci** [comment]
@RazorShaman Please follow #545
