### ISSUE TITLE
Notify of Pokémon

### ISSUE THREAD

**Issue by Aradax666** [mchristopher/PokemonGo-DesktopMap#488]
When trying to add pokemon to the Notify list (NoP), if adding too many the selectable list appears off screen.
At the top on the below example.
![capture](https://cloud.githubusercontent.com/assets/20771115/17292259/c35aa760-57e0-11e6-86f4-10303f6a28bf.JPG)

**Comment by Aradax666** [comment]
Seems to have corrected itself. Or you have sorted it.  Selectable list now appears under the NoP box.

**Comment by DavidBabel** [comment]
It depends on your scroll position

**Comment by ssutcher** [comment]
I have this issue as well. I find that if I search by typing instead of scrolling and clicking it works a lot better.
