### ISSUE TITLE
[Suggestion] Scan between two points &/or PATH?

### ISSUE THREAD

**Issue by ineiva** [mchristopher/PokemonGo-DesktopMap#489]
Hi, 

first of all thanks for your program, it works wonderfully and it's extremely useful. 

Since you've added the chance to change the scanning area without logging out, I've been thinking if would it be too difficult to implement scanning between two points as opposed to the spiral that the program runs by default? Better yet would be if it were possible to scan along a determined path by putting in 3 or more POIs... I don't know if this is a Farfetch'ed request but anyways...

Thanks for your time!

**Comment by beestiel** [comment]
I'd love to be able to define an area (kind of like you can on Google Maps) for scanning as well. My apartment complex is irregularly shaped, and I can't really get the program to scan just the area I need.
