### ISSUE TITLE
Linux App does not work

### ISSUE THREAD

**Issue by heipnotik** [mchristopher/PokemonGo-DesktopMap#492]
Downloaded lin.zip
Executable does not work. Not sure how to install or run.

**Comment by erylflynn** [comment]
Same here, does not work.  I tried older versions and got farther with 1.2, I was able to login but it wouldn't load the map.  Running arch x64 myself.

**Comment by MeTheRebel** [comment]
PokemonGoMap-Lin-x64.zip, v. 0.1.6 works perfectly for me on Fedora 24

**Comment by nahga** [comment]
There is nothing to install for the Linux version. Just unzip and run the Map executable. I'm running it under fedora 23. I did receive an error about javascript, but then found out I needed a server api key from google. Once that was generated and added, all was well.

Some stats:
Linux local 4.5.7-202.fc23.x86_64 #1 SMP Tue Jun 28 18:22:51 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
