### ISSUE TITLE
much less pokemon found since July 31 update 

### ISSUE THREAD

**Issue by aquastrike** [mchristopher/PokemonGo-DesktopMap#493]
After yesterday (July 31) update of Pokemon Go, I found much less Pokemon species could be found. I used be able to find much more rare species, but yesterday, almost zero. In the region I often scanned to find many pokemon, yesterday, almost nothing. Has Niantic found a way to avoid the scanning or they don't spawn that many good pokemon any more as before?

**Comment by AVellucci** [comment]
Thsi is related to Niantic's Speed Check, once you jump from the last scan of your radius back to the center of it you trip the speed check and no pokemon will effectively spawn until the triggered speed check is reset. for better results use multiple instances with smaller scan radiuses.

**Comment by Ezoteric** [comment]
I have disabled all commons and i still get plenty of uncommon and rare spawns...

**Comment by G0rzilla** [comment]
I am new to all this how do you use multiple instances?
I am also getting allot less.
Please helps

**Comment by AVellucci** [comment]
@G0rzilla multiple instances means run more than one scanner and use a unique account for each one with different coordinates in each one.

**Comment by G0rzilla** [comment]
Ah thanx @AVellucci how many accounts should I create I have one currently (not my main one) and scanning at about 4 zones? Thank you for the quick response.

**Comment by KikkomanChow** [comment]
@AVellucci are there any method to run with multiple accounts but use the same window? I think that would be great information knowing now about the restrictions in place.

**Comment by AVellucci** [comment]
All the instances use the same map already, I don't understand the question.
Just start them all up with their coordinates and minimize all but 1.

**Comment by G0rzilla** [comment]
@Ezoteric what version you using?

**Comment by Ezoteric** [comment]
the screenshot was from Version 0.1.3  but i use that and the new one to see if i indeed get all spawns.

**Comment by aquastrike** [comment]
@AVellucci thanks for comments. What is the speed check? Did you mean that one spot
can only spawn after a certain time period since your last scan? I don't quite get it. I followed your suggestion to use multiple small radius scans, it's not improving the searching results at all.

**Comment by AVellucci** [comment]
@aquastrike Are you using multiple accounts or just one PTC account run through multiple instances?

**Comment by Holli357** [comment]
Do you need multiple Google Maps API keys, as well as multiple accounts in order to run multiple instances?

**Comment by aquastrike** [comment]
@AVellucci I used only one account

**Comment by ssutcher** [comment]
Interesting. I actually find that after the update I see more rare pokemon around me.

**Comment by AVellucci** [comment]
@aquastrike if you run multiple instnaces you should use multiple accounts as jumping from one location to another too quickly now trips a safeguard in PGO that stop pokemon from spawning on your map.
using multiple accounts with smaller radii and setup to scan an area you'll see improvements in scans.
