### ISSUE TITLE
[ERROR!]

### ISSUE THREAD

**Issue by jsrider** [mchristopher/PokemonGo-DesktopMap#494]
Oops! Something went wrong and we couldn't log you in. Please try again.
Unable to exchange token for authorization code.
why?

**Comment by cvnation1** [comment]
need api key

**Comment by jsrider** [comment]
I have provided API key

**Comment by cvnation1** [comment]
pfff now i have the same problem

**Comment by AVellucci** [comment]
Please provide more details, logs, screenshot etc... will help diagnose this.

**Comment by Mirx** [comment]
The PTC servers seem to be on the fritz again.

[ search_thread][      auth_ptc] [   INFO] PTC Login successful
[ search_thread][        pgoapi] [  ERROR] Login failed - unexpected server response!
[ search_thread][        search] [   INFO] Failed to login to Pokemon Go. Trying again in 5 seconds.
[ search_thread][      auth_ptc] [   INFO] PTC login for: obscured
[ search_thread][      auth_ptc] [   INFO] PTC Login successful
[ search_thread][        search] [   INFO] Login to Pokemon Go successful.
[search_thread-0][        models] [   INFO] Upserted 0 pokemon, 7 pokestops, and 3 gyms
[     Thread-60][           app] [   INFO] Changing next location: xxx
[ search_thread][        search] [   INFO] Search loop 0 complete.
[ search_thread][        search] [   INFO] Waiting 5 seconds before beginning new scan.
[ search_thread][        search] [   INFO] Search loop 1 starting
[ search_thread][        search] [   INFO] New location set
[ search_thread][        search] [   INFO] Attempting login to Pokemon Go.
[ search_thread][      auth_ptc] [   INFO] PTC login for: obscured
[ search_thread][      auth_ptc] [  ERROR] No JSON object could be decoded... server seems to be down :(
[ search_thread][        search] [   INFO] Failed to login to Pokemon Go. Trying again in 5 seconds.
[ search_thread][      auth_ptc] [   INFO] PTC login for: obscured
[ search_thread][      auth_ptc] [   INFO] Seems not to be a PTC Session Token... login failed :(
[ search_thread][        search] [   INFO] Failed to login to Pokemon Go. Trying again in 5 seconds.
[ search_thread][      auth_ptc] [   INFO] PTC login for: obscured
[ search_thread][      auth_ptc] [  ERROR] No JSON object could be decoded... server seems to be down :(
[ search_thread][        search] [   INFO] Failed to login to Pokemon Go. Trying again in 5 seconds.
[ search_thread][      auth_ptc] [   INFO] PTC login for: obscured

**Comment by abdulsettarova** [comment]
![image](https://cloud.githubusercontent.com/assets/20702299/17305792/ee572a0c-5834-11e6-9b18-244eefb9679e.png)
what is it???????????
