### ISSUE TITLE
[Suggestion] Alerts for specific rarities

### ISSUE THREAD

**Issue by ElNamano** [mchristopher/PokemonGo-DesktopMap#495]
It would be nice to get alerts when an Uncommon/Rare/Very Rare Pokemon appears.

**Comment by StewieGriffin** [comment]
Check "Options" on the upper left corner, you can customize your alerts for every pokemon already

**Comment by AVellucci** [comment]
While it is true that there is no blanket rule for rarity just adding the pokemon to the notify list should be just as good. I'm sure there are some rarities where you don't want to get notified for all the pokemon of that tier, so I don't see why a specific rule should be downgraded to be a vague rule instead.

**Comment by ElNamano** [comment]
It wouldn't need to downgrade the current system. What about just typing "Rare" into the list and having that work?

**Comment by MacDogg** [comment]
Also how about being able to **hide** all Common/Uncommon/Rare/Ultra Rare in a single rule?
For me I want to see only the Commons (easy capture for dust) and Ultra Rare.
