### ISSUE TITLE
Mobile Sharing

### ISSUE THREAD

**Issue by enokisoju** [mchristopher/PokemonGo-DesktopMap#496]
When enabled and I try the address it says no Tunnel not found? Any suggestions

**Comment by TheValliant** [comment]
If you've closed the program and reopened it, by default mobile sharing will have been disabled and the address will have changed.

**Comment by nahga** [comment]
Also the address changes every time you run the app again, can always pay ngrok for a static name and change the code base of the program, or just update the url on your phone when you re-launch it.

**Comment by enokisoju** [comment]
tyvm =)

**Comment by starstremr** [comment]
i have a year of a static ngrok.io all i do is run the map program and run ngrok have my ngrok shortcut point to C:\PokemonGo\ngrok.exe http -subdomain=your subdoamin here 8001 and it works any where i go on any device with web browsing so far.
