### ISSUE TITLE
[Request] Reset scanned circles + multi-account automation

### ISSUE THREAD

**Issue by MrAwesomers** [mchristopher/PokemonGo-DesktopMap#497]
Since they broke the fast scan option, I've started using multiple clients (4) with a smaller radius. The problem is placing the markers on the correct position. When I start, I place them randomly and after each complete cycle, I can move them a bit closer to each other. After doing this a few times, it's really hard to see anything underneath all those circles.

I'd like to see an option to reset the circles, to "start fresh" without removing previous scanned pokemon.

Or even better, make us able to login with 4 or more clients at once, spreading them around the selected coords automatically on the correct coords depending on the radius you choose to scan. Right now, it's a lot of work when you decide to hunt other cities or if you want to scan cities while you are at home/work to find spawns of certain pokemon in nearby towns. 

See screenshot - The entered coords would be in the center, and the 4 clients scan around. Waiting in the middle of the scanned zone, will allow you to get to the scanned pokemon on time.

![screenshot 2016-08-01 at 17 37 07](https://cloud.githubusercontent.com/assets/20760672/17299451/a90193c8-580e-11e6-8436-fa82575873b2.PNG)

**Comment by G0rzilla** [comment]
Would even say it would help when you move the markers it will show like a grayed out area of till where the scan will go then you can easy find placements.
