### ISSUE TITLE
[Suggestion] Multi-threaded searching with multiple PTC accounts

### ISSUE THREAD

**Issue by TheRadGasm** [mchristopher/PokemonGo-DesktopMap#498]
There's a mobile app that does this, and it dramatically speeds up scan times.

Also, I would love to see multiple scan sites, like one for home and one for work.

Oh, and app auto-updates would be nice!

Thanks so much for this - it's a great app!

**Comment by cvnation1** [comment]
NAME

**Comment by jane0815** [comment]
Yes that would be great. Now scanning is too slow. 

What mobile app are you talking about @TheRadGasm?

**Comment by roflinger** [comment]
yep prefer this too

**Comment by voidpublic** [comment]
https://github.com/PokeGoRadar/pokegoradar does this for example
