### ISSUE TITLE
Outage

### ISSUE THREAD

**Issue by Gentleman-Taco** [mchristopher/PokemonGo-DesktopMap#499]
Is there a way to see updates on outages? My map worked for about an hour but has been on red Outage since.

**Comment by AVellucci** [comment]
@Gentleman-Taco Are you using PTC of Google?

**Comment by Gentleman-Taco** [comment]
Google

**Comment by crdistructo** [comment]
I am having the same problem

**Comment by AVellucci** [comment]
This is due to Google accounts being logged out by google after 30 minutes.
Re-login and you'll be able to see it again for another 30 minutes.
PTC can run indefinitely.

**Comment by Gentleman-Taco** [comment]
ah ok. Might have to make a PTC account. Wish I would remember my location though. Thanks for the help!
