### ISSUE TITLE
Multiple errors w/ linux

### ISSUE THREAD

**Issue by tomtobac** [mchristopher/PokemonGo-DesktopMap#5]
`
AttributeError: 'tuple' object has no attribute 'parent_pid'
`
`
AttributeError: lat and lng required
`
on 4.4.0-31-generic GNU/Linux
and using python 2.7

**Comment by AVellucci** [comment]
@tomtobac Can you confirm if this is still occurring for you in any of the recent releases?

**Comment by tomtobac** [comment]
@AVellucci solved already with the new updates. thanks! :-)
