### ISSUE TITLE
pop-up error! "uncatch exeption" 

### ISSUE THREAD

**Issue by aradzu10** [mchristopher/PokemonGo-DesktopMap#500]
when I open the program, he pop-up that there is an uncatch exeption and the map allways crash.
https://s32.postimg.org/qfpoi3jk5/image.png
that is the error 
http://www.filedropper.com/squirrelsetup
her is the log
Pls help

**Comment by heipnotik** [comment]
I have the same issue.

**Comment by gearan** [comment]
I have been having the same error, but then my map loads, but some pokemon I normally see are not there anymore (like eevee). This didn't happen the first day I tried the 0.1.6 update

http://prntscr.com/c0c922

**Comment by abdulsettarova** [comment]
![image](https://cloud.githubusercontent.com/assets/20702299/17305810/13553e84-5835-11e6-983e-661fede7c453.png)
what is it?????
