### ISSUE TITLE
Multiple instances?

### ISSUE THREAD

**Issue by ejd59005** [mchristopher/PokemonGo-DesktopMap#501]
This is probably an easy one for you guys, but how can I run multiple instances? I have one running, then when I attempt to run another, the first one closes and the second one opens. How can I run multiple at a time?

**Comment by MrAwesomers** [comment]
What operating system are you using?

**Comment by ejd59005** [comment]
Windows 10

**Comment by MrAwesomers** [comment]
There are two primary ways to run another copy of an app that’s already open on your PC, and the methods work the same on Windows 7, Windows 8, and Windows 10. The first method is to right-click on the app’s icon in the taskbar, and then left-click on the app’s name in the pop-up menu that appears. This will open a second instance of the app as if it were being launched for the first time.

I don't even use windows.. That took me 5 seconds using google.

**Comment by ejd59005** [comment]
Thanks. I was overthinking it.

**Comment by psychoblue** [comment]
With 2 instances running, to search two areas, it requires... 2 ptc accounts? 2 api? both?

Thanks.

**Comment by KikkomanChow** [comment]
2 ptc account, same api.

**Comment by psychoblue** [comment]
It's not working. I have 3 accounts, 1 API. Once I get the first one searching and log in with the 2nd, the 1st one stops scanning and the 2nd instance takes over. Same thing with the 3rd.
