### ISSUE TITLE
Google maps not correctie loaded

### ISSUE THREAD

**Issue by JGoeij** [mchristopher/PokemonGo-DesktopMap#502]
Im having trouble right after logging in with my google account:

![image](https://cloud.githubusercontent.com/assets/20778878/17304574/8cbf693e-5826-11e6-9071-a2ec67bd608d.png)

I have tried both the downloading the exe and unzipping the nupkg. 

Advice anyone?

Thank you!

**Comment by KikkomanChow** [comment]
I've originally have this problem. What I did was to create the Google Maps API key as per instruction on the login screen (must follow the exact instruction there).

**Comment by JGoeij** [comment]
I did, but tried it again and it worked. Maybe copy paste went wrong?

Thanks!
