### ISSUE TITLE
Found Pokemon log (CSV)

### ISSUE THREAD

**Issue by akylle95** [mchristopher/PokemonGo-DesktopMap#504]
The app is fantastic, but please insert an option to choose a path where the software creates a CSV log (something like "Pokemon code;LAT;LONG;expiring_datetime" should be fine) of found Pokemon. 

So we can use this data to implement crowd-sourced maps (probably just friends in the same city) using third-parts software. 

Thanks!!

**Comment by eyl327** [comment]
There's a solution here: https://github.com/mchristopher/PokemonGo-DesktopMap/issues/831

The database file doesn't just have Pokestops and Gyms. It also has Pokemon and Scanned Locations. Each type is in a separate table.
