### ISSUE TITLE
I need help POKEMONGoMap

### ISSUE THREAD

**Issue by Chirinos19** [mchristopher/PokemonGo-DesktopMap#506]
I need help every time I try to enter the application and login tells me that error and how to fix not have Windows 10 Pro 64b
[http://oi65.tinypic.com/j0jzps.jpg](url)

**Comment by AVellucci** [comment]
unfortunately, I have tinypic blocked at my place of business can you upload the file to Github instead?

**Comment by Chirinos19** [comment]
will not let me upload the image for any error, please do not explain the problem as the error is too long.
Copy the url and open it to another tab and see the image.

**Comment by AVellucci** [comment]
@Chirinos19 I'm not clicking the link, my place of work actively block image share sites. I'll have to take a look at home, since you "can't" upload the image to github.

**Comment by Chirinos19** [comment]
I made it here this image!
[https://cloud.githubusercontent.com/assets/20780321/17308613/f63fa1da-5808-11e6-950d-bdef48dc5427.jpg](url)

**Comment by Chirinos19** [comment]
My error on console:
main.html:172 Python server started!
main.html:172 Got open express port: 8001
main.html:172 Express server started!
2main.html:157 server up: http://localhost:8001
main.html:145 Error getting location, trying second provider PositionError
main.html:147 Found location [8.0000,-66.0000] by ipinfo.io
main.html:167 2016-08-01 16:44:04,118 [      auth_ptc] [   INFO] PTC Login successful

main.html:167 2016-08-01 16:44:05,594 [        search] ...
