### ISSUE TITLE
Map Marker Suggestion(s)

### ISSUE THREAD

**Issue by CanadianToast** [mchristopher/PokemonGo-DesktopMap#507]
Marker Options:
Show/Hide Markers
Change Marker Icon
Toggle Marker Dragging
AutoMarkers (Evenly creates and places markers from center-out according to size of scan radius)

Also:
Jump Scan Mode: Scan jumps from one marker to the next for a specified amount of time (intervals)

**Comment by hrdsk** [comment]
very good idea
