### ISSUE TITLE
Errors every time I launch, but it manages to launch.

### ISSUE THREAD

**Issue by HighOnTacos** [mchristopher/PokemonGo-DesktopMap#511]
I get a long page of errors every time I launch. I was having other problems (Wouldn't launch) so I deleted the temp folders. Then it managed to launch, but the map wouldn't load unless I opened the mobile page. Relaunched again, more errors, but it finally seems to be back to normal.

**Comment by MacDogg** [comment]
You didn't provide any part of the error so no one can try to look into it.  If you can take a screen shot or copy and paste the text someone could potentially look at it.  There is a screen shot posted in the thread a few down from this titled.

**Comment by HighOnTacos** [comment]
![pokemon error](https://cloud.githubusercontent.com/assets/15607458/17312594/6577fe3e-5819-11e6-9ba4-34c66ffe1755.PNG)
There it is. Once I dismiss the error, it seems to login. Map loaded fine this time.

Do I need to run the game from the downloaded executable every time, or is it installing something somewhere?

**Comment by MacDogg** [comment]
Thanks for posting it.  There are a few screen shots on here with that same error, someone just posted it right after you did.  Let's hope there is a solution.

**Comment by HighOnTacos** [comment]
Yeah... I noticed that the "Command failed" number is the same, but the errors that follow seem to be different for mine. Just glad it's working though!
