### ISSUE TITLE
Installation crash [Win7 Pro x64]

### ISSUE THREAD

**Issue by rakamakaf0n** [mchristopher/PokemonGo-DesktopMap#512]
![default](https://cloud.githubusercontent.com/assets/20782990/17312519/9d8cbd14-5896-11e6-813a-e60d21ec7e8c.png)

**Comment by MacDogg** [comment]
I get the same error on start up but the application still works as advertised.  Are you still abel to use the application?  I am on Windows 10 Ult 64-bit.

**Comment by rakamakaf0n** [comment]
No, I launch the app, it shows "Loading, please wait..." and that's it.
I've enabled Javascript in Google APIs, but it doesn't help.

**Comment by andres-orozco1** [comment]
Hey guys,  i think its probably an issue associated with some ports. I tried in another computer and it definitely works. Well it can be a solution for guys that are having the same. 

PD: Waiting for solve this.

**Comment by rakamakaf0n** [comment]
It works well on my laptop (Win7 Home Base x64)

**Comment by MacDogg** [comment]
When I first started the app Windows Firewall popped up a window asking to allow the traffic and I had to hit Always Allow or some button to approve it.

**Comment by rakamakaf0n** [comment]
Same here. Allowed all connections. No result.

**Comment by MacDogg** [comment]
Hmm, maybe disable the windows firewall altogether just to rule it out?  Then turn it back on, of course.

**Comment by andres-orozco1** [comment]
I did and didnt work, I think its a port in use.

**Comment by rakamakaf0n** [comment]
Well I have Microsoft Security Essentials as antivirus soft. 
Disabling it doesn't do any use.

**Comment by MacDogg** [comment]
Last thing for tonight.  Can you ping https://www.googleapis.com/?  I see a lot of reports on github with a similar error and someone mentioned a DNS issue and once fixed that resolved this error.

**Comment by rakamakaf0n** [comment]
![image](https://cloud.githubusercontent.com/assets/20782990/17315863/910b7a32-58b2-11e6-8dd6-1c1018542a48.png)

**Comment by MacDogg** [comment]
I get a different IP.  I am in the US and maybe that is why?  Your IP points to cache.google.com when I tracert it.

**Comment by andres-orozco1** [comment]
![captura](https://cloud.githubusercontent.com/assets/19438367/17315900/2ee5268c-5835-11e6-8b29-3401c5c55d30.PNG)

**Comment by rakamakaf0n** [comment]
I have ru IP at home and the App is working fine.

**Comment by MacDogg** [comment]
C:\Users\MacAdmin>ping googleapis.com
Pinging googleapis.com [74.125.21.147] with 32 bytes of data:
Reply from 74.125.21.147: bytes=32 time=69ms TTL=40

**Comment by andres-orozco1** [comment]
@rakamakaf0n  what is the meaning of "ru IP"

pd: @MacDogg  dont u think its a port in use?

**Comment by MacDogg** [comment]
Russian IP address.
I don't if it would be a port in use.  How would you consider that?

**Comment by rakamakaf0n** [comment]
@andres-orozco1 MacDogg said that maybe there is a problem with russian IP)
I just said that I have ru IP at home and it works well.

**Comment by andres-orozco1** [comment]
@MacDogg Because in a friend's computer it works perfectly and we did it in the same network, i think its, maybe im needing know which ports the app needs.

**Comment by MacDogg** [comment]
Check the ping and make sure they both go to the same place.  Finding out the ports is a little tougher to do on our own.

**Comment by MacDogg** [comment]
I ran a wireshark capture on mine and there are a bunch of external IPs getting hit before I get logged in.  I am unsure what one it is because none of them resolve to a name to kinda point in the right direction.
