### ISSUE TITLE
Pokemon Onix is mispelt, should be spelled Onyx.

### ISSUE THREAD

**Issue by LukasVannStruth** [mchristopher/PokemonGo-DesktopMap#513]
Minor issue in the pokemon lists for Hide Pokemon and Notify Pokemon.

**Comment by eyermann** [comment]
http://bulbapedia.bulbagarden.net/wiki/Onix_(Pokémon)

**Comment by LesBean** [comment]
Actually you are incorrect
http://pokemondb.net/pokedex/onix

**Comment by eyermann** [comment]
no "minor text fixes" here!

**Comment by LukasVannStruth** [comment]
Wow supposed i was mistaken 
perhaps it was different in one of the games.
