### ISSUE TITLE
Oops! Something went wrong 

### ISSUE THREAD

**Issue by ttan039** [mchristopher/PokemonGo-DesktopMap#514]
![screenshot 4](https://cloud.githubusercontent.com/assets/20764168/17312717/cbc28c46-5822-11e6-89a7-929bff89082a.png)

**Comment by hoeguard** [comment]
Hi there, the errors returned here appear to be related to a failure to connect to the google maps API, not a failure within the application itself. Please try deleting the key you generated, and follow through the steps listed in the api key generation walkthrough one more time in a new project. Ensure you paste the entire key, and the correct settings have been used.

**Comment by MacDogg** [comment]
If the API code is the possible culprit, I noticed when I used the COPY button on the API window it added a space and the front and back of the code.  Make sure you delete those and just type the characters with no spaces.

**Comment by ttan039** [comment]
Hoeguard that worked! Thanks to both of you for the support
