### ISSUE TITLE
Blue circles when clicking "Scanned Locations"?

### ISSUE THREAD

**Issue by Kenny427** [mchristopher/PokemonGo-DesktopMap#517]
Hey,

So I tried adding a lot of instances to search a bigger area, at first it worked fine, but I redid it so it would be better, now every circle in the "Scanned Locations" is blue ish and I only see a few select Pokemon.

Anyone know what this is and what causes it?

**Comment by MacDogg** [comment]
Can you provide a screen shot?  If you are on Windows 7/10 there is an application called Snipping Tool (click start, type snip and it should appear).  That allows you to drag a box around part of your screen.  After you do that click on the Save button and save the file.  When you come back here, just below the text box we type in there is a box that says **Attach files by dragging and dropping or selecting them**.  Drag the file into that box and drop it so it gets posted here.

**Comment by Kenny427** [comment]
![skjermbilde](https://cloud.githubusercontent.com/assets/20783585/17313507/8858a6e0-585c-11e6-8b88-a3f5534ec9db.PNG)

This is how it looks.

**Comment by MacDogg** [comment]
Wow!!  Do they go from green to orange, yellow and red or something like that?  Truthfully I only started using the application today and I have never seen blue yet.  When they expire they just disappear.

**Comment by Kenny427** [comment]
Anyone know what blue circles indicate?

**Comment by Genek1968** [comment]
How did you set up to run this many instances at the same time ?
