### ISSUE TITLE
How do i run multiple instances? 

### ISSUE THREAD

**Issue by Doyoueventraps** [mchristopher/PokemonGo-DesktopMap#518]
How do I run multiple instances?

I know with the smaller radius that I would need multiple instances

**Comment by MacDogg** [comment]
Let's see if I can help, I use Google to login, no PTC.  I just started using this app today and was able to run four for a while.
First off you need to have multiple Gmail accounts so get started on that.  Someone said in another post here that you only need 1 API code and I assume you have that.
So start up your first instance and get it going.  Then start the app again and when it comes up you need to click Logon with Google and then click on the drop arrow in the upper right where it shows your current email address.  Click on Sign out.  Click on Add Account and then login with another account.  Click on the Allow button and it should start a new window.  You then move the marker someone else of course.  Now in both windows you should see both of the scans running.
![capture](https://cloud.githubusercontent.com/assets/20782190/17315213/809acd2a-582f-11e6-87f2-39a4a78b74f4.JPG)

**Comment by MrAwesomers** [comment]
Don't use google accounts for scanning. Google accounts stop working after 30 mins.

**Comment by MacDogg** [comment]
No wonders the stop after a while!!  Thanks for the heads up, I will look into PTC accounts.
