### ISSUE TITLE
Suddenly not working

### ISSUE THREAD

**Issue by Riechao** [mchristopher/PokemonGo-DesktopMap#52]
It was working fine until about 10 minutes before this post. Suddenly I'm getting 500 errors:

> 127.0.0.1 - - [21/Jul/2016 13:34:50] "GET / HTTP/1.1" 500 -
>
>main.html:168 [2016-07-21 13:34:50,401] ERROR in app: Exception on / [GET]
>Traceback (most recent call last):
> File "packages.zip/flask/app.py", line 1988, in wsgi_app
>  response = self.full_dispatch_request()
> File "packages.zip/flask/app.py", line 1641, in full_dispatch_request
>   rv = self.handle_user_exception(e)
>  File "packages.zip/flask/app.py", line 1544, in handle_user_exception
>    reraise(exc_type, exc_value, tb)
>  File "packages.zip/flask/app.py", line 1639, in full_dispatch_request
>    rv = self.dispatch_request()
>  File "packages.zip/flask/app.py", line 1625, in dispatch_request
>    return self.view_functions[rule.endpoint](**req.view_args)
>  File "./example.py", line 824, in fullmap
>    'example_fullmap.html', key=GOOGLEMAPS_KEY, fullmap=get_map(), >auto_refresh=auto_refresh)
>  File "./example.py", line 935, in get_map
>    zoom='15', )
>  File "/home/pike/Downloads/PokemonGoMap-Lin-x64/resources/app/map/flask_googlemaps>/__init__.py", line 44, in __init__
>    self.build_markers(markers)
>  File "/home/pike/Downloads/PokemonGoMap-Lin-x64/resources/app/map/flask_googlemaps>/__init__.py", line 80, in build_markers
    self.add_marker(**marker)
>  File "/home/pike/Downloads/PokemonGoMap-Lin-x64/resources/app/map/flask_googlemaps/__init__.py", line 103, in add_marker
    raise AttributeError('lat and lng required')
>AttributeError: lat and lng required
>
>main.html:168 127.0.0.1 - - [21/Jul/2016 13:34:50] "GET / HTTP/1.1" 500 -

**Comment by Riechao** [comment]
I'm using linux mint 17 64bit but that shouldn't cause any issues.

**Comment by jameskrawczyk** [comment]
500 is an Internal Server Error. Basically it means the servers have broken again, or at least are currently unresponsive. It should come back.

**Comment by Riechao** [comment]
Thanks! I realize 500 is internal server error, but I'm wondering if it's Pokemon go or something with the App since Go is working fine, but the app isn't.

**Comment by jameskrawczyk** [comment]
The error looks like it's coming from the HTTP header, which would mean it is being returned from the server. It's possible the app is accessing a different server group since it's using 'unofficial' API from your Go game.

**Comment by Riechao** [comment]
Nothing I can do but wait I suppose? Not sure if it's anything like other APIs I've worked with, but they give a 500 error if the request is not formatted exactly correct. I'm not sure how to debug this since it's the first time I've played with an electron app.

**Comment by mbostwick** [comment]
There is an update for the app..so likely server changes..

**Comment by Riechao** [comment]
Does this mean I'm not the only one down?

**Comment by Riechao** [comment]
All fixed with version 7
