### ISSUE TITLE
Ops! Something went wrong. [Detailed]

### ISSUE THREAD

**Issue by kebabas** [mchristopher/PokemonGo-DesktopMap#520]
![gg](https://cloud.githubusercontent.com/assets/20784712/17314851/04e1e952-5870-11e6-97c9-85f5e3589134.png)
![ggg](https://cloud.githubusercontent.com/assets/20784712/17314879/35b12d4a-5870-11e6-8869-3bb718f89153.png)

Hello. I keep getting theese errors (Windows7) every time i log in with google. A small flash of the map and then the error comes. Yes , I Generated like ~30 new api keys , did what was told in the guide but i still get this error. Tried 1.3 - 1.6 versions of this map and still same error. There is nothing wrong with my API key and i cant find where is the problem. Updated java and etc but so far nothing helped. Thanks for answers and solutions :P

**Comment by TheFalseKing** [comment]
I still get this error with 1.6 but it eventually worked. There should be a panel to the right when you got your key. I think there are 3 choices and the last one is Credentials where you got your key from. Did you also remember to pick the first choice and hit "enable API"? If not go back and do that. It will then bring you to a summary page and you will want to hit Google Map API or something along those lines. Once you do that it should work. Like I said though. I still receive this error on the newer releases but the map does load. Sorry for all the ambiguity this is all from memory and I don't remember the site or anything that I visited.

**Comment by MacDogg** [comment]
Hmm, that is the 2nd or 3rd time this has been posted today, I think.  I also got it but the game was still able to run.  I didn't have to do anything like TheFalseKing typed but hope that helps.  A couple of suggestions if not:
Make sure your API code does not have spaces and the front and back.
Did your Windows Firewall pop up asking you to allow traffic for Python?  You might have to allow all UDP and TCP traffic for that app.

**Comment by MacDogg** [comment]
Here is the info in the log that I exported.  The thing is, I got the same error above but the app worked fine.  I logged out and logged back in and didn't get the error but this same code was in the log.  I removed my lat/lng and replaced them with ##.
server up: http://localhost:8001 Error getting location, trying second provider PositionErrorcode: 2message: "Network location provider at 'https://www.googleapis.com/' : Returned error code 403."__proto__: PositionErrorPERMISSION_DENIED: 1POSITION_UNAVAILABLE: 2TIMEOUT: 3code: (...)get code: ()arguments: nullcaller: nulllength: 0name: ""__proto__: ()<function scope>constructor: PositionError()PERMISSION_DENIED: 1POSITION_UNAVAILABLE: 2TIMEOUT: 3arguments: nullcaller: nulllength: 0name: "PositionError"prototype: PositionError__proto__: ()<function scope>message: (...)get message: ()arguments: nullcaller: nulllength: 0name: ""__proto__: ()<function scope>Symbol(Symbol.toStringTag): "PositionError"__proto__: Object__defineGetter__: __defineGetter__()__defineSetter__: __defineSetter__()__lookupGetter__: __lookupGetter__()__lookupSetter__: __lookupSetter__()constructor: Object()hasOwnProperty: hasOwnProperty()isPrototypeOf: isPrototypeOf()propertyIsEnumerable: propertyIsEnumerable()toLocaleString: toLocaleString()toString: toString()valueOf: valueOf()get __proto__: __proto__()set __proto__: __proto__()
Found location [##.####,-##.####] by ipinfo.io
2016-08-01 21:45:13,576 [    MainThread][     runserver] [   INFO] Parsed location is: ##.####/-##.####/0.0000 (lat/lng/alt)

**Comment by Yashley05** [comment]
I had this issue several time last night. Did 2 email addresses with several API but nothing worked. In fact it turned out that the API was not Enabled. I just did so and it loads the map.

Go on Google API Console, click on Dashboard, then Enable API, then choose Google Maps JavaScript API (Which I did), then Enable it. 
Log out from Pokemon Go Live Map, paste the API then log in again. It worked for me and hopefully for you too.

**Comment by zaqrwe** [comment]
What the hell? After logging up, I CAN see the map with pokemon and everything, but it only last 1 second, and then I get the error "something went wrong"

**Comment by kebabas** [comment]
@Yashley05 
"Go on Google API Console, click on Dashboard, then Enable API, then choose Google Maps JavaScript API (Which I did), then Enable it". This worked. Thank you very much :P have a nice day :)

**Comment by Genek1968** [comment]
I'm having the same problem. The map will pop up for a second and then I get the " Ops ! something went wrong."   I followed the steps to enable " Google Maps JavaScript API " .  but it was already enabled. Please help.

**Comment by Genek1968** [comment]
I just figured out that my issue was an incorrect API Key .  I typed in wrong API.  ( was not able to paste to Pokémon Go Map ).  After typing in correct API the Map worked
