### ISSUE TITLE
Ransomeware

### ISSUE THREAD

**Issue by MrKinetik** [mchristopher/PokemonGo-DesktopMap#521]
Attempted to run the compiled .exe and Malwarebytes Anti-Ransome ware quarantined multiple files.

**Comment by robertybob** [comment]
...any more details then that?

**Comment by MrKinetik** [comment]
Sadly Malware's anti-ransomeware didn't keep any files in the quarantine logs but I do remember it making a reference to a file path that I believe involved 'Squirrel' and 'Temp'. I'll see about spinning up a virtual machine to sandbox and test again.

**Comment by AVellucci** [comment]
The file is not a virus, please see the VirusTotal page provided.
[VirusTotal](https://www.virustotal.com/en/file/455fdb254ce8e4bf83991ae22b37e11c9e4c33df0941ab9c7f31863abebc21cf/analysis/)

**Comment by macinmn** [comment]
This may be related to the update module.  I received the warning relating to 'squirrel' from AVG shortly after closing and relaunching the 0.15 version for the second time basically right when 0.16 was published.  It was reported as 'IDP.ARES Generic', I panicked a bit, but then saw it is related to '~python script modifying your computer', and figured the update was why it was present.  scanning manually failed to locate any similar threat.
