### ISSUE TITLE
Notification bug 

### ISSUE THREAD

**Issue by theChief96** [mchristopher/PokemonGo-DesktopMap#524]
When it notifies me about a pokemon. It keeps seding me notifications after I close it. Even when I removed the pokemon from the notify list. It keeps sending me notifications about the same pokemon constatly.

**Comment by superslayin** [comment]
Yea I am having this issue too and its super frustrating, just constantly spams the notification after the monster disappears, then even if you close and reopen the app it starts notifying you that that monster has appeared even tho it hasn't, the only way to make it stop is to remove it from the list which makes this map unusable unless you want to sit there and stare at it all day until u see the monster appear.

**Comment by Aradax666** [comment]
Same. Not all the time though, maybe 1 in 5 times this happens. Actually thinking about it, I think its always a Dratini that does it......

**Comment by yassotreyo** [comment]
same issue here

**Comment by loilemix** [comment]
Has anyone tackled this issue yet?

For me, even after the listed Pokemon despawns, the notifications are still coming in.
