### ISSUE TITLE
Over-lapping circles. Consequences?

### ISSUE THREAD

**Issue by TheFalseKing** [mchristopher/PokemonGo-DesktopMap#526]
I've been going at it for about a day now trying to cover a large portion of an area with a good consistency for scanning. I recall someone saying something about if your circles overlap it can cause something bad to happen? I'm not sure if I read it wrong or what, but I'm curious as to how(if) overlapping can cause any negative effect at all besides looking awful and hard on the eyes. I've got about 8 accounts set up so far and I'll most likely make at least another 4-8 before I get the density and coverage required. If any of you might know of a way to spread out the scans so they don't overlap but come into perfect proximity (know exactly how much latitude and or longitude is required based on the radius of the scan) I'd be grateful.

**Comment by bobbajobb** [comment]
If they don't overlap you will miss scanning certain areas.

You cannot perfectly tessellate circles.

**Comment by TheFalseKing** [comment]
Ok thanks. Glad to hear nothing negative happens if you simply overlap.
