### ISSUE TITLE
[Question] Notification forwarding

### ISSUE THREAD

**Issue by kiwijam77** [mchristopher/PokemonGo-DesktopMap#527]
This is a great app, thank you to everyone involved.
I use it to notify me when a rare pokemon is nearby. I have it running on Windows 10, which raises a notification in the corner of the screen and makes a ding noise. But this only works if I stay near to the computer, I tend to miss them otherwise.
Does anybody know a method (or app) that these windows notifications can trigger an email, or somehow send a notification/message to a nearby phone/tablet?

**Comment by Padawin86** [comment]
I suggested Growl for Windows. That coupled with something like Notify My Android would do exactly what we are looking for

http://www.growlforwindows.com/gfw/developers.aspx
