### ISSUE TITLE
Is there a way to permanently set starting scanning location

### ISSUE THREAD

**Issue by jijetelu** [mchristopher/PokemonGo-DesktopMap#528]
Whenever I restart application, location is set to somewhere nowhere, Is there a way i can specify staring location, eg. coordintates ?

**Comment by FirelordPhoenix** [comment]
You can set the coordinates in the login screen under "Config Options".

**Comment by jijetelu** [comment]
Oh, thank you very much

**Comment by FirelordPhoenix** [comment]
No problem, I'm just glad this map still works unlike Pokevision and other sites.
