### ISSUE TITLE
[Feature Request] Gym Information Text Log

### ISSUE THREAD

**Issue by DrWinstonOBoogie** [mchristopher/PokemonGo-DesktopMap#530]
Thanks to everyone for their hard work on this project.

I am attempting to analyse local gyms to find out which team holds each gym, how long they hold it, the highest level they get to and other things.  For this purpose, I would like the ability to log certain information to a text file.  When this option is enabled, every one second I would like a line written to a text file with this information:

date, time, latitude, longitude, gym name, team id, gym points, gym level
 
If there is other information available about the gym or it's status such as the current trainer's names, levels or Pokemon info, I'd like that, too.

Thanks

**Comment by AVellucci** [comment]
Having a 1 second output would put undue stress on the API and most definitely get you banned out right.
maybe having it update when the scanner passes over the gyms location each time instead would be ore feasible.

**Comment by DrWinstonOBoogie** [comment]
I agree with you on taking the not-getting-banned route. :)  The only reason I wanted it to have a log line written every one second was to be able to see (as accurately as possible) when each gym switched team ownership.  I have no idea what information can be gleaned from each gym, but I will take as much information as possible.  If there is a field for how long or what time the current team took control of the gym, then that is what I need.  Thanks!
