### ISSUE TITLE
Location has gone crazy

### ISSUE THREAD

**Issue by Nodws** [mchristopher/PokemonGo-DesktopMap#532]
Cant move the pin, if I change the coords It will jump to the IP location

**Comment by Mirx** [comment]
Check if you have the follow option enabled.

**Comment by Nodws** [comment]
yes tried disabling, logging out, closing process, creating new account.

Suddenly happened, it was working fine this evening, after 30min of runtime it just popped to the ip location

**Comment by Mirx** [comment]
It might be tied to a session time-out, and re-login.
Try "toggle developer tools" and check the console log if there is an event before the location is reset.
