### ISSUE TITLE
Rarest Creatures only appear for less than 2 mins?

### ISSUE THREAD

**Issue by johndoe416852** [mchristopher/PokemonGo-DesktopMap#535]
Anything that can be done about this?  Don't have time to drive over in 2mins. Thanks

**Comment by TheFalseKing** [comment]
When they first appear they have 15 minutes before despawning. The reason you have 2minutes is because the pokemon wasn't found until its timer was almost up. The best way to find pokemon quickly is to have a much smaller radius and multiple accounts scanning.

**Comment by johndoe416852** [comment]
Ahhhh thanks for the info! I'll look into setting up multiple accounts. Thank you.

**Comment by EternisRequiem** [comment]
What is the best size of the radius/number of accounts?  Can you re-use some of the accounts like before?

I wanna find out where the new damn dratini spawns are in town >>

**Comment by khashte** [comment]
Do I have to edit the Source or ist there any settings option to resize the radius?

**Comment by tinarazzburton** [comment]
It might have been 2mins because it was a Pokemon that was the result of a lured pokestop.  I think those only spawn for like 2 and a half minutes.

**Comment by Xavierh95** [comment]
If you have the last build, on the login screen you have the following.

![screen shot 2016-08-02 at 11 21 26](https://cloud.githubusercontent.com/assets/7370867/17323666/4d502a4a-58a3-11e6-885c-418baf67a391.png)

Don't set a too big scan radius. With the last build and the slow search, 8 is the max I can go for the moment with one scan.

**Comment by majuss** [comment]
I have 25 Accounts with Radius 10. 1 scan takes 25 minutes so the pkm are 1 minute old when I see them. Just create multiple ptc accounts (google is getting kicked) with virtual email addresses "youremail+1@gmail.com; yoremail+2@gmail.com" and so on...

**Comment by jbouaziz** [comment]
How do you set multiple accounts in the app ?

**Comment by Xavierh95** [comment]
For the moment, you can't with one app.
You just have to launch X instances of the app with switching the PTC credentials.
Every pokemons found will appear on each map.
I'm running 8 instances on my side. You can create yopmail address to create PTC Account like this : "youraccount1", "youraccount2", "youraccount3"... 

So it will easy for you to launch every instance :)

**Comment by minim8** [comment]
+1 to the lured Pokemon assumption
and I really hope that we soon have the option to run one instance with multiple account logins.

**Comment by bpchasse** [comment]
@Xavierh95 Have you found a way to move all/multiple pins from one instance ❔ 😕

**Comment by Xavierh95** [comment]
@bpchasse No. I launch instances with a "simple manually method".
The first instance pin is the center of my whole scanning zone (radius 10).
All others instances pins are placed all around (radius 8). I place them manually to create a big scanning zone all around my house. Here you can see three screenshots of the scanning result and instances (without pokemon ignoring filters. I ignore every common pokemon like Pidgey, Zubat, etc.)

![screen_1](https://cloud.githubusercontent.com/assets/7370867/17356582/9a80797c-5958-11e6-8647-75cd0cfdc206.png)
![screen_2](https://cloud.githubusercontent.com/assets/7370867/17356584/9a88f318-5958-11e6-86a4-02e3fae7a146.png)
![screen_3](https://cloud.githubusercontent.com/assets/7370867/17356583/9a88c668-5958-11e6-9747-210807bc0a4c.png)

Yesterday, this method allow me to capture many "rare" / "very rare" pokemons of my zone (Alakazam, Persian, Licktitung, Snorlax, etc.)

Have fun! ;)

PS : A simple tip. Place your first pin, and 4 other in "square" all around. After that, wait 2-3 minutes and do it again. It will be better for refresh.

PS2 : Indeed, it will be realy appreciated to just set a list of PTC Accounts  and do this with one instance :)
