### ISSUE TITLE
Notify of Pokemon with sound when no creature appears.

### ISSUE THREAD

**Issue by johndoe416852** [mchristopher/PokemonGo-DesktopMap#536]
Keep getting this issue.

**Comment by TheFalseKing** [comment]
I've had this happen once or twice. Not sure if it's a bug. It's also possible the pokemon you uncovered simply had it's timer up as it was uncovered.

**Comment by johndoe416852** [comment]
I've only set the notifications for about 10 Creatures at most. The remainder of the creatures have been set to hidden so I have a pretty barren map at most times.  It usually happens with Dratinis and Dragonairs. I've encountered this issue over and over again.
