### ISSUE TITLE
[Error] Error on Logout an in with google account

### ISSUE THREAD

**Issue by Luy222** [mchristopher/PokemonGo-DesktopMap#541]
When I start searching and then want to change a setting via logout and than log back in a error appears:

************************************************************************************************************
[Window Title]
Error

[Main Instruction]
A JavaScript error occurred in the main process

[Content]
Uncaught Exception:
Error: listen EADDRINUSE :::8002
    at Object.exports._errnoException (util.js:949:11)
    at exports._exceptionWithHostPort (util.js:972:20)
    at Server._listen2 (net.js:1253:14)
    at listen (net.js:1289:10)
    at Server.listen (net.js:1385:5)
    at EventEmitter.listen (C:\Users\<Username>\AppData\Local\pokemon\app-0.1.6\resources\app\node_modules\express\lib\application.js:617:24)
    at C:\Users\<Username>\AppData\Local\pokemon\app-0.1.6\resources\app\main.js:294:21
    at C:\Users\<Username>\AppData\Local\pokemon\app-0.1.6\resources\app\node_modules\portfinder\lib\portfinder.js:138:14
    at C:\Users\<Username>\AppData\Local\pokemon\app-0.1.6\resources\app\node_modules\portfinder\node_modules\async\lib\async.js:52:16
    at C:\Users\<Username>\AppData\Local\pokemon\app-0.1.6\resources\app\node_modules\portfinder\node_modules\async\lib\async.js:269:32
    at C:\Users\<Username>\AppData\Local\pokemon\app-0.1.6\resources\app\node_modules\portfinder\node_modules\async\lib\async.js:44:16
    at C:\Users\<Username>\AppData\Local\pokemon\app-0.1.6\resources\app\node_modules\portfinder\lib\portfinder.js:106:16
    at Server.onListen (C:\Users\<Username>\AppData\Local\pokemon\app-0.1.6\resources\app\node_modules\portfinder\lib\portfinder.js:35:5)
    at Server.g (events.js:286:16)
    at emitNone (events.js:86:13)
    at Server.emit (events.js:185:7)

[OK]
************************************************************************************************************

I replaced my real user name with <Username>

**Comment by SNOWFLAKEDK** [comment]
i have the same problem

**Comment by hagel05** [comment]
Looks like on Windows it's attempting to open a listener on port 8001.  Close PoGoMap.  Open up "Resource Monitor" and find what is running on port 8001.  If whatever you're running on Port 8001 isn't mission critical close it/terminate the pid.  It appears PoGoMap will attempt to use 8001 as a listener on IPv6 and IPv4 (just in case it ends up mattering for somebody).  Here is something with better detail on where to look in resmon.  

http://stackoverflow.com/questions/48198/how-can-you-find-out-which-process-is-listening-on-a-port-on-windows
