### ISSUE TITLE
Nothing showing up

### ISSUE THREAD

**Issue by nzfrisco** [mchristopher/PokemonGo-DesktopMap#542]
Thank you for your time.
I downloaded the exe file and installed the software.
Found my google maps api and logged in.
nothing appears to be happening and no pokemon is showing up.

![image](https://cloud.githubusercontent.com/assets/20791421/17323786/824f22ba-58f7-11e6-988c-c234e6f8bcfa.png)

**Comment by nzfrisco** [comment]
on start up the following error message shows
![image](https://cloud.githubusercontent.com/assets/20791421/17323841/c60a89c2-58f7-11e6-826a-86be99762179.png)

**Comment by zaqrwe** [comment]
Are you sure you enabled API javascript on dashboard?

**Comment by nzfrisco** [comment]
![image](https://cloud.githubusercontent.com/assets/20791421/17356225/50686f8c-59aa-11e6-8bea-a20e92faef1d.png)
Yes I think so

**Comment by nzfrisco** [comment]
![image](https://cloud.githubusercontent.com/assets/20791421/17356280/9df3d4bc-59aa-11e6-8658-c8a095094f9c.png)

I used the API key in my credential

**Comment by nzfrisco** [comment]
![image](https://cloud.githubusercontent.com/assets/20791421/17356315/d5c9ff1a-59aa-11e6-9864-1ac3c314c1ab.png)

Is this correct?

**Comment by nzfrisco** [comment]
![image](https://cloud.githubusercontent.com/assets/20791421/17356339/fa380bf8-59aa-11e6-88b5-5447f7a27599.png)

now showing this error message

**Comment by nzfrisco** [comment]
![image](https://cloud.githubusercontent.com/assets/20791421/17356363/1ab517cc-59ab-11e6-8f30-49e55aa13fda.png)
After I click ok on the error message

**Comment by zaqrwe** [comment]
Try addindg exe files as exceptions in antyvirus and windows defender. I'm also getting that window with java error, but map is still working

**Comment by nzfrisco** [comment]
![image](https://cloud.githubusercontent.com/assets/20791421/17373169/2a82e580-59fb-11e6-82f6-c429283fa5af.png)
Thank  you so much it is working now.
I realised the red marker needed to be moved to where I am.
Really appreciate your help
