### ISSUE TITLE
Pokemon only show up in scanned location under 3 minutes

### ISSUE THREAD

**Issue by mna8c** [mchristopher/PokemonGo-DesktopMap#547]
I am currently using multiple accounts to speed up the scanning but i noticed that pokemon only show up with under 3 minutes to go even though the location has been scanned.

**Comment by abuch47** [comment]
same I get this often which version are you using?

**Comment by voidpublic** [comment]
Doesn't happen to me whatsoever. How can you use multiple accounts, i haven't figured that out yet

**Comment by MacDogg** [comment]
voidpublic: https://github.com/mchristopher/PokemonGo-DesktopMap/issues/518

**Comment by voidpublic** [comment]
@MacDogg nice thanks, would be nice tho if they could implement it so you can run it in once instance with multiple logins

**Comment by MaxPower3** [comment]
On latest version 0.1.6. win 10. Using 7 PTC accounts in 7 instances with step 4 for 12h and many of the spawns report back as always less than 3 minutes remaining.

**Comment by BrodrickChilds** [comment]
Having exactly the same issue.  Very frustrating to seem them only for them to vanish before I can get close enough :/

**Comment by minim8** [comment]
Had the same problem in earlier versions and could confirm that nothing was there, but since he updated it (like 2 or 3 updates ago) these Pokemons exist and seem to be lured ones. Enable Pokestops, "Only Lured" and the next time you see these under 3 min Pokemons check if they spawned because of the Lure module.

**Comment by MaxPower3** [comment]
@minim8 Thanks. Confirmed that the sub 3 minute ones are Lured Pokemons with 15min observation. Issue should be closed. 
Suggestion, add a Lured tag to the Pokemon info tooltip.
