### ISSUE TITLE
Outage

### ISSUE THREAD

**Issue by textcursor** [mchristopher/PokemonGo-DesktopMap#549]
I just installed the app, it worked fine for an hour or so but now it appears there is an outage, just wondering what causes this outage and is there a way to fix or do i just wait for it to come back online?

**Comment by furax187** [comment]
textcursor where did you find the app? can u give me a direct link of the app pls on playstore?

**Comment by furax187** [comment]
i have the program installed on pc and i see now too an outage, the servers of pokemon are probably unstable

**Comment by textcursor** [comment]
ah you know what i just read a previous thread and it seems i have to close and restart the map app.
I'm using a mac so maybe thats the issue.
but yeah not mobile app just a mirroring browser window I'm using

**Comment by furax187** [comment]
ah i tought u were using an app on smartphone :)

**Comment by furax187** [comment]
ye you are right, i just reopened the program and it says operational now :)

**Comment by textcursor** [comment]
i just hit the mobile button on the top right and pasted the url into my mobile browser, i think most apps that are released are being shut down by google/apple etc so for now this seems the only solution

**Comment by furax187** [comment]
omg i didnt saw that, thx for sharing man, u rock :DDDD

**Comment by textcursor** [comment]
hehe no probs I'm liking this app a lot more than pokevision now so hopefully ill find a way to stabilise it or get a friend to host from his house while I'm out catching em all lol

**Comment by furax187** [comment]
i just copied that url on my webbrowser on my smartphone, now i wonder does this change my real gps position, cause i dont want to get banned by pokemon go for changing my real gps location

**Comment by furax187** [comment]
it doesnt change it, i opened my pokemon and i am still in the street i live :D

**Comment by textcursor** [comment]
no it shouldn't but i did use a gmail that isn't associated with my main account just incase!

**Comment by textcursor** [comment]
ooh i see an omanyte nearby brb...........:D

**Comment by furax187** [comment]
hahah good luck :DDD

**Comment by khashte** [comment]
i'm on mac too and have 3 acc's active simultaneously. On one acc i don't have any problems with the outage, but i have to restart the other 2 every now and then (first is ptc the others are google accs). Any solutions yet?

**Comment by textcursor** [comment]
i just read that google accounts timeout every 30 mins and with a PTC account they just re-login for you every disconnect, going to make a PTC now...

**Comment by textcursor** [comment]
covered here: https://github.com/mchristopher/PokemonGo-DesktopMap/issues/522

**Comment by khashte** [comment]
ah thanks mate. gonna do that aswell
