### ISSUE TITLE
`Cannot read property 'getSouthWest' of undefined`

### ISSUE THREAD

**Issue by Michael-0** [mchristopher/PokemonGo-DesktopMap#550]
Just downloaded the latest version 0.1.6 on Windows. I have an error page and the same error repeats in the console : `MAP: Uncaught TypeError: Cannot read property 'getSouthWest' of undefined`

**Comment by jonpilon** [comment]
Same issue here.

**Comment by bvdrax** [comment]
Hey guys,

I had the same issue. Chances are that you did not put in the proper google maps API key. It is NOT the project ID. You need to specifically request the Google Maps Java API Key.

Thanks,
Ben

**Comment by npremo** [comment]
I also have the same issue.  I am using the google maps API key.

After logging in using the google login the map will show briefly (less than one second) and then the error page "Oops! Something went wrong." will appear.  When I open the developer tools I see the exception: "MAP: Uncaught TypeError: Cannot read property 'getSouthWest' of undefined".

This is with Version 0.1.6 (Windows) - I also tried Version 0.1.5 but was running into a different issue.

**Comment by npremo** [comment]
After taking a closer look I saw that I had also an google maps API error in the console logs, which lead me to realize I missed the "enable the Javascript API" step when setting up my API key.

After enabling the Javescript API and waiting around 5 minutes the map is now working for me.
