### ISSUE TITLE
Great work mike can you please return fast scan?

### ISSUE THREAD

**Issue by abuch47** [mchristopher/PokemonGo-DesktopMap#551]
I understand it doesn't work as accurately due to throttling but it is still preferable for me to run 1.5 with fast scan and wrong search radius over 1.6 with slower scans and multiple PTCs to cover the same area.

A fast scan option on 1.6 may still be inaccurate but would provide a better overview and quicker just like you stated in 1.5 anyway.

I preffered the option of fast scan/less acurate to slow scan/more accurate as the rare spawns seemed to come up on fast anyway.

just yesterday using 1.5 I caught electabuzz which is unheard of in my area and saw haunter and gengar at same time but had to go out :(

**Comment by avielc** [comment]
impossible @abuch47, they have limited the third party API (They=Niantic) so don't expect that feature to come back. 
If you really wanna try it, use an older version, but take into consideration Niantic may soft-ban you on a regular basis

**Comment by abuch47** [comment]
Yeah ive been using 1.5 how will i know if i have been softbanned?

**Comment by avielc** [comment]
I guess, nothing will come up, pretty much that's it right?

**Comment by abuch47** [comment]
I definitely get pokemon still not as common as before though and rares (the ones im looking for) normally have little time left.

Having slightly more success on 1.6 with 19 ptcs on a 20 radius. Want to up it to a 21 radius and at 5 min intervals will need 24 threads but that will be my best option.

Just missed a lured muk. Came up with the full 2.5 minutes but is further away than that so had no chance.

**Comment by avielc** [comment]
if only i could see what you mean,
for some reason after using the first version that came out, i can't seem to see to be able and see pokemons on the newest version out (or any version in fact except the old one)

**Comment by abuch47** [comment]
Yeah last night went well for me on 1.6 as I said got nidoqueen and missed that muk and machamp coz i was too lazy. As of this morning though looks like Niantic have shutdown all hope of scanning and someone blocked all scanners finding pokemon.
