### ISSUE TITLE
Wiki update

### ISSUE THREAD

**Issue by RvdHNL** [mchristopher/PokemonGo-DesktopMap#553]
First off; awesome app!

There are some options in this application. Most are self-explanatory.  But what does the scanned location toggle do?

Maybe an idea to do a quickstart and option explanation on the wiki. 

Also maybe for the less technical ppl here include an option to make the tunnel configurable so you could (easily) pin it to a static subdomain.

**Comment by MacDogg** [comment]
If you turn OFF the scanned location it hides the circles while it scans.  Turn it ON and you see all the circles when it is scanning.

**Comment by MacDogg** [comment]
I added a bunch of info in the Wiki.  We all can update it so if you have additional things to add go ahead and add it at the bottom.

**Comment by RvdHNL** [comment]
Thank you for the quick response!
