### ISSUE TITLE
Mobile access question

### ISSUE THREAD

**Issue by LittleGoliathh** [mchristopher/PokemonGo-DesktopMap#554]
Hey, 

Just stumbled across this earlier today, set it up fairly easily, put in some preferred settings (notifications, which ones to hide, etc) then there was an outage, and apparently I had to reset the app via my computer. Afterwards I did a few tests with login-logouts, refreshing on mobile phone, etc so have a few questions

I read that a PTC account would be better than a gmail account, bc it usually log-ins again after a certain timespan. Is this confirmed, and would this reduce the outage problems severely?

Also I've noticed that refreshing on your mobile does have a nefast impact, so you better don't do that either I guess? Sometimes I got this 'tunnel ngrok io is not found' then, and I'll have to restart application again. 

Last question, is it possible to save some preferred settings or do we always have to re-establish those with every new login? 

Really love the app, and actually think it's even better than pokevision so please keep up the good work and TIA for responses.

**Comment by Mirx** [comment]
Google versus PTC is confirmed.

If ngrok keeps acting up for you, you could always just make a port forward on your router. That's the most stable way to connect. Check "Server Mode / Allow access from anywhere" on the login page, and then forward to the PC running the map on port 8000.

That will also retain the settings on relogin/refresh of the map.

**Comment by LittleGoliathh** [comment]
Cool, thx for quick response :)

**Comment by jcqesr** [comment]
''and then forward to the PC running the map on port 8000'' Are you able to explain this to me please? I would love to be able to do this!

**Comment by AVellucci** [comment]
@jcqesr you can find PortForward instruction for your specific router on [Port-Forward](http://portforward.com)

**Comment by jcqesr** [comment]
@AVellucci Thank you. I've got a Netduma R1. I'm on the port forwarding page on my router, but I just don't understand the whole process. How would I display the map on my mobile?

**Comment by jcqesr** [comment]
Wow I think I did it. The only thing is, it doesn't save the Pokemon I have hidden or notified. I forwarded the port 8000 on my router, and then on my mobile phone browser I put the IP of my PC and the port. so it looked like this <myipaddress>:8000

**Comment by Mirx** [comment]
You have to administer them the first time on your mobile, and then the should be retained for that specific mobile each subsequent login.

**Comment by jcqesr** [comment]
@Mirx Oh ok thanks. So am I able to access it on another network, or do I have to be on the same network as my PC?

**Comment by Mirx** [comment]
That's what the forward is for. Go to whatsmyip.org or a similar site to figure out your external ip, and then enter that instead of the internal ip of the pc.

**Comment by jcqesr** [comment]
@Mirx Right, so I put into the browser on my phone <External ip of PC>:port ?
