### ISSUE TITLE
Stops responding

### ISSUE THREAD

**Issue by sallen67** [mchristopher/PokemonGo-DesktopMap#557]
First, this is awesome, thank you so much for creating this program!
I have tried it on several computers, 1 windows 10 desktop , 1 windows 7 laptop, and 1 Mac laptop.
The installation process was easy and functional.

Now the bad news, it keeps stopping.  After a few minutes the searches stop and you can't get any new info.  The program has to be restarted.  This has been consistent across all 3 of the computers.

Is there a memory issue or a way to stop and restart the searches without closing down the program and reloading.  It makes it had to go mobile if I have to keep closing down the program and restarting it.

Thanks again for all the great work!

**Comment by AVellucci** [comment]
@sallen67 Are you using Google Login or PTC?

**Comment by DrGalactus** [comment]
Experiencing the same issue, using Google Login.

**Comment by AVellucci** [comment]
Please check the [FAQ](https://github.com/mchristopher/PokemonGo-DesktopMap/wiki/FAQ)

**Comment by DrGalactus** [comment]
Yep that'd be it, I'll learn to RTFM :)
