### ISSUE TITLE
OSX: How can I quit the app, then on relaunch there's data on the map?

### ISSUE THREAD

**Issue by JaymerJaymer** [mchristopher/PokemonGo-DesktopMap#558]
Using only 1 session on OS X, I don't see how I can totally quit the app, check processes to make sure its not running, and then when I come back in, it has scanned location green circles on it still.  

Also, I've see a mon icon appear way outside my scanning radius very near the beginning of launch... when the pokestops appear.   how can this be?  if I turn on scanning circles, its in an area that I'll never get to cause of my radius.

**Comment by AVellucci** [comment]
@JaymerJaymer The Scanned Location circles will disappear on their own after about 5 - 10 minutes(I'm not sure of the actual disappearance time) If you close the app and reopen it before that despawn time has triggered the scanned locations will still show up as they still hold valid scan data until they disappear.
