### ISSUE TITLE
No pokemon showing up. Need some update?

### ISSUE THREAD

**Issue by Arepas** [mchristopher/PokemonGo-DesktopMap#559]
Hi guys!

Am I missing something? the map is not showing pokemons in lastest version but when I toggle developer tool it is finding pokemons. I tryied swithing "hide pokemon" in Options but no working for me. 
I hope some advise thanks

I'm running Win7 x64

map scanning at UCF
![none](https://cloud.githubusercontent.com/assets/20797937/17334928/eae533e8-588c-11e6-90b6-a0c6ea187abe.png)

developer console finding pokemons
![none1](https://cloud.githubusercontent.com/assets/20797937/17334947/046cb976-588d-11e6-8a6f-b1502f41a7d6.png)

**Comment by cvnation1** [comment]
same no pokemon

**Comment by Arepas** [comment]
I noticed in some pokestops says name of pokemons
![none2](https://cloud.githubusercontent.com/assets/20797937/17335316/6326638a-588e-11e6-8592-3958e2ce1577.png)

**Comment by MacDogg** [comment]
I see Pokemon around that area right now.
![capture](https://cloud.githubusercontent.com/assets/20782190/17336401/a378d318-58a3-11e6-82cd-c0b0d4f30269.JPG)

**Comment by Arepas** [comment]
@MacDogg Are you using 0.1.6? what setup do you have?

Sometimes when I switch PTC user I got javascript error

**Comment by MacDogg** [comment]
Dang, now I am not showing any Pokemons at my location.  I wonder if it soft bans us (PTC login) if you bounce around to different places?
I have the latest version.  I also get the javascript error but it still lets me in and scan.

**Comment by Pichilona** [comment]
Experiencing the same issue actually. After a certain amount of time, the refreshing does not show any kind of pokemon in the map. Tried to logout and relogin but got a java runtime error. Loging out does not seem to resolve the problem. Is there some kind of cache to be emptied?

**Comment by Arepas** [comment]
![error](https://cloud.githubusercontent.com/assets/20797937/17337073/00daaa44-5896-11e6-90a6-6a54f564753f.png)

getting error after change to a new PTC user

**Comment by avielc** [comment]
Having the same issues as everyone. No idea why though. Any help at all would be welcome (this isn't the first issue that reports this case)
So hoping a solution would be found. (if anyone can think of a log file that could mention something) that could be helpful and such.
@mchristopher
