### ISSUE TITLE
Notifications after despawn

### ISSUE THREAD

**Issue by JesseWV** [mchristopher/PokemonGo-DesktopMap#560]
When a Pokemon that is listed in the Notify section despawns, it generates many notifications in a row. I haven't counted how many but it's seems like 10-20.

**Comment by MacDogg** [comment]
I just noticed that same issue.

**Comment by JesseWV** [comment]
Now I can't get it to stop. I have two that are doing it continuously and still do it even after I exit the program and reload. :(

**Comment by jane0815** [comment]
Happened for me several times too. Only way to turn it off for me was to remove the pokemon from alert list.

**Comment by SkyFyre** [comment]
The problem with this has to do with lures. The notification is triggering when a lured pokemon despawns until the lure is changed, MANY times. It is making notifications nigh-unusable in heavily lured areas. PLEASE FIX.
