### ISSUE TITLE
Data from other scanners

### ISSUE THREAD

**Issue by Drewbacca81** [mchristopher/PokemonGo-DesktopMap#566]
So, I have a PTC account login, and I've noticed alot of pokemon showing up outside of my scan radius. They're always in the same general location, and I've confirmed that it's accurate. It's not just outside of my radius either... it's several blocks. Does that mean someone else has the scanner as well? Do scanners share data? I only have one account going, so it's not coming from me.

**Comment by maxxx-lfc** [comment]
if you turn on pokestops in options its probably a lured pokemons but im not sure

**Comment by TheFalseKing** [comment]
I think someone reported this as a bug about a day or so ago. You keep seeing pokemon spawn outside your scanner radius but if you actually take their coords and put them into google maps it should give you a location inside your scanner.

**Comment by Drewbacca81** [comment]
No, it's showing up outside my radius, and the coords are correct. I've actually found those pokemon to be in the correct spot too. It's correctly detecting pokemon outside of my radius.

**Comment by EternisRequiem** [comment]
Lured pokestops  = Everyone
Incense lures = Only you

They should have a little pink or purplish or something ring around their base with a particle effect (it's actually kinda hard to see sometimes)
