### ISSUE TITLE
Google Map Key Issue

### ISSUE THREAD

**Issue by vhenriques** [mchristopher/PokemonGo-DesktopMap#569]
Im following this guide

https://github.com/mchristopher/PokemonGo-DesktopMap/wiki/Google-Maps-API:-a-brief-guide-to-your-own-key

When i open the website listed in step 1 and login i get this error
![capture](https://cloud.githubusercontent.com/assets/3635834/17341536/a934fc72-5912-11e6-9e58-3c80900cbaad.PNG)

When i open the desktop client i get this error
![1](https://cloud.githubusercontent.com/assets/3635834/17341574/d80dade6-5912-11e6-8239-35e3d0e93de0.PNG)

any pointers to what im doing wrong ?
Thanks in advance

**Comment by avielc** [comment]
google API has these issues sometimes, try to re-enable stuff and it'll work (it needs a small wait time for it to happen sometimes) 
I still don't understand if it works at all, as i get a position error in the dev-console
