### ISSUE TITLE
[Suggestion] Allow multiple markers

### ISSUE THREAD

**Issue by killerjerick** [mchristopher/PokemonGo-DesktopMap#57]
First of all, Thanks MChristopher, I really appretiate the work that's gone in to making this wonderful program, I however have several friends who live sort of close to me but JUST out of reach from the default "7" radius, However, increasing it dramatically increases the update time so it's a bit pointless when none of us go very far to find pokemon.

My idea would be to allow multiple map markers at set radius' (E.g. I'd have one near my house with a radius of 2, and one near my friends' houses with a radius of 2 each)

If this is possible I'd really like to see it implemented however if you have no time to do something like this yourself, that's fine, it's more of an ease of use thing anyway.

Thanks again for all the work you've put into this already and I look forward to see what the future brings :)

**Comment by dwk001** [comment]
I could see this working if they allowed multiple accounts, and then on the sign-in screen you can associate markers/ location points with login accounts. So that you can use one account for your house, and one for your friends.

**Comment by Mrxshamsi** [comment]
This would be actually nice if you can use multiple logins to put markers in several places, right now using 3 windows of the same program and then restarting just resets all of the accounts to the last one used, even the long/lat is the same.
