### ISSUE TITLE
Best radius for detect a lot of pokemon

### ISSUE THREAD

**Issue by dualshote** [mchristopher/PokemonGo-DesktopMap#573]
Hi guys, i need to know the radius parameter for detect a lot of pokemon :) 

It's import to checked the "Server mode/ Allow access from anywhere" ? 

Thanks :D

**Comment by MacDogg** [comment]
I have mine set to 5.  The higher the number, the wider the search radius and the longer it takes to start the scan over.
So, in the middle it will start at, for example, 4pm.  By the time it gets out to ring 7 and starts over in the middle it might be 4:13pm.  Anything that spawned in the middle will only have a few more minutes left and you would need to be rushing to get there in time.
What some people are doing is running multiple instances of the program.  I have it running 4 times on scan radius of 5 so I have time to ride to the inside or outside if something spawned 12 minutes ago.

**Comment by MacDogg** [comment]
I did the math.  On scan radius of 5 there are 61 circles.  After the first circle appears the next will take 5 seconds to appear.  5x60=300 seconds.  That's 5 minutes from the start of the first circle to the next time it refreshes.
Just taking a guess that a 6 scan radius has 91 circles, that comes out to be 5x90=7.5 minutes.
Looks like a scan radius of 4 has 37 circles.  That comes out to be 4x36=2.4 minutes.
If you are running a scan radius of 7, count the circles, subtract 1, multiply by 5 and then divide by 60.  That will be how long it takes each circle to refresh.

**Comment by dualshote** [comment]
Thx man ! :) But i don't understand... The scan radius number is the range around our personnage or the number of circle ? Because if circle spawn at the same place is useless no ? :) Thanks
