### ISSUE TITLE
'map download failed'

### ISSUE THREAD

**Issue by denizagovic** [mchristopher/PokemonGo-DesktopMap#577]
in the developer tools section, i was told to go into the console. the error says that the map cannot be downloaded and that it is retrying constantly. Are there any fixes for this?
![image](https://cloud.githubusercontent.com/assets/20803437/17346133/472f3dbe-5901-11e6-81b9-34ca4998d2c5.png)

**Comment by tin18** [comment]
i am getting the something

**Comment by battosai52** [comment]
hi , 
same problem for me

**Comment by tin18** [comment]
i figured it out you have to get the google maps java script api and it will work

**Comment by battosai52** [comment]
lol just an error in the API key , sorry
