### ISSUE TITLE
Multiple scans not working

### ISSUE THREAD

**Issue by tristan86** [mchristopher/PokemonGo-DesktopMap#578]
Hi there!  Great work with the program so far!  I was trying to run multiple instances of the program simultaneously with 3 different PTC accounts for multiple scan locations, but when i would move the scan location on each of the different windows, it would stop scanning on two and favor one.  Any way to prevent this from happening?  End goal is to simply scan a few different locations at the same time on the same PC.

**Comment by bpchasse** [comment]
I am not able to reproduce this when running the latest OS X release. I have two instances running, one with PTC and one with Google. I am able to move either location without stopping the *other* scan.

**Comment by tristan86** [comment]
Hey, thanks very much for getting back to me!  Does it require one account be PTC and the other be google?  In my particular case, I've been trying to use 3 unique PTC accounts. 

 

    On Tuesday, August 2, 2016 8:22 PM, bpchasse <notifications@github.com> wrote:
 

 I am not able to reproduce this when running the latest OS X release. I have two instances running, one with PTC and one with Google. I am able to move either location without stopping the other scan.—
