### ISSUE TITLE
Decreasing Scan Time (how?)

### ISSUE THREAD

**Issue by TheFalseKing** [mchristopher/PokemonGo-DesktopMap#579]
Is it possible to decrease the scan time to a different number? I'm using release 1.3 because the newer versions seem to give me errors at start-up and can only seem to handle 2 accounts at once. I'd simply like to slow down the scanners in 1.3 to see if they are missing anything (still getting rare pokemon quite often as it is).

**Comment by milano140** [comment]
yh i tested this earlier, use multiple 1.6 versions (3 different windows) and then lower the scan radius to 5 each, and used those in close proximity you should get a decent search window that constantly updates

**Comment by TheFalseKing** [comment]
I don't mean radius I mean the actual time the program actually spends getting the information from each circle. I think currently it's set to 5secs. I'd like to increase it to 6 or 7 to make sure I'm getting all possible pokemon from each scan.

**Comment by EternisRequiem** [comment]
@TheFalseKing Niantic just made it so it's now 10s, so yeah this will be necessary soon.

**Comment by rickymiles22** [comment]
I think I found a solution, for me the file is:
C:\Users\[NAME]\AppData\Local\pokemon\app-0.1.6\resources\app\map\config\config.ini
Change the line 
#scan-delay:             # default 5
to
scan-delay: 10            # default 5
