### ISSUE TITLE
app automatically switches "off" after a certain amount of time with the pin not being moved on the app itself

### ISSUE THREAD

**Issue by dhyde79** [mchristopher/PokemonGo-DesktopMap#580]
trying to run it in server mode so that I can check as I'm out and about, but, after a random amount of time the changes from "operational" to whatever the "off" name is, and, the only way to trigger it to start scanning again is to log out and back in, which can't be done except from the computer running the app, and then the "URL" changes for sharing mode, which defaults to being off again...

**Comment by beestiel** [comment]
Are you using PTC or Google login? Google logins stop scanning after 30 minutes.

**Comment by dhyde79** [comment]
google...is there any way to fix google scan turning off?

**Comment by beestiel** [comment]
[Not at this time](https://github.com/mchristopher/PokemonGo-DesktopMap/wiki/FAQ); you'll need to set up a PTC account and use that.
