### ISSUE TITLE
Java script error

### ISSUE THREAD

**Issue by TomanPCM** [mchristopher/PokemonGo-DesktopMap#581]
error after login with PCT:
![map](https://cloud.githubusercontent.com/assets/15616920/17347647/898aaf6c-5911-11e6-8ea0-6292bfd68cf1.png)

on clean install Win 8.1

**Comment by hazezu** [comment]
I get that also

**Comment by PokemonCindy** [comment]
same as me, and less pokemon appearing than early versions.

**Comment by EternisRequiem** [comment]
@PokemonCindy Because they changed the scan rate from 5s to 10s about 13 hours ago.

**Comment by PokemonCindy** [comment]
@EternisRequiem Oh, that explains a lot. Thanks ! Also this is bad news.
