### ISSUE TITLE
Was working but now unable to log in.  Error Message " Unable to exchange token for authorization code"

### ISSUE THREAD

**Issue by Genek1968** [mchristopher/PokemonGo-DesktopMap#584]
![capture](https://cloud.githubusercontent.com/assets/20802244/17349262/49370a0e-58ea-11e6-8518-5d6c9ade8066.JPG)

**Comment by MacDogg** [comment]
Maybe double check your API code from Google?  Make sure there are no extra spaces in front or back?
Try a new API code?

**Comment by Genek1968** [comment]
Started working again. Probably wifi issue because I was connected to a hotspot from my cell
