### ISSUE TITLE
ECONNREFUSED error?

### ISSUE THREAD

**Issue by SaipanDamashii** [mchristopher/PokemonGo-DesktopMap#585]
> Error: connect ECONNREFUSED 127.0.0.1:8000
>    at Object.exports._errnoException (util.js:949:11)
>    at exports._exceptionWithHostPort (util.js:972:20)
>    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1080:14)

is what I get after I log in, then the message disappears and the interface seems to load partially, but no map is displayed and no images are shown, just a bunch of words and blank boxes.

**Comment by MrAwesomers** [comment]
I always get this on mac os x, right before a window pops up, asking for permission to use accept connections. When I click allow (twice) the error disappears and the map loads. I have to do this for every client, when running multiple.

If you are using windows, I can't help you. I can only suggest you to see if your firewall blocks the connection.

See screenshot for the alert.
![screenshot 2016-08-03 at 04 54 32](https://cloud.githubusercontent.com/assets/20760672/17352439/d6784b98-5936-11e6-8cc1-3953bcb6bb6b.PNG)

**Comment by SaipanDamashii** [comment]
I'm on a Mac, running the latest OS X, and I have never seen that alert before lol

**Comment by MrAwesomers** [comment]
You could try installing python and the requirements again, but using sudo instead of the normal command. When I used to normal command, I got a permission error somewhere in the middle. When I added sudo before the install commands, everything installed without a problem. 

That's the last idea I have, so I hope someone else has more ideas if it doesn't work.

**Comment by fmn1116** [comment]
Dependent on how you set up security in the beginning. If right click to open it asks if you are sure you want to download from unknown source and you can.
