### ISSUE TITLE
Feature Request: Manage multiple pin-drops from one instance

### ISSUE THREAD

**Issue by bpchasse** [mchristopher/PokemonGo-DesktopMap#587]
Although it is currently possible to run multiple instances of the scan with different accounts, **AND** see the scan results of all instances within each individual instance, one is unable to see/move a pin-drop that is not created in that instance.

Use case:
1. Open a scan at location "A" using PCT act. ALPHA in client *omega*
2. Open a scan at location "B" using PTC act. BETA in client *zeta*
3. Notice scanning appear around location "B" in client *omega*, in addition to scan around location "A"
3a. Notice cannot see pin-drop from client *zeta* in client *omega*
4. Notice the vice-a-versa of 3 & 3a

I believe it should be possible to observe in client *omega* when the pin at location "B" is created by client *zeta*. I'm less confident about the inverse (finding a pin that is already present).

🎸 keep on rocking 🎸 @mchristopher

**Comment by Kazpers** [comment]
It seems like allowing multiple logins from one client start to make more sense than trying to further integrate separate processes?
