### ISSUE TITLE
Not showing Pokemon?

### ISSUE THREAD

**Issue by Chalkaluver** [mchristopher/PokemonGo-DesktopMap#588]
I installed the windows newest version, found my API, enabled every API that came up for javascript, and I can find pokestops, poke gyms, all no problem. I can even see lures on pokestops and the pokemon that are there from the lure. But no pokemon are showing anywhere else. 
![pokeeeeeeeee](https://cloud.githubusercontent.com/assets/20807602/17352936/1a105d42-5909-11e6-8f22-320b6052e4c0.png)

**Comment by TheFalseKing** [comment]
This might be a silly statement, but did you make sure the pokemon slider under the options tab to the top left was slided on? (blue bar showing)

It's also possible that you could be a dead zone. Some places for Pokemon Go have not been populated for pokemon since that region hasn't been added yet.

**Comment by Chalkaluver** [comment]
@TheFalseKing not a silly question! but yes, I'm fairly sure I've been using it right. This is what mine looks like :) any help is greatly appreciated. ever since pokevision went down I really need something to help me find where all the pokemon are around me. and I don't think it's a deadzone, I find a lot nearby especially since my house backs right onto a hydrofield. but I just use the scanner to exactly locate where the pokemon is, since the three step BS was bugged and is now deleted completely.
![pokay](https://cloud.githubusercontent.com/assets/20807602/17354768/99532d54-5919-11e6-960a-dae14bd67292.png)

**Comment by SupermarketHobo** [comment]
I have the same issue. It was working fine yesterday, but now it just doesn't show any pokemon. I have the slider to on, and I live in New York, so there's no problem with where I live being a deadzone. Please, somebody help. There was a Dragonite nearby earlier and I couldn't find it! I really don't want that happening again.
![img_1055](https://cloud.githubusercontent.com/assets/20810134/17356513/dd5043a0-5925-11e6-827d-7f04ff4f2c3b.PNG)

**Comment by amac1430** [comment]
I'm now having this same issue.  The app worked perfectly for me as of Tuesday night/Wednesday morning but when I got home from work last night, it wasn't able to identify any pokemon whatsoever.  Additionally, it looks like the data it is displaying is out dated or incorrect.  For example, the gym that I can see on my in game map from my home is run by team instinct, however, the map in the app shows it as team mystic.  Further, in playing around with the map in the app, I see some pokestops that have lures on but it says the lures won't expire for another 90 hours.  Clearly that information can't be correct.
