### ISSUE TITLE
Can I use the same google account for the API Key and the actual game  ? Or should be different ?

### ISSUE THREAD

**Issue by Genek1968** [mchristopher/PokemonGo-DesktopMap#589]

**Comment by bpchasse** [comment]
You can use the same, though doing so may be risking being banned. I think anyone would suggest using a separate account for the game than you use for the map key & this scanner.

**Comment by TheFalseKing** [comment]
Any time you do something against a ToS for any game/etc you should also use a back-up email and or account. If you're willing to lose your main or anything tied to it feel free. Now there is no guarantee they will ban even if you do, but it's always better to protect yourself.

If this is still the case, you may want to use PTC - Pokemon Trainer Club accounts instead. Reason being is that they won't stop scanning after 30minutes or an hour (not exactly sure when, just know they do) like the google accounts will. It's a bit of a longer process to make an email and then sign up for PTC, but I've found it to be worth it. I'd recommend watching or listening to something in the background while signing up if you plan to have multiple scans going on.

**Comment by MrAwesomers** [comment]
Use mailinator for your registrations, open inbox without the need to login. Easy activation!
