### ISSUE TITLE
what does the follow location switch do and what does the color of the scans mean?

### ISSUE THREAD

**Issue by sweetlou1217** [mchristopher/PokemonGo-DesktopMap#590]

**Comment by TheFalseKing** [comment]
I do not know what the follow location, but the colours of the scan indicate how "fresh" the scan of that area is.
Green: New
Faded Green:
Yellow: 
Orange: 
Orangey/red:
Red: About to expire 15 minutes I think.

Sorry I can't be more descriptive. I'm pretty new myself and only know that you want to try and keep all your scans within a 3-5 minute scan so you have a minimum of 12-10 minutes of getting to your pokemon.

I hope this helps.

**Comment by torantal** [comment]
As I understand it the current scan circles around your current location and starts afresh once you change your location. When set manually this scan area will go out further and further until at some point it starts again at the center. 

When follow is on, this center in continually reset with your device data and the scan process gets started from the new center everytime. 

So always a fresh look at your surroundings but only a limited reach.

At least that's how I see it working. Turn on scanned locations in option and you should see fresh green circles around you when you move.
