### ISSUE TITLE
Niantic changes 08/03/16

### ISSUE THREAD

**Issue by minim8** [mchristopher/PokemonGo-DesktopMap#593]
Scanupdate got upped to 10s (from 5s, originally 1s). Please update the app rate as well. And also try to implement the login for multiple accounts in one instance - more important than ever now.
Ah and people pls dont use like 20 accounts for a radius of 15 thats why they increase this updaterate again and again.. too much serverload

**Comment by RvdHNL** [comment]
Multiple accounts in one instance with an offset to the master would be great. Then you could set the master to "follow location" and the rest would scan statically around the master with an x-offset.

A max of 7 radius in total (master+slaves) would keep the load acceptable i think.

**Comment by pill0ws** [comment]
dang, is that why I stopped popping shit up while driving? Not even using the scanner, I was having trouble getting anything at all to appear on my game screen unless I fully stopped... then maybe I saw a pidgey or rat appear. Am I just crazy or are these changes effecting the gameplay?

**Comment by pill0ws** [comment]
What other data can be scanned for? My tracker updates at pretty much any speed I travel. Is it possible to receive data from the in game tracker via scanning apps? The tracker literally just points in a direction the moment that you cross an invisible line, if this can be pulled by a scan, it could be possible just to revert to high speed scanning and triangulate on positions via the tracker updates. Other information that could be valuable is orientation of the pokemon when revealed, if thats possible as well. Each pokemon has a unique orientation when they appear, after extensively blanket scanning areas when it was possible, it's my belief that the orientation of the pokemon infers the direction the next respawn will occur (after some hidden respawn timer). I started testing this literally the night before they broke the game and it appeared to be true but I couldnt collect a decent sample size and now its practically impossible to test

**Comment by minim8** [comment]
@pill0ws yes the new changes are also effecting the normal gameplay for people who are riding a bike and run fast. Especially the Pokemon on the edge of your circle are affected- I hope Niantic realises that they are destroying the game.

**Comment by pill0ws** [comment]
Wow, they overreacted like a motherfucker to pokevision. They would rather us not play at all than us find rares. Did they curtail GPS spoofing as well or are peopel still poping all over the country taking over gyms?

**Comment by majuss** [comment]
"python ./runserver.py --cors --auth-service ptc --location=gpslocation --port 8000 --db /Users/majuss/Library/Application\ Support/pokemon-go-map/pogom.db --gmaps-key apikey --username $username --password $password --step-limit 10 --scan-delay 10"

Just add the scan-delay option at the end of the scanner command.

**Comment by pill0ws** [comment]
is the scan radius still 70 meters with the 10s rate change? or are they basically just making the game less and less playable at all. I really could care less to use scanners if they keep making the game harder and harder to even play normally

**Comment by majuss** [comment]
I life in a small city, without a scanner I would be never able to catch anything rare!

**Comment by pill0ws** [comment]
Im more annoyed about not having a bike or a skateboard. They seem to want to force walking, fuck that shit. You dont find shit by walking. You've used a scanner, you know the cool stuff is all over the place, you gotta travel.  I understand trying to restrict driving, trying to literally FORCE walking if uncalled for. After the 5s change I though, ok well thats cool, I'll just use my bike. Walking is barely even exercise, the whole draw of this was getting out of the house and playing outside, not walking

**Comment by EternisRequiem** [comment]
@pill0ws To be fair, walking is actually what we're designed for and in some ways is the best exercise for you ;)
But I get what you're saying.

**Comment by coreyme** [comment]
Anyone on Windows who needs a quick fix, open %localappdata%\pokemon\app-0.1.6\resources\app\map\config\config.ini and change the line:

`#scan-delay:           # default 5`
to
`scan-delay: 10           # default 5`

**Comment by Aerokii** [comment]
@coreyme This is much simpler than me rebuilding 1.3 every time I want to run it... though I'm having difficulty opening multiple instances of 1.6. Is there any way to have multiple instances of 1.6 running currently? Right now it just closes the current one to open a new one.

**Comment by Drewbacca81** [comment]
Dear God, pill0ws, don't play while you're driving!

**Comment by ed4ever** [comment]
Anyone on Windows who needs a quick fix, open %localappdata%\pokemon\app-0.1.6\resources\app\map\config\config.ini and change the line:
#scan-delay: # default 5
to
scan-delay: 10 # default 5

Every time that I open the file and edit and save it, then run the program, i notice it still refreshes at 5 seconds. then when i go back to open the config.ini I find it back in the original state. I can't get it to shift to 10sec

PS: i am a computer noob so aim replys accordingly please.

**Comment by majuss** [comment]
Just make it read only...

**Comment by mattrat88** [comment]
How do I make the Mac program adjust the scan delay ?

**Comment by majuss** [comment]
Jusr run the python runserver from a terminal and add "--scan-delay 10" at the end. But at the moment the scanner is broken because Niantic has changed the API.

**Comment by mattrat88** [comment]
Or will I have to wait for the updated version to release ?

**Comment by mattrat88** [comment]
So even if I change it I'm still not gunna see Pokemon ? I can still see gyms and stops

**Comment by majuss** [comment]
You have to wait for a new version, the current is broken since 2 hours!

**Comment by mattrat88** [comment]
Well I'm looking forward to spamming that donate bitcoins button as this is a glorious effort indeed

**Comment by majuss** [comment]
I don't think maps like this have a bright future. Niantic will block them one day completely or implement a system into the game so you dond't need the map anymore.
