### ISSUE TITLE
Can't login via PTC Account

### ISSUE THREAD

**Issue by InkTheory** [mchristopher/PokemonGo-DesktopMap#595]
Hi,

I just created a PTC account by going here:

https://club.pokemon.com/uk/pokemon-trainer-club/sign-up/

I specifically made the account because of the issues I had with the map where it would stop scanning after a certain period of time under my gmail. However I can't use my new PTC account. I have tried creating several different accounts but none of them work (I have checked my password and username is correct).

I get the error 'Your username or password is incorrect. You have 4 attempts left before you will be locked out of your account for 15 minutes'

Any help would be much appreciated!

Many thanks!

**Comment by Mirx** [comment]
You need to login to the website and accept the Pokemon Go Terms.

Additionally, it might be you created a too complex / long password. I used a password generated with KeePass, and although it allowed login to the website, it wouldn't allow me to log in to the game, nor change the password through the website.

**Comment by Kazpers** [comment]
Have you confirmed your PTC accounts? Because you have to do that to use them for Pokemon Go

**Comment by InkTheory** [comment]
Thanks everyone. The problem was the password was longer the 15 characters :)
