### ISSUE TITLE
Notifications problems

### ISSUE THREAD

**Issue by MrWhacco** [mchristopher/PokemonGo-DesktopMap#596]
Notifications dosnt seem to work if minimized. No sound / popup. 

Besides, Everyone here should KNOW, that this map/program is just a "launcher" for this project: https://github.com/AHAAAAAAA/PokemonGo-Map

Correct credits should be posted on the Wiki &/ Readme.

**Comment by MacDogg** [comment]
Thanks for pointing to the other project.  I just looked at the installer for that one and hell no.  This is a few things and boom you're done and it works.  No need to install python and pip and run commands in a command prompt.
Whether this is a launcher for something else or not...I don't care but appreciate your comment.

**Comment by EternisRequiem** [comment]
I found something different.  It can be minimized, but if I have a bunch of different areas scanning and/or I'm zoomed in where there isn't a scan, I *wont* get a notification until I zoom out.  Works minimized and not minimized for me (Windows 10)
