### ISSUE TITLE
[Suggestion} Allow us to use multiple accounts of our own to increase scan times

### ISSUE THREAD

**Issue by AquatikJustice** [mchristopher/PokemonGo-DesktopMap#599]
As we all know, scan times have now been increased to 10 seconds. While this doesn't affect scanning sites which can just spin up more PTC accounts, users of apps like this one are hurt the most since we can only use 1 account. I suggest allowing us to input as many dummy PTC accounts as we desire in order to increase the scanning speed. Then you could loop through the accounts, scan area 1 with account 1, area 2 with account 2, etc and then start over once you run out of accounts.

**Comment by MacDogg** [comment]
Launch the application **multiple times** and login with multiple PTC accounts and set your markers in different locations.

**Comment by Kazpers** [comment]
Yes that's a workaround, but it's messy and hard to time just right. It's a good suggestion to include it in the app.

**Comment by Schnubbi** [comment]
would be awesome !
