### ISSUE TITLE
Oops !

### ISSUE THREAD

**Issue by kitohiro** [mchristopher/PokemonGo-DesktopMap#600]
I have this error after trying to log and authorise the google sign in.

Oops! Something went wrong and we couldn't log you in. Please try again.
Unable to exchange token for authorization code.

the API key is good, login to....

**Comment by MrAwesomers** [comment]
I'm just taking a guess here from information I've found browsing the Issues page, but have you clicked "ENABLE JAVASCRIPT API" on the google api key pages?

**Comment by kitohiro** [comment]
yes I did.
I double checked and create another project, then went to the main page, and activate google map JavaScript API.
But still the same error.

**Comment by zaqrwe** [comment]
PTC service may be down. It happens very often

**Comment by kitohiro** [comment]
yes PTC service is down, but i'm using google login.

**Comment by MrAwesomers** [comment]
I suggest using a PTC account for scanning. The login servers became more stable and downtime is reducing. A Google account will stop scanning after 30 minutes, forcing you to restart it, while a PTC account will go on forever. 

It probably won't fix your error, but try it.

**Comment by MrAwesomers** [comment]
#584

**Comment by Genek1968** [comment]
Kitohiro.  I have the same issue when I try to log in using mobile hot spot .  It works on home wifi but not mobile.  How did you figure out it was proxy and how do you fix the proxy issue ?
