### ISSUE TITLE
a javascript error occur in the main process

### ISSUE THREAD

**Issue by wantednowdk** [mchristopher/PokemonGo-DesktopMap#602]
keep getting that one when opening program... what am i doing wrong. reinstalled java a few times now

**Comment by MrAwesomers** [comment]
Java and javascript are something completely different. This has nothing to do with your Java installation. Did you click "ENABLE JAVASCRIPT API" on the Google API Manager Dashboard?

**Comment by IluvPidgeys** [comment]
If thats the "Google Maps JavaScript API", when I click on it theres only the option "disable", so it is enabled right?

All other posts so far related to javascript are redirected to 1 that still has no solution, dunno what else to do :/

**Comment by BMWtx** [comment]
I too have been dealing with this issue and have yet to find any answer in the various topics created on the subject. Tried disabling /  re-enabling all of the pertinent API categories, got a new google API key etc. etc., still getting the error and pokemon are not showing up.

**Comment by wantednowdk** [comment]
i did enable it. but im using the the applivcation.
since i cant figure out how to use it with all the other programs. 

but i cant even use the scanner.
