### ISSUE TITLE
JavaScript error prompt when launching the program.

### ISSUE THREAD

**Issue by Shogunz1** [mchristopher/PokemonGo-DesktopMap#603]
When I start the program I get a error prompt stating 'A JavaScript error occurred in the main process'. The program seems to be still working fine I just never had an error prompt before. 

The rest of the prompt states 'Uncaught Exception: Error: Command failed: 4294967295'....'The remote server returned an error:(503) Server Unavailable' 

Working fine though lol, just thought I should double check.

**Comment by SmilinItalin** [comment]
Im havein the same problem

**Comment by henrinho** [comment]
Me too. What to do?

**Comment by Gentleman-Taco** [comment]
I click OK and it loads anyway. Works great.

**Comment by markus-zhang** [comment]
Having the same problem, stuck on loading scene. I have enabled all the API.
