### ISSUE TITLE
Not Scanning

### ISSUE THREAD

**Issue by SturgBoy** [mchristopher/PokemonGo-DesktopMap#606]
Ive checked PTC logins and they are both active, Ive turned on scanned locations to make sure its scanning and no circles are appearing
Any reason for this?

**Comment by MacDogg** [comment]
Did you flip the switch for scanned locations in the options menu?

**Comment by SturgBoy** [comment]
Yep

**Comment by jecates** [comment]
I've noticed that if I move the scan location on mobile, sometimes I'll come back to the desktop and the pin will still show the location I last left it, even though it's actually scanning wherever I left the pin on mobile. I'm sure you've already tried this, but in case you haven't, try changing location and see if that makes a difference.

**Comment by SturgBoy** [comment]
I've already tried that, I've tried to log out and use a different account but I still have the same problem too

**Comment by zaqrwe** [comment]
just happened to me. Accounts active, application is running without errors, scanned locations turned on, and suddenly poof.. it stopped scanning

**Comment by SturgBoy** [comment]
I'm running with a few errors but nothing that I've not had from the start of using this, it's just randomly stopped working

**Comment by torreyt1991** [comment]
<img width="919" alt="screen shot 2016-08-03 at 4 15 25 pm" src="https://cloud.githubusercontent.com/assets/5889424/17380511/83133cd8-5995-11e6-9ecc-1a5922de86d6.png">

Getting a Niantic heavy server load error on my end. Sounds like something that will have to pass.

**Comment by mattrat88** [comment]
Yea I'm retuning zero Pokemon in my scan , but I can return stops and gyms , seems niantic is blocking pokes now

**Comment by mattrat88** [comment]
this is really fun a suck

**Comment by mattrat88** [comment]
Going to lol

**Comment by jecates** [comment]
I'm seeing the issue now, too. Looks like it's scanning, but no pokemon show up.

**Comment by andrewda** [comment]
@jecates There was a major API change within the past hour. It needs to be dealt with before Pokémon, Pokestops, and gyms will start showing up again.
