### ISSUE TITLE
Works great with home wifi but get error " Unable to exchange token for authorization code"

### ISSUE THREAD

**Issue by Genek1968** [mchristopher/PokemonGo-DesktopMap#607]
![wifi error](https://cloud.githubusercontent.com/assets/20802244/17377213/d0638524-5986-11e6-9eed-b62b53d6fa14.jpg)

I use Surface pro 3 ( Win 10) to run the Map. Works great with home Wi-Fi but if I connect to a mobile hot spot Wi-Fi from a T-Mobile device I get the above error.   The mobile Wifi is 4GLTE . I'm   able to go online.  Tested internet speed and it's good (40mb/sec) . So I know the wifi is good.  Any ideas how I can resolve this issue.  Thanks

**Comment by Mirx** [comment]
You shouldn't be posting screenshots with your api key visible...

**Comment by Genek1968** [comment]
Thx Mirx. I took it out.

**Comment by zaqrwe** [comment]
Did you check if PTC service is down?

**Comment by Genek1968** [comment]
PTC service good.  I'm able to log in home wifi no problems but If I try mobile hot spot then errror
