### ISSUE TITLE
Possible config.ini solution for recent 10 second scan delay change

### ISSUE THREAD

**Issue by rickymiles22** [mchristopher/PokemonGo-DesktopMap#608]
Yesterday Niantic changed the scantime for pokemon appearing in game from 5 seconds to 10 seconds, this means at a 5 second scan time this radar map misses 50% of the scanned areas. 

I think I found a solution, for me the file is:
C:\Users\[NAME]\AppData\Local\pokemon\app-0.1.6\resources\app\map\config\config.ini
Change the line 
#scan-delay:             # default 5
to
scan-delay: 10            # default 5

You can quickly open the file by running
%localappdata%\pokemon\app-0.1.6\resources\app\map\config\config.ini

**Comment by KikkomanChow** [comment]
when I run multiple instances, 1 instance would get the 10 scan-delay, but the other ones would revert to 5.

**Comment by pocketq10** [comment]
how exactly are you running multiple instance?? im running the program twice on my computer but it just a copy of the master.

**Comment by KikkomanChow** [comment]
I also run multiple programs, each using different ptc account and each with different coordinates. 
I minimize all except 1, and it shows all the scans for all the accounts.

**Comment by pocketq10** [comment]
ah ok you have to change the coordinates. thanks kikko.

yeah i know of that one already ricky haha thanks for the reply tho

**Comment by Benturd** [comment]
Is there a Mac alternative that is available? If anyone can translate, it would be greatly appreciated.

**Comment by mg6101** [comment]
There is but it looks to be irrelevant. Niantic changed more than this at roughly 4PM EST. Every scanner seems to be down.

**Comment by obamaphone** [comment]
mg6101 is right. the Pokécops are out in full force...

**Comment by Benturd** [comment]
Including the scanners that refresh at an increased rate? Which means that the game would have to be actively incorporating a radar into it then right?

**Comment by iPaulis** [comment]
I've done the scan time change and still does not work.  I've tried both with PTC and Google login. No pokemons at all.

**Comment by mg6101** [comment]
@Benturd Even changing the scan time does not work. People on the Pokemon Go Dev subreddit are working on reverse engineering the changes and believe that they are close. Once that is done, changes to the main mapping tool, AHA, can be solidified. Then the guy who rolls that tool into this stand alone app can update his app. Until that happens, we are all out of luck.

**Comment by Madman8** [comment]
mega bummer. I know we all love free, but it is amazing that so many people are doing all of this work to help other people and then updating an app that was built to help people for free, then got blocked, then rebuilt, etc etc, all for free... it's amazing. I am DEF donating when this comes back up!
