### ISSUE TITLE
Scan Settings

### ISSUE THREAD

**Issue by Shogunz1** [mchristopher/PokemonGo-DesktopMap#610]
With the recent changes what scanning options is everyone using? I used to run a bigger scan of 10 but now that seems illogical.

**Comment by KikkomanChow** [comment]
5 (which seems like it's already too slow for)

**Comment by Shogunz1** [comment]
yeah lol. Im so used to using one account to cover a 10 scan size. I have to have two now. Thinking about adding one more ptc account too lol.

**Comment by MacDogg** [comment]
Just understand the times when you get a bigger scan radius going.  If we can only scan every 10 seconds then this is what we have:
Scan radius 4 has 37 circles.  After the 1st one appears, you have 10 seconds times 36 more.  That is 360 seconds to complete the scan.  That means the first, center circle will refresh in 6 minutes.  That will leave at most 9 minutes left on something that spawned 1 second after the circle appeared.
If you go to a scan radius of 5 there are 61 circles.  Do the math and that is 10 minutes for the center circle to refresh.  That will leave at most 5 minutes left on any Pokemon.

**Comment by Shogunz1** [comment]
TY Mac.

**Comment by PokemonCindy** [comment]
How to scan like that @MacDogg o.0?
