### ISSUE TITLE
[SUGGESTION] Notify - Within Radius

### ISSUE THREAD

**Issue by crkellen** [mchristopher/PokemonGo-DesktopMap#611]
So I have a spawn point in my backyard because of the pond. However, what spawns is not usually something I want to be notified for (only dratini really). But I still want to catch a few of them, like slowpokes.

I don't however, want to be notified about slowpokes that are half a mile away (I do a 5 search radius to hit all of my neighborhood). A very non-essential, unimportant feature addition could be adding in a secondary notification for chosen pokemon, within a given radius. (Lets say 1 circle, or maybe 2, I would personally like it to be user defined).

If I am in the wrong by creating this suggestion, I apologize.

**Comment by ManiacDC** [comment]
I would agree with this suggestion.
