### ISSUE TITLE
Outage? 

### ISSUE THREAD

**Issue by Gentleman-Taco** [mchristopher/PokemonGo-DesktopMap#613]
I cannot get logged in with either PTC or Google.

**Comment by QyyBAAASSH** [comment]
Same here, outage

**Comment by kebabas** [comment]
Same here. i think it temporary.

**Comment by rickymiles22** [comment]
Same.

**Comment by kringon** [comment]
Same here. Not going to troubleshoot now, but hopefully it will be up by tomorrow morning.

**Comment by PokemonCindy** [comment]
Same.

**Comment by Melo88** [comment]
http://ispokemongodownornot.com/

**Comment by jijetelu** [comment]
it is possible that N* did something to block this ?

**Comment by Gentleman-Taco** [comment]
PTC servers are down. I think they have to be up for the API to work.

**Comment by QyyBAAASSH** [comment]
> it is possible that N* did something to block this ?

As far as we know, no.

**Comment by jijetelu** [comment]
if all the servers are down, why can I connect with the phone just fine ?

**Comment by thatoneguyyouallknowbutdontlike** [comment]
It was working for me as well until I ended the session to create a new API. Tried logging in after that and got "outage".

**Comment by Gentleman-Taco** [comment]
Both Pokémon Go and PPTC servers are listed as unstable.

**Comment by TheFalseKing** [comment]
I'm having the same issues. I thought it was because I changed a setting ; /

**Comment by kebabas** [comment]
It works now

**Comment by david123w** [comment]
its back online

**Comment by jijetelu** [comment]
yea :D

**Comment by TheFalseKing** [comment]
Are you guys picking up any pokemon? I can't see, to find any now.

**Comment by QyyBAAASSH** [comment]
YEAAAAAAH

**Comment by kringon** [comment]
Should close this issue now.

**Comment by Gentleman-Taco** [comment]
Scanner is up but no Pokemon are appearing.

**Comment by david123w** [comment]
no pokemon are appearing

**Comment by Shogunz1** [comment]
yeah no pokemon here either

**Comment by Shogunz1** [comment]
probably just have to give it some time

**Comment by jijetelu** [comment]
wtf !!!

**Comment by kebabas** [comment]
Yea,  we should give it some time...

**Comment by TheFalseKing** [comment]
In the console it's not even picking up pokemon, stops or gyms. Hopefully in time...

**Comment by kebabas** [comment]
By the way guys , anyone knows where is the best dratini farm ?

**Comment by Gentleman-Taco** [comment]
Closing topic since there is one specifically on the lack of scanned pokemon above this and the server are up.
