### ISSUE TITLE
Scans end up blank

### ISSUE THREAD

**Issue by MissStabby** [mchristopher/PokemonGo-DesktopMap#614]
after the outage it returned only to get blank scans

**Comment by david123w** [comment]
no pokemon are appearing

**Comment by Gentleman-Taco** [comment]
Pokémon Go and PTC servers are all struggling right now.

**Comment by SmilinItalin** [comment]
mines not working either lol...... and i show the servers are running well.......maybe the finally did it ?

**Comment by QyyBAAASSH** [comment]
I can say that app state is linked to Pokemon Server so just wait for them

**Comment by jijetelu** [comment]
troublesome, the phone detects pokemons

**Comment by SmilinItalin** [comment]
hmmmmm lol maybe they finally found a way to block the API?

**Comment by Gentleman-Taco** [comment]
Nah their servers are still struggling. PTC is down again.

**Comment by linxspider** [comment]
could this be related?
https://twitter.com/nycpokespawn/status/760932605097308160

**Comment by QyyBAAASSH** [comment]
"Following a supposed API change, we will be down for approximately 24 hours." ??

**Comment by PokemonCindy** [comment]
Its going to be pretty long hours without Pokemap, seems like that.

**Comment by TheFalseKing** [comment]
Noooo my pokemans : (

**Comment by PokemonCindy** [comment]
No footprints and now absolutely nothing, GG shitTic.

**Comment by YoLinKin** [comment]
My question is after N* saaw soooooo many people leave the game when they took out the foot prints why instead of trying to limit the service why dont they speak with the guys here to team up and sort out their tracker?

**Comment by SOLIDTROY77** [comment]
The Plural of Pokémon is Pokémon.....Thats why the server dropped.....to many people searching for Pokémons......*FACEPALM*

**Comment by linxspider** [comment]
found the related thread here.
https://www.reddit.com/r/pokemongodev/comments/4w0jum/all_ptcgoogle_logins_failing_from_api/

**Comment by MacDogg** [comment]
Fun while it lasted.  Hopefully someone fingers out a way to make scanners worked again.
Deuces!

**Comment by kringon** [comment]
https://github.com/NECROBOTIO/NecroBot/commit/35339c3f527e7f934ae5fae6a7c7aa45e246be32

Looks like they changed mapObjects. A fix is on its way.
