### ISSUE TITLE
No pokemon on scanner

### ISSUE THREAD

**Issue by Optimus-Prance** [mchristopher/PokemonGo-DesktopMap#615]
I know I'm likely not the only one, but the tracker doesn't seem to pick up any pokemon now after the update, not even pidgeys or rattatas :(

**Comment by pocketq10** [comment]
yeah it just hsppen to me as well lol i get a java script error thought that was it

**Comment by Optimus-Prance** [comment]
I don't know, I think the update for the spawn times busted the tracker personally

**Comment by hotsmiles2000** [comment]
yep no pokemon lol lucky i was at home just listening to kids be annoying watching it scan thanks for the scanner and hope its back up soon to keep me busy

**Comment by marcox199** [comment]
Well I keep hearing the notifications for found pokemon.
What is that update for spawn times?

**Comment by trev4788** [comment]
Same problem overhere

**Comment by sohfah** [comment]
Same

**Comment by obamaphone** [comment]
This is what I know: 

At about 3:50PM (eastern time) I couldn't login via PTC. I checked some websites and they also said PTC was down.
While PTC was down, your map reported "outage"... All this lasted for about 30 minutes.
Simultaneously, they both came back online simultaneously around 4:22PM.
I can see Gyms, Pokestops and lured Pokestops but no actual Pokemon.

That's my report. Hope it helps.

**Comment by mg6101** [comment]
https://github.com/mchristopher/PokemonGo-DesktopMap/issues/608

This is how you change the scan timing to change the default scan time of once every 5 seconds to once every 10 seconds. Anything faster than 10 seconds will not show Pokemon. Either shrink your radius to compensate or run multiple instances with multiple PTC logins at appropriate time offsets.

**Comment by mg6101** [comment]
You have it correct. At roughly 4PM EST Niantic changed the way everything works. No scanners work at all.
