### ISSUE TITLE
Error on Windows

### ISSUE THREAD

**Issue by cabotillo** [mchristopher/PokemonGo-DesktopMap#616]
![windowspokemon](https://cloud.githubusercontent.com/assets/15909691/17381153/d91d5174-59ca-11e6-9f38-40edf39d6fc9.PNG)

**Comment by YoLinKin** [comment]
I`m also having the same error upon login. been happening for about 2 days now but the scanner has been running OK-ish untill today with the "Outage" thingy. today though i have changed the scan time from 5s to 10s (as explained in #806 issue) but the change did not take place. could the two be related?
