### ISSUE TITLE
4:45pm EST, after Outage

### ISSUE THREAD

**Issue by JaymerJaymer** [mchristopher/PokemonGo-DesktopMap#618]
some other threads talked about all API calls stopping about 10-15 mins ago.
This is back up now on OS X and scanning circles are appearing, but no mons, stops or gyms.

![Image of bad scanning](https://scontent.ftpa1-2.fna.fbcdn.net/v/t1.0-9/13873174_10155160341273146_223113903550431473_n.jpg?oh=3d1bb495d602ea3cbf48e8baaf79c968&oe=582B6E61)

**Comment by hunterd95** [comment]
exact same problem here. i  generated a new API on a different email and it made no difference.

**Comment by NickHab** [comment]
same issue

**Comment by Kirbay** [comment]
Looks like they've figured out a way to detect if you're using a scanner some how...

I wonder if they're just looking at the device info they've been collecting for a while now and blocking anyone not on android/ios.. Does anyone have an android based map they could test with?

**Comment by hotsmiles2000** [comment]
im on my computer scanning and its not working either

**Comment by RubberDogTurds** [comment]
There was an API change in PoGo. All trackers are currently down.

Sources:
https://twitter.com/nycpokespawn
https://www.reddit.com/r/TheSilphRoad/comments/4w0nyl/desktop_scanner_and_pokescanner_stopped_working/

**Comment by mg6101** [comment]
https://github.com/mchristopher/PokemonGo-DesktopMap/issues/608

This is how you change the scan timing to change the default scan time of once every 5 seconds to once every 10 seconds. Anything faster than 10 seconds will not show Pokemon. Either shrink your radius to compensate or run multiple instances with multiple PTC logins at appropriate time offsets.

**Comment by EternisRequiem** [comment]
@mg6101 I'm confused, what does that have to do with an API change?  Have you gotten this to work for yourself?

**Comment by mg6101** [comment]
I had it working for roughly 4 hours. But since then, Niantic has changed their API significantly. No scanners currently work.

**Comment by obamaphone** [comment]
Dude, I live in Tampa bay too! Ballast Point is the place to be!

**Comment by JaymerJaymer** [comment]
heyi'm in brandon
never been to ballast point "in person"i GPS over there.
have probably caught more exotic stuff at BP, but running a loop around Amalie Arena is decent
jaymer...
