### ISSUE TITLE
Scanner not functioning

### ISSUE THREAD

**Issue by skridjet** [mchristopher/PokemonGo-DesktopMap#619]
It seems as though the scanner has stopped functioning correctly. The map is reading "operational", however gyms are listed incorrectly and no pokemon are showing up on the scanner. I have tried generating new APIs and restarting the app but nothing has worked so far.

**Comment by mg6101** [comment]
https://github.com/mchristopher/PokemonGo-DesktopMap/issues/608

This is how you change the scan timing to change the default scan time of once every 5 seconds to once every 10 seconds. Anything faster than 10 seconds will not show Pokemon. Either shrink your radius to compensate or run multiple instances with multiple PTC logins at appropriate time offsets.

**Comment by kringon** [comment]
@mg6101 more like slightly ;) A fix fore the core files is in progress afaik.

https://github.com/NECROBOTIO/NecroBot/commit/35339c3f527e7f934ae5fae6a7c7aa45e246be32

**Comment by mg6101** [comment]
Really?! Thats all they did. Lol.

**Comment by kringon** [comment]
@mg6101 No, i was wrong. THey have obfuscated the objects aswell

https://www.reddit.com/r/pokemongodev/comments/4w124h/pokemon_go_antibots_reverse_engineering/

**Comment by Madman8** [comment]
I hate being such a dev/programing illiterate. I want to understand why my map isn't working, or how to do updates (if there are any) or how to implement APIs or put things on my iPhone... but I am dumb and dependent on the tit of you folks and thereby stuck until one of you have the mercy to make a braindead version of things where i can drool on my keyboard grin with an underbite and click ferociously on the "launch" "start" or "go" button.

**Comment by mohd19994** [comment]
its not work to all since 7 or 8 hour any body know if it will back scann or not ?
