### ISSUE TITLE
Pokemon Rarity

### ISSUE THREAD

**Issue by Id3ntyD** [mchristopher/PokemonGo-DesktopMap#622]
How did you choose which pokemon are belonging to which tier rarity? Is this some data you took from the code?

**Comment by pcecere** [comment]
there is a file called pokemon.json that has this information.
it has a spawn rate value, that I'm pretty sure it wasn't made up, and instead taken from some interface information from the game.

it looks like this:
"130": {
    "name": "Gyarados",
    "rarity": "Ultra Rare",
    "types": [
      {
        "type": "Water",
        "color": "#6890f0"
      },
      {
        "type": "Flying",
        "color": "#a890f0"
      }
    ],
    "spawn_rate": "2279"

**Comment by Id3ntyD** [comment]
Thank you for your answer :) Highly appreciated. Now I have no idea on how to extract such data and was wondering if you could create or have a list with all pokemons and their rarity (taken from the programm). Some of Rarity Lists out there are not done according to this.

This helps me to define spawn points far easier, as usually you have a spawn point common or uncommon and any pokemon from that can spawn there .) (helps me with keeping manual track haha).

Thanks in advance!
