### ISSUE TITLE
No pokemon pop up.

### ISSUE THREAD

**Issue by tucool** [mchristopher/PokemonGo-DesktopMap#625]
Hello guys, I just got back home from work and start up the program, however no pokemon showed up.  The gyms and Pokestops tracking still work but not pokemon.

**Comment by starstremr** [comment]
niantic changed the API so it is not showing them right now. waiting on fix.

**Comment by Madman8** [comment]
when it is fixed, I wonder if it will automatically come back to life for us or we need to re-download or do something in terminal god forbid, where idiots like me fall short.
