### ISSUE TITLE
Api change.. where is a good place to farm dratinis?

### ISSUE THREAD

**Issue by hunterd95** [mchristopher/PokemonGo-DesktopMap#626]
anywhere you like to go to?

**Comment by ShaggyChrist** [comment]
Before they changed the Api I was able find them around the tower of london a few times,close to the bridge.

**Comment by mangantj** [comment]
@hunterd95 this is not reddit

**Comment by Nodws** [comment]
San francisco or Cancun Mexico, now close thread
