### ISSUE TITLE
2 issues

### ISSUE THREAD

**Issue by whyfly0** [mchristopher/PokemonGo-DesktopMap#627]
1) Nothing is showing up now, the app says its functional, but there is nothing around? 
2) Notifications when a pokemon disappears constantly notifies and doesn't stop even if pokemon is removed from notification list and then reapplied.
Any help?

**Comment by IsExtant** [comment]
My first issue is that you haven't bothered to read any of the issues below this issue.
https://github.com/mchristopher/PokemonGo-DesktopMap/issues/621 
https://github.com/mchristopher/PokemonGo-DesktopMap/issues/623

**Comment by pill0ws** [comment]
I suggest waiting for those working on this project to update it. Over the past 2-3 days, Niantic has shaken it up a bit. People are hard at work figuring out what they did. Someone just posted on a possible place to look here http://imgur.com/a/1Xu1D

**Comment by whyfly0** [comment]
@ IsExtant, I did read them actually but as the new version of the app has been released in the past 2 hours and both of these posts are over 8 hours old, i thought they may have been addressed and I was just raising them as an ongoing issue. I apologize for your ignorance.

@pill0ws Thanks.

**Comment by HUN73R13** [comment]
@whyfly0 as stated under Version 0.1.7 Release, the only change is "Adding notice to main screen about outage."

**Comment by whyfly0** [comment]
@HUN73R13 Many programmers do all sorts of changes under the hood that they don't write in the change log because most of them are little things to keep the app working.

**Comment by MacDogg** [comment]
But if the issue was resolved it would have been mentioned is HUGE words or something.  :)

**Comment by HUN73R13** [comment]
It's ok, this is just a minor misunderstanding, anyway, regarding the notification issue, I faced the same bug you mentioned. I got multiple notifications (+4 to 6 alerts as I remember) and it kept alerting tho I clicked it and removed the pokemon.
and to mention something slightly related, the  notification menu (under options) float too high when adding a big list of Pokemons.

I'd love to see a feature like "Notify for any ultra rare pokemon".

**Comment by mohd19994** [comment]
@HUN73R13 how did u download version 1.7 and open it please tell me i cant download any version exept 0.7 cause its zip version

**Comment by HUN73R13** [comment]
@mohd19994 I didn't download the update, as it doesn't fix anything yet
but you can download it from here: https://github.com/mchristopher/PokemonGo-DesktopMap/releases
and click PokemonGoMap-Win.exe if you're on windows

**Comment by MacDogg** [comment]
I'm still using the old version because it is still showing the Gyms and Stops around me and in the downtown area (which I don't remember where they all are).  The data might be stale but at least I can look to see where to go to battle and get items.

**Comment by Aerokii** [comment]
@mohd19994 No point in downloading it- it just tells you that it's not currently working. Wait for 1.8, if that ever happens.

**Comment by seaturtle91** [comment]
My iphone shows pokemon, gyms and pokestops but my ipad mini has a blank map since the outage yesterday, but before that both showed everything just fine.  Both are running the same version of the PoGo app, the only difference is my ipad mini doesn't have GPS and my iphone does.  Are devices without GPS chips excluded now?  if I go buy an external GPS for my ipad mini will this fix my blank map?  (sorry, i'm obviously not a programmer)

**Comment by HUN73R13** [comment]
@macdogg I think the pokestops and gyms you're seeing are cached. The only downside to that is that gyms don't update "ownership". Because as far as I know the app can't get ANY data since the update.

**Comment by seaturtle91** [comment]
I hit some pokestops on the way to work this morning and caught a pidgey just to see if it worked, and it did.  Iphone works fine, but iPad mini just shows blank map and won't detect pokemon..

**Comment by psychoblue** [comment]
@seaturtle91, The one called PoGo Radar?  I've tried that today, and when i click Refresh Map, the box just says Please wait... and sits there.  Wrong app?

**Comment by seaturtle91** [comment]
@psychoblue  no, just using the Pokemon Go app and PokemonGo-Desktop Map

**Comment by psychoblue** [comment]
That's weird.  I'm just upset at Niantic that they'd go so far out of their way to screw with these things instead of actually fixing their game.  So much wasted energy.  

Anyway... so you load the desktop app (1.6?, 1.7?), use the mobile function and when you view it on your phone it works?

**Comment by seaturtle91** [comment]
@psychoblue no, my Desktop app just shows blank everything regardless of mobile or not.  What I was saying was about the actual PokemonGo game app that is running on both my iPhone and my iPad.  On the iPhone everything works fine.  on the iPad, there are no Pokemon and no pokestops or gyms - it's showing blank just like the Desktop app.  So, I was wondering the only difference between my phone and iPad is that the phone has GPS and the iPad doesn't.  If I plug in a Bad Elf external GPS to my iPad will the game app work fine just like it does on my phone?  then, if I plug a USB GPS into my PC will the Desktop App map suddenly show everything again?

**Comment by psychoblue** [comment]
I see what you mean.

*sigh*  This is depressing.  I was just starting to enjoy the game too.

**Comment by topcatzero** [comment]
@seaturtle91 My guess is that the latest update of the game requires gps and won't use location from just wifi and cell signal. I think this is to address the issue where people on android could use "battery-saver" location instead of "high accuracy" to make your avatar jitter and get free steps for eggs. So that is unrelated to this issue with the desktop map.
