### ISSUE TITLE
Error while opening, cant use the program at all! :(

### ISSUE THREAD

**Issue by RedFirebreak** [mchristopher/PokemonGo-DesktopMap#628]
I have not been able to get this program working at all,
When I start the program it immediately gives me this error:
![help pls 2](https://cloud.githubusercontent.com/assets/20814656/17396876/a934452e-5a35-11e6-9ac0-12d17adc1106.png)

When I press OK I get the screen with all the option, but now I cant login. When I press "sign in with google" I just get a white screen and nothing changes. And when I press "Login with PTC" It waits a minute before I get an error message saying "oops something went wrong and we couldnt log you in"

I have no idea what all this means, please help me :)

Thanks for even looking at my issue! Hope the community can help me

**Comment by torantal** [comment]
At this point in time only one information is relevant - mapping is blocked by niantic and devs are looking to reverse engineer the changes.

All that the map is useful for right now is locating lured pokestops and stats on gyms.

**Comment by MidKnightReaper** [comment]
Niantic changed the API yesterday rendering all mapping programs inoperable at the moment. They are working on a fix. Please close this issue. Thank you.
