### ISSUE TITLE
Have to manually move location pin

### ISSUE THREAD

**Issue by MrWuffle** [mchristopher/PokemonGo-DesktopMap#629]
I know the app isn't working atm cuz of Niantic's API change, but whenever I try to press the Location button on the bottom right, it just starts flashing and doesn't actually do anything. I also have the "Follow Location" option on, which also seemingly does nothing. And of course, Location is turned on on my laptop itself.

Operating System: Windows 10
Type of computer: Laptop
What login are you using: PTC

https://i.gyazo.com/55e9c98977593c8a601da1d8c65933c1.gif

**Comment by jwright777** [comment]
I worked around this by manually entering the location I wanted to scan before logging into the app under "config options".
Go to google maps, click and hold where you want to find the coordinates for it will then provide you with the longitude and latitude details for you to enter into the log in screen.

Obviously this only works if you want to continually scan one area
