### ISSUE TITLE
Reverse Engineer

### ISSUE THREAD

**Issue by PedroHenrique2** [mchristopher/PokemonGo-DesktopMap#632]
Hi guys hugs from Brazil here, I'd love to contribute with money at least 10 dollar, my suggestion is to analyze this site https://skiplagged.com/pokemon/, although it says that it's not working, it's ;)

**Comment by SnoozeFiesta** [comment]
skiplagged is crowdsourced.... that is completely different from how the pokemon map works. The Pokemon map uses the API and stuff. That website simply allows people to report where they saw a certain Pokemon, and places it on the map.

**Comment by PedroHenrique2** [comment]
I don't know anything about programming, I would have thought about that but it got timers it is possible to get time even from reports?

**Comment by jane0815** [comment]
Pokemons on skiplagged are not reported by people. They use mitm to scrape the data.

**Comment by PedroHenrique2** [comment]
that's explained, sorry guys, bets of luck I still have the gyms with me, but can't scan anything in Brazil expect for big concentration of people, my city doesn't work, closing this here
