### ISSUE TITLE
Recover previous version?

### ISSUE THREAD

**Issue by SkateCycleLee** [mchristopher/PokemonGo-DesktopMap#633]
Before the map stopped working, I had mapped a large area using v0.1.5 but when 0.1.7 was released my copy of 0.1.5 was deleted before I could copy it over and as such all my pokestop location data is gone. Is there any way to recover those map files?

**Comment by rjansen90** [comment]
%appdata%\pokemon-go-map

Pokestops are stored in a database there (as well as the pokemon, gyms etc). Maybe your data is still in there?

**Comment by MacDogg** [comment]
Mine auto updated to 0.1.7.  Kindy crappy because this am when I tried to look at the local gyms to go gank I just got the Opps error.

**Comment by SkateCycleLee** [comment]
Sadly it looks like the database file was erased with the new version. Opening the file that was appdata\roaming, there was only 2 stops in the file.
