### ISSUE TITLE
Weird behavior considering API changes

### ISSUE THREAD

**Issue by torreyt1991** [mchristopher/PokemonGo-DesktopMap#634]
So I've been following everything Niantic has done very closely over the course of the last week and before that. I've used a number of the apps and this one is definitely the best so far in terms of functionality, so I was as annoyed as everyone else when Niantic nuked everything. Right after that happened the other day, I opened the app and could see that it was no longer scanning anywhere for me. Just a few minutes ago, I decided to open up the app for the hell of it, and is began scanning on my location. I had it running for 30 minutes around a few different locations in my area but no Pokemon were showing up (as I expected).

I closed it out and opened it again, and it placed my location at the dead center point in the middle of Los Angeles (this was a bug that has happened to me randomly when I'd open the app since I first installed it). So I zoomed out on my map to drag it over to my city in Florida, and to my surprise I started getting notifications about nearby Pokemon appearing at the LA location! Once I moved the marker to my city, and zoomed in, it stopped. About 5 minutes later, I zoomed out without moving my marker and got this wave of notifications of Pokemon appearing (near LA), probably 100 of them in the span of 30 seconds. Then from there they began to come every few seconds as long as I was zoomed out and still are.

Just wondering if anyone knows why this is happening. I feel pretty confident that the notifications are either old or false, and no Pokemon icons are appearing on the map, but it just seems weird. Just wanted to see if this is useful in any way to anyone working on adjusting for the new API.

**Comment by torreyt1991** [comment]
![screen shot 2016-08-05 at 12 44 35 pm](https://cloud.githubusercontent.com/assets/5889424/17443797/a6431cca-5b0a-11e6-90c3-7d02468a08d0.png)

Still coming in every few seconds

**Comment by Shogunz1** [comment]
lol i have mine up with the hopes it will magically start showing Pokemon sometime lol. I do get notifications though, sometimes but cant see them.

**Comment by Shogunz1** [comment]
that's weird...it's showing lured pokestops and a pokemon labeled as lured to that stop. I just put my cursor over three different actively lured stops and it had one monster for each stop.

**Comment by torreyt1991** [comment]
Yeah since there's no icons it's clearly not "functional", but I guess considering the interval of notifications (every few seconds), does that mean it's firing a false positive every single time the scanner takes a new step?

**Comment by pcecere** [comment]
@torreyt1991 how do you get those notification from ELECTRON in your iphone??

**Comment by torreyt1991** [comment]
@pcecere The screenshot is just one from my notifications on my Macbook, but I actually customized my POGO Desktop app to push my phone notifications using the service InstaPush. This can also be done by utilizing an IFTTT recipe that fires a push notification when it receives an email (in which you have the POGO Desktop app send an email to the IFTTT address whenever a Pokemon is scanned).
