### ISSUE TITLE
[Suggestion] How to fix people from using this as a forum.

### ISSUE THREAD

**Issue by zunox** [mchristopher/PokemonGo-DesktopMap#635]
I been on reddit for some time and here reading articles and progress. This section has been miss used quite a bit. This is meant for issues with the program and not so much talking. A while back i purchased a domain. Over the past week i have been working to improve it. I added a forum.  Would the staff want to make their own thread or section so people can talk and not open up issues when its just general chat?

Anyways if interested everything is fresh. http://pokemongohelp.net 

Let me know if its something you guys would be interested in.

Cheers!

**Comment by rickymiles22** [comment]
The problem is reddit's pokemon go sub is so heavily moderated that it pushes people to areas like this.  If you mention anything about radar sites or a huge amount of other issues you get your post deleted and sometimes banned... It seems like the mods are working for Niantic at this point

**Comment by zunox** [comment]
Thats why Niantic cant ban post in the forum. Safe heaven.

**Comment by Regulator69** [comment]
Yea i know! kind of like in a section of github where you're supposed to be talking about the pokemon-map and you complain about others misusing these sections while you do nothing to contribute yourself but to self-promote a personally made site and contribute to the b.s. thats already on here.. yea i hate that too damn it... damn people make me sick! ;)

**Comment by obamaphone** [comment]
@Regulator69 LMAO!!!!

**Comment by SnoozeFiesta** [comment]
Fucking roasted

**Comment by Madman8** [comment]
LOL how do i virtual kiss @Regulator69?

**Comment by Regulator69** [comment]
ill give ya a hint..
:-o C::::::8   
 lol

**Comment by Madman8** [comment]
hahahhaha 8===D  
dick jokes. god love'm

**Comment by tinarazzburton** [comment]
Since this is a shitpost already, can someone explain to me how the "Go Radar" app from the iOS app store works?  I don't see a single post on /r/pokemongo or /r/pokemongodev talking about it, but it's actually showing all the pokemon near me and seems to be entirely accurate.

**Comment by Ezoteric** [comment]
@tinarazzburton install -> see -> know

**Comment by tinarazzburton** [comment]
@Ezoteric ... I have installed... I have seen... it works.  It shows real-time as new pokemon appear in my area.   What I'm not clear on is HOW it works.  It's clearly a different method than any of these scanners which use the API since none of the ones built with that method have been working for days.
