### ISSUE TITLE
scan work or not with the new api ?

### ISSUE THREAD

**Issue by sheryus** [mchristopher/PokemonGo-DesktopMap#637]
hi can you say me if scan work or not ? thank you

**Comment by MrAwesomers** [comment]
Hi, can you do some research before asking a question? The issues page is filled with posts that contain your answer. Thank you!

**Comment by unknownss** [comment]
Lol @ idiot sheryus

**Comment by MrKetchumAll** [comment]
Annoyed @sheryus Sheeshes, if you're gonna be that lazy, don't even bother playing pokemon go.
