### ISSUE TITLE
Now it's official. Reverse engineer IT.

### ISSUE THREAD

**Issue by PedroHenrique2** [mchristopher/PokemonGo-DesktopMap#638]
Guys check this out.

**Poke Search ‏@PokeSearchGo 44m44 minutes ago

When the site is working again if you could share it amongst your friends I'd really appreciate it. This project means a lot to me
0 retweets 7 likes.**

**Comment by mattrat88** [comment]
Android ? Or website

**Comment by danieliser** [comment]
@mchristopher - Looks like API has been cracked, time to update?

https://github.com/keyphact/pgoapi

**Comment by tinarazzburton** [comment]
I think everyone is using the ios app called "Go Radar".  It seems to be working really well and doesn't seem to use the API, though I can't seem to find any actual discussion on it.

**Comment by danieliser** [comment]
@tinarazzburton - Unfortunately that one will only be useful if your in a highly populated area with tons of users reporting data. IE NYC, LA etc.

**Comment by markus-zhang** [comment]
@tinarazzburton This is crowd sourced, so if you live in DT of a populated city, very good for you. Otherwise it shows basically nothing.

**Comment by TravisMeister** [comment]
@mchristopher Updaterino? <3
