### ISSUE TITLE
Quite possibly the end...

### ISSUE THREAD

**Issue by mg6101** [mchristopher/PokemonGo-DesktopMap#639]
The developer who created the AHAAAAAAA Pokemon go map that this project is based off of received a C&D letter today. He has decided to shut the project down and remove all code from Github. Looks like we might be dead in the water on this one.

https://github.com/AHAAAAAAA/PokemonGo-Map

**Comment by pocketq10** [comment]
i just saw the post too, sigh, when an app get this big it was bound to be easily discovered and get shut down. RIP

**Comment by Nodws** [comment]
Any Russian hax0rs willing to take the wheel?

**Comment by mg6101** [comment]
Looks like we might be saved after all.... new API was just published.
