### ISSUE TITLE
Please Run "Grunt Build" before starting the server Error

### ISSUE THREAD

**Issue by Shda0w** [mchristopher/PokemonGo-DesktopMap#641]
Hello All,

I think im pretty close to getting this running but when i try to execute the runserver.py command i get the error "Please run "grunt build" before starting the server. 

Did i miss a step? How do i fix this?

Thanks!

**Comment by crkellen** [comment]
Grunt is some sort of other library or API. I didn't fully read this, but it's the exact same issue.
Good luck:
https://github.com/scottstamp/PokemonGo-Map/issues/8

**Comment by srikad8** [comment]
run 'npm install' and that should run grunt build
I can confirm that version 0.1.6 with the map replaced with the new 'github.com/PokemonGoMap/PokemonGo-Map' does work.

**Comment by crkellen** [comment]
@srikad8 Do you have a tutorial or set of instructions somewhere that explains how to set that up?

**Comment by srikad8** [comment]
@crkellen The new official upstream repo is https://github.com/PokemonGoMap/PokemonGo-Map
The old instructions to get that running are here: https://jonaharagon.github.io/PoGoMapWiki/#!installation.md

I should clarify I got this working on linux, I am not sure what files need to be replaced for windows and osx. If you feel lost following these instructions just wait wait for an official release, @mchristopher  seems to know his shit and will probably release an updated version.

**Comment by Shda0w** [comment]
Hey all thanks for the quick responses i was able to run the 'npm install' command!

But now when i run the runserver.py command i tells me "It seems 'pgoapi' is not installed. You must run pip install -r requirements.txt again'. Which i have done and it ends with Successfully installed pgoapi -1.1.6 but then when i run the runserver.py command i get the same error message.

Any ideas?

**Comment by blackhattristar** [comment]
@srikad8 npm install grunt is bringing up `sudo: npm: command not found` 

Please help!

**Comment by Shda0w** [comment]
I was able to get it up and running!!!! turns out my last issue was because i had 64bit python installed not 32bit THANKS EVERYONE!

**Comment by LuckyYou** [comment]
I did the install and logged in fine but still says 0 pokemon upserted. what am I doing wrong, do I need to obtain a new api key from google?

**Comment by srikad8** [comment]
@blackhattristar what os are you using?

**Comment by blackhattristar** [comment]
@srikad8 I got it working on my DO Droplet. Not mac terminal though. All good! Thanks for the help!

**Comment by lungbubble** [comment]
So is the problem that one has 64 bit python installed instead of 32?  npm install grunt worked for me, but then typing "grunt build" doesn't do anything.  am I supposed to type that in a particular directory?  (windows)

**Comment by elvquant** [comment]
Had running PGM before API changed on my RaspberryPi : "Linux raspberrypi 4.1.13+ #826 PREEMPT Fri Nov 13 20:13:22 GMT 2015 armv6l GNU/Linux"

 pip install --no-cache-dir -r requirements.txt ... completly OK
xxhash ... Installed

```
$ npm install -g grunt-cli                    npm http GET https://registry.npmjs.org/grunt-cli

npm ERR! Error: failed to fetch from registry: grunt-cli
npm ERR!     at /usr/share/npm/lib/utils/npm-registry-client/get.js:139:12
npm ERR!     at cb (/usr/share/npm/lib/utils/npm-registry-client/request.js:31:9)
npm ERR!     at Request._callback (/usr/share/npm/lib/utils/npm-registry-client/request.js:136:18)
npm ERR!     at Request.callback (/usr/lib/nodejs/request/main.js:119:22)
npm ERR!     at Request.<anonymous> (/usr/lib/nodejs/request/main.js:212:58)
npm ERR!     at Request.emit (events.js:88:20)
npm ERR!     at ClientRequest.<anonymous> (/usr/lib/nodejs/request/main.js:412:12)
npm ERR!     at ClientRequest.g (events.js:156:14)
npm ERR!     at ClientRequest.emit (events.js:67:17)
npm ERR!     at HTTPParser.parserOnIncomingClient [as onIncoming] (http.js:1256:7)
npm ERR! You may report this log at:
npm ERR!     <http://bugs.debian.org/npm>
npm ERR! or use
npm ERR!     reportbug --attach /home/pi/bin/PokemonGo-Map/npm-debug.log npm
npm ERR!
npm ERR! System Linux 4.1.13+
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "grunt-cli"
npm ERR! cwd /home/pi/bin/PokemonGo-Map
npm ERR! node -v v0.6.19
npm ERR! npm -v 1.1.4
npm ERR! message failed to fetch from registry: grunt-cli
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /home/pi/bin/PokemonGo-Map/npm-debug.log
npm not ok

```
