### ISSUE TITLE
npm install not working (included debug log)

### ISSUE THREAD

**Issue by MrMOABy** [mchristopher/PokemonGo-DesktopMap#643]
I was getting to the grunt build step, and then it didnt install properly
[npm-debug.txt](https://github.com/mchristopher/PokemonGo-DesktopMap/files/405349/npm-debug.txt)

**Comment by LuckyYou** [comment]
try npm install -gruntfile.js that worked for me when all else failed

**Comment by MrMOABy** [comment]
Now Im getting this:

npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.

**Comment by LuckyYou** [comment]
https://github.com/mchristopher/PokemonGo-DesktopMap/issues/641 
check out this. 
also 

Remove all existing and previous versions of the map and empty your trash bin 
https://github.com/PokemonGoMap/PokemonGo-Map

re-download they are issuing fixes for bugs pretty rapidly 
you have to run the requirements install again and probably have to do the grunt install again as I did and it worked. I'm live right now

**Comment by srikad8** [comment]
Version 0.2 has been released, just download the executable : https://github.com/mchristopher/PokemonGo-DesktopMap/releases

**Comment by MrMOABy** [comment]
i actually just got it working, but when i go to http://localhost:5000/ it has the heading, but just a white screen
