### ISSUE TITLE
stuck at waiting

### ISSUE THREAD

**Issue by drippybutt** [mchristopher/PokemonGo-DesktopMap#645]
Installed fine and previous versions worked great. When I login it says waiting in the top and is not becoming operational. Not sure if it's me or the program.

**Comment by sirmicha** [comment]
Same Problem on OSX - No Problem on Windows10

**Comment by EstebanVargas10** [comment]
Same. macOS user.

**Comment by drippybutt** [comment]
I am on windows 10. You have a version on windows 10 that is showing pokeys!?!?!?! I must figure this out, let me reinstall and try again.

**Comment by Dayskyfairy** [comment]
Same on mac ! I tested before this new release, to install this program on Windows but never worked at all (stucked on loading please wait). But on my mac, it always worked until now.

**Comment by drippybutt** [comment]
The issues persists for me, it still says waiting. If only it said operational I could get that Dragonite that was ??? red and disappeared after a curveball great throw with an ultra ball and razzberry on the first try. :|

**Comment by clone1612** [comment]
It seems to be related to the xxhash dependency, this is what I see with the developer tools open:
![error_xxhash](https://cloud.githubusercontent.com/assets/4518410/17461174/ef6bd2c4-5c82-11e6-84b8-3f367105974d.jpg)

But looking at what's installed it clearly shows up:
![error_xxhash2](https://cloud.githubusercontent.com/assets/4518410/17461180/06cf855a-5c83-11e6-95df-fa965fe5bd46.jpg)

So maybe something related to a virtualenv with xxhash not being present there? Or that might just be my sleepy head talking.

**Comment by Dayskyfairy** [comment]
Hey !! I just tested the previous version, and it still works, no loading please wait, I see the map !
But no pokemon of course ^^
And it is stucked on loading please wait with this new version

**Comment by mchristopher** [comment]
Fixing an issue I missed on packaging, should have a new version up shortly.

**Comment by Dayskyfairy** [comment]
Thanks you rocks !!!! Big thanks from belgium <3

**Comment by drippybutt** [comment]
Thank you sir. You are a wonderful man.

**Comment by LuckyYou** [comment]
I just want to say bravo sir that was fast @mchristopher

**Comment by Nodws** [comment]
Also stuck at loading, nothing in console

**Comment by mchristopher** [comment]
Version 0.2.1 should fix the issue.
