### ISSUE TITLE
Cannot Move Location Marker

### ISSUE THREAD

**Issue by Tonikane** [mchristopher/PokemonGo-DesktopMap#646]
Can Drag location marker but on dropping to new location, it returns to where it was located previously.

**Comment by 23ten** [comment]
Do you have the "Scan follows location" option on? maybe it's jumping due to that.
Could be worth reinstalling it from scratch so the ini options are reset.

**Comment by espiritom** [comment]
oh man, i actually need to set the location to fixed in order to share the scan with my comunity. can some one tell me how to actually get the marker to not move? please?

**Comment by Tonikane** [comment]
Working fantastic now  Awesome
