### ISSUE TITLE
stuck at waiting issue persisting

### ISSUE THREAD

**Issue by drippybutt** [mchristopher/PokemonGo-DesktopMap#647]
I am on windows 10 and I have uninstalled 0.2.0, downloaded and reinstalled 0.2.1 and I am having the same issue with this version as the last. It is still stuck at waiting. I tried re-downloading and fresh install twice, just to be sure, and I have left it open for 5 minutes now.

**Comment by 23ten** [comment]
You need to open the Pokemon GO app with the account you're using in the Electron Desktop Map. Once you access with that account you'll be presented with TOS that you need to accept. Once you accept the terms and conditions the map will start working fine.

**Comment by Si4nne** [comment]
I had the same issue because I didn't initiate the game with fake PTC account.

**Comment by WojteKris** [comment]
in my console i got that: "Python: C:\Users\Profile\Desktop\PokemonGo-DestopMap-master\pywin\phyton.exe: can't open file './runserver.py':[Errno 2] No such file or directory" I search folder and i don't find any runserver.py file :cry:

**Comment by drippybutt** [comment]
Can I do this on my desktop, or do I have to log in on my phone? Im paranoid about making that connection

**Comment by 23ten** [comment]
@drippybutt sorry I missed this post - As I mentioned on the other thread, I'm afraid that you need to use the mobile app to accept the TOS of the game. It doesn't matter "where" (other phone, other tablet...) but it has to be accepted after logging into the game.
