### ISSUE TITLE
Problem with PokemonGoMap-Win.exe

### ISSUE THREAD

**Issue by spdragon** [mchristopher/PokemonGo-DesktopMap#648]
![problem](https://cloud.githubusercontent.com/assets/20884593/17461280/850a85ec-5cb9-11e6-96df-18d9b2dccef5.jpg)
How to solve this? I am a newbie for this.

**Comment by Sht12** [comment]
Solution!!! 
Just Ignore the error.

**Comment by spdragon** [comment]
But then i got error with the program
![problem2](https://cloud.githubusercontent.com/assets/20884593/17461382/370c7702-5cbd-11e6-8f4d-2de7dd5d7c38.jpg)

**Comment by Joaomms** [comment]
This seems to be a problem with your Google API key. Try to create a new one, it worked for me.

**Comment by SolutionNine** [comment]
@Joaomms I just got back from work and saw that it's fixed? What new stuff am I having to install in order to update it?

**Comment by Joaomms** [comment]
I just installed the 2.1 version and created a new google API and it works fine now :)

**Comment by SolutionNine** [comment]
Okay, awesome!!

**Comment by spdragon** [comment]
@Joaomms Oh god it fixed! Thanks you!!!!

**Comment by Nikage127** [comment]
I have the same issue, i just created a new browser API but i still get the same error. Maybe it takes some time for the API to be active and used?

**Comment by Siceleys** [comment]
I dont get any error but It wont load Pokemon on my map.. someone can help me?

**Comment by wucop** [comment]
I got the same issue, console is saying:

`2016-08-07 10:55:58,545 [ search_worker_0][        pgoapi][    INFO] Creating a new direct request...`
`2016-08-07 10:55:58,545 [ search_worker_0][        pgoapi][    INFO] Adding 'GET_MAP_OBJECTS' to RPC request including arguments`
`2016-08-07 10:55:58,546 [ search_worker_0][        pgoapi][    INFO] Execution of RPC`
`2016-08-07 10:55:58,848 [ search_worker_0][        pgoapi][    INFO] Cleanup of request!`
`2016-08-07 10:55:58,851 [ search_worker_0][        search][   ERROR] Search step 1 map parsing failed, retyring request in 50 seconds`

**Comment by Siceleys** [comment]
016-08-07 10:57:13,391 [ search_worker_0][        search][   ERROR] Search step 1 map parsing failed, retyring request in 20 seconds

Yeahh , me also

**Comment by Nikage127** [comment]
Ok i solved the problem by creating a new project and getting a new API key from the new project!! Hope this helps!

**Comment by Sid733** [comment]
link of 2.1 verison please ??

**Comment by wucop** [comment]
@Nikage127: nope, this didnt help me ...

**Comment by zaqrwe** [comment]
Problem looks like the same as in earlier versions - on google API dashboard click on link javascript API and then enable it

**Comment by Siceleys** [comment]
@zaqrwe how to do that?

**Comment by zaqrwe** [comment]
google api console> click dashboard. You will see many links. Click on the one "Javascript API" or something like that, then on the top of page hit "Enable API" and wait a while

**Comment by wucop** [comment]
@zaqrwe: it is already enabled, I am also able to see the requests in the dashboard.

**Comment by zaqrwe** [comment]
maybe antyvirus/windows firewall not allows you to read map? My Windows 10 AVG said "squirrel.exe" was a virus first

**Comment by Siceleys** [comment]
ahh okay I will shut down my firewall ;D maybe that helps.

**Comment by zaqrwe** [comment]
if it will, You should add program exe files as exceptions rather than turning firewall off :P

**Comment by Sid733** [comment]
link plz?//

**Comment by Siceleys** [comment]
ohwww, I had an update for java. Maybe that was the problem?

**Comment by wucop** [comment]
It could also be this issue: https://github.com/mchristopher/PokemonGo-DesktopMap/issues/653

Can't try atm since I dont have a 2nd Smartphone available

**Comment by Siceleys** [comment]
It still wont load. :(

**Comment by zaqrwe** [comment]
@Sid733 what link?
