### ISSUE TITLE
How to decrease scan size &/or increase rate of scan?

### ISSUE THREAD

**Issue by SolutionNine** [mchristopher/PokemonGo-DesktopMap#649]
I am kind of clueless, but I did read a lot before asking the question.

I know that refresh rate was changed on the server side so 10 is what might be absolute, currently.
However, is there a way for me to make the scan size smaller so that it covers less space? I want the scan to cycle through more quickly by not being so large.

Or am I misunderstanding something?

**Comment by Cromi38** [comment]
Before you log into the map when you can put in your API there is a box labeled radius or something of the sort.  Change that.

**Comment by SolutionNine** [comment]
@Cromi38 Thanks so much. So, is 10 the fastest we're scanning these days?

**Comment by Cromi38** [comment]
It's actually size, the lower you put it the faster the scans will be. I find myself more comfortable at 5 or 6 with the speed.  But this was before the 10s refresh rate. Try it out and check how fast the radius updates by clicking filter then turning on updated area or whatever.  Everyone's settings are different.

**Comment by SolutionNine** [comment]
@Cromi38 okay, I will. Filter in the ini or on the actual UI?

**Comment by Cromi38** [comment]
@SolutionNine in the actual UI.  You should be able to toggle something on to show refreshed areas in a regtangle shape.  Should give you an idea of how fast it's scanning and how far.

**Comment by SolutionNine** [comment]
@Cromi38 Oh, the scanned areas. Yeah I always have it turned on. Making it smaller has definitely helped.

Thanks for making it easy for me. Appreciate it!

**Comment by Cromi38** [comment]
@SolutionNine no problem buddy, I'm always here to help :D. Let me know if you have any more issues I might be able to solve.
