### ISSUE TITLE
any chance to make it work on android?

### ISSUE THREAD

**Issue by barby1606** [mchristopher/PokemonGo-DesktopMap#65]
is there any chance to make it work on android?

**Comment by lcddrm** [comment]
Porting to Android is a pain in the ass. The last update added mobile support. You can open the map on your computer and connect your mobile device via QR Code. This lets you view the map on the mobile device

**Comment by CrystaX01** [comment]
@lcddrm That doesn't help much tho since the App stops updating after less then an Hour. And you aren't home to be able to Refresh the map then.

**Comment by TaylorZaneKirk** [comment]
@CrystaX01 Do you know where in the code that timeout could be modified?

**Comment by CrystaX01** [comment]
It's surely not in the code. It's probably rather a time-out from Nintendos API since one user asks for to Data I guess. But I have no real clue at all. Just a guess.

**Comment by TaylorZaneKirk** [comment]
@CrystaX01 That makes perfect sense. Thank you!
