### ISSUE TITLE
Just a quick question about scanning speed

### ISSUE THREAD

**Issue by LitoOsaka** [mchristopher/PokemonGo-DesktopMap#650]
V0.2.1 work fine for me, but it's much much slower than when it was like 0.1.5. This is just because Niantic throttle the request rate to 10s, there's nothing I can do right?

PS. SO GLAD THIS WORK AGAIN. THANKS DEVS FOR YOUR HARD WORK!!!!!!!!!!

**Comment by Cromi38** [comment]
I was actually wondering the same thing and about to make a post myself.

**Comment by Siceleys** [comment]
Can someone help me to download it and shit? :dancer:

**Comment by Cromi38** [comment]
What is your exact problem?

**Comment by EiTeR94** [comment]
scanning is veeeeery slow

**Comment by Cromi38** [comment]
Are you using a Java API? If you are then I did hear a rumor that they are making new accounts accept the ToS on Pokemon go before being able to see the API files or something like that. So if that's the case try logging onto that gmail on pogo and agreeing to everything and making an account THEN try the app again and see if it changed anything.  If it's none if these make sure that you have "show Pokemon" turned on in the filter area of the UI.

**Comment by EiTeR94** [comment]
change nothing scan is really slow and show not many pokemon
