### ISSUE TITLE
Multiple Instance JavaScript Error

### ISSUE THREAD

**Issue by KrogerKandy** [mchristopher/PokemonGo-DesktopMap#651]
I've been getting an error occasionally when trying to run two instances of the client, sometimes when I try to run three.  This error tends to pop up more often the longer I wait before opening an additional instance. Check out the attached image.

![9049cd8c21bbcd519e2665a1b98dfafc](https://cloud.githubusercontent.com/assets/20885223/17461530/1cb9271a-5c5e-11e6-9f0c-6276ef217a49.png)

Version: 0.2.1
OS: Windows 10 64-bit
Login Method: 2-3 PTC accounts

Ways to reproduce this error:
(1) Login with multiple clients, eventually this error will trigger
(2) Close the client and reopen it immediately, and this error may trigger
(3) Set one client into server mode, and connect several others. Eventually this error will trigger.

**Comment by LezChap** [comment]
I'm getting what looks like the same error whenever I log out, and log back in on a single instance using Win10.  Looks like when I log out it doesn't close the TCP listener or whatever it's using, and then tries to re-open it resulting in an error and being unable to log in.  Completely closing the instance, and re-opening it has thus far allowed me to log in.

**Comment by Siceleys** [comment]
Can someone help me on skype? xD Skype: bart870

**Comment by similikitip** [comment]
I'm on win7 x64 .
Same errors.
This page didn't load Google Maps correctly. See the JavaScript console for technical details.

**Comment by KrogerKandy** [comment]
Looks like this error can also be triggered by putting the first client into server mode, and trying to connect a second client afterwards. Still no comment or status change from the dev so far though.
