### ISSUE TITLE
A version for Android ?

### ISSUE THREAD

**Issue by Skyparay** [mchristopher/PokemonGo-DesktopMap#652]
Hi, I was wondering if there was a version for Android or you think you do one. Thank you

**Comment by 23ten** [comment]
There's no real need for specific-mobile versions, Android or iOS. Once you have it running on your Desktop you can toggle on the "mobile" option and use the generated URL to access the map from any browser in any device and you'll be seeing the map in that device. Wouldn't that do?

**Comment by Skyparay** [comment]
It works thanks !

**Comment by Siceleys** [comment]
It won't load any pokemon by me :(

**Comment by Skyparay** [comment]
Install the new version and test

**Comment by Siceleys** [comment]
I already did :/

**Comment by 23ten** [comment]
@Siceleys, you may want to review the console logs from your app, some of the recent threads and, if they don't solve the issue, you can follow this and submit a new thread: https://github.com/mchristopher/PokemonGo-DesktopMap/wiki

@Skyparay, glad that worked :) you may want to close the thread?
