### ISSUE TITLE
Empty map

### ISSUE THREAD

**Issue by zabuza88** [mchristopher/PokemonGo-DesktopMap#653]
Downloaded last version,installed python etc.
My map is empty 
Windows 8 64b
Laptop

**Comment by 23ten** [comment]
Have you tried what is described in #647 ? 

> You need to open the Pokemon GO app with the account you're using in the Electron Desktop Map. Once you access with that account you'll be presented with TOS that you need to accept. Once you accept the terms and conditions the map will start working fine.

**Comment by drippybutt** [comment]
@23ten How can I log in and accept the terms of service without using my phone. I am a tad paranoid to login on the phone that Ill be using my normal account with.

**Comment by 23ten** [comment]
@drippybutt as far as I know, you can't. 
Depending on your circumstances, you could use a second phone (family members? non-playing friends?...) or a tablet to download the game, access it with the second account and then accept the TOS. Personally, the other phones/tablets I had access to didn't allow the game's installation so I had to use my own phone to access the second account, not ideal but...fingers crossed nothing happens.

**Comment by drippybutt** [comment]
maybe tomorrow ill get bluestacks and try to see if I can run it on there. Other than that, ill go visit my dad and use his phone for a minute...

**Comment by zabuza88** [comment]
@23ten thanks..It worked.
One question..How i can scan multiple location?
Can i get pokemon list and gps coords from this app?

**Comment by movak93** [comment]
How do I get the Map to work on an Iphone? I just have the desktop map for my Macbook.

**Comment by 23ten** [comment]
@zabuza88 , glad that it worked. 
As far as I know, you'd need to have multiple instances of the app running to scan multiple locations. There are a few threads about that and its challenges, personally, I've never done that so I can't help much. Try a quick search and see what you can find.

About the list of pokemons and locations, I don't think that's possible at the moment. I think I also saw in the few days before the API changes people requesting that feature but, for now, I don't think it can be done automatically.

**Comment by 23ten** [comment]
@movak93, you may want to check the answer from #652 

> There's no real need for specific-mobile versions, Android or iOS. Once you have it running on your Desktop you can toggle on the "mobile" option and use the generated URL to access the map from any browser in any device and you'll be seeing the map in that device. Wouldn't that do?

**Comment by 23ten** [comment]
@zabuza88, since this worked you may want to close the thread before more questions crop up :)
