### ISSUE TITLE
Multiple workers?

### ISSUE THREAD

**Issue by DarkChemical** [mchristopher/PokemonGo-DesktopMap#654]
Is it possible to make it like, for example, 5 different accounts scan the are? atm. IT is so slow. We would like it to get scanning arround 14 fields, but with this scanning speed eaven 5 is to much. 
As in, launch the programm 4 times, but make them apear on the same map"?

**Comment by Markx85** [comment]
It is possible, I'm runing 6 of them for our small city. Just open program multiple times, I run one in server mode, others without and they all appear on the same map :)

**Comment by rickg42** [comment]
Im trying to open the program multiple times, but it keeps shutting the previous one down and reopening, are there any other steps i need to make this work?

Thanks

**Comment by Roarma** [comment]
If you're on Windows: Run the shortcut which was created, not the .exe. The Exe seems to be an installer which installs a whole package into your AppData.
