### ISSUE TITLE
Not many Pokemon on the Map

### ISSUE THREAD

**Issue by Ekz0r** [mchristopher/PokemonGo-DesktopMap#657]
Hi there,

i have a problem, on my Map there are not many pokemons.
Why?

**Comment by Siceleys** [comment]
I also don't have any pokemon or gyms

**Comment by 23ten** [comment]
@Siceleys , have you tried #647 

> You need to open the Pokemon GO app with the account you're using in the Electron Desktop Map. Once you access with that account you'll be presented with TOS that you need to accept. Once you accept the terms and conditions the map will start working fine.

@Ekz0r is the map empty? or do you have some?

**Comment by Ekz0r** [comment]
Which Account is this for the Electron Desktop Map?

Not empty, i have some pokemon, but not many.

Anyone from Germany here, who can help me?

**Comment by movak93** [comment]
@23ten  How do I access the electron desktop map on my Iphone? I switched on the toggle sharing option on my Mac, but how do I open my account on the electron desktop map on my phone?

**Comment by ArnoM** [comment]
@movak93 if you click mobile you get a link. Just type it in your phone browser and you see the same map as on desktop

I also see a few pokemons. Only see 1 pokemon that isn't near a lure pokestop. Maybe it helps you debugging?

**Comment by ArnoM** [comment]
Add on that. Looks like if y move the pin around that the pokemons start to appear near the pin. Maybe a server side distance lock?

**Comment by 23ten** [comment]
I'm puzzled, not too sure what to recommend if you're seeing some. Are you guys in an area with many of them? I'm dragging the pointer around my map to some different areas and all seems to work as expected.

You could just verify what pokemons are listed in the "close" area of the game in your mobile (after closing and opening, for accuracy) and compare them with the list in the desktop map? Also, you can toggle the "Scanned Locations" option on so you can have a look at what areas are being scanner, maybe you have to wait a bit until all pokemons in areas a bit further away appear.
