### ISSUE TITLE
Javascript error upon entering app

### ISSUE THREAD

**Issue by edenmystery** [mchristopher/PokemonGo-DesktopMap#660]
How could this be fixed? Is that normal?
![this](https://cloud.githubusercontent.com/assets/20885970/17461924/2648f4b6-5cce-11e6-93e5-3e3f4963420e.png)

**Comment by 23ten** [comment]
Sometimes I get errors when opening the app but when I click "OK" it disappears and the app runs anyway, is the same for you? can you just click "OK" and ignore the error? or does the map fail?

**Comment by edenmystery** [comment]
@23ten the map runs, but I can't see a single pokemon.

**Comment by 23ten** [comment]
@edenmystery and have you tried #647 ?

> You need to open the Pokemon GO app with the account you're using in the Electron Desktop Map. Once you access with that account you'll be presented with TOS that you need to accept. Once you accept the terms and conditions the map will start working fine.
