### ISSUE TITLE
OSX: Google Maps loading error

### ISSUE THREAD

**Issue by chrisisonwildcode** [mchristopher/PokemonGo-DesktopMap#661]
When I log in the map flashes up for a fraction of a second then grey screen with 

"This page didn't load Google Maps correctly. See the JavaScript console for technical detail."

This was with the current OSX version you have available.

OSX 10.11.5

**Comment by 23ten** [comment]
What does the JavaScript console say?
I've seen that error with invalid API keys, could you maybe try to generate and use a new one?

**Comment by earthchie** [comment]
My case was

MAP: Google Maps API error: RefererNotAllowedMapError https://developers.google.com/maps/documentation/javascript/error-messages#referer-not-allowed-map-error
Your site URL to be authorized: http://localhost:8005/

![image](https://cloud.githubusercontent.com/assets/7013039/17648551/f9b078ea-6243-11e6-86c0-34cc5f064ba0.png)
