### ISSUE TITLE
No Pokemons/Pokestops/Arena on Map

### ISSUE THREAD

**Issue by steffenkj** [mchristopher/PokemonGo-DesktopMap#663]
Like the titel, i cant find andy items on the map.
My OS is Windows 7 with the windwos installer.
In the developer console ther is comming this massage:

_2016-08-07 12:51:01,042 [ search_worker_0][        search][   ERROR] Search step 1 area download failed, retyring request in 30 seconds_

Is this a problem with the new API?

Best regards

**Comment by 23ten** [comment]
@steffenkj , try the solution from thread #647 

> You need to open the Pokemon GO app with the account you're using in the Electron Desktop Map. Once you access with that account you'll be presented with TOS that you need to accept. Once you accept the terms and conditions the map will start working fine.

**Comment by steffenkj** [comment]
Thanks. Works great
