### ISSUE TITLE
running multiple scan

### ISSUE THREAD

**Issue by pocketq10** [mchristopher/PokemonGo-DesktopMap#666]
is running multiple scans an option?

**Comment by majuss** [comment]
Yes just create multiple ptc accounts and create a shell script that starts multiple python-runserver with a delay.

'
usernumber=1
portnumber=8002
username=foobar
password=foobar
link=0
cd /home/pi/Desktop/pongo/resources/app/map

for i in {1..25}
do
python ./runserver.py --cors --auth-service ptc --location=gpslocation --port ${portnumber} --db /home/pi/.config/pokemon-go-map/pogom.db --gmaps-key gmapsapikey --username $username${usernumber} --password $password --step-limit 10 &
usernumber=$((usernumber+1))
portnumber=$((portnumber+2))


sleep 60

done
'


Then start ngrok with: 'ngrok http 8000'
And enter the https URL.
