### ISSUE TITLE
More than two accounts do not seem to work

### ISSUE THREAD

**Issue by Shogunz1** [mchristopher/PokemonGo-DesktopMap#672]
I have a couple of accounts and can only get two 'Operational' in the program. Seems others are having a similar problem.

**Comment by ac796** [comment]
Doesn't seem to depend on number of accounts, rather on the actual account you are using. I had 3 running, now only one is operational. Even if I close them all, the ones that were not operational remain not operational when launched.

**Comment by RedHerring27** [comment]
How do you use multiple accounts anyway?

**Comment by ac796** [comment]
Just run the app multiple times

**Comment by RedHerring27** [comment]
I tried that, but the I'm not able to change the location in the second instance. Instead when I move the location marker in either window it just moves the scan for the first instance. The second window just keeps scanning in a static location that's the same every time I reopen it.
