### ISSUE TITLE
Dont forget to donate

### ISSUE THREAD

**Issue by Shogunz1** [mchristopher/PokemonGo-DesktopMap#673]
This program is great. Hit that donate button to say ty because this takes work. mchristopher is doing this on his free time too. Only way I can play this game is because of this, disabled vet.

**Comment by pcecere** [comment]
done!! thank you @mchristopher

**Comment by hunterd95** [comment]
what do i do to get the map working again? i generated a new api but its not working.

**Comment by pcecere** [comment]
go to releases and download the version for Mac or PC ... https://github.com/mchristopher/PokemonGo-DesktopMap/releases

**Comment by Rengor** [comment]
Done! Thanks for the work on this!

**Comment by khloro** [comment]
Sorry i dont see the donate button

**Comment by Rengor** [comment]
Donate buttons are on the top of the login screen for the program.
