### ISSUE TITLE
Stuck at loading - This is the error in Console

### ISSUE THREAD

**Issue by dacutz3** [mchristopher/PokemonGo-DesktopMap#674]
Error getting location, trying second provider 
PositionError {code: 2, message: "Network location provider at 'https://www.googleapis.com/' : Returned error code 403."}
code
:
2
message
:
"Network location provider at 'https://www.googleapis.com/' : Returned error code 403."
__proto__
:
PositionError

**Comment by bobcobb** [comment]
I also get this. Did anyone find a solution?
