### ISSUE TITLE
Waiting instead of Operational

### ISSUE THREAD

**Issue by DaRealDfid** [mchristopher/PokemonGo-DesktopMap#675]
Instead of Operational there just Waiting written and nothing is loading. What can I do about it?

**Comment by jwitos** [comment]
Are you running a Mac version?

**Comment by markus-zhang** [comment]
I also have the same "Loading" screen since 0.17.0, I enabled every API but it doesn't work. I guess it's unstable right now so I'll wait for a while. Thanks for the good work anyway!

**Comment by Kevinclon** [comment]
works fine for me

**Comment by dacutz3** [comment]
I also got "please wait, Loading.."

**Comment by markus-zhang** [comment]
I checked the console and it only shows:

server up: null
main.html:146 Error getting location, trying second provider PositionError
main.html:148 Found location [45.5401,-73.6225] by ipinfo.io

Then it does nothing after that, not sure if I could enter some command to force it to go on?

**Comment by dacutz3** [comment]
@markus-zhang Same as mine console.

**Comment by markus-zhang** [comment]
@dacutz3 OK guys I got this running up smoothly. It's easy, I'm running win7 64, just INSTALL UNDER ADMINISTRATOR account, not user accounts. After that it runs smoothly.

**Comment by dacutz3** [comment]
@markus-zhang How do you manage to do that? I am using the .exe version of the Desktop Map

**Comment by markus-zhang** [comment]
@dacutz3  Just log off win7 and log in the Administrator account. If you don't know how to enable Administrator account for win7, you might need to google for it. I forgot what I did as it was a long time ago.

**Comment by dacutz3** [comment]
@markus-zhang Oh, I see what you mean.. I always use the administrator account on this computer.. still no luck.

**Comment by markus-zhang** [comment]
@dacutz3 Sorry to hear that...Not sure what you can do right now. I'm also reading reddit where a lot of users have the same problem.

**Comment by asavage44** [comment]
New accounts need to accept ToS in game before they can play.  I had this problem and tried another account that was level 3 or something and it worked right away.
