### ISSUE TITLE
(request) Run from command line?

### ISSUE THREAD

**Issue by Kevinclon** [mchristopher/PokemonGo-DesktopMap#676]
Is there a way to run it from command line, Where I supply username, password, cords and distance?

**Comment by Kevinclon** [comment]
O and server/noserver

**Comment by cyan** [comment]
did you found out a way? :/

**Comment by Kevinclon** [comment]
no, i just accedently closed so i opened

**Comment by Kevinclon** [comment]
But it would be extremely helpful for scanning large areas

**Comment by clone1612** [comment]
You can use the Pokemon-Map repository from the author himself that forms the basis for this app: https://github.com/mchristopher/PokemonGo-Map

That way you can run it from the terminal.

**Comment by Kevinclon** [comment]
Yea but i really like the features this has
