### ISSUE TITLE
[BUG] warning with Machop

### ISSUE THREAD

**Issue by PassyFox** [mchristopher/PokemonGo-DesktopMap#677]
Every time a Machop spawns the notification keeps on spamming. It only happens with this pokémon and his notification setting.

**Comment by bilgekan** [comment]
Same problem but it's dratini in my case.

**Comment by eritropp** [comment]
similar, but only with squirtle

**Comment by thebigsmileXD** [comment]
Pidgey and Weedle, same for me.
