### ISSUE TITLE
Quick scan a large area.

### ISSUE THREAD

**Issue by Pineyka** [mchristopher/PokemonGo-DesktopMap#679]
I discovered how you can quickly scan a large area. This may be a clue to mchristopher.

1.) I turn on the map and wait for a few seconds (2-3 field in green)
2.) I move the marker in a further area (outside radius scanning) wait 2-3 seconds
3.) renew step 2

It shows on the map plenty of pokemon at a distance

check it out and see if you are in the same or just me so scans.

1.  http://screenshot.sh/owk3uOKWfheME
2.  http://screenshot.sh/owqxOtnI2FAi6
3.  http://screenshot.sh/m7ue4Opmalv2Q

**Comment by dragitz** [comment]
Daium that helped !

It would be awesome if we could move to pointer by holding it

**Comment by jwright777** [comment]
I think this may be caused by other users having scans in that area, doesn't work for me as I live in a rural village

**Comment by Draag** [comment]
Are those the locations of lured Pokestops? It may be gathering the lured spawns. Turn on Pokestops and see if they're lured. Or check if all the spawned stuff has less than 3 minutes.
