### ISSUE TITLE
No Pokemon?

### ISSUE THREAD

**Issue by Reeblur21** [mchristopher/PokemonGo-DesktopMap#681]
Anyone having an issue with the new build?? I unfortunately don't see any pokemon between my google API or PTC acct. I generated a new api code for google, and accepted TOS in my secondary PTC acct. I also used the scan delay with default 5 and set it to 10 after it didnt work, still no luck. Only other thread i saw having an issue actually saw a few pokemon, i dont see anything :(

 any help would be awesome!

**Comment by angelo8800** [comment]
do you see other stuff like gyms and pokestops

**Comment by Reeblur21** [comment]
First thanks for the super quick response.

Second, its weird, i see the pokestops by my one residence, but not the other.

**Comment by jintan1994** [comment]
for me i can't see pokemons or pokestops nothing it's just the map what shld i do ??

**Comment by syropian** [comment]
I also don't see anything at all. Just an empty map.

**Comment by GusToughSon** [comment]
same Empty map
windows 10

**Comment by Reeblur21** [comment]
Figured it out, make sure you're enabling the javascript API in your google dev area.

**Comment by GusToughSon** [comment]
i thought it was, What did you do specifically ?

**Comment by GusToughSon** [comment]
my thing says "Waiting" 
i cant find what you mean "enable it" as far as i can see its enabled...
