### ISSUE TITLE
Only one field in green around the marker

### ISSUE THREAD

**Issue by Djidjisven** [mchristopher/PokemonGo-DesktopMap#685]
Hello,

When I put the marker in an area, only one field in green appears and nothing more.

http://hpics.li/c1a4eee

Someone know how I can resolve this issue to have the others fields in green around the marker ? This issue only appeared in the 0.2.1 version. It worked before, so I dont know why...

Thanks,
Dj

**Comment by jwright777** [comment]
Close the app, when reloading it change your scan radius to a larger number

**Comment by Djidjisven** [comment]
Thank you, it works :D
