### ISSUE TITLE
Notifications to android

### ISSUE THREAD

**Issue by Markx85** [mchristopher/PokemonGo-DesktopMap#686]
Hello!

I love this whole thing, really amazing work. I have just one more question/wish. Any idea, how it would be possible to send notifications to Android? It works great on Windows, but I don't want to check map on mobile whole time, it would be fantastic if I can somehow push windows notification of rare spawn to Android. 

Thanks!

**Comment by beestiel** [comment]
I have the same question, but for iOS! I saw a screenshot somewhere (Reddit?) of someone getting Electron notifications on their iPhone...

**Comment by Mackiiboy** [comment]
There are probably much more adequate methods for doing this, but a way that might be possible that I'm planning to try today is the following:

(1) reading the pogom.db database-file, (2) see if there are any new rare Pokémons, (3) generate a string with Pokemon name, the long/lat-coordinate for its spawn location and the time when it will despawn, and finally, (4) sending this string from Windows to my Android mobile.

**Comment by Mackiiboy** [comment]
@Markx85 I've figured out a way to implement steps (1) - (3) in Python and step (4) as an Android application by using Google Cloud Messaging. Now I'll get a push notification for each new rare Pokémon that spawns. If you are interested, I can make a tutorial for you next week. 

One extra feature that I want to implement but yet not have figured out how, is to set up a click event so the notifications for instance can open Google Maps.
