### ISSUE TITLE
Okay... need an expert response in regards to the Google API

### ISSUE THREAD

**Issue by koltb1** [mchristopher/PokemonGo-DesktopMap#687]
I have not been able to use a version with Google API keys. I've created multiple API keys and tried different things,..

When I enter the API key to this version, it says, "Oops something went wrong"

PLEASE HELP ME.... I really want this to work, since I cant use the older versions now....

**Comment by koltb1** [comment]
Google Javascript API is enabled already by the way...

**Comment by koltb1** [comment]
If someone  can detail a fix I will donate $500.

**Comment by TheDouglife** [comment]
Use F12 for developer console to see what it is / isn't loading, that should give you a head start.

**Comment by koltb1** [comment]
I was able to get it to work using PTC.
