### ISSUE TITLE
[Suggestion] Add ability to enter location names

### ISSUE THREAD

**Issue by andrewda** [mchristopher/PokemonGo-DesktopMap#69]
We should be able to enter the name of a location (e.g. `Portland, Oregon, USA` or a specific address such as  `2 Bryant St #220, San Francisco, California, USA`) instead of hassling around with coordinates. There are a ton of APIs (including a Google Maps one IIRC) to convert these location strings into coordinates if necessary.

**Comment by fenixasin** [comment]
Repeat of issue #41

**Comment by andrewda** [comment]
@fenixasin Nope, this is entering location strings. #41 is remembering saved longitude/latitude coordinates to use again in the future.
