### ISSUE TITLE
#### Repeated Notifications ### 

### ISSUE THREAD

**Issue by ffsd** [mchristopher/PokemonGo-DesktopMap#692]
I can see and hear notifications for selected pokemons but they keep **repeating** for the same pokemon and it unbarable to keep the map open. It happens in **every browser**.
This is an issue that already ocurred on previous versions.
How can I **just receive the notification once**?
This issue appears to happen to many users (maybe related to lure spawn pokémons)

**Is there anything I can change in the map file provided?**

      <div>
        <div class="form-control">
          <label for="notify-pokemon">
            <h3>Notify of Pokémon</h3>
            <div style="max-height:165px;overflow-y:auto";>
              <select id="notify-pokemon" multiple="multiple"></select>
            </div>
          </label>
        </div>
        <div class="form-control switch-container">
          <h3>Notify with sound</h3>
          <div class="onoffswitch">
            <input id="sound-switch" type="checkbox" name="sound-switch" class="onoffswitch-checkbox" checked>
            <label class="onoffswitch-label" for="sound-switch">
            <span class="switch-label" data-on="On" data-off="Off"></span>

**Comment by to-metrion** [comment]
The same has been happening to me, with previous versions as well. For me, it was definitely related to lures, only Pokemon spawning for a lure would get repeated notifications - the only way to make it stop was to place the lure out of sight until the lure expired, or a different Pokemon was attracted by it.
