### ISSUE TITLE
how to modify the scan delay ?

### ISSUE THREAD

**Issue by malnc** [mchristopher/PokemonGo-DesktopMap#694]
hi just downloaded this since AHAAAA's map is off and it's a great map and easy to use, but i live off-town and i need a faster scan to not miss pokemons who can be far from the scan center so how can i change that data to an acceptable delay ?

**Comment by luckylgames** [comment]
I believe the scan delay is pre-set so as not to trigger server throttling.

**Comment by ejd59005** [comment]
It appears each circle is now scanned every 10 seconds? It was 5 seconds before the API changes.

**Comment by malnc** [comment]
i've timed it and it's 15 sec, it's way too long

**Comment by ejd59005** [comment]
And I'm sure there's no way to change that? Might need to start utilizing multi accounts

**Comment by luckylgames** [comment]
Yeah I'd try that.

**Comment by mg6101** [comment]
You can't change the scan speed without triggering server throttling from niantic. You need to open a second instance of the map (with a different PTC account) 5 minutes after you open the first one. Then minimize the second instance and the first map will show updated from both of the maps.

**Comment by malnc** [comment]
i've tried to run it with two google accounts but the second is always "waiting" and no scan begins on the first map, so what should i do to make both scans operationnal
