### ISSUE TITLE
having problems with the new version of pokemonGo-Desktop-Map

### ISSUE THREAD

**Issue by Rawr2134** [mchristopher/PokemonGo-DesktopMap#695]
with the new api changes, i am getting this error ' This page didn't load Google Maps correctly. See the JavaScript console for technical details. ' what is the best way to fix this?

**Comment by apriest8781** [comment]
![error](https://cloud.githubusercontent.com/assets/20889794/17463669/cf3481d4-5c7f-11e6-8f9f-669cfd9df697.PNG)
Also getting an error at launch with latest version

**Comment by NT747** [comment]
having the same issues with Windows 10. but it works fine on my mac.
also created a new api as suggested, still doesnt work though

**Comment by GusToughSon** [comment]
i got around this by downloading old version, and using "updater"

**Comment by silvablue2016** [comment]
i dont see updater on old app?

**Comment by NT747** [comment]
no there is none.

just solved the problem by refreshing my old API a couple of times.

**Comment by ianedups** [comment]
@NT747 how did you refresh the api?

**Comment by GusToughSon** [comment]
The way i fixed this was to login on the ptc/google account made to use and accept tos start the player then close app and login on scanner.

**Comment by NT747** [comment]
@ianedups 

go on: https://console.developers.google.com/?hl=de

sign in with ur google account if you are not signed in already.

on the left it will say "Credentials" click on that

now it will show your Project for which an API was created. Click on ur project..  name

On the top it will say "regenerate key". i used the newly created key and it worked

hope this works for u 2
