### ISSUE TITLE
настройки карты

### ISSUE THREAD

**Issue by Yuk111** [mchristopher/PokemonGo-DesktopMap#697]
Как выставить настройки карты, которых нет на начальном экране с логином?
Я на пример до этого использовал -L ru -sd 1 , тут куда их писать?

**Comment by rickymiles22** [comment]
To change the map settings, you must log out (I believe).  

изменить настройки карты Вы должны выйти из системы.

**Comment by rickymiles22** [comment]
Try going to "Location Settings" then "Change scan location"

**Comment by Yuk111** [comment]
it will change the scanning location, but not recharge time between steps
and especially not to change location

**Comment by rickymiles22** [comment]
Oh.  You want to change the Scan Time? For example, faster or slower?  The game requires 10 seconds now.  But if you wish to change that, try:

%localappdata%\pokemon\app-0.2.1\resources\app\map\config

change config.ini.example to config.ini

Edit the line
#scan-delay:            # default 5

to

#scan-delay: 12            # default 5

Or change 12 to whatever time you wish to scan.  But know that if you reduce it less than 10 it may miss some pokemon

**Comment by rickymiles22** [comment]
Oops edited above comment, make sure to remove the # before the line in config.ini as that means comment. Any line after # will be ignored

**Comment by Yuk111** [comment]
This configuration file does not work
file as simply ignored

**Comment by Yuk111** [comment]
Oops... 1 moment

**Comment by Yuk111** [comment]
really works
I had seen the file and rules, but not rename

and how to deal with localization?

**Comment by rickymiles22** [comment]
Can you explain your next question again? Maybe type in Russian and I can try to translate it.  I don't understand what you mean by "how to deal with localization"?

**Comment by Yuk111** [comment]
before the names of Pokemon were Russian language with the help of key -L ru :)

and another question

get the configuration file is more important that you write on the home screen?

**Comment by Yuk111** [comment]
можно изменить шаг сканирование не перезапуская программу?

**Comment by rickymiles22** [comment]
I'm not sure which file takes priority, also unsure about language options.  But I don't think its possible to change the scan speed without restarting the game.   I'll make a post about the language option argument and see if it gets a response

**Comment by Yuk111** [comment]
big thanks
I close the question?
