### ISSUE TITLE
map setup

### ISSUE THREAD

**Issue by Yuk111** [mchristopher/PokemonGo-DesktopMap#698]
My English is bad
I use Google translator
Please tell me where to insert the card settings are not on your home screen
I used to use keys -L ru -sd 1
Where the config file?

**Comment by rickymiles22** [comment]
I think you mean "map settings" I speak a little Russian Карты is map (google translates it to card).  As I posted in your other thread, when logged in goto "Location Settings" and then "Change scan location" and enter the X,, Y coords
i.e.   55.771698, 37.517024 
for Moscow.

You can also click "Scan follows location" if you are mobile

**Comment by Yuk111** [comment]
please closed
