### ISSUE TITLE
Export google map of stops and gyms?

### ISSUE THREAD

**Issue by SpookyDaysAreHere** [mchristopher/PokemonGo-DesktopMap#699]
Anyway to get the map locations of all the stops and gyms out to a google map on a server? Not the pokemon of course as they will have despawned, but it'd be handy to set the map radius to a large number, put it in a town or area, then have a detailed map of where all the stops and gyms are (that I can hit from a web page at anytime, not necessarily this application running)

**Comment by jonnyjules** [comment]
I'd also like to do this. Is there a simple way to access the sql database?
