### ISSUE TITLE
No pokemon

### ISSUE THREAD

**Issue by sainar** [mchristopher/PokemonGo-DesktopMap#7]
On the map you cannot see any pokemon, what it can be connected?

**Comment by speedyswimmer1000** [comment]
Agreed, tried on Windows and Ubuntu, can't see pokemon.

**Comment by samuelgnoble** [comment]
Have you made sure to check the server status on a site like ispokemongodownornot.com?

Currently Pokemon Trainer Club login is experiencing latency. If the Pokemon Go servers or login are down, the app is not able to function.
![screen shot 2016-07-25 at 1 46 51 pm](https://cloud.githubusercontent.com/assets/13971571/17111786/19c412e6-5271-11e6-86c6-7e3feedc2286.png)
