### ISSUE TITLE
Pokemon go map

### ISSUE THREAD

**Issue by archonis83** [mchristopher/PokemonGo-DesktopMap#700]
I use to use pokemon go map master but this one dont seam to be as fast. am i doing something wrong?

**Comment by rickymiles22** [comment]
They changed the scan time from 5 sec to 10 sec server side.  So unless you use multiple accounts the scanning has to be at this speed

**Comment by silvablue2016** [comment]
Why will mine not load? says this page didnt load maps correctly, see javascript console for tech details. Im trying to login with google. Please someone help.
