### ISSUE TITLE
Multiple workers api question

### ISSUE THREAD

**Issue by wartortle87** [mchristopher/PokemonGo-DesktopMap#701]
Do you need a new google api for each ptc account you run, or can you use the same one for multiple ptc accounts running at the same time?

**Comment by topgunpilott** [comment]
I am able to run a single google API for two PG accounts setup through google with no problems.  I can't speak for certain in regards to doing this with a PTC account.

**Comment by Genek1968** [comment]
What is a PG account ? I thought PTC is the same as PG

**Comment by topgunpilott** [comment]
PTC (Pokemon Training Club) is of course one method of signing into the game but I sign-in using Google accounts. So when I say I can use a single API for two PG accounts I simply mean is I can use one API  to run multiple "Pokemon Go" game sign-ins through google gmail accounts.
