### ISSUE TITLE
Changing Languages & Passing Parameters through Windows Shortcut or Another Method?

### ISSUE THREAD

**Issue by rickymiles22** [mchristopher/PokemonGo-DesktopMap#702]
Is it possible to pass Parameter Arguments from Shortcuts to change languages?  A guy in here was asking about using -L ru  for Russian pokemon names to appear, said it was previously working (I think by adding the parameter in the shortcut.).

Does anyone know how to change language options with the new version?

**Comment by krummrey** [comment]
The language files are bundled in the original PokemonGoMap directory, should be fairly simple to add a language option to the first startup page. I'be tried
`    cmdLine.push('-L de');` in the main.js file. But that didn't do the trick. :(
