### ISSUE TITLE
mac crashes at map load

### ISSUE THREAD

**Issue by macduff79** [mchristopher/PokemonGo-DesktopMap#705]
It crashes when the map is loading. This was also the case in 0.1.7, but not 0.1.6. The log is:

8/7/16 1:58:50.588 PM Pokemon GO Live Map Helper[924]: <<<< VTVideoEncoderSelection >>>> VTSelectAndCreateVideoEncoderInstanceInternal: no video encoder found for 'avc1'
8/7/16 1:58:50.590 PM Pokemon GO Live Map Helper[924]: [13:58:50.590] VTSelectAndCreateVideoEncoderInstanceInternal signalled err=-12908 (err) (Video encoder not available) at /Library/Caches/com.apple.xbs/Sources/CoreMedia_frameworks/CoreMedia-1731.15.204/Sources/VideoToolbox/VTVideoEncoderSelection.c line 1308
8/7/16 1:58:50.590 PM Pokemon GO Live Map Helper[924]: [13:58:50.590] VTCompressionSessionCreate signalled err=-12908 (err) (Could not select and open encoder instance) at /Library/Caches/com.apple.xbs/Sources/CoreMedia_frameworks/CoreMedia-1731.15.204/Sources/VideoToolbox/VTCompressionSession.c line 1003
8/7/16 1:58:58.912 PM com.apple.xpc.launchd[1]: (com.electron.pokemon-go-live-map.348832[923]) Service exited due to signal: Segmentation fault: 11

**Comment by minim8** [comment]
+1

**Comment by 10tribu** [comment]
+1
