### ISSUE TITLE
[BUG] Map Will Not load - OSX

### ISSUE THREAD

**Issue by swimboy46163** [mchristopher/PokemonGo-DesktopMap#706]
<img width="797" alt="screen shot 2016-08-07 at 2 10 05 pm" src="https://cloud.githubusercontent.com/assets/1245042/17464263/d018df18-5ca8-11e6-9703-bcd866060c79.png">

It will not load the map it just stays here and never loads. Let me know if there is any more info you might need.

**Comment by QuadrupleDouble** [comment]
Have this trouble too. Windows 7 x64. Help please
![default](https://cloud.githubusercontent.com/assets/20892194/17464956/d1bc55f8-5cf2-11e6-9820-1e3f29acd249.jpg)
