### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by GutsMFR** [mchristopher/PokemonGo-DesktopMap#709]
New to alot of this, ive tried new map keys and accepted the TOS in client... map starts to load then crashes. Keeps repeating getsouthwest error. any advice would be appreciated
![javascript](https://cloud.githubusercontent.com/assets/20891380/17464459/4cf16ede-5cad-11e6-955a-b37a4b868396.jpg)

**Comment by silvablue2016** [comment]
Same problem here, not getting any help :(
