### ISSUE TITLE
Cannot call load URL

### ISSUE THREAD

**Issue by Pineyka** [mchristopher/PokemonGo-DesktopMap#71]
main.html:196
Error: Cannot call loadURL because the webContents is unavailable. The WebView must be attached to the DOM and the dom-ready event emitted before this method can be called 
Wait Screen. Not view map.

**Comment by Pineyka** [comment]
Windows 7 - work all ok 
Windows 10 - white screen..   What is wrong?

**Comment by Pineyka** [comment]
This is the problem with my Windows 10. On another Windows 10 program is operating normally.
Good job, guys. Respect!
Greetings from Poland

**Comment by lcddrm** [comment]
I get white screen when I don't start as Administrator. Tried that?
