### ISSUE TITLE
Lure Notification Bug

### ISSUE THREAD

**Issue by JoeyFarrell** [mchristopher/PokemonGo-DesktopMap#716]
When a Pokemon is lured to a Pokestop which is outside your scanned location, and you have the app set to notify you when it appears, the notifications will repeat themselves over and over again. 

For example, the notification "A Wild Slowpoke appeared!" keeps coming up whenever I dismiss it. 

Just thought I'd let you know of this.

**Comment by geeman1960** [comment]
I am having this problem too.

Specific symptoms - 

- At a lured Pokestop, one of the types of Pokemon I have listed in notification will spawn
- I will receive a notification, which can be disabled normally by clicking on the Pokemon on the map 
- The Pokemon will disappear from the map when it's time expires (which always seems to be <3 min)
- I will receive notifications about the (now gone from the map) Pokemon every time a scan occurs (default 5 sec) with no way to cancel the notifications.  These continue for several minutes, alerting every 5 sec.

I have not confirmed if the Pokemon is still really at the Pokestop or if it's a false alert after it disappears from the map.
