### ISSUE TITLE
oops something went wrong

### ISSUE THREAD

**Issue by slaugbr1** [mchristopher/PokemonGo-DesktopMap#717]
the page didn't load google maps correctly. see java script console for details..........

every time i log in. please halp looked for fixes

**Comment by chintqm03** [comment]
Maybe API isn't correct? I had that issue before just generate a new one

**Comment by cybernimf** [comment]
Same problem, i did generate new api, unless i typed in wrong. It wont paste into the map. Still getting this error?

**Comment by chintqm03** [comment]
Do you have google maps geocoding Api and google maps JavaScript Api enabled

**Comment by cybernimf** [comment]
I do think i do..looks like

**Comment by notthesharpest** [comment]
Same problem for me as well

**Comment by EternisRequiem** [comment]
Sigh.  Me too.  I dunno if this helps, but I'm getting this:
 Uncaught TypeError: Cannot read property 'getSouthWest' of undefined
