### ISSUE TITLE
Map stops working after an hour. Relogging fixes.

### ISSUE THREAD

**Issue by Smileynator** [mchristopher/PokemonGo-DesktopMap#72]
The map sometimes stops working after an hour or so of use. Kind of troublesome when the PC back home is scanning for me, and i am out catching them. Since i would have to teamviewer in on a shitty connection to hit refresh.

**Comment by Smileynator** [comment]
Also, i suspect this is due to some sort of timeout/countermeasure of the developer. They receive too many requests in a short time period and cut me off? Not sure.

**Comment by jnovack** [comment]
I can concur, it's exactly an hour.  Is this because I do not move, do not try to catch anything?

I think once we have the phone browser pass location back to the main application it may not be a problem since we'll be moving on the phone.

**Comment by lcddrm** [comment]
You can refresh the map. At the top left under "Tools" there is a menu button for it. The Keyboard shortcut ist CTRL-r. Unfortunately I can't get it to automatically refresh with Autoit or pyautogui. The map doesn't accept any mouse or keyboard events from those two programs, I wonder why that is...

**Comment by fenixasin** [comment]
This needs to be looked into, killed my session last night, I only caught 1 rare pokemon. Well worth it tho, never would have found it.

the next 4 hours were walking grind to reach level 20.....  103K dust, and have not evolved anything using candies or powerup since level 15... so I should be able to just to 21-1/4 easily with an egg or two.

**Comment by fenixasin** [comment]
This is tied to Issue #38, they were worded differently but in essence the same issue.

**Comment by robertftw** [comment]
An ugly workaround:

main.html
`	//Force logout every 45min
	window.setTimeout(function(){
		console.log('Logging out (force refresh)');
		logout();
	}, 27000);`

and in login.html inside document.ready (at the end)
`doPTCLogin();`

**Comment by HuXu77** [comment]
@robertftw does that work? Does it maintain the same mobile URL?

**Comment by fenixasin** [comment]
this is being worked on or already has in a new commit.

This may be consolidated and closed as resolved shortly.

**Comment by robertftw** [comment]
@HuXu77 It does work but new mobile url and you have to change the code to auto toggle mobile in document.ready
