### ISSUE TITLE
Suggestion for Multi Account Update

### ISSUE THREAD

**Issue by ejd59005** [mchristopher/PokemonGo-DesktopMap#720]
Since the scans are now down to 10-15 seconds, it's best if we start using multi accounts.

Was wondering if you could add a button on the login page that says "Account 1, Account 2 etc" that we can click and have it auto populate our saved account credentials. 

Right now once I open one map and login, it saves those credentials. Then when I want to open my second map, I have to remove the first username and password, and enter in my second account, and so one. Just gets tedious having to type in each account every time and would be easier if we could just click on "Account 2" button and have it populate those fields. 

Just an idea. 

Thanks for everything you do.

**Comment by davidluong** [comment]
I've been wanting to do the same for a while and I am looking for a way to make it work. Currently, people are saying that it is possible to modify the config file to include multiple accounts but I'm just starting to try this myself.

**Comment by zaqrwe** [comment]
You can search in more accounts? Just launched second account and app doesnt't scan that one :(

**Comment by Barabicus** [comment]
I would love to see this feature. I tried using the other repository that this is app is derived from and started it via command line specifying multi accounts which would work on the other maps (the one that has been shut down) I'm getting an error when trying to use multiple threads though unfortunately so I don't know if it needs to be patched or if I'm doing something wrong. Unfortunately I have a very limited knowledge of python.

**Comment by cykou** [comment]
Hello, I wanted to ask I cannot get another pokemon catcher account because it says they are "busy". How can I search 2 different locations if I only have one account ? thank you

**Comment by mg6101** [comment]
@zaqrwe What login method are you using? Is it a throw away account? If so, have you logged into it on an old phone/tablet to complete the tutorial? Reports say that the API calls are dropped if the account hasn't completed the tutorial.

@cykou You cannot search 2 locations with 1 account. You must have 1 account for each location you want to search.

**Comment by cykou** [comment]
Well I tried getting another PTC account but  the Pokemon site won't let me
. Is there a workaround for this ? thank you for help.

**Comment by mg6101** [comment]
@cykou There is not a work around. You will have to wait for the site to come back online. Usually takes a few hours.

**Comment by cykou** [comment]
dang , the site seems permanently screwed for account creation. Before Niantic did the API mess up  you could use the same account to get different scans does anyone know why?

**Comment by mg6101** [comment]
It's only temporary. Niantic released the game in 15 new countries over the weekend so the site is getting hit pretty bad. As for why you can't use 1 account, niantic made some very significant changes in the way it validates API calls. Everything from your location, orientation, and even magnetic field of the earth, among others, all get calculated to encrypt your request for map data. In addition, requests from the same account, in 2 different locations is an immediate red flag. Your map will display no Pokémon at all and could result in a ban of the account. There haven't been massive ban waves yet but they have said they are coming once the server issues are all settled. Be careful. Don't use your real account for maps and definitely don't use services or apps to spoof your gps data.

**Comment by tkrause** [comment]
Because of the API changes you can only make 1 API call every 10 seconds for scanning purpose anyways. This is due to the rate limiting. The way to get around this is multiple accounts ~10 ish throw away accounts on multiple threads to update an SQLite or MySQL backend. I'm working on something similar and will submit a pull request to merge the change into the master branch when done.

**Comment by torantal** [comment]
When I startup "Pokemon GO Live Map.exe" a second time **with a different PTC account**, I seem to have two working instances but there is only one valid marker. If I target another area on the second instance, the marker on the first instance moves as well. How should I do this?
