### ISSUE TITLE
Error NPM Start on Digital Ocean VM

### ISSUE THREAD

**Issue by chintqm03** [mchristopher/PokemonGo-DesktopMap#721]
I followed the steps 
If you are pulling from git, you must first instruct git to fetch the included submodules. Run this after cloning:

git submodule update --init --recursive
Development is currently done on OS X and tested on Windows 10. To get started, you'll need to install NodeJS, Python 2.7, pip, and virtualenv. With Homebrew, I use:

brew install python node
pip install virtualenv
npm install
To run the project, run:

npm start

After I get an error 
> electron main.js

sh: 1: electron: not found

npm ERR! Linux 4.4.0-31-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! pokemon-go-map@0.2.1 start: `electron main.js`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the pokemon-go-map@0.2.1 start script 'electron main.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the pokemon-go-map package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     electron main.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs pokemon-go-map
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls pokemon-go-map
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/lmao/as/PokemonGo-DesktopMap/npm-debug.log

**NPM LOG**

0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'start' ]
2 info using npm@3.5.2
3 info using node@v4.2.6
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle pokemon-go-map@0.2.1~prestart: pokemon-go-map@0.2.1
6 silly lifecycle pokemon-go-map@0.2.1~prestart: no script for prestart, contin$
7 info lifecycle pokemon-go-map@0.2.1~start: pokemon-go-map@0.2.1
8 verbose lifecycle pokemon-go-map@0.2.1~start: unsafe-perm in lifecycle true
9 verbose lifecycle pokemon-go-map@0.2.1~start: PATH: /usr/share/npm/bin/node-g$
10 verbose lifecycle pokemon-go-map@0.2.1~start: CWD: /home/lmao/as/PokemonGo-D$
11 silly lifecycle pokemon-go-map@0.2.1~start: Args: [ '-c', 'electron main.js'$
12 info lifecycle pokemon-go-map@0.2.1~start: Failed to exec start script
13 verbose stack Error: pokemon-go-map@0.2.1 start: `electron main.js`
13 verbose stack spawn ENOENT
13 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/lib/utils/spaw$
13 verbose stack     at emitTwo (events.js:87:13)
13 verbose stack     at ChildProcess.emit (events.js:172:7)
13 verbose stack     at maybeClose (internal/child_process.js:821:16)

**Comment by chintqm03** [comment]
Also please don't hate on me i'm new to linux.

**Comment by MakkaHareesh** [comment]
i also get same problem so please solve
