### ISSUE TITLE
Not scanning anymore?

### ISSUE THREAD

**Issue by xzeikx** [mchristopher/PokemonGo-DesktopMap#722]
Did Niantic already squash it? It doesnt seem to scan anymore

**Comment by cykou** [comment]
same I just downloaded it

**Comment by drippybutt** [comment]
Still works for me

**Comment by drippybutt** [comment]
Parasect and hypno just popped up for me so its def still working

**Comment by aleleiva16** [comment]
Is working fine for me

**Comment by DaRealDfid** [comment]
u have to go tools and refresh or move the Cursor to set a new scanning point.

**Comment by xzeikx** [comment]
yea that doesnt do me much good when im out though :/

**Comment by aleleiva16** [comment]
It would be cool to receive those notifications even if I am not sharing
the link via Ngrok. Just when a Pokemon listed on the notifications list
appear, receive a notification via Pushbullet, Twitter, Telegram or
Whatsapp.

*Alejandro José Leiva Valverde*
Ingeniero en Producción Industrial
Celular: 8308-9843


2016-08-07 18:34 GMT-06:00 xzeikx <notifications@github.com>:
