### ISSUE TITLE
"Waiting" issue - Cant Scan

### ISSUE THREAD

**Issue by poke2ndacc** [mchristopher/PokemonGo-DesktopMap#723]
The button at the top is constantly waiting. 
Cant search.

Anyone else??

**Comment by ejd59005** [comment]
Thatso usually what happens when your on a vps that has a banned ip

**Comment by ejd59005** [comment]
Thats*. Sorry typo in phone

**Comment by poke2ndacc** [comment]
hi do u know how  i can fix it or?

**Comment by ejd59005** [comment]
Are you on a vps?

**Comment by poke2ndacc** [comment]
no im on a home network

**Comment by Rengor** [comment]
Make sure the account has accepted the TOS in-game, otherwise you'll get that issue.

**Comment by mg6101** [comment]
Rengor is right. Reports say that the API calls are dropped if the account hasn't completed the tutorial.

**Comment by monhustla** [comment]
Dumb question, but do you have to actually log into the game with your account to complete tutorial?

**Comment by mg6101** [comment]
Yup. You have to log in with that account (preferably on a phone/tablet that isn't connected to your main account) and complete the tutorial by catching your first Pokemon.

**Comment by monhustla** [comment]
Doing the above works, all set. Good to go.

**Comment by pcecere** [comment]
@poke2ndacc please close this issue. there is a solution already.
