### ISSUE TITLE
No Pokemon Apearing on map

### ISSUE THREAD

**Issue by jorgen3** [mchristopher/PokemonGo-DesktopMap#724]
I'm using the mac file and I followed the instructions and the map opend just fine, but no gyms pokemon or pokestops appeared. Any help? 

> http://jorgenholbrook.imgur.com/all/?third_party=1

**Comment by tkrause** [comment]
Got an error log? Also try enabling show scanned locations...should give you an idea if it is actually scanning or if it is erroring out somewhere.
