### ISSUE TITLE
javascript error from remote server error 500 internal server error - see attachment

### ISSUE THREAD

**Issue by redbone75** [mchristopher/PokemonGo-DesktopMap#725]
javascript error from remote server error 500 internal server error - see attachment

thoughts?

![capture](https://cloud.githubusercontent.com/assets/20893831/17465932/9bd7215e-5cc8-11e6-8ccf-7fd99b9a8508.PNG)

**Comment by thebigsmileXD** [comment]
Had this one yesterday and #707
