### ISSUE TITLE
download canceled or forbidden error

### ISSUE THREAD

**Issue by gigi82** [mchristopher/PokemonGo-DesktopMap#726]
every time i try to download it will cancel itself or say forbidden and progress will not move

**Comment by Regulator69** [comment]
change your firewall settings, theres an option in your setting to allow even dangerous files to download (forget exact wording) then it will give you option to "run anyways" when it says forbidden.. thats what i had to do to download custom zombie maps for world at war anyways cuz it would forbid everything
