### ISSUE TITLE
Notification

### ISSUE THREAD

**Issue by wbgneto** [mchristopher/PokemonGo-DesktopMap#728]
It's bad to set one by one on the notification list.

Please allow notification by rarity.

**Comment by rsteagall** [comment]
It's configurable so you could do that.  Select the one's you want to get notifications on.   Then you can also hide the junk too.

**Comment by walterneto** [comment]
I know, just suggesting a new feature. ( Not sure if I should use 'Issues' for that, but there are no labels here so.. )

I don't want to select them all one by one, got it? haha
Probably everyone will want any pokemon above 'rare'

**Comment by NickHab** [comment]
I just set all of mine up then it didnt save them
