### ISSUE TITLE
Map doesnt work for me, so looked at skiplagged,, there map showed all 4 unrelease pokemon.

### ISSUE THREAD

**Issue by silvablue2016** [mchristopher/PokemonGo-DesktopMap#731]
All 4 on the map, but nothing poped up. 

Any chane of help getting desktop map working?

**Comment by mg6101** [comment]
What login method are you using? Is it a throw away account? If so, have you logged into it on an old phone/tablet to complete the tutorial? Reports say that the API calls are dropped if the account hasn't completed the tutorial.

**Comment by alangerow** [comment]
> All 4 on the map, but nothing poped up.

That's because Skiplagged is a crowdsourced tracker, and people are filthy liars.

**Comment by silvablue2016** [comment]
Not logging in on phone, im trying to open desktop map. Worked on old version but not this one.
