### ISSUE TITLE
JavaScript Error?

### ISSUE THREAD

**Issue by ianedups** [mchristopher/PokemonGo-DesktopMap#732]
When I start the app I get a JavaScript error and the map only shows a couple of pokestops and no Pokemon at all. Since I'm new to this maybe I installed it wrong. What files are needed to be downloaded for Windows? Is it only the Windows.exe one?

**Comment by pcecere** [comment]
PokemonGoMap-Win.exe should be the one you need to download, and that will install the application, directories, etc.

**Comment by thebigsmileXD** [comment]
#707
