### ISSUE TITLE
Javascript error

### ISSUE THREAD

**Issue by HeyLookPonies** [mchristopher/PokemonGo-DesktopMap#734]
Even after updating and many APIs, I'm still getting a Javascript error (seems to surround: MAP: Uncaught TypeError: Cannot read property 'getSouthWest' of undefined).

**Comment by thebigsmileXD** [comment]
#707

**Comment by deathx420** [comment]
yh, i get the same error message. "MAP: Uncaught TypeError: Cannot read property 'getSouthWest' of undefined". ive searched, & it could be a typo error in the script.
