### ISSUE TITLE
Suggestion: configurable/correction to result radius

### ISSUE THREAD

**Issue by davidhouweling** [mchristopher/PokemonGo-DesktopMap#736]
I have the 'Scanned Locations' enabled, and i noticed that the radius of each individual scan is about 70m (which i'm guessing is based what was being reported by news sites). However, from my phone (and with what i know about spawn spots in my area, and the Pokemon Go Map showing me), the actual radius of the data seems a lot closer to 170m (potentially even 175m).

If this could be configurable, it could also allow for a less global radius (i use a radius of '4' so that it gets back to my location scan quicker), but also be able to cover a wider area with less scans.

I suggest it to be configurable, as maybe others may not be as confident as I am in that it could be a 170m radius scan, so at least if others don't believe me, they can tweak it themselves from the UI.

It could potentially be that there is a limit to results returned as well. For example, in my area there are very few spawn spots, so the game gets results back for a larger radius, but in more dense locations where spawns are a lot closer to each other, then you may need a smaller radius.

**Comment by TomanPCM** [comment]
scroll down on login page

**Comment by pill0ws** [comment]
I believe he means the actual radius of the individual scan query, not the radius of the spiral built by the queries. 70m would be the diameter of the update area, not the scan pattern
