### ISSUE TITLE
[Error] Map displays nothing

### ISSUE THREAD

**Issue by avielc** [mchristopher/PokemonGo-DesktopMap#737]
Hi all, using the latest version 0.2.1 Windows 10 Pro 64bit.
registered a few api keys on google and enabled all api required. (geocoding, etc...)
the only version that actually worked for me was a 0.0.7 or something like that (one of those that came in a zip file instead of an installable.exe), 
 - All the versions that followed showed gyms and pokestops, not pokemons <<- if that's any indication of something
currently the console prints out: 

> 2016-08-08 08:25:33,286 [ search_worker_0][      auth_ptc][    INFO] PTC User Login successful.
> 2016-08-08 08:25:33,288 [ search_worker_0][      auth_ptc][    INFO] Request PTC Access Token...
> 
> main.html:168 2016-08-08 08:25:33,486 [ search_worker_0][      auth_ptc][    INFO] PTC Access Token successfully retrieved.
> 
> main.html:168 2016-08-08 08:25:33,496 [ search_worker_0][        pgoapi][    INFO] Creating a new direct request...
> 2016-08-08 08:25:33,496 [ search_worker_0][        pgoapi][    INFO] Adding 'GET_MAP_OBJECTS' to RPC request including arguments
> 
> main.html:168 2016-08-08 08:25:33,496 [ search_worker_0][        pgoapi][    INFO] Execution of RPC
> 
> main.html:168 2016-08-08 08:25:34,109 [ search_worker_0][        pgoapi][    INFO] Cleanup of request!
> 
> main.html:168 2016-08-08 08:25:34,111 [ search_worker_0][        models][    INFO] Upserted 0 pokemon, 0 pokestops, and 0 gyms

I've tried changing between fake to level 8 character to level 22, in all cases nothing changes.

if anyone know any idea why, i'd be most happy to hear.

Also, on a different laptop with win10 pro 64 bit it worked. so i put my head around to figure what am i missing here.
@mchristopher 
@anyone who knows

**Comment by avielc** [comment]
![image](https://cloud.githubusercontent.com/assets/13572969/17470160/c2df478e-5d42-11e6-91f1-969c9764b9d2.png)
Also, this error happens when i log out and log in again if it means anything

**Comment by ianedups** [comment]
Same problem also on Windows 10 as well

**Comment by tkrause** [comment]
@avielc You issue looks like the application is already running in the background and python cannot bind to the port needed to run the app. Try killing python in task manager or restart your PC.

**Comment by avielc** [comment]
@tkrause hey man, thanks for the reply,
that's the weird part the computer is after a restart, so python shouldn't be running anywhere.
I can only assume that when you do a log out and log back in, if python doesn't close the process behind it will remain running.

Aside of that. the main issue persists as i can't see nothing on the map. (it just won't update anything)
is there a way to find a more detailed log? or has anyone ran across the issue mentioned on the first post?

**Comment by dannyphung** [comment]
Same on Linux
```
Python: 2016-08-08 13:33:23,708 [    MainThread][     runserver] [   INFO] Parsed location is: 10.8142/106.6438/0.0000 (lat/lng/alt)
2016-08-08 13:33:23,711 [    MainThread][        models] [   INFO] Connecting to local SQLLite database.
2016-08-08 13:33:23,713 [ search_thread][        search] [   INFO] Search loop 0 starting
2016-08-08 13:33:23,713 [ search_thread][        search] [   INFO] Attempting login to Pokemon Go.
2016-08-08 13:33:23,714 [ search_thread][   auth_google] [   INFO] Google Login successful.

Python server started!
Got open express port: 8001
Express listening on port 8001
Express server started!
Python: 2016-08-08 13:33:24,214 [ search_thread][        search] [   INFO] Login to Pokemon Go successful.

Python: 2016-08-08 13:33:24,669 [search_thread-0][        models] [   INFO] Upserted 0 pokemon, 0 pokestops, and 0 gyms

Python: 2016-08-08 13:33:30,285 [search_thread-0][        models] [   INFO] Upserted 0 pokemon, 0 pokestops, and 0 gyms

Python: 2016-08-08 13:33:36,003 [search_thread-0][        models] [   INFO] Upserted 0 pokemon, 0 pokestops, and 0 gyms

Python: 2016-08-08 13:33:41,673 [search_thread-0][        models] [   INFO] Upserted 0 pokemon, 0 pokestops, and 0 gyms

Python: 2016-08-08 13:33:47,160 [search_thread-0][        models] [   INFO] Upserted 0 pokemon, 0 pokestops, and 0 gyms

Python: 2016-08-08 13:33:52,761 [search_thread-0][        models] [   INFO] Upserted 0 pokemon, 0 pokestops, and 0 gyms

```

**Comment by TrigpointingUK** [comment]
Same here.  Console log contains the following (my google key works fine on previous versions of the code).

    server up: http://localhost:8003
    Error getting location, trying second provider PositionError
    Found location [xxx.xxxx,xxx.xxxx] by ipinfo.io
    [ search_worker_0][        search][    INFO] Search step 3 beginning (queue size is 124)
    [ search_worker_0][        pgoapi][    INFO] Creating a new direct request...
    [ search_worker_0][        pgoapi][    INFO] Adding 'GET_MAP_OBJECTS' to RPC request including arguments
    [ search_worker_0][        pgoapi][    INFO] Execution of RPC
    [ search_worker_0][        pgoapi][    INFO] Cleanup of request!
    [ search_worker_0][        models][    INFO] Upserted 0 pokemon, 0 pokestops, and 0 gyms

    MAP: Google Maps API error: InvalidKeyMapError https://developers.google.com/maps/documentation/javascript/error-messages#invalid-key-map-error
    MAP: Google Maps API warning: InvalidKey https://developers.google.com/maps/documentation/javascript/error-messages#invalid-key
    MAP: Uncaught TypeError: Cannot read property 'getSouthWest' of undefined

**Comment by avielc** [comment]
How do you get an extra information?
I'm trying to figure out how to get an extra log information

**Comment by Sigmarion** [comment]
Same problem - need a solution!

**Comment by IBentMyWookie** [comment]
I had the same problem running it on Windows 10.  I had it scanning, but no Pokemon showing up.  I have it running on a separate Win 7 computer just fine.  I changed the windows 10 PG Live Map compatibility in properties to windows 7 and it started working.  I had to restart the program twice, but it finally started working.

**Comment by avielc** [comment]
I was thinking the same thing. but for some reason that didn't do anything.
I'll try that again.

Have you made a different shortcut to the app?

**Comment by IBentMyWookie** [comment]
Forget what I said.  It works for a bit and then won't pick them up anymore.

**Comment by IBentMyWookie** [comment]
It is strange, it will work for a bit, then quit working and then start seeing the Pokemon again.

**Comment by IBentMyWookie** [comment]
I closed it, ran it as Windows 7 and ran as Admin and it is currently working.  Hopefully the up time it permanent.

**Comment by avielc** [comment]
I've tried what you said, it didn't work for me at all. i tried Win7+admin on the shortcut on the desktop, on the actual exe file inside the 0.2.1app folder. didn't work
my next trial will be python script. to try and run it the old fashioned way

**Comment by dannyphung** [comment]
I Updated latest version of map repository into folder `resoures/app/map` and this work fine again. It take about a minutes to get pokemon on to the map.

**Comment by avielc** [comment]
@dannyphung where did you get the latest version of map repo?
developer version?

**Comment by regzilla** [comment]
Same situation, i'm stuck too. I can't figured out what's happened and how to solve it...

**Comment by dannyphung** [comment]
@avielc : Yep, I used developer version.

**Comment by avielc** [comment]
I'll give it a whirl then, thanks @dannyphung

**Comment by avielc** [comment]
Closing issue, new update has solved everything (it just works!)
