### ISSUE TITLE
Time Seen is being recorded wrong

### ISSUE THREAD

**Issue by Luke-Avnaim** [mchristopher/PokemonGo-DesktopMap#738]
A timestamp recorded just in front of me shows a Tauros appearing about 15 minutes into the future. I think the time is being recorded wrong. Maybe it is seeing into the future?

**Comment by Luke-Avnaim** [comment]
Unless it records the time the pokemon disappears? Solved my own issue.

**Comment by thebigsmileXD** [comment]
Actually could refer something to that. The wrong timezone is chosen, i get GMT instead of GMT +1
