### ISSUE TITLE
"Loading, please wait..."

### ISSUE THREAD

**Issue by jayappletree** [mchristopher/PokemonGo-DesktopMap#739]
Why after I login, it always shows "Loading, please wait..." 

At the beginning I thought DesktopMap was blocked. But after you guys released an update and some of you still using it, I found the same problem of mine doesn't go away...

**Comment by Mirx** [comment]
Firewall, proxy, blocked IP range, etc.

**Comment by jayappletree** [comment]
@Mirx Why am I blocked? And what should I to free myself? Change a new account? 

I am just a normal pokemon player. These stuff are too complicated to me... but sounds interesting.

**Comment by Mirx** [comment]
What login type are you using for your map account? Google or PTC. The added some security steps in there, which you might first need to perform before your account will be operational. 

https://github.com/mchristopher/PokemonGo-DesktopMap/issues/753#issuecomment-238297269

**Comment by jayappletree** [comment]
@Mirx Google account is what I am using. And it is also my secondary pokemon go account. It doesn't matter to if it is softbanned.

**Comment by jayappletree** [comment]
@Mirx I tried on another macbook. And it is working well. So it was not the problem with account, but with my computer... Don't understand what is wrong with my macbook???

**Comment by diophantus7** [comment]
Same problem here. I started from the terminal and there I get an error about the config
