### ISSUE TITLE
Can't Log in, code 6

### ISSUE THREAD

**Issue by xphalz** [mchristopher/PokemonGo-DesktopMap#74]
When it gets to the login screen the only thing that comes up is the texts on a white screen and when I try to log into my trainer club account it says "Something went wrong and we couldn't log you in. Please try again. Code 6." Help :(

**Comment by fenixasin** [comment]
we need more info  what platform   win/linux/mac what version of the OS.

what install steps did you perform.

so that this error can be repeated. include pics if possible

**Comment by vishnudmindfreak** [comment]
Please check the internet connection once, if you are running under a proxy server, disable proxy and try again. I have faced the same issue, but now I am able to login  to the application.

**Comment by xphalz** [comment]
i unzipped the files from the newest version and ran the program and the error came up as i logged in.
im using windows 8.1 right now. my internet connection appears to be fine right now and im not using a proxy server
![notwork](https://cloud.githubusercontent.com/assets/20578204/17023064/469e6f3c-4f06-11e6-82a3-2e26c083201c.png)
