### ISSUE TITLE
Suggestion: 

### ISSUE THREAD

**Issue by bmeucci** [mchristopher/PokemonGo-DesktopMap#741]
It seems like you've slowed the scan rate for compatibility reasons but it seems that if you had three different accounts scanning simultaneously it could accomplish the same thing.

**Comment by bmeucci** [comment]
It seems like you've slowed the scan rate for compatibility reasons but it seems that if you had three different accounts scanning simultaneously it could accomplish the same thing.

**Comment by krummrey** [comment]
The original PokemonGo-Map by Aaaaaaa has been shut down. Lots of people have picked up the work and it looks like https://github.com/PokemonGoMap/PokemonGo-Map is the busiest. They have a feature that can do just that. Maybe using that as the base for this app would make sense, as they are working a lot on their codebase.
