### ISSUE TITLE
[SOLVED] Loading please wait problem with console pic 

### ISSUE THREAD

**Issue by tufuwood** [mchristopher/PokemonGo-DesktopMap#742]
After I login with google account, I got this scene. 
The F12 console says this.

![default](https://cloud.githubusercontent.com/assets/13704317/17474841/a566d170-5d8a-11e6-8b19-9002550ee019.png)

I'm sure the API are right and enabled. And the TOS of this account is done.
Just don't know why peewee error and error getting location......
Can Somebody help me, plz....

**Comment by DanielKokorin** [comment]
I have this problem too,pls help

**Comment by tufuwood** [comment]
I solve this!!
I figure out that my User names is not english, that is XXXX in the path C:/Users/XXXX  not english.
This situation will result in some problem.
Because modifying it to english word is troublesome and risky,  I create a new HOST users (DO NOT CONNECT TO MICROSOFT) with english word instead, and the live map program works.
