### ISSUE TITLE
Failing to npm start

### ISSUE THREAD

**Issue by inakigloo** [mchristopher/PokemonGo-DesktopMap#744]
It gives me this error:  electron main.js

**Comment by chintqm03** [comment]
same

**Comment by aragacalledpat** [comment]
Me too.  Running on linux mint 18.

**Comment by pincy** [comment]
The problem in earlier versions was, the postinsall script tried to install stuff as root and the main.js was starting simply 'python' and not the exact 'python2'...
So after fixing this points i had it working.
Im running gentoo here and can confirm, currently (v0.2.1) there is something broken if you check it out from the git. Starting the Prepackaged Lin64 works currently
