### ISSUE TITLE
[Suggestion] - Poke Logging feature

### ISSUE THREAD

**Issue by fenixasin** [mchristopher/PokemonGo-DesktopMap#75]
Would be great to have a logging feature that writes to a txt file the poke info (#/name/Lat/Long TIMESTAMP).

Basically to let it run, and then we can later review the txt, say we let it run for a few hrs to analyse spawns.

txt file could be read in a viewer at a later revision of app , poke on map with #of occurances and timestamps.

just a thought

**Comment by Manonster** [comment]
Great idea!!!

**Comment by andrewda** [comment]
Might be easier to save them to a local MongoDB database, and allow exporting that database or viewing the heatmap.

**Comment by fenixasin** [comment]
I stumbled upon this bit of a project by another redditor.

Based on some of your code, it could be used???

https://github.com/modrzew/pokeminer

**Comment by fenixasin** [comment]
JUST FOUND THIS, based off a poke-map version.

This may be the easiest to implement. please please please

https://www.reddit.com/r/pokemongodev/comments/4tu584/some_spawn_location_research/d5kpohh

https://github.com/Samuirai/PokemonGo-Map

**Comment by CalyPhornia** [comment]
Great idea! I want it :)
