### ISSUE TITLE
Cannot load map 

### ISSUE THREAD

**Issue by cybernimf** [mchristopher/PokemonGo-DesktopMap#752]
Here is what i get when i try to open. I have done 3 new api keys, old one worked just fine before. Have checked that google geocoding and javascript api is active. Is there anything else i can do? I am on Windows 10 also.
![captures](https://cloud.githubusercontent.com/assets/20893208/17487265/b6ab0dc4-5d59-11e6-9fa5-0d92771582eb.JPG)

**Comment by NT747** [comment]
refresh your API. had the same problem.

**Comment by cybernimf** [comment]
excuse me as im taking chemo, some times things dont work right upstairs.
Refresh api? i made new ones, that isnt same?

**Comment by NT747** [comment]
i did a new one, but that didnt work for some inexpicable reason.

try this:

go on: https://console.developers.google.com/?hl=de

sign in with ur google account for which u made the api, if you are not signed in already.

on the left it will say "Credentials" click on that

now it will show your Project for which an API was created. Click on ur project name

On the top it will say "regenerate key". i used the newly created key and it worked

**Comment by Trainnnnn** [comment]
Make sure you have Javascript enabled on your API key.
