### ISSUE TITLE
Pokemon not showing

### ISSUE THREAD

**Issue by nicktan147** [mchristopher/PokemonGo-DesktopMap#753]
I have done all the required steps but the pokemon doesn't come out. I checked the console seems like step 1 map search seems failed. Here is the screenshot.

![screenshot_1](https://cloud.githubusercontent.com/assets/7764638/17487913/8a9b9ae4-5dc9-11e6-9a92-13c347c3c50f.png)

**Comment by mg6101** [comment]
Are you using a brand new secondary login? Have you completed the tutorial by catching your first Pokemon with that account?

**Comment by drippybutt** [comment]
Yea you have to catch you're first pokemon and get through all the dialog and choose a name and click on let's go. Then lots of them show up. :D

**Comment by iPaulis** [comment]
I have not done any of that and my map works. I just created a PTC account from their website, confirmed email and that's all. I didn't even login once in PokemonGo.

**Comment by mg6101** [comment]
When did you create it? Before the API changes or within the last 30 minutes. There are reports that both of those scenarios will still provide valid map data but after an undisclosed amount of time, the map will no longer populate. Several thousand people have confirmed the need to accept the TOS on the new PTC account in game fore their API calls to work properly.

**Comment by iPaulis** [comment]
I created my PTC account the same day the map stopped working because I wanted to make sure it was not a problem with my google account login. Later I read about the API changes.

**Comment by avielc** [comment]
Add a reference to #737
