### ISSUE TITLE
Login again from same window

### ISSUE THREAD

**Issue by hanpal** [mchristopher/PokemonGo-DesktopMap#755]
It would be great if was possible to login again after 30 minutes without having to leave the main window, also from the mobile connection. Add a "reconnect" button? Or, have an option for an automatic re-login using saved login information.

Have tried using a PTC account but this doesn't work for me.

**Comment by Mirx** [comment]
No, as Googe login needs human interaction to accept the terms, it will time-out.

As for PTC
https://github.com/mchristopher/PokemonGo-DesktopMap/issues/753#issuecomment-238297269

**Comment by hanpal** [comment]
Got PTC to work, after passing the training procedure using the Pokémon Go app.
