### ISSUE TITLE
Map Interferes with Pokemon GO App!!!

### ISSUE THREAD

**Issue by JDClough** [mchristopher/PokemonGo-DesktopMap#756]
I have tested a couple of times having both the map and the app on my phone running at the same time, and whenever I do so no pokemon want to load on my phone. But the moment I close the map and restart the app, everything is fine.

**Comment by Stevendylan01** [comment]
Are you using the same account for both the map and your pokémon go account? If so make sure to use two different accounts as to avoid this problem and the chance of getting banned

**Comment by JDClough** [comment]
@Stevendylan01 Thank you very much for the help, and I did end up making a second account one for the map and one for my phone.

**Comment by movak93** [comment]
@Stevendylan01 How do I login on the electron desktop map using my Pokemon go account on the mobile?

**Comment by JDClough** [comment]
@movak93 When you first launch the pokemon GO map from you computer before you login scroll down to the bottom and toggle the server mode. Then when the map loads, click the blue "Mobile" button and turn it on. Then from there I think it just loads what your computer scans (I haven't used It that much, but when I used it I had some problems with it.)

**Comment by MrAwesomers** [comment]
Use a different account for scanning, not the one you play the actual game with. You don't want your main account banned, if they would ever ban for scanning.
