### ISSUE TITLE
More information saved for Gyms and Pokestops

### ISSUE THREAD

**Issue by rourke** [mchristopher/PokemonGo-DesktopMap#759]
Is it possible to store more information in the database for Gyms and Pokestops? I'd like to have the name and the picture with it.

**Comment by Xcelled** [comment]
I believe this is something that needs to be implemented on the backend map repo: https://github.com/PokemonGoMap/PokemonGo-Map/issues

**Comment by rourke** [comment]
Ah you're probably right at that one. Didn't notice the separate back-end. Apologies.

**Comment by Xcelled** [comment]
It's tripped me up a lot, too. Further complicating it is mchristopher forked the map repo and has implemented some things himself.
