### ISSUE TITLE
Other account doens work

### ISSUE THREAD

**Issue by Qurre** [mchristopher/PokemonGo-DesktopMap#760]
Hi!

One of my PTC accounts works great on my PC. But I wanna have 2 sessions up so I got 2 accounts. But 1 of them doesnt work, it just says "Waiting" on the top button that usually says "Opertional". Any ideas?

**Comment by agita88** [comment]
you need to login in on the account on pokemongo and do the tutorial and it should work

**Comment by Qurre** [comment]
thank you, that did work! 

do u know how it affects if u have 2 maps open at the same computer? 

and also, where is all data stored? I would like to be able to clear map from pokemons and the scanned location. gets so messy if u try to move it around!
