### ISSUE TITLE
Login on phone

### ISSUE THREAD

**Issue by movak93** [mchristopher/PokemonGo-DesktopMap#762]
How do I login on the electron desktop map using my Pokemon go account on the mobile? I used the toggle sharing option and used that link to open the map on my phone, but there's no login option. Please tell me how it works on the phone!

**Comment by nicholasgodoyx** [comment]
When you click "toggle sharing" it shows you an URL. Just go to that URL and the map should be there.

**Comment by movak93** [comment]
@nicholasgodoyx  I'm able to open the map on my phone. But how do I login using my Pokemon account on the map?

**Comment by nicholasgodoyx** [comment]
You don't need to if you already did it on your PC. It's connected to the computer. It sees everything the computer sees.

**Comment by MrAwesomers** [comment]
Please use a different account for scanning, not the account you actually play on. It's possible the account you scan with might get banned in the future. You never know, so rather be safe than sorry!
