### ISSUE TITLE
Compatability for exposing as a webserver?

### ISSUE THREAD

**Issue by Schwaitz** [mchristopher/PokemonGo-DesktopMap#763]
Hey, I'm new to this project. It seems to only be on localhost, is there a way to expose it via port forwarding?

Thanks.

**Comment by mike2246** [comment]
8000

**Comment by yosang** [comment]
How exactly can we put this into a website? Any tutorials around?

**Comment by Schwaitz** [comment]
@yosang Portforward the port 8000, go to [whatismyip](https://www.whatismyip.com/) on the computer that is running the program, go to that ip:8000 on a different device.

**Comment by mattrat88** [comment]
@yosang the reason we had Pokevision taken away was because of stupid stuff like wanting to put it on a public website , stop while your ahead don't screw this up for the rest of us

**Comment by squirtlesquadLA** [comment]
Why set it up as a website if you can get the app working and other people can do it themselves? If they want it that bad then let them download it honestly. I understand that we should be nice to the community, but just share locations when you are out hunting not putting up a website. @yosang

**Comment by mattrat88** [comment]
If he puts a website up he can be sure he'll be in for some cyber attacks don't screw this up for us , cause you will make so many people your enemy

**Comment by mattrat88** [comment]
Omg and he displays his gmail on his profile ! Agahaha man your skin fornt

**Comment by Schwaitz** [comment]
I just read this.

@mattrat88 I don't know if that was directed towards me, or to @yosang, but I have no itentions on creating any sort of website. @yosang was. I simply wanted to open a port for my own personal access.
