### ISSUE TITLE
Location not following 

### ISSUE THREAD

**Issue by mattrat88** [mchristopher/PokemonGo-DesktopMap#765]
Maybe I'm a little new for assuming this but if the app is open on my phone am I not abled to have it follow my phones. Location ? If so it doesn't seem to be working :/ I apologies if this is a stupid question

**Comment by SmilinItalin** [comment]
We had it working last night the same thing......kind of knew to the mobile aspect though.

**Comment by muffettsman** [comment]
one way to manually do it - setup rdp to your home pc.... pull the long/lat cords from google maps of the current area you are in then plug it in via the options menu - then i pulled the url from the mobile button and messaged it to myself / shared with the kids (obviously this isn't the RIGHT way to do it but i'm a hack and it worked lol)

**Comment by screwyluie** [comment]
prior to the API change and the subsequent new version of this the map used to follow my phone's location. It no longer does. The webpage doesn't even ask for permission to use location so it seems to be completely broken
