### ISSUE TITLE
Multiple people on same map. 

### ISSUE THREAD

**Issue by SmilinItalin** [mchristopher/PokemonGo-DesktopMap#767]
Not sure but i was trying to run one map with my son and I last night. I thought it was working today. but seemed like, when you scan a new place it stops the old one. So i guess my question is there a way to set up more than one scan on the same map?

**Comment by ohiotech** [comment]
Don't use the same login for the second map. Use a different login. So if you want to create 5 maps, you need 5 unique logins for overlap and spread on an area. And as always, never use your actual credentials used for the game.

**Comment by Drewbacca81** [comment]
Shouldn't be limiting the number of logins we're using? These scanners already limit the servers pretty badly, using multiple scanners makes it even worse. Ha, I promise I'm not paid by Niantic...

**Comment by SmilinItalin** [comment]
lol i think a lot of that is just hype @Drewbacca81  but im not a programmer. i was just trying to set it up kind of to help my local community some lol........ yes was just about to try that @ohiotech  thank you

**Comment by SmilinItalin** [comment]
@ohiotech ......ok just tried it......with two diff accounts. and for some reason it would do the same thing as if i had two people on the same account. I was running it as two seperat progams with two diff logg in? anyidea's?

**Comment by Kr4ml** [comment]
I have same issue as @SmilinItalin 
When I login second account it stop scanning at the first one. First looks like it scanning but it don't refresh anything...
I use two separated PTC account with different API keys (i try WIN7 and WIN 10)....

**Comment by 23ten** [comment]
Maybe, just maybe, those requests are being throttled by the server. You should be able to check the console logs and verify if there's anything there saying throttled. I'm just guessing though.

**Comment by ohiotech** [comment]
Sorry for the delay guys. I do up to 3 on any given night. I'm using version 2.1. Note that The first account I'm using it PTC, and it's the one I've had the longest. When I opt to perform a 2nd and 3rd scan at the same time, I can do all three sometimes, and others I can only do my original. When it works, you get the green  Operational box at the top. When the other two don't, you get the Waiting box. For scans 2 and 3, I drag out the location icon so there's overlap onto my main search area.

Note that I have gone through the tutorial on all 3 accounts, have caught pokemon close to my house, so I should be past all of the ToS and tutorial based reasons why the other two don't work. Oddly enough, my first one has been working all this time and I never accepted the ToS until the other night.

That said, there may be other considerations why my other two work the way they do. I'm using one map key for all 3 logins. The other two accounts are Google, and only work for 30 minutes to 8 hours before crapping out. If they do crap out, I have to wait 24 hours from when I started using them again.
