### ISSUE TITLE
Map on Iphone

### ISSUE THREAD

**Issue by movak93** [mchristopher/PokemonGo-DesktopMap#772]
My laptop is out of commission right now. I need to start using the map on my phone. I don't have the link anymore. How do I get the maps on my phone?

**Comment by SmilinItalin** [comment]
Im not positive.......but i think one of the designer addressed this once. As its a app that is designed for a Pc........ So the only way i know is to run it on a pc then link to your phone.......but im  not  100 positive of this..... only 95% lol
