### ISSUE TITLE
View map without scanning?

### ISSUE THREAD

**Issue by ShinigamiSama13** [mchristopher/PokemonGo-DesktopMap#773]
Is there any way of viewing the map without scanning? I use this only to map out the locations of stops and gyms in areas I will be going to so I can see what's there before getting there. Once I have an area mapped out I like to go back and refer to it but the program doesn't really have a "view only" mode. Is there a program I can use to view all the points on a map? I've tried using Google My Maps but it has a 2000 point limit per layer and I have at least 4000 points in the .db file.

**Comment by SmilinItalin** [comment]
As they have developed this they have set it up pretty sweetly, if you look at the left top corner..... there is a drop down you can change it to view all of it or nothing, i change it depending on what im doing..... if im going gym hunting as an example......i turn off stops and Mons and just show gyms....... with the moblie aspect......... you can view it and change it as your out there.......

**Comment by ShinigamiSama13** [comment]
@SmilinItalin I've been using that feature and it is useful. However I was wondering if there was a way to look at just gyms/stops without the program scanning somewhere in the background. Even with the scan radius set to 0, it will keep scanning the same spot over and over. Basically once I finish mapping, I'd like to be able to view all the gym/stop locations without needing to connect to Niantic's servers at all.

**Comment by Mirx** [comment]
If you are worried about unnecessarily utilizing the API just disable search under "Location Settings" after you got the first results for gyms and stops.

**Comment by Galastorm** [comment]
I'd really like to see this feature added to the application as well please.  I often use the map to look for stops and gyms and it was really frustrating to know all that information was there for me to use but with no access when the API was down.
