### ISSUE TITLE
Waiting.........

### ISSUE THREAD

**Issue by Roosje007** [mchristopher/PokemonGo-DesktopMap#774]
Can some one help me with this bug, that its stuck on waiting and does not show anything.

**Comment by dudeman999** [comment]
When that happened to me, It meant that the ptc account that I created needed to accept the TOS. So either manually log into the game with the account you plan to use for the scanner or find a program that will automatically accept the TOS for you. It will not scan until the account accepts TOS.

**Comment by Roosje007** [comment]
Thanks its fixt!

**Comment by Benyuss** [comment]
i've accepted it + caught my first pokemon with that acc but it's the same after that.

**Comment by oldage** [comment]
Same here, TOS has been accepted on the account but it never gets past waiting.
