### ISSUE TITLE
linux version doesnt work (0.2.1)

### ISSUE THREAD

**Issue by francistower** [mchristopher/PokemonGo-DesktopMap#776]
linux version doesnt work (0.2.1)

**Comment by man981** [comment]
Does not work for me either. I am stuck at the "Loading, please wait..." page

**Comment by diophantus7** [comment]
Same here. After deleting config.ini I get 'ImportError: No module named xxhash'

**Comment by peacemaker11** [comment]
me working 0.2.1, try upgrade and install

pip install --upgrade pip
sudo pip install xxhash

**Comment by diophantus7** [comment]
Did the job, thanks!

**Comment by Benyuss** [comment]
> pip install --upgrade pip
sudo pip install xxhash

got past through "Loading, please wait..." but after that I get the UI and map never come up.

**Comment by diophantus7** [comment]
Well, to be precise I did 
sudo -H pip install -r requirements.txt
with the requirements.txt from https://github.com/PokemonGoMap/PokemonGo-Map/

**Comment by Benyuss** [comment]
nothing's changed

**Comment by diophantus7** [comment]
What kind of message do you get if you start Pokemon Go Map from console?

**Comment by Benyuss** [comment]
https://drive.google.com/file/d/0B7wJyNPLUTHVaTB5d1Jmd1hQUzQ/view

theres literally no errors. Should I wait 'til queue drops to 0?

**Comment by patrissimo** [comment]
I'm trying to run on linux; nothing happens after I enter the info and hit "Login with PTC". I'd love to have log messages like Benyuss posted - do I need a flag or something to enable logging? There's no output in my console. I know PTC logins can be really flaky.

**Comment by diophantus7** [comment]
Have you guys tried to run the regular PokemonGoMap? Maybe that will work...
