### ISSUE TITLE
PokemonGo - Desktop map operational but not working

### ISSUE THREAD

**Issue by PokemongoGether** [mchristopher/PokemonGo-DesktopMap#777]
Map works from anywhere of half an hour to an hour and 30mins then stops sending update to phone and stops working on PC, need a co pilot to run maps for me at home while i hunt in order to get around this, any other suggestions? or fixes?

**Comment by Kr4ml** [comment]
This happens when you use google login, use PTC login and it will work almost forewer...
Its because google need intraction from user every 30min...

**Comment by jareem** [comment]
Solved.

**Comment by PokemongoGether** [comment]
You're the man keep it up and thanks

**Comment by Benyuss** [comment]
close it then

**Comment by PokemongoGether** [comment]
Now all it says is that its Waiting and not operational at the center top using this method

**Comment by jijetelu** [comment]
I created a new PTC account and it stays on Waiting. The account i had for 14 days works fine ?

**Comment by Wanderer859** [comment]
Hey, I don't know the solution but I know the problem.

New PTC accounts now require you to accept a terms of agreement when they login which is why you're getting your waiting message.  Once it's accepted you can scan.

**Comment by Benyuss** [comment]
Log in with that account on your phone, accept, catch the first pokemon and log out.

**Comment by jijetelu** [comment]
Thx, did just that, works fine now, a bit troublesome, thx :D

**Comment by PokemongoGether** [comment]
works case closed =]

**Comment by jareem** [comment]
@PokemongoGether Please close this thread.
