### ISSUE TITLE
Can't change scan location

### ISSUE THREAD

**Issue by easygoing17** [mchristopher/PokemonGo-DesktopMap#778]
Hi everybody,
I installed PokemonGo on my PC (windows). Everything OK (i had to put javascript API on cause I had problems), but now I cannot change location by typing a new address, except thanks to the first menu, but close the app to change the address is very boring.
Need ur help plz

**Comment by FirelordPhoenix** [comment]
Can you drag the marker?

**Comment by easygoing17** [comment]
yes, I didn't know this trick ! Thks

**Comment by jareem** [comment]
Close this issue then.

**Comment by easygoing17** [comment]
Not possible to fix the problem despite everything ? Not easy to use for far away cities from me

**Comment by jareem** [comment]
![capture](https://cloud.githubusercontent.com/assets/18504090/17524969/fe64a4e2-5e60-11e6-8fab-40c4503bdd50.PNG)

**Comment by easygoing17** [comment]
ahah funny, I appreciate :)
But no, when I write something, nothing change, even if i press enter ...

I can only move the marker

**Comment by eyl327** [comment]
I had the same issue happening. After waiting a few hours, it was working again. I'm not sure what fixed it.
