### ISSUE TITLE
Search step 1 map parsing failed

### ISSUE THREAD

**Issue by woutervuden** [mchristopher/PokemonGo-DesktopMap#779]
Used the map without any problems yesterday. Today I keep getting the message "Search step 1 map parsing failed, retrying request in [x] seconds" in the console.
Is the app down? anybody a solution? 

caught some amazing stuff yesterday!

**Comment by jareem** [comment]
What step number do you use ?

**Comment by DigitalPigeon** [comment]
Hey man, see my comments on 800, or from 789.

You literally just need to log in to the account you are using for scanning via your smart phone of choice, and catch your first intro pokemon. That will clear it up.

This just started happening yesterday, so if you've been using a dedicated account for scanning all along, it would have stopped yesterday until you login and do this.
