### ISSUE TITLE
Mac app crashes

### ISSUE THREAD

**Issue by alessioros** [mchristopher/PokemonGo-DesktopMap#780]
The last version 0.2.1 crashes after login with Google:

Crashed Thread:        11  Chrome_IOThread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000010
Exception Note:        EXC_CORPSE_NOTIFY

**Comment by pokemontracker81** [comment]
Getting the same on a fully up to date Mac. Can dump a full log but seems like it's pretty reproducible on login with a google acct.

**Comment by bwebs** [comment]
I had this same problem. Re-installed Chrome in Applications and it fixed it.
