### ISSUE TITLE
scan stops when frends are scanning 

### ISSUE THREAD

**Issue by mitchellnec** [mchristopher/PokemonGo-DesktopMap#781]
hii all is there a way, for who used it to get more scanning running at one time, cuz when im scanning and seconds later a frend is scanning my scan stops, is there a way to get them both running ? 
and see the results of both or even more scans ? 
really sorry for my bad writen eng, tnx!

**Comment by jareem** [comment]
You are using the same account. That's why.
Create a second PTC account, login in pgo app, follow the tutorial, log off.
Use this account on a second instance of Pgo map.
