### ISSUE TITLE
More range and less delay to scan

### ISSUE THREAD

**Issue by ThigSchuch** [mchristopher/PokemonGo-DesktopMap#783]

**Comment by mg6101** [comment]
Not sure of any specifics to why you posted this "bug." The scan radius and speed are the best values that they can be. Niantic changed the scan radius to 70 meters a while ago and last week changed the maximum scan time to roughly once every 10 seconds. Anything faster than that will show 0 Pokemon on the map and eventually earn the account a ban. If you need faster scanning, try opening a second instance of the map 5 minutes after the first one and log in with a different PTC account. Then minimize the second one and both should be running on the first map.

**Comment by ThigSchuch** [comment]
Could have a greater reach in less time, if possible, as a radius of 1km in
less than 5 seconds, a region or small town would be quickly scanned. Did
you understand what I said? But if the Niantic does not, ok, I'm enjoying
your work!

2016-08-09 15:13 GMT-03:00 mg6101 <notifications@github.com>:
