### ISSUE TITLE
"All Locations" maps do not work, showing Oops error.

### ISSUE THREAD

**Issue by Rezurektion** [mchristopher/PokemonGo-DesktopMap#785]
When I try to view the All Locations of a Pokemon from the Full Stats page, the heat map show up for a second and then switches to this: 
![image](https://cloud.githubusercontent.com/assets/20930552/17522133/dfbf293c-5e23-11e6-8120-f87976d46d90.png)

A little backstory...when I first was running the local map using Python (before Pokemon GO Live Map), I had this same issue when running a standard scan. I was able to fix it by editing the map.html file in the Templates folder, removing the "{{ gmaps_key ))" entry and replacing it with my actual API key. I didn't have to do this with Pokemon GO Live Map for it to work, which was nice. When I tried to use the All Locations feature, it would bring up a blank white page. I modified the statistics.html file in the Templates folder (assuming that's what it's calling) the same way at before, replacing "{{ gmaps_key }}" with the actual API key. Once I did this and restarted the program, I tested the All Locations feature and it brought me to my current issue; the map shows for 1 second, than shows the "Oops!" error in the screenshot. Strangely, I reverted the change to the statistics.html file, yet I'm still getting the same error rather than a blank white screen.

Any help is appreciated! :)

Windows 7 x64, Desktop, PTC account.

**Comment by jareem** [comment]
Is your gmap Javascript API activated ? Check your google console for any error aswell.

**Comment by Davidsrao** [comment]
same issue. Javascript API is activated. Access through the original pokemon-go-map submodule no problem at all.
<img width="1769" alt="screen shot 2016-08-09 at 18 39 14" src="https://cloud.githubusercontent.com/assets/6170811/17524886/ad7a9f14-5e60-11e6-8ff6-b9a0352d100f.png">

**Comment by jareem** [comment]
Are you using the compiled version ?

**Comment by Mirx** [comment]
Just use the back button. At least, that works for me in Firefox. It's probably ABP or some other plugin blocking the java script popup.

**Comment by Rezurektion** [comment]
jareem: You were on the money with needing to enable the Javascipt API. After enabling it and restarting the program, I can see the heatmap. Thank you very much!
