### ISSUE TITLE
Pokemons that last longer than 15 minutes, only show when they are 15 minutes away from expiring

### ISSUE THREAD

**Issue by Beltroniko** [mchristopher/PokemonGo-DesktopMap#786]
This has happened to me twice in the last couple of days (with a Primeape and a Dratini). I could see them in Pokemon GO, but they would not show in the map. After a while (~10mins), the map found them with still 12-14 minutes to expire.

**Comment by jareem** [comment]
No pokemon spawn for more than 15min.
The complete cycle can last up to 10min if you select a radius of 5.

**Comment by romanticheart** [comment]
@jareem Is there a source for that? I had an Eevee show up in my Sightings list earlier today. I have two instances going on this map, with a scan radius of 3, so it refreshes pretty fast all things considered. Took over 10 minutes for Eevee to show up on the map, and the timer said 15 minutes.

**Comment by Beltroniko** [comment]
@jareem : My radius was just 2 and I centered it at the exact spot where they were.

AFAIK, althought rare, there are pokemon that stay longer than 15 minutes and those are only being shown when they are 15 minutes away from expiring.

**Comment by Beltroniko** [comment]
@jareem, @romanticheart 

Actually, someone else just opened a thread about this issue on reddit:
https://www.reddit.com/r/pokemongodev/comments/4x8xk3/false_positive_pokemon_db_spawn_entries_indicates/
