### ISSUE TITLE
Multiple Search locations 

### ISSUE THREAD

**Issue by DataDrug** [mchristopher/PokemonGo-DesktopMap#787]
https://github.com/AHAAAAAAA/PokemonGo-Map/pull/2179/files

I've tested this before, is anyone implementing it on the AHAAAAAAA fork ?

**Comment by Mirx** [comment]
AHAAAAAA is dead due to a cease and desist request which they are complying to. 

https://github.com/AHAAAAAAA/PokemonGo-Map

There are other "forks" continuing on the maps.

https://github.com/PokemonGoMap/PokemonGo-Map

**Comment by DataDrug** [comment]
I'm talking about mchristopher PokemonGo-Map for from the original developer :/

**Comment by Mirx** [comment]
Ah, then I think it would be better to ask the question in https://github.com/PokemonGoMap/PokemonGo-Map/tree/develop or submit a pull request there.

**Comment by Mirx** [comment]
If you go to https://github.com/mchristopher/PokemonGo-Map, you'll see at the bottom of the page:

_Please submit all pull requests to develop branch._

Where the develop branch is the above link.

**Comment by DataDrug** [comment]
I'll post there, thanks!
