### ISSUE TITLE
No pokemons, Java Script error. Fifth day trying to resolve.

### ISSUE THREAD

**Issue by Sigmarion** [mchristopher/PokemonGo-DesktopMap#788]
I have a problem - it was already discussed in other issues, but i found no decision. I tried almost everithing. I have Windows 7.

Here is the problem. The expected desicions that doesn't worked for me will be in the end.

This happens when I install the map.
![3skreen](https://cloud.githubusercontent.com/assets/20904006/17524898/bb8b65d4-5e60-11e6-9c1a-4a6e917791b2.jpg)
This happens when I start the map.
![2skreen](https://cloud.githubusercontent.com/assets/20904006/17524979/0a56f264-5e61-11e6-8aa3-7c0c682500d9.jpg)
Thie happens when I use the map.
![1skreen](https://cloud.githubusercontent.com/assets/20904006/17525036/471aa02e-5e61-11e6-9470-0483bac53755.jpg)

I have tried to:
1) Update Java.
2) Reinstall the map on my PC.
3) Install the map on my friends PC.  (He has Windows 7)
4) Install the map on PC with WinXP.
5) Use different API and different projects (I use Google Maps JavaScript API, Browser type)
6) Regenarate API key in API Console.
7) Accept Terms and Conditions. Pass the in-game tutorial and give a name to a pokemon master.
8) Log-inn with Google - old one and brand-new with new API and old API, and with PTC - neither helped.
9) Start the shortcut like andmin and in different Compatibility modes.
10) Turn off firewall and antivirus.

The point is that the problem starts with installation...

Please help, tired of this(

**Comment by Wanderer859** [comment]
I'm not a developer but i'll help with what I can.

1. Which version of the map are you using?

2. Are you using a google account or PTC account?

3. How long ago did you create the account to scan?

4. Are you using a separate account from your main account?

**Comment by avielc** [comment]
@Wanderer859 just to clear up what sigmarion said. he is probably using the latest ( i did)
he tried both accounts, in my case i've used 3 accounts, 1 google, create few weeks ago, 2 ptc, one is main another was made few days ago and passed through training.
that should answer everything, and yet nothing works.
check also #737 for that error

**Comment by avielc** [comment]
also @Sigmarion your main errors mean there is a python running in background

**Comment by regzilla** [comment]
Same situation, i'm stuck too. I can't figured out what's happened and how to solve it...

**Comment by avielc** [comment]
same, I need a more detailed log for python to understand this

**Comment by Sigmarion** [comment]
Today is the fifth day I'm trying to resolve this problem. I think next release can help.

**Comment by avielc** [comment]
do you know if and when there will be a next release? i don't hear anything from @mchristopher

**Comment by Sigmarion** [comment]
@avielc i actually don't know. And of couse there is a possibility that next release won't help.
Lets try to figure out whats wrong together.
My oppinion is that the problem is not with API google and PTC because I have the first error while installation. Now i'm trying to find solutions for samelike JS errors - i found this - https://support.discordapp.com/hc/en-us/articles/209099387--Windows-Installer-Update-failed- .
It didn't helped me - but i think the way is right.
If u find something interesting post it here.

**Comment by Sigmarion** [comment]
@avielc I have a progress - i've done whats written in my link (delete two folders - than RESTART (very important) the PC). While installation i didn't had a JS ERROR!!! And while 
Still not working but i have no Gyms and Pokestops (i saw them before deleting folders).
So maybe now the problem is with API

**Comment by avielc** [comment]
i'm totally up to work together buddy!
looking into your link now as well

**Comment by avielc** [comment]
the folders you mention there are related to discord app, which isn't really related to pokemongo
I need to try and remove everything related to Java,Python, nodejs (i went that far too) remove everything and restart, and start over
there are cache folder in appdata\roaming\pokemon-go-map
if you delete it, it pretty much erases the app back to default. but i'm sure there is something else i'm missing.
and why the very old 0.0.7 worked for me until the api change few days ago.. still puzzling

**Comment by Sigmarion** [comment]
@avielc 0.0.7 worked for me too. The point is that only from 0.1.2 "Everyone will need their own Google Maps API key."
I have started from 0.0.6 version and than 0.0.7. A week or two ago (before api changes) I have tried to use Version 0.1.4 or something (that needed API) and had no success. It didn't showed pokes - I thought that the problem was with API  and I returned to my 0.07. Maybe that problem stil remains and do not depends of API changes but depends of my PC settings or something.
Now we have no choise between versions.

**Comment by avielc** [comment]
Someone mentioned API ban. Maybe we need to switch API and try again?

**Comment by Sigmarion** [comment]
@avielc I found working APP - https://play.google.com/store/apps/details?id=xyz.syzygylabs.mapperforpokemongo&hl=ru . Poke Mapper. Worse than Desktop Map but at least something.

**Comment by avielc** [comment]
can it work on desktop though? I need a desktop app :-\

**Comment by Sigmarion** [comment]
@avielc It works only on Android. But u can use Bluestacks or something.

About Desktop map i found this:

https://github.com/mchristopher/PokemonGo-DesktopMap/issues/845
https://github.com/mchristopher/PokemonGo-DesktopMap/issues/799 - last post.

Maybe the problem is with port numbers but I didn't found how to change it yet.

**Comment by Sigmarion** [comment]
I found how to change => right click on a shortcut => settings => and where is written C:\Users\User_Name\AppData\Local\pokemon\Update.exe --processStart "Pokemon GO Live Map.exe" u should add   --port NUMBER.
For example:
C:\Users\BlaBlaBla\AppData\Local\pokemon\Update.exe --processStart "Pokemon GO Live Map.exe"  --port 8002

I think the java error has gone - and in log there is no "style of null" error.
![image](https://cloud.githubusercontent.com/assets/20904006/17616378/a67c70b4-6074-11e6-9561-a3f39c420da7.png)

But still 0 gyms 0 pokes.
I think the soution is close.

**Comment by avielc** [comment]
Hi @Sigmarion, in the meantime here is a crowdsourcing site for you to check
pokecrew.com.
that takes your mind off it.
also, i don't think its related to the port, as your computer should have that port occupied. 
we have a more serious issue with our GoogleAPI key not registering properly (check the 2nd line of your console in the picture)
i'm thinking something is missing, so i'm going to try a different approach which got updated really lately
https://github.com/tejado/pgoapi/issues/186
it has so many comments, but they go through few issues people have and how they got it to work.
so i think it's a good place to venture in. and most importantly, a different approach to our issue.
