### ISSUE TITLE
Nothing shows up on the map

### ISSUE THREAD

**Issue by loicboutet** [mchristopher/PokemonGo-DesktopMap#789]
I'm using the release for mac, I set up a PTC account and accepted the TOS.
The javascript API key is set up and request shows on the dashboard. 

However I have just the map showing up with nothing on it. 
<img width="799" alt="capture d ecran 2016-08-09 a 19 46 56" src="https://cloud.githubusercontent.com/assets/3776/17527038/10f33ef8-5e6a-11e6-952d-00610b41f3bb.png">

On the console I see the log : 
2016-08-09 19:47:20,382 [ search_worker_0][        search][   ERROR] Search step 1 map parsing failed, retyring request in 30 seconds

Any idea on what is going wrong?

**Comment by mg6101** [comment]
Did you catch your first Pokemon? Its not just the TOS anymore.

**Comment by wartortle87** [comment]
in the options menu, is "pokemon" toggled on?

**Comment by loicboutet** [comment]
The problem was to catch the first pokemon :) Thanks!
