### ISSUE TITLE
no pokemon in the 4 versions I tried

### ISSUE THREAD

**Issue by dotas86** [mchristopher/PokemonGo-DesktopMap#79]
Hello, 

I use windows 10 and when I run the program I try with and without admin rights. I have tried 0.0.2, 0.0.3, 0.0.6 and 0.0.7 versions of your app but none of them show any pokemons/pokestops/gyms.
Am I doing something wrong? The servers were not down while I tried.

Thanks

**Comment by killerjerick** [comment]
Could be your firewall blocking them, works fine for me on 0.0.7 Win 10

**Comment by dotas86** [comment]
When it asked me for permission I allowed it . How can I be sure that it has indeed been allowed by my firewall? (Windows firewall and Avira Antivirus)

**Comment by killerjerick** [comment]
The quickest way to try it is disable them both, launch it see if it works, then enable one and try the other, that'll quickly tell you which one is blocking

**Comment by dotas86** [comment]
I disabled both and still nothing. I even tried in a laptop with no firewall at all. Maybe I do something else wrong. Let's take it to basics. I extract files to a folder, I run Pokemon GO Live Map from the extracted files as admin and then login to google from the form. I can see the map, I can change the coordinates but no pokemons/gyms/pokestops...
Do I miss something?

**Comment by kolyasik86** [comment]
Hi guys!
I very much want to install on Ubuntu, but does not work ((

Help please, or give guide.

Thank you so much!

**Comment by dotas86** [comment]
![nothing here](https://cloud.githubusercontent.com/assets/20579775/17029297/67961614-4f73-11e6-8f83-45ab9924bd5a.PNG)
This is what I see in my location which I have found the past 40 mins more than 30 pokemons and has 2 gyms nearby as well as more than 15 pokestops.

**Comment by dotas86** [comment]
Can anyone help? This is really fristrating

**Comment by dotas86** [comment]
I found the solution. It only works when the zip file is extracted where it's downloaded. Otherwise it does not work.
