### ISSUE TITLE
Not sure if issue, but...

### ISSUE THREAD

**Issue by Raazk** [mchristopher/PokemonGo-DesktopMap#792]
I was wondering if its possible to have several scannings on at once. I have manage somehow to make mine scan two areas atm. But i dont know how. 
I would like to push like several 3 or 2 radius scans all over my town instead of just having 1 big 1. Is this possible? 
If so, then how do i do?

**Comment by mg6101** [comment]
Not currently possible on one machine. You can create a large scan and open multiple instances of the map with multiple PTC accounts 5 minutes apart to stagger the scan time but thats about it right now.

**Comment by Raazk** [comment]
Okey thx. :(
