### ISSUE TITLE
Using real account? Softban?

### ISSUE THREAD

**Issue by jayappletree** [mchristopher/PokemonGo-DesktopMap#793]
Just wondering is DesktopMap using real account to scan? Cause I found two interesting things while login DesktopMap with my secondary account.

1.Egg has been hatched even if I haven't play this account for a long time. 
2. Once I catch some pokemon with this account, this pokemon would not been detected by DesktopMap. 

If the answer to my question at the beginning is yes, so I am a little bit worried about my account would be banned.

If DesktopMap is all safe, the bright side is that I could use it as an automatic egg hatcher : )

**Comment by Wanderer859** [comment]
Do not use your real account. Before the API was updated a few days ago they were able to tell which accounts were scanners and which were people actually playing and thus update the API and block those that weren't real people..

**Comment by jayappletree** [comment]
@Wanderer859 Thanks for your advice!!!

**Comment by lfctan** [comment]
Hi what if I have already used my real account?Can I disable it?

**Comment by Shogunz1** [comment]
From what I understand they just do a temp ban, or soft ban. You should be able to use ur main fine later. Just don't scan with it again.

**Comment by lfctan** [comment]
I have only scanned it once and i scared of ban so i went to delete the application and also delete the google project.Does it work???If not what should i do?
