### ISSUE TITLE
How to reduce the number of scans?

### ISSUE THREAD

**Issue by jalapenopicante** [mchristopher/PokemonGo-DesktopMap#794]
Hello could someone please direct me on how to reduce the number of scans? In a sense, I don't want to make a big hexagon. Only one 2-3 layers thick (~20 scans). Could someone please help?

**Comment by squirtlesquadLA** [comment]
on login screen just scroll down and reduce the radius

**Comment by jalapenopicante** [comment]
Wow I'm dumb. Thank you!!!
