### ISSUE TITLE
Map Does Not Work

### ISSUE THREAD

**Issue by harunosakura872** [mchristopher/PokemonGo-DesktopMap#796]
Map does not work for me. I have accepted TOS in game and tried to login using PTC and google. Map shows operational but does not show pokestops or pokemon. When I click on options or stats nothing comes up.

Please help

**Comment by DigitalPigeon** [comment]
Jump to Tools -> Toggle Developer Tools. Can you copy and paste in the content from there after 30  seconds or so of operation please?

**Comment by avielc** [comment]
@DigitalPigeon care to take a look at #737 we have the issue there with more detail

**Comment by harunosakura872** [comment]
@DigitalPigeon below is the log

Express server started!
2main.html:158 server up: http://localhost:8001
main.html:146 Error getting location, trying second provider PositionError
main.html:148 Found location [18.9750,72.8258] by ipinfo.io
main.html:168 2016-08-10 22:48:24,859 [ search_worker_0][      auth_ptc][    INFO] PTC User Login successful.

main.html:168 2016-08-10 22:48:24,859 [ search_worker_0][      auth_ptc][    INFO] Request PTC Access Token...

main.html:274 MAP: Uncaught ReferenceError: skel is not defined
main.html:274 MAP: Uncaught ReferenceError: $ is not defined
main.html:168 2016-08-10 22:48:25,302 [ search_worker_0][      auth_ptc][    INFO] PTC Access Token successfully retrieved.

main.html:168 2016-08-10 22:48:25,312 [ search_worker_0][        pgoapi][    INFO] Creating a new direct request...

main.html:168 2016-08-10 22:48:25,312 [ search_worker_0][        pgoapi][    INFO] Adding 'GET_MAP_OBJECTS' to RPC request including arguments

main.html:168 2016-08-10 22:48:25,313 [ search_worker_0][        pgoapi][    INFO] Execution of RPC

main.html:274 MAP: Uncaught ReferenceError: $ is not defined
main.html:168 2016-08-10 22:48:26,019 [ search_worker_0][        pgoapi][    INFO] API Endpoint redirect... re-execution of call

main.html:274 MAP: Uncaught ReferenceError: $ is not defined
main.html:168 2016-08-10 22:48:26,421 [ search_worker_0][        pgoapi][    INFO] Cleanup of request!

main.html:168 2016-08-10 22:48:26,733 [ search_worker_0][        models][    INFO] Upserted 0 pokemon, 77 pokestops, and 12 gyms

2main.html:274 MAP: Uncaught ReferenceError: $ is not defined
main.html:168 2016-08-10 22:48:36,892 [ search_worker_0][        search][    INFO] Search step 2 beginning (queue size is 5)

main.html:168 2016-08-10 22:48:36,911 [ search_worker_0][        pgoapi][    INFO] Creating a new direct request...
2016-08-10 22:48:36,911 [ search_worker_0][        pgoapi][    INFO] Adding 'GET_MAP_OBJECTS' to RPC request including arguments

main.html:168 2016-08-10 22:48:36,911 [ search_worker_0][        pgoapi][    INFO] Execution of RPC

main.html:168 2016-08-10 22:48:37,262 [ search_worker_0][        pgoapi][    INFO] Cleanup of request!

main.html:168 2016-08-10 22:48:37,456 [ search_worker_0][        models][    INFO] Upserted 0 pokemon, 78 pokestops, and 12 gyms

4main.html:274 MAP: Uncaught ReferenceError: $ is not defined
main.html:168 2016-08-10 22:48:47,535 [ search_worker_0][        search][    INFO] Search step 3 beginning (queue size is 4)

main.html:168 2016-08-10 22:48:47,545 [ search_worker_0][        pgoapi][    INFO] Creating a new direct request...
2016-08-10 22:48:47,545 [ search_worker_0][        pgoapi][    INFO] Adding 'GET_MAP_OBJECTS' to RPC request including arguments

main.html:168 2016-08-10 22:48:47,545 [ search_worker_0][        pgoapi][    INFO] Execution of RPC

main.html:168 2016-08-10 22:48:47,895 [ search_worker_0][        pgoapi][    INFO] Cleanup of request!

main.html:168 2016-08-10 22:48:48,288 [ search_worker_0][        models][    INFO] Upserted 0 pokemon, 83 pokestops, and 12 gyms

main.html:168 2016-08-10 22:48:58,385 [ search_worker_0][        search][    INFO] Search step 4 beginning (queue size is 3)

main.html:168 2016-08-10 22:48:58,405 [ search_worker_0][        pgoapi][    INFO] Creating a new direct request...
2016-08-10 22:48:58,405 [ search_worker_0][        pgoapi][    INFO] Adding 'GET_MAP_OBJECTS' to RPC request including arguments

main.html:168 2016-08-10 22:48:58,405 [ search_worker_0][        pgoapi][    INFO] Execution of RPC

main.html:168 2016-08-10 22:48:58,756 [ search_worker_0][        pgoapi][    INFO] Cleanup of request!

main.html:168 2016-08-10 22:48:58,986 [ search_worker_0][        models][    INFO] Upserted 0 pokemon, 88 pokestops, and 12 gyms

main.html:168 2016-08-10 22:49:09,084 [ search_worker_0][        search][    INFO] Search step 5 beginning (queue size is 2)

main.html:168 2016-08-10 22:49:09,104 [ search_worker_0][        pgoapi][    INFO] Creating a new direct request...
2016-08-10 22:49:09,104 [ search_worker_0][        pgoapi][    INFO] Adding 'GET_MAP_OBJECTS' to RPC request including arguments

main.html:168 2016-08-10 22:49:09,104 [ search_worker_0][        pgoapi][    INFO] Execution of RPC

main.html:168 2016-08-10 22:49:09,453 [ search_worker_0][        pgoapi][    INFO] Cleanup of request!

main.html:168 2016-08-10 22:49:09,654 [ search_worker_0][        models][    INFO] Upserted 0 pokemon, 90 pokestops, and 13 gyms

main.html:168 2016-08-10 22:49:19,723 [ search_worker_0][        search][    INFO] Search step 6 beginning (queue size is 1)

main.html:168 2016-08-10 22:49:19,743 [ search_worker_0][        pgoapi][    INFO] Creating a new direct request...
2016-08-10 22:49:19,743 [ search_worker_0][        pgoapi][    INFO] Adding 'GET_MAP_OBJECTS' to RPC request including arguments

main.html:168 2016-08-10 22:49:19,743 [ search_worker_0][        pgoapi][    INFO] Execution of RPC

main.html:168 2016-08-10 22:49:20,094 [ search_worker_0][        pgoapi][    INFO] Cleanup of request!

main.html:168 2016-08-10 22:49:20,293 [ search_worker_0][        models][    INFO] Upserted 0 pokemon, 77 pokestops, and 11 gyms

main.html:168 2016-08-10 22:49:30,354 [ search_worker_0][        search][    INFO] Search step 7 beginning (queue size is 0)

main.html:168 2016-08-10 22:49:30,364 [ search_worker_0][        pgoapi][    INFO] Creating a new direct request...
2016-08-10 22:49:30,364 [ search_worker_0][        pgoapi][    INFO] Adding 'GET_MAP_OBJECTS' to RPC request including arguments

main.html:168 2016-08-10 22:49:30,364 [ search_worker_0][        pgoapi][    INFO] Execution of RPC

main.html:168 2016-08-10 22:49:30,733 [ search_worker_0][        pgoapi][    INFO] Cleanup of request!

main.html:168 2016-08-10 22:49:30,950 [ search_worker_0][        models][    INFO] Upserted 0 pokemon, 80 pokestops, and 11 gyms

main.html:168 2016-08-10 22:49:41,003 [ search_worker_0][        search][    INFO] Search step 1 beginning (queue size is 6)

main.html:168 2016-08-10 22:49:41,013 [ search_worker_0][        pgoapi][    INFO] Creating a new direct request...
2016-08-10 22:49:41,013 [ search_worker_0][        pgoapi][    INFO] Adding 'GET_MAP_OBJECTS' to RPC request including arguments

main.html:168 2016-08-10 22:49:41,013 [ search_worker_0][        pgoapi][    INFO] Execution of RPC

main.html:168 2016-08-10 22:49:41,364 [ search_worker_0][        pgoapi][    INFO] Cleanup of request!

main.html:168 2016-08-10 22:49:41,565 [ search_worker_0][        models][    INFO] Upserted 0 pokemon, 77 pokestops, and 12 gyms

main.html:274 MAP: Uncaught ReferenceError: $ is not defined
main.html:168 2016-08-10 22:49:51,635 [ search_worker_0][        search][    INFO] Search step 2 beginning (queue size is 5)

main.html:168 2016-08-10 22:49:51,655 [ search_worker_0][        pgoapi][    INFO] Creating a new direct request...
2016-08-10 22:49:51,655 [ search_worker_0][        pgoapi][    INFO] Adding 'GET_MAP_OBJECTS' to RPC request including arguments

main.html:168 2016-08-10 22:49:51,657 [ search_worker_0][        pgoapi][    INFO] Execution of RPC

main.html:168 2016-08-10 22:49:52,026 [ search_worker_0][        pgoapi][    INFO] Cleanup of request!

main.html:168 2016-08-10 22:49:52,250 [ search_worker_0][        models][    INFO] Upserted 0 pokemon, 78 pokestops, and 12 gyms

main.html:168 2016-08-10 22:50:02,321 [ search_worker_0][        search][    INFO] Search step 3 beginning (queue size is 4)

main.html:168 2016-08-10 22:50:02,335 [ search_worker_0][        pgoapi][    INFO] Creating a new direct request...
2016-08-10 22:50:02,336 [ search_worker_0][        pgoapi][    INFO] Adding 'GET_MAP_OBJECTS' to RPC request including arguments

main.html:168 2016-08-10 22:50:02,336 [ search_worker_0][        pgoapi][    INFO] Execution of RPC

main.html:168 2016-08-10 22:50:02,671 [ search_worker_0][        pgoapi][    INFO] Cleanup of request!

main.html:168 2016-08-10 22:50:02,858 [ search_worker_0][        models][    INFO] Upserted 0 pokemon, 83 pokestops, and 12 gyms

main.html:168 2016-08-10 22:50:12,941 [ search_worker_0][        search][    INFO] Search step 4 beginning (queue size is 3)

main.html:168 2016-08-10 22:50:12,963 [ search_worker_0][        pgoapi][    INFO] Creating a new direct request...

main.html:168 2016-08-10 22:50:12,963 [ search_worker_0][        pgoapi][    INFO] Adding 'GET_MAP_OBJECTS' to RPC request including arguments

main.html:168 2016-08-10 22:50:12,963 [ search_worker_0][        pgoapi][    INFO] Execution of RPC

main.html:168 2016-08-10 22:50:13,292 [ search_worker_0][        pgoapi][    INFO] Cleanup of request!

main.html:168 2016-08-10 22:50:13,648 [ search_worker_0][        models][    INFO] Upserted 0 pokemon, 88 pokestops, and 12 gyms

main.html:168 2016-08-10 22:50:23,780 [ search_worker_0][        search][    INFO] Search step 5 beginning (queue size is 2)

main.html:168 2016-08-10 22:50:23,803 [ search_worker_0][        pgoapi][    INFO] Creating a new direct request...

main.html:168 2016-08-10 22:50:23,803 [ search_worker_0][        pgoapi][    INFO] Adding 'GET_MAP_OBJECTS' to RPC request including arguments

main.html:168 2016-08-10 22:50:23,803 [ search_worker_0][        pgoapi][    INFO] Execution of RPC

main.html:168 2016-08-10 22:50:24,154 [ search_worker_0][        pgoapi][    INFO] Cleanup of request!

main.html:168 2016-08-10 22:50:24,375 [ search_worker_0][        models][    INFO] Upserted 0 pokemon, 90 pokestops, and 13 gyms

main.html:168 2016-08-10 22:50:34,450 [ search_worker_0][        search][    INFO] Search step 6 beginning (queue size is 1)

main.html:168 2016-08-10 22:50:34,470 [ search_worker_0][        pgoapi][    INFO] Creating a new direct request...
2016-08-10 22:50:34,470 [ search_worker_0][        pgoapi][    INFO] Adding 'GET_MAP_OBJECTS' to RPC request including arguments
2016-08-10 22:50:34,470 [ search_worker_0][        pgoapi][    INFO] Execution of RPC

main.html:168 2016-08-10 22:50:34,867 [ search_worker_0][        pgoapi][    INFO] Cleanup of request!

main.html:168 2016-08-10 22:50:35,069 [ search_worker_0][        models][    INFO] Upserted 0 pokemon, 77 pokestops, and 11 gyms

main.html:168 2016-08-10 22:50:45,168 [ search_worker_0][        search][    INFO] Search step 7 beginning (queue size is 0)

main.html:168 2016-08-10 22:50:45,188 [ search_worker_0][        pgoapi][    INFO] Creating a new direct request...
2016-08-10 22:50:45,188 [ search_worker_0][        pgoapi][    INFO] Adding 'GET_MAP_OBJECTS' to RPC request including arguments

main.html:168 2016-08-10 22:50:45,188 [ search_worker_0][        pgoapi][    INFO] Execution of RPC

main.html:168 2016-08-10 22:50:45,865 [ search_worker_0][        pgoapi][    INFO] Cleanup of request!

main.html:168 2016-08-10 22:50:46,256 [ search_worker_0][        models][    INFO] Upserted 0 pokemon, 80 pokestops, and 11 gyms

main.html:168 2016-08-10 22:50:56,348 [ search_worker_0][        search][    INFO] Search step 1 beginning (queue size is 6)

main.html:168 2016-08-10 22:50:56,358 [ search_worker_0][        pgoapi][    INFO] Creating a new direct request...
2016-08-10 22:50:56,358 [ search_worker_0][        pgoapi][    INFO] Adding 'GET_MAP_OBJECTS' to RPC request including arguments

main.html:168 2016-08-10 22:50:56,358 [ search_worker_0][        pgoapi][    INFO] Execution of RPC

main.html:168 2016-08-10 22:50:56,734 [ search_worker_0][        pgoapi][    INFO] Cleanup of request!

main.html:168 2016-08-10 22:50:56,967 [ search_worker_0][        models][    INFO] Upserted 0 pokemon, 77 pokestops, and 12 gyms

main.html:168 2016-08-10 22:51:07,051 [ search_worker_0][        search][    INFO] Search step 2 beginning (queue size is 5)

main.html:168 2016-08-10 22:51:07,061 [ search_worker_0][        pgoapi][    INFO] Creating a new direct request...
2016-08-10 22:51:07,061 [ search_worker_0][        pgoapi][    INFO] Adding 'GET_MAP_OBJECTS' to RPC request including arguments

main.html:168 2016-08-10 22:51:07,061 [ search_worker_0][        pgoapi][    INFO] Execution of RPC

main.html:168 2016-08-10 22:51:07,424 [ search_worker_0][        pgoapi][    INFO] Cleanup of request!

main.html:168 2016-08-10 22:51:07,634 [ search_worker_0][        models][    INFO] Upserted 0 pokemon, 78 pokestops, and 12 gyms

main.html:168 2016-08-10 22:51:17,704 [ search_worker_0][        search][    INFO] Search step 3 beginning (queue size is 4)

main.html:168 2016-08-10 22:51:17,723 [ search_worker_0][        pgoapi][    INFO] Creating a new direct request...
2016-08-10 22:51:17,723 [ search_worker_0][        pgoapi][    INFO] Adding 'GET_MAP_OBJECTS' to RPC request including arguments

main.html:168 2016-08-10 22:51:17,724 [ search_worker_0][        pgoapi][    INFO] Execution of RPC

main.html:168 2016-08-10 22:51:18,062 [ search_worker_0][        pgoapi][    INFO] Cleanup of request!

main.html:168 2016-08-10 22:51:18,279 [ search_worker_0][        models][    INFO] Upserted 0 pokemon, 83 pokestops, and 12 gyms
