### ISSUE TITLE
actual map not displaying on mobile

### ISSUE THREAD

**Issue by brusselseGiraf** [mchristopher/PokemonGo-DesktopMap#797]
The application works fine on desktop.
However if i open the mobile link provided on ipad or iphone or adroid, the map isnt displayed (nor pokemon). The necessary google maps apis are activated.
Im puzzled.

Anyone else with this issue?

**Comment by cpbeckner** [comment]
On the login screen, did you select Server Mode at the very bottom?

**Comment by 4esterfield** [comment]
@cpbeckner - I've the same problem. Server Mode was enabled. More detail I've wrote in [#798](https://github.com/mchristopher/PokemonGo-DesktopMap/issues/798) with error from PC console and mobile browser console (firefox)
