### ISSUE TITLE
Real account?

### ISSUE THREAD

**Issue by lfctan** [mchristopher/PokemonGo-DesktopMap#801]
Hi what if I have already used my real account?Can I disable it?

**Comment by MrAwesomers** [comment]
You can just logout, or restart the scanner to change accounts. If you have used your real account, they might have flagged it and it might get banned someday, depending on how many times you have used it for scanning and how long those sessions lasted. I don't know if they will really ban scanners though, I think their main problem is people using bots.

Never cheat on an account you are not prepared to lose.
