### ISSUE TITLE
A map where all our scans are combined.

### ISSUE THREAD

**Issue by Ezoteric** [mchristopher/PokemonGo-DesktopMap#802]
Is this possible ? if so, pretty please :D

**Comment by NickIxo** [comment]
As long as you are using the same google API key all your scans should show up on every window.
At least this is how it has worked for me since the beginning, and now.

**Comment by Ezoteric** [comment]
yeah, well even that doesnt work for me anymore :( worked fine before the "outage" but with the new versions just doesnt do it.

BUT i was aiming to a map that combines all scans of everyone :) saves you to do the same area ;)
