### ISSUE TITLE
5th/6th accounts stuck at "waiting"

### ISSUE THREAD

**Issue by NickIxo** [mchristopher/PokemonGo-DesktopMap#803]
So I currently have 4 accounts scanning just fine, however my 5th and 6th get stuck at waiting.
Additionally, if i log out of all accounts and try to log into 5th and 6th by themselves, they remain at waiting.

Is there something in the code that is not making room for more accounts that I can change? 
I have also tried on a separate computer and the issue remains. I would have thought IP related, but given that they still won't work even when they are signed in alone, i'm not sure how valid that is.

Let me know any of your thoughts.

**Comment by ommalin** [comment]
did u just make the accounts?
have u logged into the accounts and accepted the terms?

after a uppdate they did u now have to log into each account and accept the terms inside the game ( or use another python scipt to do it automaticly ) :)

if thats not the problem then i dont know :/

**Comment by ShadowSCI** [comment]
You also have to catch the first pokemon (Starter) in each account as of August 8th.  That's what I'm assuming my problem is, so working on that now as well.

**Comment by NickIxo** [comment]
Okay, I did what Ommalin said but wow @ needing starter. will try that.

**Comment by lfctan** [comment]
Hi guys can I know what if I use my real account?Can I disable it because I scared being ban?

**Comment by NickIxo** [comment]
Nobody can know but niantic.  I wouldn't use your real account.

**Comment by lfctan** [comment]
No what I mean is can I stop it?

**Comment by long-horse** [comment]
How did you get more than one account? Did you shift click the task bar icon or is it all in the same window?

**Comment by NickIxo** [comment]
@long-horse you just click your shortcut and it opens a new instance every time. Rarely, i have had some windows close when logging in (last time i had 2 windows randomly shut down)
@lfctan I think that if you have already used your main account for scanning, it depends on whether or not niantic is doing any sort of "flagging" in preparation for ban waves, as companies sometimes do.
If they are not currently flagging anyone, then I would simply switch your scanner account ASAP. If they are flagging this early, then I would say no. But again this obviously relies on information only someone deep in niantic would know.
