### ISSUE TITLE
Mobile Access Not Enabled

### ISSUE THREAD

**Issue by winhhh** [mchristopher/PokemonGo-DesktopMap#804]
Hey, no matter what I do, or try, clicking "Toggle Sharing" doesn't enable the Mobile Access...
Any one else had this issue and/or know a fix?

**Comment by mitchellnec** [comment]
im not a pro but try to help, make sure your key is a browser key, if that not helped i really dont know never had a problem with it. only when i made also a wrong key

**Comment by 4esterfield** [comment]
@mitchellnec - I've the same problem. Server Mode was enabled. More detail I've wrote in [#798](https://github.com/mchristopher/PokemonGo-DesktopMap/issues/798) with error from PC console and mobile browser console (firefox)

**Comment by winhhh** [comment]
Nothing even happens when I click Toggle Sharing... No QR code, nothing
