### ISSUE TITLE
Map not working

### ISSUE THREAD

**Issue by JacobMcNab** [mchristopher/PokemonGo-DesktopMap#806]
I downloaded and installed the app but when I login it just shows the map with no pokemon, pokestops, or gyms. It says waiting at the top.

![screen shot 2016-08-09 at 8 15 11 pm](https://cloud.githubusercontent.com/assets/15043602/17540783/178df128-5e6e-11e6-9961-7f2335b82e96.png)

**Comment by coconutboy6** [comment]
I have exactly the same problem on my Mac.

It used to work well on the previous versions (before the API changes), but now it shows nothing, even the green circles are not working.

**Comment by pokemonfan22** [comment]
What program did you use, to open the app?
I can't open it because none of my current programs on my mac are suitable for opening the pokemon map

**Comment by JacobMcNab** [comment]
Pokemonfan22, you have to go to your preferences > security and allow 3rd party programs

**Comment by avogabo** [comment]
I hace the same problem, "waiting"
