### ISSUE TITLE
Lured pokestops not showing properly

### ISSUE THREAD

**Issue by rnicolas7** [mchristopher/PokemonGo-DesktopMap#810]
the application was running properly on Mac OSX, suddenly the lured pokestops doesn't work nor show properly on the map.
If i set the scan to follow the marker, it works for a min and then it goes back down. Has anybody else faced this issue?

**Comment by rnicolas7** [comment]
I can confirm this is an issue. its definitely not working for me anymore, i even tried it on another laptop

**Comment by KeiPii** [comment]
I'm having the same problem. Everything was running smoothly approx. 7 hours ago.

**Comment by rnicolas7** [comment]
Well at least some pokemons still appear. i guess development will need to work out a fix. they have been very generous with us

**Comment by Alexfreeskier** [comment]
I can confirm this issue, too. 7 hours from now on however everything worked proper. Now almost no lured pokestops on the map and not as many Pokemon then before (even outside scan radius).

**Comment by zaqrwe** [comment]
Lured pokestops show for a 5-10 seconds(with a pokemons) and then dissapear. Cycle repeats every 5 minutes. Maybe Niantic changed something again due their tracking system tests?

**Comment by rnicolas7** [comment]
Yes, i reckon so. I hope the developers won't have a real hard time fixing this.

**Comment by Thunder5765** [comment]
Same here. lure pokestop show when it scan first circle. after second circle scan all lure pokestop dissapear.

**Comment by rnicolas7** [comment]
Looking at the issue, from a technology perspective - the lured pokestop used to "push" information regarding what pokemon is next to it. However, right now the lures only appear when the bot is passing next to it. I'm afraid its not as simple as i originally thought.

**Comment by zaqrwe** [comment]
@rnicolas7 but app could at least keep pokestop as lured until next bot pass. It would be less confounding I think.

**Comment by dualshote** [comment]
Same problem here :/

**Comment by abuch47** [comment]
mine still works especially if I scan that area. Time on lures doesnt work though. 

Doesn't always load lures outside of scan zone but within map view though.

**Comment by Alexfreeskier** [comment]
The main problem is that the wohle day after the update I get notification of Pokemon that where far far away from my scan radius (like merging other scans from different users) which was pretty cool. Now it again just shows the scanned radius (even without lured Pokestops) which is pretty unhelpfull if there are just 2 Pokemon left in your Pokedex and you like to find them.
I can't understand why most of the people here don't bother? Are you so undemanding?? Can't help it..

**Comment by rnicolas7** [comment]
I don't know yet if this issue is acknowledged by the developers with intention to fix it. I hope they do though!

**Comment by dualshote** [comment]
No fixe ? :/
