### ISSUE TITLE
Too many connections issue

### ISSUE THREAD

**Issue by ap2s2k** [mchristopher/PokemonGo-DesktopMap#811]
When im on mobile and I try to scan new areas, I would consistently get this message Too many connections! The tunnel session '----------' has violated the rate-limit policy of 20 connections per minute. Please decrease your inbound connection volume or upgrade to a paid plan for additional capacity. "

What can I do to be able to use this on mobile without having that problem?

Now my knowledge and technical expertise is pretty bad. The most I know how to do is download the .exe file and install it.

any help is a appreciated

**Comment by seiferfury** [comment]
Pretty sure this is an issue with your ISP (maybe your ISP limits connections going to you, possibly to block torrent connections or similar services). It is even described on your error message.

**Comment by JMHendon** [comment]
@seiferfury - Actually, I'm pretty sure it's an error message from Ngrok.io, and not from the ISP.  I've been experiencing the same issue for a few days but also don't know how to fix it.

**Comment by justinblayney** [comment]
it is a ngrok.io error, i get it to,  it says you have gone over your max of 20 connections per minute  for ngrok.io, please upgrade to a paid account

**Comment by ap2s2k** [comment]
It seems like people are suggesting port forwarding.

**Comment by justinblayney** [comment]
it only seems to happen to be when I am on the road and using the mobile map,  then trying to move it al over the place to the perfect spot. If I just wait a minute it resets and is fine.
