### ISSUE TITLE
Soft IP Ban for multiple threads

### ISSUE THREAD

**Issue by abuch47** [mchristopher/PokemonGo-DesktopMap#812]
So I was running between 60-90 threads and all of a sudden map data disappeared due to IP ban.

Nearby pokemon would be empty on WIFI and populate on mobile data.

Was confirmed on reddit to be happening but not sure if due to so many threads or a general ban at a certain time of day.

Only lasted 15 minutes but the IP is surely blacklisted now.

**Comment by Shogunz1** [comment]
It's focused on the excessive use of bots, accounts on a single ip. Mostly bots though. I mean if you're running a crap load of accounts I would expect someone from Niantic to notice. Common sense. 

Saw this from a botter testing:

'Running more than 50 Accounts for 5 minutes will get your IP blocked.

Stopping all connections (or possibly going back below 50?) to PoGo serers will allow you to resume again within 30 minutes, but you'll get blocked again if over the account limit'

God that's a lot lol.

**Comment by abuch47** [comment]
Yeah I agree but others are saying its happening with 10 current scans and also at a certain time stamp.

I don't have the skills to run a custom setup which is why I'm using this git, but need many scans to hit the rare spawns in my area
