### ISSUE TITLE
waiting

### ISSUE THREAD

**Issue by raysin21** [mchristopher/PokemonGo-DesktopMap#813]
i cant get the map to operate it just keeps saying waiting, i tried using my account and my brothers, i done the javascript api already, anyone know what to do?

**Comment by BanzaiBonsai** [comment]
You have to log in with the accounts you use to scan and catch one of the starters for it to work. They changed this about a week ago.

**Comment by mg6101** [comment]
You have to create a secondary account, then log into that account on your phone, catch a starter, then log into that account on the app. Then you can go back to your main account on your phone and leave the secondary account just for scanning. This way you don't get your main account banned.
