### ISSUE TITLE
Loading, please wait...

### ISSUE THREAD

**Issue by endym1on** [mchristopher/PokemonGo-DesktopMap#814]
I'm stuck at "Loading, please wait..." screen. I'm using Windows 7 and PTC and followed every step in instructions. Why doesn't my map work?

**Comment by mg6101** [comment]
Have you logged into this PTC account on your phone and caught your first pokemon? Niantic servers drop all requests from accounts that haven't caught a pokemon yet.

**Comment by osnoser1** [comment]
![image](https://cloud.githubusercontent.com/assets/1179744/17565420/636089a2-5f05-11e6-82f1-847ee32a32e8.png)

**Comment by Heinyy** [comment]
I got the same error on 2 of my PCs and got a third one working. With your screenshot I pretty sure the problem is in the Path. 

You're name seems to be Alfonso Andrès I bet. That è is the problem. I got a é in both of my non working and no one in the one who work.

All we need is a option too choose the path of installation

**Comment by osnoser1** [comment]
Yes! I had a similar problem years ago programming in Python!
I had not thought that that was the problem.
![image](https://cloud.githubusercontent.com/assets/1179744/17574904/f7889b56-5f32-11e6-8cb8-07df51d4624d.png)

**Comment by Heinyy** [comment]
I'm not a dev. Can't find a way to make it working : /

**Comment by osnoser1** [comment]
@Heinyy Did you notice that the image of my previous message, i changed the route and gives the same error?

**Comment by Heinyy** [comment]
I know, can reproduce. I'M pretty sure path is forced during installation somewhere in the code.

We'll need to wait an update for that or create a new session in your PC.

**Comment by endym1on** [comment]
> You're name seems to be Alfonso Andrès I bet. That è is the problem. I got a é in both of my non working and no one in the one who work.
You're right, I have an "Ł" in my name.

**Comment by tufuwood** [comment]
https://github.com/mchristopher/PokemonGo-DesktopMap/issues/742

**Comment by Heinyy** [comment]
Yes, thx but no. I will not create a new user/session to make one apps work.

But you confirm that there is a problem with non english caracter and that need a fix

**Comment by osnoser1** [comment]
I really think that is the encoding 'utf-8' python 2.7. :unamused:
