### ISSUE TITLE
Scanner taking long time to scan.

### ISSUE THREAD

**Issue by bearmannn** [mchristopher/PokemonGo-DesktopMap#816]
Hi, 

I am fairly new to coding as well as GitHub so I won't understand all too much but it appears that my desktop scanner takes very long to scan areas now. Yesterday a whole 1 KM area would be scanned in seconds now it takes about 10 seconds per every 100 meters. 

Any help or ways to fix this?

**Comment by EternalHD** [comment]
Following.....

I have noticed this problem today, last night it was fine checked it again this morning now exactly the same problem as op.

**Comment by rsteagall** [comment]
Is #820 similar to what you are seeing?  I think it is.

Sounds like Niantic has reduced the redius for which pokemon can be seen?

**Comment by christig** [comment]
I'm experiencing this issue as well. Could it have something to do with the "sightings" update noted in this [article](http://www.gamenguide.com/articles/37689/20160810/pokemon-go-latest-news-release-date-update-what-the-new-sightings-feature-needs-to-succeed.htm) ?

**Comment by DatN3xus** [comment]
Niantic limited the requests to only one per 5-10 seconds; if an application requests more often, it gets empty results so there is no workaround for this limitation. That's the reason, why scanning is taking more time now.

**Comment by rsteag** [comment]
I have 2 live maps running with different accounts.  The map points are of course different, but the radius seems to be very small.  So, are you sure it's a request rate or are they limiting the returned results by area?
