### ISSUE TITLE
What program do I use on mac computer?

### ISSUE THREAD

**Issue by pokemonfan22** [mchristopher/PokemonGo-DesktopMap#818]
Hi people,

I've downloaded the pokemon go map, but I can't get in on the actual app. My computer does apparently not have a program that is suitable for the app? What do I do? Can I just go into google maps on the internet or what?
I've went to the app store on my computer, but there is no program, that can open the app with the pokemon map!
I really want this to work, so if anyone could help me, I would be very thankful!

**Comment by MrAwesomers** [comment]
Have you installed python?
