### ISSUE TITLE
Pokestops not showing as lured

### ISSUE THREAD

**Issue by Raazk** [mchristopher/PokemonGo-DesktopMap#819]
I have the marker settings to Pokestops on and show only lured. Its not showing any of the lured pokestops around. When i put it to showing all pokestops it shows all pokestops but the lured ones arent lured on that setting either...

**Comment by CtrlasAltas** [comment]
Same here.

**Comment by robertybob** [comment]
This issue has been opened a number of times now, why not add your comments to an existing one?
