### ISSUE TITLE
Modify notification sound, duration

### ISSUE THREAD

**Issue by AGuyWithAHat** [mchristopher/PokemonGo-DesktopMap#821]
Would like to modify the notification sound to something loud, and more specifically something that can repeat until it is interacted with.  Is this possible?

**Comment by pdevacc** [comment]
If all you want to do is replace the notification noise, the file itself is called ding.mp3
It can be found in the folder you installed this on under /resources/app/map/static/sounds

If you replace this file with another mp3 of your choosing and rename the new file to ding.mp3 it will function as the new notification noise. (Note that you will have to restart the mapping program for this to take effect).

I'm not sure if there's a max limit to how long the mp3 can be, but you can try just picking something super long. As far as I know there's no way to make it loop right now.
