### ISSUE TITLE
Javascript issue?

### ISSUE THREAD

**Issue by orchid666** [mchristopher/PokemonGo-DesktopMap#822]
Im on OSX, when i launch the app, google maps shows for half of a second then i have this message:
"This page didn't load Google Maps correctly. See the JavaScript console for technical details."

**Comment by Alexfreeskier** [comment]
I got the same problem on windows 7. After updating Java it now stucks in Loading screen? On windows 10 everything works fine. Anyone any idea?

**Comment by MrAwesomers** [comment]
Java and JavaScript are not the same thing. I'm not sure if this is the right answer, but I betting my money you didn't click the big green "ENABLE JAVASCRIPT API" on the google maps api key page. I might be wrong but if you don't know what button I'm talking about, this will be the solution to your problem.

**Comment by orchid666** [comment]
I dont know that button :) Is it with the key? I can't find it :(
