### ISSUE TITLE
Ban ?

### ISSUE THREAD

**Issue by Faiild** [mchristopher/PokemonGo-DesktopMap#824]
Could the app in any way be concidered as a bot and result in an IP ban ?

**Comment by BlackFeatherXXV** [comment]
i think it may be. Because the scanner is not picking up any pokemon around me anymore and while my game is connected to my wifi there are no pokemon spawning in game. But if i use my phones data and restart the app there are pokemon spawning again.

**Comment by Faiild** [comment]
Were you using multiple account ?

**Comment by BlackFeatherXXV** [comment]
No just running one account to scan with a dummy trainer account. It seems to be working again so im wondering if it was a soft ban

**Comment by zaqrwe** [comment]
I'm playing on Nox and using different account to scan. Today morning I noticed pokemons don't show unless I restart Nox. But also when I let my avatar in one place for few minutes(transferring pokemons) the pokemons appeared after maybe minute

**Comment by SolutionNine** [comment]
Mine is working fine.

**Comment by abuch47** [comment]
@BlackFeatherXXV  were you gps spoofing or botting?

because thats crazy they soft banned you for 1 account.

**Comment by BlackFeatherXXV** [comment]
nope just sitting at lures
