### ISSUE TITLE
Not scanning after changing location

### ISSUE THREAD

**Issue by ferdblabla** [mchristopher/PokemonGo-DesktopMap#828]
I was trying to change a few locations to scan the pokemon nearby for those area. It works well for the first few changes but it stop scanning after five or six time of location changing. Then i will need to restart the whole software to make it work again. Please help

**Comment by khloro** [comment]
I have the same experience also its missing some pokemon i see while i am logged in. Yesterday everything was working well did the make changes to the API? Please note also the alert stop working after a time. When i restart the app the alerts work for a while .
