### ISSUE TITLE
Blank Map, catching first pokémon doesn't resolve

### ISSUE THREAD

**Issue by ugiketo** [mchristopher/PokemonGo-DesktopMap#830]
I'm aware of the other issues and have tried to resolve the steps using what worked for others. Unfortunately, it didn't work for me. Here are my error logs:
`Python server started!
main.html:173 Got open express port: 8001
main.html:173 Express server started!
main.html:158 server up: http://localhost:8001
main.html:274 MAP: Uncaught TypeError: Cannot read property 'setMapTypeId' of undefined
main.html:168 2016-08-10 14:46:14,217 [ search_worker_0][      auth_ptc][    INFO] PTC User Login successful.
2016-08-10 14:46:14,218 [ search_worker_0][      auth_ptc][    INFO] Request PTC Access Token...
main.html:168 2016-08-10 14:46:14,391 [ search_worker_0][      auth_ptc][    INFO] PTC Access Token successfully retrieved.
main.html:168 2016-08-10 14:46:14,403 [ search_worker_0][        pgoapi][    INFO] Creating a new direct request...
main.html:168 2016-08-10 14:46:14,403 [ search_worker_0][        pgoapi][    INFO] Adding 'GET_MAP_OBJECTS' to RPC request including arguments
main.html:168 2016-08-10 14:46:14,404 [ search_worker_0][        pgoapi][    INFO] Execution of RPC
main.html:168 2016-08-10 14:46:15,319 [ search_worker_0][        pgoapi][    INFO] Cleanup of request!
main.html:168 2016-08-10 14:46:15,322 [ search_worker_0][        search][   ERROR] Search step 1 map parsing failed, retyring request in 10 seconds
main.html:146 Error getting location, trying second provider PositionError
main.html:148 Found location [41.9742,-87.7526] by ipinfo.io
main.html:168 2016-08-10 14:46:25,336 [ search_worker_0][        pgoapi][    INFO] Creating a new direct request...
main.html:168 2016-08-10 14:46:25,336 [ search_worker_0][        pgoapi][    INFO] Adding 'GET_MAP_OBJECTS' to RPC request including arguments
main.html:168 2016-08-10 14:46:25,337 [ search_worker_0][        pgoapi][    INFO] Execution of RPC
main.html:168 2016-08-10 14:46:25,469 [ search_worker_0][        pgoapi][    INFO] Cleanup of request!
main.html:168 2016-08-10 14:46:25,469 [ search_worker_0][        search][   ERROR] Search step 1 map parsing failed, retyring request in 20 seconds
main.html:168 2016-08-10 14:46:45,487 [ search_worker_0][        pgoapi][    INFO] Creating a new direct request...
main.html:168 2016-08-10 14:46:45,487 [ search_worker_0][        pgoapi][    INFO] Adding 'GET_MAP_OBJECTS' to RPC request including arguments
main.html:168 2016-08-10 14:46:45,488 [ search_worker_0][        pgoapi][    INFO] Execution of RPC
main.html:168 2016-08-10 14:46:45,619 [ search_worker_0][        pgoapi][    INFO] Cleanup of request!
main.html:168 2016-08-10 14:46:45,619 [ search_worker_0][        search][   ERROR] Search step 1 map parsing failed, retyring request in 30 seconds
`
I've been watching issues:
https://github.com/mchristopher/PokemonGo-DesktopMap/issues/823
https://github.com/mchristopher/PokemonGo-DesktopMap/issues/789
https://github.com/mchristopher/PokemonGo-DesktopMap/issues/800
https://github.com/mchristopher/PokemonGo-DesktopMap/issues/779

None of these seem to solve my problem.

I've tried a new API key, I've tried logging in with the same google account and catching my first pokemon, i've restarted the computer, and I've copied over the latest files in the map folder. What else can I do to resolve this?

**Comment by jns123** [comment]
Having the same problem. Still not working after catching my first pokemon... Please help with this

**Comment by ugiketo** [comment]
Updated, still not seeing anything.
