### ISSUE TITLE
[Suggestion] Ability to export Pokestop and Gym Coords

### ISSUE THREAD

**Issue by eyl327** [mchristopher/PokemonGo-DesktopMap#831]
I would like the ability to get a file with all of the Pokestops and Gyms on the map in a .csv, excel, or .kml for importing into a google map in order to have a static map without running the application.

With a different map, I was able to copy the kml data from the source code, but this one doesn't display it. I would like if someone could help me edit the code to get that data, or if the creator could add a feature to do that.

Thank you.

**Comment by pdevacc** [comment]
I've been looking around for a way to export the scanned pokemon to run an analysis of the spawns, it seems that our problems are somewhat related. I'll keep you updated if I find anything; I've gone through a lot of the individual files without any success,

**Comment by ShinigamiSama13** [comment]
There is a .db file in AppData\Roaming\pokemon-go-map. I've been converting that to .csv files and importing it into Google Earth.

**Comment by pdevacc** [comment]
I'll look around, however, I'm running this on ubuntu. Thanks for the heads up, that's definitely a good lead.

**Comment by eyl327** [comment]
Thank you for the response. It seems like it will work. Can you help me figure out how to convert the .db to .csv?

**Comment by ShinigamiSama13** [comment]
@eyl327 I've been using DB Browser for SQLite to convert the .db to .csv. It outputs the gyms and the pokestops as separate .csv files.

**Comment by eyl327** [comment]
@ShinigamiSama13 Thank you for your helpful suggestion. It worked!
