### ISSUE TITLE
Help: Pokestops and gyms showing but not pokemons

### ISSUE THREAD

**Issue by Discouraged** [mchristopher/PokemonGo-DesktopMap#837]
I've been trying to fix this for a few days now but pokemon aren't appearing on the map.
I made a PTC account and accepted the Terms and Conditions and also caught my first pokemon. I also have a google maps key but still, only pokestops and gyms are showing. If anyone reads this please reply with a helping answer.

Image: https://gyazo.com/227f28962831dca3e877bb7806946630

**Comment by Vulcaiiin** [comment]
Can't help you to resolve this, I had the same issue and I made another google account instead of the PTC and it worked.
