### ISSUE TITLE
Not see lured pokestops and slow scanning

### ISSUE THREAD

**Issue by ShaguaRs** [mchristopher/PokemonGo-DesktopMap#838]
I don't see lured pokestops (it show in one moment when field is already scanned) and scanning for pokemons are too slow (i have set 3 radius). This is too small area but in higher radius settings scanning stuck when end for 15min (radius 7). Please change this like before Niantic change API, it works much better.

**Comment by MidKnightReaper** [comment]
They can't just increase the scanning speed, Niantic changed the Default scanning speed within the API to 10 seconds and that's as fast as it can go. Try running multiple instances of the app with a scan radius of around 5. I have found that is a decent balance between scan speed refresh and area coverage. But for now please close this issue.

**Comment by joecool6101** [comment]
Should just add support for multiple accounts like every other app that's updated since API changes.

**Comment by zak66601** [comment]
You can have 2 open at the same time using different ptc ( doesn't always work). Why did u tell him to close it? He also asked about lured pokemon not just the sd being 10sec now
