### ISSUE TITLE
How to save pokemon shown under stats?

### ISSUE THREAD

**Issue by pdevacc** [mchristopher/PokemonGo-DesktopMap#839]
I've been poking around in the code and I can't seem to find out where the info for the spawned pokemon is stored. I can display it just fine under the stats page on the top right, but where is this info stored? I'd like to export it into a database. 

Ideally I'd do this via pokeminer, but I can't get that to work, and this works excellently and I know the data exists somewhere.

Thanks in advance guys,

**Comment by toomuchtrying** [comment]
You can get it under folder: 
..\AppData\Roaming\pokemon-go-map\pogom.db

and youe use SQLiteStudio to open it.

**Comment by pdevacc** [comment]
Any idea where it's saved in ubuntu? I'm running 16.04. I wasn't able to get it running on windows (possible incompatibilities with electron on vista? The installer always froze and crashed, but that's another issue altogether)

**Comment by pdevacc** [comment]
Found it, thanks so much for your help. 

For future reference it's in home/****/.config/pokemon-go-map/pogom.db

And can be found by going to the home directory, pressing ctrl+H and navigating from there.
