### ISSUE TITLE
App wont Open Win10 64bit release 0.7

### ISSUE THREAD

**Issue by bobsyouruncle55** [mchristopher/PokemonGo-DesktopMap#84]
Windows 10 64bit. release 0.7

Double click on the app, and nothing happens
. Tried running as admin, and various compatibility settings. Still no luck. If i go into task manager, a com surrogate appears, then quickly dissapears. am i doing something wrong?

tried all i can think of. still i cant get it to work. going crazy here

**Comment by ShawnHardwick** [comment]
I would like to just state that it works on my Win10 64-bit machine for 0.0.7.

**Comment by dipstiick** [comment]
@bobsyouruncle55 i got the same problem. second release worked just fine, after installing 0.07 it didn't. Also Win 10 64-bit.
