### ISSUE TITLE
Scanner scanning all over the place?

### ISSUE THREAD

**Issue by THwhOR** [mchristopher/PokemonGo-DesktopMap#840]
I can't control my scanner.. its like running multiple locations and not just scanning where the red location thing is.. some of the locations its scanning aren't even close to my area..? Anyone know how to fix this, and just scan the areas I want?

**Comment by pdevacc** [comment]
How is it behaving? On a fresh install the scanner scans in a hexagonal pattern scaling to a specified radius (this radius can be altered on the login screen). If the radius is large enough some of these locations will be relatively far away from you.
