### ISSUE TITLE
[Suggestion] Ability to determine how scanning works

### ISSUE THREAD

**Issue by ghost** [mchristopher/PokemonGo-DesktopMap#841]
Currently scanning are set to individual small circles going around one another, which in this case, scan areas that are irrelevant to players. Could we have a configuration where we can set scanner to scan on on a determined straight line? Begin in the middle then scan from left and right side of the first circle alternatively? This allow players to cover more relevant areas and eliminate the system from scanning unnecessary areas, which mean faster scanning.

**Comment by Pixtr** [comment]
I was just thinking abut something similar. But it does not have to be in a straight line. 
My idea was to create some file with few coordinates and the map would load it and change position after each 10 s search. Now it is possible to do it manually via "Change location" but it would be more elegant to do it automatically.
Do you think it would be possible?
