### ISSUE TITLE
[QUESTION] New scanner works beyond 30 mins?

### ISSUE THREAD

**Issue by bashford427** [mchristopher/PokemonGo-DesktopMap#843]
Hi, just trying to figure something out.  Before the API changes, the scanner seemed to "time out" after about 30 mins, and you would have to log out and restart the scan.  

Now that the scan is much slower, I run about 10 instances of the app (at locations around my area to get a faster map) at a radius of 6.  I figured the same rules applied and I would have to restart all 10 every 30 mins.

However, I set up all 10 scans around 8PM CST last night, and fell asleep.  This morning and as of right now (7:30AM CST) the map is still scanning and giving me locations.  I don't think all the scans are still active, which is curious, but 8 out of the 10 appear to still be going on.

Is there a new time limit or no time limit to the scans now?  Am i getting bad data?  anybody else experience this?

**Comment by pdevacc** [comment]
Are you using PTC or google to login? From what I've been reading google accounts time out after a certain amount of time while PTC doesn't appear to do this.

**Comment by bashford427** [comment]
You're right, the two google log ins are the ones that timed out, the others are still working over 12 hours later!
