### ISSUE TITLE
JavaScript error occurred in the main process

### ISSUE THREAD

**Issue by Facas** [mchristopher/PokemonGo-DesktopMap#845]
![javaerro](https://cloud.githubusercontent.com/assets/20973570/17594874/2866829a-5fc1-11e6-913c-fb1ce436d2dd.jpg)

So i take me google maps jaka browser api key, and enable the same.

Can anyone help me?

**Comment by ThunderVamp9** [comment]
Have you tried specifying a port number in the shortcut?

C:\Users\xxxxx\AppData\Local\pokemon\Update.exe --processStart "Pokemon GO Live Map.exe" --port 8001

Change the port number until you don't get the error. Also, be sure your router is port forwarding that port to the PC.

If you are using multiple accounts, create a shortcut separately for each and specify a different port in each shortcut.

That worked for me, I no longer get this error. YMMV

**Comment by Facas** [comment]
![error](https://cloud.githubusercontent.com/assets/20973570/17595693/6549fb1c-5fc4-11e6-94fb-c7584699922e.jpg)

So ok i put in a port which i forwarding in my router, i dont get more the java error but still doesnt running the map.

Thanks for the initial help, have any other suggestion?

**Comment by ThunderVamp9** [comment]
That would happen if your Google Maps API key wasn't working.

**Comment by abrahamnm** [comment]
You may need to enable the Google Maps JavaScript API under APIs in the Google API Console.

**Comment by david082321** [comment]
@Facas 
get api here
https://developers.google.com/maps/documentation/javascript
