### ISSUE TITLE
Map not showing anything

### ISSUE THREAD

**Issue by herpi** [mchristopher/PokemonGo-DesktopMap#847]
Hello,

I created pokemonGO account and Google Maps Key according to the guide. Then I logged in with the newly made account (also copied the key where it is supposed to be) and nothing. Basically I did everything as my friend told me to, but for me the map is not working while his is working. In the middle there is a button saying "waiting", i typed in my location and nothing shows up. Can someone help me?

**Comment by ThunderVamp9** [comment]
Sign out of your actual active PoGo account. Sign in with the PTC account you created for the map. Agree to the TOS. And play through to catching your first starter. 

Until you do those things, the account will not work.

**Comment by herpi** [comment]
Thank you! That fixed my problem! :)
