### ISSUE TITLE
[Suggestion]Exporting of Stats

### ISSUE THREAD

**Issue by pill0ws** [mchristopher/PokemonGo-DesktopMap#849]
First off, I just want to thank you and everyone on this project. I have had more fun just using this app than actually playing the game. I still wholeheartedly intend on donating once I get my funds straight (I'm a poor bastard but god damn this app is a masterpiece). I just noticed the "Full Stats" feature today and the SWEET heatmaps that it generates. This has got to be the coolest feature added ever. My only real fear is Niantic swinging their big grinch dongers around again and ruining this beautiful piece of poetically coded art. I don't hammer their servers like some others, I run one single instance of the App and all of the features added over time just make one instance all I ever really need. If they ever bust out a C&D on you, they better damn sure give some props with it.

In the event that Niantic screws up the joy that this App brings, will the heatmaps that were collected over time still be accessible? If so then ignore this suggestion. If somehow they break the ability to login at all, is it possible to store/export/save the overall stats collected by the app in a manner that they can be accessed offline? I can see a long term value in generating a Google "My Map" using this data and users could even compare notes. How cool would it be if we all could donate stats to a centralized map? None of that skiplagged lying users saying they've seen all the legendaries crap, just straight up a compilation of pure data.  So beautiful it brings a damn tear to my eye

**Comment by pdevacc** [comment]
On windows this data can be accessed under ..\AppData\Roaming\pokemon-go-map\pogom.db
On linux home/****/.config/pokemon-go-map/pogom.db (home folder, ctrl+H, config)

This file can be edited or exported and accessed however you like.

**Comment by pill0ws** [comment]
Sweeeeeet, thanks so much!
