### ISSUE TITLE
[Suggestion] Pokemon Notification Based on Filter

### ISSUE THREAD

**Issue by ShawnHardwick** [mchristopher/PokemonGo-DesktopMap#85]
As a user, I would like to receive a notification if a Pokemon is found based on a list of pokemon. As of 0.0.7, the app filters the map based on a list of Pokemon, but another separate list that the notifier can reference would allow better control and granularity. 

Although written in Python, this code base has Pushbullet notification support:
https://github.com/jxmorris12/PokemonGo-Finder

Notification platform suggestions:
-Pushbullet
-SMS
-Email
-Windows Notification

**Comment by fenixasin** [comment]
was just about to post this same info

**Comment by hassanalami** [comment]
That would be a very interesting functionality ! +1

**Comment by ShawnHardwick** [comment]
Seem like this has also been implemented here as well with the develop branch of the PokemonGO Map framework:

https://github.com/kvangent/PokemonGo-Map/tree/develop
