### ISSUE TITLE
[suggestion] She needs a feature using multiple accounts google or RTS, for faster scanning

### ISSUE THREAD

**Issue by Andez427** [mchristopher/PokemonGo-DesktopMap#850]
This program is simply a bomb. This program is perfectly coped before, but now she needs a feature using multiple accounts google or RTS, for faster scanning and every account that will scan the area to give a random color.

**Comment by rsteag** [comment]
I'd love to see some kind of solution to the limited scanning radius now.  Again... it's not a scanning time for me.  The range of which things are scanned simply isn't like it use to be.  It appears to be around 100m now?  Before the last update, it would scan about .5 mile radius or something like that.

**Comment by DaMatteo** [comment]
I too would love to see a way to scan with multiple PTC accounts from a single PC, I have a lot of accounts just sitting around that could be running scans for my API but no way for me to utilise them (Or I don't know how to! As I'm far from a pro at this sort of thing), if there is a way to do this, could somebody please let me know? Thanks!

**Comment by alangerow** [comment]
To use multiple PTC accounts, load up multiple instances of the desktop app and log into each instance with a different PTC account but the same Google Maps API Key. The results from all the individual apps will appear on each others maps. 

You can also alter the radius of the search area at the bottom of the log-in screen. It defaults to 7, which is 7 search areas in a radius from your center point. You can adjust this to get the right search area you need.
