### ISSUE TITLE
Stuck on "Loading, please wait..." 

### ISSUE THREAD

**Issue by brendoncwright** [mchristopher/PokemonGo-DesktopMap#851]
Was working fine last night, nothing has changed as far as I know. Loaded in new Google Maps Key, just to be sure. Login with Google, allow permissions, then it just hangs on "Loading, please wait..." which used to only last for 1-2 seconds at most. Anyone have any suggestions? 

![loading](https://cloud.githubusercontent.com/assets/20824691/17598726/b5178fc4-5fb0-11e6-846f-eb0e64439030.png)

Update: 

Uninstalled completely, removed all local files, rebooted, reinstalled, and used a different google account for map key and login... still same error. 

Update 2: 

I remoted in to a computer that's never had this program on it before. Installed from scratch using a virgin google account and map key. Got past "Loading, please wait..." but only to get a blank map with the status at the top displaying "Waiting" 

![waiting](https://cloud.githubusercontent.com/assets/20824691/17599609/d22618c0-5fb4-11e6-80bc-cbecad59418c.png)

**Comment by ellenth** [comment]
I have the same problem

**Comment by shersey42** [comment]
I had the same problem on Linux. It was fixed by installing python-dev and xxhash as was needed for the previous release. This can be done on ubuntu using:

sudo apt-get install python-dev
sudo pip install xxhash

**Comment by Frysinger** [comment]
Any suggestions for windows users?

**Comment by tuulioo** [comment]
I have the same problem

**Comment by fissics** [comment]
Thank you shersey42
