### ISSUE TITLE
 whether the ban for this program???

### ISSUE THREAD

**Issue by leon504** [mchristopher/PokemonGo-DesktopMap#853]
with this program my eggs hatched themselves . for it may be banned ???

**Comment by Aerokii** [comment]
Using this program at all carries the risk of the account you're using being banned.

It's heavily suggested that you use spare Pokemon Trainer's Club accounts.

**Comment by leon504** [comment]
i use google account.
I may be banned???
how to play another players with this program??they may also ban?
how to play you?you play through your primary account?

**Comment by iamrudra** [comment]
@leon504 - I think @Aerokii meant that you use another, spare account to use this application and not use your main/primary account

**Comment by pill0ws** [comment]
Do not use your main account. Make new account only for app (complete tutorial). There are still risks if Niantic gets all CIA on their ban process. Niantic does not like these kinds of Apps

**Comment by leon504** [comment]
if i one day used this program?? i have ban??Now I'm already using a different account

**Comment by pill0ws** [comment]
I doubt one day would result in ban

**Comment by leon504** [comment]
I hope so.another account you also lvl 1 ? you have a Google accounts?
I have 2 Google account 1 apple id. its normal?

**Comment by pill0ws** [comment]
you want a PTC account. Google would time out, PTC account seems to last longer. I just use 1 PTC account, I had previously setup 5 but now only use 1
