### ISSUE TITLE
OSX Python Crashing

### ISSUE THREAD

**Issue by minstrel007** [mchristopher/PokemonGo-DesktopMap#855]
Getting this after being up running for a while via PTC so it shouldn't have the 30 min issue that Google does:

Process:         Python [318]
Path:            /System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python
Identifier:      Python
Version:         2.7.5 (2.7.5)
Code Type:       X86-64 (Native)
Parent Process:  Pokemon GO Live Map [310]
Responsible:     Pokemon GO Live Map [310]
User ID:         501

Date/Time:       2016-08-11 12:54:14.525 -0500
OS Version:      Mac OS X 10.9.5 (13F1911)
Report Version:  11
Anonymous UUID:  384135D3-0D52-C90B-FC35-6E4A8D0BDA41

Crashed Thread:  2

Exception Type:  EXC_GUARD
Exception Codes: 0x4000000100000017, 0x08fd4dbfade2dead

--------------------------------------------------------------

Then if you try to refresh you get:

Error: connect ECONNREFUSED 127.0.0.1:8000
   at Object.exports._errnoException (util.js:949:11)
   at exports._exceptionWithHostPort (util.js:972:20)
   at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1080:14)

**Comment by MrAwesomers** [comment]
When you start the scanner, you get a popup that asks permission to let the python script use network connections. If you don't accept it, you get the same error as the one you posted. Python crashing seems to do give the same error as it not being able to send/receive data. 

Could you please reinstall Python (plus required packages) and test if it still crashes?

**Comment by minstrel007** [comment]
Hmm don't get a permissions popup, not sure if I ever did...

But upon re-installing Python it did run for a few hours this time, but then crapped out with the same info as above.
