### ISSUE TITLE
Is anything being worked on to expand the radius of scans?

### ISSUE THREAD

**Issue by redbone75** [mchristopher/PokemonGo-DesktopMap#856]
Is anything being worked on to expand the radius of scans?

**Comment by rsteag** [comment]
If the scan area isn't increased/fixed then this program is severely crippled. =\

**Comment by mg6101** [comment]
The scan radius is not set by any program. It is set by Niantic. If the scan speed is too slow, create multiple accounts and open them 3-5 minutes apart from each other. This will start multiple threads of the map to scan the area faster.

**Comment by rsteag** [comment]
It's not s scan speed thing at least the way I understand it.  The radius has greatly changed since about 3 days ago.

**Comment by pill0ws** [comment]
Did Niantic return the 100m scan circle? I have read on reddit similar reports though I have not yet heard from someone whom knows for sure

**Comment by rsteag** [comment]
pill0ws, it would appear so to me.  :(

**Comment by pill0ws** [comment]
One report suggested 140m circle is new update range but I am skeptical to believe that. They may have underlying mechanics to the circle, perhaps updates occur but queue previously covered areas near the 10s mark? I have certainly seen things in game reveal themselves much further away than usual

**Comment by pill0ws** [comment]
They have certainly drastically reduced spawned pokemon. Perhaps an increase to scan radius was permitable after reducing the amount of events that can occur for any one update

**Comment by rsteag** [comment]
Why is there a "Scanning Options" if Niantic appears to control this anyway?  I'm just confused about the option's purpose.

**Comment by pill0ws** [comment]
That is for the radius of the scanning pattern, not the radius of an individual update. That is how large of an area that the scanner will spiral out to

**Comment by rsteag** [comment]
pill0ws, thanks or the explanation and suggestions.

**Comment by anon2019** [comment]
how is it crippled? better than the in game options or anything out there.
