### ISSUE TITLE
[Suggestion] Current Location Mobile

### ISSUE THREAD

**Issue by halorrr** [mchristopher/PokemonGo-DesktopMap#86]
Would there be a way when using the Mobile to submit the mobile's current location to become the new centre for the map scans?

**Comment by ShawnHardwick** [comment]
I think this is a good suggestion as well. I would append your title with an [Suggestion] tag at the front.

**Comment by jameson167** [comment]
I agree this would be a great feature.

**Comment by shadowsyllvet** [comment]
To take this a step further, Would it be possible to slave the desktop app to the phones GPS so that it updates as you walk? I'm not sure it would be a good idea since it would need to constantly refresh but maybe lock the radius to 3-4 while the app is slaved?
