### ISSUE TITLE
Blank Page, Map Not Loading

### ISSUE THREAD

**Issue by SoWowMuchName** [mchristopher/PokemonGo-DesktopMap#860]
I run this app on three different devices, but one of them won't run the app properly. Whenever I load the application, it seems as though the settings page completely covers the map, since the map never shows up. I found a couple issues similar in the history, which referenced tips like redownloading the app, clearing out registry errors using CCleaner, but I personally haven't had any success. Any help would be appreciated!

![image](https://cloud.githubusercontent.com/assets/20979255/17607028/fbc2fa36-5ff0-11e6-8ee4-808b895679a1.png)

**Comment by francisalfanta** [comment]
Check your API Credentials if Google Maps JavaScript API is enabled.
