### ISSUE TITLE
Middle Button on the top just keeps showing "Waiting"

### ISSUE THREAD

**Issue by Videosaver1974** [mchristopher/PokemonGo-DesktopMap#861]
The middle button on the top bar, between logout and mobile, just keeps showing "Waiting"

Here is what I am seeing in the console:

2016-08-11 19:55:16,052 [ search_worker_0][        pgoapi][    INFO] Execution of RPC

main.html:274 MAP: Uncaught TypeError: Cannot read property 'style' of null
main.html:168 2016-08-11 19:55:16,328 [ search_worker_0][        pgoapi][    INFO] Cleanup of request!

main.html:168 2016-08-11 19:55:16,328 [ search_worker_0][        search][   ERROR] Search step 1 map parsing failed, retyring request in 40 seconds

80main.html:274 MAP: Uncaught TypeError: Cannot read property 'style' of null
main.html:168 2016-08-11 19:55:56,339 [ search_worker_0][        pgoapi][    INFO] Creating a new direct request...
2016-08-11 19:55:56,339 [ search_worker_0][        pgoapi][    INFO] Adding 'GET_MAP_OBJECTS' to RPC request including arguments

main.html:168 2016-08-11 19:55:56,339 [ search_worker_0][        pgoapi][    INFO] Execution of RPC

main.html:274 MAP: Uncaught TypeError: Cannot read property 'style' of null
main.html:168 2016-08-11 19:55:56,697 [ search_worker_0][        pgoapi][    INFO] Cleanup of request!

main.html:168 2016-08-11 19:55:56,700 [ search_worker_0][        search][   ERROR] Search step 1 map parsing failed, retyring request in 50 seconds

21main.html:274 MAP: Uncaught TypeError: Cannot read property 'style' of null
79main.html:274 MAP: Uncaught TypeError: Cannot read property 'style' of null

Also get this error when trying to rerun the app.
![pokemon sight](https://cloud.githubusercontent.com/assets/20980111/17609139/2031ab06-6000-11e6-84a3-6a16776c4f99.png)

Program is running on a friends computer with no problems.  Any help would be appreciated.

**Comment by drippybutt** [comment]
You must log into your burner account and agree to terms of service and get your starter pokemon, works 100% fine after that is done.

**Comment by Frysinger** [comment]
I just did this and it didn't work for me.

**Comment by pill0ws** [comment]
The timing of this post is interesting. Last night I had the App completely stop responding at about 2am central (which would be 12am PST). Today Niantic posted a Ban appeal site. Could it be possible the perm bans are hitting?

**Comment by pill0ws** [comment]
here is the console results

Error getting location, trying second provider PositionError
main.html:148 Found location [30.6162,-86.9219] by ipinfo.io
main.html:168 2016-08-12 14:30:50,072 [      Thread-125][           app][    INFO] Changing next location: 30.6529933248,-87.1520982037

main.html:168 2016-08-12 14:30:50,732 [   search_thread][        search][    INFO] New location caught, moving search grid

main.html:168 2016-08-12 14:30:57,404 [ search_worker_0][        pgoapi][    INFO] Creating a new direct request...
2016-08-12 14:30:57,404 [ search_worker_0][        pgoapi][    INFO] Adding 'GET_MAP_OBJECTS' to RPC request including arguments

main.html:168 2016-08-12 14:30:57,405 [ search_worker_0][        pgoapi][    INFO] Execution of RPC

main.html:168 2016-08-12 14:30:57,704 [ search_worker_0][        pgoapi][    INFO] Cleanup of request!

main.html:168 2016-08-12 14:30:57,707 [ search_worker_0][        search][   ERROR] Search step 2 map parsing failed, retyring request in 40 seconds

**Comment by pill0ws** [comment]
this is while using a PTC account after doing tutorial, when I use the google account tied to the same email however, it appears to start scanning. I will be watching to see if similar results occur with a separate account... I smell a hammer

**Comment by primius** [comment]
Solution of this problem is pointed out here:
https://github.com/mchristopher/PokemonGo-DesktopMap/issues/886
