### ISSUE TITLE
Map spawning a copy of a monster just caught

### ISSUE THREAD

**Issue by Shogunz1** [mchristopher/PokemonGo-DesktopMap#863]
Must be a bug but I had two instances yesterday where I went and captured a rare, came back, and the same rare came up again in the same location, like 10 minutes after. I then went out and nothing was there. Literally just happened to me too. Now I know not to go out if the 'coincidence' happens again but just thought I'd bring it up.

**Comment by Shogunz1** [comment]
Effin smart text...'like 10 minutes after'

**Comment by RedHerring27** [comment]
This is a bug with pokemon go, not this program. I've seen it happen a few times. A pokemon will appear, It'll expire, and, a few minutes later it will reappear. It is the same pokemon, so if you've already caught it you won't be able to catch it again.

**Comment by torantal** [comment]
I consider it a second chance bug. Had a few instances where I didn't get there in time and a few minutes later got my chance. But as RedHerring27 posted - once you caught it (or if it escaped) you won't see it again.
