### ISSUE TITLE
Stops working after a while

### ISSUE THREAD

**Issue by riquesameshima** [mchristopher/PokemonGo-DesktopMap#865]
Whenever I'm running and after some time, the application stops working, being necessary to log out and log in again.

In the log appear these messages:

![error](https://cloud.githubusercontent.com/assets/9365346/17610787/ed53f00a-6017-11e6-8370-2d38a1b34d8e.png)

**Comment by ThunderVamp9** [comment]
You're logging in with a Google account. Those time out after about 30 mins. Create a new Pokemon Trainer Club account and use that.

**Comment by riquesameshima** [comment]
Nice, thank you.
