### ISSUE TITLE
Python Quit Unexpectedly (Mac)

### ISSUE THREAD

**Issue by cflyers** [mchristopher/PokemonGo-DesktopMap#866]
Every half hour or so I get this error message and the app either crashes or stops working until I reload it. Does anyone else have this issue or know how to fix it?

**Comment by mg6101** [comment]
Which login method are you using? Google dies every 30 minutes. Switch to a PTC account.

**Comment by cflyers** [comment]
PTC is the only account I ever used

**Comment by mwoelky** [comment]
I'm getting the same issues on Mac - but only if I use Mobile Sharing. If I use Mobile Sharing after the time mentioned the server crashes and works only again after Logout/Login.

I made the countercheck to not enable Mobile Sharing and then not issue occurred.

**Comment by mwoelky** [comment]
maybe releated to #855

**Comment by mwoelky** [comment]
Hmmm, did not start Mobile Sharing but python crashed. At least it lasted longer...

`Parent Process:  Pokemon GO Live Map [9208]
Responsible:     Pokemon GO Live Map [9208]
       0x1059e1000 -        0x1059e3fff +xxhash.so (0) <181A3C9B-EAD4-3ECC-ABB4-0FF0BD49ADF6> /Users/USER/Documents/*/Pokemon GO Live Map.app/Contents/Resources/app/map/pogom/pgoapi/darwin/xxhash.so
       0x107b6e000 -        0x107b9fff7 +libencrypt-osx.so (0) <45F4D13C-0C0E-3839-B239-F6AC3B4EE79A> /Users/USER/Documents/*/Pokemon GO Live Map.app/Contents/Resources/app/map/pogom/libencrypt-osx.so`

Details:
`Process:         Python [13421]
Path:            /System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python
Identifier:      Python
Version:         2.7.5 (2.7.5)
Code Type:       X86-64 (Native)
Parent Process:  Pokemon GO Live Map [9208]
Responsible:     Pokemon GO Live Map [9208]
User ID:         501

Date/Time:       2016-08-14 11:06:48.028 +0200
OS Version:      Mac OS X 10.9.2 (13C64)
Report Version:  11
Anonymous UUID:  ************

Sleep/Wake UUID: ********

Crashed Thread:  2

...

Thread 2 Crashed:
0   libsystem_kernel.dylib        	0x00007fff918cd0c2 close + 10
1   org.python.python             	0x00000001058749d2 0x1057bf000 + 743890
2   org.python.python             	0x000000010584114d PyEval_EvalFrameEx + 8080
3   org.python.python             	0x000000010583f093 PyEval_EvalCodeEx + 1641
4   org.python.python             	0x00000001057e6796 0x1057bf000 + 161686
5   org.python.python             	0x00000001057c8f72 PyObject_Call + 101
6   org.python.python             	0x00000001057d39a7 0x1057bf000 + 84391
7   org.python.python             	0x00000001057c8f72 PyObject_Call + 101
8   org.python.python             	0x000000010580e6ce 0x1057bf000 + 325326
9   org.python.python             	0x000000010580a184 0x1057bf000 + 307588
10  org.python.python             	0x00000001057c8f72 PyObject_Call + 101
11  org.python.python             	0x0000000105842df5 PyEval_EvalFrameEx + 15416
12  org.python.python             	0x000000010583f093 PyEval_EvalCodeEx + 1641
13  org.python.python             	0x00000001058458c8 0x1057bf000 + 551112
14  org.python.python             	0x00000001058424d4 PyEval_EvalFrameEx + 13079
15  org.python.python             	0x000000010583f093 PyEval_EvalCodeEx + 1641
16  org.python.python             	0x00000001058458c8 0x1057bf000 + 551112
....
`

**Comment by mwoelky** [comment]
Updated python 2.7.5 -> 2.7.12 

Hope this helps

**Comment by mwoelky** [comment]
UPDATE: Upgrading my system python installation from 2.7.5 to 2.7.12 fixed the stability problems fully

Mac OSX 10.9.2

**Comment by cflyers** [comment]
I just tried this today and it hasn't crashed since. Thank you so much @mwoelky !

**Comment by chansters** [comment]
I see that this issue is closed but unfortunately I'm having the same problem with Python 2.7.12 on OS X 10.9.5.  Python keeps crashing every 5 minutes or so.  I'm using PTC to login, not Google.
