### ISSUE TITLE
Main account working, 2nd not

### ISSUE THREAD

**Issue by hibbovsky** [mchristopher/PokemonGo-DesktopMap#868]
When I'm logging on my main Pokemon GO account, everything seems to be fine but when I try to make new one just to use it here, I'm having this error:
[ search_worker_0][        search][   ERROR] Search step 1 map parsing failed, retyring request in 20 seconds
MAP: Uncaught TypeError: Cannot read property 'style' of null

Made tutorial, caught even two pokemons, got level 2. Any ideas?

**Comment by themagicpanda** [comment]
Possible ban.
https://www.reddit.com/r/pokemongodev/

**Comment by addui** [comment]
I am having this issue too, how did you fix this? If it is not fixed why is this closed?
