### ISSUE TITLE
[Suggestion] Alert Notification, change alert sound or send email/message

### ISSUE THREAD

**Issue by NervJMSL** [mchristopher/PokemonGo-DesktopMap#869]
Hi, it would be great if one could change the notification sound to something more personalized. I ask this because my job's ticket software uses the same sound. Also if there was an option to get an email or message alert it would be awesome to make sure you get to the place as soon as possible, specially while using the app remotely.

**Comment by Mackiiboy** [comment]
You can implement this by your own by some simple programming. 

In the pogom.db database-file, we have access to all scanned data. You can read that file, sorting out new rare Pokémons that have spawned and use your own notifcation sound. 

I can make a tutorial for this in Python next week if you are interested.

With Python, I have so far managed to read the pogom.db database-file, (2) see if there are any new rare Pokémons, (3) generate a string with Pokemon name, the long/lat-coordinate for its spawn location and the time when it will despawn, and finally, (4) send this string from Windows to my Android mobile as a push notification as well as a copy of the message to the Facebook Messenger app.

**Comment by Radaenne** [comment]
@Mackiiboy 
Any chance you can do that tutorial? This would be absolutely fantastic, I'm always devastated when i miss a rare spawn because i wasn't staring at the screen at the time

**Comment by Mackiiboy** [comment]
@Radaenne Sure, I will post a tutorial here next week when I have time.

**Comment by GrodanFreeman** [comment]
I was thinking the exact same thing last night.  Either and SMS text push or a email notification.  Then you could play as normal and just get location alerts to the things you are looking for.  This should be added if at all possible.

**Comment by phiphoe** [comment]
as i stated before i was only looking for a possibility to replace the sound without other notification... want to use a very noisy ringing sound to wake me up at night when that lapras or dragonite or charizard spawns in my village :D if anybody finds a solution for that pls tell me (no clue of programming, so i would be able to replace a file but not more^^). The tiny "ding"-sound it does currently doesn't wake me up at all even setting speakers to house-shaking-full-volume...

**Comment by NervJMSL** [comment]
Thanks, and yes. I would appreciate a tutorial if possible.

**Comment by ohiotech** [comment]
I too would love this!

**Comment by pdevacc** [comment]
If all you want to do is replace the notification noise, the file itself is called ding.mp3
It can be found in the folder you installed this on under /resources/app/map/static/sounds

If you replace this file with another mp3 of your choosing and rename the new file to ding.mp3 it will function as the new notification noise. (Note that you will have to restart the mapping program for this to take effect).

**Comment by androidfan84** [comment]
I would love to still see this tutorial posted.
