### ISSUE TITLE
Pokemon appearance is delayed

### ISSUE THREAD

**Issue by Scannn** [mchristopher/PokemonGo-DesktopMap#870]
Pokemon appear on my pokemon go sightings way before they appear on the map. This sometimes makes me find a pokemon that is far away and has like 30 seconds left before despawn.

**Comment by ManiacDC** [comment]
Turn on scanned location marker. It scans in a spiraling circle, so if you want it to re-scan areas faster, you need to lower the scan radius. 3 or 4 works pretty well.

**Comment by adrenalinexxx** [comment]
Where do you change the scan radius ? I can't find a document that shows the setting.

**Comment by ManiacDC** [comment]
@adrenalinexxx It's on the log in screen.

**Comment by adrenalinexxx** [comment]
yah i figured that out after reading another thread about scrolling down.. I'm on a 4k screen and didn't notice the scroll :)
