### ISSUE TITLE
update.exe virus/ransomware 

### ISSUE THREAD

**Issue by anon2019** [mchristopher/PokemonGo-DesktopMap#871]
Was not doing this yesterday but as of today latest version. Running on windows 10 x64 
[SquirrelSetup - Copy.txt](https://github.com/mchristopher/PokemonGo-DesktopMap/files/415227/SquirrelSetup.-.Copy.txt)

C:\Users\user\AppData\Local\SquirrelTemp\updater.exe

My anti ransoware program is seeing this as ransome ware and symantec is seeing this the following 
Bloodhound.MalPE i
http://us.norton.com/security_response/writeup.jsp?docid=2010-061410-5559-99

**Comment by vincentcox** [comment]
Can you post the hash of the file?

**Comment by anon2019** [comment]
md5: 2ea5269f97e78dcc6a6b81b25a16ff1c

**Comment by vincentcox** [comment]
https://www.virustotal.com/nl/file/194a57e9e1eec0bdc645a37dc5d67c3e75be26b58512f3bdd8009ad5cd104a56/analysis/ seems that none AV is detecting it.

**Comment by anon2019** [comment]
My Symantec was not hitting on it yesterday but not today. And so is malware bytes. I still assume its good as I'm looking at it through carbon black IR software. But its just very interesting that things have changed with it today.  I'm assuming the same but i always have to keep an eye out for the haters. Will update if i see anything strange.

**Comment by vincentcox** [comment]
Thanks for clarifying. I will keep an eye on this thread: I take security very seriously, so I appreciate every report, even if it turns out a false positive. If you see unusual traffic, feel free to report that also.

**Comment by anon2019** [comment]
No problem. Thanks
