### ISSUE TITLE
Oops! Something went wrong. This page didn't load Google Maps correctly. See the JavaScript console for technical details.

### ISSUE THREAD

**Issue by tambu22** [mchristopher/PokemonGo-DesktopMap#872]
it load the map for like 2 secs and then shows this: Oops! Something went wrong.
This page didn't load Google Maps correctly. See the JavaScript console for technical details.

console: Error getting location, trying second provider PositionError {code: 2, message: "Network location provider at 'https://www.googleapis.com/' : Returned error code 403."}
but then ound location [XX.XXXX,-XX.XXXX] by ipinfo.io

**Comment by Davidsrao** [comment]
Same problem. I actually posted this once but seems you've closed my ticket.
OS X El Capitan. Compiled from the latest source code.

<img width="1555" alt="screen shot 2016-08-15 at 22 55 19" src="https://cloud.githubusercontent.com/assets/6170811/17679383/7ce255ba-633b-11e6-80f8-30552542ee71.png">

**Comment by nats12** [comment]
I've just had the same issue. Checked the console and after the 'upserted x pokemon, x pokestops, x gyms', I get a lot of these 'main.html:274 MAP: Uncaught TypeError: Cannot read property 'getSouthWest' of undefined'. Using Windows and signed in with google if that helps.

**Comment by nats12** [comment]
FIXED - just needed to enable google maps javascript API in the dashboard.
