### ISSUE TITLE
Option for Decreasing Scan Radius

### ISSUE THREAD

**Issue by selfdisplaced** [mchristopher/PokemonGo-DesktopMap#874]
Is there a way for the Windows exe to change scanning to a smaller radius.  When I'm out walking around I don't need it scanning so far away from me.  Need it much smaller.  Maybe in the first ring that comes up.

Any way to do this?

**Comment by AVellucci** [comment]
@selfdisplaced If you scroll down on the login you'll see a setting for that already.
The default is currently 7

**Comment by selfdisplaced** [comment]
Oh geez sorry. Didn't see it on that screen.
