### ISSUE TITLE
ImportError: No module named queue

### ISSUE THREAD

**Issue by bolemeus** [mchristopher/PokemonGo-DesktopMap#877]
I get the following error when installing this from scratch.

Python: Traceback (most recent call last):
  File "./runserver.py", line 27, in <module>
    from queue import Queue
ImportError: No module named queue

Am I missing something?

**Comment by newsh** [comment]
Got the same error and landed here when i googled it.

What worked for me when running Raspbian OS:
- Updating pip from 1.5.6 to 8.1.2 `sudo python -m pip install -U pip`
- Reboot system (don't know if necessary, but only after reboot new version of pip was listed)
