### ISSUE TITLE
Suggestion: don't reset window position on logout

### ISSUE THREAD

**Issue by BenElgin** [mchristopher/PokemonGo-DesktopMap#879]
This is pretty minor, but it would be nice if the app window didn't reset itself to the center of the main monitor whenever you hit the Logout button. I normally leave a scan running on a second monitor, and every time the connection drops such that I have to logout and back in (which I assume is a server issue that we can't do anything about), I have to re-position the window back where I want it.

Thanks to everyone who's worked on this.

**Comment by MrAwesomers** [comment]
+1

Or being able to save locations to a list would be a big improvement for running multiple instances.
