### ISSUE TITLE
pokemon spawn 560 hours?

### ISSUE THREAD

**Issue by zaqrwe** [mchristopher/PokemonGo-DesktopMap#880]
Today I've got some pokemons on map, which last about 560 hours :P Somebody else noticed that? Is it application bug, or it's pokemon go bug?

**Comment by hypeislove** [comment]
Same idk whats up

**Comment by hypeislove** [comment]
I just removed my old stats page and ran the program and it seems to work fine now

C:\Users\(your user)\AppData\Roaming\pokemon-go-map

**Comment by sagabomb** [comment]
@hypeislove what should we remove under this folder? everything? thanks.

**Comment by cjhwick** [comment]
Removed everything in that folder and it cleared most, but some still remaining :/

**Comment by hypeislove** [comment]
Move or delete pogom. I think thats what its called it should be at the bottom

**Comment by anon2019** [comment]
as mentioned above



I delete
C:\Users\users\AppData\Local\pokemon
and
C:\Users\users\AppData\Local\SquirrelTemp
but i noticed my info stayed in the login boxes and such and so did the 600 hr pokemon

Then delete
C:\Users\user\AppData\Roaming\pokemon-go-map
and this cleared it up i don't think it has anything to do with nantic or if it does clearing all your stuff works fine
do this yeah baby.

**Comment by Mirx** [comment]
https://github.com/PokemonGoMap/PokemonGo-Map/issues/566

**Comment by RyusuiJL** [comment]
Has anyone else noticed that these seem to be all in the same spawn location?  I watch my neighborhood daily and all my 600hr spawns are piled together in like 4 or 5 locations.
