### ISSUE TITLE
600 Hour spawn??

### ISSUE THREAD

**Issue by hypeislove** [mchristopher/PokemonGo-DesktopMap#881]
So I've been using this tool for the last couple of days to help find pokemon on the go and its been wonderful. But now Eevee's and some other pokemon spawn in my neighbor hood spawn and say they are avaliable for 600 hours? I believe its a bug and just remove them when i see them Im just looking for verification from others here.

**Comment by zaqrwe** [comment]
I opened the same issue just minute ago :P I already checked few. When scan shows pokemon, went there and it was really in this place. But then I checked pokemon,. which was on map for about one hour and nothing was on that place.

**Comment by pill0ws** [comment]
it is interesting that this only occurs for a few pokemon here and there. I wonder if it is related to some nest changes or something like that

**Comment by Shogunz1** [comment]
Yeah I'm wondering about this too

**Comment by sallen67** [comment]
I just had this happen with a Ghastly.  I cleared him from the screen and the next time the scan came around it picked him up again at 591 minutes

**Comment by Shogunz1** [comment]
Lol same with me. A gastly.

**Comment by Regulator69** [comment]
yep just had an ekans pop up and said 591 hours, then refreshed the page and went down to 8:30 just a lil glitch in the system i guess lol no biggie

**Comment by pill0ws** [comment]
I am now curious if this is a detection method being used by Niantic for map scanners. If something will not pop up in game but will pop up on the map scanner could the query request trigger some sort of security measure? It nearly always seems to be something common/uncommon and this seemed to only start occurring today.... coincidentally perm bans have also started going out today. Could this be a dirty trick?

**Comment by anon2019** [comment]
I delete
C:\Users\users\AppData\Local\pokemon
and
C:\Users\users\AppData\Local\SquirrelTemp
but i noticed my info stayed in the login boxes and such and so did the 600 hr pokemon

Then delete
C:\Users\user\AppData\Roaming\pokemon-go-map
and this cleared it up i don't think it has anything to do with nantic or if it does clearing all your stuff works fine
do this yeah baby.

**Comment by cooler67** [comment]
It doesn't seem to work at all now. It just gets stuck on "waiting"

**Comment by Mirx** [comment]
https://github.com/PokemonGoMap/PokemonGo-Map/issues/566

**Comment by eluarca1971** [comment]
Hi, as a temporal solution: uninstall Pokemon go Live map. Don't reinstall yet, go to: C:\Users\AppData\Roaming\ there delete the Folder: "Pokemon Go Live Map" there is where the app stores the Access data and the log of pokemon located in the time. once that, reinstall the app and input your acces data (Google Key and coordinates) Note: BEFORE the uninstall be sure that you have write down at least your Google Key) I know that this is a not programming soultion, but at least that give you tme to find the real solution. I hope that this can help you.
