### ISSUE TITLE
safe to use maps, ban?

### ISSUE THREAD

**Issue by agita88** [mchristopher/PokemonGo-DesktopMap#884]
is there a risk to run maps with fake accounts on home(wifi) and view it on ngrok.io on my phone(4g). will there be a risk in main account getting banned? should i stream maps on a diffrent service like remote desktop?

**Comment by anon2019** [comment]
I use 2 different ptc accounts but they are on the same network. I would not go that far as running them on different networks. To much work

**Comment by pill0ws** [comment]
I expect some device bans will be going out to take care of scanners. That would be the easiest way to deal with all the fake accounts that exist solely for scanning. They may pull some CIA stunts and try and tie it back to the mobile device used for the tutorial but I imagine it would be difficult to know  some dudes roommate didn't just borrow their phone to do a tutorial for a fake account. It's a mobile game, if they block a home IP and a PC mac address then they chop the nuts off the bull.

**Comment by ejd59005** [comment]
I would recommend against using your home WiFi for any map scanning. Your WiFi has an IP (obviously) and when you're at home, your phone most likely is connected to your WiFi. If you've ever opened up PokemonGo on your phone while connected to your WiFi, Niantic can absolutely link the two together.  (1 being your phone which is logged into your main PokemonGo account and 2 being your WiFi IP address that is constantly pinging the server for scans.)

Like you said in your post, I use Remote Desktop on a VPS and use a Remote Desktop app on my phone to view the map as I walk around my neighborhood to spot Pokemon. 

Hope that helped.

**Comment by anon2019** [comment]
yes i get that but to much work for a game....

**Comment by sfelman** [comment]
How would they know it's not just a public wifi, like a starbucks or panera wifi for instance

**Comment by anon2019** [comment]
exactly or like my work where shit ton of people playing
