### ISSUE TITLE
Frozen Map stuck at an old location

### ISSUE THREAD

**Issue by ntomec** [mchristopher/PokemonGo-DesktopMap#885]
No matter where i reboot the app and log in, i am brought back to an old location and the map is frozen, cant see any stops or pokemon on the app, nor can I zoom out/go to another location.
Anyone know what might have caused this/how to resolve this issue? 
Thanks in advance

**Comment by cooler67** [comment]
I'm having similar problems, expect I can move the marker around. Doesn't show stops, gyms or pokemon. Not even when I put the marker downtown.
