### ISSUE TITLE
Lured pokestopes are not presented unless its in the scan redius

### ISSUE THREAD

**Issue by eitvrdt** [mchristopher/PokemonGo-DesktopMap#888]
Lured pokestopes and their Pokemons used to be presented no matter of the scanning radius,
it seems like this feature does not work anymore.

**Comment by zak66601** [comment]
I have been tryin to find a answer for this for days now. Have u tried uninstalling and reinstalling because that what i was thinking about doing?

**Comment by eitvrdt** [comment]
Reinstalled several of times, no luck

**Comment by ninebreaker87** [comment]
This is the same problem my friend and I are having. I hope it can be fixed

**Comment by tashinasydney** [comment]
+1 on this. Noticed this last night when in a place with a lot of lures.
