### ISSUE TITLE
[feature request] fast scan based on sightings

### ISSUE THREAD

**Issue by zordin** [mchristopher/PokemonGo-DesktopMap#890]
Is it possible to implement fast scan mode based on sightings?
It will just tell us that there are pokemons and what types in this area or not without sharp coordinates

**Comment by hypeislove** [comment]
You could try lowering your scan area before booting the program so it will scan and bring results faster. Change the 7 or whatever number you have to 1,2,3 and that should be faster.

**Comment by zordin** [comment]
That is not a solution! cause if you're seeking for specific pokemon, you need more than 3!
it ok to search in sightings, and if you found, search in specific place!

**Comment by zordin** [comment]
it just gives you really fast scan option!
