### ISSUE TITLE
Time/Data Limit for ngrok Tunnel?

### ISSUE THREAD

**Issue by PokeFinder** [mchristopher/PokemonGo-DesktopMap#891]
I've been using a PTC account on a Windows 10 machine for 5 days straight with the same mobile tunnel address from ngrok. Today I was suddenly unable to reach my DesktopMap, and received the following message:

"Tunnel xxxxxxxx.ngrok.io not found"

My question is this: Is there some sort of time limit or data limit associated with the ngrok tunnel?

The ngrok website is fairly vague, and the closest part on the rate plans that may be applicable says that "Connections to TCP and TLS tunnels violating the rate limit will be closed without a response." 

Unfortunately I am on the road and cannot access the machine to see if it spontaneously rebooted or the like. :(

Any information would be much appreciated!

**Comment by jareem** [comment]
Nope you probably disabled Mobile sharing without noticing, or you closed/reopened the app. Activate it again.
