### ISSUE TITLE
Full stats from 2 days ago

### ISSUE THREAD

**Issue by pill0ws** [mchristopher/PokemonGo-DesktopMap#894]
So I just noticed that "Full Stats" only displays data from within the last day. All of the heatmaps I generated a couple days ago no longer show up here. Is this DB data archived somewhere or is it overridden? I am just curious if I need to manually archive such things or if they are in some special section of the AppData for this app

**Comment by hypeislove** [comment]
Probably only have your stats set to last day.  Click options in when you are in the full stats menu
