### ISSUE TITLE
"Waiting"

### ISSUE THREAD

**Issue by donohoo33** [mchristopher/PokemonGo-DesktopMap#896]
I am successfully running this program with a PTC login.  However, I tried to make a second account to run on a different computer, and it doesn't work.  The map logs in and loads successfully, but says "Waiting" at the top instead of "Operational."  I've tried logging in with my other older account, and it works fine, but the new account doesn't work.  Created a second new account with same issue - "Waiting."

Any thoughts?

**Comment by cooler67** [comment]
I have the same problem. I even tried with a google account and a different google key, and same thing.

**Comment by xPhantomNL** [comment]
Did you accept the ToS and caught a starter with that new account? I've had the same issue, until I did both.

**Comment by cooler67** [comment]
It doesn't even work with a google account, and I made yet another ptc account and same thing. It's stuck on "waiting"

**Comment by dhyde79** [comment]
ditto, was working fine earlier, closed it down so that it wouldn't be constantly scanning my house with me paying zero attention to it and when I opened it back up wanting to head out and play, it's stuck in "waiting" mode....

**Comment by dhyde79** [comment]
looking at the logs, it appears that the following is occurring....

[code]Error getting location, trying second provider PositionErrorcode: 2message: "Network location provider at 'https://www.googleapis.com/' : Returned error code 403."__proto__: PositionErrorPERMISSION_DENIED: 1POSITION_UNAVAILABLE: 2TIMEOUT: 3code: (...)get code: ()arguments: nullcaller: nulllength: 0name: ""__proto__: ()apply: apply()arguments: (...)get arguments: ThrowTypeError()set arguments: ThrowTypeError()bind: bind()call: call()caller: (...)get caller: ThrowTypeError()set caller: ThrowTypeError()constructor: Function()length: 0name: ""toString: toString()Symbol(Symbol.hasInstance): [Symbol.hasInstance]()__proto__: Object<function scope><function scope>constructor: PositionError()PERMISSION_DENIED: 1POSITION_UNAVAILABLE: 2TIMEOUT: 3arguments: nullcaller: nulllength: 0name: "PositionError"prototype: PositionError__proto__: ()<function scope>message: (...)get message: ()arguments: nullcaller: nulllength: 0name: ""__proto__: ()<function scope>Symbol(Symbol.toStringTag): "PositionError"__proto__: Object__defineGetter__: __defineGetter__()__defineSetter__: __defineSetter__()__lookupGetter__: __lookupGetter__()__lookupSetter__: __lookupSetter__()constructor: Object()hasOwnProperty: hasOwnProperty()isPrototypeOf: isPrototypeOf()propertyIsEnumerable: propertyIsEnumerable()toLocaleString: toLocaleString()toString: toString()valueOf: valueOf()get __proto__: __proto__()set __proto__: __proto__()[/code]

**Comment by youtubesteak** [comment]
When I login to the phone app using the accounts affected, I get a screen saying "Our servers are humbled by your incredible response...." Anyone else?

**Comment by cooler67** [comment]
If you are worried about them tracing it back to your IP. Go somewhere with free wifi. Logg out of the game, and log back in with the same username
 and pass you use for the map. Accept the tos, and then close the game. Clear the data, and log back in under your normal account. The map should work then.

**Comment by donohoo33** [comment]
Thanks cooler67.  That fixed the problem.  I'd never actually used the account.  Once I did that it works fine now.

**Comment by dhyde79** [comment]
tried to do what you suggested Cooler, I get the same thing that youtubesteak does, and, mmoserverstatus.com/pokemon_go reports PTC login issues, I believe that's effecting it, as I'm logged in successfully under my (alternate) gmail account just fine....I just run on the ptc because it doesn't require me to logout and log back in every 30 minutes
