### ISSUE TITLE
Question in regards to multiple scanners

### ISSUE THREAD

**Issue by wartortle87** [mchristopher/PokemonGo-DesktopMap#897]
Been using this program for a while now with great success. I know when I run multiple tabs that all the results will populate on each window, and this has been working quite nicely.

My question is, can results from my scanners populate with the results from other people in my community using the same program? Are there particular settings to achieve this, or is it not possible?

Thanks

**Comment by hypeislove** [comment]
No its running from your computer.

**Comment by wartortle87** [comment]
@hypeislove i see, so you're saying it will only share results from the same device?

**Comment by NickIxo** [comment]
Currently yes, sharing results amongst everyone would require a server of some sort, which costs money.

**Comment by donohoo33** [comment]
Interesting, because I've seen pokemon shown in areas where I know I didn't scan before...  Yet someone did...

**Comment by NickIxo** [comment]
No, your scanner can pick up Lured pokestop pokemon from far outside your scan zone :)
