### ISSUE TITLE
Pokemon expiry time

### ISSUE THREAD

**Issue by SturgBoy** [mchristopher/PokemonGo-DesktopMap#898]
got multiple clumps of pokemon that expire in 586 hours, is there anyway to manually remove them?

**Comment by LePhantom** [comment]
Yes. Click in the pokemon, than click "Remove"

**Comment by PureMassacre** [comment]
I forget to that and when I get back on I get excited then realise it expired hours ago.

**Comment by SturgBoy** [comment]
Clicking remove works but more keep appearing, guessing this is a problem in the coding perhaps?

**Comment by Anklosaur** [comment]
Duplicate of #892 which is a duplicate of #883 which is a duplicate of #881 which is a duplicate of #880. Issue is being worked on here: https://github.com/PokemonGoMap/PokemonGo-Map Specifically here: https://github.com/PokemonGoMap/PokemonGo-Map/pull/572
