### ISSUE TITLE
Not refreshing and updating after 30min

### ISSUE THREAD

**Issue by michaelcao** [mchristopher/PokemonGo-DesktopMap#90]
It seems that this app for some reason times out after 30+ minutes of use, and no longer refreshes and updates for new pokemon spawns. I left it on for 45 minutes and came back to just see an empty map with only gyms. This can definitely make it difficult to go out into the world to catch pokemon, while your computer is at home timing out after 30min with no way of refreshing it

**Comment by ranmasaotome** [comment]
can confirm this happens to me as well, have to logout and back in for it to "refresh"

**Comment by A7IE** [comment]
can confirm the same here

**Comment by wseery** [comment]
yea, happens to me too.

**Comment by Mindezo** [comment]
Yea would be awesome if this problem get fixed

**Comment by jameson167** [comment]
Same here. 

The developer tools Network list shows the Searches initiating for the Pokemon at the proper locations but it never returns any new pokemon, only expires old ones. This means we have to remotely logout & log back in just to get an update on the existing map.

**Comment by jameson167** [comment]
Looks like MChristopher is working on a new commit that has some kind of authorization pass to prevent "timeouts" perhaps this is to solve this issue?

**Comment by mchristopher** [comment]
Sound be fixed in the latest release.

**Comment by michaelcao** [comment]
Thanks! If only Niantic was as responsive as you :)

**Comment by A7IE** [comment]
So it's fixed now? Thankyou !

**Comment by michaelcao** [comment]
Haha I think the latest release broke everything actually

**Comment by fenixasin** [comment]
Related to ISSUE #72  Merge or Close

**Comment by fenixasin** [comment]
Yea I just saw the code on this, this is looking legit and should be fixed if I read the code right.

**Comment by Dravenfilth** [comment]
Tried this last night, left the map running at home, at 7 for distance in the area I was going to, worked for about 30 min and than expired pokemon left the map and nothing refreshed. Came home to an empty map as well.

**Comment by koliha** [comment]
@Dravenfilth  Fix should be present in release 0.0.8 (which has not been released yet, hopefully soon?).

**Comment by IMNoob1** [comment]
Yes it's a known problem as people said even in pogo map, there was a commit fixing the issue so it will probably will be planted in 008 as koliha said above.

**Comment by itzgankstah** [comment]
Nice!! Crosses fingers.

**Comment by tinarazzburton** [comment]
is it possible to just make the map auto-refresh after 25 minutes or something?  Like, start the search over?

**Comment by ahartlaub** [comment]
yeah, this is still happening with latest repo.

**Comment by AVellucci** [comment]
This is a common problem for "Google Login" The request token expires after 30 minutes and as such will disconnect you from PGO servers.
If you use a PTC account it should no longer disconnect after 30 minutes.
