### ISSUE TITLE
Mobile Problems Question

### ISSUE THREAD

**Issue by LePhantom** [mchristopher/PokemonGo-DesktopMap#902]
Well, i'm trying to use the mobile version, but when i open the URL in the phone nothing occurs, only show the map and nothing else work. I need to do something else?

And a question. The map, after downloaded, what i need to do? Sorry for this stupid question, but i really dont know where i use.

**Comment by smontana** [comment]
This isn't where you log a user-error-related issue. Try and troubleshoot your own problems (i.e. google/youtube.......) because this is for issues related to the code and/or project.

**Comment by PureMassacre** [comment]
When your map needs to be reloaded after a while. This changes the URL and therefore the mobile URL you used doesn't work anymore
