### ISSUE TITLE
running concurrent scans

### ISSUE THREAD

**Issue by handskun** [mchristopher/PokemonGo-DesktopMap#904]
I have seen people posting that they are running the program more than once alongside each other and the results are appearing on the same window.
I have created multiple ptc accounts and google api keys, the results appear in the same window, but when i move the scanning location on one it stops the other from scanning (ie only one scan runs at a time no matter how many windows)
How are people solving this?
Sorry if this has been asked/solved many times,and thanks

**Comment by Yaaksa** [comment]
I would also like to know about this.

**Comment by Rawr2134** [comment]
agreed, i would like to add multiple accounts to make this faster

**Comment by Shogunz1** [comment]
this just started for me too. i dont know why. anybody know a fix?

**Comment by cpbeckner** [comment]
I use different PTC accounts but I use the same API key.  I also use a radius of 4 and scans take ~5min.

**Comment by adrenalinexxx** [comment]
where are you changing your scanning radius?

All i have is the windows exe file.  

I also run the pokemon go app that i pulled using github and running python and you set the radius in the command line.
