### ISSUE TITLE
Pokemon expired time ?

### ISSUE THREAD

**Issue by ExTraviNash** [mchristopher/PokemonGo-DesktopMap#905]
Hello !

I've had this issue since yesterday. Some pokemons are showing very high expired times. My question is are those pokemons from the future or pokemons that have already expired ? And is there anyway to fix this bug ? 

Thank you !

**Comment by jure33** [comment]
i have this same problem

**Comment by drdread66** [comment]
Same issue here. Typical expiration times are 551 hours or more. Clearly the expiration times are bogus. If there was some way to clear the local cache of discovered pokemon, that would be nice.

**Comment by pdevacc** [comment]
if all you want to do is visually clear it, they'll reset if you restart the map or if you open the stats page (top right) and click on full stats. Go back to the main map and it should be reset.

**Comment by ninebreaker87** [comment]
This happened to me too. i restarted the map but they were still there so i manually clicked on each one tat had 542 hours or whatever and deleted them, now all the ones showing up are showing proper times. Im wondering if leaving the live map open and running when i closed my laptop yesterday was the issue that caused all of them to be there when i opened it back up today

**Comment by mattrat88** [comment]
im wondering if its pokemon niantics throwing out there for us to ctach ?

**Comment by pks11** [comment]
I'm still having this problem, and there are so many ridiculously expired Pokemon on my map not that it would take forever to manually remove them all. Of course, restarting the Map and clicking on "Full Stats" didn't help me.
