### ISSUE TITLE
Map stuck on 'waiting'

### ISSUE THREAD

**Issue by abnmojo** [mchristopher/PokemonGo-DesktopMap#907]
Been running current version since published.  Been leaving it running, When I woke up this AM to check it, no pokemon were on the map and I noticed the app was 'waiting' instead of operational.  Closed the app and re opened it with a second PTC account and google API key and same thing, map not 'operational' stuck on 'waiting'.

**Comment by abnmojo** [comment]
UPDATE:  tried to log in to the actual pokemon go game with my very old PTC dummy account and got a server error, then tried my newer PTC dummy account and once logged in the map went from 'waiting' to operational.    If you have this issue with 'waiting' log in the actual game with the dummy account, it resolved it for me.

**Comment by jijetelu** [comment]
It's interesting that 3 accounts are working, 2 not ?

**Comment by tuulioo** [comment]
I´m stuck at Loading Screen ever.
