### ISSUE TITLE
Waiting...

### ISSUE THREAD

**Issue by Wasschiggy** [mchristopher/PokemonGo-DesktopMap#909]
Hey guys,

I've downloaded the newest version. Got my API Key and I could start the map. However, the map doesn't show any pokemon. The google API shows traffic so it connects somehow. I see the map but no pokemon

Any ideas? 

The console is spamming this:

Adding 'GET_MAP_OBJECTS' to RPC request including arguments

main.html:168 2016-08-14 14:21:21,424 [ search_worker_0][        pgoapi][    INFO] Execution of RPC

main.html:168 2016-08-14 14:21:21,730 [ search_worker_0][        pgoapi][    INFO] Cleanup of request!

main.html:168 2016-08-14 14:21:21,734 [ search_worker_0][        search][   ERROR] Search step 6 map parsing failed, retyring request in 30 seconds

main.html:168 2016-08-14 14:21:51,793 [ search_worker_0][        pgoapi][    INFO] Creating a new direct request...

main.html:168 2016-08-14 14:21:51,793 [ search_worker_0][        pgoapi][    INFO] Adding 'GET_MAP_OBJECTS' to RPC request including arguments

main.html:168 2016-08-14 14:21:51,795 [ search_worker_0][        pgoapi][    INFO] Execution of RPC

main.html:168 2016-08-14 14:21:52,118 [ search_worker_0][        pgoapi][    INFO] Cleanup of request!

main.html:168 2016-08-14 14:21:52,121 [ search_worker_0][        search][   ERROR] Search step 6 map parsing failed, retyring request in 40 seconds

main.html:168 2016-08-14 14:22:32,130 [ search_worker_0][        pgoapi][    INFO] Creating a new direct request...
2016-08-14 14:22:32,130 [ search_worker_0][        pgoapi][    INFO] Adding 'GET_MAP_OBJECTS' to RPC request including arguments

main.html:168 2016-08-14 14:22:32,131 [ search_worker_0][        pgoapi][    INFO] Execution of RPC

main.html:168 2016-08-14 14:22:32,456 [ search_worker_0][        pgoapi][    INFO] Cleanup of request!

main.html:168 2016-08-14 14:22:32,457 [ search_worker_0][        search][   ERROR] Search step 6 map parsing failed, retyring request in 50 seconds

**Comment by abnmojo** [comment]
sign out of the pokemon go app and log in with the dummy account, go through the initial set up and get to the 3 started pokemon and then sign out.  The map should update with 'operational' now, you can sign back in with your main account and keep on catching them

**Comment by Nbr1Sniper** [comment]
Same issue here but not a fan of needing to use my dummy account on my phone. Why does this fix work?

**Comment by dese1ect** [comment]
Nbr1Sniper it is a counter measure to the scanning apps, Pokemon Go will no longer return scans unless you've chosen a starter since you must choose a starter to play the game anyways.

**Comment by Nbr1Sniper** [comment]
Thank you!

**Comment by Nbr1Sniper** [comment]
Getting an error "Failed to get game data from server"

**Comment by ManiacDC** [comment]
Me too, I think my scanning account may have been banned.

**Comment by skielbasa** [comment]
Pretty sure it is a ban/suspension. Made a new worker account, played the account till I caught my starter, then logged in to the map with that account and it worked. I haven't tried to log in with my original worker in game to confirm the ban/suspension though.

**Comment by Nbr1Sniper** [comment]
Yup... thinking the same. Changed my email address in the banned account so I can create a new user id. Caught the starter and logging in ok now.
