### ISSUE TITLE
[Suggestion] Add authentication to ngrok tunnel

### ISSUE THREAD

**Issue by molecularswords** [mchristopher/PokemonGo-DesktopMap#91]
I love the mobile feature implemented by ngrok. In it's current state, however, it is insecure (as far as I can tell) since anyone with the ngrok link can access the webserver once started. Ngrok allows for authentication using the "--auth" option, so I request that this be implemented. From a security standpoint it would be best if authentication was enabled by default, and it could be minimally intrusive to usability by simply generating a random username and password that is displayed under the QR code when the server is started.

Thanks

**Comment by theebanka** [comment]
Are you able to load the same ngrok link more than once? For me even if I try to reload the page I get a Tunnel not found message.

**Comment by molecularswords** [comment]
> Are you able to load the same ngrok link more than once? For me even if I try to reload the page I get a Tunnel not found message.

Yes. I can access it from multiple different devices, IPs, and after reloading the page.

**Comment by theebanka** [comment]
> Yes. I can access it from multiple different devices, IPs, and after reloading the page.

Huh, that is the strangest thing! An authorization feature would definitely be nice in that case!

I might need to try a fresh install or something. Do you know if the port that the map gets broadcasted to can be changed anywhere in the code? I tried using ngrok on other ports and it seems to work fine but only the localhost:8000 port seems to have the "Tunnel not found" issue

**Comment by molecularswords** [comment]
> Huh, that is the strangest thing! An authorization feature would definitely be nice in that case! I might need to try a fresh install or something. Do you know if the port that the map gets broadcasted to can be changed anywhere in the code? I tried using ngrok on other ports and it seems to work fine but only the localhost:8000 port seems to have the "Tunnel not found" issue

I'm not sure. You can try changing the command line options in the ngrok.js file under resources/app/.

**Comment by theebanka** [comment]
Is that found under the package contents for the bundled version?

**Comment by molecularswords** [comment]
> Is that found under the package contents for the bundled version?

Yes, for release 0.0.7

**Comment by mchristopher** [comment]
Authentication requires registering with ngrok, which would require users to deal with another service. Are you running into issues with people finding the random URLs?

**Comment by ShawnHardwick** [comment]
Offering authentication could be another prompt in the Mobile feature if the user has registration with ngrok, but I think security by obscurity is the best course of action right now to have a rough implementation of a shareable link to the map. I think there could be better features/suggestions to work on.
