### ISSUE TITLE
Possible IP temp ban?

### ISSUE THREAD

**Issue by Shogunz1** [mchristopher/PokemonGo-DesktopMap#911]
I'm running a total of four accounts. One main, three others. Today I went out and saw no stops or gyms and no pokemon. I didn't have the program up or anything. Weird stuff. Never seen that before. Anyone else see a similar problem? Maybe i should get rid of one account? Was it a glitch?

**Comment by Shogunz1** [comment]
After booting up the program I noticed that I could only use two accounts now. So my main and second account seem to be ip banned im guessing.

**Comment by Shogunz1** [comment]
everything is back up. hmm im going to run my main and two theres now I heard running three is the sweet spot. Idk if it was an ip ban or just a temp bug on Niantics side. Working great now.

**Comment by Shogunz1** [comment]
I was just informed that it could just be a bug. Oh well back up and feeling good.

**Comment by jijetelu** [comment]
my 2 accounts still not working !

**Comment by cooler67** [comment]
The game will do that sometimes. If you see the stops and gyms after launching the game again, then it was just a bug.

**Comment by Shogunz1** [comment]
yeah i didnt get them back after a restart. all came back after like 10 min

**Comment by Shogunz1** [comment]
Hmm it's weird. My first acct I made up isn't working anymore. Just shows up 'waiting' at the top. I made that acct before the updates and didn't need to log in to accept the tos. Suspicious. My main acct and the two others are working fine.I wonder if I got an ip ban or not.
