### ISSUE TITLE
Adding filter to solve the time issue

### ISSUE THREAD

**Issue by shxhmy** [mchristopher/PokemonGo-DesktopMap#913]
Can we simply add a filter to solve the time issue?
For example, we all know about this:

Nidorina - #30 (Very Rare) - POISON
Disappears at 10:56:22 540h36m10s)
Location: 40.055562, -83.0475906
Exclude   Notify   Remove   Get directions

It obviously has an strange expiration time. Normal time is about 15 min or less. Then, can we just filter out the Pokemons with super long time? We already know how much time they will normally appear on the map.

**Comment by pill0ws** [comment]
Another possibly even easier solution, is add an extra command to the pop up when clicking them. Currently "Exclude" just puts that species on an ignore list but helps resolve by hiding everything. These tend to be very common spawn and that is where the clutter comes from. A "Remove All" as an alternative to outright "Ignore All" could just cleaning up the clutter super easy

**Comment by Roseleinest** [comment]
In some other tools, this " bug" have already been fixed : the pokemons with strange spawn time are not shown anymore.  I think it's a pity because they are really spawning ... 

Maybe it 's a mere coincidence, but it seems that on this special spawning points, there is more rare pokemons than anywhere else.  

-> This "bug" helped us discovering a lot of new spawning points near us. 

Sorry for my English :/

**Comment by shxhmy** [comment]
@Roseleinest 
I agree. It can be seen that pokemons are shown in some certain spots. 
However, the map of my account now has more that 50 expired pokemons. I can hardly see normal pokemons unless removing these expired pokemons, wasting lots of time. It is quite annoying now.

**Comment by shxhmy** [comment]
@pill0ws 
Remove all and start a new scan. These might be two possible and easy buttons.

**Comment by fiifth** [comment]
As Roseleinest mentioned the main application already fixed the bug so I solved it by updating the application.

This is how I did that.

1) Download the new version: https://github.com/PokemonGoMap/PokemonGo-Map/releases

2) Rename the folder 'map' to 'mapOld' in "C:\Users\[your username]\AppData\Local\pokemon\app-0.2.1\resources\app".

3) Create new folder 'map' in the 'app' folder.

4) Copy content of  pokemonGo-Map-3.1.0 (which you downloaded in step 1) in this newly created folder.

5) Copy all the files in "C:\Users\[your username]\AppData\Local\pokemon\app-0.2.1\resources\app\mapOld" and paste them in the new 'map' folder and overwrite everything. 
(Do not copy the folders of mapOld only the files)

6) copy the entire folder "C:\Users\[your username]\AppData\Local\pokemon\app-0.2.1\resources\app\mapOld\pogom\pgoapi" to "C:\Users\[your username]\AppData\Local\pokemon\app-0.2.1\resources\app\map\pogom"

**Comment by shxhmy** [comment]
@fiifth Thank you

Actually I tried to update the program by following these steps carefully, and the program seemed already updated. However, the problem still exists. I try for several times, uninstall, install and update, the problem is cannot be solved. I don't know why...

**Comment by shxhmy** [comment]
@fiifth 

Now I fix the problem by clearing the cache. Thanks for your help!

**Comment by fiifth** [comment]
Great to hear! The more complete set of instructions can be found here: #935

**Comment by shxhmy** [comment]
@fiifth Yeah I found that. Thanks for your contribution!
