### ISSUE TITLE
600 hour pokemon markers

### ISSUE THREAD

**Issue by MeDav94** [mchristopher/PokemonGo-DesktopMap#918]
A few bugged pokemon markers have a timer of 600 hours. They dont disappear upon relog. When i use the "remove", they come back after i relog. (see atchment)
![untitled](https://cloud.githubusercontent.com/assets/21037087/17663494/73998148-631f-11e6-976a-fd8631a23314.jpg)

overall, program is great, no other problems!

**Comment by FirelordPhoenix** [comment]
Please look at the other issues that are open now, everyone is having this issue.

**Comment by AVellucci** [comment]
Please follow #910 for this issue.
