### ISSUE TITLE
{Suggestion} Option to remove common Pokemon

### ISSUE THREAD

**Issue by Mohammed-Rasoul** [mchristopher/PokemonGo-DesktopMap#92]
E.g option to remove rattata, pidgey, zubat etc

**Comment by theebanka** [comment]
Currently already implemented. You just need to input the Pokemon # that you want to remove like 16 for pudgy or 19 for rattata

**Comment by valkonzero** [comment]
Can you elaborate? Input how?

**Comment by theebanka** [comment]
At the bottom of the login page you should see something like this.
![screen shot 2016-07-21 at 11 13 26 am](https://cloud.githubusercontent.com/assets/10566478/17033704/36cd56bc-4f34-11e6-85f8-683a789f6d5d.png)

**Comment by valkonzero** [comment]
I completely missed that. Thank you.

**Comment by xsharky2000** [comment]
theebanka, How do I go about finding Pokemon Go Pokemon ids?

**Comment by theebanka** [comment]
It is just their podedex number so you can use any number of Pokémon websites or just look in your Pokémon Go Pokedex and count

**Comment by ShawnHardwick** [comment]
Please this issue as it has already been implemented.
