### ISSUE TITLE
Can this app plot spawn points over time? Recommendation?

### ISSUE THREAD

**Issue by MountainDrow** [mchristopher/PokemonGo-DesktopMap#921]
I want to plot spawn points in a certain area over time, but I haven't found a function anywhere. If not this app, can someone recommend?

**Comment by AVellucci** [comment]
@MountainDrow This app has a feature to show you all the spawns it's found during the many time you've run it.

Once you start the scanner you can click on Stats > Full Stats
from there click "All Locations" for a specific pokemon and you can view all the tracked spawns for it.

**Comment by MountainDrow** [comment]
Any way to reset any previous results?

**Comment by AVellucci** [comment]
you can delete the `pogom.db` file within the `%AppData%\pokemon-go-map` location in windows.
Not sure where it's saved on Mac or Linux.
