### ISSUE TITLE
Gym leveling up immidiately after defeating the opposing team

### ISSUE THREAD

**Issue by Genek1968** [mchristopher/PokemonGo-DesktopMap#922]
Sometimes I see a gym get defeated and almost immediately its like level 4 or 5. How does a gym level up so fast without training battles ?   ( sorry the question is unrelated to the program but maybe someone here knows the reason )

**Comment by AVellucci** [comment]
once a gym is taken over, other nearby players can place pokemon in (one per user) up to about 3 - 4 pokemon. after that the gym needs to be leveled up to add more pokemon.
