### ISSUE TITLE
Pokemon GO Live Map Status = Waiting

### ISSUE THREAD

**Issue by majinclown** [mchristopher/PokemonGo-DesktopMap#924]
Hi all,

My scanner is not working, the status is not operational but waiting. 
![livemap status](https://cloud.githubusercontent.com/assets/21043483/17674160/b8785816-6324-11e6-9dfd-ee6706057ede.png)

Tried re-installing, but did not work.

**Comment by skylex77** [comment]
I got the same, this happen to me because I use a new PTC account an never login to the game, so I login to the game, choose a nickname etc, and then I log in again in the map and work :)

**Comment by majinclown** [comment]
@skylex77 Thanks, but it's not working. Made a new PTC account and done the necessary steps, but not working,

**Comment by majinclown** [comment]
[ search_worker_0][        models][ WARNING] table pokestop has no column named active_pokemon_id... Retrying, is what I get on console

**Comment by Fryhole8816** [comment]
Actually, now I see SOME accounts of mine work and some don't. Ban perhaps?

**Comment by gautamjain28** [comment]
I am facing the same issue, even after creating new PTC account. Its showing as waiting since morning and also there are few ones that are not leaving the screen - they are showing some 500+hrs for expiry and those are the only ones shown. Any idea what to do?

**Comment by AVellucci** [comment]
Have you all checked the login server statuses?
http://ispokemongodownornot.com/
looks like US logins are down for both Google and PTC

**Comment by majinclown** [comment]
@Fryhole8816 Don't think so. I have tried it with two PTC account (one made recently, logged in, caught a starter etc.) and if it was banned, then you couldn't play login with the PTC account, see pokestops, etc. The issue started happening since the 500+hrs ''bug''. @gautamjain28 It might be the servers as well @AVellucci, but I'm located in Europe so it should work fine..

**Comment by selfdisplaced** [comment]
I'm having issue as well in US the up and down site show its OK

**Comment by majinclown** [comment]
Removing the pokemon folder in roaming worked for me, issue solved

**Comment by selfdisplaced** [comment]
Now site shows PTC login is down.

**Comment by majinclown** [comment]
close

**Comment by Neoublie** [comment]
I can sign into a Pokemon Trainer account I use to play but the one I use for the map is telling me thanks for the overwhelming support, please try again later (or something to that effect)

Temp Bans?

**Comment by galaxy9999** [comment]
I have a few accounts have the same problem Try to log in through app and saw "can't retrieve data". So yes, they are banned. Can anybody teach me how to change search delay manually for this program.

**Comment by GrodanFreeman** [comment]
I have slowly been loosing accounts too.  They are catching on some how.

**Comment by monhustla** [comment]
I have the same issue, started right around the same time as this post.

**Comment by Neoublie** [comment]
Created new PTC account and issue went away. I would guess that it is a wave of bans. the way the accounts behave must be unique compared to a real player. for example the account is logged in but never captures pokemon or never accesses pokestops.

**Comment by tashinasydney** [comment]
I am not sure about the ban theory. I created a second PTC account and API key and still says Waiting. Also deleted the roaming folder first just in case. My spare google account works fine with the old api key (not sure if they ban api keys too). So the problem is somewhere in the PTC login process I think. Will just use Google while I wait it out.

**Comment by swapps** [comment]
Hi, i'm having the same issue in France.

I have tried with a new ptc account too, doens't work.

I don't know if it's related but i was using an android app (pokescanner). It was working fine until 2 hours ago, now it doesn't work anymore. doesn't show anything

**Comment by Nbr1Sniper** [comment]
Probably banned. Both of mine were banned. Won't be using this anymore. Too much worm
