### ISSUE TITLE
Scanner position moves by itself

### ISSUE THREAD

**Issue by zaqrwe** [mchristopher/PokemonGo-DesktopMap#926]
I run two scanners on two different accounts and set them coordinates. But every time the scanner which is below, moves two areas up And just did not scan areas I want. Marker is always on place where I set localization, but scanner gives a f*ck about that and scan in other place -.- Any possible solutions?

**Comment by Amitloaf** [comment]
Are you sure you didn't give access to other people who manually change the location?
Also if they use the same db you'll see both results on the same web page

**Comment by zaqrwe** [comment]
Nope, I didn't give access to anybody. I reinstalled app, didn't worked.  But it is some kind of javascript bug. I figured out how to deal with it. When second scanner was running, I manually move markers for both scanners(just a bit, maybe milimeters of first positions) and then it started to scan on proper places. I wonder if I use more scanners, must I do it after every scanner lanuch.
