### ISSUE TITLE
Where is the scanned database file ?

### ISSUE THREAD

**Issue by swapps** [mchristopher/PokemonGo-DesktopMap#927]
Do you know where is the database file ?

i would like to export the pokestops locations.

**Comment by jareem** [comment]
C:\Users\%USERNAME%\AppData\Roaming\pokemon-go-map\

**Comment by chancrescolex** [comment]
How about on mac?

**Comment by jareem** [comment]
Not on Mac, but have a look on something like ~/Library/Application Support...

**Comment by swapps** [comment]
Thanks @Jareem

**Comment by MountainDrow** [comment]
I couldn't find it under application support, any other place or maybe I'm missing something

**Comment by split21** [comment]
Some folders are hidden. You can see this file using Onyx. (Utilitaires/Visibilité on french version)
