### ISSUE TITLE
Full Stats showing future date?

### ISSUE THREAD

**Issue by NWTSCL** [mchristopher/PokemonGo-DesktopMap#928]
I notice that the Full Stats are showing last seen as a future date.

OS: OSX 10.11.6
Macbook Air laptop
PTC login
app Ver 0.2.1

![screen shot 2016-08-15 at 5 42 01 pm](https://cloud.githubusercontent.com/assets/21048240/17684369/ec318868-630f-11e6-81aa-80487e208fcd.png)

**Comment by RedHerring27** [comment]
This seems to be related to the 560+ hours glitch. From what I've seen, once the bugged Pokemon expires, the "last seen" time and date will correct itself.

**Comment by NWTSCL** [comment]
I haven't noticed that yet. Thanks!
