### ISSUE TITLE
PTC Issues? 

### ISSUE THREAD

**Issue by dhyde79** [mchristopher/PokemonGo-DesktopMap#929]
My scanner quit working, neither PTC account works, both can log into the website fine, neither has gotten an email indicating any sort of ban, but both PTC accounts are stuck in "waiting" mode, and if you try to log in with the actual client I get the blue "we're humbled by your response" screen....please advise?

**Comment by jareem** [comment]
Banned

**Comment by Nbr1Sniper** [comment]
Yup, banned

**Comment by Regulator69** [comment]
hope they are your dummy accounts yo.. lol

**Comment by nickadimouse** [comment]
The scanner is working for me, the only issue i am having with it is the fact the pokemon are staying
 on the screen and when i log out and restart it , I am still getting them stuckon my screen

**Comment by Deathstroke10** [comment]
@Nickadiomouse yeah they always stay on there for 572 hours, its a pain to remove them all

**Comment by Deathstroke10** [comment]
I know they can ban PTC but can they ban google accounts too?

**Comment by devinvb** [comment]
@Deathstroke10 Why wouldn't they?

**Comment by dhyde79** [comment]
they'll ban PTC accounts, but, I think that's part of why the google accounts automatically stop scanning after 30 minutes, it's a great ban-dodger...
