### ISSUE TITLE
Use python2 or python2.7 instead of python

### ISSUE THREAD

**Issue by marandus** [mchristopher/PokemonGo-DesktopMap#93]
Using the `python` executable to run the map server application is bad practice, because it fails on systems that have python3 and python2 installed side by side (most modern Linux distributions allow this and link `python` to `python3` by default).

So please use `python2` or `python2.7` (don't know if the latter exists on Windows, but `python2` does for sure) to make sure you run the correct version.

**Comment by dotas86** [comment]
Do I need to have python installed for this to work ordo I need it just to modify it?

**Comment by marandus** [comment]
I have no idea what you comment has to do with this issue, but on Linux/OSX you need to have python 2.7 installed and symlinked to the python executable. For Windows it seems to be bundled in the package, so you would not need it installed. But I am not the developer, I cannot tell you exactly.
