### ISSUE TITLE
All of my accounts were banned tonight

### ISSUE THREAD

**Issue by Psykoflo** [mchristopher/PokemonGo-DesktopMap#930]
I was using 3 accounts on this tool (I know it's bad). All of them were banned tonight :-( And it doesn't seem to be a soft ban.
What about you guys?
I can create new ones of course but I think it will be now impossible to use the tool. If they ban users scanning a map so slowly, I don't see how it's possible to imagine using a workign radar.
I guess it's the end of Pokemon Go Desktop Map :(
Anyway, thanks a lot, it helped me a lot and made the game fun again!

**Comment by rejins2** [comment]
I'll keep making new accounts as they keep banning old ones #fuckNiantic

**Comment by Bbqz** [comment]
Yeah my 3 accounts have just been banned, had to make new ones... lets see how long they last x-x

**Comment by romanticheart** [comment]
I only have two accounts (one PTC, one Google) and the PTC one got banned. The Google account is still active, but with the scanning stopping after 30min-1hr I stopped using it. I just created another PTC account for now. I think the real tell will be how long it is until the next ban-wave. If it's a few weeks in between, it's not a big deal to have to make a new account for this at least until the updated tracking. But I'm one of the ones who probably won't use this much once we get working tracking back in-game, so.

**Comment by mikerudie** [comment]
I assume everyone is using made-up PTC accounts to use for this app, and not their primary account, correct? In other words, you play on your primary account, and use a fake PTC account to use this mapping app.  Will they ever be able to track your primary account, and ban it also?

**Comment by Psykoflo** [comment]
Well it appears that they can ban my IP. And it's difficult to take that risk, I don't have Dynamic IP's :(

**Comment by FirelordPhoenix** [comment]
@mikerudie That's being discussed on issue #917 .

**Comment by drippybutt** [comment]
I made 40 accounts, and use 3 at a time. Mine get banned every three days. #fuckniantic

**Comment by pill0ws** [comment]
lol, you made 40 dummy accounts on their servers. Why shouldnt they delete dummy accounts?

**Comment by drippybutt** [comment]
Oh I dont blame them for banning them, I am saying that is why I made 40 dummy accounts, so when 3 get banned, I have 37 left. Once they are all gone, I will make 40 more. :D
