### ISSUE TITLE
dont work

### ISSUE THREAD

**Issue by StiflerDog** [mchristopher/PokemonGo-DesktopMap#931]
showing the mensage "Oops! Something went wrong. This page didn't load Google Maps correctly. See the JavaScript console for technical details."
 
any tips?

**Comment by StiflerDog** [comment]
i can see the map working for 1 second before this menssage tho

**Comment by StiflerDog** [comment]
![Image of error](https://uploaddeimagens.com.br/images/000/692/292/full/erro.png)

**Comment by fiifth** [comment]
I'm guessing your google map key is incorrect. Toggle on developer tools and switch to console before logging in and you will know what went wrong.

**Comment by zaqrwe** [comment]
Also maybe you just didn't enable javascript API on API console dashboard. Had the same error till I enabled it.
