### ISSUE TITLE
Stuck at loading

### ISSUE THREAD

**Issue by DaviCode** [mchristopher/PokemonGo-DesktopMap#936]
Hi guys, i'm trying to run the PokemonGo map that I downloaded from the zip file, but after i log in the application gets stuck when "Loading please wait" appears. 
This is the terminal view
Python: Traceback (most recent call last):
  File "./runserver.py", line 11, in <module>
    import shutil
  File "/usr/lib/python3.5/shutil.py", line 10, in <module>
    import fnmatch
  File "/usr/lib/python3.5/fnmatch.py", line 14, in <module>
    import re
  File "/usr/lib/python3.5/re.py", line 335, in <module>
    import copyreg
  File "packages.zip/copyreg/__init__.py", line 7, in <module>
ImportError: This package should not be accessible on Python 3. Either you are trying to run from the python-future src folder or your installation of python-future is corrupted.
How can I solve this?

**Comment by fiifth** [comment]
@DaviCode  Which version of python do you have installed? If your version is 3.x.x pleas try removing this version and install python 2.7 (https://www.python.org/).

**Comment by DaviCode** [comment]
@fiifth i have installed both the packages, but whenever I try to uninstall with pacman -R python, 
checking dependencies...
error: failed to prepare transaction (could not satisfy dependencies)
:: gdb: removing python breaks dependency 'python'
:: libixion: removing python breaks dependency 'python'
:: libreoffice-fresh: removing python breaks dependency 'python>=3.5'
:: python-pip: removing python breaks dependency 'python'
:: python-pyparsing: removing python breaks dependency 'python'
:: python-six: removing python breaks dependency 'python'
:: python-xdg: removing python breaks dependency 'python'

**Comment by fiifth** [comment]
@DaviCode I see. Well the map.zip provided was compiled with python 2.7 so I thought that would be the problem. Only thing I can think of is removing the pokemon go map application and execute the first 6 steps before launching the newly installed pokemongo map app.

**Comment by DaviCode** [comment]
@fiifth 6 steps meaning? I only downloaded the zip and run by ./Pokemon go map etcc

**Comment by rhawley88** [comment]
Its been running for me past couple of days fine but today its stuck on waiting also haven't made any changes to program so wondering if API change again or something

**Comment by rhawley88** [comment]
ok after some trying my google account works fine but my ptc account does not i have created a new ptc account and that one works fine i've been reading that there is a possibility of a Ban wave so not sure if other account was banned or what try and log in to pokemon go with it and get failed to get game data 

with new account it is running smooth just make sure you catch your starter with new account or it won't work
