### ISSUE TITLE
Program stops scanning

### ISSUE THREAD

**Issue by xslayserx** [mchristopher/PokemonGo-DesktopMap#937]
My Desktop Map just stoped scanning for no reason. After restarting the program nothing changed. Is my PTC Account banned ?

**Comment by monhustla** [comment]
Just happened to me as well. Mine scans in solely the location the map opens on and doesn't work anywhere else when moved.

**Comment by monhustla** [comment]
Also, I can scan in a new location as long as it's in the same area as the original scan. What's weird is it's now scanning in two locations for some reason.

**Comment by xslayserx** [comment]
@monhustla  I had the same issue yesterday but now i cant scan anything ... it`s just stopped scanning

**Comment by xslayserx** [comment]
Well my Acc got banned, will make a new one
