### ISSUE TITLE
Stuck at "Waiting"

### ISSUE THREAD

**Issue by grimgm31** [mchristopher/PokemonGo-DesktopMap#938]
The app is stuck at "Waiting" and even after uninstalling and installing it will not scan my area.

**Comment by zak66601** [comment]
Yea it's ur ptc or google, one of mine is stuck at waiting, plus ever new ptc or google i made is too.

**Comment by AVellucci** [comment]
Have you launched the account and caught a starter? if you don't do so it won't be able to scan.

**Comment by ZaFwamingDwagon** [comment]
Made another PTC account. Went as far as catching a starter (and inputting a screen name) and using the new credentials worked.

**Comment by Sedare** [comment]
your accounts have been banned. Start some new ones!
