### ISSUE TITLE
Map only scans in one location, can't move location pin

### ISSUE THREAD

**Issue by monhustla** [mchristopher/PokemonGo-DesktopMap#940]
It seems to be stuck scanning in only one location. If I type in a new address or move the pin too far away it stops scanning altogether. 

Just created a new ptc account yesterday so not sure what's going on.

**Comment by monhustla** [comment]
New account doesn't work. In fact, it even pulls up the scans from my previous account.

**Comment by monhustla** [comment]
Uninstalled and reinstalled app and it's still doing the exact same thing.

**Comment by pdevacc** [comment]
Have you tried deleting the old scan files (including pogom.db) ?

**Comment by secondhandnudes** [comment]
There's a new feature in location settings called "Lock Marker" that appears to turn on by default. Is this what you're experiencing?

**Comment by monhustla** [comment]
I'm not sure how to delete old scan files. The "lock marker" feature would actually make quite a bit of sense. How would I check to see if that is on?

**Comment by monhustla** [comment]
It's very odd, I can only move pin and have it scan successfully if the previous scan is on the screen when I move it.

**Comment by monhustla** [comment]
I'm going to reinstall from git link instead of existing file on desktop and see if that works. Pretty frustrating as it's worked perfectly until now.

**Comment by monhustla** [comment]
Redownloaded from git, still same issue. Only scans in the initial location.

**Comment by monhustla** [comment]
@pdevacc how would I delete old scan files?

**Comment by monhustla** [comment]
I'd pay if someone could help me with this. I'm 3 Pokemon away from finishing the dex

**Comment by fiifth** [comment]
You could try to update your application, this might fix your problem. You can find the instructions over here: #935 .

**Comment by meisterluv** [comment]
@monhustla  

> 7 ) Go to C:\Users[username]\AppData\Roaming\pokemon-go-map and delete the file pogom.db and the folders Cache, Local Storage (solution provided by @ManiacDC). (on Mac the folder is located in /Users//Library/Application Support/pokemon-go-map. thanks to @mwoelky for posting this)
8) In case this doesn't work: delete C:\Users[your username]\AppData\Local\pokemon\app-0.2.1\resources\app\map and replace it with this 'map' folder, and repeat step 7.
