### ISSUE TITLE
Pokemon stay on the map

### ISSUE THREAD

**Issue by PugliesiPc** [mchristopher/PokemonGo-DesktopMap#942]
first of all i'm french so sorry for my english 
So I have pokemon who stay on the map like they never disappear, I try to restart the software but they are still there, and when I click on it, it's wrote about 500 hours before they disappear.
Please help me I want to fix that because actually i have fake pokemon every where on my map.
by the way : 
_ i try to click on remove but when i restart the software they appear again
_i also try to re download but it's still same

**Comment by PugliesiPc** [comment]
I use Google API

**Comment by fiifth** [comment]
Follow the instruction over here: #935

**Comment by PugliesiPc** [comment]
thank you man
now it's fix
