### ISSUE TITLE
Accounts getting banned

### ISSUE THREAD

**Issue by cooler67** [mchristopher/PokemonGo-DesktopMap#943]
Just a heads up, they are banning PTC accounts. My throw away got banned.

**Comment by HunterSnatch** [comment]
Same issue with three of my burner accounts with PTC and google. Wondering what the fix is to get it out of "Waiting" mode now. I tired to create another fake and the Desktop Map still says "Waiting" at the top. Would a change of iP address help like a VPN service? Just trying to figure it all out.

**Comment by BMWtx** [comment]
I just created more accounts and it seems to have fixed the issue for me.

**Comment by HunterSnatch** [comment]
Did you create the PTC from another iP address or the same one you've used before? Thanks for your reply!

**Comment by jijetelu** [comment]
They are getting banned quite regularly, l think like half a day, max one day, so we need to figure something out about that. Anyone any ideas ?

**Comment by cooler67** [comment]
So I first thought it was banned.. I was able to log into the account, and I even got my sister to download the game and try to get in. She was able to without issue. However, the scanner was telling me "awaiting activation" when I tried to use that account. So I don't know what was up with that.

**Comment by ejd59005** [comment]
Mine usually last about a day or so. No big deal to make another though, so I'm not really worried about it.

**Comment by HunterSnatch** [comment]
Are yopu making another PTC account or another gmail account or both? Can't seem to figure it out and get it out of "Waiting"

**Comment by cooler67** [comment]
Hunter:  The fix for the "waiting" is you have to log into the game and accept the TOS. That be easily done a free Wifi spot, like starbucks or whatever.

**Comment by HunterSnatch** [comment]
Thanks! Do you do that from your phone? Is there a way around using the device I use for my actual account? Appreciate it, Cooler67.

**Comment by cooler67** [comment]
You have to do it from your phone. They don't link it back to you. They typically just ban the account, or the IP. However, seeing as several different people can be using that IP, they typically just ban the Account. It's just safer to do it on a public Wifi network.

**Comment by starstremr** [comment]
well what i did not notice was i had been running my on my pc that downloads stuff so it is on a vpn so when they did the ban i had the vpn up. so i just tried a different connection and it is working again. So a VPN is the answer for now.

**Comment by HunterSnatch** [comment]
Legends. Thanks everyone. I used a VPN just to be careful and it's operational again. Anyone placing bets on when the next account gets banned? haha

**Comment by ejd59005** [comment]
I use anow android emulator to log in the new accounts and accept the TOS. I don't want ANY link between my phone and these crap accounts. Not rinking it. And my map runs on a vps as well.

**Comment by MorgothBauglir** [comment]
Why is it not OK for people to use this app, but everyone living in major cities is free to use Go Radar? It's still in the app store...I have friends in NYC so I went to visit. It's out of control. I can't compete with them at all...a Snorlax spawns in Central Park and hundreds upon hundreds of people are all sprinting to get it...and that's just a one example. Meanwhile people living in rural areas/suburbs are getting banned left and right for using apps such as this. I understand one uses the games API and the other is crowd sourced but give me a break.

**Comment by cooler67** [comment]
I'm going to just keep my location in one spot, vs moving it around all the time. Less likely to get noticed that way. I mostly use it now for magikarp. There is a nest a few house down from me, and they never show up on the nearby list. The only way to farm them, is to get a sound alert when they spawn.

**Comment by chun1324** [comment]
Not sure if PTC servers down or get banned. When I was trying to login with PTC account in game that used by this map before, I got a error message about server issue instead of failed to login.

**Comment by cooler67** [comment]
Servers seem to be fine.

**Comment by Mirx** [comment]
Just to pitch in some personal experience for the ban conspiracy theorists among us...

(Luckily) I haven't had any banning issues with my account.

I currently have just one worker scanning a radius of 3 when I need it. So I'm not running it 24/7 to gather database information. 

Switching between my home location and office locations is not a problem. I did start disabling search when I start to commute to make the GPS hop not instant. This morning I traveled about 50 miles, and no troubles with changing the location and multiple smaller drags and drops.

Switching between devices (I sometimes run it from my laptop when I forget to turn it on om my HTPC at home) hasn't been a red flag apparently.

Having 2 devices (app and map) on the same IP hasn't been a red flag apparently.

Having multiple overlapping GPS coordinates hasn't been a red flag apparently.

**Comment by PassyFox** [comment]
PEOPLE just please for the love of god STOP USING MUTLIPLE ACCOUNTS!!! just use this scanner with only one account and have the scanner set to radius 4 that way you have a small impact on the servers, and you are not realy attracting any attention to yourself!

**Comment by ployteabagger** [comment]
Have any of you considered using a mobile (cellphone) as a tethered connection? I have a new IP each time i use it and it reports my IP as being at the HQ for my phone provider. I'm pretty sure they won't ban that one ;-) Anyways like PassyFox mentioned. I think some people are getting a little greedy and just need to be grateful that aside from odd error, the lack of lured pokestops and the infamous 500+ glitch it is still working. I for one am certainly grateful to mchristopher. At least he didn't cave into Niantic, however a lack of update could be a sign of things to come.

**Comment by Mirx** [comment]
Don't be too sure, they ip banned the biggest mobile provider in belgium today.

**Comment by cooler67** [comment]
Looks like they go based on reports from people, if the system doesn't automatically catch them.
