### ISSUE TITLE
Getting "Error: Could not get code signature for running application" after `npm start`

### ISSUE THREAD

**Issue by just3ws** [mchristopher/PokemonGo-DesktopMap#945]
*UPDATE*: This error only occurs from source. I'm able to run the app fine from the downloadable package. Thanks.

Howdy... getting the error pasted below when I run `npm start`. I've tried blowing away the `~/.npm` and `.node_modules` and restarting but the error is consistent. I'm sure I'm doing something wrong but am not sure what it is. :)

`npm --version` ➜ 3.10.3
`node --version` ➜ v6.4.0
`python --version` ➜ Python 2.7.12
`electron --version` ➜ v1.3.3
`OS X` ➜ 10.11.6
`XCode` ➜ Version 7.3.1 (7D1014)
`brew --version` ➜ Homebrew 0.9.9 (git revision 3774b; last commit 2016-08-17)
Homebrew/homebrew-core (git revision 654a; last commit 2016-08-17)

Running checkout of master `f053274 2 days ago by Aldo Vellucci (HEAD -> master, origin/master, origin/HEAD): Updated README`

Googling the error was less than insightful. :(

Anything else I can provide that might be helpful?

```
➜  PokemonGo-DesktopMap (master) ✗ npm start

> pokemon-go-map@0.2.1 start $HOME/src/PokemonGo-DesktopMap
> electron main.js

{ Error: Could not get code signature for running application
    at Error (native)
    at Object.<anonymous> ($HOME/src/PokemonGo-DesktopMap/main.js:29:15)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at loadApplicationPackage ($HOME/src/PokemonGo-DesktopMap/node_modules/electron-prebuilt/dist/Electron.app/Contents/Resources/default_app.asar/main.js:288:12)
    at Object.<anonymous> ($HOME/src/PokemonGo-DesktopMap/node_modules/electron-prebuilt/dist/Electron.app/Contents/Resources/default_app.asar/main.js:330:5)
    at Module._compile (module.js:541:32)
  preventDefault: [Function: preventDefault],
  sender: AutoUpdater {} }
```

**Comment by gempesaw** [comment]
Hey, I ran across this same issue when trying to run from source. When I tried running `npm start` for a second time,  it threw the same error in the shell, but the app started up fine and seemed to work fine (logged in, scanned for pokemon, didn't see the 500h ones.)

The third time I ran `npm start`, it gave the error and crashed immediately; the fourth time I ran `npm start`, it threw the error and worked fine :P.

Unrelatedly, I also went into the `map` directory and did a `pip install` in there, but I don't think it mattered.

    $ source bin/activate
    $ cd map && pip install -r requirements.txt --target ./packages
