### ISSUE TITLE
How do I completely uninstall and remove everything off my mac?

### ISSUE THREAD

**Issue by MountainDrow** [mchristopher/PokemonGo-DesktopMap#946]
I want to do a fresh reinstall but everytime i delete and uninstall, there is still data from previous versions such as map sightings, preferred pokemon, etc.
Any idea how to completely wipe it off my hard drive and start fresh?

**Comment by LuckyYou** [comment]
delete the cache folder in VV

Users/YOUR USERNAME/library/application support/pokemon-go-maps/

**Comment by MountainDrow** [comment]
I can't find it under that directory, atleast not in application support

**Comment by LuckyYou** [comment]
It's in there but you're not looking directly in the library you have to go through users and your username 
/users/YOUR USERNAME GOES HERE/library
