### ISSUE TITLE
Possible Virus?

### ISSUE THREAD

**Issue by TProject1990** [mchristopher/PokemonGo-DesktopMap#947]
Today, when I opened the App, my Anti-Virus popped up saying:

Trojan: HEUR/QVM10.1.335B.Malware.Gen
Directory: Pokemon Go Live Map.exe

I tried redownloading it and reinstall it, but after installation, the AntiVirus detects it and I can't run the App. Anybody else have the same problem?

**Comment by AVellucci** [comment]
@TProject1990 This is a false-positive, you can view the VirusTotal Results here: [FAQ](https://github.com/mchristopher/PokemonGo-DesktopMap/wiki/FAQ)
