### ISSUE TITLE
Suggestion : Like PokeMesh, be able to add accounts to increase speed/range capabilities. 

### ISSUE THREAD

**Issue by SolutionNine** [mchristopher/PokemonGo-DesktopMap#948]
Probably not the right place for this. Sorry if that's the case.

PokeMesh has recently implemented an incredible feature. It allows you to login to accounts you want it to have privileges to automatically. This is much easier and faster than the "new instance" scanning.

**Comment by wartortle87** [comment]
pokemesh only allows multiple scans within a certain radius tho right? so multiple scans just increase the rate of scan within a fixed area if I understand right. With multiple instance setup im able to cover my entire (small) town with up to date tracking.

**Comment by andrewrov** [comment]
up

**Comment by SolutionNine** [comment]
@wartortle87 
I don't bother with multi scans on mesh since I use my home scanner at home.
but, with about 30 PTCs tied to it I can scan a range 7 in a few seconds.
If you are able to scan and rescan that quickly, it kind of makes multi scanning obsolete.

**Comment by wartortle87** [comment]
@SolutionNine i wouldnt say obsolete, considering with multi scanning i have an entire town scanned without having to manually click around and search, i can just trust that with all my scans range 4 and interlocking, I wont miss any spawns in my field or ever see a new scan result with less than ~9 minutes remaining. That setup _kinda_ renders pokemesh obsolete really.

**Comment by Pokemongoryan** [comment]
@wartortle87  I have absolutley no idea about this but how do you set up multiple scanning / accounts at the moment i have 1 and dont know how to add more, pls help

**Comment by SolutionNine** [comment]
@wartortle87 the difference is mobile capability. PokeDesktop has outages fairly frequently and you can't scan multis with mobile linking. 

Pokemesh, also, does it all automatically. More user friendly and you don't have to stagger time on instance loading.
