### ISSUE TITLE
Banned my PTC Accounts. New IP, still banned

### ISSUE THREAD

**Issue by ejd59005** [mchristopher/PokemonGo-DesktopMap#951]
As the title says, my PTC accounts were banned again. 

I created a new account, logged in the game via an emulator and accepted the TOS (as I always do), but still says waiting. 

I then switch my IP (thinking I was IP banned) and still says waiting. 

UPDATE: Apparently I was insta banned on my new IP. I was able to log in to PokemonGo app via Bluestacks, and accept the TOS. I closed it out to try and login the map, but it still said waiting. I figued maybe I have to catch the starter pokemon, so I log back into the game and click on charmander and the game freaks out. 

At this point I say screw it and proceed to create a new PTC account again. I head over to their website to create the account and the page is inaccessible. I switch IP's back to my main desktop IP and the page loads perfectly fine. So it would seem that within the span of about 5-7 mins, my new IP went from working just fine, to banned. 

Anyone else seeing this?

**Comment by Xrecon420** [comment]
Maybe i got the same issue. like 2 hours ago my map stopped working, It keeps saying "waiting" and i'm getting this in console.

main.html:158 server up: null
main.html:146 Error getting location, trying second provider PositionError
main.html:148 Found location [60.6745,17.1417] by ipinfo.io
main.html:168 2016-08-18 00:59:26,897 [      MainThread][     runserver][    INFO] Parsed location is: 60.6514/17.1376/0.0000 (lat/lng/alt)

main.html:168 2016-08-18 00:59:26,898 [      MainThread][        models][    INFO] Connecting to local SQLLite database

main.html:168 2016-08-18 00:59:26,900 [   search_thread][        search][    INFO] Search overseer starting

main.html:168 2016-08-18 00:59:26,901 [   search_thread][        search][    INFO] Starting search worker threads

main.html:168 2016-08-18 00:59:26,914 [   search_thread][        search][    INFO] New location caught, moving search grid
2016-08-18 00:59:26,914 [ search_worker_0][        pgoapi][    INFO] pgoapi v1.1.7 - Copyright (c) 2016 tjado <https://github.com/tejado>

main.html:168 2016-08-18 00:59:26,915 [ search_worker_0][        search][    INFO] Search step 1 beginning (queue size is 0)

main.html:168 2016-08-18 00:59:26,917 [ search_worker_0][      auth_ptc][    INFO] PTC User Login for: ********

main.html:173 Python server started!
main.html:173 Got open express port: 8001
main.html:173 Express server started!
main.html:158 server up: http://localhost:8001
main.html:168 2016-08-18 00:59:28,410 [ search_worker_0][      auth_ptc][    INFO] PTC User Login successful.
2016-08-18 00:59:28,410 [ search_worker_0][      auth_ptc][    INFO] Request PTC Access Token...

main.html:168 2016-08-18 00:59:28,716 [ search_worker_0][      auth_ptc][    INFO] PTC Access Token successfully retrieved.

main.html:168 2016-08-18 00:59:28,727 [ search_worker_0][        pgoapi][    INFO] Creating a new direct request...

main.html:168 2016-08-18 00:59:28,729 [ search_worker_0][        pgoapi][    INFO] Adding 'GET_MAP_OBJECTS' to RPC request including arguments

main.html:168 2016-08-18 00:59:28,743 [ search_worker_0][        pgoapi][    INFO] Execution of RPC

main.html:168 2016-08-18 00:59:29,285 [ search_worker_0][        pgoapi][    INFO] API Endpoint redirect... re-execution of call

main.html:168 2016-08-18 00:59:29,499 [ search_worker_0][        pgoapi][    INFO] Cleanup of request!

main.html:168 2016-08-18 00:59:29,500 [ search_worker_0][        search][   ERROR] Search step 1 map parsing failed, retyring request in 10 seconds

main.html:168 2016-08-18 00:59:39,522 [ search_worker_0][        pgoapi][    INFO] Creating a new direct request...
2016-08-18 00:59:39,522 [ search_worker_0][        pgoapi][    INFO] Adding 'GET_MAP_OBJECTS' to RPC request including arguments

main.html:168 2016-08-18 00:59:39,522 [ search_worker_0][        pgoapi][    INFO] Execution of RPC

main.html:168 2016-08-18 00:59:39,743 [ search_worker_0][        pgoapi][    INFO] Cleanup of request!

main.html:168 2016-08-18 00:59:39,746 [ search_worker_0][        search][   ERROR] Search step 1 map parsing failed, retyring request in 20 seconds
