### ISSUE TITLE
Residual pokemon on map

### ISSUE THREAD

**Issue by kla007** [mchristopher/PokemonGo-DesktopMap#952]
After I've closed the program and re-enter there appear to be some pokemon left on the map before I even start scanning. At some points it actual has a bunch of pokemon on top of each other that never leave the map.

Any way to clear cache, I guess?

**Comment by jijetelu** [comment]
yes, delete the pogom.db file in your data map (use search)

**Comment by starstremr** [comment]
did not work for me

**Comment by c350xander** [comment]
I can not find the file.

**Comment by MrWuffle** [comment]
Same here, the file was nowhere to be found.

**Comment by rainer111** [comment]
File is here. C drive: AppData\Roaming\pokemon-go-map
Thanks Jijetelu
