### ISSUE TITLE
i keep getting  these errors  keep in mind i have no idea how to code. just reporting.

### ISSUE THREAD

**Issue by crispy123** [mchristopher/PokemonGo-DesktopMap#953]
i updated the screen shot to show which ports are being used.
![screenshot 2016-08-12 06 17 56](https://cloud.githubusercontent.com/assets/21096925/17793209/44044578-656b-11e6-8106-e9d49aae1de1.png)
![screenshot 2016-08-10 02 20 58](https://cloud.githubusercontent.com/assets/21096925/17767411/8096aac4-64f5-11e6-9be8-a341a3ae2cad.png)
![screenshot 2016-08-10 02 30 21]
(https://cloud.githubusercontent.com/assets/21096925/17767412/809f82de-64f5-11e6-9c4a-8a6907376220.png)

**Comment by MrAwesomers** [comment]
Did you click the big green "ENABLE JAVASCRIPT API" button on the google maps api key page?

**Comment by crispy123** [comment]
Thing is i gave no idea how

**Comment by jareem** [comment]
It's like the port is already in use.
Close Pkm map.
Open a command prompt and type "netstat -b"
Look for a line that has "8001" in it.
Just above, you'll see the .exe using this port.

**Comment by crispy123** [comment]
mine replies to me requires elevation
