### ISSUE TITLE
The +400 hours problem will it be fixed? And consider adding TBTerra Spawntracker?

### ISSUE THREAD

**Issue by thetof91** [mchristopher/PokemonGo-DesktopMap#954]
Hello.

I just wonder if the problem with pokemons spawn and then says they despawn in +400 hours will be fixed? :)

Also have you consider adding this in any way: https://www.reddit.com/r/pokemongodev/comments/4wxteh/i_implemented_tbterras_spawntracker_into/

**Comment by Kavex** [comment]
It got fixed in the pokemon go map source code but just hasn't been updated in the Electron app bundle.

https://github.com/PokemonGoMap/PokemonGo-Map/pull/572

**Comment by Zentriert** [comment]
Support for a spawns.json file from TBTerra spawnScan would be amazing!

**Comment by linxspider** [comment]
@thetof91 @Zentriert :
https://github.com/mchristopher/PokemonGo-DesktopMap/issues/967
