### ISSUE TITLE
Possible update with the new 400+ Pokemon fix?

### ISSUE THREAD

**Issue by Shogunz1** [mchristopher/PokemonGo-DesktopMap#955]
I know you got a lot going on mchristopher but was just wondering if there is a future update with the fix coming?

**Comment by Kavex** [comment]
It got fixed in the pokemon go map source code but just hasn't been updated in the Electron app bundle.

PokemonGoMap/PokemonGo-Map#572

**Comment by Shogunz1** [comment]
k ty. just was hoping the electron app would be updated with it soon.

**Comment by linxspider** [comment]
solution is here: https://github.com/mchristopher/PokemonGo-DesktopMap/issues/967
