### ISSUE TITLE
Possible to implement a search path?

### ISSUE THREAD

**Issue by cfsterpka** [mchristopher/PokemonGo-DesktopMap#956]
First off, amazing program.  Really appreciate that someone is putting time into making a program like this.
I was wondering would it be possible to implement the ability for the user to define a search path?  I'm thinking something along the lines of being able to draw a line (or polyline) on the map which then combined with the search radius would form the search path?

**Comment by macinmn** [comment]
I thought a poly area may be useful also, since I live in an area that has an L-shape that is accessible.  I decided not to submit a feature req since you can't really skip that area without implying some sort of teleporting past the unwanted area.

a linear path I think would still be useful and probably not as difficult to program.

my request though, also search related, is the ability to just cap the number of cycles to a set number, instead of in perpetuity.

**Comment by pill0ws** [comment]
i havent seen much activity with this app, it appears most Mr Christopher as well as some other of the primary contributors are focusing on the main branch here. 

https://github.com/PokemonGoMap/PokemonGo-Map

This is the more popular project and probably recieves the most functionality from contributors. This Desktop app seems like a persona lside project of Mr Christophers so I imagine at some juncture he will pull the stuf he likes best from the main project. In the mean time, this App is behind the times. I however an still using it as I am experimenting with limitations. I am not trying to farm/grind pokemon to have all of the CP's ever. I am more interested in gameplay and I really enjoy manual control of the scanner. My dream project, if I had any knowledge whatsoever of this kinda stuff, would be to turn the functionality of map scanning into a game mechanic that utilized the pokemon you have caught and provided tradeoffs and advantages to each of them in how they scanned, where they scanned, how long it took them or how far they could go, etc. I'd love this feature as a game mechanic so I basically use this app in a manner that just supplements such a feature (although I cant do a lot of things with it, I am interested in custom scan patterns as this is one of the core components to turning scan functionality into a metagame

**Comment by arbymou** [comment]
the other app may have more activity but i think thus one is more user friendly, as far as i saw most other maps require python, and requires you to use commands to run the app. this app however is much more user friendly "one click go".

**Comment by cfsterpka** [comment]
Ah - thanks for pointing that out.  I didn't even think to check the other app!
