### ISSUE TITLE
Operational but no pokemon found

### ISSUE THREAD

**Issue by cjdraeger** [mchristopher/PokemonGo-DesktopMap#957]
Hi guys, I was just looking for some help. My first scanner account got banned and I created a new one. Now when I sign in it says operational (unlike with my banned account), but I still find no pokemon while scanning. The green scanned area circles pop up, but nothing else does. I don't have any pokemon filtered.

**Comment by PraiseDuarte** [comment]
When you created your PTC account did you agree to TOS and pick your first pokemon on it as well?

**Comment by cjdraeger** [comment]
I did. I even went to a pokestop.

**Comment by PraiseDuarte** [comment]
Hmm that is weird, this hasn't happened to me before... though I've never gotten an account banned, so if it is Niantic's doing that isn't allowing you to see pokemon then maybe they are blocking the IP address.  Maybe try using a proxy, or if that doesn't work try reinstalling and clearing the cache files?

**Comment by CarstenHouweling** [comment]
My map stopped working aswell this morning.

**Comment by cjdraeger** [comment]
Do you know where the cache files are? I am struggling to find them. The uninstall and reinstall leaves the information filled in.

**Comment by Anden1980** [comment]
Same problem here.
Scanning shows no pokemons. Has stopped working within the last two hours. 
Has tried with two different PC's on different networks, and my account hasn't been banned.

What to do?
