### ISSUE TITLE
Release 0.08 JavaScript error in main.js

### ISSUE THREAD

**Issue by jameson167** [mchristopher/PokemonGo-DesktopMap#96]
![image](https://cloud.githubusercontent.com/assets/20566412/17036792/511d3912-4f7d-11e6-9719-33614fba3ba9.png)

Socket exception error after clicking "Login" via HTC on the new 0.08 release. 

Everything works for me on 0.07.

**Comment by Ruined1** [comment]
same http://imgur.com/hHpxoOX

**Comment by LitoOsaka** [comment]
I also got the same message while loggin via PTC. Google login was a blank white map with nothing load.

**Comment by zwittenauer** [comment]
Nothing is loading on the new 0.08 version, but works fine on 0.07.

- ZW

**Comment by mchristopher** [comment]
I just pulled this release down, there are some bugs I didn't catch in Windows. I'll publish it again once they are fixed.

**Comment by brettgus** [comment]
I was also running into issues with Mac OS on this release.  Also, how do we check the version number.  It looks like it reports 1.2.7 regardless of the release
