### ISSUE TITLE
Can we expect an update?

### ISSUE THREAD

**Issue by SnoopyDoo947** [mchristopher/PokemonGo-DesktopMap#960]
I'm not really tech savy so I don't really know how to setup the map myself. I was just wondering when the electron app will be updated, if at all. Thanks!

**Comment by Shogunz1** [comment]
same..

**Comment by linxspider** [comment]
https://github.com/mchristopher/PokemonGo-DesktopMap/issues/967

**Comment by linxspider** [comment]
@SnoopyDoo947 @Shogunz1 link for updating the map:

https://github.com/mchristopher/PokemonGo-DesktopMap/issues/967
