### ISSUE TITLE
[Suggestion] Hunting mode, scan only handful of selected areas

### ISSUE THREAD

**Issue by mygo89** [mchristopher/PokemonGo-DesktopMap#961]
With the stats pulling data from the map i know locations where certain mons spawns that i'm hunting for. they spawn every 2-3h. Can we have a scan mode where the map scans a handful(let's say 10 total circles) of locations over and over again?
E.g. i'm only interested in these spots http://imgur.com/a/LbtJj

**Comment by Trax3r** [comment]
in such a feature I'm interested too.
