### ISSUE TITLE
App is not detecting my location - must enter location manually.

### ISSUE THREAD

**Issue by arieljannai** [mchristopher/PokemonGo-DesktopMap#962]
Hi,

When I try using the button to detect my location or checking the option to start at my location, it doesn't work. I'm using windows 10, so I tried playing a bit with the location settings but without success.

Anyone else is also experiencing that? Maybe the app need to request location in some other way on windows 10? I also don't see the location icon on the tray.

Thanks!

**Comment by PokemongoGether** [comment]
I ALSO JUST STARTED NOTICING THIS oops caps

**Comment by joshuacane** [comment]
It always shows my location as being a mile north of my true location

**Comment by magicbrownie** [comment]
It always starts me in a different country. Most times LA

**Comment by arieljannai** [comment]
What OS all of you use?
I checked it now on another computer that runs windows 7 and the location works fine.

Maybe it's just a problem on windows 10?

**Comment by arieljannai** [comment]
why closed?
is there a solution?

**Comment by arieljannai** [comment]
nvm, I see that in the new version it was fixed :smile:

**Comment by arieljannai** [comment]
I take it back, still not working (noticed that the coordination were not deleted)
