### ISSUE TITLE
Pokemon piling up on top of each other.

### ISSUE THREAD

**Issue by MrWuffle** [mchristopher/PokemonGo-DesktopMap#963]
Just like the title says. It's like all the pokemon that spawn on the map doesn't disappear after it's gone. It's slowly turning into a clusterf*ck and it's pretty annoying, especially since you'll get notifications for all of the ones you want to be notified of, every single one of them...even when they're not actually there.

![image](https://cloud.githubusercontent.com/assets/20843138/17824424/e7ed51a6-662f-11e6-8bd0-366fe45a9cd8.png)

**Comment by fiifth** [comment]
#935 will provide you with a solution.

**Comment by starstremr** [comment]
have they figured this out yet?
