### ISSUE TITLE
Question for people getting banned 

### ISSUE THREAD

**Issue by Ang41187** [mchristopher/PokemonGo-DesktopMap#964]
First off, I  apologize because this is probably going to sound like a dumb question. I am legally blind but have enough vision to play the game and use the map. Earlier today I noticed my map wasn't scanning at all. I went to log into the PTC account and it gave me some message about the servers being humbled by incredible response. However, my husband who also has a  PTC account was able to log in just fine. I then tried logging in hrough the pokemon website on my desktop and under my account it just says "scheduled maintenance" Have I been banned, or is something else going on? Thank you for any help.

**Comment by UnderHost** [comment]
Yes, banned or IPs banned.

**Comment by Ang41187** [comment]
Thanks @UnderHost. Any way to tell which it was? (Account or IP) this is the message I got when I tried to log in 
![image](https://cloud.githubusercontent.com/assets/20845203/17829227/94ad5ca8-6665-11e6-9752-0c24fb9c48fb.jpg)
