### ISSUE TITLE
JS error in version .0.8 on login.

### ISSUE THREAD

**Issue by Kairnth** [mchristopher/PokemonGo-DesktopMap#97]
![2016-07-21 13_59_03-issues mchristopher_pokemongo-desktopmap github](https://cloud.githubusercontent.com/assets/11773720/17036879/6852b166-4f4b-11e6-80ee-21eb94d1126b.png)

Attached is a copy of the JS error I get every time I try to login in version .0.8. Other versions have all worked fine.

Running Windows 10.

**Comment by gilbarshlomo** [comment]
same to me.

**Comment by Mr10001** [comment]
same here as well

**Comment by poekrel** [comment]
I have the same error as well.

**Comment by Mr10001** [comment]
Could this be firewall related?

**Comment by mchristopher** [comment]
Duplicate of #96
