### ISSUE TITLE
Map not scanning

### ISSUE THREAD

**Issue by Ruuzha** [mchristopher/PokemonGo-DesktopMap#970]
Hi everyone,
at first sorry for my english,  I´ll try to describe my problem as good as possible .)
Few day ago my application stop working. Now everytime I log in, nothing happens.
I tried change acount, generate new API, reinstal, clean cache, change provider and nothings help.
When i start, program just don´t scan, there are no more green scan circles and console generate this message over and over.

`main.html:274 MAP: Uncaught TypeError: Cannot read property 'style' of null
main.html:168 2016-08-20 17:44:01,013 [ search_worker_0][        pgoapi][    INFO] Creating a new direct request...
2016-08-20 17:44:01,013 [ search_worker_0][        pgoapi][    INFO] Adding 'GET_MAP_OBJECTS' to RPC request including arguments

main.html:168 2016-08-20 17:44:01,013 [ search_worker_0][        pgoapi][    INFO] Execution of RPC

main.html:168 2016-08-20 17:44:01,322 [ search_worker_0][        pgoapi][    INFO] Cleanup of request!

main.html:168 2016-08-20 17:44:01,325 [ search_worker_0][        search][   ERROR] Search step 2 map parsing failed, retrying request in 30 seconds. Username: Pl1140
Traceback (most recent call last):
  File "C:\Users\Ruuzhaa\AppData\Local\pokemon\app-0.2.1\resources\app\map\pogom\search.py", line 254, in search_worker_thread
    parse_map(response_dict, step_location)
  File "C:\Users\Ruuzhaa\AppData\Local\pokemon\app-0.2.1\resources\app\map\pogom\models.py", line 326, in parse_map
    cells = map_dict['responses']['GET_MAP_OBJECTS']['map_cells']
KeyError: 'map_cells'`

In the top middle there are still "waiting"

Any helps?

Thanks a lot

**Comment by cjdraeger** [comment]
Have you tired creating a new account? Itis possible the one you were using was banned. Aslo, how did you clear your cache for this program? I'm not sure where to do that.

**Comment by Ruuzha** [comment]
I´m just dumb, catch first pokemon solved that problem.

**Comment by darkgreengoblin** [comment]
@Ruuzha what do you mean by 'catch first pokemon'?

**Comment by darkgreengoblin** [comment]
@cjdraeger I tried creating a new account, but it doesn't work either. The map still says 'Waiting.' Please help!

**Comment by outofchocolate** [comment]
If you create the account, go in, catch a pokemon and create a trainer name, and restart the map. It's how I got mine to work.

**Comment by darkgreengoblin** [comment]
@outofchocolate it actually worked!!! you're a lifesaver.. thank you so so much

**Comment by outofchocolate** [comment]
@darkgreengoblin  my pleasure! 

I sent this to niantic when I "appealed" having my lvl 20 account banned. Lot good it will do me, I'm sure.

Honestly? I'm guilty of using a third party service. I catch the pokemon myself. I buy poke balls and lures and lucky eggs. As a mom who plays with her four year old, we don't have the time or energy to search for nearby pokemon we may never find. For us, the excitement of saying "oh! look there's a (rare pokemon) around the corner, let's go get it!" is so much more fulfilling than saying "sorry bud, we couldn't find it today." I think disallowing this service for those that want to take advantage of it is short sighted.  The bot is not playing for me. I'm not collecting pokemon that I haven't thrown pokeballs at or hatching eggs that I haven't walked for. We haven't lied or cheated about our GPS location. I'm just playing with my son. I would rather start all over again with different accounts than lie to you in an appeal, to let you know that, while some users are definitely cheating, I don't consider foreknowledge of a pokemon's whereabouts to be an unfair advantage: I find it a deficit of the game. "

**Comment by darkgreengoblin** [comment]
wow @outofchocolate ! loads of respect to you

have they replied yet?

**Comment by outofchocolate** [comment]
@darkgreengoblin  Not yet. I only just sent it before I came here to comment. Thank you for saying that; I feel very strongly about this. side note: while setting up a dummy account, understand that "nianticsucksa$$" and other such variants have already been taken.

**Comment by FakacX** [comment]
Hi everybody,

i was participated with @Ruuzha  on this problem solving. We used same version of a PoGo Map client and we had same Error logs in console. This problem appeard at thuesday evening on CzechRep servers.

We tried everithing before we discover right PoGo Map setting as he said at top.

And here it is -> If you got the same error message in your Application, maybe this could help you.

1) Start with clear installation of PoGo Map client (When im writing this, is possible to download ver.0.2.1) / or you can yous your actual version but PowerShell scrip may collide with the app version (check it bellow) 

2) Read and follow instructions in this thread -> #967 (THX guys -> you made realy good job and all of you got big peace on this problem solve!)

3) I´m recommending to use for Step 2 this PowerShell script which was written by @dodsky (Thx -> worked fine for us), but if u make changes from step 2 mannualy continue by steps 5 and etc... of our manual

> Created a short powershell script that follows the steps in case I need to repeat the steps later, tested it locally and it worked. Just create a .ps1 file on windows and paste the following. Check the versions in code before blaming me. :D

`
$map_folder = "$env:LOCALAPPDATA\pokemon\app-0.2.1\resources\app\map"
$map_old_folder = "$env:LOCALAPPDATA\pokemon\app-0.2.1\resources\app\mapOld"

Rename-Item $map_folder mapOld


New-Item -ItemType directory -Path $map_folder


$clnt = new-object System.Net.WebClient
$url = "https://github.com/PokemonGoMap/PokemonGo-Map/archive/v3.1.0.zip"
$file = "$env:temp\map.zip"
$clnt.DownloadFile($url, $file)

$shell_app=new-object -com shell.application 
$zip_file = $shell_app.namespace("$file\PokemonGo-Map-3.1.0") 
$destination = $shell_app.namespace($map_folder) 
$destination.Copyhere($zip_file.items())


Copy-Item -Path "$map_old_folder\*.*" -Destination $map_folder -Recurse -Force


Copy-Item -Path "$map_old_folder\pogom\pgoapi" -Destination "$map_folder\pogom" -Recurse -Force


Remove-Item "$env:APPDATA\pokemon-go-map\pogom.db" -ErrorAction Ignore
Remove-Item "$env:APPDATA\pokemon-go-map\Cache\" -Recurse -ErrorAction Ignore
Remove-Item "$env:APPDATA\pokemon-go-map\Local Storage\" -Recurse -ErrorAction Ignore
`

4) As @Dodsky said -> Copy and paste this script in to Notepad and Save it as ".ps1" file right next by file with unofficial 3.1.0 zip which you downloaded in step 2 -> Right click on this .ps1 file and chose Run with PoweShell

5) Lets make thing happend and after continue with usually known procedure (generate your new API key and Create fake account on PTC) -> we recommend to use fake Google mail and PCT accounts!.

6) After you successfully create and verifies your new PTC account go in to the account setting in PTC portal and agree with Therm Of Use (TOS)

7) Log in to game and catch one Pokemon (as usually we recommend to use different mobile/tablet device then the device where you want to play the game, Niantic can catch you and ban can comes...)

8) Log in to PoGo Map application -> if the status is Operating you made it!

So it looks like Niantic made some changes in the game mechanics without some hard changes in game API. They just let the new account search for pokemons after a first pokemon pick in the game. It can be a rly good tactic when you want to block fakers. 

Thx @Ruuzha and everybody in the other threads for they´r  job. 

We was pretty sad without the map.

Good night
