### ISSUE TITLE
map gives an error message and keeps on saying 'Waiting'  

### ISSUE THREAD

**Issue by darkgreengoblin** [mchristopher/PokemonGo-DesktopMap#971]
Since yesterday I've been getting the following error message. The map would open up, but wouldn't scan. On top of the map, where normally 'Operational' used to be, there is 'Waiting' and it wouldn't change. I tried logging in with a different PTC account, same thing :( please help!

<img width="417" alt="error message" src="https://cloud.githubusercontent.com/assets/21145641/17832933/e0df73e0-66dd-11e6-98f2-cd439dc28f9c.PNG">

**Comment by NicolasKulka** [comment]
Same issue !

**Comment by darkgreengoblin** [comment]
@NicolasKulka  just login to Pokemon GO with the account that you used to log in to the live map, catch the starter pokemon, and try logging in to the map with that account again.. it worked for me
hope it works for you as well
good luck! 

(thanks to @ruuzha and @outofchocolate for the solution)

**Comment by NicolasKulka** [comment]
Yes it's ok, thank you !!
