### ISSUE TITLE
How do I clear the cache?

### ISSUE THREAD

**Issue by cjdraeger** [mchristopher/PokemonGo-DesktopMap#972]
Hey guys, I was just looking for help on where to locate the cache for this program so I can clear it. Uninstall/reinstall doesn't do the trick.

**Comment by guyreese** [comment]
I'm pretty sure you have to clear out the app data. In Windows, it's C:\Users\mrparker\AppData\Roaming\pokemon-go-map in OS X, it's probably in Application Data under your user Library folder. I'm not sure what all needs to be deleted to clear the cache (that's why I'm on here actually).

**Comment by drdread66** [comment]
If you're on a Mac, exit the map application, go to ~/Library/Application Support/pokemon-go-map and delete pogom.db. Then re-start the map application and all the bogus data will be gone...
