### ISSUE TITLE
Updated pokemonGo-DesktopMap over here (Windows, only .exe)

### ISSUE THREAD

**Issue by fiifth** [mchristopher/PokemonGo-DesktopMap#974]
https://github.com/fiifth/PokemonGo-DesktopMap/releases/tag/v0.2.1-map-v3.1.0

**For other operaton systems follow the instructions over here: #967.**

*(Edit: If you already followed those instructions there is no point in installing this version since it will give you the same result)*

**Comment by secondhandnudes** [comment]
Thanks so much for this. One question: is there any added functionality in this if I've already done the workaround you detailed in issue #967?

**Comment by fiifth** [comment]
@secondhandnudes No, this is simply an easier way of updating your map.

**Comment by Shogunz1** [comment]
Such a great job. Ty for this.

**Comment by fiifth** [comment]
Well all credit goes to mchristopher. The exe basically creates itself :+1:

**Comment by conklin75** [comment]
Thanks for this and thanks to mchristopher for the desktop app if it weren't for these I would have quit this game long ago

**Comment by mchristopher** [comment]
@fiifth I'm working on a new build right now that doesn't require me to maintain a special fork of the main repo. Will probably take another day or so...

**Comment by zegmatje** [comment]
Thanks for your work and effort in updating it, but sadly enough it isn't functioning with me... It's stuck of Loading - please wait (white screen-black text). I've done the clear cache.

**Comment by drippybutt** [comment]
Does this new version take care of the 400 + hour bug?

**Comment by rait0kun** [comment]
keep loading please wait screen
help

**Comment by fiifth** [comment]
@mchristopher That's great news, looking forward to it!

@zegmatje @rait0kun Could you try to go to "C:\Users\[your username]\AppData\Roaming" and delete the "pokemon-go-map" folder entirely?

@drippybutt Yes this takes care of that bug.

I'll Close the issue since a better/official update is incoming.
