### ISSUE TITLE
Anyone else with Ubuntu 14.04 issues

### ISSUE THREAD

**Issue by JonTheGreek** [mchristopher/PokemonGo-DesktopMap#975]
I cant get the server started. I had the previous versions working fine but I installed the new one and cannot get past the "Loading, please wait..." screen without first clicking the "Follow this guide to generate your API key." Don't know what I am doing wrong here... Semi-n00b to Ubuntu, only a year under my belt :\

**Comment by enigmaticmindx** [comment]
open a terminal 
sudo apt-get install python-dev
then 
sudo pip install xxhash

This worked for me on 14.04
