### ISSUE TITLE
Maps works for a while, 1 - 2 hours later, the search doesn't work

### ISSUE THREAD

**Issue by kraoux** [mchristopher/PokemonGo-DesktopMap#980]
As in the title, the scan works perfectly, but after a while the scan stops and i have to exit and re-open the program. Also, can you set up a permanent web link so it doesn't change everytime you restart the app and toggle mobile mode?

**Comment by Mirx** [comment]
1) Use the search function
2) Use PTC account to login instead of Google
3) Forward an external port to your internal ip:8000

**Comment by fanbian75** [comment]
Sorry for english, but after 1-2 hour (no action on pc, i go outside for pokemon) the scan stop and i have to exit and re-open the program. Help please.
