### ISSUE TITLE
Pokemon with glitched time remaining

### ISSUE THREAD

**Issue by neta1o** [mchristopher/PokemonGo-DesktopMap#981]
Some pokemon, on map, show 300+hours remaining and won't go away

![capture](https://cloud.githubusercontent.com/assets/16583852/17837839/3d45fcd8-677b-11e6-985c-c240483df121.PNG)

**Comment by Mirx** [comment]
Use the search, multiple issues exist describing this issue and fixes.

**Comment by neta1o** [comment]
Found a solution here that seems to work.  https://github.com/mchristopher/PokemonGo-DesktopMap/issues/935
