### ISSUE TITLE
Port Issue Running Multiple Instances

### ISSUE THREAD

**Issue by datdominator** [mchristopher/PokemonGo-DesktopMap#982]
Hi all, I am trying to run multiple instance but when I open another version of the program and try to run it it gets rejected with a javascript error due to the port already being in use (by the other instance). I tried running the line in cmd.exe to update the port in a copied version but that didn't have the desired effect. Any workaround for this?

Thanks!

**Comment by linxspider** [comment]
just ignore the warning. it doesn't really matter if you connect remotely to anyone of them since the updates from all the scanners will appear on all the  maps. from what i see, every new instance opens additional port starting from port 8001 (so instance 2 will be 8002, port 3 8003 etc)

**Comment by Butom** [comment]
i opened ports, use different acc from google and still only one window is working, if i refresh the second window starts and first stops working

**Comment by datdominator** [comment]
Sorry I may not have been clear in my initial post. It isn't just a warning, it errors out so I can't do anything and doesn't load.
