### ISSUE TITLE
How does "scan follows location" work?

### ISSUE THREAD

**Issue by cason444** [mchristopher/PokemonGo-DesktopMap#983]
I don't think this feature has worked for me. The button on the map that looks like a bullseye just blinks when I tap it. I thought this would be a "snap to location" tool.

**Comment by Mirx** [comment]
Yes, but only on devices that have GPS info. For example, from your PC it will just use the IP address geo-location that happens to be administered.

**Comment by cason444** [comment]
Closing. For those who have the same issue, I had five my browser permission to my location.
