### ISSUE TITLE
ngrok tunnel - how to add an authtoken??

### ISSUE THREAD

**Issue by Galastorm** [mchristopher/PokemonGo-DesktopMap#984]
I'm trying to access the server while out and about and I'm running in to the limit of an unauthorised tunnel.  I have an authtoken from ngrok, and have been trying to find an example of how to add the token to the code that creates the tunner but havn't been able to.

Could someone post which file to change and an example of where it needs changing please?

Thanks in advance.

**Comment by starstremr** [comment]
go to the command prompt og the folder you have ngrok and type the following
ngrok authtoken your token here it will make a config file for ngrok in the same folder.

**Comment by FamoNd** [comment]
> go to the command prompt of the folder that you have ngrok.exe in  and type the following
> "ngrok authtoken your token here" minus the quotes. it will make a config file for ngrok in the same folder.
> 
> Example - ngrok authtoken 3c45KbrLJ7BMxSsCH3wZd_5QTaP6mPRu1L56m2sW3aE
> 

do someone know how to install authtoken in termux?
"ERROR:  Unrecognized command: config"
