### ISSUE TITLE
how can i use one map with multiple instances on multiplate PC's (database share?)

### ISSUE THREAD

**Issue by madkeeper89** [mchristopher/PokemonGo-DesktopMap#985]
Hey there,

i want to build a pokemon live map for our whole city together with my friends. 
muliple instances on a single PC works,
we tried out to use the google API key on two PC's to connect our search results on the web-map.
and it doesnt works :(

i think the answer is to share the database.

i covert the pogom.db (sqllite) to my web mysql server. next i setup the config.ini like this:

auth-service:ptc          # ptc (default) or google
username:XXXXXXXX
password:YYYYYYYYY

db-type:mysql        # sqlite (default) or mysql
db-host:sql7.ZZZZZZZZZZZZZ.com 	              # required for mysql
db-name:sqlxxxxxxxxx              # required for mysql
db-user:sqlxxxxxxxxxxx            # required for mysql
db-pass:xxxxxxxxxxxxx              # required for mysql

gmaps-key:XXXXXXXXXXXXXXX            # your Google Maps API key

how ever, it still dont work.

maybe someone can tell me if the way of database sharing could work and how can i configure that ?

thanks guys :)

**Comment by Goshi45** [comment]
You are correct, sharing the database is the answer and you did it correctly.

What do you mean by "it still dont work" ?

**Comment by Quatitos** [comment]
8th Ilock888 8hUintah Ilock888 8hUintah!ñ ñin ñ i

**Comment by Quatitos** [comment]
8th Ilock888 8hUintah Ilock888 8hUintah!ñ ñin ñ i

**Comment by madkeeper89** [comment]
map with multiple instances on multiplate PC's = database share works without any issue.

actualy run 8 instances on 3 PCs with 1 map.

thread closed.
