### ISSUE TITLE
pokemon with extremely high spawn timer

### ISSUE THREAD

**Issue by RyuTLawliet** [mchristopher/PokemonGo-DesktopMap#986]
anyone else having the issue where pokemon have timers that are like 300+hrs. most of my map is full of them and to really use it i have to remove them all. and they reappear after i refresh or close and open the app. 
any help to fix this permanently would be much appreciated.
thank you and have a good day.
@RTL

**Comment by danieleserra** [comment]
i have the same problem

**Comment by FirelordPhoenix** [comment]
#967

**Comment by ultimate2106** [comment]
#934
