### ISSUE TITLE
Tried update the map oldMap thing, now dead

### ISSUE THREAD

**Issue by freddieboy8123** [mchristopher/PokemonGo-DesktopMap#989]
So i tried the map OldMap help someone posted to get rid of all the 400h spawns.
Not i cant use the app anymore. Tried to delete and reinstall but it didnt work.

Says Waiting now :(

I rather have it working with a lot of error pokemons that not working at all ;(

**Comment by likethemouse** [comment]
I woke up this morning and tried (without messing with anything) and all I'm getting is "Waiting" aswell... Hopefully this isn't permanent!!!!! :(

**Comment by romanticheart** [comment]
This means that the account you used to sign into the app got banned. Create a new account and it will be fixed.

**Comment by starstremr** [comment]
try using a vpn

**Comment by likethemouse** [comment]
Weird thing is that's what I thought so I created another one and it didn't work... But than I tried it again just now and it did so.. Thanks yeah cheers thanks
