### ISSUE TITLE
is the map down?

### ISSUE THREAD

**Issue by furax187** [mchristopher/PokemonGo-DesktopMap#990]
i was using it, and all of a sudden it doesnt work anymore, it says "waiting" now.
Any1else has this problem?

**Comment by starstremr** [comment]
try a vpn

mine is working

**Comment by furax187** [comment]
i see what the problem is, my acc got banned by niantic, was level 6 anyway, so cba, just used a new acc now, logged in and it works

**Comment by BadKarmaa** [comment]
Tried creating a new account, still not working for me. keep getting "waiting". my account on PTC has scheduled maintenance against it

**Comment by starstremr** [comment]
last i knew they were banning ip address's

**Comment by BadKarmaa** [comment]
Created another account (third one) and used it to catch the starter pokemon. Now Operational!

**Comment by demokan77** [comment]
Hello, you think it's possible that Niantic can ban our ip / iphone if we use this appli.
My first account (only for the appli) has been banned and I have created another one

**Comment by Optimus-Prance** [comment]
created another account and caught the starter but still stuck on waiting for me :\

**Comment by starstremr** [comment]
how many time do i have to repeat my self i have done the VPN thing. if i log in with the account without vpn it says waiting but if i use a vpn it works.

**Comment by Optimus-Prance** [comment]
ahh yeah, that would make sense actually...guess I better find one

**Comment by Optimus-Prance** [comment]
if anyone reads this and has any suggestions for a decent vpn service id be eternally grateful, I can't seem to get any that I have to work, yet at least

**Comment by starstremr** [comment]
i use Private internet access

https://www.privateinternetaccess.com/pages/buy-vpn/?gclid=CjwKEAjwxeq9BRDDh4_MheOnvAESJABZ4VTqXCXhOg1XuGIBs4GbAoQbHzw1iDljZHw1o0282FUWoxoCY-Hw_wcB

**Comment by Shogunz1** [comment]
starstremr I just got downloaded Private Internet Access but now when I have it active pogo goes to 'waiting'. I turn PIA off and its Operational. Is there a setting im missing here?

**Comment by Shogunz1** [comment]
Yeah when my VPN is on I can't log into the game either

**Comment by gamerbabe001** [comment]
same "waiting..." issue here. tried to make new acct and it didnt work.

**Comment by BadKarmaa** [comment]
Okay so if you want to test this theory simpley create a hot spot with your
phone and connect your PC/notebook to your phone. You will have a new IP
address! Make sure you are using your phone data!

I already tried this and  was getting the same result. I.e. waiting.

**Comment by Optimus-Prance** [comment]
oh, seems it was an issue with my google account, no issue my ip address at least

thanks to those who tried to help anyhow!
