### ISSUE TITLE
App doesn't work anymore

### ISSUE THREAD

**Issue by manojrajput** [mchristopher/PokemonGo-DesktopMap#995]
Since morning i am getting "waiting" on top-center where it was operational earlier. Is something changed ? or Niantic blocked this one as well ?? Please let me know..

**Comment by galaxy9999** [comment]
nah, your account is banned.

**Comment by manojrajput** [comment]
ohhh... sad how have to create another one...

**Comment by trolund** [comment]
I have the same problem, but my account was created this morning! - can they  will have banned me on my first try on login?

**Comment by trolund** [comment]
please help!! what can i do?

**Comment by Sixpax** [comment]
Did you actually login to the game with the new account and 'catch' the starter pokemon?  get to the point where you set your nickname in game and try again

**Comment by trolund** [comment]
you miss understand, it is det scanner i can get to work. it just saying "waiting" and then "possible ban" but i have tried with both a new api key and new ptc user but noting works! :(

**Comment by Sixpax** [comment]
Yes, with your new PTC user did you login to the game and "play" to the point of getting the starter pokemon and setting the nickname in game.  If you don't do this, your new account won't work either.
