### ISSUE TITLE
Got Java error...

### ISSUE THREAD

**Issue by manojrajput** [mchristopher/PokemonGo-DesktopMap#997]
Got Java error... Please help to resolve it. Application doesn't run.

![image](https://cloud.githubusercontent.com/assets/20891925/17882796/50a7396a-692c-11e6-856a-7b40eda69e72.png)

**Comment by cooler67** [comment]
I get the same error with the newest version.. I had just gotten rid of the error and the 500 hour bug, and now the newest version is giving me this error everytime I open the ap. Minor bug though. I just mute the pc when I open it.
